# FineTuneHuBERTV1_Optuna_Final.ipynb

Notebook utama HuBERT+LoRA pada strict split sebagai pembanding adil terhadap WavLM.
Perlakuan dibuat sama dengan WavLM: loss MAE/L1, Optuna 50 trial, final 10 seeds, early stopping, metric selection berdasarkan validation S = 1 - MAE, serta export tabel/figure lengkap.

Notebook ini **tidak melakukan download dataset**. Jalankan sanity notebook terlebih dahulu untuk menyiapkan `data/manifest_strict_vast.csv`.

## Cara menjalankan notebook utama via tmux + papermill

Notebook utama mengasumsikan `data/manifest_strict_vast.csv` dan folder audio sudah tersedia dari sanity notebook. Jika `manifest_strict_vast.csv` belum ada tetapi `manifest_strict.csv` dan audio sudah tersedia, notebook akan mencoba membangunnya otomatis.

Dari root workspace di Vast.ai:

```bash
tmux new -s hubert_main
cd /workspace/finetunev2
mkdir -p logs
set -o pipefail
PROJECT_ROOT=/workspace/finetunev2 papermill notebooks/FineTuneHuBERTV1_Optuna_Final.ipynb notebooks/FineTuneHuBERTV1_Optuna_Final_executed.ipynb --log-output 2>&1 | tee logs/papermill_stdout.log
```

Detach tanpa mematikan proses:

```text
Ctrl+b lalu d
```

Cek progress:

```bash
tmux attach -t hubert_main
# atau, untuk log ringkas yang ditulis langsung oleh notebook:
cd /workspace/finetunev2
tail -f logs/train_live.log
# atau, untuk stdout papermill lengkap:
cd /workspace/finetunev2
tail -f logs/papermill_stdout.log
```

Catatan aman:

- Jangan klik Restart Kernel, Interrupt Kernel, atau Run All pada notebook yang sedang dieksekusi oleh papermill.
- Browser/Jupyter boleh dibuka untuk melihat file output, tetapi jangan menjalankan ulang cell pada notebook yang sedang diproses.
- File logs/train_live.log berisi log ringkas dari dalam notebook.
- File logs/papermill_stdout.log berisi output lengkap dari proses papermill.
- Jika notebook utama selesai dengan sukses, hasil executed notebook akan tersimpan sebagai: 
```text
notebooks/FineTuneHuBERTV1_Optuna_Final_executed.ipynb
```

In [1]:
# =========================
# Optional dependency check / install
# =========================
# Set AUTO_INSTALL=False if you want the notebook to fail fast when a package is missing.
AUTO_INSTALL = False

import importlib
import subprocess
import sys

# import_name -> pip_name
REQUIRED = {
    "numpy": "numpy",
    "pandas": "pandas",
    "matplotlib": "matplotlib",
    "tqdm": "tqdm",
    "torch": "torch",
    "soundfile": "soundfile",
    "librosa": "librosa",
    "sklearn": "scikit-learn",
    "optuna": "optuna",
    "transformers": "transformers",
    "peft": "peft",
    "IPython": "ipython",
}

missing = []
for import_name, pip_name in REQUIRED.items():
    try:
        importlib.import_module(import_name)
    except Exception:
        missing.append(pip_name)

print("Missing packages:", missing)
if missing and AUTO_INSTALL:
    cmd = [sys.executable, "-m", "pip", "install", "-U"] + missing
    print("Installing:", " ".join(cmd))
    subprocess.check_call(cmd)
elif missing:
    raise RuntimeError(f"Missing packages: {missing}")
else:
    print("All required packages are available.")

Missing packages: []
All required packages are available.

In [2]:
# =========================
# Imports and logging behavior
# =========================
import os
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
import sys
import gc
import json
import math
import time
import random
import shutil
import warnings
import zipfile
import tarfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from contextlib import nullcontext

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# IMPORTANT:
# Use terminal tqdm instead of notebook widget tqdm.
# This keeps monitoring visible in tmux/papermill and avoids
# application/vnd.jupyter.widget-view+json outputs in the saved notebook.
from tqdm.std import tqdm
from IPython.display import display

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

import soundfile as sf
import librosa

from sklearn.metrics import r2_score

import optuna
from optuna.trial import TrialState

from transformers import AutoFeatureExtractor, AutoModel, get_linear_schedule_with_warmup
from peft import LoraConfig, get_peft_model

warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)

print("Python:", sys.version)
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("CUDA device:", torch.cuda.get_device_name(0))

Python: 3.14.3 | packaged by conda-forge | (main, Feb  9 2026, 21:56:02) [GCC 14.3.0]
Torch: 2.11.0+cu130
CUDA available: True
CUDA device: NVIDIA RTX A6000

In [3]:
# =========================
# Root and folder architecture
# =========================
# If this notebook is run from the `notebooks/` folder, PROJECT_ROOT becomes its parent.
# You can override by setting env var PROJECT_ROOT=/workspace/your_project.
_cwd = Path.cwd().resolve()
PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", str(_cwd))).resolve()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

ROOT = PROJECT_ROOT
NOTEBOOKS = ROOT / "notebooks"
DATA = ROOT / "data"

OUTPUTS = ROOT / "outputs"
CHECKPOINTS = ROOT / "checkpoints"
LOGS = ROOT / "logs"
CACHE = ROOT / "cache"

OUT_OPTUNA_STUDY = OUTPUTS / "optuna_study"
OUT_OPTUNA_TRIALS = OUTPUTS / "optuna_trials"
OUT_FINAL_RUNS = OUTPUTS / "final_runs"
OUT_FINAL_AGG = OUTPUTS / "final_aggregate"
OUT_FINAL_SELECTED = OUTPUTS / "final_selected"
OUT_APPENDIX = OUTPUTS / "appendix_ready"
OUT_TABLES = OUTPUTS / "tables"
OUT_FIGURES = OUTPUTS / "figures"

CKPT_OPTUNA_TRIALS = CHECKPOINTS / "optuna_trials"
CKPT_FINAL_RUNS = CHECKPOINTS / "final_runs"
CKPT_FINAL_SELECTED = CHECKPOINTS / "final_selected"
CKPT_SELECTED_BEST = CKPT_FINAL_SELECTED / "best_val"
CKPT_SELECTED_MEDIAN = CKPT_FINAL_SELECTED / "median"
CKPT_SELECTED_ENSEMBLE = CKPT_FINAL_SELECTED / "ensemble_sources"

HF_CACHE = CACHE / "hf_cache"
TMP_CACHE = CACHE / "tmp"

for p in [
    ROOT, NOTEBOOKS, DATA, OUTPUTS, CHECKPOINTS, LOGS, CACHE,
    OUT_OPTUNA_STUDY, OUT_OPTUNA_TRIALS, OUT_FINAL_RUNS, OUT_FINAL_AGG,
    OUT_FINAL_SELECTED, OUT_APPENDIX, OUT_TABLES, OUT_FIGURES,
    CKPT_OPTUNA_TRIALS, CKPT_FINAL_RUNS, CKPT_FINAL_SELECTED,
    CKPT_SELECTED_BEST, CKPT_SELECTED_MEDIAN, CKPT_SELECTED_ENSEMBLE,
    HF_CACHE, TMP_CACHE,
]:
    p.mkdir(parents=True, exist_ok=True)

os.environ["HF_HOME"] = str(HF_CACHE)
os.environ["TRANSFORMERS_CACHE"] = str(HF_CACHE)
os.environ["HF_HUB_CACHE"] = str(HF_CACHE)

STUDY_LOG = LOGS / "study_run.log"
TRIAL_FAIL_LOG = LOGS / "trial_failures.jsonl"
LIVE_LOG = LOGS / "train_live.log"

print("ROOT:", ROOT)
print("DATA:", DATA)
print("OUTPUTS:", OUTPUTS)
print("CHECKPOINTS:", CHECKPOINTS)
print("LOGS:", LOGS)

ROOT: /workspace/hubert_finetune
DATA: /workspace/hubert_finetune/data
OUTPUTS: /workspace/hubert_finetune/outputs
CHECKPOINTS: /workspace/hubert_finetune/checkpoints
LOGS: /workspace/hubert_finetune/logs

In [4]:
# =========================
# Global config — MAIN HuBERT+LoRA experiment
# =========================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
AMP_ENABLED = (DEVICE == "cuda")

MODEL_NAME = "facebook/hubert-base-ls960"
EXPERIMENT_NAME = "HuBERT_LoRA_Strict"
SR_TARGET = 16000
MAX_SEC = 15.0
MAX_LEN = int(SR_TARGET * MAX_SEC)

# Manifest columns
SOURCE_AUDIO_COL = "audio_out"
AUDIO_COL = "audio_path"
CLIP_ID_COL = "clip_id"
GROUP_ID_COL = "group_id"
SPLIT_COL = "split_strict"

TRAIN_SPLIT_VALUE = "train"
VAL_SPLIT_VALUE = "val"
TEST_SPLIT_VALUE = "test"

LABEL_COLS = ["extraversion", "neuroticism", "agreeableness", "conscientiousness", "openness"]

# Fixed training config: kept aligned with WavLM notebook for fair comparison.
BATCH_SIZE = 40
GRAD_ACCUM_STEPS = 1
MAX_EPOCHS = 100
PATIENCE = 5
MIN_DELTA = 0.0
GRAD_CLIP = 1.0
HEAD_DROPOUT = 0.1

NUM_WORKERS = 0
PIN_MEMORY = (DEVICE == "cuda")
PERSISTENT_WORKERS = False

# Optuna: kept aligned with WavLM notebook.
N_TRIALS = 50
OPTUNA_TOPK = 5
OPTUNA_SEED = 42
SELECTION_METRIC = "S"
STUDY_NAME = "hubert_lora_strict_optuna"
STUDY_DB = OUT_OPTUNA_STUDY / "hubert_lora_optuna.db"
STUDY_STORAGE = f"sqlite:///{STUDY_DB}"

# Final runs: same seeds as WavLM.
FINAL_SEEDS = [42, 52, 62, 72, 82, 92, 102, 112, 122, 132]
N_FINAL_RUNS = len(FINAL_SEEDS)

DISPLAY_TRIAL_PLOTS = False
DISPLAY_FINAL_RUN_PLOTS = False
DISPLAY_SUMMARY_PLOTS = True

PRUNER = optuna.pruners.MedianPruner(
    n_startup_trials=10,
    n_warmup_steps=8,
    interval_steps=1,
    n_min_trials=5,
)


print("DEVICE:", DEVICE)
print("AMP_ENABLED:", AMP_ENABLED)
print("MODEL_NAME:", MODEL_NAME)
print("BATCH_SIZE:", BATCH_SIZE)
print("MAX_EPOCHS:", MAX_EPOCHS)
print("PATIENCE:", PATIENCE)
print("N_TRIALS:", N_TRIALS)
print("FINAL_SEEDS:", FINAL_SEEDS)
assert GRAD_ACCUM_STEPS == 1, "Notebook ini belum mengimplementasikan gradient accumulation; pertahankan GRAD_ACCUM_STEPS=1."
print("STUDY_STORAGE:", STUDY_STORAGE)

DEVICE: cuda
AMP_ENABLED: True
MODEL_NAME: facebook/hubert-base-ls960
BATCH_SIZE: 40
MAX_EPOCHS: 100
PATIENCE: 5
N_TRIALS: 50
FINAL_SEEDS: [42, 52, 62, 72, 82, 92, 102, 112, 122, 132]
STUDY_STORAGE: sqlite:////workspace/hubert_finetune/outputs/optuna_study/hubert_lora_optuna.db

In [5]:
# =========================
# Utilities
# =========================
def log_line(msg: str, log_path: Optional[Path] = None, also_print: bool = True):
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    if also_print:
        print(line, flush=True)
    if log_path is not None:
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(line + "\n")


def section(title: str):
    bar = "=" * 80
    log_line(f"\n{bar}\n{title}\n{bar}", LIVE_LOG)


def save_text(text: str, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def append_jsonl(obj: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(make_json_safe(obj), ensure_ascii=False, allow_nan=False) + "\n")


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_json_safe(obj):
    """Convert numpy/pandas/path/torch objects into JSON-serializable Python objects."""

    if obj is None:
        return None

    if isinstance(obj, (str, bytes)):
        return obj.decode("utf-8", errors="replace") if isinstance(obj, bytes) else obj

    if isinstance(obj, (bool, np.bool_)):
        return bool(obj)

    if isinstance(obj, Path):
        return str(obj)

    if isinstance(obj, (np.integer,)):
        return int(obj)

    if isinstance(obj, int):
        return obj

    if isinstance(obj, (np.floating, float)):
        val = float(obj)
        return val if np.isfinite(val) else None

    if isinstance(obj, torch.Tensor):
        return make_json_safe(obj.detach().cpu().tolist())

    if isinstance(obj, np.ndarray):
        return make_json_safe(obj.tolist())

    if isinstance(obj, pd.Timestamp):
        return obj.isoformat()

    if isinstance(obj, pd.Series):
        return make_json_safe(obj.to_dict())

    if isinstance(obj, pd.DataFrame):
        return make_json_safe(obj.to_dict(orient="records"))

    if isinstance(obj, dict):
        return {str(k): make_json_safe(v) for k, v in obj.items()}

    if isinstance(obj, (list, tuple, set)):
        return [make_json_safe(v) for v in obj]

    try:
        if pd.isna(obj):
            return None
    except Exception:
        pass

    return obj


def save_json(obj: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(make_json_safe(obj), f, indent=2, ensure_ascii=False, allow_nan=False)
        

def save_csv(df: pd.DataFrame, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


def copy_if_exists(src: Path, dst: Path):
    if src.exists():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        return True
    return False

def safe_torch_load(path: Path, map_location=None):
    """Load checkpoints robustly across PyTorch versions."""
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)


def safe_to_float(x):
    try:
        if x is None:
            return np.nan
        return float(x)
    except Exception:
        return np.nan


def gpu_flush(reset_peak: bool = True):
    gc.collect()
    plt.close("all")
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        try:
            torch.cuda.ipc_collect()
        except Exception:
            pass
        try:
            torch.cuda.synchronize()
        except Exception:
            pass
        if reset_peak:
            try:
                torch.cuda.reset_peak_memory_stats()
            except Exception:
                pass


def del_and_flush(*objs):
    for obj in objs:
        try:
            del obj
        except Exception:
            pass
    gpu_flush()


def print_gpu_memory(prefix="GPU"):
    if not torch.cuda.is_available():
        return
    allocated = torch.cuda.memory_allocated() / (1024 ** 3)
    reserved = torch.cuda.memory_reserved() / (1024 ** 3)
    log_line(f"[{prefix}] allocated={allocated:.2f} GB | reserved={reserved:.2f} GB", LIVE_LOG)

section("Utilities loaded")

[2026-05-28 20:03:08]
================================================================================
Utilities loaded
================================================================================

In [6]:
import transformers, peft, sklearn, librosa, optuna
env_info = {
    "python": sys.version,
    "torch": torch.__version__,
    "transformers": transformers.__version__,
    "peft": peft.__version__,
    "sklearn": sklearn.__version__,
    "librosa": librosa.__version__,
    "optuna": optuna.__version__,
    "cuda_available": torch.cuda.is_available(),
    "cuda_device": torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
}
save_json(env_info, OUT_TABLES / "environment_info.json")

In [7]:
# =========================
# Prepare manifest_strict_vast.csv and audit strict split
# =========================
section("Cell | Prepare manifest_strict_vast.csv and audit split")

MANIFEST = DATA / "manifest_strict.csv"
MANIFEST_VAST = DATA / "manifest_strict_vast.csv"


def find_audio_dir(data_dir: Path) -> Path:
    preferred = [
        data_dir / "preprocessed_full" / "preprocessed_full",
        data_dir / "preprocessed_full",
    ]
    candidates = []
    for p in preferred:
        if p.exists() and p.is_dir():
            count = len(list(p.rglob("*.wav")))
            if count > 0:
                candidates.append((count, p))
    # Fallback: search directories containing wav files.
    for p in data_dir.rglob("*"):
        if p.is_dir():
            try:
                count = len(list(p.glob("*.wav")))
            except Exception:
                count = 0
            if count > 0:
                candidates.append((count, p))
    if not candidates:
        raise FileNotFoundError(f"No directory containing .wav files found under {data_dir}")
    candidates = sorted(set(candidates), key=lambda x: x[0], reverse=True)
    log_line("Audio dir candidates:", LIVE_LOG)
    for count, p in candidates[:10]:
        log_line(f"- {p} | wav_count={count}", LIVE_LOG)
    selected = candidates[0][1]
    expected = data_dir / "preprocessed_full" / "preprocessed_full"
    if expected.exists() and expected.is_dir():
        expected_count = len(list(expected.rglob("*.wav")))
        if expected_count > 0 and selected.resolve() != expected.resolve():
            log_line(
                f"[WARN] Auto-selected audio dir differs from WavLM expected path. "
                f"selected={selected}, expected={expected}. Using expected path for fairness.",
                LIVE_LOG,
            )
            selected = expected

    log_line(f"Final selected AUDIO_DIR: {selected}", LIVE_LOG)
    return selected


def normalize_split_values(df_: pd.DataFrame) -> pd.DataFrame:
    df_ = df_.copy()
    df_[SPLIT_COL] = df_[SPLIT_COL].astype(str).str.strip().str.lower()
    mapping = {
        "validation": "val",
        "valid": "val",
        "dev": "val",
        "train_strict": "train",
        "val_strict": "val",
        "validation_strict": "val",
        "test_strict": "test",
    }
    df_[SPLIT_COL] = df_[SPLIT_COL].replace(mapping)
    return df_


def build_manifest_vast(force_rebuild: bool = True) -> pd.DataFrame:
    assert MANIFEST.exists(), f"Manifest not found: {MANIFEST}"
    audio_dir = find_audio_dir(DATA)
    log_line(f"Selected AUDIO_DIR: {audio_dir}", LIVE_LOG)

    dfm = pd.read_csv(MANIFEST)
    assert SPLIT_COL in dfm.columns, f"Missing split column {SPLIT_COL}. Columns: {dfm.columns.tolist()}"
    assert CLIP_ID_COL in dfm.columns, f"Missing clip column {CLIP_ID_COL}"
    assert GROUP_ID_COL in dfm.columns, f"Missing group column {GROUP_ID_COL}"
    missing_labels = [c for c in LABEL_COLS if c not in dfm.columns]
    assert not missing_labels, f"Missing label columns: {missing_labels}"

    dfm = normalize_split_values(dfm)

    wav_files = list(audio_dir.rglob("*.wav"))
    wav_by_name = {p.name: p for p in wav_files}
    wav_by_stem = {p.stem: p for p in wav_files}
    log_line(f"Indexed wav files: {len(wav_files)}", LIVE_LOG)

    def resolve_audio(row):
        names = []
        if SOURCE_AUDIO_COL in row.index:
            raw = str(row[SOURCE_AUDIO_COL])
            if raw and raw.lower() != "nan":
                names.append(Path(raw).name)
                names.append(Path(raw).stem)
        clip_id = str(row[CLIP_ID_COL])
        names.extend([clip_id, f"{clip_id}.wav", Path(clip_id).stem, f"{Path(clip_id).stem}.wav"])
        for name in names:
            if name in wav_by_name:
                return str(wav_by_name[name])
            if name in wav_by_stem:
                return str(wav_by_stem[name])
        return str(audio_dir / (Path(str(row[CLIP_ID_COL])).stem + ".wav"))

    dfm[AUDIO_COL] = dfm.apply(resolve_audio, axis=1)
    exists = dfm[AUDIO_COL].apply(lambda s: Path(s).exists())
    missing_audio = dfm.loc[~exists, [CLIP_ID_COL, GROUP_ID_COL, SPLIT_COL, AUDIO_COL]].copy()
    if len(missing_audio):
        missing_csv = DATA / "manifest_missing_audio.csv"
        save_csv(missing_audio, missing_csv)
        display(missing_audio.head(10))
        raise FileNotFoundError(f"Missing audio: {len(missing_audio)}. Saved list to {missing_csv}")

    save_csv(dfm, MANIFEST_VAST)
    log_line(f"Saved manifest: {MANIFEST_VAST} | rows={len(dfm)}", LIVE_LOG)
    return dfm


def audit_manifest(df_: pd.DataFrame, out_dir: Path) -> pd.DataFrame:
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    def add(check, value, status, detail=""):
        rows.append({"check": check, "value": value, "status": status, "detail": detail})

    required = [CLIP_ID_COL, GROUP_ID_COL, AUDIO_COL, SPLIT_COL] + LABEL_COLS
    missing = [c for c in required if c not in df_.columns]
    add("required_columns_missing", len(missing), "PASS" if not missing else "FAIL", ", ".join(missing))

    split_counts = df_[SPLIT_COL].value_counts(dropna=False).to_dict()
    add("split_counts", json.dumps(split_counts), "PASS", "")

    audio_exists = df_[AUDIO_COL].apply(lambda s: Path(str(s)).exists())
    add("audio_exists", f"{int(audio_exists.sum())}/{len(audio_exists)}", "PASS" if audio_exists.all() else "FAIL", "")

    label_nan = int(df_[LABEL_COLS].isna().sum().sum())
    add("label_nan_count", label_nan, "PASS" if label_nan == 0 else "FAIL", "")

    clip_unique = df_[CLIP_ID_COL].is_unique
    add("clip_id_unique", bool(clip_unique), "PASS" if clip_unique else "FAIL", "")

    subsets = {name: set(df_.loc[df_[SPLIT_COL] == name, GROUP_ID_COL].astype(str)) for name in [TRAIN_SPLIT_VALUE, VAL_SPLIT_VALUE, TEST_SPLIT_VALUE]}
    overlaps = {
        "train_val": len(subsets[TRAIN_SPLIT_VALUE] & subsets[VAL_SPLIT_VALUE]),
        "train_test": len(subsets[TRAIN_SPLIT_VALUE] & subsets[TEST_SPLIT_VALUE]),
        "val_test": len(subsets[VAL_SPLIT_VALUE] & subsets[TEST_SPLIT_VALUE]),
    }
    add("group_id_overlap", json.dumps(overlaps), "PASS" if sum(overlaps.values()) == 0 else "FAIL", "")

    clip_subsets = {name: set(df_.loc[df_[SPLIT_COL] == name, CLIP_ID_COL].astype(str)) for name in [TRAIN_SPLIT_VALUE, VAL_SPLIT_VALUE, TEST_SPLIT_VALUE]}
    clip_overlaps = {
        "train_val": len(clip_subsets[TRAIN_SPLIT_VALUE] & clip_subsets[VAL_SPLIT_VALUE]),
        "train_test": len(clip_subsets[TRAIN_SPLIT_VALUE] & clip_subsets[TEST_SPLIT_VALUE]),
        "val_test": len(clip_subsets[VAL_SPLIT_VALUE] & clip_subsets[TEST_SPLIT_VALUE]),
    }
    add("clip_id_overlap", json.dumps(clip_overlaps), "PASS" if sum(clip_overlaps.values()) == 0 else "FAIL", "")

    audit_df = pd.DataFrame(rows)
    save_csv(audit_df, out_dir / "strict_split_audit.csv")
    # WavLM posthoc-compatible alias.
    save_csv(audit_df, out_dir / "strict_split_leakage_audit.csv")
    display(audit_df)
    if (audit_df["status"] == "FAIL").any():
        raise RuntimeError("Audit failed. Fix data/manifest before continuing.")
    return audit_df


if MANIFEST_VAST.exists():
    log_line(f"Existing manifest_strict_vast.csv found: {MANIFEST_VAST}", LIVE_LOG)
    df = pd.read_csv(MANIFEST_VAST)
    df = normalize_split_values(df)
    try:
        audit_df = audit_manifest(df, OUT_TABLES)
    except RuntimeError as e:
        log_line(f"Existing manifest_strict_vast.csv audit failed: {repr(e)}", LIVE_LOG)
        if MANIFEST.exists():
            log_line("Rebuilding manifest_strict_vast.csv from manifest_strict.csv and available audio files.", LIVE_LOG)
            df = build_manifest_vast(force_rebuild=True)
            audit_df = audit_manifest(df, OUT_TABLES)
        else:
            raise
else:
    log_line("manifest_strict_vast.csv not found; building from manifest_strict.csv and available audio files.", LIVE_LOG)
    df = build_manifest_vast(force_rebuild=True)
    audit_df = audit_manifest(df, OUT_TABLES)

[2026-05-28 20:03:08]
================================================================================
Cell | Prepare manifest_strict_vast.csv and audit split
================================================================================

[2026-05-28 20:03:08] Existing manifest_strict_vast.csv found: /workspace/hubert_finetune/data/manifest_strict_vast.csv

,check,value,status,detail
0,required_columns_missing,0,PASS,
1,split_counts,"{""train"": 5936, ""test"": 2039, ""val"": 1999}",PASS,
2,audio_exists,9974/9974,PASS,
3,label_nan_count,0,PASS,
4,clip_id_unique,True,PASS,
5,group_id_overlap,"{""train_val"": 0, ""train_test"": 0, ""val_test"": 0}",PASS,
6,clip_id_overlap,"{""train_val"": 0, ""train_test"": 0, ""val_test"": 0}",PASS,

In [8]:
# =========================
# Load manifest_strict_vast.csv and split data
# =========================
section("Cell | Load manifest_strict_vast.csv and split data")

MANIFEST_VAST = DATA / "manifest_strict_vast.csv"
if not MANIFEST_VAST.exists():
    log_line("manifest_strict_vast.csv not found; trying to build from manifest_strict.csv and audio files.", LIVE_LOG)
    df = build_manifest_vast(force_rebuild=True)
else:
    df = pd.read_csv(MANIFEST_VAST)
    df = normalize_split_values(df)

required_cols = [CLIP_ID_COL, GROUP_ID_COL, AUDIO_COL, SPLIT_COL] + LABEL_COLS
for c in required_cols:
    assert c in df.columns, f"Missing col: {c}"

audit_df = audit_manifest(df, OUT_TABLES)

df_train = df[df[SPLIT_COL] == TRAIN_SPLIT_VALUE].copy().reset_index(drop=True)
df_val = df[df[SPLIT_COL] == VAL_SPLIT_VALUE].copy().reset_index(drop=True)
df_test = df[df[SPLIT_COL] == TEST_SPLIT_VALUE].copy().reset_index(drop=True)

assert len(df_train) > 0, "df_train is empty"
assert len(df_val) > 0, "df_val is empty"
assert len(df_test) > 0, "df_test is empty"

log_line(f"train/val/test: {len(df_train)} / {len(df_val)} / {len(df_test)}", LIVE_LOG)
display(df[[CLIP_ID_COL, GROUP_ID_COL, SPLIT_COL, AUDIO_COL] + LABEL_COLS].head())

[2026-05-28 20:03:08]
================================================================================
Cell | Load manifest_strict_vast.csv and split data
================================================================================

,check,value,status,detail
0,required_columns_missing,0,PASS,
1,split_counts,"{""train"": 5936, ""test"": 2039, ""val"": 1999}",PASS,
2,audio_exists,9974/9974,PASS,
3,label_nan_count,0,PASS,
4,clip_id_unique,True,PASS,
5,group_id_overlap,"{""train_val"": 0, ""train_test"": 0, ""val_test"": 0}",PASS,
6,clip_id_overlap,"{""train_val"": 0, ""train_test"": 0, ""val_test"": 0}",PASS,

[2026-05-28 20:03:09] train/val/test: 5936 / 1999 / 2039

,clip_id,group_id,split_strict,audio_path,extraversion,neuroticism,agreeableness,conscientiousness,openness
0,-10-QQDO_ME.001,-10-QQDO_ME,test,/workspace/hubert_finetune/data/preprocessed_f...,0.532710,0.416667,0.549451,0.563107,0.655556
1,-10-QQDO_ME.002,-10-QQDO_ME,test,/workspace/hubert_finetune/data/preprocessed_f...,0.579439,0.531250,0.670330,0.582524,0.655556
2,-10-QQDO_ME.005,-10-QQDO_ME,test,/workspace/hubert_finetune/data/preprocessed_f...,0.532710,0.552083,0.516484,0.611650,0.633333
3,-IK--4uz5ZY.000,-IK--4uz5ZY,test,/workspace/hubert_finetune/data/preprocessed_f...,0.579439,0.562500,0.604396,0.679612,0.588889
4,-IK--4uz5ZY.002,-IK--4uz5ZY,test,/workspace/hubert_finetune/data/preprocessed_f...,0.542056,0.635417,0.527473,0.660194,0.566667

In [9]:
# =========================
# Dataset and DataLoader
# =========================
section("Cell | Dataset and DataLoader")

feature_extractor = AutoFeatureExtractor.from_pretrained(MODEL_NAME)


def trim_pad_wav(wav: np.ndarray) -> np.ndarray:
    if wav.shape[0] > MAX_LEN:
        return wav[:MAX_LEN]
    if wav.shape[0] < MAX_LEN:
        return np.pad(wav, (0, MAX_LEN - wav.shape[0]), mode="constant")
    return wav


class StrictAudioDataset(Dataset):
    def __init__(self, df_: pd.DataFrame):
        self.df = df_.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx: int):
        row = self.df.iloc[idx]
        audio_path = Path(str(row[AUDIO_COL]))
        try:
            wav, sr = sf.read(audio_path)
        except Exception as e:
            raise RuntimeError(f"Failed to read audio: {audio_path} | {repr(e)}")

        if wav.ndim > 1:
            wav = wav.mean(axis=1)
        wav = wav.astype(np.float32)

        if sr != SR_TARGET:
            wav = librosa.resample(wav, orig_sr=sr, target_sr=SR_TARGET)
            wav = wav.astype(np.float32)

        wav = trim_pad_wav(wav).astype(np.float32)
        y = np.array([row[c] for c in LABEL_COLS], dtype=np.float32)
        clip_id = str(row[CLIP_ID_COL])
        return wav, y, clip_id


def collate_fn(batch):
    wavs, ys, clip_ids = zip(*batch)
    feats = feature_extractor(
        list(wavs),
        sampling_rate=SR_TARGET,
        return_tensors="pt",
        padding=True,
    )
    y = torch.tensor(np.stack(ys), dtype=torch.float32)
    return feats, y, list(clip_ids)


def make_loaders(df_tr: pd.DataFrame, df_va: pd.DataFrame, batch_size: int):
    train_ds = StrictAudioDataset(df_tr)
    val_ds = StrictAudioDataset(df_va)
    train_dl = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=PERSISTENT_WORKERS,
        collate_fn=collate_fn,
    )
    val_dl = DataLoader(
        val_ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=PERSISTENT_WORKERS,
        collate_fn=collate_fn,
    )
    return train_dl, val_dl


def make_test_loader(df_te: pd.DataFrame, batch_size: int):
    test_ds = StrictAudioDataset(df_te)
    test_dl = DataLoader(
        test_ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=PERSISTENT_WORKERS,
        collate_fn=collate_fn,
    )
    return test_dl

# Smoke check one batch.
_tmp_train_dl, _tmp_val_dl = make_loaders(df_train.head(min(len(df_train), BATCH_SIZE)), df_val.head(min(len(df_val), BATCH_SIZE)), batch_size=min(BATCH_SIZE, len(df_train)))
_inputs, _y, _clip_ids = next(iter(_tmp_train_dl))
log_line(f"Batch input_values: {tuple(_inputs['input_values'].shape)} | y: {tuple(_y.shape)} | first clip: {_clip_ids[0]}", LIVE_LOG)
del _tmp_train_dl, _tmp_val_dl, _inputs, _y, _clip_ids
gpu_flush()

[2026-05-28 20:03:09]
================================================================================
Cell | Dataset and DataLoader
================================================================================

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

[2026-05-28 20:03:09] Batch input_values: (40, 240000) | y: (40, 5) | first clip: -N6QKrbnaDs.001

In [10]:
# =========================
# HuBERT + LoRA + regression head
# =========================
section("Cell | HuBERT + LoRA + regression head")


def list_lora_target_candidates(backbone_name: str) -> pd.DataFrame:
    base = AutoModel.from_pretrained(backbone_name)
    rows = []
    for name, module in base.named_modules():
        if any(name.endswith(t) for t in ["q_proj", "v_proj", "k_proj", "out_proj"]):
            rows.append({"module_name": name, "module_type": type(module).__name__})
    del base
    gpu_flush()
    return pd.DataFrame(rows)


target_df = list_lora_target_candidates(MODEL_NAME)
save_csv(target_df, OUT_TABLES / "hubert_lora_target_module_candidates.csv")
display(target_df.head(20))
assert target_df["module_name"].str.endswith("q_proj").any(), "No q_proj module found in HuBERT backbone."
assert target_df["module_name"].str.endswith("v_proj").any(), "No v_proj module found in HuBERT backbone."


class HuBERTWithHead(nn.Module):
    def __init__(
        self,
        backbone_name: str,
        r: int,
        lora_alpha: int = 32,
        lora_dropout: float = 0.05,
        head_dropout: float = 0.1,
    ):
        super().__init__()
        base = AutoModel.from_pretrained(backbone_name)
        for p in base.parameters():
            p.requires_grad = False

        lora_cfg = LoraConfig(
            r=r,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            target_modules=["q_proj", "v_proj"],
            bias="none",
        )
        self.backbone = get_peft_model(base, lora_cfg)
        hidden = base.config.hidden_size
        self.head = nn.Sequential(
            nn.Linear(hidden, 256),
            nn.GELU(),
            nn.Dropout(head_dropout),
            nn.Linear(256, len(LABEL_COLS)),
            nn.Sigmoid(),
        )

    def mean_pool(self, x, attn_mask=None):
        if attn_mask is None:
            return x.mean(dim=1)
        m = attn_mask.unsqueeze(-1).type_as(x)
        return (x * m).sum(dim=1) / m.sum(dim=1).clamp(min=1.0)

    def _get_feat_mask_safe(self, hidden_states, attention_mask):
        try:
            base_model = self.backbone.get_base_model() if hasattr(self.backbone, "get_base_model") else self.backbone
            if hasattr(base_model, "_get_feature_vector_attention_mask"):
                return base_model._get_feature_vector_attention_mask(hidden_states.shape[1], attention_mask)
        except Exception:
            pass
        return None

    def forward(self, input_values, attention_mask=None):
        out = self.backbone(input_values=input_values, attention_mask=attention_mask)
        h = out.last_hidden_state
        feat_mask = None
        if attention_mask is not None:
            feat_mask = self._get_feat_mask_safe(h, attention_mask)
        pooled = self.mean_pool(h, feat_mask)
        return self.head(pooled)


def trainable_params(model: nn.Module):
    return [p for p in model.parameters() if p.requires_grad]


def count_params(model: nn.Module):
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return total, trainable

# Model smoke test.
_tmp_model = HuBERTWithHead(MODEL_NAME, r=8).to(DEVICE)
_total, _trainable = count_params(_tmp_model)
log_line(f"Total params: {_total:,}", LIVE_LOG)
log_line(f"Trainable params: {_trainable:,} ({100*_trainable/max(_total,1):.4f}%)", LIVE_LOG)
_tmp_model.eval()
with torch.no_grad():
    _tmp_dl = make_test_loader(df_val.head(min(len(df_val), BATCH_SIZE)), batch_size=min(BATCH_SIZE, len(df_val)))
    _inputs, _y, _clip_ids = next(iter(_tmp_dl))
    _iv = _inputs["input_values"].to(DEVICE)
    _am = _inputs.get("attention_mask", None)
    if _am is not None:
        _am = _am.to(DEVICE)
    _out = _tmp_model(_iv, _am)
    log_line(f"Forward output shape: {tuple(_out.shape)}", LIVE_LOG)
    assert tuple(_out.shape) == (len(_clip_ids), len(LABEL_COLS))

del _tmp_model, _tmp_dl, _inputs, _y, _clip_ids, _iv, _am, _out
gpu_flush()

[2026-05-28 20:03:10]
================================================================================
Cell | HuBERT + LoRA + regression head
================================================================================

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

                            module_name module_type
0     encoder.layers.0.attention.k_proj      Linear
1     encoder.layers.0.attention.v_proj      Linear
2     encoder.layers.0.attention.q_proj      Linear
3   encoder.layers.0.attention.out_proj      Linear
4     encoder.layers.1.attention.k_proj      Linear
5     encoder.layers.1.attention.v_proj      Linear
6     encoder.layers.1.attention.q_proj      Linear
7   encoder.layers.1.attention.out_proj      Linear
8     encoder.layers.2.attention.k_proj      Linear
9     encoder.layers.2.attention.v_proj      Linear
10    encoder.layers.2.attention.q_proj      Linear
11  encoder.layers.2.attention.out_proj      Linear
12    encoder.layers.3.attention.k_proj      Linear
13    encoder.layers.3.attention.v_proj      Linear
14    encoder.layers.3.attention.q_proj      Linear
15  encoder.layers.3.attention.out_proj      Linear
16    encoder.layers.4.attention.k_proj      Linear
17    encoder.layers.4.attention.v_proj      Linear
18    encoder.layers.4.attention.q_proj      Linear
19  encoder.layers.4.attention.out_proj      Linear

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

[2026-05-28 20:03:12] Total params: 94,864,773

[2026-05-28 20:03:12] Trainable params: 493,061 (0.5198%)

[2026-05-28 20:03:13] Forward output shape: (40, 5)

In [11]:
# =========================
# Metrics
# =========================
section("Cell | Metrics")


def compute_metrics_from_arrays(y_true: np.ndarray, y_pred: np.ndarray) -> Dict:
    mae_per = np.mean(np.abs(y_pred - y_true), axis=0)
    mae_mean = float(np.mean(mae_per))
    rmse_per = np.sqrt(np.mean((y_pred - y_true) ** 2, axis=0))
    rmse_mean = float(np.mean(rmse_per))

    r2_per = []
    for j in range(y_true.shape[1]):
        yt = y_true[:, j]
        yp = y_pred[:, j]
        sst = float(np.sum((yt - np.mean(yt)) ** 2))
        if sst <= 1e-12:
            r2_per.append(np.nan)
        else:
            r2_per.append(float(r2_score(yt, yp)))
    r2_per = np.array(r2_per, dtype=float)
    r2_mean = float(np.nanmean(r2_per))

    acc_per = 1.0 - mae_per
    acc_mean = float(np.mean(acc_per))
    S = 1.0 - mae_mean
    return {
        "mae_per": mae_per,
        "mae_mean": mae_mean,
        "rmse_per": rmse_per,
        "rmse_mean": rmse_mean,
        "r2_per": r2_per,
        "r2_mean": r2_mean,
        "acc_per": acc_per,
        "acc_mean": acc_mean,
        "S": S,
    }


def metrics_to_flat_dict(metrics: Dict) -> Dict:
    out = {
        "mae_mean": float(metrics["mae_mean"]),
        "rmse_mean": float(metrics["rmse_mean"]),
        "r2_mean": float(metrics["r2_mean"]),
        "acc_mean": float(metrics["acc_mean"]),
        "S": float(metrics["S"]),
    }
    for i, col in enumerate(LABEL_COLS):
        out[f"mae_{col}"] = float(metrics["mae_per"][i])
        out[f"rmse_{col}"] = float(metrics["rmse_per"][i])
        out[f"r2_{col}"] = float(metrics["r2_per"][i]) if not np.isnan(metrics["r2_per"][i]) else np.nan
        out[f"acc_{col}"] = float(metrics["acc_per"][i])
    return out


def per_trait_metrics_df(y_true: np.ndarray, y_pred: np.ndarray, tag: str) -> pd.DataFrame:
    metrics = compute_metrics_from_arrays(y_true, y_pred)
    rows = []
    for i, col in enumerate(LABEL_COLS):
        rows.append({
            "tag": tag,
            "trait": col,
            "MAE": float(metrics["mae_per"][i]),
            "RMSE": float(metrics["rmse_per"][i]),
            "R2": float(metrics["r2_per"][i]),
            "Acc(1-MAE)": float(metrics["acc_per"][i]),
        })
    rows.append({
        "tag": tag,
        "trait": "mean",
        "MAE": float(metrics["mae_mean"]),
        "RMSE": float(metrics["rmse_mean"]),
        "R2": float(metrics["r2_mean"]),
        "Acc(1-MAE)": float(metrics["acc_mean"]),
    })
    return pd.DataFrame(rows)

[2026-05-28 20:03:14]
================================================================================
Cell | Metrics
================================================================================

In [12]:
# =========================
# Plot helpers
# =========================
section("Cell | Plot helpers")


def save_and_maybe_show(fig, path: Path, show: bool = False):
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=200, bbox_inches="tight")
    if show:
        plt.show()
    plt.close(fig)


def plot_history(history_df: pd.DataFrame, out_dir: Path, show: bool = False):
    """Save WavLM-compatible per-run curves plus the combined train/validation loss curve."""
    if len(history_df) == 0:
        return

    # Combined train loss and validation loss in one figure.
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(history_df["epoch"], history_df["train_loss"], marker="o", label="train_loss")
    if "val_mae_mean" in history_df.columns:
        ax.plot(history_df["epoch"], history_df["val_mae_mean"], marker="o", label="validation_loss / val_MAE_mean")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("MAE / L1 loss")
    ax.set_title("Train Loss and Validation Loss")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_and_maybe_show(fig, out_dir / "loss_curve.png", show=show)

    # WavLM-compatible separate train loss curve.
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(history_df["epoch"], history_df["train_loss"], marker="o")
    ax.set_title("Train Loss per Epoch")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.grid(True, alpha=0.3)
    save_and_maybe_show(fig, out_dir / "curve_train_loss.png", show=show)

    # WavLM-compatible validation metric curves.
    for col, title, fname in [
        ("val_S", "Validation S per Epoch", "curve_val_S.png"),
        ("val_mae_mean", "Validation MAE Mean per Epoch", "curve_val_mae_mean.png"),
        ("val_rmse_mean", "Validation RMSE Mean per Epoch", "curve_val_rmse_mean.png"),
        ("val_r2_mean", "Validation R2 Mean per Epoch", "curve_val_r2_mean.png"),
    ]:
        if col not in history_df.columns:
            continue
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.plot(history_df["epoch"], history_df[col], marker="o")
        ax.set_title(title)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(col)
        ax.grid(True, alpha=0.3)
        save_and_maybe_show(fig, out_dir / fname, show=show)

    # WavLM-compatible validation MAE per trait.
    trait_cols = [f"val_mae_{col}" for col in LABEL_COLS if f"val_mae_{col}" in history_df.columns]
    if trait_cols:
        fig, ax = plt.subplots(figsize=(9, 5))
        for col in LABEL_COLS:
            metric_col = f"val_mae_{col}"
            if metric_col in history_df.columns:
                ax.plot(history_df["epoch"], history_df[metric_col], marker="o", label=col)
        ax.set_title("Validation MAE per Trait")
        ax.set_xlabel("Epoch")
        ax.set_ylabel("MAE")
        ax.legend()
        ax.grid(True, alpha=0.3)
        save_and_maybe_show(fig, out_dir / "curve_mae_per_trait.png", show=show)


def plot_pred_vs_true(df_pred: pd.DataFrame, out_dir: Path, tag: str, show: bool = False):
    # Histogram true vs pred per trait.
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    axes = axes.flatten()
    for i, col in enumerate(LABEL_COLS):
        ax = axes[i]
        ax.hist(df_pred[f"true_{col}"].values, bins=30, alpha=0.55, label="true")
        ax.hist(df_pred[f"pred_{col}"].values, bins=30, alpha=0.55, label="pred")
        ax.set_title(col)
        ax.set_xlabel("Score")
        ax.set_ylabel("Count")
        ax.legend()
    axes[-1].axis("off")
    save_and_maybe_show(fig, out_dir / f"hist_{tag}_pred_vs_true.png", show=show)

    # Scatter true vs pred per trait.
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    axes = axes.flatten()
    for i, col in enumerate(LABEL_COLS):
        ax = axes[i]
        ax.scatter(df_pred[f"true_{col}"].values, df_pred[f"pred_{col}"].values, s=8, alpha=0.35)
        ax.plot([0, 1], [0, 1], linestyle="--")
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.set_title(col)
        ax.set_xlabel("True")
        ax.set_ylabel("Pred")
    axes[-1].axis("off")
    save_and_maybe_show(fig, out_dir / f"scatter_{tag}_pred_vs_true.png", show=show)

    # WavLM-compatible residual scatter plot.
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    axes = axes.flatten()
    for i, col in enumerate(LABEL_COLS):
        ax = axes[i]
        pred = df_pred[f"pred_{col}"].values
        residual = df_pred[f"pred_{col}"].values - df_pred[f"true_{col}"].values
        ax.scatter(pred, residual, s=8, alpha=0.35)
        ax.axhline(0, linestyle="--")
        ax.set_title(col)
        ax.set_xlabel("Pred")
        ax.set_ylabel("Residual")
    axes[-1].axis("off")
    save_and_maybe_show(fig, out_dir / f"scatter_{tag}_residuals.png", show=show)


def plot_bar_metrics(df_metric: pd.DataFrame, metric: str, out_path: Path, title: str, show: bool = False):
    d = df_metric[df_metric["trait"] != "mean"].copy()
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(d["trait"], d[metric])
    ax.set_title(title)
    ax.set_ylabel(metric)
    ax.tick_params(axis="x", rotation=30)
    save_and_maybe_show(fig, out_path, show=show)

[2026-05-28 20:03:14]
================================================================================
Cell | Plot helpers
================================================================================

In [13]:
# =========================
# Predict and evaluate
# =========================
section("Cell | Predict and evaluate")


def predict_and_evaluate(
    model: nn.Module,
    dl: DataLoader,
    run_id: str,
    seed: int,
    best_epoch: Optional[int] = None,
    best_val_S: Optional[float] = None,
    desc: str = "eval",
):
    model.eval()
    y_true_all = []
    y_pred_all = []
    clip_ids_all = []

    amp_ctx = torch.cuda.amp.autocast if AMP_ENABLED else nullcontext
    with torch.no_grad():
        pbar = tqdm(dl, desc=desc, leave=False, file=sys.stdout, dynamic_ncols=True)
        for inputs, y, clip_ids in pbar:
            iv = inputs["input_values"].to(DEVICE, non_blocking=True)
            am = inputs.get("attention_mask", None)
            if am is not None:
                am = am.to(DEVICE, non_blocking=True)
            y = y.to(DEVICE, non_blocking=True)

            with amp_ctx():
                yhat = model(iv, am)
            y_true_all.append(y.detach().cpu().numpy())
            y_pred_all.append(yhat.detach().cpu().numpy())
            clip_ids_all.extend(clip_ids)
        pbar.close()

    y_true = np.concatenate(y_true_all, axis=0)
    y_pred = np.concatenate(y_pred_all, axis=0)
    metrics = compute_metrics_from_arrays(y_true, y_pred)

    rows = []
    for i, clip_id in enumerate(clip_ids_all):
        row = {
            "clip_id": clip_id,
            "run_id": run_id,
            "seed": seed,
        }
        if best_epoch is not None:
            row["best_epoch"] = int(best_epoch)
        if best_val_S is not None:
            row["best_val_S"] = float(best_val_S)
        for j, col in enumerate(LABEL_COLS):
            row[f"true_{col}"] = float(y_true[i, j])
            row[f"pred_{col}"] = float(y_pred[i, j])
            row[f"abs_err_{col}"] = float(abs(y_pred[i, j] - y_true[i, j]))
        row["mae_per_sample"] = float(np.mean([row[f"abs_err_{c}"] for c in LABEL_COLS]))
        rows.append(row)

    df_pred = pd.DataFrame(rows)
    return metrics, df_pred

[2026-05-28 20:03:14]
================================================================================
Cell | Predict and evaluate
================================================================================

In [14]:
# =========================
# Optimizer, scheduler, checkpoint, train epoch
# =========================
section("Cell | Optimizer, scheduler, checkpoint, train epoch")


def build_optimizer(model: nn.Module, lr: float, weight_decay: float):
    return torch.optim.AdamW(trainable_params(model), lr=lr, weight_decay=weight_decay)


def build_scheduler(optimizer, train_loader_len: int, warmup_ratio: float):
    total_steps = max(1, train_loader_len * MAX_EPOCHS)
    warmup_steps = int(total_steps * warmup_ratio)
    return get_linear_schedule_with_warmup(
        optimizer=optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )


def save_checkpoint(ckpt_dir: Path, model: nn.Module, optimizer, scheduler, state: Dict):
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    ckpt_path = ckpt_dir / "best_model.pt"
    payload = {
        "model_state": model.state_dict(),
        "optimizer_state": optimizer.state_dict() if optimizer is not None else None,
        "scheduler_state": scheduler.state_dict() if scheduler is not None else None,
        **state,
    }
    torch.save(payload, ckpt_path)
    save_json(state, ckpt_dir / "checkpoint_meta.json")
    return ckpt_path


def train_one_epoch(model, dl, optimizer, scheduler=None, desc="train"):
    model.train()
    total_loss = 0.0
    n = 0
    amp_ctx = torch.cuda.amp.autocast if AMP_ENABLED else nullcontext
    # Match the WavLM notebook behavior: initialize GradScaler inside each epoch.
    scaler = torch.cuda.amp.GradScaler(enabled=AMP_ENABLED)

    optimizer.zero_grad(set_to_none=True)
    pbar = tqdm(dl, desc=desc, leave=False, file=sys.stdout, dynamic_ncols=True)
    for inputs, y, _clip_ids in pbar:
        iv = inputs["input_values"].to(DEVICE, non_blocking=True)
        am = inputs.get("attention_mask", None)
        if am is not None:
            am = am.to(DEVICE, non_blocking=True)
        y = y.to(DEVICE, non_blocking=True)

        with amp_ctx():
            yhat = model(iv, am)
            loss = F.l1_loss(yhat, y, reduction="mean")

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(trainable_params(model), GRAD_CLIP)
        scaler.step(optimizer)
        scaler.update()
        optimizer.zero_grad(set_to_none=True)

        if scheduler is not None:
            scheduler.step()

        bs = y.size(0)
        total_loss += float(loss.item()) * bs
        n += bs
        pbar.set_postfix(loss=f"{float(loss.item()):.5f}", avg=f"{float(total_loss/max(n,1)):.5f}")
    pbar.close()
    return float(total_loss / max(n, 1))

[2026-05-28 20:03:14]
================================================================================
Cell | Optimizer, scheduler, checkpoint, train epoch
================================================================================

In [15]:
# =========================
# Single run training
# =========================
section("Cell | Single run training function")


def run_single_training(
    run_name: str,
    run_output_dir: Path,
    run_ckpt_dir: Path,
    df_tr: pd.DataFrame,
    df_va: pd.DataFrame,
    df_te: Optional[pd.DataFrame],
    seed: int,
    hp: Dict,
    is_optuna: bool = False,
    trial: Optional[optuna.Trial] = None,
    show_plots: bool = False,
):
    set_seed(seed)
    gpu_flush()
    run_output_dir.mkdir(parents=True, exist_ok=True)
    run_ckpt_dir.mkdir(parents=True, exist_ok=True)

    log_line(f"[{run_name}] START | seed={seed} | hp={hp}", LIVE_LOG)
    train_dl, val_dl = make_loaders(df_tr, df_va, batch_size=BATCH_SIZE)
    test_dl = make_test_loader(df_te, batch_size=BATCH_SIZE) if df_te is not None else None

    model = HuBERTWithHead(
        backbone_name=MODEL_NAME,
        r=int(hp["r"]),
        lora_alpha=int(hp["lora_alpha"]),
        lora_dropout=float(hp["lora_dropout"]),
        head_dropout=HEAD_DROPOUT,
    ).to(DEVICE)

    optimizer = build_optimizer(model, lr=float(hp["learning_rate"]), weight_decay=float(hp["weight_decay"]))
    scheduler = build_scheduler(optimizer, len(train_dl), warmup_ratio=float(hp["warmup_ratio"]))
    total_params, train_params = count_params(model)

    best_S = -1e18
    best_epoch = 0
    stop_epoch = 0
    patience_count = 0
    best_metrics_val = None
    best_ckpt_path = None
    best_df_pred_val = None
    last_metrics_val = None
    last_df_pred_val = None
    history_rows = []

    try:
        epoch_iter = tqdm(range(1, MAX_EPOCHS + 1), desc=f"[{run_name}] epochs", leave=False, file=sys.stdout, dynamic_ncols=True)
        for epoch in epoch_iter:
            train_loss = train_one_epoch(model, train_dl, optimizer, scheduler=scheduler, desc=f"{run_name} train e{epoch:03d}")
            val_metrics, df_pred_val = predict_and_evaluate(model, val_dl, run_id=run_name, seed=seed, desc=f"{run_name} val e{epoch:03d}")

            last_metrics_val = val_metrics
            last_df_pred_val = df_pred_val.copy()
            row = {"epoch": int(epoch), "train_loss": float(train_loss)}
            row.update({f"val_{k}": v for k, v in metrics_to_flat_dict(val_metrics).items()})
            history_rows.append(row)

            current_S = float(val_metrics["S"])
            if not np.isfinite(current_S):
                raise RuntimeError(f"{run_name} failed because val S is NaN/Inf at epoch {epoch}")

            improved = current_S > (best_S + MIN_DELTA)
            if improved:
                best_S = current_S
                best_epoch = int(epoch)
                patience_count = 0
                best_metrics_val = val_metrics
                best_df_pred_val = df_pred_val.copy()
                state = {
                    "run_name": run_name,
                    "seed": int(seed),
                    "best_epoch": int(best_epoch),
                    "best_val_S": float(best_S),
                    "total_params": int(total_params),
                    "trainable_params": int(train_params),
                    "hp": hp,
                    "is_optuna": bool(is_optuna),
                    "model_name": MODEL_NAME,
                    "experiment_name": EXPERIMENT_NAME,
                }
                best_ckpt_path = save_checkpoint(run_ckpt_dir, model, optimizer, scheduler, state)
            else:
                patience_count += 1

            log_line(
                f"[{run_name}] epoch={epoch:03d} | train_loss={train_loss:.6f} | "
                f"val_MAE={val_metrics['mae_mean']:.6f} | val_S={current_S:.6f} | "
                f"best_S={best_S:.6f} @epoch={best_epoch} | patience={patience_count}/{PATIENCE}",
                LIVE_LOG,
            )

            if trial is not None:
                trial.report(best_S, step=epoch)
                if trial.should_prune():
                    log_line(f"[{run_name}] PRUNED at epoch={epoch} | best_S={best_S:.6f}", LIVE_LOG)
                    raise optuna.TrialPruned()

            if patience_count >= PATIENCE:
                stop_epoch = int(epoch)
                log_line(f"[{run_name}] early stopping at epoch={stop_epoch}", LIVE_LOG)
                break

            del df_pred_val

        epoch_iter.close()
        if stop_epoch == 0:
            stop_epoch = int(history_rows[-1]["epoch"] if history_rows else MAX_EPOCHS)

        history_df = pd.DataFrame(history_rows)
        save_csv(history_df, run_output_dir / "history.csv")
        plot_history(history_df, run_output_dir, show=show_plots)

        if last_df_pred_val is not None:
            save_csv(last_df_pred_val, run_output_dir / "predictions_val.csv")
            plot_pred_vs_true(last_df_pred_val, run_output_dir, tag="val", show=False)
        if best_df_pred_val is not None:
            save_csv(best_df_pred_val, run_output_dir / "predictions_val_best.csv")
        if last_metrics_val is not None:
            save_json(metrics_to_flat_dict(last_metrics_val), run_output_dir / "last_val_metrics.json")
        if best_metrics_val is not None:
            save_json(metrics_to_flat_dict(best_metrics_val), run_output_dir / "best_val_metrics.json")

        assert best_ckpt_path is not None and Path(best_ckpt_path).exists(), f"Best checkpoint was not saved for {run_name}"
        ck = safe_torch_load(best_ckpt_path, map_location=DEVICE)
        model.load_state_dict(ck["model_state"], strict=True)

        run_summary = {
            "run_name": run_name,
            "seed": int(seed),
            "best_epoch": int(best_epoch),
            "stop_epoch": int(stop_epoch),
            "best_val_S": float(best_S),
            "total_params": int(total_params),
            "trainable_params": int(train_params),
            "checkpoint_path": str(best_ckpt_path),
            "hp": hp,
            "model_name": MODEL_NAME,
            "experiment_name": EXPERIMENT_NAME,
        }
        if best_metrics_val is not None:
            best_val_flat = metrics_to_flat_dict(best_metrics_val)
            run_summary.update({f"best_val_{k}": safe_to_float(v) for k, v in best_val_flat.items()})

        test_metrics = None
        df_pred_test = None
        if test_dl is not None:
            test_metrics, df_pred_test = predict_and_evaluate(
                model,
                test_dl,
                run_id=run_name,
                seed=seed,
                best_epoch=best_epoch,
                best_val_S=best_S,
                desc=f"{run_name} test",
            )
            save_csv(df_pred_test, run_output_dir / "predictions_test_strict.csv")
            plot_pred_vs_true(df_pred_test, run_output_dir, tag="test_strict", show=show_plots)
            test_flat = metrics_to_flat_dict(test_metrics)
            save_json(test_flat, run_output_dir / "test_metrics.json")
            run_summary.update({f"test_{k}": safe_to_float(v) for k, v in test_flat.items()})

            trait_df = per_trait_metrics_df(
                df_pred_test[[f"true_{c}" for c in LABEL_COLS]].values,
                df_pred_test[[f"pred_{c}" for c in LABEL_COLS]].values,
                tag=run_name,
            )
            save_csv(trait_df, run_output_dir / "test_per_trait_metrics.csv")

        save_json(run_summary, run_output_dir / "run_summary.json")
        log_line(f"[{run_name}] DONE | best_epoch={best_epoch} | best_val_S={best_S:.6f} | test_MAE={run_summary.get('test_mae_mean', np.nan):.6f} | test_R2={run_summary.get('test_r2_mean', np.nan):.6f}", LIVE_LOG)

        return {
            "run_summary": run_summary,
            "history_df": history_df,
            "best_ckpt_path": str(best_ckpt_path),
            "test_metrics": test_metrics,
            "df_pred_test": df_pred_test,
            "df_pred_val_best": best_df_pred_val,
            "df_pred_val_last": last_df_pred_val,
        }
    except optuna.TrialPruned:
        history_df = pd.DataFrame(history_rows)
        if len(history_df):
            save_csv(history_df, run_output_dir / "history.csv")
            plot_history(history_df, run_output_dir, show=False)
        raise
    except Exception as e:
        history_df = pd.DataFrame(history_rows)
        if len(history_df):
            save_csv(history_df, run_output_dir / "history.csv")
            plot_history(history_df, run_output_dir, show=False)
        save_json({"run_name": run_name, "seed": int(seed), "status": "failed", "error": repr(e), "hp": hp}, run_output_dir / "run_summary_failed.json")
        log_line(f"[{run_name}] FAILED | {repr(e)}", LIVE_LOG)
        raise
    finally:
        for obj_name in ["model", "optimizer", "scheduler", "scaler", "train_dl", "val_dl", "test_dl", "ck"]:
            if obj_name in locals():
                try:
                    del locals()[obj_name]
                except Exception:
                    pass
        gpu_flush()

[2026-05-28 20:03:14]
================================================================================
Cell | Single run training function
================================================================================

In [16]:
# =========================
# Optuna search space and objective
# =========================
section("Cell | Optuna search space and objective")


def sample_hp(trial: optuna.Trial) -> Dict:
    # Same search space as WavLM for fair comparison.
    return {
        "learning_rate": trial.suggest_float("learning_rate", 5e-5, 3e-4, log=True),
        "r": trial.suggest_categorical("r", [4, 8, 16]),
        "lora_alpha": trial.suggest_categorical("lora_alpha", [16, 32, 64]),
        "lora_dropout": trial.suggest_categorical("lora_dropout", [0.0, 0.05, 0.1, 0.15]),
        "weight_decay": trial.suggest_float("weight_decay", 1e-4, 2e-2, log=True),
        "warmup_ratio": trial.suggest_categorical("warmup_ratio", [0.0, 0.03, 0.05, 0.08, 0.1]),
    }


def objective(trial: optuna.Trial):
    trial_num = trial.number + 1
    trial_name = f"trial_{trial_num:03d}"
    trial_out_dir = OUT_OPTUNA_TRIALS / trial_name
    trial_ckpt_dir = CKPT_OPTUNA_TRIALS / trial_name
    hp = sample_hp(trial)
    log_line(f"[OPTUNA] {trial_name} start | hp={hp}", LIVE_LOG)

    try:
        result = run_single_training(
            run_name=trial_name,
            run_output_dir=trial_out_dir,
            run_ckpt_dir=trial_ckpt_dir,
            df_tr=df_train,
            df_va=df_val,
            df_te=None,
            seed=OPTUNA_SEED,
            hp=hp,
            is_optuna=True,
            trial=trial,
            show_plots=DISPLAY_TRIAL_PLOTS,
        )
        best_S = float(result["run_summary"]["best_val_S"])
        save_json({"trial_number": trial.number, "trial_name": trial_name, "value": best_S, "seed": OPTUNA_SEED, "hp": hp}, trial_out_dir / "trial_config.json")
        log_line(f"[OPTUNA] {trial_name} done | best_val_S={best_S:.6f}", LIVE_LOG)
        return best_S
    except optuna.TrialPruned:
        log_line(f"[OPTUNA] {trial_name} pruned", LIVE_LOG)
        raise
    except Exception as e:
        append_jsonl({"trial_name": trial_name, "error": repr(e), "hp": hp}, TRIAL_FAIL_LOG)
        log_line(f"[OPTUNA-FAIL] {trial_name} | {repr(e)}", LIVE_LOG)
        raise

[2026-05-28 20:03:14]
================================================================================
Cell | Optuna search space and objective
================================================================================

In [17]:
# =========================
# Create/resume Optuna study and run optimization
# =========================
section("Cell | Run Optuna")

study_config = {
    "study_name": STUDY_NAME,
    "model_name": MODEL_NAME,
    "n_trials": N_TRIALS,
    "selection_metric": SELECTION_METRIC,
    "patience": PATIENCE,
    "batch_size": BATCH_SIZE,
    "split_source": str(MANIFEST_VAST),
    "pruner": str(PRUNER),
    "optuna_seed": OPTUNA_SEED,
    "note": "Optuna default sampler is used to mirror the WavLM notebook.",
}
save_json(study_config, OUT_OPTUNA_STUDY / "study_config.json")
save_json(study_config, OUT_TABLES / "study_config.json")

# Keep Optuna sampler behavior aligned with the WavLM notebook:
# no explicit sampler is passed to create_study, so Optuna uses its default sampler.
study = optuna.create_study(
    study_name=STUDY_NAME,
    direction="maximize",
    storage=STUDY_STORAGE,
    load_if_exists=True,
    pruner=PRUNER,
)

total_trials_before = len(study.trials)
completed_before = len([t for t in study.trials if t.state == TrialState.COMPLETE])
remaining = max(0, N_TRIALS - total_trials_before)
log_line(f"Study loaded: {STUDY_NAME} | total_trials_before={total_trials_before} | complete_before={completed_before} | remaining={remaining}", LIVE_LOG)

if remaining > 0:
    study.optimize(objective, n_trials=remaining, gc_after_trial=True, show_progress_bar=False)
else:
    log_line("No remaining Optuna trials. Reusing existing study.", LIVE_LOG)

# Save Optuna trial state counts for audit transparency
trial_state_counts = pd.Series(
    [str(t.state) for t in study.trials]
).value_counts().reset_index()

trial_state_counts.columns = ["state", "count"]

save_csv(trial_state_counts, OUT_OPTUNA_STUDY / "trial_state_counts.csv")
save_csv(trial_state_counts, OUT_TABLES / "trial_state_counts.csv")

complete_count = len([t for t in study.trials if t.state == TrialState.COMPLETE])

if complete_count < N_TRIALS:
    log_line(
        f"[WARN] Completed Optuna trials < N_TRIALS. "
        f"complete={complete_count}, total={len(study.trials)}. "
        "This matches WavLM total-trial policy, but must be reported.",
        LIVE_LOG,
    )

completed = [t for t in study.trials if t.state == TrialState.COMPLETE]
assert len(completed) > 0, "No completed Optuna trial. Cannot continue."
best_trial = study.best_trial

completed = [t for t in study.trials if t.state == TrialState.COMPLETE]
assert len(completed) > 0, "No completed Optuna trial. Cannot continue."
best_trial = study.best_trial
log_line(f"Best trial: #{best_trial.number} | value={best_trial.value:.6f} | params={best_trial.params}", LIVE_LOG)
best_trial_summary = {
    "number": int(best_trial.number),
    "value": float(best_trial.value),
    "params": dict(best_trial.params),
}
save_json(best_trial_summary, OUT_OPTUNA_STUDY / "best_trial_summary.json")
save_json(best_trial_summary, OUT_TABLES / "best_trial_summary.json")

[2026-05-28 20:03:14]
================================================================================
Cell | Run Optuna
================================================================================

[2026-05-28 20:03:15] Study loaded: hubert_lora_strict_optuna | total_trials_before=0 | complete_before=0 | remaining=50

[2026-05-28 20:03:16] [OPTUNA] trial_001 start | hp={'learning_rate': 0.00012816842992683473, 'r': 4, 'lora_alpha': 64, 'lora_dropout': 0.15, 'weight_decay': 0.015177021393917542, 'warmup_ratio': 0.0}

[2026-05-28 20:03:16] [trial_001] START | seed=42 | hp={'learning_rate': 0.00012816842992683473, 'r': 4, 'lora_alpha': 64, 'lora_dropout': 0.15, 'weight_decay': 0.015177021393917542, 'warmup_ratio': 0.0}

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

[trial_001] epochs:   0%|                                                                                                                                    | 0/100 [00:00<?, ?it/s]

trial_001 train e001:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e001:   0%|                                                                                                       | 0/149 [00:01<?, ?it/s, avg=0.12754, loss=0.12754]

trial_001 train e001:   1%|▋                                                                                              | 1/149 [00:01<03:41,  1.49s/it, avg=0.12754, loss=0.12754]

trial_001 train e001:   1%|▋                                                                                              | 1/149 [00:02<03:41,  1.49s/it, avg=0.13158, loss=0.13562]

trial_001 train e001:   1%|█▎                                                                                             | 2/149 [00:02<02:43,  1.11s/it, avg=0.13158, loss=0.13562]

trial_001 train e001:   1%|█▎                                                                                             | 2/149 [00:03<02:43,  1.11s/it, avg=0.12821, loss=0.12146]

trial_001 train e001:   2%|█▉                                                                                             | 3/149 [00:03<02:16,  1.07it/s, avg=0.12821, loss=0.12146]

trial_001 train e001:   2%|█▉                                                                                             | 3/149 [00:03<02:16,  1.07it/s, avg=0.12268, loss=0.10609]

trial_001 train e001:   3%|██▌                                                                                            | 4/149 [00:03<02:04,  1.17it/s, avg=0.12268, loss=0.10609]

trial_001 train e001:   3%|██▌                                                                                            | 4/149 [00:04<02:04,  1.17it/s, avg=0.12485, loss=0.13356]

trial_001 train e001:   3%|███▏                                                                                           | 5/149 [00:04<01:56,  1.23it/s, avg=0.12485, loss=0.13356]

trial_001 train e001:   3%|███▏                                                                                           | 5/149 [00:05<01:56,  1.23it/s, avg=0.12505, loss=0.12600]

trial_001 train e001:   4%|███▊                                                                                           | 6/149 [00:05<01:52,  1.27it/s, avg=0.12505, loss=0.12600]

trial_001 train e001:   4%|███▊                                                                                           | 6/149 [00:06<01:52,  1.27it/s, avg=0.12417, loss=0.11892]

trial_001 train e001:   5%|████▍                                                                                          | 7/149 [00:06<01:51,  1.27it/s, avg=0.12417, loss=0.11892]

trial_001 train e001:   5%|████▍                                                                                          | 7/149 [00:06<01:51,  1.27it/s, avg=0.12304, loss=0.11513]

trial_001 train e001:   5%|█████                                                                                          | 8/149 [00:06<01:47,  1.31it/s, avg=0.12304, loss=0.11513]

trial_001 train e001:   5%|█████                                                                                          | 8/149 [00:07<01:47,  1.31it/s, avg=0.12300, loss=0.12272]

trial_001 train e001:   6%|█████▋                                                                                         | 9/149 [00:07<01:44,  1.34it/s, avg=0.12300, loss=0.12272]

trial_001 train e001:   6%|█████▋                                                                                         | 9/149 [00:08<01:44,  1.34it/s, avg=0.12243, loss=0.11728]

trial_001 train e001:   7%|██████▎                                                                                       | 10/149 [00:08<01:43,  1.34it/s, avg=0.12243, loss=0.11728]

trial_001 train e001:   7%|██████▎                                                                                       | 10/149 [00:08<01:43,  1.34it/s, avg=0.12249, loss=0.12304]

trial_001 train e001:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.34it/s, avg=0.12249, loss=0.12304]

trial_001 train e001:   7%|██████▉                                                                                       | 11/149 [00:09<01:42,  1.34it/s, avg=0.12154, loss=0.11112]

trial_001 train e001:   8%|███████▌                                                                                      | 12/149 [00:09<01:43,  1.32it/s, avg=0.12154, loss=0.11112]

trial_001 train e001:   8%|███████▌                                                                                      | 12/149 [00:10<01:43,  1.32it/s, avg=0.12162, loss=0.12253]

trial_001 train e001:   9%|████████▏                                                                                     | 13/149 [00:10<01:44,  1.31it/s, avg=0.12162, loss=0.12253]

trial_001 train e001:   9%|████████▏                                                                                     | 13/149 [00:11<01:44,  1.31it/s, avg=0.12166, loss=0.12220]

trial_001 train e001:   9%|████████▊                                                                                     | 14/149 [00:11<01:40,  1.34it/s, avg=0.12166, loss=0.12220]

trial_001 train e001:   9%|████████▊                                                                                     | 14/149 [00:11<01:40,  1.34it/s, avg=0.12127, loss=0.11582]

trial_001 train e001:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.35it/s, avg=0.12127, loss=0.11582]

trial_001 train e001:  10%|█████████▍                                                                                    | 15/149 [00:12<01:39,  1.35it/s, avg=0.12086, loss=0.11472]

trial_001 train e001:  11%|██████████                                                                                    | 16/149 [00:12<01:39,  1.34it/s, avg=0.12086, loss=0.11472]

trial_001 train e001:  11%|██████████                                                                                    | 16/149 [00:13<01:39,  1.34it/s, avg=0.12105, loss=0.12409]

trial_001 train e001:  11%|██████████▋                                                                                   | 17/149 [00:13<01:37,  1.35it/s, avg=0.12105, loss=0.12409]

trial_001 train e001:  11%|██████████▋                                                                                   | 17/149 [00:14<01:37,  1.35it/s, avg=0.12097, loss=0.11954]

trial_001 train e001:  12%|███████████▎                                                                                  | 18/149 [00:14<01:36,  1.35it/s, avg=0.12097, loss=0.11954]

trial_001 train e001:  12%|███████████▎                                                                                  | 18/149 [00:14<01:36,  1.35it/s, avg=0.12144, loss=0.12993]

trial_001 train e001:  13%|███████████▉                                                                                  | 19/149 [00:14<01:36,  1.35it/s, avg=0.12144, loss=0.12993]

trial_001 train e001:  13%|███████████▉                                                                                  | 19/149 [00:15<01:36,  1.35it/s, avg=0.12148, loss=0.12222]

trial_001 train e001:  13%|████████████▌                                                                                 | 20/149 [00:15<01:36,  1.34it/s, avg=0.12148, loss=0.12222]

trial_001 train e001:  13%|████████████▌                                                                                 | 20/149 [00:16<01:36,  1.34it/s, avg=0.12189, loss=0.13011]

trial_001 train e001:  14%|█████████████▏                                                                                | 21/149 [00:16<01:35,  1.34it/s, avg=0.12189, loss=0.13011]

trial_001 train e001:  14%|█████████████▏                                                                                | 21/149 [00:17<01:35,  1.34it/s, avg=0.12168, loss=0.11737]

trial_001 train e001:  15%|█████████████▉                                                                                | 22/149 [00:17<01:32,  1.38it/s, avg=0.12168, loss=0.11737]

trial_001 train e001:  15%|█████████████▉                                                                                | 22/149 [00:17<01:32,  1.38it/s, avg=0.12158, loss=0.11940]

trial_001 train e001:  15%|██████████████▌                                                                               | 23/149 [00:17<01:32,  1.36it/s, avg=0.12158, loss=0.11940]

trial_001 train e001:  15%|██████████████▌                                                                               | 23/149 [00:18<01:32,  1.36it/s, avg=0.12098, loss=0.10723]

trial_001 train e001:  16%|███████████████▏                                                                              | 24/149 [00:18<01:32,  1.35it/s, avg=0.12098, loss=0.10723]

trial_001 train e001:  16%|███████████████▏                                                                              | 24/149 [00:19<01:32,  1.35it/s, avg=0.12158, loss=0.13579]

trial_001 train e001:  17%|███████████████▊                                                                              | 25/149 [00:19<01:32,  1.33it/s, avg=0.12158, loss=0.13579]

trial_001 train e001:  17%|███████████████▊                                                                              | 25/149 [00:20<01:32,  1.33it/s, avg=0.12122, loss=0.11218]

trial_001 train e001:  17%|████████████████▍                                                                             | 26/149 [00:20<01:31,  1.34it/s, avg=0.12122, loss=0.11218]

trial_001 train e001:  17%|████████████████▍                                                                             | 26/149 [00:20<01:31,  1.34it/s, avg=0.12032, loss=0.09713]

trial_001 train e001:  18%|█████████████████                                                                             | 27/149 [00:20<01:32,  1.32it/s, avg=0.12032, loss=0.09713]

trial_001 train e001:  18%|█████████████████                                                                             | 27/149 [00:21<01:32,  1.32it/s, avg=0.11994, loss=0.10954]

trial_001 train e001:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:30,  1.34it/s, avg=0.11994, loss=0.10954]

trial_001 train e001:  19%|█████████████████▋                                                                            | 28/149 [00:22<01:30,  1.34it/s, avg=0.11986, loss=0.11781]

trial_001 train e001:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:29,  1.34it/s, avg=0.11986, loss=0.11781]

trial_001 train e001:  19%|██████████████████▎                                                                           | 29/149 [00:23<01:29,  1.34it/s, avg=0.11927, loss=0.10206]

trial_001 train e001:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:29,  1.33it/s, avg=0.11927, loss=0.10206]

trial_001 train e001:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:29,  1.33it/s, avg=0.11866, loss=0.10028]

trial_001 train e001:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.34it/s, avg=0.11866, loss=0.10028]

trial_001 train e001:  21%|███████████████████▌                                                                          | 31/149 [00:24<01:27,  1.34it/s, avg=0.11852, loss=0.11420]

trial_001 train e001:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:26,  1.35it/s, avg=0.11852, loss=0.11420]

trial_001 train e001:  21%|████████████████████▏                                                                         | 32/149 [00:25<01:26,  1.35it/s, avg=0.11892, loss=0.13176]

trial_001 train e001:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:25,  1.36it/s, avg=0.11892, loss=0.13176]

trial_001 train e001:  22%|████████████████████▊                                                                         | 33/149 [00:26<01:25,  1.36it/s, avg=0.11845, loss=0.10284]

trial_001 train e001:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:24,  1.37it/s, avg=0.11845, loss=0.10284]

trial_001 train e001:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:24,  1.37it/s, avg=0.11861, loss=0.12418]

trial_001 train e001:  23%|██████████████████████                                                                        | 35/149 [00:26<01:21,  1.41it/s, avg=0.11861, loss=0.12418]

trial_001 train e001:  23%|██████████████████████                                                                        | 35/149 [00:27<01:21,  1.41it/s, avg=0.11884, loss=0.12670]

trial_001 train e001:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:20,  1.41it/s, avg=0.11884, loss=0.12670]

trial_001 train e001:  24%|██████████████████████▋                                                                       | 36/149 [00:28<01:20,  1.41it/s, avg=0.11866, loss=0.11213]

trial_001 train e001:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:18,  1.42it/s, avg=0.11866, loss=0.11213]

trial_001 train e001:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:18,  1.42it/s, avg=0.11843, loss=0.11015]

trial_001 train e001:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:19,  1.40it/s, avg=0.11843, loss=0.11015]

trial_001 train e001:  26%|███████████████████████▉                                                                      | 38/149 [00:29<01:19,  1.40it/s, avg=0.11824, loss=0.11085]

trial_001 train e001:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:17,  1.41it/s, avg=0.11824, loss=0.11085]

trial_001 train e001:  26%|████████████████████████▌                                                                     | 39/149 [00:30<01:17,  1.41it/s, avg=0.11765, loss=0.09458]

trial_001 train e001:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:18,  1.38it/s, avg=0.11765, loss=0.09458]

trial_001 train e001:  27%|█████████████████████████▏                                                                    | 40/149 [00:31<01:18,  1.38it/s, avg=0.11776, loss=0.12247]

trial_001 train e001:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:18,  1.38it/s, avg=0.11776, loss=0.12247]

trial_001 train e001:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:18,  1.38it/s, avg=0.11819, loss=0.13578]

trial_001 train e001:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:19,  1.35it/s, avg=0.11819, loss=0.13578]

trial_001 train e001:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:19,  1.35it/s, avg=0.11838, loss=0.12606]

trial_001 train e001:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:15,  1.40it/s, avg=0.11838, loss=0.12606]

trial_001 train e001:  29%|███████████████████████████▏                                                                  | 43/149 [00:33<01:15,  1.40it/s, avg=0.11773, loss=0.08990]

trial_001 train e001:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:15,  1.39it/s, avg=0.11773, loss=0.08990]

trial_001 train e001:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:15,  1.39it/s, avg=0.11738, loss=0.10224]

trial_001 train e001:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.38it/s, avg=0.11738, loss=0.10224]

trial_001 train e001:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:15,  1.38it/s, avg=0.11727, loss=0.11216]

trial_001 train e001:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:14,  1.38it/s, avg=0.11727, loss=0.11216]

trial_001 train e001:  31%|█████████████████████████████                                                                 | 46/149 [00:35<01:14,  1.38it/s, avg=0.11729, loss=0.11807]

trial_001 train e001:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:13,  1.39it/s, avg=0.11729, loss=0.11807]

trial_001 train e001:  32%|█████████████████████████████▋                                                                | 47/149 [00:36<01:13,  1.39it/s, avg=0.11709, loss=0.10800]

trial_001 train e001:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:12,  1.38it/s, avg=0.11709, loss=0.10800]

trial_001 train e001:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:12,  1.38it/s, avg=0.11666, loss=0.09601]

trial_001 train e001:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:10,  1.43it/s, avg=0.11666, loss=0.09601]

trial_001 train e001:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:10,  1.43it/s, avg=0.11666, loss=0.11667]

trial_001 train e001:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:09,  1.43it/s, avg=0.11666, loss=0.11667]

trial_001 train e001:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:09,  1.43it/s, avg=0.11670, loss=0.11830]

trial_001 train e001:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:08,  1.43it/s, avg=0.11670, loss=0.11830]

trial_001 train e001:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:08,  1.43it/s, avg=0.11667, loss=0.11558]

trial_001 train e001:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:08,  1.41it/s, avg=0.11667, loss=0.11558]

trial_001 train e001:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:08,  1.41it/s, avg=0.11640, loss=0.10188]

trial_001 train e001:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:08,  1.41it/s, avg=0.11640, loss=0.10188]

trial_001 train e001:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:08,  1.41it/s, avg=0.11627, loss=0.10969]

trial_001 train e001:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:08,  1.39it/s, avg=0.11627, loss=0.10969]

trial_001 train e001:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:08,  1.39it/s, avg=0.11608, loss=0.10597]

trial_001 train e001:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:08,  1.36it/s, avg=0.11608, loss=0.10597]

trial_001 train e001:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:08,  1.36it/s, avg=0.11585, loss=0.10294]

trial_001 train e001:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.37it/s, avg=0.11585, loss=0.10294]

trial_001 train e001:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:07,  1.37it/s, avg=0.11570, loss=0.10707]

trial_001 train e001:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:07,  1.36it/s, avg=0.11570, loss=0.10707]

trial_001 train e001:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:07,  1.36it/s, avg=0.11596, loss=0.13111]

trial_001 train e001:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:07,  1.34it/s, avg=0.11596, loss=0.13111]

trial_001 train e001:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:07,  1.34it/s, avg=0.11570, loss=0.10047]

trial_001 train e001:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:07,  1.34it/s, avg=0.11570, loss=0.10047]

trial_001 train e001:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:07,  1.34it/s, avg=0.11550, loss=0.10370]

trial_001 train e001:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.35it/s, avg=0.11550, loss=0.10370]

trial_001 train e001:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:05,  1.35it/s, avg=0.11541, loss=0.11032]

trial_001 train e001:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:05,  1.34it/s, avg=0.11541, loss=0.11032]

trial_001 train e001:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:05,  1.34it/s, avg=0.11528, loss=0.10702]

trial_001 train e001:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.35it/s, avg=0.11528, loss=0.10702]

trial_001 train e001:  42%|███████████████████████████████████████                                                       | 62/149 [00:47<01:04,  1.35it/s, avg=0.11497, loss=0.09575]

trial_001 train e001:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:03,  1.36it/s, avg=0.11497, loss=0.09575]

trial_001 train e001:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:03,  1.36it/s, avg=0.11523, loss=0.13200]

trial_001 train e001:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:02,  1.36it/s, avg=0.11523, loss=0.13200]

trial_001 train e001:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:02,  1.36it/s, avg=0.11551, loss=0.13320]

trial_001 train e001:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:02,  1.35it/s, avg=0.11551, loss=0.13320]

trial_001 train e001:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:02,  1.35it/s, avg=0.11535, loss=0.10465]

trial_001 train e001:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:01,  1.34it/s, avg=0.11535, loss=0.10465]

trial_001 train e001:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:50<01:01,  1.34it/s, avg=0.11539, loss=0.11838]

trial_001 train e001:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:01,  1.33it/s, avg=0.11539, loss=0.11838]

trial_001 train e001:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:01,  1.33it/s, avg=0.11508, loss=0.09447]

trial_001 train e001:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<01:01,  1.32it/s, avg=0.11508, loss=0.09447]

trial_001 train e001:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:01,  1.32it/s, avg=0.11507, loss=0.11396]

trial_001 train e001:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<01:00,  1.33it/s, avg=0.11507, loss=0.11396]

trial_001 train e001:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<01:00,  1.33it/s, avg=0.11480, loss=0.09604]

trial_001 train e001:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:59,  1.33it/s, avg=0.11480, loss=0.09604]

trial_001 train e001:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:53<00:59,  1.33it/s, avg=0.11469, loss=0.10734]

trial_001 train e001:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:57,  1.35it/s, avg=0.11469, loss=0.10734]

trial_001 train e001:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:57,  1.35it/s, avg=0.11494, loss=0.13277]

trial_001 train e001:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:56,  1.37it/s, avg=0.11494, loss=0.13277]

trial_001 train e001:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:56,  1.37it/s, avg=0.11478, loss=0.10312]

trial_001 train e001:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:55,  1.37it/s, avg=0.11478, loss=0.10312]

trial_001 train e001:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:55,  1.37it/s, avg=0.11480, loss=0.11643]

trial_001 train e001:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:55,  1.36it/s, avg=0.11480, loss=0.11643]

trial_001 train e001:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:55,  1.36it/s, avg=0.11493, loss=0.12409]

trial_001 train e001:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:54,  1.37it/s, avg=0.11493, loss=0.12409]

trial_001 train e001:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:54,  1.37it/s, avg=0.11486, loss=0.11008]

trial_001 train e001:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:52,  1.39it/s, avg=0.11486, loss=0.11008]

trial_001 train e001:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:52,  1.39it/s, avg=0.11458, loss=0.09281]

trial_001 train e001:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:51,  1.39it/s, avg=0.11458, loss=0.09281]

trial_001 train e001:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:51,  1.39it/s, avg=0.11453, loss=0.11128]

trial_001 train e001:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:52,  1.36it/s, avg=0.11453, loss=0.11128]

trial_001 train e001:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:52,  1.36it/s, avg=0.11446, loss=0.10892]

trial_001 train e001:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:52,  1.34it/s, avg=0.11446, loss=0.10892]

trial_001 train e001:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:52,  1.34it/s, avg=0.11453, loss=0.11994]

trial_001 train e001:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:52,  1.31it/s, avg=0.11453, loss=0.11994]

trial_001 train e001:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:52,  1.31it/s, avg=0.11459, loss=0.11955]

trial_001 train e001:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:51,  1.32it/s, avg=0.11459, loss=0.11955]

trial_001 train e001:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:51,  1.32it/s, avg=0.11438, loss=0.09680]

trial_001 train e001:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:51,  1.31it/s, avg=0.11438, loss=0.09680]

trial_001 train e001:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:51,  1.31it/s, avg=0.11421, loss=0.10069]

trial_001 train e001:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:50,  1.32it/s, avg=0.11421, loss=0.10069]

trial_001 train e001:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:50,  1.32it/s, avg=0.11405, loss=0.10075]

trial_001 train e001:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:49,  1.31it/s, avg=0.11405, loss=0.10075]

trial_001 train e001:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:49,  1.31it/s, avg=0.11379, loss=0.09160]

trial_001 train e001:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:48,  1.31it/s, avg=0.11379, loss=0.09160]

trial_001 train e001:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:48,  1.31it/s, avg=0.11396, loss=0.12908]

trial_001 train e001:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:47,  1.33it/s, avg=0.11396, loss=0.12908]

trial_001 train e001:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:47,  1.33it/s, avg=0.11382, loss=0.10119]

trial_001 train e001:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:46,  1.33it/s, avg=0.11382, loss=0.10119]

trial_001 train e001:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:46,  1.33it/s, avg=0.11398, loss=0.12808]

trial_001 train e001:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:45,  1.35it/s, avg=0.11398, loss=0.12808]

trial_001 train e001:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:45,  1.35it/s, avg=0.11369, loss=0.08852]

trial_001 train e001:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.34it/s, avg=0.11369, loss=0.08852]

trial_001 train e001:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:44,  1.34it/s, avg=0.11363, loss=0.10752]

trial_001 train e001:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:43,  1.36it/s, avg=0.11363, loss=0.10752]

trial_001 train e001:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:43,  1.36it/s, avg=0.11325, loss=0.07994]

trial_001 train e001:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.36it/s, avg=0.11325, loss=0.07994]

trial_001 train e001:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:42,  1.36it/s, avg=0.11318, loss=0.10644]

trial_001 train e001:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:42,  1.36it/s, avg=0.11318, loss=0.10644]

trial_001 train e001:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:42,  1.36it/s, avg=0.11313, loss=0.10874]

trial_001 train e001:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:41,  1.35it/s, avg=0.11313, loss=0.10874]

trial_001 train e001:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:41,  1.35it/s, avg=0.11316, loss=0.11550]

trial_001 train e001:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:41,  1.33it/s, avg=0.11316, loss=0.11550]

trial_001 train e001:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:41,  1.33it/s, avg=0.11297, loss=0.09541]

trial_001 train e001:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:40,  1.32it/s, avg=0.11297, loss=0.09541]

trial_001 train e001:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:40,  1.32it/s, avg=0.11306, loss=0.12147]

trial_001 train e001:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:39,  1.33it/s, avg=0.11306, loss=0.12147]

trial_001 train e001:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.33it/s, avg=0.11301, loss=0.10850]

trial_001 train e001:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.35it/s, avg=0.11301, loss=0.10850]

trial_001 train e001:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:38,  1.35it/s, avg=0.11281, loss=0.09294]

trial_001 train e001:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:37,  1.35it/s, avg=0.11281, loss=0.09294]

trial_001 train e001:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:37,  1.35it/s, avg=0.11275, loss=0.10705]

trial_001 train e001:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.37it/s, avg=0.11275, loss=0.10705]

trial_001 train e001:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:36,  1.37it/s, avg=0.11276, loss=0.11347]

trial_001 train e001:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:36,  1.35it/s, avg=0.11276, loss=0.11347]

trial_001 train e001:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:36,  1.35it/s, avg=0.11267, loss=0.10399]

trial_001 train e001:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:35,  1.35it/s, avg=0.11267, loss=0.10399]

trial_001 train e001:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:35,  1.35it/s, avg=0.11245, loss=0.09007]

trial_001 train e001:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:35,  1.34it/s, avg=0.11245, loss=0.09007]

trial_001 train e001:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:35,  1.34it/s, avg=0.11236, loss=0.10304]

trial_001 train e001:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:34,  1.34it/s, avg=0.11236, loss=0.10304]

trial_001 train e001:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:34,  1.34it/s, avg=0.11218, loss=0.09339]

trial_001 train e001:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:33,  1.36it/s, avg=0.11218, loss=0.09339]

trial_001 train e001:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.36it/s, avg=0.11195, loss=0.08882]

trial_001 train e001:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:32,  1.36it/s, avg=0.11195, loss=0.08882]

trial_001 train e001:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:32,  1.36it/s, avg=0.11189, loss=0.10478]

trial_001 train e001:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:32,  1.34it/s, avg=0.11189, loss=0.10478]

trial_001 train e001:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:32,  1.34it/s, avg=0.11182, loss=0.10458]

trial_001 train e001:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:30,  1.36it/s, avg=0.11182, loss=0.10458]

trial_001 train e001:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:30,  1.36it/s, avg=0.11184, loss=0.11424]

trial_001 train e001:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:30,  1.35it/s, avg=0.11184, loss=0.11424]

trial_001 train e001:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.35it/s, avg=0.11172, loss=0.09899]

trial_001 train e001:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:29,  1.35it/s, avg=0.11172, loss=0.09899]

trial_001 train e001:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:29,  1.35it/s, avg=0.11158, loss=0.09619]

trial_001 train e001:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:28,  1.35it/s, avg=0.11158, loss=0.09619]

trial_001 train e001:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:28,  1.35it/s, avg=0.11158, loss=0.11208]

trial_001 train e001:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:27,  1.36it/s, avg=0.11158, loss=0.11208]

trial_001 train e001:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:27,  1.36it/s, avg=0.11142, loss=0.09294]

trial_001 train e001:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:27,  1.35it/s, avg=0.11142, loss=0.09294]

trial_001 train e001:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:27,  1.35it/s, avg=0.11142, loss=0.11208]

trial_001 train e001:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:27,  1.33it/s, avg=0.11142, loss=0.11208]

trial_001 train e001:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:27,  1.33it/s, avg=0.11128, loss=0.09537]

trial_001 train e001:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.36it/s, avg=0.11128, loss=0.09537]

trial_001 train e001:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:25,  1.36it/s, avg=0.11118, loss=0.09981]

trial_001 train e001:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:25<00:25,  1.35it/s, avg=0.11118, loss=0.09981]

trial_001 train e001:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.35it/s, avg=0.11119, loss=0.11148]

trial_001 train e001:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:26<00:24,  1.36it/s, avg=0.11119, loss=0.11148]

trial_001 train e001:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.36it/s, avg=0.11116, loss=0.10786]

trial_001 train e001:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:23,  1.33it/s, avg=0.11116, loss=0.10786]

trial_001 train e001:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:23,  1.33it/s, avg=0.11114, loss=0.10898]

trial_001 train e001:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:23,  1.33it/s, avg=0.11114, loss=0.10898]

trial_001 train e001:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.33it/s, avg=0.11108, loss=0.10360]

trial_001 train e001:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:28<00:22,  1.33it/s, avg=0.11108, loss=0.10360]

trial_001 train e001:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.33it/s, avg=0.11109, loss=0.11320]

trial_001 train e001:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:29<00:21,  1.33it/s, avg=0.11109, loss=0.11320]

trial_001 train e001:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.33it/s, avg=0.11100, loss=0.09974]

trial_001 train e001:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:20,  1.35it/s, avg=0.11100, loss=0.09974]

trial_001 train e001:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:20,  1.35it/s, avg=0.11084, loss=0.09152]

trial_001 train e001:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:20,  1.33it/s, avg=0.11084, loss=0.09152]

trial_001 train e001:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:20,  1.33it/s, avg=0.11080, loss=0.10558]

trial_001 train e001:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:31<00:19,  1.32it/s, avg=0.11080, loss=0.10558]

trial_001 train e001:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.32it/s, avg=0.11074, loss=0.10350]

trial_001 train e001:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:32<00:18,  1.34it/s, avg=0.11074, loss=0.10350]

trial_001 train e001:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:18,  1.34it/s, avg=0.11068, loss=0.10299]

trial_001 train e001:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.35it/s, avg=0.11068, loss=0.10299]

trial_001 train e001:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.35it/s, avg=0.11057, loss=0.09695]

trial_001 train e001:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:17,  1.35it/s, avg=0.11057, loss=0.09695]

trial_001 train e001:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:17,  1.35it/s, avg=0.11050, loss=0.10163]

trial_001 train e001:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:34<00:16,  1.33it/s, avg=0.11050, loss=0.10163]

trial_001 train e001:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.33it/s, avg=0.11047, loss=0.10655]

trial_001 train e001:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:35<00:15,  1.34it/s, avg=0.11047, loss=0.10655]

trial_001 train e001:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.34it/s, avg=0.11048, loss=0.11232]

trial_001 train e001:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:14,  1.34it/s, avg=0.11048, loss=0.11232]

trial_001 train e001:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:14,  1.34it/s, avg=0.11044, loss=0.10543]

trial_001 train e001:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:14,  1.33it/s, avg=0.11044, loss=0.10543]

trial_001 train e001:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.33it/s, avg=0.11034, loss=0.09720]

trial_001 train e001:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:37<00:13,  1.30it/s, avg=0.11034, loss=0.09720]

trial_001 train e001:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.30it/s, avg=0.11022, loss=0.09382]

trial_001 train e001:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:38<00:13,  1.30it/s, avg=0.11022, loss=0.09382]

trial_001 train e001:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:13,  1.30it/s, avg=0.11021, loss=0.10987]

trial_001 train e001:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:12,  1.33it/s, avg=0.11021, loss=0.10987]

trial_001 train e001:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:12,  1.33it/s, avg=0.11007, loss=0.09038]

trial_001 train e001:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:39<00:11,  1.34it/s, avg=0.11007, loss=0.09038]

trial_001 train e001:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:11,  1.34it/s, avg=0.10993, loss=0.09202]

trial_001 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:40<00:10,  1.34it/s, avg=0.10993, loss=0.09202]

trial_001 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.34it/s, avg=0.10988, loss=0.10349]

trial_001 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:41<00:09,  1.33it/s, avg=0.10988, loss=0.10349]

trial_001 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.33it/s, avg=0.10982, loss=0.10046]

trial_001 train e001:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:08,  1.34it/s, avg=0.10982, loss=0.10046]

trial_001 train e001:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:08,  1.34it/s, avg=0.10983, loss=0.11140]

trial_001 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:42<00:08,  1.35it/s, avg=0.10983, loss=0.11140]

trial_001 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.35it/s, avg=0.10972, loss=0.09526]

trial_001 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:43<00:07,  1.34it/s, avg=0.10972, loss=0.09526]

trial_001 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.34it/s, avg=0.10965, loss=0.09988]

trial_001 train e001:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:44<00:06,  1.34it/s, avg=0.10965, loss=0.09988]

trial_001 train e001:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.34it/s, avg=0.10963, loss=0.10675]

trial_001 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:05,  1.34it/s, avg=0.10963, loss=0.10675]

trial_001 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:05,  1.34it/s, avg=0.10955, loss=0.09819]

trial_001 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:45<00:05,  1.35it/s, avg=0.10955, loss=0.09819]

trial_001 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.35it/s, avg=0.10962, loss=0.11879]

trial_001 train e001:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:46<00:04,  1.35it/s, avg=0.10962, loss=0.11879]

trial_001 train e001:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.35it/s, avg=0.10961, loss=0.10858]

trial_001 train e001:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:47<00:03,  1.37it/s, avg=0.10961, loss=0.10858]

trial_001 train e001:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.37it/s, avg=0.10958, loss=0.10504]

trial_001 train e001:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:02,  1.35it/s, avg=0.10958, loss=0.10504]

trial_001 train e001:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:02,  1.35it/s, avg=0.10950, loss=0.09874]

trial_001 train e001:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:48<00:02,  1.36it/s, avg=0.10950, loss=0.09874]

trial_001 train e001:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.36it/s, avg=0.10933, loss=0.08469]

trial_001 train e001:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:49<00:01,  1.34it/s, avg=0.10933, loss=0.08469]

trial_001 train e001:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.34it/s, avg=0.10924, loss=0.09497]

trial_001 train e001:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:50<00:00,  1.35it/s, avg=0.10924, loss=0.09497]

trial_001 train e001:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:50<00:00,  1.35it/s, avg=0.10922, loss=0.10162]

trial_001 train e001: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:50<00:00,  1.62it/s, avg=0.10922, loss=0.10162]

trial_001 val e001:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e001:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.38it/s]

trial_001 val e001:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.32it/s]

trial_001 val e001:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.30it/s]

trial_001 val e001:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.31it/s]

trial_001 val e001:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.32it/s]

trial_001 val e001:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.32it/s]

trial_001 val e001:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:18,  2.30it/s]

trial_001 val e001:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:18,  2.28it/s]

trial_001 val e001:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:18,  2.23it/s]

trial_001 val e001:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.24it/s]

trial_001 val e001:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:17,  2.22it/s]

trial_001 val e001:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:17,  2.22it/s]

trial_001 val e001:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:16,  2.24it/s]

trial_001 val e001:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.26it/s]

trial_001 val e001:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.27it/s]

trial_001 val e001:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:07<00:14,  2.28it/s]

trial_001 val e001:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.28it/s]

trial_001 val e001:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:14,  2.27it/s]

trial_001 val e001:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.27it/s]

trial_001 val e001:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:13,  2.26it/s]

trial_001 val e001:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.26it/s]

trial_001 val e001:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.27it/s]

trial_001 val e001:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:10<00:11,  2.27it/s]

trial_001 val e001:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.28it/s]

trial_001 val e001:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:11<00:10,  2.28it/s]

trial_001 val e001:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.28it/s]

trial_001 val e001:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:10,  2.28it/s]

trial_001 val e001:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.28it/s]

trial_001 val e001:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.28it/s]

trial_001 val e001:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:13<00:08,  2.26it/s]

trial_001 val e001:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.26it/s]

trial_001 val e001:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:14<00:08,  2.24it/s]

trial_001 val e001:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.20it/s]

trial_001 val e001:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:15<00:07,  2.23it/s]

trial_001 val e001:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.24it/s]

trial_001 val e001:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.26it/s]

trial_001 val e001:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:16<00:05,  2.26it/s]

trial_001 val e001:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.26it/s]

trial_001 val e001:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:17<00:04,  2.27it/s]

trial_001 val e001:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.26it/s]

trial_001 val e001:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:18<00:03,  2.27it/s]

trial_001 val e001:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.27it/s]

trial_001 val e001:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.28it/s]

trial_001 val e001:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.26it/s]

trial_001 val e001:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.24it/s]

trial_001 val e001:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:20<00:01,  2.26it/s]

trial_001 val e001:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.27it/s]

trial_001 val e001:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:21<00:00,  2.27it/s]

trial_001 val e001:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.27it/s]

trial_001 val e001: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:22<00:00,  2.28it/s]

[2026-05-28 20:05:31] [trial_001] epoch=001 | train_loss=0.109216 | val_MAE=0.103300 | val_S=0.896700 | best_S=0.896700 @epoch=1 | patience=0/5

[trial_001] epochs:   1%|█▏                                                                                                                       | 1/100 [02:13<3:40:33, 133.67s/it]

trial_001 train e002:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e002:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10809, loss=0.10809]

trial_001 train e002:   1%|▋                                                                                              | 1/149 [00:00<01:50,  1.33it/s, avg=0.10809, loss=0.10809]

trial_001 train e002:   1%|▋                                                                                              | 1/149 [00:01<01:50,  1.33it/s, avg=0.10206, loss=0.09603]

trial_001 train e002:   1%|█▎                                                                                             | 2/149 [00:01<01:51,  1.32it/s, avg=0.10206, loss=0.09603]

trial_001 train e002:   1%|█▎                                                                                             | 2/149 [00:02<01:51,  1.32it/s, avg=0.10500, loss=0.11086]

trial_001 train e002:   2%|█▉                                                                                             | 3/149 [00:02<01:53,  1.28it/s, avg=0.10500, loss=0.11086]

trial_001 train e002:   2%|█▉                                                                                             | 3/149 [00:03<01:53,  1.28it/s, avg=0.10063, loss=0.08752]

trial_001 train e002:   3%|██▌                                                                                            | 4/149 [00:03<01:54,  1.26it/s, avg=0.10063, loss=0.08752]

trial_001 train e002:   3%|██▌                                                                                            | 4/149 [00:03<01:54,  1.26it/s, avg=0.10237, loss=0.10934]

trial_001 train e002:   3%|███▏                                                                                           | 5/149 [00:03<01:52,  1.28it/s, avg=0.10237, loss=0.10934]

trial_001 train e002:   3%|███▏                                                                                           | 5/149 [00:04<01:52,  1.28it/s, avg=0.10172, loss=0.09850]

trial_001 train e002:   4%|███▊                                                                                           | 6/149 [00:04<01:47,  1.32it/s, avg=0.10172, loss=0.09850]

trial_001 train e002:   4%|███▊                                                                                           | 6/149 [00:05<01:47,  1.32it/s, avg=0.10298, loss=0.11051]

trial_001 train e002:   5%|████▍                                                                                          | 7/149 [00:05<01:47,  1.32it/s, avg=0.10298, loss=0.11051]

trial_001 train e002:   5%|████▍                                                                                          | 7/149 [00:06<01:47,  1.32it/s, avg=0.10252, loss=0.09930]

trial_001 train e002:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.35it/s, avg=0.10252, loss=0.09930]

trial_001 train e002:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.35it/s, avg=0.10220, loss=0.09962]

trial_001 train e002:   6%|█████▋                                                                                         | 9/149 [00:06<01:45,  1.32it/s, avg=0.10220, loss=0.09962]

trial_001 train e002:   6%|█████▋                                                                                         | 9/149 [00:07<01:45,  1.32it/s, avg=0.10228, loss=0.10297]

trial_001 train e002:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.36it/s, avg=0.10228, loss=0.10297]

trial_001 train e002:   7%|██████▎                                                                                       | 10/149 [00:08<01:42,  1.36it/s, avg=0.10256, loss=0.10536]

trial_001 train e002:   7%|██████▉                                                                                       | 11/149 [00:08<01:41,  1.35it/s, avg=0.10256, loss=0.10536]

trial_001 train e002:   7%|██████▉                                                                                       | 11/149 [00:09<01:41,  1.35it/s, avg=0.10291, loss=0.10681]

trial_001 train e002:   8%|███████▌                                                                                      | 12/149 [00:09<01:41,  1.35it/s, avg=0.10291, loss=0.10681]

trial_001 train e002:   8%|███████▌                                                                                      | 12/149 [00:09<01:41,  1.35it/s, avg=0.10251, loss=0.09772]

trial_001 train e002:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.35it/s, avg=0.10251, loss=0.09772]

trial_001 train e002:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.35it/s, avg=0.10183, loss=0.09302]

trial_001 train e002:   9%|████████▊                                                                                     | 14/149 [00:10<01:40,  1.34it/s, avg=0.10183, loss=0.09302]

trial_001 train e002:   9%|████████▊                                                                                     | 14/149 [00:11<01:40,  1.34it/s, avg=0.10229, loss=0.10875]

trial_001 train e002:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.33it/s, avg=0.10229, loss=0.10875]

trial_001 train e002:  10%|█████████▍                                                                                    | 15/149 [00:12<01:40,  1.33it/s, avg=0.10157, loss=0.09075]

trial_001 train e002:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.35it/s, avg=0.10157, loss=0.09075]

trial_001 train e002:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.35it/s, avg=0.10107, loss=0.09303]

trial_001 train e002:  11%|██████████▋                                                                                   | 17/149 [00:12<01:39,  1.33it/s, avg=0.10107, loss=0.09303]

trial_001 train e002:  11%|██████████▋                                                                                   | 17/149 [00:13<01:39,  1.33it/s, avg=0.10128, loss=0.10481]

trial_001 train e002:  12%|███████████▎                                                                                  | 18/149 [00:13<01:39,  1.32it/s, avg=0.10128, loss=0.10481]

trial_001 train e002:  12%|███████████▎                                                                                  | 18/149 [00:14<01:39,  1.32it/s, avg=0.10193, loss=0.11363]

trial_001 train e002:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.37it/s, avg=0.10193, loss=0.11363]

trial_001 train e002:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.37it/s, avg=0.10139, loss=0.09107]

trial_001 train e002:  13%|████████████▌                                                                                 | 20/149 [00:14<01:34,  1.36it/s, avg=0.10139, loss=0.09107]

trial_001 train e002:  13%|████████████▌                                                                                 | 20/149 [00:15<01:34,  1.36it/s, avg=0.10078, loss=0.08869]

trial_001 train e002:  14%|█████████████▏                                                                                | 21/149 [00:15<01:33,  1.37it/s, avg=0.10078, loss=0.08869]

trial_001 train e002:  14%|█████████████▏                                                                                | 21/149 [00:16<01:33,  1.37it/s, avg=0.10039, loss=0.09223]

trial_001 train e002:  15%|█████████████▉                                                                                | 22/149 [00:16<01:32,  1.37it/s, avg=0.10039, loss=0.09223]

trial_001 train e002:  15%|█████████████▉                                                                                | 22/149 [00:17<01:32,  1.37it/s, avg=0.10018, loss=0.09551]

trial_001 train e002:  15%|██████████████▌                                                                               | 23/149 [00:17<01:28,  1.42it/s, avg=0.10018, loss=0.09551]

trial_001 train e002:  15%|██████████████▌                                                                               | 23/149 [00:17<01:28,  1.42it/s, avg=0.10015, loss=0.09957]

trial_001 train e002:  16%|███████████████▏                                                                              | 24/149 [00:17<01:29,  1.39it/s, avg=0.10015, loss=0.09957]

trial_001 train e002:  16%|███████████████▏                                                                              | 24/149 [00:18<01:29,  1.39it/s, avg=0.09998, loss=0.09581]

trial_001 train e002:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.36it/s, avg=0.09998, loss=0.09581]

trial_001 train e002:  17%|███████████████▊                                                                              | 25/149 [00:19<01:31,  1.36it/s, avg=0.10067, loss=0.11779]

trial_001 train e002:  17%|████████████████▍                                                                             | 26/149 [00:19<01:31,  1.34it/s, avg=0.10067, loss=0.11779]

trial_001 train e002:  17%|████████████████▍                                                                             | 26/149 [00:20<01:31,  1.34it/s, avg=0.10043, loss=0.09438]

trial_001 train e002:  18%|█████████████████                                                                             | 27/149 [00:20<01:31,  1.33it/s, avg=0.10043, loss=0.09438]

trial_001 train e002:  18%|█████████████████                                                                             | 27/149 [00:20<01:31,  1.33it/s, avg=0.10051, loss=0.10250]

trial_001 train e002:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:30,  1.33it/s, avg=0.10051, loss=0.10250]

trial_001 train e002:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:30,  1.33it/s, avg=0.10070, loss=0.10622]

trial_001 train e002:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:30,  1.33it/s, avg=0.10070, loss=0.10622]

trial_001 train e002:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:30,  1.33it/s, avg=0.10038, loss=0.09109]

trial_001 train e002:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:30,  1.31it/s, avg=0.10038, loss=0.09109]

trial_001 train e002:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:30,  1.31it/s, avg=0.09989, loss=0.08501]

trial_001 train e002:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:29,  1.32it/s, avg=0.09989, loss=0.08501]

trial_001 train e002:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:29,  1.32it/s, avg=0.09988, loss=0.09976]

trial_001 train e002:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:28,  1.33it/s, avg=0.09988, loss=0.09976]

trial_001 train e002:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:28,  1.33it/s, avg=0.09993, loss=0.10135]

trial_001 train e002:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:27,  1.32it/s, avg=0.09993, loss=0.10135]

trial_001 train e002:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:27,  1.32it/s, avg=0.09974, loss=0.09371]

trial_001 train e002:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.35it/s, avg=0.09974, loss=0.09371]

trial_001 train e002:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:24,  1.35it/s, avg=0.09951, loss=0.09154]

trial_001 train e002:  23%|██████████████████████                                                                        | 35/149 [00:26<01:25,  1.34it/s, avg=0.09951, loss=0.09154]

trial_001 train e002:  23%|██████████████████████                                                                        | 35/149 [00:26<01:25,  1.34it/s, avg=0.09958, loss=0.10197]

trial_001 train e002:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:23,  1.35it/s, avg=0.09958, loss=0.10197]

trial_001 train e002:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:23,  1.35it/s, avg=0.09950, loss=0.09667]

trial_001 train e002:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:23,  1.35it/s, avg=0.09950, loss=0.09667]

trial_001 train e002:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:23,  1.35it/s, avg=0.09962, loss=0.10422]

trial_001 train e002:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:21,  1.37it/s, avg=0.09962, loss=0.10422]

trial_001 train e002:  26%|███████████████████████▉                                                                      | 38/149 [00:29<01:21,  1.37it/s, avg=0.10034, loss=0.12764]

trial_001 train e002:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:20,  1.37it/s, avg=0.10034, loss=0.12764]

trial_001 train e002:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:20,  1.37it/s, avg=0.10033, loss=0.09987]

trial_001 train e002:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:22,  1.33it/s, avg=0.10033, loss=0.09987]

trial_001 train e002:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:22,  1.33it/s, avg=0.10024, loss=0.09668]

trial_001 train e002:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:22,  1.31it/s, avg=0.10024, loss=0.09668]

trial_001 train e002:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:22,  1.31it/s, avg=0.10051, loss=0.11147]

trial_001 train e002:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:22,  1.30it/s, avg=0.10051, loss=0.11147]

trial_001 train e002:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:22,  1.30it/s, avg=0.10076, loss=0.11141]

trial_001 train e002:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:20,  1.32it/s, avg=0.10076, loss=0.11141]

trial_001 train e002:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:20,  1.32it/s, avg=0.10065, loss=0.09579]

trial_001 train e002:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:19,  1.33it/s, avg=0.10065, loss=0.09579]

trial_001 train e002:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:19,  1.33it/s, avg=0.10045, loss=0.09180]

trial_001 train e002:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:18,  1.33it/s, avg=0.10045, loss=0.09180]

trial_001 train e002:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:18,  1.33it/s, avg=0.10042, loss=0.09892]

trial_001 train e002:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:17,  1.33it/s, avg=0.10042, loss=0.09892]

trial_001 train e002:  31%|█████████████████████████████                                                                 | 46/149 [00:35<01:17,  1.33it/s, avg=0.10034, loss=0.09680]

trial_001 train e002:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:18,  1.31it/s, avg=0.10034, loss=0.09680]

trial_001 train e002:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:18,  1.31it/s, avg=0.10037, loss=0.10161]

trial_001 train e002:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:17,  1.30it/s, avg=0.10037, loss=0.10161]

trial_001 train e002:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:17,  1.30it/s, avg=0.10045, loss=0.10412]

trial_001 train e002:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:16,  1.31it/s, avg=0.10045, loss=0.10412]

trial_001 train e002:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:16,  1.31it/s, avg=0.10043, loss=0.09982]

trial_001 train e002:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:15,  1.32it/s, avg=0.10043, loss=0.09982]

trial_001 train e002:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:15,  1.32it/s, avg=0.10033, loss=0.09543]

trial_001 train e002:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:14,  1.32it/s, avg=0.10033, loss=0.09543]

trial_001 train e002:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:14,  1.32it/s, avg=0.10015, loss=0.09066]

trial_001 train e002:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:13,  1.32it/s, avg=0.10015, loss=0.09066]

trial_001 train e002:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:13,  1.32it/s, avg=0.10018, loss=0.10185]

trial_001 train e002:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:13,  1.31it/s, avg=0.10018, loss=0.10185]

trial_001 train e002:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:13,  1.31it/s, avg=0.10028, loss=0.10558]

trial_001 train e002:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:10,  1.34it/s, avg=0.10028, loss=0.10558]

trial_001 train e002:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:10,  1.34it/s, avg=0.10016, loss=0.09373]

trial_001 train e002:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:11,  1.32it/s, avg=0.10016, loss=0.09373]

trial_001 train e002:  37%|██████████████████████████████████▋                                                           | 55/149 [00:42<01:11,  1.32it/s, avg=0.10034, loss=0.11025]

trial_001 train e002:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:11,  1.31it/s, avg=0.10034, loss=0.11025]

trial_001 train e002:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:11,  1.31it/s, avg=0.10065, loss=0.11798]

trial_001 train e002:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:09,  1.32it/s, avg=0.10065, loss=0.11798]

trial_001 train e002:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:09,  1.32it/s, avg=0.10066, loss=0.10089]

trial_001 train e002:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:08,  1.32it/s, avg=0.10066, loss=0.10089]

trial_001 train e002:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:08,  1.32it/s, avg=0.10067, loss=0.10152]

trial_001 train e002:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:07,  1.34it/s, avg=0.10067, loss=0.10152]

trial_001 train e002:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:45<01:07,  1.34it/s, avg=0.10068, loss=0.10120]

trial_001 train e002:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:06,  1.34it/s, avg=0.10068, loss=0.10120]

trial_001 train e002:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:06,  1.34it/s, avg=0.10056, loss=0.09369]

trial_001 train e002:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:06,  1.33it/s, avg=0.10056, loss=0.09369]

trial_001 train e002:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:06,  1.33it/s, avg=0.10056, loss=0.10025]

trial_001 train e002:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.35it/s, avg=0.10056, loss=0.10025]

trial_001 train e002:  42%|███████████████████████████████████████                                                       | 62/149 [00:47<01:04,  1.35it/s, avg=0.10073, loss=0.11112]

trial_001 train e002:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:04,  1.33it/s, avg=0.10073, loss=0.11112]

trial_001 train e002:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:48<01:04,  1.33it/s, avg=0.10068, loss=0.09764]

trial_001 train e002:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:04,  1.33it/s, avg=0.10068, loss=0.09764]

trial_001 train e002:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:04,  1.33it/s, avg=0.10072, loss=0.10313]

trial_001 train e002:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.36it/s, avg=0.10072, loss=0.10313]

trial_001 train e002:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:01,  1.36it/s, avg=0.10059, loss=0.09258]

trial_001 train e002:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<00:59,  1.39it/s, avg=0.10059, loss=0.09258]

trial_001 train e002:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:50<00:59,  1.39it/s, avg=0.10047, loss=0.09216]

trial_001 train e002:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<00:59,  1.37it/s, avg=0.10047, loss=0.09216]

trial_001 train e002:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<00:59,  1.37it/s, avg=0.10046, loss=0.09982]

trial_001 train e002:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:59,  1.36it/s, avg=0.10046, loss=0.09982]

trial_001 train e002:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<00:59,  1.36it/s, avg=0.10056, loss=0.10743]

trial_001 train e002:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<01:00,  1.33it/s, avg=0.10056, loss=0.10743]

trial_001 train e002:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<01:00,  1.33it/s, avg=0.10032, loss=0.08401]

trial_001 train e002:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<01:01,  1.29it/s, avg=0.10032, loss=0.08401]

trial_001 train e002:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:53<01:01,  1.29it/s, avg=0.10045, loss=0.10943]

trial_001 train e002:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:59,  1.32it/s, avg=0.10045, loss=0.10943]

trial_001 train e002:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:54<00:59,  1.32it/s, avg=0.10044, loss=0.09948]

trial_001 train e002:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:59,  1.30it/s, avg=0.10044, loss=0.09948]

trial_001 train e002:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:59,  1.30it/s, avg=0.10065, loss=0.11613]

trial_001 train e002:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:56,  1.34it/s, avg=0.10065, loss=0.11613]

trial_001 train e002:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:56,  1.34it/s, avg=0.10074, loss=0.10691]

trial_001 train e002:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:55,  1.34it/s, avg=0.10074, loss=0.10691]

trial_001 train e002:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:56<00:55,  1.34it/s, avg=0.10069, loss=0.09713]

trial_001 train e002:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:54,  1.36it/s, avg=0.10069, loss=0.09713]

trial_001 train e002:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:54,  1.36it/s, avg=0.10054, loss=0.08976]

trial_001 train e002:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:53,  1.35it/s, avg=0.10054, loss=0.08976]

trial_001 train e002:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:53,  1.35it/s, avg=0.10048, loss=0.09520]

trial_001 train e002:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:54,  1.33it/s, avg=0.10048, loss=0.09520]

trial_001 train e002:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:54,  1.33it/s, avg=0.10062, loss=0.11215]

trial_001 train e002:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:53,  1.32it/s, avg=0.10062, loss=0.11215]

trial_001 train e002:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:59<00:53,  1.32it/s, avg=0.10091, loss=0.12312]

trial_001 train e002:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:52,  1.33it/s, avg=0.10091, loss=0.12312]

trial_001 train e002:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:52,  1.33it/s, avg=0.10092, loss=0.10189]

trial_001 train e002:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:51,  1.33it/s, avg=0.10092, loss=0.10189]

trial_001 train e002:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:51,  1.33it/s, avg=0.10087, loss=0.09707]

trial_001 train e002:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:51,  1.33it/s, avg=0.10087, loss=0.09707]

trial_001 train e002:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:51,  1.33it/s, avg=0.10073, loss=0.08892]

trial_001 train e002:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:50,  1.31it/s, avg=0.10073, loss=0.08892]

trial_001 train e002:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:02<00:50,  1.31it/s, avg=0.10077, loss=0.10428]

trial_001 train e002:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:49,  1.33it/s, avg=0.10077, loss=0.10428]

trial_001 train e002:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:49,  1.33it/s, avg=0.10082, loss=0.10523]

trial_001 train e002:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:48,  1.34it/s, avg=0.10082, loss=0.10523]

trial_001 train e002:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.34it/s, avg=0.10071, loss=0.09081]

trial_001 train e002:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:49,  1.28it/s, avg=0.10071, loss=0.09081]

trial_001 train e002:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:49,  1.28it/s, avg=0.10065, loss=0.09582]

trial_001 train e002:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:49,  1.28it/s, avg=0.10065, loss=0.09582]

trial_001 train e002:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:05<00:49,  1.28it/s, avg=0.10061, loss=0.09754]

trial_001 train e002:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:47,  1.31it/s, avg=0.10061, loss=0.09754]

trial_001 train e002:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:06<00:47,  1.31it/s, avg=0.10059, loss=0.09854]

trial_001 train e002:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:46,  1.31it/s, avg=0.10059, loss=0.09854]

trial_001 train e002:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:46,  1.31it/s, avg=0.10064, loss=0.10479]

trial_001 train e002:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.35it/s, avg=0.10064, loss=0.10479]

trial_001 train e002:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:44,  1.35it/s, avg=0.10066, loss=0.10227]

trial_001 train e002:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:43,  1.35it/s, avg=0.10066, loss=0.10227]

trial_001 train e002:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:08<00:43,  1.35it/s, avg=0.10062, loss=0.09774]

trial_001 train e002:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:43,  1.34it/s, avg=0.10062, loss=0.09774]

trial_001 train e002:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:09<00:43,  1.34it/s, avg=0.10075, loss=0.11216]

trial_001 train e002:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:42,  1.33it/s, avg=0.10075, loss=0.11216]

trial_001 train e002:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:42,  1.33it/s, avg=0.10064, loss=0.09062]

trial_001 train e002:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:42,  1.31it/s, avg=0.10064, loss=0.09062]

trial_001 train e002:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:42,  1.31it/s, avg=0.10055, loss=0.09236]

trial_001 train e002:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:41,  1.32it/s, avg=0.10055, loss=0.09236]

trial_001 train e002:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:11<00:41,  1.32it/s, avg=0.10038, loss=0.08444]

trial_001 train e002:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:41,  1.32it/s, avg=0.10038, loss=0.08444]

trial_001 train e002:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:12<00:41,  1.32it/s, avg=0.10042, loss=0.10369]

trial_001 train e002:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.35it/s, avg=0.10042, loss=0.10369]

trial_001 train e002:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.35it/s, avg=0.10031, loss=0.08985]

trial_001 train e002:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:39,  1.33it/s, avg=0.10031, loss=0.08985]

trial_001 train e002:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:39,  1.33it/s, avg=0.10027, loss=0.09654]

trial_001 train e002:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:38,  1.33it/s, avg=0.10027, loss=0.09654]

trial_001 train e002:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:14<00:38,  1.33it/s, avg=0.10031, loss=0.10434]

trial_001 train e002:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:37,  1.33it/s, avg=0.10031, loss=0.10434]

trial_001 train e002:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:15<00:37,  1.33it/s, avg=0.10030, loss=0.09885]

trial_001 train e002:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:37,  1.32it/s, avg=0.10030, loss=0.09885]

trial_001 train e002:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:37,  1.32it/s, avg=0.10030, loss=0.10048]

trial_001 train e002:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:36,  1.33it/s, avg=0.10030, loss=0.10048]

trial_001 train e002:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:36,  1.33it/s, avg=0.10037, loss=0.10746]

trial_001 train e002:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:34,  1.36it/s, avg=0.10037, loss=0.10746]

trial_001 train e002:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:17<00:34,  1.36it/s, avg=0.10037, loss=0.10104]

trial_001 train e002:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:34,  1.33it/s, avg=0.10037, loss=0.10104]

trial_001 train e002:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:18<00:34,  1.33it/s, avg=0.10031, loss=0.09409]

trial_001 train e002:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.33it/s, avg=0.10031, loss=0.09409]

trial_001 train e002:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.33it/s, avg=0.10044, loss=0.11345]

trial_001 train e002:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:33,  1.32it/s, avg=0.10044, loss=0.11345]

trial_001 train e002:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:33,  1.32it/s, avg=0.10045, loss=0.10187]

trial_001 train e002:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:32,  1.30it/s, avg=0.10045, loss=0.10187]

trial_001 train e002:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:20<00:32,  1.30it/s, avg=0.10035, loss=0.08904]

trial_001 train e002:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:31,  1.31it/s, avg=0.10035, loss=0.08904]

trial_001 train e002:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:21<00:31,  1.31it/s, avg=0.10029, loss=0.09425]

trial_001 train e002:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.33it/s, avg=0.10029, loss=0.09425]

trial_001 train e002:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.33it/s, avg=0.10035, loss=0.10680]

trial_001 train e002:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:30,  1.33it/s, avg=0.10035, loss=0.10680]

trial_001 train e002:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:30,  1.33it/s, avg=0.10039, loss=0.10452]

trial_001 train e002:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:29,  1.32it/s, avg=0.10039, loss=0.10452]

trial_001 train e002:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:23<00:29,  1.32it/s, avg=0.10032, loss=0.09327]

trial_001 train e002:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:28,  1.32it/s, avg=0.10032, loss=0.09327]

trial_001 train e002:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:24<00:28,  1.32it/s, avg=0.10045, loss=0.11446]

trial_001 train e002:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:27,  1.32it/s, avg=0.10045, loss=0.11446]

trial_001 train e002:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:27,  1.32it/s, avg=0.10040, loss=0.09525]

trial_001 train e002:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:27,  1.31it/s, avg=0.10040, loss=0.09525]

trial_001 train e002:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:27,  1.31it/s, avg=0.10046, loss=0.10733]

trial_001 train e002:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:26,  1.30it/s, avg=0.10046, loss=0.10733]

trial_001 train e002:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:26<00:26,  1.30it/s, avg=0.10033, loss=0.08519]

trial_001 train e002:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.32it/s, avg=0.10033, loss=0.08519]

trial_001 train e002:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:27<00:25,  1.32it/s, avg=0.10040, loss=0.10850]

trial_001 train e002:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.32it/s, avg=0.10040, loss=0.10850]

trial_001 train e002:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.32it/s, avg=0.10039, loss=0.09925]

trial_001 train e002:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:23,  1.34it/s, avg=0.10039, loss=0.09925]

trial_001 train e002:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:23,  1.34it/s, avg=0.10052, loss=0.11602]

trial_001 train e002:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.34it/s, avg=0.10052, loss=0.11602]

trial_001 train e002:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:29<00:23,  1.34it/s, avg=0.10070, loss=0.12089]

trial_001 train e002:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:21,  1.37it/s, avg=0.10070, loss=0.12089]

trial_001 train e002:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:30<00:21,  1.37it/s, avg=0.10065, loss=0.09561]

trial_001 train e002:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.35it/s, avg=0.10065, loss=0.09561]

trial_001 train e002:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.35it/s, avg=0.10062, loss=0.09669]

trial_001 train e002:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:21,  1.32it/s, avg=0.10062, loss=0.09669]

trial_001 train e002:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:21,  1.32it/s, avg=0.10071, loss=0.11162]

trial_001 train e002:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:20,  1.32it/s, avg=0.10071, loss=0.11162]

trial_001 train e002:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:32<00:20,  1.32it/s, avg=0.10063, loss=0.09029]

trial_001 train e002:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.31it/s, avg=0.10063, loss=0.09029]

trial_001 train e002:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:33<00:19,  1.31it/s, avg=0.10062, loss=0.10002]

trial_001 train e002:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:19,  1.31it/s, avg=0.10062, loss=0.10002]

trial_001 train e002:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:19,  1.31it/s, avg=0.10062, loss=0.10013]

trial_001 train e002:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:18,  1.33it/s, avg=0.10062, loss=0.10013]

trial_001 train e002:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:34<00:18,  1.33it/s, avg=0.10054, loss=0.09103]

trial_001 train e002:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:17,  1.33it/s, avg=0.10054, loss=0.09103]

trial_001 train e002:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:35<00:17,  1.33it/s, avg=0.10055, loss=0.10225]

trial_001 train e002:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.30it/s, avg=0.10055, loss=0.10225]

trial_001 train e002:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:36<00:16,  1.30it/s, avg=0.10058, loss=0.10414]

trial_001 train e002:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.33it/s, avg=0.10058, loss=0.10414]

trial_001 train e002:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.33it/s, avg=0.10049, loss=0.08919]

trial_001 train e002:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:15,  1.33it/s, avg=0.10049, loss=0.08919]

trial_001 train e002:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:37<00:15,  1.33it/s, avg=0.10059, loss=0.11278]

trial_001 train e002:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.32it/s, avg=0.10059, loss=0.11278]

trial_001 train e002:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:38<00:14,  1.32it/s, avg=0.10058, loss=0.09947]

trial_001 train e002:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.31it/s, avg=0.10058, loss=0.09947]

trial_001 train e002:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:39<00:13,  1.31it/s, avg=0.10060, loss=0.10328]

trial_001 train e002:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.34it/s, avg=0.10060, loss=0.10328]

trial_001 train e002:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:40<00:12,  1.34it/s, avg=0.10056, loss=0.09500]

trial_001 train e002:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:12,  1.33it/s, avg=0.10056, loss=0.09500]

trial_001 train e002:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:12,  1.33it/s, avg=0.10072, loss=0.12257]

trial_001 train e002:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:11,  1.34it/s, avg=0.10072, loss=0.12257]

trial_001 train e002:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:41<00:11,  1.34it/s, avg=0.10079, loss=0.10999]

trial_001 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.36it/s, avg=0.10079, loss=0.10999]

trial_001 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:42<00:10,  1.36it/s, avg=0.10074, loss=0.09389]

trial_001 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.37it/s, avg=0.10074, loss=0.09389]

trial_001 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.37it/s, avg=0.10069, loss=0.09334]

trial_001 train e002:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:08,  1.36it/s, avg=0.10069, loss=0.09334]

trial_001 train e002:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:43<00:08,  1.36it/s, avg=0.10070, loss=0.10239]

trial_001 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.35it/s, avg=0.10070, loss=0.10239]

trial_001 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:44<00:08,  1.35it/s, avg=0.10071, loss=0.10166]

trial_001 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.37it/s, avg=0.10071, loss=0.10166]

trial_001 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:45<00:07,  1.37it/s, avg=0.10064, loss=0.09109]

trial_001 train e002:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.37it/s, avg=0.10064, loss=0.09109]

trial_001 train e002:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.37it/s, avg=0.10061, loss=0.09626]

trial_001 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:05,  1.38it/s, avg=0.10061, loss=0.09626]

trial_001 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:46<00:05,  1.38it/s, avg=0.10058, loss=0.09748]

trial_001 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.37it/s, avg=0.10058, loss=0.09748]

trial_001 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:47<00:05,  1.37it/s, avg=0.10067, loss=0.11216]

trial_001 train e002:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.37it/s, avg=0.10067, loss=0.11216]

trial_001 train e002:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:48<00:04,  1.37it/s, avg=0.10066, loss=0.10041]

trial_001 train e002:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.36it/s, avg=0.10066, loss=0.10041]

trial_001 train e002:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.36it/s, avg=0.10062, loss=0.09430]

trial_001 train e002:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:02,  1.36it/s, avg=0.10062, loss=0.09430]

trial_001 train e002:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:49<00:02,  1.36it/s, avg=0.10068, loss=0.11002]

trial_001 train e002:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.34it/s, avg=0.10068, loss=0.11002]

trial_001 train e002:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:50<00:02,  1.34it/s, avg=0.10065, loss=0.09554]

trial_001 train e002:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.32it/s, avg=0.10065, loss=0.09554]

trial_001 train e002:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:51<00:01,  1.32it/s, avg=0.10069, loss=0.10625]

trial_001 train e002:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.32it/s, avg=0.10069, loss=0.10625]

trial_001 train e002:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.32it/s, avg=0.10067, loss=0.09591]

trial_001 train e002: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:51<00:00,  1.59it/s, avg=0.10067, loss=0.09591]

trial_001 val e002:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e002:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.30it/s]

trial_001 val e002:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.31it/s]

trial_001 val e002:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.30it/s]

trial_001 val e002:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.31it/s]

trial_001 val e002:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.30it/s]

trial_001 val e002:  12%|███████████████                                                                                                              | 6/50 [00:02<00:19,  2.28it/s]

trial_001 val e002:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:18,  2.30it/s]

trial_001 val e002:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:18,  2.32it/s]

trial_001 val e002:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.33it/s]

trial_001 val e002:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.33it/s]

trial_001 val e002:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.33it/s]

trial_001 val e002:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.30it/s]

trial_001 val e002:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:16,  2.29it/s]

trial_001 val e002:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.31it/s]

trial_001 val e002:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.32it/s]

trial_001 val e002:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.33it/s]

trial_001 val e002:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.31it/s]

trial_001 val e002:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.30it/s]

trial_001 val e002:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.30it/s]

trial_001 val e002:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:13,  2.29it/s]

trial_001 val e002:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.29it/s]

trial_001 val e002:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.29it/s]

trial_001 val e002:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.29it/s]

trial_001 val e002:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.27it/s]

trial_001 val e002:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:11,  2.24it/s]

trial_001 val e002:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.24it/s]

trial_001 val e002:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:10,  2.26it/s]

trial_001 val e002:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.27it/s]

trial_001 val e002:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.28it/s]

trial_001 val e002:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:13<00:08,  2.28it/s]

trial_001 val e002:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.26it/s]

trial_001 val e002:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.27it/s]

trial_001 val e002:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.28it/s]

trial_001 val e002:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:07,  2.27it/s]

trial_001 val e002:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.28it/s]

trial_001 val e002:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.28it/s]

trial_001 val e002:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:16<00:05,  2.26it/s]

trial_001 val e002:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.24it/s]

trial_001 val e002:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:17<00:04,  2.25it/s]

trial_001 val e002:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.24it/s]

trial_001 val e002:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:04,  2.23it/s]

trial_001 val e002:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.21it/s]

trial_001 val e002:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.23it/s]

trial_001 val e002:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.21it/s]

trial_001 val e002:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.23it/s]

trial_001 val e002:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:20<00:01,  2.24it/s]

trial_001 val e002:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.23it/s]

trial_001 val e002:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:21<00:00,  2.22it/s]

trial_001 val e002:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.21it/s]

trial_001 val e002: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:22<00:00,  2.23it/s]

[2026-05-28 20:07:45] [trial_001] epoch=002 | train_loss=0.100674 | val_MAE=0.100639 | val_S=0.899361 | best_S=0.899361 @epoch=2 | patience=0/5

[trial_001] epochs:   2%|██▍                                                                                                                      | 2/100 [04:28<3:39:15, 134.24s/it]

trial_001 train e003:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e003:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10000, loss=0.10000]

trial_001 train e003:   1%|▋                                                                                              | 1/149 [00:00<01:51,  1.33it/s, avg=0.10000, loss=0.10000]

trial_001 train e003:   1%|▋                                                                                              | 1/149 [00:01<01:51,  1.33it/s, avg=0.09751, loss=0.09502]

trial_001 train e003:   1%|█▎                                                                                             | 2/149 [00:01<01:48,  1.35it/s, avg=0.09751, loss=0.09502]

trial_001 train e003:   1%|█▎                                                                                             | 2/149 [00:02<01:48,  1.35it/s, avg=0.10172, loss=0.11014]

trial_001 train e003:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.10172, loss=0.11014]

trial_001 train e003:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.10447, loss=0.11272]

trial_001 train e003:   3%|██▌                                                                                            | 4/149 [00:02<01:42,  1.42it/s, avg=0.10447, loss=0.11272]

trial_001 train e003:   3%|██▌                                                                                            | 4/149 [00:03<01:42,  1.42it/s, avg=0.10371, loss=0.10067]

trial_001 train e003:   3%|███▏                                                                                           | 5/149 [00:03<01:41,  1.42it/s, avg=0.10371, loss=0.10067]

trial_001 train e003:   3%|███▏                                                                                           | 5/149 [00:04<01:41,  1.42it/s, avg=0.10218, loss=0.09451]

trial_001 train e003:   4%|███▊                                                                                           | 6/149 [00:04<01:43,  1.38it/s, avg=0.10218, loss=0.09451]

trial_001 train e003:   4%|███▊                                                                                           | 6/149 [00:05<01:43,  1.38it/s, avg=0.10135, loss=0.09636]

trial_001 train e003:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.10135, loss=0.09636]

trial_001 train e003:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.10121, loss=0.10024]

trial_001 train e003:   5%|█████                                                                                          | 8/149 [00:05<01:44,  1.35it/s, avg=0.10121, loss=0.10024]

trial_001 train e003:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.35it/s, avg=0.10054, loss=0.09523]

trial_001 train e003:   6%|█████▋                                                                                         | 9/149 [00:06<01:45,  1.33it/s, avg=0.10054, loss=0.09523]

trial_001 train e003:   6%|█████▋                                                                                         | 9/149 [00:07<01:45,  1.33it/s, avg=0.10115, loss=0.10662]

trial_001 train e003:   7%|██████▎                                                                                       | 10/149 [00:07<01:46,  1.31it/s, avg=0.10115, loss=0.10662]

trial_001 train e003:   7%|██████▎                                                                                       | 10/149 [00:08<01:46,  1.31it/s, avg=0.10111, loss=0.10072]

trial_001 train e003:   7%|██████▉                                                                                       | 11/149 [00:08<01:46,  1.30it/s, avg=0.10111, loss=0.10072]

trial_001 train e003:   7%|██████▉                                                                                       | 11/149 [00:08<01:46,  1.30it/s, avg=0.10093, loss=0.09894]

trial_001 train e003:   8%|███████▌                                                                                      | 12/149 [00:08<01:44,  1.31it/s, avg=0.10093, loss=0.09894]

trial_001 train e003:   8%|███████▌                                                                                      | 12/149 [00:09<01:44,  1.31it/s, avg=0.10040, loss=0.09410]

trial_001 train e003:   9%|████████▏                                                                                     | 13/149 [00:09<01:44,  1.30it/s, avg=0.10040, loss=0.09410]

trial_001 train e003:   9%|████████▏                                                                                     | 13/149 [00:10<01:44,  1.30it/s, avg=0.10033, loss=0.09932]

trial_001 train e003:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.33it/s, avg=0.10033, loss=0.09932]

trial_001 train e003:   9%|████████▊                                                                                     | 14/149 [00:11<01:41,  1.33it/s, avg=0.09993, loss=0.09439]

trial_001 train e003:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.33it/s, avg=0.09993, loss=0.09439]

trial_001 train e003:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.33it/s, avg=0.09997, loss=0.10047]

trial_001 train e003:  11%|██████████                                                                                    | 16/149 [00:11<01:38,  1.35it/s, avg=0.09997, loss=0.10047]

trial_001 train e003:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.35it/s, avg=0.09953, loss=0.09257]

trial_001 train e003:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.38it/s, avg=0.09953, loss=0.09257]

trial_001 train e003:  11%|██████████▋                                                                                   | 17/149 [00:13<01:35,  1.38it/s, avg=0.09963, loss=0.10125]

trial_001 train e003:  12%|███████████▎                                                                                  | 18/149 [00:13<01:36,  1.36it/s, avg=0.09963, loss=0.10125]

trial_001 train e003:  12%|███████████▎                                                                                  | 18/149 [00:14<01:36,  1.36it/s, avg=0.09966, loss=0.10023]

trial_001 train e003:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.37it/s, avg=0.09966, loss=0.10023]

trial_001 train e003:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.37it/s, avg=0.09987, loss=0.10383]

trial_001 train e003:  13%|████████████▌                                                                                 | 20/149 [00:14<01:36,  1.34it/s, avg=0.09987, loss=0.10383]

trial_001 train e003:  13%|████████████▌                                                                                 | 20/149 [00:15<01:36,  1.34it/s, avg=0.10051, loss=0.11341]

trial_001 train e003:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.33it/s, avg=0.10051, loss=0.11341]

trial_001 train e003:  14%|█████████████▏                                                                                | 21/149 [00:16<01:36,  1.33it/s, avg=0.10014, loss=0.09231]

trial_001 train e003:  15%|█████████████▉                                                                                | 22/149 [00:16<01:35,  1.33it/s, avg=0.10014, loss=0.09231]

trial_001 train e003:  15%|█████████████▉                                                                                | 22/149 [00:17<01:35,  1.33it/s, avg=0.10022, loss=0.10193]

trial_001 train e003:  15%|██████████████▌                                                                               | 23/149 [00:17<01:35,  1.31it/s, avg=0.10022, loss=0.10193]

trial_001 train e003:  15%|██████████████▌                                                                               | 23/149 [00:17<01:35,  1.31it/s, avg=0.09938, loss=0.08013]

trial_001 train e003:  16%|███████████████▏                                                                              | 24/149 [00:17<01:35,  1.31it/s, avg=0.09938, loss=0.08013]

trial_001 train e003:  16%|███████████████▏                                                                              | 24/149 [00:18<01:35,  1.31it/s, avg=0.09962, loss=0.10531]

trial_001 train e003:  17%|███████████████▊                                                                              | 25/149 [00:18<01:33,  1.33it/s, avg=0.09962, loss=0.10531]

trial_001 train e003:  17%|███████████████▊                                                                              | 25/149 [00:19<01:33,  1.33it/s, avg=0.09933, loss=0.09227]

trial_001 train e003:  17%|████████████████▍                                                                             | 26/149 [00:19<01:32,  1.33it/s, avg=0.09933, loss=0.09227]

trial_001 train e003:  17%|████████████████▍                                                                             | 26/149 [00:20<01:32,  1.33it/s, avg=0.09933, loss=0.09920]

trial_001 train e003:  18%|█████████████████                                                                             | 27/149 [00:20<01:31,  1.33it/s, avg=0.09933, loss=0.09920]

trial_001 train e003:  18%|█████████████████                                                                             | 27/149 [00:20<01:31,  1.33it/s, avg=0.09952, loss=0.10475]

trial_001 train e003:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:31,  1.32it/s, avg=0.09952, loss=0.10475]

trial_001 train e003:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:31,  1.32it/s, avg=0.09894, loss=0.08277]

trial_001 train e003:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:31,  1.32it/s, avg=0.09894, loss=0.08277]

trial_001 train e003:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:31,  1.32it/s, avg=0.09864, loss=0.08974]

trial_001 train e003:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:30,  1.31it/s, avg=0.09864, loss=0.08974]

trial_001 train e003:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:30,  1.31it/s, avg=0.09890, loss=0.10682]

trial_001 train e003:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:28,  1.34it/s, avg=0.09890, loss=0.10682]

trial_001 train e003:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:28,  1.34it/s, avg=0.09879, loss=0.09541]

trial_001 train e003:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:27,  1.33it/s, avg=0.09879, loss=0.09541]

trial_001 train e003:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:27,  1.33it/s, avg=0.09889, loss=0.10188]

trial_001 train e003:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:25,  1.35it/s, avg=0.09889, loss=0.10188]

trial_001 train e003:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:25,  1.35it/s, avg=0.09850, loss=0.08579]

trial_001 train e003:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:26,  1.32it/s, avg=0.09850, loss=0.08579]

trial_001 train e003:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:26,  1.32it/s, avg=0.09819, loss=0.08766]

trial_001 train e003:  23%|██████████████████████                                                                        | 35/149 [00:26<01:25,  1.33it/s, avg=0.09819, loss=0.08766]

trial_001 train e003:  23%|██████████████████████                                                                        | 35/149 [00:26<01:25,  1.33it/s, avg=0.09803, loss=0.09240]

trial_001 train e003:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:25,  1.32it/s, avg=0.09803, loss=0.09240]

trial_001 train e003:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:25,  1.32it/s, avg=0.09785, loss=0.09134]

trial_001 train e003:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:25,  1.30it/s, avg=0.09785, loss=0.09134]

trial_001 train e003:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:25,  1.30it/s, avg=0.09793, loss=0.10093]

trial_001 train e003:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:23,  1.32it/s, avg=0.09793, loss=0.10093]

trial_001 train e003:  26%|███████████████████████▉                                                                      | 38/149 [00:29<01:23,  1.32it/s, avg=0.09769, loss=0.08862]

trial_001 train e003:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:21,  1.35it/s, avg=0.09769, loss=0.08862]

trial_001 train e003:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:21,  1.35it/s, avg=0.09764, loss=0.09547]

trial_001 train e003:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:21,  1.33it/s, avg=0.09764, loss=0.09547]

trial_001 train e003:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:21,  1.33it/s, avg=0.09822, loss=0.12152]

trial_001 train e003:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:19,  1.35it/s, avg=0.09822, loss=0.12152]

trial_001 train e003:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:19,  1.35it/s, avg=0.09856, loss=0.11241]

trial_001 train e003:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:18,  1.36it/s, avg=0.09856, loss=0.11241]

trial_001 train e003:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:18,  1.36it/s, avg=0.09853, loss=0.09737]

trial_001 train e003:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:20,  1.31it/s, avg=0.09853, loss=0.09737]

trial_001 train e003:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:20,  1.31it/s, avg=0.09889, loss=0.11419]

trial_001 train e003:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:20,  1.30it/s, avg=0.09889, loss=0.11419]

trial_001 train e003:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:20,  1.30it/s, avg=0.09891, loss=0.09984]

trial_001 train e003:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:20,  1.29it/s, avg=0.09891, loss=0.09984]

trial_001 train e003:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:20,  1.29it/s, avg=0.09881, loss=0.09434]

trial_001 train e003:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:20,  1.29it/s, avg=0.09881, loss=0.09434]

trial_001 train e003:  31%|█████████████████████████████                                                                 | 46/149 [00:35<01:20,  1.29it/s, avg=0.09858, loss=0.08816]

trial_001 train e003:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:18,  1.30it/s, avg=0.09858, loss=0.08816]

trial_001 train e003:  32%|█████████████████████████████▋                                                                | 47/149 [00:36<01:18,  1.30it/s, avg=0.09867, loss=0.10298]

trial_001 train e003:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:15,  1.34it/s, avg=0.09867, loss=0.10298]

trial_001 train e003:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:15,  1.34it/s, avg=0.09867, loss=0.09848]

trial_001 train e003:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:14,  1.33it/s, avg=0.09867, loss=0.09848]

trial_001 train e003:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:14,  1.33it/s, avg=0.09879, loss=0.10489]

trial_001 train e003:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:14,  1.32it/s, avg=0.09879, loss=0.10489]

trial_001 train e003:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:14,  1.32it/s, avg=0.09865, loss=0.09148]

trial_001 train e003:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:14,  1.31it/s, avg=0.09865, loss=0.09148]

trial_001 train e003:  34%|████████████████████████████████▏                                                             | 51/149 [00:39<01:14,  1.31it/s, avg=0.09880, loss=0.10627]

trial_001 train e003:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:11,  1.35it/s, avg=0.09880, loss=0.10627]

trial_001 train e003:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:11,  1.35it/s, avg=0.09892, loss=0.10522]

trial_001 train e003:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.36it/s, avg=0.09892, loss=0.10522]

trial_001 train e003:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:10,  1.36it/s, avg=0.09878, loss=0.09159]

trial_001 train e003:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:09,  1.36it/s, avg=0.09878, loss=0.09159]

trial_001 train e003:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:09,  1.36it/s, avg=0.09871, loss=0.09475]

trial_001 train e003:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:10,  1.34it/s, avg=0.09871, loss=0.09475]

trial_001 train e003:  37%|██████████████████████████████████▋                                                           | 55/149 [00:42<01:10,  1.34it/s, avg=0.09866, loss=0.09626]

trial_001 train e003:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:09,  1.33it/s, avg=0.09866, loss=0.09626]

trial_001 train e003:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:09,  1.33it/s, avg=0.09882, loss=0.10754]

trial_001 train e003:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:09,  1.33it/s, avg=0.09882, loss=0.10754]

trial_001 train e003:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:09,  1.33it/s, avg=0.09875, loss=0.09467]

trial_001 train e003:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:09,  1.30it/s, avg=0.09875, loss=0.09467]

trial_001 train e003:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:09,  1.30it/s, avg=0.09862, loss=0.09106]

trial_001 train e003:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:09,  1.30it/s, avg=0.09862, loss=0.09106]

trial_001 train e003:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:45<01:09,  1.30it/s, avg=0.09865, loss=0.10025]

trial_001 train e003:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:08,  1.30it/s, avg=0.09865, loss=0.10025]

trial_001 train e003:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:08,  1.30it/s, avg=0.09874, loss=0.10441]

trial_001 train e003:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:08,  1.29it/s, avg=0.09874, loss=0.10441]

trial_001 train e003:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:08,  1.29it/s, avg=0.09878, loss=0.10136]

trial_001 train e003:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:07,  1.29it/s, avg=0.09878, loss=0.10136]

trial_001 train e003:  42%|███████████████████████████████████████                                                       | 62/149 [00:47<01:07,  1.29it/s, avg=0.09867, loss=0.09144]

trial_001 train e003:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:04,  1.33it/s, avg=0.09867, loss=0.09144]

trial_001 train e003:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:48<01:04,  1.33it/s, avg=0.09876, loss=0.10460]

trial_001 train e003:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:04,  1.33it/s, avg=0.09876, loss=0.10460]

trial_001 train e003:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:04,  1.33it/s, avg=0.09879, loss=0.10058]

trial_001 train e003:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:03,  1.32it/s, avg=0.09879, loss=0.10058]

trial_001 train e003:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:03,  1.32it/s, avg=0.09871, loss=0.09345]

trial_001 train e003:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:02,  1.33it/s, avg=0.09871, loss=0.09345]

trial_001 train e003:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:50<01:02,  1.33it/s, avg=0.09868, loss=0.09666]

trial_001 train e003:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:00,  1.34it/s, avg=0.09868, loss=0.09666]

trial_001 train e003:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:51<01:00,  1.34it/s, avg=0.09880, loss=0.10700]

trial_001 train e003:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:00,  1.34it/s, avg=0.09880, loss=0.10700]

trial_001 train e003:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:00,  1.34it/s, avg=0.09896, loss=0.11005]

trial_001 train e003:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.36it/s, avg=0.09896, loss=0.11005]

trial_001 train e003:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<00:58,  1.36it/s, avg=0.09925, loss=0.11949]

trial_001 train e003:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:57,  1.38it/s, avg=0.09925, loss=0.11949]

trial_001 train e003:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:53<00:57,  1.38it/s, avg=0.09916, loss=0.09229]

trial_001 train e003:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:56,  1.39it/s, avg=0.09916, loss=0.09229]

trial_001 train e003:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:54<00:56,  1.39it/s, avg=0.09909, loss=0.09418]

trial_001 train e003:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:57,  1.35it/s, avg=0.09909, loss=0.09418]

trial_001 train e003:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:57,  1.35it/s, avg=0.09892, loss=0.08684]

trial_001 train e003:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:57,  1.33it/s, avg=0.09892, loss=0.08684]

trial_001 train e003:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:57,  1.33it/s, avg=0.09891, loss=0.09855]

trial_001 train e003:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:56,  1.33it/s, avg=0.09891, loss=0.09855]

trial_001 train e003:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:56<00:56,  1.33it/s, avg=0.09885, loss=0.09393]

trial_001 train e003:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:55,  1.33it/s, avg=0.09885, loss=0.09393]

trial_001 train e003:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:57<00:55,  1.33it/s, avg=0.09888, loss=0.10125]

trial_001 train e003:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:55,  1.31it/s, avg=0.09888, loss=0.10125]

trial_001 train e003:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:55,  1.31it/s, avg=0.09878, loss=0.09126]

trial_001 train e003:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:54,  1.33it/s, avg=0.09878, loss=0.09126]

trial_001 train e003:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:54,  1.33it/s, avg=0.09877, loss=0.09828]

trial_001 train e003:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:52,  1.34it/s, avg=0.09877, loss=0.09828]

trial_001 train e003:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:59<00:52,  1.34it/s, avg=0.09867, loss=0.09057]

trial_001 train e003:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:51,  1.36it/s, avg=0.09867, loss=0.09057]

trial_001 train e003:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [01:00<00:51,  1.36it/s, avg=0.09868, loss=0.09980]

trial_001 train e003:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:51,  1.34it/s, avg=0.09868, loss=0.09980]

trial_001 train e003:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:51,  1.34it/s, avg=0.09862, loss=0.09321]

trial_001 train e003:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:50,  1.35it/s, avg=0.09862, loss=0.09321]

trial_001 train e003:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:50,  1.35it/s, avg=0.09854, loss=0.09251]

trial_001 train e003:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:49,  1.34it/s, avg=0.09854, loss=0.09251]

trial_001 train e003:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:02<00:49,  1.34it/s, avg=0.09854, loss=0.09796]

trial_001 train e003:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:49,  1.34it/s, avg=0.09854, loss=0.09796]

trial_001 train e003:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:03<00:49,  1.34it/s, avg=0.09861, loss=0.10503]

trial_001 train e003:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.33it/s, avg=0.09861, loss=0.10503]

trial_001 train e003:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.33it/s, avg=0.09855, loss=0.09308]

trial_001 train e003:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:48,  1.33it/s, avg=0.09855, loss=0.09308]

trial_001 train e003:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:48,  1.33it/s, avg=0.09848, loss=0.09298]

trial_001 train e003:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:47,  1.33it/s, avg=0.09848, loss=0.09298]

trial_001 train e003:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:05<00:47,  1.33it/s, avg=0.09845, loss=0.09564]

trial_001 train e003:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:46,  1.32it/s, avg=0.09845, loss=0.09564]

trial_001 train e003:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:06<00:46,  1.32it/s, avg=0.09854, loss=0.10601]

trial_001 train e003:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:46,  1.32it/s, avg=0.09854, loss=0.10601]

trial_001 train e003:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:46,  1.32it/s, avg=0.09846, loss=0.09221]

trial_001 train e003:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:45,  1.32it/s, avg=0.09846, loss=0.09221]

trial_001 train e003:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:45,  1.32it/s, avg=0.09868, loss=0.11791]

trial_001 train e003:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:44,  1.32it/s, avg=0.09868, loss=0.11791]

trial_001 train e003:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:08<00:44,  1.32it/s, avg=0.09863, loss=0.09430]

trial_001 train e003:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:44,  1.31it/s, avg=0.09863, loss=0.09430]

trial_001 train e003:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:09<00:44,  1.31it/s, avg=0.09872, loss=0.10640]

trial_001 train e003:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.31it/s, avg=0.09872, loss=0.10640]

trial_001 train e003:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.31it/s, avg=0.09866, loss=0.09322]

trial_001 train e003:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:43,  1.29it/s, avg=0.09866, loss=0.09322]

trial_001 train e003:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:43,  1.29it/s, avg=0.09874, loss=0.10647]

trial_001 train e003:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:41,  1.32it/s, avg=0.09874, loss=0.10647]

trial_001 train e003:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:11<00:41,  1.32it/s, avg=0.09880, loss=0.10401]

trial_001 train e003:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:41,  1.30it/s, avg=0.09880, loss=0.10401]

trial_001 train e003:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:12<00:41,  1.30it/s, avg=0.09898, loss=0.11601]

trial_001 train e003:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:40,  1.31it/s, avg=0.09898, loss=0.11601]

trial_001 train e003:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:40,  1.31it/s, avg=0.09902, loss=0.10343]

trial_001 train e003:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.34it/s, avg=0.09902, loss=0.10343]

trial_001 train e003:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:38,  1.34it/s, avg=0.09883, loss=0.07981]

trial_001 train e003:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:38,  1.32it/s, avg=0.09883, loss=0.07981]

trial_001 train e003:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:14<00:38,  1.32it/s, avg=0.09887, loss=0.10355]

trial_001 train e003:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:38,  1.31it/s, avg=0.09887, loss=0.10355]

trial_001 train e003:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:15<00:38,  1.31it/s, avg=0.09878, loss=0.08968]

trial_001 train e003:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:37,  1.30it/s, avg=0.09878, loss=0.08968]

trial_001 train e003:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:16<00:37,  1.30it/s, avg=0.09887, loss=0.10790]

trial_001 train e003:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:37,  1.29it/s, avg=0.09887, loss=0.10790]

trial_001 train e003:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:37,  1.29it/s, avg=0.09876, loss=0.08759]

trial_001 train e003:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:36,  1.28it/s, avg=0.09876, loss=0.08759]

trial_001 train e003:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:17<00:36,  1.28it/s, avg=0.09878, loss=0.10020]

trial_001 train e003:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:35,  1.28it/s, avg=0.09878, loss=0.10020]

trial_001 train e003:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:18<00:35,  1.28it/s, avg=0.09878, loss=0.09878]

trial_001 train e003:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:34,  1.31it/s, avg=0.09878, loss=0.09878]

trial_001 train e003:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:19<00:34,  1.31it/s, avg=0.09884, loss=0.10535]

trial_001 train e003:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:33,  1.33it/s, avg=0.09884, loss=0.10535]

trial_001 train e003:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:33,  1.33it/s, avg=0.09893, loss=0.10852]

trial_001 train e003:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:32,  1.34it/s, avg=0.09893, loss=0.10852]

trial_001 train e003:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:20<00:32,  1.34it/s, avg=0.09895, loss=0.10072]

trial_001 train e003:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:31,  1.35it/s, avg=0.09895, loss=0.10072]

trial_001 train e003:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:21<00:31,  1.35it/s, avg=0.09883, loss=0.08604]

trial_001 train e003:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.34it/s, avg=0.09883, loss=0.08604]

trial_001 train e003:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:22<00:30,  1.34it/s, avg=0.09873, loss=0.08783]

trial_001 train e003:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:30,  1.31it/s, avg=0.09873, loss=0.08783]

trial_001 train e003:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:30,  1.31it/s, avg=0.09878, loss=0.10477]

trial_001 train e003:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:29,  1.31it/s, avg=0.09878, loss=0.10477]

trial_001 train e003:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:23<00:29,  1.31it/s, avg=0.09883, loss=0.10408]

trial_001 train e003:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:28,  1.31it/s, avg=0.09883, loss=0.10408]

trial_001 train e003:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:24<00:28,  1.31it/s, avg=0.09893, loss=0.10972]

trial_001 train e003:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:27,  1.34it/s, avg=0.09893, loss=0.10972]

trial_001 train e003:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:25<00:27,  1.34it/s, avg=0.09882, loss=0.08703]

trial_001 train e003:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:26,  1.34it/s, avg=0.09882, loss=0.08703]

trial_001 train e003:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:26,  1.34it/s, avg=0.09884, loss=0.10073]

trial_001 train e003:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:26,  1.33it/s, avg=0.09884, loss=0.10073]

trial_001 train e003:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:26<00:26,  1.33it/s, avg=0.09890, loss=0.10552]

trial_001 train e003:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.32it/s, avg=0.09890, loss=0.10552]

trial_001 train e003:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:27<00:25,  1.32it/s, avg=0.09885, loss=0.09380]

trial_001 train e003:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:26,  1.27it/s, avg=0.09885, loss=0.09380]

trial_001 train e003:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:28<00:26,  1.27it/s, avg=0.09879, loss=0.09158]

trial_001 train e003:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:25,  1.27it/s, avg=0.09879, loss=0.09158]

trial_001 train e003:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:29<00:25,  1.27it/s, avg=0.09875, loss=0.09362]

trial_001 train e003:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:29<00:24,  1.27it/s, avg=0.09875, loss=0.09362]

trial_001 train e003:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:29<00:24,  1.27it/s, avg=0.09874, loss=0.09813]

trial_001 train e003:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:23,  1.27it/s, avg=0.09874, loss=0.09813]

trial_001 train e003:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:30<00:23,  1.27it/s, avg=0.09879, loss=0.10425]

trial_001 train e003:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:22,  1.28it/s, avg=0.09879, loss=0.10425]

trial_001 train e003:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:31<00:22,  1.28it/s, avg=0.09867, loss=0.08453]

trial_001 train e003:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:21,  1.29it/s, avg=0.09867, loss=0.08453]

trial_001 train e003:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:32<00:21,  1.29it/s, avg=0.09860, loss=0.09010]

trial_001 train e003:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:32<00:20,  1.29it/s, avg=0.09860, loss=0.09010]

trial_001 train e003:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:32<00:20,  1.29it/s, avg=0.09859, loss=0.09790]

trial_001 train e003:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:20,  1.29it/s, avg=0.09859, loss=0.09790]

trial_001 train e003:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:33<00:20,  1.29it/s, avg=0.09851, loss=0.08780]

trial_001 train e003:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:19,  1.30it/s, avg=0.09851, loss=0.08780]

trial_001 train e003:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:34<00:19,  1.30it/s, avg=0.09858, loss=0.10821]

trial_001 train e003:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:34<00:18,  1.33it/s, avg=0.09858, loss=0.10821]

trial_001 train e003:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:35<00:18,  1.33it/s, avg=0.09859, loss=0.09912]

trial_001 train e003:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:35<00:17,  1.33it/s, avg=0.09859, loss=0.09912]

trial_001 train e003:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:35<00:17,  1.33it/s, avg=0.09854, loss=0.09267]

trial_001 train e003:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.33it/s, avg=0.09854, loss=0.09267]

trial_001 train e003:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:36<00:16,  1.33it/s, avg=0.09856, loss=0.10070]

trial_001 train e003:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.33it/s, avg=0.09856, loss=0.10070]

trial_001 train e003:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:37<00:15,  1.33it/s, avg=0.09856, loss=0.09944]

trial_001 train e003:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:37<00:15,  1.32it/s, avg=0.09856, loss=0.09944]

trial_001 train e003:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:38<00:15,  1.32it/s, avg=0.09864, loss=0.10785]

trial_001 train e003:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:38<00:14,  1.33it/s, avg=0.09864, loss=0.10785]

trial_001 train e003:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:38<00:14,  1.33it/s, avg=0.09872, loss=0.11005]

trial_001 train e003:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.31it/s, avg=0.09872, loss=0.11005]

trial_001 train e003:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:39<00:13,  1.31it/s, avg=0.09863, loss=0.08688]

trial_001 train e003:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.34it/s, avg=0.09863, loss=0.08688]

trial_001 train e003:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:40<00:12,  1.34it/s, avg=0.09851, loss=0.08205]

trial_001 train e003:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:12,  1.32it/s, avg=0.09851, loss=0.08205]

trial_001 train e003:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:41<00:12,  1.32it/s, avg=0.09847, loss=0.09304]

trial_001 train e003:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:41<00:11,  1.31it/s, avg=0.09847, loss=0.09304]

trial_001 train e003:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:41<00:11,  1.31it/s, avg=0.09844, loss=0.09416]

trial_001 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.33it/s, avg=0.09844, loss=0.09416]

trial_001 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:42<00:10,  1.33it/s, avg=0.09844, loss=0.09896]

trial_001 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.33it/s, avg=0.09844, loss=0.09896]

trial_001 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:43<00:09,  1.33it/s, avg=0.09837, loss=0.08861]

trial_001 train e003:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:43<00:09,  1.29it/s, avg=0.09837, loss=0.08861]

trial_001 train e003:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:44<00:09,  1.29it/s, avg=0.09827, loss=0.08421]

trial_001 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:44<00:08,  1.29it/s, avg=0.09827, loss=0.08421]

trial_001 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:44<00:08,  1.29it/s, avg=0.09818, loss=0.08642]

trial_001 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.31it/s, avg=0.09818, loss=0.08642]

trial_001 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:45<00:07,  1.31it/s, avg=0.09819, loss=0.09966]

trial_001 train e003:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.31it/s, avg=0.09819, loss=0.09966]

trial_001 train e003:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:46<00:06,  1.31it/s, avg=0.09810, loss=0.08609]

trial_001 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:46<00:06,  1.32it/s, avg=0.09810, loss=0.08609]

trial_001 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:47<00:06,  1.32it/s, avg=0.09809, loss=0.09640]

trial_001 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:47<00:05,  1.34it/s, avg=0.09809, loss=0.09640]

trial_001 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:47<00:05,  1.34it/s, avg=0.09804, loss=0.09023]

trial_001 train e003:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.32it/s, avg=0.09804, loss=0.09023]

trial_001 train e003:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:48<00:04,  1.32it/s, avg=0.09806, loss=0.10079]

trial_001 train e003:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.31it/s, avg=0.09806, loss=0.10079]

trial_001 train e003:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:49<00:03,  1.31it/s, avg=0.09809, loss=0.10322]

trial_001 train e003:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:49<00:03,  1.30it/s, avg=0.09809, loss=0.10322]

trial_001 train e003:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:50<00:03,  1.30it/s, avg=0.09808, loss=0.09569]

trial_001 train e003:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:50<00:02,  1.30it/s, avg=0.09808, loss=0.09569]

trial_001 train e003:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:51<00:02,  1.30it/s, avg=0.09806, loss=0.09544]

trial_001 train e003:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:51<00:01,  1.30it/s, avg=0.09806, loss=0.09544]

trial_001 train e003:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:51<00:01,  1.30it/s, avg=0.09817, loss=0.11455]

trial_001 train e003:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.29it/s, avg=0.09817, loss=0.11455]

trial_001 train e003:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:52<00:00,  1.29it/s, avg=0.09816, loss=0.09612]

trial_001 train e003: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:52<00:00,  1.59it/s, avg=0.09816, loss=0.09612]

trial_001 val e003:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e003:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.29it/s]

trial_001 val e003:   4%|█████                                                                                                                        | 2/50 [00:00<00:21,  2.28it/s]

trial_001 val e003:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.28it/s]

trial_001 val e003:   8%|██████████                                                                                                                   | 4/50 [00:01<00:20,  2.26it/s]

trial_001 val e003:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:20,  2.24it/s]

trial_001 val e003:  12%|███████████████                                                                                                              | 6/50 [00:02<00:19,  2.24it/s]

trial_001 val e003:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:19,  2.25it/s]

trial_001 val e003:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:18,  2.26it/s]

trial_001 val e003:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:18,  2.25it/s]

trial_001 val e003:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.26it/s]

trial_001 val e003:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:17,  2.26it/s]

trial_001 val e003:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.27it/s]

trial_001 val e003:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:16,  2.27it/s]

trial_001 val e003:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.27it/s]

trial_001 val e003:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.24it/s]

trial_001 val e003:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:07<00:15,  2.24it/s]

trial_001 val e003:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.24it/s]

trial_001 val e003:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:14,  2.24it/s]

trial_001 val e003:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.25it/s]

trial_001 val e003:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:13,  2.26it/s]

trial_001 val e003:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.27it/s]

trial_001 val e003:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.28it/s]

trial_001 val e003:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:10<00:11,  2.28it/s]

trial_001 val e003:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.28it/s]

trial_001 val e003:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:11<00:10,  2.28it/s]

trial_001 val e003:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.28it/s]

trial_001 val e003:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:10,  2.28it/s]

trial_001 val e003:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.28it/s]

trial_001 val e003:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.28it/s]

trial_001 val e003:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:13<00:08,  2.26it/s]

trial_001 val e003:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.24it/s]

trial_001 val e003:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:14<00:08,  2.25it/s]

trial_001 val e003:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.26it/s]

trial_001 val e003:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:15<00:07,  2.26it/s]

trial_001 val e003:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.27it/s]

trial_001 val e003:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.27it/s]

trial_001 val e003:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:16<00:05,  2.28it/s]

trial_001 val e003:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.28it/s]

trial_001 val e003:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:17<00:04,  2.29it/s]

trial_001 val e003:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.29it/s]

trial_001 val e003:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:18<00:03,  2.29it/s]

trial_001 val e003:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.27it/s]

trial_001 val e003:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.26it/s]

trial_001 val e003:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.27it/s]

trial_001 val e003:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.28it/s]

trial_001 val e003:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:20<00:01,  2.28it/s]

trial_001 val e003:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.27it/s]

trial_001 val e003:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:21<00:00,  2.28it/s]

trial_001 val e003:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.28it/s]

trial_001 val e003: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:22<00:00,  2.31it/s]

[2026-05-28 20:10:00] [trial_001] epoch=003 | train_loss=0.098164 | val_MAE=0.100199 | val_S=0.899801 | best_S=0.899801 @epoch=3 | patience=0/5

[trial_001] epochs:   3%|███▋                                                                                                                     | 3/100 [06:43<3:37:44, 134.69s/it]

trial_001 train e004:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e004:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09806, loss=0.09806]

trial_001 train e004:   1%|▋                                                                                              | 1/149 [00:00<01:43,  1.43it/s, avg=0.09806, loss=0.09806]

trial_001 train e004:   1%|▋                                                                                              | 1/149 [00:01<01:43,  1.43it/s, avg=0.10015, loss=0.10225]

trial_001 train e004:   1%|█▎                                                                                             | 2/149 [00:01<01:45,  1.40it/s, avg=0.10015, loss=0.10225]

trial_001 train e004:   1%|█▎                                                                                             | 2/149 [00:02<01:45,  1.40it/s, avg=0.10679, loss=0.12005]

trial_001 train e004:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.10679, loss=0.12005]

trial_001 train e004:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.10391, loss=0.09528]

trial_001 train e004:   3%|██▌                                                                                            | 4/149 [00:02<01:47,  1.34it/s, avg=0.10391, loss=0.09528]

trial_001 train e004:   3%|██▌                                                                                            | 4/149 [00:03<01:47,  1.34it/s, avg=0.10084, loss=0.08858]

trial_001 train e004:   3%|███▏                                                                                           | 5/149 [00:03<01:47,  1.34it/s, avg=0.10084, loss=0.08858]

trial_001 train e004:   3%|███▏                                                                                           | 5/149 [00:04<01:47,  1.34it/s, avg=0.10209, loss=0.10831]

trial_001 train e004:   4%|███▊                                                                                           | 6/149 [00:04<01:48,  1.32it/s, avg=0.10209, loss=0.10831]

trial_001 train e004:   4%|███▊                                                                                           | 6/149 [00:05<01:48,  1.32it/s, avg=0.10072, loss=0.09251]

trial_001 train e004:   5%|████▍                                                                                          | 7/149 [00:05<01:47,  1.32it/s, avg=0.10072, loss=0.09251]

trial_001 train e004:   5%|████▍                                                                                          | 7/149 [00:05<01:47,  1.32it/s, avg=0.09868, loss=0.08436]

trial_001 train e004:   5%|█████                                                                                          | 8/149 [00:05<01:46,  1.32it/s, avg=0.09868, loss=0.08436]

trial_001 train e004:   5%|█████                                                                                          | 8/149 [00:06<01:46,  1.32it/s, avg=0.09824, loss=0.09479]

trial_001 train e004:   6%|█████▋                                                                                         | 9/149 [00:06<01:46,  1.32it/s, avg=0.09824, loss=0.09479]

trial_001 train e004:   6%|█████▋                                                                                         | 9/149 [00:07<01:46,  1.32it/s, avg=0.10006, loss=0.11635]

trial_001 train e004:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.36it/s, avg=0.10006, loss=0.11635]

trial_001 train e004:   7%|██████▎                                                                                       | 10/149 [00:08<01:42,  1.36it/s, avg=0.10024, loss=0.10210]

trial_001 train e004:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.35it/s, avg=0.10024, loss=0.10210]

trial_001 train e004:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.35it/s, avg=0.09934, loss=0.08947]

trial_001 train e004:   8%|███████▌                                                                                      | 12/149 [00:08<01:42,  1.33it/s, avg=0.09934, loss=0.08947]

trial_001 train e004:   8%|███████▌                                                                                      | 12/149 [00:09<01:42,  1.33it/s, avg=0.09830, loss=0.08578]

trial_001 train e004:   9%|████████▏                                                                                     | 13/149 [00:09<01:42,  1.33it/s, avg=0.09830, loss=0.08578]

trial_001 train e004:   9%|████████▏                                                                                     | 13/149 [00:10<01:42,  1.33it/s, avg=0.09799, loss=0.09397]

trial_001 train e004:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.33it/s, avg=0.09799, loss=0.09397]

trial_001 train e004:   9%|████████▊                                                                                     | 14/149 [00:11<01:41,  1.33it/s, avg=0.09788, loss=0.09633]

trial_001 train e004:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.33it/s, avg=0.09788, loss=0.09633]

trial_001 train e004:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.33it/s, avg=0.09892, loss=0.11451]

trial_001 train e004:  11%|██████████                                                                                    | 16/149 [00:11<01:40,  1.33it/s, avg=0.09892, loss=0.11451]

trial_001 train e004:  11%|██████████                                                                                    | 16/149 [00:12<01:40,  1.33it/s, avg=0.09911, loss=0.10214]

trial_001 train e004:  11%|██████████▋                                                                                   | 17/149 [00:12<01:40,  1.31it/s, avg=0.09911, loss=0.10214]

trial_001 train e004:  11%|██████████▋                                                                                   | 17/149 [00:13<01:40,  1.31it/s, avg=0.09823, loss=0.08330]

trial_001 train e004:  12%|███████████▎                                                                                  | 18/149 [00:13<01:40,  1.30it/s, avg=0.09823, loss=0.08330]

trial_001 train e004:  12%|███████████▎                                                                                  | 18/149 [00:14<01:40,  1.30it/s, avg=0.09805, loss=0.09482]

trial_001 train e004:  13%|███████████▉                                                                                  | 19/149 [00:14<01:39,  1.31it/s, avg=0.09805, loss=0.09482]

trial_001 train e004:  13%|███████████▉                                                                                  | 19/149 [00:15<01:39,  1.31it/s, avg=0.09766, loss=0.09023]

trial_001 train e004:  13%|████████████▌                                                                                 | 20/149 [00:15<01:37,  1.33it/s, avg=0.09766, loss=0.09023]

trial_001 train e004:  13%|████████████▌                                                                                 | 20/149 [00:15<01:37,  1.33it/s, avg=0.09776, loss=0.09972]

trial_001 train e004:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.33it/s, avg=0.09776, loss=0.09972]

trial_001 train e004:  14%|█████████████▏                                                                                | 21/149 [00:16<01:36,  1.33it/s, avg=0.09786, loss=0.09993]

trial_001 train e004:  15%|█████████████▉                                                                                | 22/149 [00:16<01:33,  1.36it/s, avg=0.09786, loss=0.09993]

trial_001 train e004:  15%|█████████████▉                                                                                | 22/149 [00:17<01:33,  1.36it/s, avg=0.09888, loss=0.12144]

trial_001 train e004:  15%|██████████████▌                                                                               | 23/149 [00:17<01:31,  1.38it/s, avg=0.09888, loss=0.12144]

trial_001 train e004:  15%|██████████████▌                                                                               | 23/149 [00:17<01:31,  1.38it/s, avg=0.09908, loss=0.10371]

trial_001 train e004:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.37it/s, avg=0.09908, loss=0.10371]

trial_001 train e004:  16%|███████████████▏                                                                              | 24/149 [00:18<01:31,  1.37it/s, avg=0.09920, loss=0.10210]

trial_001 train e004:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.39it/s, avg=0.09920, loss=0.10210]

trial_001 train e004:  17%|███████████████▊                                                                              | 25/149 [00:19<01:29,  1.39it/s, avg=0.09922, loss=0.09958]

trial_001 train e004:  17%|████████████████▍                                                                             | 26/149 [00:19<01:29,  1.37it/s, avg=0.09922, loss=0.09958]

trial_001 train e004:  17%|████████████████▍                                                                             | 26/149 [00:20<01:29,  1.37it/s, avg=0.09847, loss=0.07908]

trial_001 train e004:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.36it/s, avg=0.09847, loss=0.07908]

trial_001 train e004:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.36it/s, avg=0.09882, loss=0.10821]

trial_001 train e004:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.36it/s, avg=0.09882, loss=0.10821]

trial_001 train e004:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:28,  1.36it/s, avg=0.09911, loss=0.10731]

trial_001 train e004:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:27,  1.37it/s, avg=0.09911, loss=0.10731]

trial_001 train e004:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:27,  1.37it/s, avg=0.09937, loss=0.10676]

trial_001 train e004:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:28,  1.34it/s, avg=0.09937, loss=0.10676]

trial_001 train e004:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:28,  1.34it/s, avg=0.09931, loss=0.09763]

trial_001 train e004:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.36it/s, avg=0.09931, loss=0.09763]

trial_001 train e004:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.36it/s, avg=0.09905, loss=0.09096]

trial_001 train e004:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.36it/s, avg=0.09905, loss=0.09096]

trial_001 train e004:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:26,  1.36it/s, avg=0.09921, loss=0.10417]

trial_001 train e004:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:25,  1.35it/s, avg=0.09921, loss=0.10417]

trial_001 train e004:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:25,  1.35it/s, avg=0.09876, loss=0.08402]

trial_001 train e004:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.09876, loss=0.08402]

trial_001 train e004:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:23,  1.37it/s, avg=0.09886, loss=0.10212]

trial_001 train e004:  23%|██████████████████████                                                                        | 35/149 [00:26<01:24,  1.35it/s, avg=0.09886, loss=0.10212]

trial_001 train e004:  23%|██████████████████████                                                                        | 35/149 [00:26<01:24,  1.35it/s, avg=0.09894, loss=0.10194]

trial_001 train e004:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:24,  1.34it/s, avg=0.09894, loss=0.10194]

trial_001 train e004:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:24,  1.34it/s, avg=0.09869, loss=0.08979]

trial_001 train e004:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:24,  1.33it/s, avg=0.09869, loss=0.08979]

trial_001 train e004:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:24,  1.33it/s, avg=0.09855, loss=0.09312]

trial_001 train e004:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:23,  1.34it/s, avg=0.09855, loss=0.09312]

trial_001 train e004:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:23,  1.34it/s, avg=0.09835, loss=0.09094]

trial_001 train e004:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:21,  1.35it/s, avg=0.09835, loss=0.09094]

trial_001 train e004:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:21,  1.35it/s, avg=0.09859, loss=0.10770]

trial_001 train e004:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:20,  1.35it/s, avg=0.09859, loss=0.10770]

trial_001 train e004:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:20,  1.35it/s, avg=0.09852, loss=0.09583]

trial_001 train e004:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:20,  1.35it/s, avg=0.09852, loss=0.09583]

trial_001 train e004:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:20,  1.35it/s, avg=0.09893, loss=0.11593]

trial_001 train e004:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:19,  1.34it/s, avg=0.09893, loss=0.11593]

trial_001 train e004:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:19,  1.34it/s, avg=0.09898, loss=0.10089]

trial_001 train e004:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:17,  1.37it/s, avg=0.09898, loss=0.10089]

trial_001 train e004:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:17,  1.37it/s, avg=0.09875, loss=0.08891]

trial_001 train e004:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:17,  1.36it/s, avg=0.09875, loss=0.08891]

trial_001 train e004:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:17,  1.36it/s, avg=0.09892, loss=0.10661]

trial_001 train e004:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.37it/s, avg=0.09892, loss=0.10661]

trial_001 train e004:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:15,  1.37it/s, avg=0.09895, loss=0.10012]

trial_001 train e004:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:15,  1.37it/s, avg=0.09895, loss=0.10012]

trial_001 train e004:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:15,  1.37it/s, avg=0.09895, loss=0.09916]

trial_001 train e004:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:16,  1.34it/s, avg=0.09895, loss=0.09916]

trial_001 train e004:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:16,  1.34it/s, avg=0.09895, loss=0.09880]

trial_001 train e004:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:15,  1.34it/s, avg=0.09895, loss=0.09880]

trial_001 train e004:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:15,  1.34it/s, avg=0.09899, loss=0.10078]

trial_001 train e004:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:14,  1.33it/s, avg=0.09899, loss=0.10078]

trial_001 train e004:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:14,  1.33it/s, avg=0.09881, loss=0.09001]

trial_001 train e004:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:14,  1.33it/s, avg=0.09881, loss=0.09001]

trial_001 train e004:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:14,  1.33it/s, avg=0.09881, loss=0.09885]

trial_001 train e004:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:13,  1.33it/s, avg=0.09881, loss=0.09885]

trial_001 train e004:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:13,  1.33it/s, avg=0.09877, loss=0.09652]

trial_001 train e004:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.09877, loss=0.09652]

trial_001 train e004:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:10,  1.37it/s, avg=0.09860, loss=0.09009]

trial_001 train e004:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.37it/s, avg=0.09860, loss=0.09009]

trial_001 train e004:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:10,  1.37it/s, avg=0.09833, loss=0.08377]

trial_001 train e004:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:11,  1.33it/s, avg=0.09833, loss=0.08377]

trial_001 train e004:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:11,  1.33it/s, avg=0.09835, loss=0.09966]

trial_001 train e004:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:09,  1.35it/s, avg=0.09835, loss=0.09966]

trial_001 train e004:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:09,  1.35it/s, avg=0.09829, loss=0.09510]

trial_001 train e004:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:08,  1.35it/s, avg=0.09829, loss=0.09510]

trial_001 train e004:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:08,  1.35it/s, avg=0.09810, loss=0.08706]

trial_001 train e004:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.34it/s, avg=0.09810, loss=0.08706]

trial_001 train e004:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:08,  1.34it/s, avg=0.09828, loss=0.10857]

trial_001 train e004:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:07,  1.35it/s, avg=0.09828, loss=0.10857]

trial_001 train e004:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:07,  1.35it/s, avg=0.09827, loss=0.09765]

trial_001 train e004:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09827, loss=0.09765]

trial_001 train e004:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:06,  1.36it/s, avg=0.09811, loss=0.08897]

trial_001 train e004:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:06,  1.34it/s, avg=0.09811, loss=0.08897]

trial_001 train e004:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:06,  1.34it/s, avg=0.09821, loss=0.10401]

trial_001 train e004:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:06,  1.33it/s, avg=0.09821, loss=0.10401]

trial_001 train e004:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:06,  1.33it/s, avg=0.09818, loss=0.09665]

trial_001 train e004:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:05,  1.33it/s, avg=0.09818, loss=0.09665]

trial_001 train e004:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:05,  1.33it/s, avg=0.09808, loss=0.09153]

trial_001 train e004:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:05,  1.32it/s, avg=0.09808, loss=0.09153]

trial_001 train e004:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:05,  1.32it/s, avg=0.09797, loss=0.09135]

trial_001 train e004:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:04,  1.32it/s, avg=0.09797, loss=0.09135]

trial_001 train e004:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:04,  1.32it/s, avg=0.09790, loss=0.09342]

trial_001 train e004:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:04,  1.31it/s, avg=0.09790, loss=0.09342]

trial_001 train e004:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:04,  1.31it/s, avg=0.09793, loss=0.09987]

trial_001 train e004:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:03,  1.30it/s, avg=0.09793, loss=0.09987]

trial_001 train e004:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:03,  1.30it/s, avg=0.09789, loss=0.09534]

trial_001 train e004:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:02,  1.31it/s, avg=0.09789, loss=0.09534]

trial_001 train e004:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:02,  1.31it/s, avg=0.09773, loss=0.08671]

trial_001 train e004:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<01:02,  1.30it/s, avg=0.09773, loss=0.08671]

trial_001 train e004:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:02,  1.30it/s, avg=0.09790, loss=0.10925]

trial_001 train e004:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<01:00,  1.32it/s, avg=0.09790, loss=0.10925]

trial_001 train e004:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<01:00,  1.32it/s, avg=0.09795, loss=0.10155]

trial_001 train e004:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:59,  1.32it/s, avg=0.09795, loss=0.10155]

trial_001 train e004:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:59,  1.32it/s, avg=0.09819, loss=0.11504]

trial_001 train e004:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.35it/s, avg=0.09819, loss=0.11504]

trial_001 train e004:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:57,  1.35it/s, avg=0.09808, loss=0.09047]

trial_001 train e004:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:57,  1.33it/s, avg=0.09808, loss=0.09047]

trial_001 train e004:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:57,  1.33it/s, avg=0.09792, loss=0.08635]

trial_001 train e004:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:56,  1.35it/s, avg=0.09792, loss=0.08635]

trial_001 train e004:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:56,  1.35it/s, avg=0.09797, loss=0.10154]

trial_001 train e004:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:54,  1.36it/s, avg=0.09797, loss=0.10154]

trial_001 train e004:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:54,  1.36it/s, avg=0.09813, loss=0.11008]

trial_001 train e004:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:55,  1.34it/s, avg=0.09813, loss=0.11008]

trial_001 train e004:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:55,  1.34it/s, avg=0.09805, loss=0.09179]

trial_001 train e004:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:54,  1.35it/s, avg=0.09805, loss=0.09179]

trial_001 train e004:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:54,  1.35it/s, avg=0.09790, loss=0.08637]

trial_001 train e004:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:53,  1.34it/s, avg=0.09790, loss=0.08637]

trial_001 train e004:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:53,  1.34it/s, avg=0.09784, loss=0.09339]

trial_001 train e004:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:52,  1.34it/s, avg=0.09784, loss=0.09339]

trial_001 train e004:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:52,  1.34it/s, avg=0.09789, loss=0.10214]

trial_001 train e004:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:52,  1.34it/s, avg=0.09789, loss=0.10214]

trial_001 train e004:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:52,  1.34it/s, avg=0.09806, loss=0.11130]

trial_001 train e004:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:50,  1.36it/s, avg=0.09806, loss=0.11130]

trial_001 train e004:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:50,  1.36it/s, avg=0.09799, loss=0.09206]

trial_001 train e004:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:50,  1.35it/s, avg=0.09799, loss=0.09206]

trial_001 train e004:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:50,  1.35it/s, avg=0.09799, loss=0.09831]

trial_001 train e004:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:50,  1.32it/s, avg=0.09799, loss=0.09831]

trial_001 train e004:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:50,  1.32it/s, avg=0.09800, loss=0.09894]

trial_001 train e004:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:50,  1.29it/s, avg=0.09800, loss=0.09894]

trial_001 train e004:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:50,  1.29it/s, avg=0.09799, loss=0.09699]

trial_001 train e004:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:48,  1.34it/s, avg=0.09799, loss=0.09699]

trial_001 train e004:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.34it/s, avg=0.09801, loss=0.09938]

trial_001 train e004:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:48,  1.33it/s, avg=0.09801, loss=0.09938]

trial_001 train e004:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:48,  1.33it/s, avg=0.09783, loss=0.08303]

trial_001 train e004:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:46,  1.34it/s, avg=0.09783, loss=0.08303]

trial_001 train e004:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:46,  1.34it/s, avg=0.09769, loss=0.08519]

trial_001 train e004:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:46,  1.34it/s, avg=0.09769, loss=0.08519]

trial_001 train e004:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:46,  1.34it/s, avg=0.09756, loss=0.08612]

trial_001 train e004:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:45,  1.35it/s, avg=0.09756, loss=0.08612]

trial_001 train e004:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:45,  1.35it/s, avg=0.09745, loss=0.08812]

trial_001 train e004:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.35it/s, avg=0.09745, loss=0.08812]

trial_001 train e004:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:44,  1.35it/s, avg=0.09747, loss=0.09939]

trial_001 train e004:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:43,  1.34it/s, avg=0.09747, loss=0.09939]

trial_001 train e004:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:43,  1.34it/s, avg=0.09766, loss=0.11419]

trial_001 train e004:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:43,  1.34it/s, avg=0.09766, loss=0.11419]

trial_001 train e004:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:43,  1.34it/s, avg=0.09774, loss=0.10549]

trial_001 train e004:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:42,  1.33it/s, avg=0.09774, loss=0.10549]

trial_001 train e004:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:42,  1.33it/s, avg=0.09761, loss=0.08576]

trial_001 train e004:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:42,  1.32it/s, avg=0.09761, loss=0.08576]

trial_001 train e004:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:42,  1.32it/s, avg=0.09764, loss=0.10048]

trial_001 train e004:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:40,  1.36it/s, avg=0.09764, loss=0.10048]

trial_001 train e004:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:40,  1.36it/s, avg=0.09750, loss=0.08416]

trial_001 train e004:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:39,  1.35it/s, avg=0.09750, loss=0.08416]

trial_001 train e004:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:39,  1.35it/s, avg=0.09746, loss=0.09374]

trial_001 train e004:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:38,  1.37it/s, avg=0.09746, loss=0.09374]

trial_001 train e004:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:38,  1.37it/s, avg=0.09744, loss=0.09556]

trial_001 train e004:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.36it/s, avg=0.09744, loss=0.09556]

trial_001 train e004:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.36it/s, avg=0.09744, loss=0.09703]

trial_001 train e004:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.37it/s, avg=0.09744, loss=0.09703]

trial_001 train e004:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:37,  1.37it/s, avg=0.09756, loss=0.10964]

trial_001 train e004:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:37,  1.34it/s, avg=0.09756, loss=0.10964]

trial_001 train e004:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:37,  1.34it/s, avg=0.09749, loss=0.09017]

trial_001 train e004:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:36,  1.36it/s, avg=0.09749, loss=0.09017]

trial_001 train e004:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:36,  1.36it/s, avg=0.09752, loss=0.10054]

trial_001 train e004:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:35,  1.36it/s, avg=0.09752, loss=0.10054]

trial_001 train e004:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:35,  1.36it/s, avg=0.09756, loss=0.10240]

trial_001 train e004:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:34,  1.35it/s, avg=0.09756, loss=0.10240]

trial_001 train e004:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:34,  1.35it/s, avg=0.09745, loss=0.08564]

trial_001 train e004:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:33,  1.36it/s, avg=0.09745, loss=0.08564]

trial_001 train e004:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:33,  1.36it/s, avg=0.09758, loss=0.11156]

trial_001 train e004:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:32,  1.38it/s, avg=0.09758, loss=0.11156]

trial_001 train e004:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:32,  1.38it/s, avg=0.09746, loss=0.08451]

trial_001 train e004:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:32,  1.34it/s, avg=0.09746, loss=0.08451]

trial_001 train e004:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:32,  1.34it/s, avg=0.09733, loss=0.08327]

trial_001 train e004:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:31,  1.35it/s, avg=0.09733, loss=0.08327]

trial_001 train e004:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:31,  1.35it/s, avg=0.09733, loss=0.09806]

trial_001 train e004:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:31,  1.34it/s, avg=0.09733, loss=0.09806]

trial_001 train e004:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:31,  1.34it/s, avg=0.09727, loss=0.09096]

trial_001 train e004:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:30,  1.35it/s, avg=0.09727, loss=0.09096]

trial_001 train e004:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.35it/s, avg=0.09719, loss=0.08856]

trial_001 train e004:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:29,  1.36it/s, avg=0.09719, loss=0.08856]

trial_001 train e004:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:29,  1.36it/s, avg=0.09710, loss=0.08666]

trial_001 train e004:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:28,  1.37it/s, avg=0.09710, loss=0.08666]

trial_001 train e004:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:28,  1.37it/s, avg=0.09707, loss=0.09360]

trial_001 train e004:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:27,  1.36it/s, avg=0.09707, loss=0.09360]

trial_001 train e004:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:27,  1.36it/s, avg=0.09702, loss=0.09181]

trial_001 train e004:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:27,  1.36it/s, avg=0.09702, loss=0.09181]

trial_001 train e004:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:27,  1.36it/s, avg=0.09704, loss=0.09947]

trial_001 train e004:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:26,  1.36it/s, avg=0.09704, loss=0.09947]

trial_001 train e004:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:26,  1.36it/s, avg=0.09708, loss=0.10105]

trial_001 train e004:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.36it/s, avg=0.09708, loss=0.10105]

trial_001 train e004:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:25,  1.36it/s, avg=0.09715, loss=0.10537]

trial_001 train e004:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:25<00:25,  1.35it/s, avg=0.09715, loss=0.10537]

trial_001 train e004:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.35it/s, avg=0.09712, loss=0.09428]

trial_001 train e004:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:26<00:24,  1.34it/s, avg=0.09712, loss=0.09428]

trial_001 train e004:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.34it/s, avg=0.09707, loss=0.09109]

trial_001 train e004:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:24,  1.33it/s, avg=0.09707, loss=0.09109]

trial_001 train e004:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:24,  1.33it/s, avg=0.09708, loss=0.09770]

trial_001 train e004:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:22,  1.36it/s, avg=0.09708, loss=0.09770]

trial_001 train e004:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:22,  1.36it/s, avg=0.09715, loss=0.10539]

trial_001 train e004:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:28<00:22,  1.35it/s, avg=0.09715, loss=0.10539]

trial_001 train e004:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.35it/s, avg=0.09703, loss=0.08336]

trial_001 train e004:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:29<00:21,  1.33it/s, avg=0.09703, loss=0.08336]

trial_001 train e004:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:29<00:21,  1.33it/s, avg=0.09707, loss=0.10138]

trial_001 train e004:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.36it/s, avg=0.09707, loss=0.10138]

trial_001 train e004:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:20,  1.36it/s, avg=0.09723, loss=0.11638]

trial_001 train e004:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:19,  1.37it/s, avg=0.09723, loss=0.11638]

trial_001 train e004:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:19,  1.37it/s, avg=0.09734, loss=0.11067]

trial_001 train e004:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:31<00:19,  1.34it/s, avg=0.09734, loss=0.11067]

trial_001 train e004:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.34it/s, avg=0.09727, loss=0.08968]

trial_001 train e004:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:32<00:18,  1.34it/s, avg=0.09727, loss=0.08968]

trial_001 train e004:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:32<00:18,  1.34it/s, avg=0.09724, loss=0.09345]

trial_001 train e004:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.34it/s, avg=0.09724, loss=0.09345]

trial_001 train e004:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.34it/s, avg=0.09739, loss=0.11582]

trial_001 train e004:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:16,  1.36it/s, avg=0.09739, loss=0.11582]

trial_001 train e004:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:16,  1.36it/s, avg=0.09744, loss=0.10316]

trial_001 train e004:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:34<00:16,  1.36it/s, avg=0.09744, loss=0.10316]

trial_001 train e004:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.36it/s, avg=0.09744, loss=0.09742]

trial_001 train e004:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:35<00:15,  1.35it/s, avg=0.09744, loss=0.09742]

trial_001 train e004:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:35<00:15,  1.35it/s, avg=0.09741, loss=0.09413]

trial_001 train e004:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.36it/s, avg=0.09741, loss=0.09413]

trial_001 train e004:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:14,  1.36it/s, avg=0.09735, loss=0.08939]

trial_001 train e004:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:14,  1.35it/s, avg=0.09735, loss=0.08939]

trial_001 train e004:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.35it/s, avg=0.09731, loss=0.09186]

trial_001 train e004:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:37<00:13,  1.38it/s, avg=0.09731, loss=0.09186]

trial_001 train e004:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.38it/s, avg=0.09723, loss=0.08733]

trial_001 train e004:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:38<00:12,  1.38it/s, avg=0.09723, loss=0.08733]

trial_001 train e004:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:38<00:12,  1.38it/s, avg=0.09727, loss=0.10173]

trial_001 train e004:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:11,  1.37it/s, avg=0.09727, loss=0.10173]

trial_001 train e004:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:11,  1.37it/s, avg=0.09732, loss=0.10491]

trial_001 train e004:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:39<00:10,  1.38it/s, avg=0.09732, loss=0.10491]

trial_001 train e004:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:10,  1.38it/s, avg=0.09734, loss=0.09985]

trial_001 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:40<00:10,  1.33it/s, avg=0.09734, loss=0.09985]

trial_001 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.33it/s, avg=0.09743, loss=0.11005]

trial_001 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:41<00:09,  1.32it/s, avg=0.09743, loss=0.11005]

trial_001 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:41<00:09,  1.32it/s, avg=0.09748, loss=0.10396]

trial_001 train e004:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:41<00:09,  1.33it/s, avg=0.09748, loss=0.10396]

trial_001 train e004:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:09,  1.33it/s, avg=0.09746, loss=0.09415]

trial_001 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:42<00:08,  1.32it/s, avg=0.09746, loss=0.09415]

trial_001 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.32it/s, avg=0.09746, loss=0.09833]

trial_001 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:43<00:07,  1.31it/s, avg=0.09746, loss=0.09833]

trial_001 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.31it/s, avg=0.09736, loss=0.08221]

trial_001 train e004:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:44<00:06,  1.31it/s, avg=0.09736, loss=0.08221]

trial_001 train e004:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:44<00:06,  1.31it/s, avg=0.09731, loss=0.09081]

trial_001 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:44<00:06,  1.30it/s, avg=0.09731, loss=0.09081]

trial_001 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:06,  1.30it/s, avg=0.09732, loss=0.09887]

trial_001 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:45<00:05,  1.30it/s, avg=0.09732, loss=0.09887]

trial_001 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.30it/s, avg=0.09728, loss=0.09169]

trial_001 train e004:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:46<00:04,  1.30it/s, avg=0.09728, loss=0.09169]

trial_001 train e004:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.30it/s, avg=0.09731, loss=0.10108]

trial_001 train e004:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:47<00:03,  1.31it/s, avg=0.09731, loss=0.10108]

trial_001 train e004:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:47<00:03,  1.31it/s, avg=0.09731, loss=0.09707]

trial_001 train e004:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:47<00:03,  1.31it/s, avg=0.09731, loss=0.09707]

trial_001 train e004:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:03,  1.31it/s, avg=0.09725, loss=0.08891]

trial_001 train e004:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:48<00:02,  1.30it/s, avg=0.09725, loss=0.08891]

trial_001 train e004:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.30it/s, avg=0.09717, loss=0.08546]

trial_001 train e004:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:49<00:01,  1.32it/s, avg=0.09717, loss=0.08546]

trial_001 train e004:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.32it/s, avg=0.09709, loss=0.08585]

trial_001 train e004:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:50<00:00,  1.33it/s, avg=0.09709, loss=0.08585]

trial_001 train e004:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:50<00:00,  1.33it/s, avg=0.09712, loss=0.10705]

trial_001 train e004: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:50<00:00,  1.61it/s, avg=0.09712, loss=0.10705]

trial_001 val e004:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e004:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.24it/s]

trial_001 val e004:   4%|█████                                                                                                                        | 2/50 [00:00<00:21,  2.26it/s]

trial_001 val e004:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.31it/s]

trial_001 val e004:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.33it/s]

trial_001 val e004:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.33it/s]

trial_001 val e004:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.34it/s]

trial_001 val e004:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:18,  2.34it/s]

trial_001 val e004:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.34it/s]

trial_001 val e004:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.30it/s]

trial_001 val e004:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.30it/s]

trial_001 val e004:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.30it/s]

trial_001 val e004:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.31it/s]

trial_001 val e004:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:16,  2.27it/s]

trial_001 val e004:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.27it/s]

trial_001 val e004:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.26it/s]

trial_001 val e004:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.30it/s]

trial_001 val e004:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.32it/s]

trial_001 val e004:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.33it/s]

trial_001 val e004:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.33it/s]

trial_001 val e004:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.34it/s]

trial_001 val e004:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.34it/s]

trial_001 val e004:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.35it/s]

trial_001 val e004:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.35it/s]

trial_001 val e004:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.35it/s]

trial_001 val e004:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.36it/s]

trial_001 val e004:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.33it/s]

trial_001 val e004:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:10,  2.29it/s]

trial_001 val e004:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.27it/s]

trial_001 val e004:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.29it/s]

trial_001 val e004:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.31it/s]

trial_001 val e004:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.32it/s]

trial_001 val e004:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.32it/s]

trial_001 val e004:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.30it/s]

trial_001 val e004:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.30it/s]

trial_001 val e004:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.31it/s]

trial_001 val e004:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.31it/s]

trial_001 val e004:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.32it/s]

trial_001 val e004:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.32it/s]

trial_001 val e004:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.30it/s]

trial_001 val e004:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.28it/s]

trial_001 val e004:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.30it/s]

trial_001 val e004:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.32it/s]

trial_001 val e004:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.32it/s]

trial_001 val e004:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.31it/s]

trial_001 val e004:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.33it/s]

trial_001 val e004:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.35it/s]

trial_001 val e004:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.35it/s]

trial_001 val e004:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:20<00:00,  2.36it/s]

trial_001 val e004:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.36it/s]

trial_001 val e004: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:21<00:00,  2.39it/s]

[2026-05-28 20:12:14] [trial_001] epoch=004 | train_loss=0.097118 | val_MAE=0.097981 | val_S=0.902019 | best_S=0.902019 @epoch=4 | patience=0/5

[trial_001] epochs:   4%|████▊                                                                                                                    | 4/100 [08:56<3:34:35, 134.12s/it]

trial_001 train e005:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e005:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09342, loss=0.09342]

trial_001 train e005:   1%|▋                                                                                              | 1/149 [00:00<01:53,  1.31it/s, avg=0.09342, loss=0.09342]

trial_001 train e005:   1%|▋                                                                                              | 1/149 [00:01<01:53,  1.31it/s, avg=0.09358, loss=0.09373]

trial_001 train e005:   1%|█▎                                                                                             | 2/149 [00:01<01:56,  1.26it/s, avg=0.09358, loss=0.09373]

trial_001 train e005:   1%|█▎                                                                                             | 2/149 [00:02<01:56,  1.26it/s, avg=0.09416, loss=0.09531]

trial_001 train e005:   2%|█▉                                                                                             | 3/149 [00:02<01:52,  1.30it/s, avg=0.09416, loss=0.09531]

trial_001 train e005:   2%|█▉                                                                                             | 3/149 [00:03<01:52,  1.30it/s, avg=0.09287, loss=0.08900]

trial_001 train e005:   3%|██▌                                                                                            | 4/149 [00:03<01:48,  1.33it/s, avg=0.09287, loss=0.08900]

trial_001 train e005:   3%|██▌                                                                                            | 4/149 [00:03<01:48,  1.33it/s, avg=0.09207, loss=0.08888]

trial_001 train e005:   3%|███▏                                                                                           | 5/149 [00:03<01:46,  1.35it/s, avg=0.09207, loss=0.08888]

trial_001 train e005:   3%|███▏                                                                                           | 5/149 [00:04<01:46,  1.35it/s, avg=0.09135, loss=0.08773]

trial_001 train e005:   4%|███▊                                                                                           | 6/149 [00:04<01:44,  1.36it/s, avg=0.09135, loss=0.08773]

trial_001 train e005:   4%|███▊                                                                                           | 6/149 [00:05<01:44,  1.36it/s, avg=0.08993, loss=0.08145]

trial_001 train e005:   5%|████▍                                                                                          | 7/149 [00:05<01:45,  1.35it/s, avg=0.08993, loss=0.08145]

trial_001 train e005:   5%|████▍                                                                                          | 7/149 [00:06<01:45,  1.35it/s, avg=0.08936, loss=0.08533]

trial_001 train e005:   5%|█████                                                                                          | 8/149 [00:06<01:46,  1.32it/s, avg=0.08936, loss=0.08533]

trial_001 train e005:   5%|█████                                                                                          | 8/149 [00:06<01:46,  1.32it/s, avg=0.08970, loss=0.09245]

trial_001 train e005:   6%|█████▋                                                                                         | 9/149 [00:06<01:46,  1.31it/s, avg=0.08970, loss=0.09245]

trial_001 train e005:   6%|█████▋                                                                                         | 9/149 [00:07<01:46,  1.31it/s, avg=0.08990, loss=0.09165]

trial_001 train e005:   7%|██████▎                                                                                       | 10/149 [00:07<01:44,  1.33it/s, avg=0.08990, loss=0.09165]

trial_001 train e005:   7%|██████▎                                                                                       | 10/149 [00:08<01:44,  1.33it/s, avg=0.09103, loss=0.10239]

trial_001 train e005:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.37it/s, avg=0.09103, loss=0.10239]

trial_001 train e005:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.37it/s, avg=0.09146, loss=0.09618]

trial_001 train e005:   8%|███████▌                                                                                      | 12/149 [00:08<01:42,  1.34it/s, avg=0.09146, loss=0.09618]

trial_001 train e005:   8%|███████▌                                                                                      | 12/149 [00:09<01:42,  1.34it/s, avg=0.09200, loss=0.09841]

trial_001 train e005:   9%|████████▏                                                                                     | 13/149 [00:09<01:41,  1.34it/s, avg=0.09200, loss=0.09841]

trial_001 train e005:   9%|████████▏                                                                                     | 13/149 [00:10<01:41,  1.34it/s, avg=0.09195, loss=0.09134]

trial_001 train e005:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.33it/s, avg=0.09195, loss=0.09134]

trial_001 train e005:   9%|████████▊                                                                                     | 14/149 [00:11<01:41,  1.33it/s, avg=0.09313, loss=0.10967]

trial_001 train e005:  10%|█████████▍                                                                                    | 15/149 [00:11<01:41,  1.31it/s, avg=0.09313, loss=0.10967]

trial_001 train e005:  10%|█████████▍                                                                                    | 15/149 [00:12<01:41,  1.31it/s, avg=0.09376, loss=0.10322]

trial_001 train e005:  11%|██████████                                                                                    | 16/149 [00:12<01:41,  1.32it/s, avg=0.09376, loss=0.10322]

trial_001 train e005:  11%|██████████                                                                                    | 16/149 [00:12<01:41,  1.32it/s, avg=0.09325, loss=0.08513]

trial_001 train e005:  11%|██████████▋                                                                                   | 17/149 [00:12<01:41,  1.31it/s, avg=0.09325, loss=0.08513]

trial_001 train e005:  11%|██████████▋                                                                                   | 17/149 [00:13<01:41,  1.31it/s, avg=0.09343, loss=0.09648]

trial_001 train e005:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.09343, loss=0.09648]

trial_001 train e005:  12%|███████████▎                                                                                  | 18/149 [00:14<01:37,  1.34it/s, avg=0.09328, loss=0.09044]

trial_001 train e005:  13%|███████████▉                                                                                  | 19/149 [00:14<01:37,  1.34it/s, avg=0.09328, loss=0.09044]

trial_001 train e005:  13%|███████████▉                                                                                  | 19/149 [00:15<01:37,  1.34it/s, avg=0.09323, loss=0.09229]

trial_001 train e005:  13%|████████████▌                                                                                 | 20/149 [00:15<01:36,  1.34it/s, avg=0.09323, loss=0.09229]

trial_001 train e005:  13%|████████████▌                                                                                 | 20/149 [00:15<01:36,  1.34it/s, avg=0.09376, loss=0.10441]

trial_001 train e005:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.33it/s, avg=0.09376, loss=0.10441]

trial_001 train e005:  14%|█████████████▏                                                                                | 21/149 [00:16<01:36,  1.33it/s, avg=0.09454, loss=0.11095]

trial_001 train e005:  15%|█████████████▉                                                                                | 22/149 [00:16<01:35,  1.34it/s, avg=0.09454, loss=0.11095]

trial_001 train e005:  15%|█████████████▉                                                                                | 22/149 [00:17<01:35,  1.34it/s, avg=0.09484, loss=0.10146]

trial_001 train e005:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.35it/s, avg=0.09484, loss=0.10146]

trial_001 train e005:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.35it/s, avg=0.09498, loss=0.09827]

trial_001 train e005:  16%|███████████████▏                                                                              | 24/149 [00:17<01:30,  1.38it/s, avg=0.09498, loss=0.09827]

trial_001 train e005:  16%|███████████████▏                                                                              | 24/149 [00:18<01:30,  1.38it/s, avg=0.09462, loss=0.08601]

trial_001 train e005:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.36it/s, avg=0.09462, loss=0.08601]

trial_001 train e005:  17%|███████████████▊                                                                              | 25/149 [00:19<01:31,  1.36it/s, avg=0.09461, loss=0.09420]

trial_001 train e005:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.36it/s, avg=0.09461, loss=0.09420]

trial_001 train e005:  17%|████████████████▍                                                                             | 26/149 [00:20<01:30,  1.36it/s, avg=0.09438, loss=0.08843]

trial_001 train e005:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.37it/s, avg=0.09438, loss=0.08843]

trial_001 train e005:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.37it/s, avg=0.09418, loss=0.08890]

trial_001 train e005:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.37it/s, avg=0.09418, loss=0.08890]

trial_001 train e005:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:28,  1.37it/s, avg=0.09448, loss=0.10273]

trial_001 train e005:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:28,  1.36it/s, avg=0.09448, loss=0.10273]

trial_001 train e005:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:28,  1.36it/s, avg=0.09484, loss=0.10535]

trial_001 train e005:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.35it/s, avg=0.09484, loss=0.10535]

trial_001 train e005:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:27,  1.35it/s, avg=0.09463, loss=0.08841]

trial_001 train e005:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.37it/s, avg=0.09463, loss=0.08841]

trial_001 train e005:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.37it/s, avg=0.09459, loss=0.09316]

trial_001 train e005:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.36it/s, avg=0.09459, loss=0.09316]

trial_001 train e005:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:26,  1.36it/s, avg=0.09451, loss=0.09213]

trial_001 train e005:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:26,  1.34it/s, avg=0.09451, loss=0.09213]

trial_001 train e005:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:26,  1.34it/s, avg=0.09452, loss=0.09470]

trial_001 train e005:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:27,  1.32it/s, avg=0.09452, loss=0.09470]

trial_001 train e005:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:27,  1.32it/s, avg=0.09418, loss=0.08277]

trial_001 train e005:  23%|██████████████████████                                                                        | 35/149 [00:26<01:23,  1.36it/s, avg=0.09418, loss=0.08277]

trial_001 train e005:  23%|██████████████████████                                                                        | 35/149 [00:26<01:23,  1.36it/s, avg=0.09419, loss=0.09432]

trial_001 train e005:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:24,  1.34it/s, avg=0.09419, loss=0.09432]

trial_001 train e005:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:24,  1.34it/s, avg=0.09417, loss=0.09355]

trial_001 train e005:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:25,  1.31it/s, avg=0.09417, loss=0.09355]

trial_001 train e005:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:25,  1.31it/s, avg=0.09441, loss=0.10319]

trial_001 train e005:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:23,  1.33it/s, avg=0.09441, loss=0.10319]

trial_001 train e005:  26%|███████████████████████▉                                                                      | 38/149 [00:29<01:23,  1.33it/s, avg=0.09443, loss=0.09521]

trial_001 train e005:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.31it/s, avg=0.09443, loss=0.09521]

trial_001 train e005:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.31it/s, avg=0.09438, loss=0.09266]

trial_001 train e005:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:23,  1.31it/s, avg=0.09438, loss=0.09266]

trial_001 train e005:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:23,  1.31it/s, avg=0.09459, loss=0.10294]

trial_001 train e005:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:22,  1.31it/s, avg=0.09459, loss=0.10294]

trial_001 train e005:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:22,  1.31it/s, avg=0.09475, loss=0.10108]

trial_001 train e005:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:21,  1.32it/s, avg=0.09475, loss=0.10108]

trial_001 train e005:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:21,  1.32it/s, avg=0.09490, loss=0.10125]

trial_001 train e005:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:18,  1.35it/s, avg=0.09490, loss=0.10125]

trial_001 train e005:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:18,  1.35it/s, avg=0.09493, loss=0.09620]

trial_001 train e005:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:17,  1.35it/s, avg=0.09493, loss=0.09620]

trial_001 train e005:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:17,  1.35it/s, avg=0.09498, loss=0.09751]

trial_001 train e005:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:18,  1.33it/s, avg=0.09498, loss=0.09751]

trial_001 train e005:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:18,  1.33it/s, avg=0.09520, loss=0.10471]

trial_001 train e005:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:17,  1.33it/s, avg=0.09520, loss=0.10471]

trial_001 train e005:  31%|█████████████████████████████                                                                 | 46/149 [00:35<01:17,  1.33it/s, avg=0.09522, loss=0.09641]

trial_001 train e005:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:16,  1.33it/s, avg=0.09522, loss=0.09641]

trial_001 train e005:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:16,  1.33it/s, avg=0.09505, loss=0.08678]

trial_001 train e005:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:16,  1.31it/s, avg=0.09505, loss=0.08678]

trial_001 train e005:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:16,  1.31it/s, avg=0.09501, loss=0.09352]

trial_001 train e005:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:16,  1.31it/s, avg=0.09501, loss=0.09352]

trial_001 train e005:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:16,  1.31it/s, avg=0.09496, loss=0.09217]

trial_001 train e005:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:16,  1.30it/s, avg=0.09496, loss=0.09217]

trial_001 train e005:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:16,  1.30it/s, avg=0.09496, loss=0.09518]

trial_001 train e005:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:15,  1.29it/s, avg=0.09496, loss=0.09518]

trial_001 train e005:  34%|████████████████████████████████▏                                                             | 51/149 [00:39<01:15,  1.29it/s, avg=0.09485, loss=0.08892]

trial_001 train e005:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:15,  1.28it/s, avg=0.09485, loss=0.08892]

trial_001 train e005:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:15,  1.28it/s, avg=0.09467, loss=0.08529]

trial_001 train e005:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:14,  1.30it/s, avg=0.09467, loss=0.08529]

trial_001 train e005:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:14,  1.30it/s, avg=0.09461, loss=0.09143]

trial_001 train e005:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:13,  1.29it/s, avg=0.09461, loss=0.09143]

trial_001 train e005:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:13,  1.29it/s, avg=0.09448, loss=0.08747]

trial_001 train e005:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:12,  1.29it/s, avg=0.09448, loss=0.08747]

trial_001 train e005:  37%|██████████████████████████████████▋                                                           | 55/149 [00:42<01:12,  1.29it/s, avg=0.09443, loss=0.09209]

trial_001 train e005:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:10,  1.32it/s, avg=0.09443, loss=0.09209]

trial_001 train e005:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:10,  1.32it/s, avg=0.09435, loss=0.08987]

trial_001 train e005:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:09,  1.33it/s, avg=0.09435, loss=0.08987]

trial_001 train e005:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:09,  1.33it/s, avg=0.09439, loss=0.09635]

trial_001 train e005:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:09,  1.32it/s, avg=0.09439, loss=0.09635]

trial_001 train e005:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:09,  1.32it/s, avg=0.09431, loss=0.08964]

trial_001 train e005:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:08,  1.32it/s, avg=0.09431, loss=0.08964]

trial_001 train e005:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:45<01:08,  1.32it/s, avg=0.09454, loss=0.10810]

trial_001 train e005:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:08,  1.31it/s, avg=0.09454, loss=0.10810]

trial_001 train e005:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:08,  1.31it/s, avg=0.09489, loss=0.11605]

trial_001 train e005:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:07,  1.31it/s, avg=0.09489, loss=0.11605]

trial_001 train e005:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:07,  1.31it/s, avg=0.09493, loss=0.09724]

trial_001 train e005:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:06,  1.31it/s, avg=0.09493, loss=0.09724]

trial_001 train e005:  42%|███████████████████████████████████████                                                       | 62/149 [00:47<01:06,  1.31it/s, avg=0.09498, loss=0.09810]

trial_001 train e005:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:05,  1.32it/s, avg=0.09498, loss=0.09810]

trial_001 train e005:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:48<01:05,  1.32it/s, avg=0.09501, loss=0.09681]

trial_001 train e005:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:03,  1.34it/s, avg=0.09501, loss=0.09681]

trial_001 train e005:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:03,  1.34it/s, avg=0.09522, loss=0.10892]

trial_001 train e005:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:03,  1.33it/s, avg=0.09522, loss=0.10892]

trial_001 train e005:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:03,  1.33it/s, avg=0.09520, loss=0.09390]

trial_001 train e005:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:03,  1.32it/s, avg=0.09520, loss=0.09390]

trial_001 train e005:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:50<01:03,  1.32it/s, avg=0.09526, loss=0.09943]

trial_001 train e005:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:03,  1.30it/s, avg=0.09526, loss=0.09943]

trial_001 train e005:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:51<01:03,  1.30it/s, avg=0.09516, loss=0.08791]

trial_001 train e005:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:02,  1.31it/s, avg=0.09516, loss=0.08791]

trial_001 train e005:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:02,  1.31it/s, avg=0.09504, loss=0.08716]

trial_001 train e005:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<01:00,  1.32it/s, avg=0.09504, loss=0.08716]

trial_001 train e005:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<01:00,  1.32it/s, avg=0.09483, loss=0.08014]

trial_001 train e005:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:59,  1.32it/s, avg=0.09483, loss=0.08014]

trial_001 train e005:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:53<00:59,  1.32it/s, avg=0.09491, loss=0.10075]

trial_001 train e005:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:57,  1.35it/s, avg=0.09491, loss=0.10075]

trial_001 train e005:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:54<00:57,  1.35it/s, avg=0.09489, loss=0.09357]

trial_001 train e005:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:56,  1.36it/s, avg=0.09489, loss=0.09357]

trial_001 train e005:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:56,  1.36it/s, avg=0.09491, loss=0.09652]

trial_001 train e005:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:56,  1.35it/s, avg=0.09491, loss=0.09652]

trial_001 train e005:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:56,  1.35it/s, avg=0.09496, loss=0.09813]

trial_001 train e005:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:55,  1.36it/s, avg=0.09496, loss=0.09813]

trial_001 train e005:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:56<00:55,  1.36it/s, avg=0.09491, loss=0.09126]

trial_001 train e005:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:54,  1.36it/s, avg=0.09491, loss=0.09126]

trial_001 train e005:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:57<00:54,  1.36it/s, avg=0.09485, loss=0.09041]

trial_001 train e005:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:53,  1.36it/s, avg=0.09485, loss=0.09041]

trial_001 train e005:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:53,  1.36it/s, avg=0.09486, loss=0.09599]

trial_001 train e005:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:53,  1.35it/s, avg=0.09486, loss=0.09599]

trial_001 train e005:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:53,  1.35it/s, avg=0.09477, loss=0.08726]

trial_001 train e005:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:52,  1.34it/s, avg=0.09477, loss=0.08726]

trial_001 train e005:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:59<00:52,  1.34it/s, avg=0.09481, loss=0.09854]

trial_001 train e005:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:52,  1.32it/s, avg=0.09481, loss=0.09854]

trial_001 train e005:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [01:00<00:52,  1.32it/s, avg=0.09484, loss=0.09653]

trial_001 train e005:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:52,  1.32it/s, avg=0.09484, loss=0.09653]

trial_001 train e005:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:52,  1.32it/s, avg=0.09472, loss=0.08544]

trial_001 train e005:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:52,  1.29it/s, avg=0.09472, loss=0.08544]

trial_001 train e005:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:52,  1.29it/s, avg=0.09503, loss=0.12019]

trial_001 train e005:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:49,  1.35it/s, avg=0.09503, loss=0.12019]

trial_001 train e005:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:02<00:49,  1.35it/s, avg=0.09489, loss=0.08332]

trial_001 train e005:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:49,  1.33it/s, avg=0.09489, loss=0.08332]

trial_001 train e005:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:03<00:49,  1.33it/s, avg=0.09490, loss=0.09561]

trial_001 train e005:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.33it/s, avg=0.09490, loss=0.09561]

trial_001 train e005:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.33it/s, avg=0.09475, loss=0.08235]

trial_001 train e005:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:47,  1.34it/s, avg=0.09475, loss=0.08235]

trial_001 train e005:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:47,  1.34it/s, avg=0.09464, loss=0.08507]

trial_001 train e005:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:47,  1.34it/s, avg=0.09464, loss=0.08507]

trial_001 train e005:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:05<00:47,  1.34it/s, avg=0.09463, loss=0.09394]

trial_001 train e005:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:46,  1.33it/s, avg=0.09463, loss=0.09394]

trial_001 train e005:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:06<00:46,  1.33it/s, avg=0.09473, loss=0.10373]

trial_001 train e005:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:46,  1.31it/s, avg=0.09473, loss=0.10373]

trial_001 train e005:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:46,  1.31it/s, avg=0.09474, loss=0.09502]

trial_001 train e005:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:46,  1.30it/s, avg=0.09474, loss=0.09502]

trial_001 train e005:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:46,  1.30it/s, avg=0.09476, loss=0.09662]

trial_001 train e005:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:45,  1.31it/s, avg=0.09476, loss=0.09662]

trial_001 train e005:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:08<00:45,  1.31it/s, avg=0.09469, loss=0.08852]

trial_001 train e005:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:44,  1.31it/s, avg=0.09469, loss=0.08852]

trial_001 train e005:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:09<00:44,  1.31it/s, avg=0.09460, loss=0.08669]

trial_001 train e005:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.32it/s, avg=0.09460, loss=0.08669]

trial_001 train e005:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.32it/s, avg=0.09447, loss=0.08208]

trial_001 train e005:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:42,  1.31it/s, avg=0.09447, loss=0.08208]

trial_001 train e005:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:42,  1.31it/s, avg=0.09440, loss=0.08782]

trial_001 train e005:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:41,  1.34it/s, avg=0.09440, loss=0.08782]

trial_001 train e005:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:11<00:41,  1.34it/s, avg=0.09446, loss=0.10003]

trial_001 train e005:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:40,  1.33it/s, avg=0.09446, loss=0.10003]

trial_001 train e005:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:12<00:40,  1.33it/s, avg=0.09436, loss=0.08534]

trial_001 train e005:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.33it/s, avg=0.09436, loss=0.08534]

trial_001 train e005:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.33it/s, avg=0.09442, loss=0.09992]

trial_001 train e005:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:39,  1.31it/s, avg=0.09442, loss=0.09992]

trial_001 train e005:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:39,  1.31it/s, avg=0.09462, loss=0.11460]

trial_001 train e005:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:39,  1.30it/s, avg=0.09462, loss=0.11460]

trial_001 train e005:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:14<00:39,  1.30it/s, avg=0.09464, loss=0.09663]

trial_001 train e005:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:38,  1.31it/s, avg=0.09464, loss=0.09663]

trial_001 train e005:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:15<00:38,  1.31it/s, avg=0.09464, loss=0.09385]

trial_001 train e005:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:36,  1.33it/s, avg=0.09464, loss=0.09385]

trial_001 train e005:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:16<00:36,  1.33it/s, avg=0.09476, loss=0.10732]

trial_001 train e005:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:36,  1.33it/s, avg=0.09476, loss=0.10732]

trial_001 train e005:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:36,  1.33it/s, avg=0.09467, loss=0.08553]

trial_001 train e005:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:36,  1.30it/s, avg=0.09467, loss=0.08553]

trial_001 train e005:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:17<00:36,  1.30it/s, avg=0.09477, loss=0.10450]

trial_001 train e005:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:35,  1.30it/s, avg=0.09477, loss=0.10450]

trial_001 train e005:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:18<00:35,  1.30it/s, avg=0.09479, loss=0.09702]

trial_001 train e005:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.33it/s, avg=0.09479, loss=0.09702]

trial_001 train e005:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:19<00:33,  1.33it/s, avg=0.09499, loss=0.11542]

trial_001 train e005:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:33,  1.33it/s, avg=0.09499, loss=0.11542]

trial_001 train e005:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:33,  1.33it/s, avg=0.09485, loss=0.08043]

trial_001 train e005:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:32,  1.34it/s, avg=0.09485, loss=0.08043]

trial_001 train e005:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:20<00:32,  1.34it/s, avg=0.09490, loss=0.10055]

trial_001 train e005:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:31,  1.32it/s, avg=0.09490, loss=0.10055]

trial_001 train e005:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:21<00:31,  1.32it/s, avg=0.09478, loss=0.08150]

trial_001 train e005:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:31,  1.32it/s, avg=0.09478, loss=0.08150]

trial_001 train e005:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:22<00:31,  1.32it/s, avg=0.09457, loss=0.07168]

trial_001 train e005:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:30,  1.31it/s, avg=0.09457, loss=0.07168]

trial_001 train e005:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:30,  1.31it/s, avg=0.09455, loss=0.09293]

trial_001 train e005:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:30,  1.30it/s, avg=0.09455, loss=0.09293]

trial_001 train e005:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:23<00:30,  1.30it/s, avg=0.09459, loss=0.09913]

trial_001 train e005:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:29,  1.31it/s, avg=0.09459, loss=0.09913]

trial_001 train e005:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:24<00:29,  1.31it/s, avg=0.09473, loss=0.10972]

trial_001 train e005:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:27,  1.34it/s, avg=0.09473, loss=0.10972]

trial_001 train e005:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:25<00:27,  1.34it/s, avg=0.09484, loss=0.10726]

trial_001 train e005:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:26,  1.34it/s, avg=0.09484, loss=0.10726]

trial_001 train e005:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:26,  1.34it/s, avg=0.09488, loss=0.09913]

trial_001 train e005:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:26,  1.33it/s, avg=0.09488, loss=0.09913]

trial_001 train e005:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:26<00:26,  1.33it/s, avg=0.09496, loss=0.10439]

trial_001 train e005:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.34it/s, avg=0.09496, loss=0.10439]

trial_001 train e005:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:27<00:25,  1.34it/s, avg=0.09502, loss=0.10210]

trial_001 train e005:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.37it/s, avg=0.09502, loss=0.10210]

trial_001 train e005:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:28<00:24,  1.37it/s, avg=0.09492, loss=0.08398]

trial_001 train e005:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:23,  1.35it/s, avg=0.09492, loss=0.08398]

trial_001 train e005:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:23,  1.35it/s, avg=0.09490, loss=0.09149]

trial_001 train e005:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.33it/s, avg=0.09490, loss=0.09149]

trial_001 train e005:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:29<00:23,  1.33it/s, avg=0.09488, loss=0.09313]

trial_001 train e005:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.35it/s, avg=0.09488, loss=0.09313]

trial_001 train e005:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:30<00:22,  1.35it/s, avg=0.09504, loss=0.11401]

trial_001 train e005:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.33it/s, avg=0.09504, loss=0.11401]

trial_001 train e005:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:31<00:21,  1.33it/s, avg=0.09491, loss=0.07872]

trial_001 train e005:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:21,  1.32it/s, avg=0.09491, loss=0.07872]

trial_001 train e005:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:21,  1.32it/s, avg=0.09501, loss=0.10720]

trial_001 train e005:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:20,  1.30it/s, avg=0.09501, loss=0.10720]

trial_001 train e005:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:32<00:20,  1.30it/s, avg=0.09495, loss=0.08819]

trial_001 train e005:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.32it/s, avg=0.09495, loss=0.08819]

trial_001 train e005:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:33<00:19,  1.32it/s, avg=0.09504, loss=0.10561]

trial_001 train e005:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:19,  1.31it/s, avg=0.09504, loss=0.10561]

trial_001 train e005:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:34<00:19,  1.31it/s, avg=0.09499, loss=0.08950]

trial_001 train e005:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:34<00:18,  1.30it/s, avg=0.09499, loss=0.08950]

trial_001 train e005:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:34<00:18,  1.30it/s, avg=0.09505, loss=0.10280]

trial_001 train e005:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:17,  1.32it/s, avg=0.09505, loss=0.10280]

trial_001 train e005:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:35<00:17,  1.32it/s, avg=0.09497, loss=0.08494]

trial_001 train e005:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.31it/s, avg=0.09497, loss=0.08494]

trial_001 train e005:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:36<00:16,  1.31it/s, avg=0.09485, loss=0.07846]

trial_001 train e005:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:16,  1.30it/s, avg=0.09485, loss=0.07846]

trial_001 train e005:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:37<00:16,  1.30it/s, avg=0.09484, loss=0.09411]

trial_001 train e005:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:37<00:15,  1.31it/s, avg=0.09484, loss=0.09411]

trial_001 train e005:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:37<00:15,  1.31it/s, avg=0.09490, loss=0.10212]

trial_001 train e005:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.30it/s, avg=0.09490, loss=0.10212]

trial_001 train e005:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:38<00:14,  1.30it/s, avg=0.09486, loss=0.08980]

trial_001 train e005:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.31it/s, avg=0.09486, loss=0.08980]

trial_001 train e005:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:39<00:13,  1.31it/s, avg=0.09480, loss=0.08664]

trial_001 train e005:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.31it/s, avg=0.09480, loss=0.08664]

trial_001 train e005:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:40<00:12,  1.31it/s, avg=0.09480, loss=0.09601]

trial_001 train e005:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:12,  1.33it/s, avg=0.09480, loss=0.09601]

trial_001 train e005:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:12,  1.33it/s, avg=0.09483, loss=0.09888]

trial_001 train e005:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:11,  1.34it/s, avg=0.09483, loss=0.09888]

trial_001 train e005:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:41<00:11,  1.34it/s, avg=0.09485, loss=0.09667]

trial_001 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.36it/s, avg=0.09485, loss=0.09667]

trial_001 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:42<00:10,  1.36it/s, avg=0.09497, loss=0.11105]

trial_001 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.35it/s, avg=0.09497, loss=0.11105]

trial_001 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:43<00:09,  1.35it/s, avg=0.09503, loss=0.10361]

trial_001 train e005:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:43<00:09,  1.33it/s, avg=0.09503, loss=0.10361]

trial_001 train e005:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:43<00:09,  1.33it/s, avg=0.09509, loss=0.10330]

trial_001 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.34it/s, avg=0.09509, loss=0.10330]

trial_001 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:44<00:08,  1.34it/s, avg=0.09511, loss=0.09847]

trial_001 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.33it/s, avg=0.09511, loss=0.09847]

trial_001 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:45<00:07,  1.33it/s, avg=0.09508, loss=0.09008]

trial_001 train e005:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.33it/s, avg=0.09508, loss=0.09008]

trial_001 train e005:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:46<00:06,  1.33it/s, avg=0.09515, loss=0.10454]

trial_001 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:46<00:05,  1.34it/s, avg=0.09515, loss=0.10454]

trial_001 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:46<00:05,  1.34it/s, avg=0.09516, loss=0.09654]

trial_001 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.35it/s, avg=0.09516, loss=0.09654]

trial_001 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:47<00:05,  1.35it/s, avg=0.09506, loss=0.08157]

trial_001 train e005:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.34it/s, avg=0.09506, loss=0.08157]

trial_001 train e005:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:48<00:04,  1.34it/s, avg=0.09499, loss=0.08545]

trial_001 train e005:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.34it/s, avg=0.09499, loss=0.08545]

trial_001 train e005:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:49<00:03,  1.34it/s, avg=0.09498, loss=0.09315]

trial_001 train e005:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:49<00:02,  1.34it/s, avg=0.09498, loss=0.09315]

trial_001 train e005:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:49<00:02,  1.34it/s, avg=0.09501, loss=0.09991]

trial_001 train e005:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.31it/s, avg=0.09501, loss=0.09991]

trial_001 train e005:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:50<00:02,  1.31it/s, avg=0.09504, loss=0.09943]

trial_001 train e005:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.31it/s, avg=0.09504, loss=0.09943]

trial_001 train e005:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:51<00:01,  1.31it/s, avg=0.09511, loss=0.10437]

trial_001 train e005:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.36it/s, avg=0.09511, loss=0.10437]

trial_001 train e005:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.36it/s, avg=0.09511, loss=0.09574]

trial_001 train e005: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:51<00:00,  1.63it/s, avg=0.09511, loss=0.09574]

trial_001 val e005:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e005:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.32it/s]

trial_001 val e005:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.31it/s]

trial_001 val e005:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.30it/s]

trial_001 val e005:   8%|██████████                                                                                                                   | 4/50 [00:01<00:20,  2.30it/s]

trial_001 val e005:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.30it/s]

trial_001 val e005:  12%|███████████████                                                                                                              | 6/50 [00:02<00:19,  2.30it/s]

trial_001 val e005:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:18,  2.28it/s]

trial_001 val e005:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:18,  2.26it/s]

trial_001 val e005:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:18,  2.26it/s]

trial_001 val e005:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.27it/s]

trial_001 val e005:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:17,  2.27it/s]

trial_001 val e005:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.29it/s]

trial_001 val e005:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:16,  2.29it/s]

trial_001 val e005:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.29it/s]

trial_001 val e005:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.30it/s]

trial_001 val e005:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.30it/s]

trial_001 val e005:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.30it/s]

trial_001 val e005:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.30it/s]

trial_001 val e005:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.30it/s]

trial_001 val e005:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:13,  2.28it/s]

trial_001 val e005:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.26it/s]

trial_001 val e005:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.25it/s]

trial_001 val e005:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:10<00:11,  2.27it/s]

trial_001 val e005:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.28it/s]

trial_001 val e005:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.29it/s]

trial_001 val e005:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.29it/s]

trial_001 val e005:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:10,  2.29it/s]

trial_001 val e005:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.30it/s]

trial_001 val e005:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.30it/s]

trial_001 val e005:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:13<00:08,  2.30it/s]

trial_001 val e005:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.30it/s]

trial_001 val e005:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.31it/s]

trial_001 val e005:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.29it/s]

trial_001 val e005:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:07,  2.27it/s]

trial_001 val e005:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.27it/s]

trial_001 val e005:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.27it/s]

trial_001 val e005:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:16<00:05,  2.27it/s]

trial_001 val e005:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.26it/s]

trial_001 val e005:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:17<00:04,  2.27it/s]

trial_001 val e005:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.28it/s]

trial_001 val e005:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.28it/s]

trial_001 val e005:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.29it/s]

trial_001 val e005:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.29it/s]

trial_001 val e005:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.29it/s]

trial_001 val e005:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.27it/s]

trial_001 val e005:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:20<00:01,  2.27it/s]

trial_001 val e005:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.25it/s]

trial_001 val e005:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:21<00:00,  2.27it/s]

trial_001 val e005:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.28it/s]

trial_001 val e005: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:21<00:00,  2.31it/s]

[2026-05-28 20:14:27] [trial_001] epoch=005 | train_loss=0.095110 | val_MAE=0.098046 | val_S=0.901954 | best_S=0.902019 @epoch=4 | patience=1/5

[trial_001] epochs:   5%|██████                                                                                                                   | 5/100 [11:10<3:32:09, 133.99s/it]

trial_001 train e006:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e006:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08572, loss=0.08572]

trial_001 train e006:   1%|▋                                                                                              | 1/149 [00:00<01:50,  1.33it/s, avg=0.08572, loss=0.08572]

trial_001 train e006:   1%|▋                                                                                              | 1/149 [00:01<01:50,  1.33it/s, avg=0.08717, loss=0.08861]

trial_001 train e006:   1%|█▎                                                                                             | 2/149 [00:01<01:45,  1.39it/s, avg=0.08717, loss=0.08861]

trial_001 train e006:   1%|█▎                                                                                             | 2/149 [00:02<01:45,  1.39it/s, avg=0.09025, loss=0.09642]

trial_001 train e006:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.09025, loss=0.09642]

trial_001 train e006:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.09022, loss=0.09011]

trial_001 train e006:   3%|██▌                                                                                            | 4/149 [00:02<01:46,  1.36it/s, avg=0.09022, loss=0.09011]

trial_001 train e006:   3%|██▌                                                                                            | 4/149 [00:03<01:46,  1.36it/s, avg=0.09036, loss=0.09093]

trial_001 train e006:   3%|███▏                                                                                           | 5/149 [00:03<01:47,  1.34it/s, avg=0.09036, loss=0.09093]

trial_001 train e006:   3%|███▏                                                                                           | 5/149 [00:04<01:47,  1.34it/s, avg=0.08946, loss=0.08496]

trial_001 train e006:   4%|███▊                                                                                           | 6/149 [00:04<01:47,  1.33it/s, avg=0.08946, loss=0.08496]

trial_001 train e006:   4%|███▊                                                                                           | 6/149 [00:05<01:47,  1.33it/s, avg=0.08901, loss=0.08630]

trial_001 train e006:   5%|████▍                                                                                          | 7/149 [00:05<01:46,  1.33it/s, avg=0.08901, loss=0.08630]

trial_001 train e006:   5%|████▍                                                                                          | 7/149 [00:05<01:46,  1.33it/s, avg=0.08951, loss=0.09304]

trial_001 train e006:   5%|█████                                                                                          | 8/149 [00:05<01:44,  1.35it/s, avg=0.08951, loss=0.09304]

trial_001 train e006:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.35it/s, avg=0.09007, loss=0.09451]

trial_001 train e006:   6%|█████▋                                                                                         | 9/149 [00:06<01:44,  1.34it/s, avg=0.09007, loss=0.09451]

trial_001 train e006:   6%|█████▋                                                                                         | 9/149 [00:07<01:44,  1.34it/s, avg=0.09102, loss=0.09965]

trial_001 train e006:   7%|██████▎                                                                                       | 10/149 [00:07<01:43,  1.34it/s, avg=0.09102, loss=0.09965]

trial_001 train e006:   7%|██████▎                                                                                       | 10/149 [00:08<01:43,  1.34it/s, avg=0.09109, loss=0.09174]

trial_001 train e006:   7%|██████▉                                                                                       | 11/149 [00:08<01:44,  1.33it/s, avg=0.09109, loss=0.09174]

trial_001 train e006:   7%|██████▉                                                                                       | 11/149 [00:08<01:44,  1.33it/s, avg=0.09011, loss=0.07933]

trial_001 train e006:   8%|███████▌                                                                                      | 12/149 [00:08<01:44,  1.31it/s, avg=0.09011, loss=0.07933]

trial_001 train e006:   8%|███████▌                                                                                      | 12/149 [00:09<01:44,  1.31it/s, avg=0.09068, loss=0.09755]

trial_001 train e006:   9%|████████▏                                                                                     | 13/149 [00:09<01:43,  1.31it/s, avg=0.09068, loss=0.09755]

trial_001 train e006:   9%|████████▏                                                                                     | 13/149 [00:10<01:43,  1.31it/s, avg=0.09048, loss=0.08786]

trial_001 train e006:   9%|████████▊                                                                                     | 14/149 [00:10<01:43,  1.30it/s, avg=0.09048, loss=0.08786]

trial_001 train e006:   9%|████████▊                                                                                     | 14/149 [00:11<01:43,  1.30it/s, avg=0.09119, loss=0.10111]

trial_001 train e006:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.34it/s, avg=0.09119, loss=0.10111]

trial_001 train e006:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.34it/s, avg=0.09185, loss=0.10179]

trial_001 train e006:  11%|██████████                                                                                    | 16/149 [00:11<01:37,  1.37it/s, avg=0.09185, loss=0.10179]

trial_001 train e006:  11%|██████████                                                                                    | 16/149 [00:12<01:37,  1.37it/s, avg=0.09128, loss=0.08208]

trial_001 train e006:  11%|██████████▋                                                                                   | 17/149 [00:12<01:37,  1.35it/s, avg=0.09128, loss=0.08208]

trial_001 train e006:  11%|██████████▋                                                                                   | 17/149 [00:13<01:37,  1.35it/s, avg=0.09075, loss=0.08174]

trial_001 train e006:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.38it/s, avg=0.09075, loss=0.08174]

trial_001 train e006:  12%|███████████▎                                                                                  | 18/149 [00:14<01:35,  1.38it/s, avg=0.09039, loss=0.08396]

trial_001 train e006:  13%|███████████▉                                                                                  | 19/149 [00:14<01:34,  1.38it/s, avg=0.09039, loss=0.08396]

trial_001 train e006:  13%|███████████▉                                                                                  | 19/149 [00:14<01:34,  1.38it/s, avg=0.09055, loss=0.09360]

trial_001 train e006:  13%|████████████▌                                                                                 | 20/149 [00:14<01:34,  1.37it/s, avg=0.09055, loss=0.09360]

trial_001 train e006:  13%|████████████▌                                                                                 | 20/149 [00:15<01:34,  1.37it/s, avg=0.09161, loss=0.11289]

trial_001 train e006:  14%|█████████████▏                                                                                | 21/149 [00:15<01:31,  1.40it/s, avg=0.09161, loss=0.11289]

trial_001 train e006:  14%|█████████████▏                                                                                | 21/149 [00:16<01:31,  1.40it/s, avg=0.09247, loss=0.11044]

trial_001 train e006:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.40it/s, avg=0.09247, loss=0.11044]

trial_001 train e006:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.40it/s, avg=0.09259, loss=0.09525]

trial_001 train e006:  15%|██████████████▌                                                                               | 23/149 [00:16<01:31,  1.38it/s, avg=0.09259, loss=0.09525]

trial_001 train e006:  15%|██████████████▌                                                                               | 23/149 [00:17<01:31,  1.38it/s, avg=0.09260, loss=0.09285]

trial_001 train e006:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.36it/s, avg=0.09260, loss=0.09285]

trial_001 train e006:  16%|███████████████▏                                                                              | 24/149 [00:18<01:31,  1.36it/s, avg=0.09248, loss=0.08959]

trial_001 train e006:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.36it/s, avg=0.09248, loss=0.08959]

trial_001 train e006:  17%|███████████████▊                                                                              | 25/149 [00:19<01:31,  1.36it/s, avg=0.09205, loss=0.08136]

trial_001 train e006:  17%|████████████████▍                                                                             | 26/149 [00:19<01:31,  1.35it/s, avg=0.09205, loss=0.08136]

trial_001 train e006:  17%|████████████████▍                                                                             | 26/149 [00:19<01:31,  1.35it/s, avg=0.09175, loss=0.08374]

trial_001 train e006:  18%|█████████████████                                                                             | 27/149 [00:19<01:29,  1.36it/s, avg=0.09175, loss=0.08374]

trial_001 train e006:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.36it/s, avg=0.09172, loss=0.09111]

trial_001 train e006:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:29,  1.36it/s, avg=0.09172, loss=0.09111]

trial_001 train e006:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:29,  1.36it/s, avg=0.09225, loss=0.10695]

trial_001 train e006:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.39it/s, avg=0.09225, loss=0.10695]

trial_001 train e006:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:26,  1.39it/s, avg=0.09238, loss=0.09635]

trial_001 train e006:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:26,  1.37it/s, avg=0.09238, loss=0.09635]

trial_001 train e006:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:26,  1.37it/s, avg=0.09198, loss=0.07994]

trial_001 train e006:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:26,  1.36it/s, avg=0.09198, loss=0.07994]

trial_001 train e006:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.36it/s, avg=0.09174, loss=0.08407]

trial_001 train e006:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.35it/s, avg=0.09174, loss=0.08407]

trial_001 train e006:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:26,  1.35it/s, avg=0.09234, loss=0.11159]

trial_001 train e006:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:26,  1.34it/s, avg=0.09234, loss=0.11159]

trial_001 train e006:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:26,  1.34it/s, avg=0.09252, loss=0.09870]

trial_001 train e006:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:27,  1.32it/s, avg=0.09252, loss=0.09870]

trial_001 train e006:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:27,  1.32it/s, avg=0.09233, loss=0.08565]

trial_001 train e006:  23%|██████████████████████                                                                        | 35/149 [00:25<01:27,  1.30it/s, avg=0.09233, loss=0.08565]

trial_001 train e006:  23%|██████████████████████                                                                        | 35/149 [00:26<01:27,  1.30it/s, avg=0.09278, loss=0.10845]

trial_001 train e006:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:26,  1.31it/s, avg=0.09278, loss=0.10845]

trial_001 train e006:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:26,  1.31it/s, avg=0.09277, loss=0.09248]

trial_001 train e006:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:25,  1.31it/s, avg=0.09277, loss=0.09248]

trial_001 train e006:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:25,  1.31it/s, avg=0.09272, loss=0.09100]

trial_001 train e006:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:25,  1.30it/s, avg=0.09272, loss=0.09100]

trial_001 train e006:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:25,  1.30it/s, avg=0.09288, loss=0.09906]

trial_001 train e006:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:21,  1.35it/s, avg=0.09288, loss=0.09906]

trial_001 train e006:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:21,  1.35it/s, avg=0.09286, loss=0.09208]

trial_001 train e006:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:22,  1.33it/s, avg=0.09286, loss=0.09208]

trial_001 train e006:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:22,  1.33it/s, avg=0.09301, loss=0.09902]

trial_001 train e006:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:21,  1.33it/s, avg=0.09301, loss=0.09902]

trial_001 train e006:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:21,  1.33it/s, avg=0.09291, loss=0.08860]

trial_001 train e006:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:21,  1.31it/s, avg=0.09291, loss=0.08860]

trial_001 train e006:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:21,  1.31it/s, avg=0.09295, loss=0.09463]

trial_001 train e006:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:21,  1.30it/s, avg=0.09295, loss=0.09463]

trial_001 train e006:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:21,  1.30it/s, avg=0.09266, loss=0.08021]

trial_001 train e006:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.34it/s, avg=0.09266, loss=0.08021]

trial_001 train e006:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:18,  1.34it/s, avg=0.09262, loss=0.09088]

trial_001 train e006:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:18,  1.32it/s, avg=0.09262, loss=0.09088]

trial_001 train e006:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:18,  1.32it/s, avg=0.09284, loss=0.10275]

trial_001 train e006:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:17,  1.33it/s, avg=0.09284, loss=0.10275]

trial_001 train e006:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:17,  1.33it/s, avg=0.09303, loss=0.10177]

trial_001 train e006:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:16,  1.34it/s, avg=0.09303, loss=0.10177]

trial_001 train e006:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:16,  1.34it/s, avg=0.09310, loss=0.09655]

trial_001 train e006:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:16,  1.32it/s, avg=0.09310, loss=0.09655]

trial_001 train e006:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:16,  1.32it/s, avg=0.09293, loss=0.08471]

trial_001 train e006:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:16,  1.30it/s, avg=0.09293, loss=0.08471]

trial_001 train e006:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:16,  1.30it/s, avg=0.09301, loss=0.09693]

trial_001 train e006:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:16,  1.30it/s, avg=0.09301, loss=0.09693]

trial_001 train e006:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:16,  1.30it/s, avg=0.09309, loss=0.09718]

trial_001 train e006:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:15,  1.31it/s, avg=0.09309, loss=0.09718]

trial_001 train e006:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:15,  1.31it/s, avg=0.09290, loss=0.08303]

trial_001 train e006:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:14,  1.30it/s, avg=0.09290, loss=0.08303]

trial_001 train e006:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:14,  1.30it/s, avg=0.09292, loss=0.09408]

trial_001 train e006:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:14,  1.29it/s, avg=0.09292, loss=0.09408]

trial_001 train e006:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:14,  1.29it/s, avg=0.09300, loss=0.09697]

trial_001 train e006:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:13,  1.29it/s, avg=0.09300, loss=0.09697]

trial_001 train e006:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:13,  1.29it/s, avg=0.09291, loss=0.08834]

trial_001 train e006:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:12,  1.30it/s, avg=0.09291, loss=0.08834]

trial_001 train e006:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:12,  1.30it/s, avg=0.09278, loss=0.08568]

trial_001 train e006:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:09,  1.35it/s, avg=0.09278, loss=0.08568]

trial_001 train e006:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:09,  1.35it/s, avg=0.09265, loss=0.08515]

trial_001 train e006:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.34it/s, avg=0.09265, loss=0.08515]

trial_001 train e006:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:08,  1.34it/s, avg=0.09253, loss=0.08576]

trial_001 train e006:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:08,  1.34it/s, avg=0.09253, loss=0.08576]

trial_001 train e006:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:08,  1.34it/s, avg=0.09242, loss=0.08579]

trial_001 train e006:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:06,  1.35it/s, avg=0.09242, loss=0.08579]

trial_001 train e006:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:06,  1.35it/s, avg=0.09249, loss=0.09701]

trial_001 train e006:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.36it/s, avg=0.09249, loss=0.09701]

trial_001 train e006:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:05,  1.36it/s, avg=0.09235, loss=0.08370]

trial_001 train e006:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:04,  1.36it/s, avg=0.09235, loss=0.08370]

trial_001 train e006:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:04,  1.36it/s, avg=0.09234, loss=0.09150]

trial_001 train e006:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:03,  1.37it/s, avg=0.09234, loss=0.09150]

trial_001 train e006:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:03,  1.37it/s, avg=0.09248, loss=0.10115]

trial_001 train e006:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:02,  1.37it/s, avg=0.09248, loss=0.10115]

trial_001 train e006:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:02,  1.37it/s, avg=0.09262, loss=0.10166]

trial_001 train e006:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:03,  1.34it/s, avg=0.09262, loss=0.10166]

trial_001 train e006:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:03,  1.34it/s, avg=0.09280, loss=0.10465]

trial_001 train e006:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:02,  1.35it/s, avg=0.09280, loss=0.10465]

trial_001 train e006:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:02,  1.35it/s, avg=0.09306, loss=0.10996]

trial_001 train e006:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:01,  1.34it/s, avg=0.09306, loss=0.10996]

trial_001 train e006:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:01,  1.34it/s, avg=0.09306, loss=0.09266]

trial_001 train e006:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:00,  1.35it/s, avg=0.09306, loss=0.09266]

trial_001 train e006:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:00,  1.35it/s, avg=0.09318, loss=0.10142]

trial_001 train e006:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:59,  1.36it/s, avg=0.09318, loss=0.10142]

trial_001 train e006:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<00:59,  1.36it/s, avg=0.09319, loss=0.09412]

trial_001 train e006:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:59,  1.35it/s, avg=0.09319, loss=0.09412]

trial_001 train e006:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<00:59,  1.35it/s, avg=0.09318, loss=0.09207]

trial_001 train e006:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:58,  1.34it/s, avg=0.09318, loss=0.09207]

trial_001 train e006:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:58,  1.34it/s, avg=0.09316, loss=0.09157]

trial_001 train e006:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:58,  1.33it/s, avg=0.09316, loss=0.09157]

trial_001 train e006:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:58,  1.33it/s, avg=0.09297, loss=0.07976]

trial_001 train e006:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:57,  1.33it/s, avg=0.09297, loss=0.07976]

trial_001 train e006:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:57,  1.33it/s, avg=0.09313, loss=0.10474]

trial_001 train e006:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:57,  1.32it/s, avg=0.09313, loss=0.10474]

trial_001 train e006:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:57,  1.32it/s, avg=0.09324, loss=0.10112]

trial_001 train e006:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:56,  1.32it/s, avg=0.09324, loss=0.10112]

trial_001 train e006:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:56<00:56,  1.32it/s, avg=0.09331, loss=0.09824]

trial_001 train e006:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:55,  1.32it/s, avg=0.09331, loss=0.09824]

trial_001 train e006:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:55,  1.32it/s, avg=0.09334, loss=0.09629]

trial_001 train e006:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:54,  1.35it/s, avg=0.09334, loss=0.09629]

trial_001 train e006:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:54,  1.35it/s, avg=0.09325, loss=0.08588]

trial_001 train e006:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:53,  1.34it/s, avg=0.09325, loss=0.08588]

trial_001 train e006:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:53,  1.34it/s, avg=0.09317, loss=0.08752]

trial_001 train e006:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:53,  1.32it/s, avg=0.09317, loss=0.08752]

trial_001 train e006:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:59<00:53,  1.32it/s, avg=0.09316, loss=0.09236]

trial_001 train e006:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:53,  1.31it/s, avg=0.09316, loss=0.09236]

trial_001 train e006:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:53,  1.31it/s, avg=0.09314, loss=0.09114]

trial_001 train e006:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:51,  1.34it/s, avg=0.09314, loss=0.09114]

trial_001 train e006:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:51,  1.34it/s, avg=0.09314, loss=0.09326]

trial_001 train e006:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:50,  1.34it/s, avg=0.09314, loss=0.09326]

trial_001 train e006:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:50,  1.34it/s, avg=0.09331, loss=0.10670]

trial_001 train e006:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:50,  1.32it/s, avg=0.09331, loss=0.10670]

trial_001 train e006:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:02<00:50,  1.32it/s, avg=0.09307, loss=0.07351]

trial_001 train e006:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:50,  1.31it/s, avg=0.09307, loss=0.07351]

trial_001 train e006:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:50,  1.31it/s, avg=0.09308, loss=0.09411]

trial_001 train e006:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:48,  1.34it/s, avg=0.09308, loss=0.09411]

trial_001 train e006:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.34it/s, avg=0.09298, loss=0.08501]

trial_001 train e006:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:47,  1.34it/s, avg=0.09298, loss=0.08501]

trial_001 train e006:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:47,  1.34it/s, avg=0.09314, loss=0.10654]

trial_001 train e006:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:48,  1.29it/s, avg=0.09314, loss=0.10654]

trial_001 train e006:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:05<00:48,  1.29it/s, avg=0.09319, loss=0.09718]

trial_001 train e006:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:47,  1.30it/s, avg=0.09319, loss=0.09718]

trial_001 train e006:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:47,  1.30it/s, avg=0.09336, loss=0.10871]

trial_001 train e006:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:46,  1.32it/s, avg=0.09336, loss=0.10871]

trial_001 train e006:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:46,  1.32it/s, avg=0.09362, loss=0.11645]

trial_001 train e006:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.34it/s, avg=0.09362, loss=0.11645]

trial_001 train e006:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:44,  1.34it/s, avg=0.09347, loss=0.07998]

trial_001 train e006:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:44,  1.34it/s, avg=0.09347, loss=0.07998]

trial_001 train e006:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:08<00:44,  1.34it/s, avg=0.09345, loss=0.09160]

trial_001 train e006:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:43,  1.33it/s, avg=0.09345, loss=0.09160]

trial_001 train e006:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:43,  1.33it/s, avg=0.09342, loss=0.09031]

trial_001 train e006:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:43,  1.32it/s, avg=0.09342, loss=0.09031]

trial_001 train e006:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.32it/s, avg=0.09333, loss=0.08501]

trial_001 train e006:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:41,  1.34it/s, avg=0.09333, loss=0.08501]

trial_001 train e006:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:41,  1.34it/s, avg=0.09338, loss=0.09811]

trial_001 train e006:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:40,  1.35it/s, avg=0.09338, loss=0.09811]

trial_001 train e006:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:11<00:40,  1.35it/s, avg=0.09342, loss=0.09713]

trial_001 train e006:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:39,  1.36it/s, avg=0.09342, loss=0.09713]

trial_001 train e006:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:39,  1.36it/s, avg=0.09332, loss=0.08450]

trial_001 train e006:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:39,  1.35it/s, avg=0.09332, loss=0.08450]

trial_001 train e006:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.35it/s, avg=0.09333, loss=0.09410]

trial_001 train e006:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.34it/s, avg=0.09333, loss=0.09410]

trial_001 train e006:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:38,  1.34it/s, avg=0.09330, loss=0.08985]

trial_001 train e006:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:37,  1.35it/s, avg=0.09330, loss=0.08985]

trial_001 train e006:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:37,  1.35it/s, avg=0.09333, loss=0.09624]

trial_001 train e006:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:35,  1.39it/s, avg=0.09333, loss=0.09624]

trial_001 train e006:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:35,  1.39it/s, avg=0.09350, loss=0.11090]

trial_001 train e006:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:35,  1.38it/s, avg=0.09350, loss=0.11090]

trial_001 train e006:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:35,  1.38it/s, avg=0.09351, loss=0.09455]

trial_001 train e006:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:35,  1.35it/s, avg=0.09351, loss=0.09455]

trial_001 train e006:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:35,  1.35it/s, avg=0.09345, loss=0.08758]

trial_001 train e006:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:34,  1.36it/s, avg=0.09345, loss=0.08758]

trial_001 train e006:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:34,  1.36it/s, avg=0.09345, loss=0.09333]

trial_001 train e006:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:33,  1.36it/s, avg=0.09345, loss=0.09333]

trial_001 train e006:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:33,  1.36it/s, avg=0.09357, loss=0.10532]

trial_001 train e006:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:33,  1.35it/s, avg=0.09357, loss=0.10532]

trial_001 train e006:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.35it/s, avg=0.09353, loss=0.08986]

trial_001 train e006:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:32,  1.36it/s, avg=0.09353, loss=0.08986]

trial_001 train e006:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:32,  1.36it/s, avg=0.09349, loss=0.08867]

trial_001 train e006:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:31,  1.36it/s, avg=0.09349, loss=0.08867]

trial_001 train e006:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:31,  1.36it/s, avg=0.09337, loss=0.08085]

trial_001 train e006:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:31,  1.34it/s, avg=0.09337, loss=0.08085]

trial_001 train e006:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:31,  1.34it/s, avg=0.09342, loss=0.09850]

trial_001 train e006:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:30,  1.33it/s, avg=0.09342, loss=0.09850]

trial_001 train e006:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.33it/s, avg=0.09344, loss=0.09595]

trial_001 train e006:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:29,  1.36it/s, avg=0.09344, loss=0.09595]

trial_001 train e006:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:29,  1.36it/s, avg=0.09355, loss=0.10540]

trial_001 train e006:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:28,  1.37it/s, avg=0.09355, loss=0.10540]

trial_001 train e006:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:28,  1.37it/s, avg=0.09347, loss=0.08511]

trial_001 train e006:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:27,  1.36it/s, avg=0.09347, loss=0.08511]

trial_001 train e006:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:27,  1.36it/s, avg=0.09349, loss=0.09582]

trial_001 train e006:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:27,  1.36it/s, avg=0.09349, loss=0.09582]

trial_001 train e006:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:27,  1.36it/s, avg=0.09347, loss=0.09089]

trial_001 train e006:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:26,  1.35it/s, avg=0.09347, loss=0.09089]

trial_001 train e006:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:26,  1.35it/s, avg=0.09339, loss=0.08459]

trial_001 train e006:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:25,  1.35it/s, avg=0.09339, loss=0.08459]

trial_001 train e006:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:25,  1.35it/s, avg=0.09345, loss=0.09995]

trial_001 train e006:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:25<00:25,  1.34it/s, avg=0.09345, loss=0.09995]

trial_001 train e006:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.34it/s, avg=0.09347, loss=0.09615]

trial_001 train e006:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:26<00:24,  1.34it/s, avg=0.09347, loss=0.09615]

trial_001 train e006:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.34it/s, avg=0.09344, loss=0.08968]

trial_001 train e006:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:24,  1.33it/s, avg=0.09344, loss=0.08968]

trial_001 train e006:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:24,  1.33it/s, avg=0.09333, loss=0.08029]

trial_001 train e006:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.34it/s, avg=0.09333, loss=0.08029]

trial_001 train e006:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.34it/s, avg=0.09333, loss=0.09398]

trial_001 train e006:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:28<00:21,  1.37it/s, avg=0.09333, loss=0.09398]

trial_001 train e006:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:21,  1.37it/s, avg=0.09336, loss=0.09625]

trial_001 train e006:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:29<00:21,  1.37it/s, avg=0.09336, loss=0.09625]

trial_001 train e006:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.37it/s, avg=0.09336, loss=0.09326]

trial_001 train e006:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:20,  1.36it/s, avg=0.09336, loss=0.09326]

trial_001 train e006:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:20,  1.36it/s, avg=0.09331, loss=0.08759]

trial_001 train e006:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:20,  1.34it/s, avg=0.09331, loss=0.08759]

trial_001 train e006:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:20,  1.34it/s, avg=0.09331, loss=0.09338]

trial_001 train e006:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:31<00:19,  1.36it/s, avg=0.09331, loss=0.09338]

trial_001 train e006:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.36it/s, avg=0.09342, loss=0.10698]

trial_001 train e006:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:32<00:18,  1.37it/s, avg=0.09342, loss=0.10698]

trial_001 train e006:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:18,  1.37it/s, avg=0.09338, loss=0.08835]

trial_001 train e006:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.39it/s, avg=0.09338, loss=0.08835]

trial_001 train e006:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.39it/s, avg=0.09347, loss=0.10516]

trial_001 train e006:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:16,  1.37it/s, avg=0.09347, loss=0.10516]

trial_001 train e006:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:16,  1.37it/s, avg=0.09345, loss=0.09076]

trial_001 train e006:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:34<00:16,  1.36it/s, avg=0.09345, loss=0.09076]

trial_001 train e006:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.36it/s, avg=0.09349, loss=0.09817]

trial_001 train e006:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:35<00:15,  1.34it/s, avg=0.09349, loss=0.09817]

trial_001 train e006:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.34it/s, avg=0.09350, loss=0.09428]

trial_001 train e006:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:14,  1.36it/s, avg=0.09350, loss=0.09428]

trial_001 train e006:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:14,  1.36it/s, avg=0.09348, loss=0.09189]

trial_001 train e006:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:13,  1.37it/s, avg=0.09348, loss=0.09189]

trial_001 train e006:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:13,  1.37it/s, avg=0.09347, loss=0.09212]

trial_001 train e006:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:37<00:13,  1.36it/s, avg=0.09347, loss=0.09212]

trial_001 train e006:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.36it/s, avg=0.09344, loss=0.08922]

trial_001 train e006:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:38<00:12,  1.35it/s, avg=0.09344, loss=0.08922]

trial_001 train e006:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.35it/s, avg=0.09350, loss=0.10129]

trial_001 train e006:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:11,  1.37it/s, avg=0.09350, loss=0.10129]

trial_001 train e006:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:11,  1.37it/s, avg=0.09354, loss=0.09829]

trial_001 train e006:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:39<00:11,  1.36it/s, avg=0.09354, loss=0.09829]

trial_001 train e006:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:11,  1.36it/s, avg=0.09347, loss=0.08428]

trial_001 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:40<00:10,  1.35it/s, avg=0.09347, loss=0.08428]

trial_001 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.35it/s, avg=0.09344, loss=0.08982]

trial_001 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:41<00:09,  1.33it/s, avg=0.09344, loss=0.08982]

trial_001 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.33it/s, avg=0.09346, loss=0.09660]

trial_001 train e006:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:09,  1.32it/s, avg=0.09346, loss=0.09660]

trial_001 train e006:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:09,  1.32it/s, avg=0.09357, loss=0.10795]

trial_001 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:42<00:08,  1.31it/s, avg=0.09357, loss=0.10795]

trial_001 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.31it/s, avg=0.09355, loss=0.09100]

trial_001 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:43<00:07,  1.32it/s, avg=0.09355, loss=0.09100]

trial_001 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.32it/s, avg=0.09348, loss=0.08373]

trial_001 train e006:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:44<00:06,  1.33it/s, avg=0.09348, loss=0.08373]

trial_001 train e006:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.33it/s, avg=0.09355, loss=0.10375]

trial_001 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:05,  1.33it/s, avg=0.09355, loss=0.10375]

trial_001 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:05,  1.33it/s, avg=0.09356, loss=0.09407]

trial_001 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:45<00:05,  1.32it/s, avg=0.09356, loss=0.09407]

trial_001 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.32it/s, avg=0.09361, loss=0.10100]

trial_001 train e006:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:46<00:04,  1.32it/s, avg=0.09361, loss=0.10100]

trial_001 train e006:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.32it/s, avg=0.09363, loss=0.09652]

trial_001 train e006:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:47<00:03,  1.33it/s, avg=0.09363, loss=0.09652]

trial_001 train e006:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.33it/s, avg=0.09361, loss=0.09110]

trial_001 train e006:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:02,  1.36it/s, avg=0.09361, loss=0.09110]

trial_001 train e006:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:02,  1.36it/s, avg=0.09368, loss=0.10396]

trial_001 train e006:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:48<00:02,  1.38it/s, avg=0.09368, loss=0.10396]

trial_001 train e006:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.38it/s, avg=0.09365, loss=0.08941]

trial_001 train e006:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:49<00:01,  1.35it/s, avg=0.09365, loss=0.08941]

trial_001 train e006:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.35it/s, avg=0.09364, loss=0.09218]

trial_001 train e006:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:50<00:00,  1.34it/s, avg=0.09364, loss=0.09218]

trial_001 train e006:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:50<00:00,  1.34it/s, avg=0.09366, loss=0.10134]

trial_001 train e006: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:50<00:00,  1.63it/s, avg=0.09366, loss=0.10134]

trial_001 val e006:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e006:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.29it/s]

trial_001 val e006:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.32it/s]

trial_001 val e006:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.32it/s]

trial_001 val e006:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.33it/s]

trial_001 val e006:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.34it/s]

trial_001 val e006:  12%|███████████████                                                                                                              | 6/50 [00:02<00:19,  2.31it/s]

trial_001 val e006:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:18,  2.30it/s]

trial_001 val e006:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:18,  2.30it/s]

trial_001 val e006:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.30it/s]

trial_001 val e006:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.32it/s]

trial_001 val e006:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.33it/s]

trial_001 val e006:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.34it/s]

trial_001 val e006:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.32it/s]

trial_001 val e006:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.32it/s]

trial_001 val e006:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.32it/s]

trial_001 val e006:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.33it/s]

trial_001 val e006:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.33it/s]

trial_001 val e006:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.32it/s]

trial_001 val e006:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.29it/s]

trial_001 val e006:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:13,  2.30it/s]

trial_001 val e006:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.32it/s]

trial_001 val e006:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.33it/s]

trial_001 val e006:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.34it/s]

trial_001 val e006:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.33it/s]

trial_001 val e006:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.33it/s]

trial_001 val e006:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.32it/s]

trial_001 val e006:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.32it/s]

trial_001 val e006:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.32it/s]

trial_001 val e006:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.33it/s]

trial_001 val e006:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.33it/s]

trial_001 val e006:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.32it/s]

trial_001 val e006:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.29it/s]

trial_001 val e006:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.28it/s]

trial_001 val e006:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:07,  2.28it/s]

trial_001 val e006:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.29it/s]

trial_001 val e006:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.30it/s]

trial_001 val e006:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.31it/s]

trial_001 val e006:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.31it/s]

trial_001 val e006:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.32it/s]

trial_001 val e006:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.33it/s]

trial_001 val e006:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.33it/s]

trial_001 val e006:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.31it/s]

trial_001 val e006:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.30it/s]

trial_001 val e006:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.29it/s]

trial_001 val e006:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.31it/s]

trial_001 val e006:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.32it/s]

trial_001 val e006:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.31it/s]

trial_001 val e006:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:20<00:00,  2.31it/s]

trial_001 val e006:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.30it/s]

trial_001 val e006: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:21<00:00,  2.32it/s]

[2026-05-28 20:16:40] [trial_001] epoch=006 | train_loss=0.093664 | val_MAE=0.098989 | val_S=0.901011 | best_S=0.902019 @epoch=4 | patience=2/5

[trial_001] epochs:   6%|███████▎                                                                                                                 | 6/100 [13:22<3:29:01, 133.42s/it]

trial_001 train e007:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e007:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09835, loss=0.09835]

trial_001 train e007:   1%|▋                                                                                              | 1/149 [00:00<01:46,  1.39it/s, avg=0.09835, loss=0.09835]

trial_001 train e007:   1%|▋                                                                                              | 1/149 [00:01<01:46,  1.39it/s, avg=0.10019, loss=0.10203]

trial_001 train e007:   1%|█▎                                                                                             | 2/149 [00:01<01:46,  1.38it/s, avg=0.10019, loss=0.10203]

trial_001 train e007:   1%|█▎                                                                                             | 2/149 [00:02<01:46,  1.38it/s, avg=0.10084, loss=0.10215]

trial_001 train e007:   2%|█▉                                                                                             | 3/149 [00:02<01:48,  1.34it/s, avg=0.10084, loss=0.10215]

trial_001 train e007:   2%|█▉                                                                                             | 3/149 [00:02<01:48,  1.34it/s, avg=0.09833, loss=0.09081]

trial_001 train e007:   3%|██▌                                                                                            | 4/149 [00:02<01:49,  1.33it/s, avg=0.09833, loss=0.09081]

trial_001 train e007:   3%|██▌                                                                                            | 4/149 [00:03<01:49,  1.33it/s, avg=0.09789, loss=0.09611]

trial_001 train e007:   3%|███▏                                                                                           | 5/149 [00:03<01:49,  1.32it/s, avg=0.09789, loss=0.09611]

trial_001 train e007:   3%|███▏                                                                                           | 5/149 [00:04<01:49,  1.32it/s, avg=0.09971, loss=0.10884]

trial_001 train e007:   4%|███▊                                                                                           | 6/149 [00:04<01:48,  1.32it/s, avg=0.09971, loss=0.10884]

trial_001 train e007:   4%|███▊                                                                                           | 6/149 [00:05<01:48,  1.32it/s, avg=0.09958, loss=0.09879]

trial_001 train e007:   5%|████▍                                                                                          | 7/149 [00:05<01:46,  1.33it/s, avg=0.09958, loss=0.09879]

trial_001 train e007:   5%|████▍                                                                                          | 7/149 [00:06<01:46,  1.33it/s, avg=0.09977, loss=0.10112]

trial_001 train e007:   5%|█████                                                                                          | 8/149 [00:06<01:46,  1.32it/s, avg=0.09977, loss=0.10112]

trial_001 train e007:   5%|█████                                                                                          | 8/149 [00:06<01:46,  1.32it/s, avg=0.09821, loss=0.08574]

trial_001 train e007:   6%|█████▋                                                                                         | 9/149 [00:06<01:45,  1.33it/s, avg=0.09821, loss=0.08574]

trial_001 train e007:   6%|█████▋                                                                                         | 9/149 [00:07<01:45,  1.33it/s, avg=0.09821, loss=0.09818]

trial_001 train e007:   7%|██████▎                                                                                       | 10/149 [00:07<01:44,  1.33it/s, avg=0.09821, loss=0.09818]

trial_001 train e007:   7%|██████▎                                                                                       | 10/149 [00:08<01:44,  1.33it/s, avg=0.09674, loss=0.08203]

trial_001 train e007:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.34it/s, avg=0.09674, loss=0.08203]

trial_001 train e007:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.34it/s, avg=0.09599, loss=0.08775]

trial_001 train e007:   8%|███████▌                                                                                      | 12/149 [00:08<01:42,  1.34it/s, avg=0.09599, loss=0.08775]

trial_001 train e007:   8%|███████▌                                                                                      | 12/149 [00:09<01:42,  1.34it/s, avg=0.09572, loss=0.09240]

trial_001 train e007:   9%|████████▏                                                                                     | 13/149 [00:09<01:42,  1.33it/s, avg=0.09572, loss=0.09240]

trial_001 train e007:   9%|████████▏                                                                                     | 13/149 [00:10<01:42,  1.33it/s, avg=0.09562, loss=0.09432]

trial_001 train e007:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.33it/s, avg=0.09562, loss=0.09432]

trial_001 train e007:   9%|████████▊                                                                                     | 14/149 [00:11<01:41,  1.33it/s, avg=0.09422, loss=0.07463]

trial_001 train e007:  10%|█████████▍                                                                                    | 15/149 [00:11<01:41,  1.31it/s, avg=0.09422, loss=0.07463]

trial_001 train e007:  10%|█████████▍                                                                                    | 15/149 [00:12<01:41,  1.31it/s, avg=0.09400, loss=0.09073]

trial_001 train e007:  11%|██████████                                                                                    | 16/149 [00:12<01:40,  1.32it/s, avg=0.09400, loss=0.09073]

trial_001 train e007:  11%|██████████                                                                                    | 16/149 [00:12<01:40,  1.32it/s, avg=0.09371, loss=0.08903]

trial_001 train e007:  11%|██████████▋                                                                                   | 17/149 [00:12<01:40,  1.31it/s, avg=0.09371, loss=0.08903]

trial_001 train e007:  11%|██████████▋                                                                                   | 17/149 [00:13<01:40,  1.31it/s, avg=0.09342, loss=0.08852]

trial_001 train e007:  12%|███████████▎                                                                                  | 18/149 [00:13<01:39,  1.32it/s, avg=0.09342, loss=0.08852]

trial_001 train e007:  12%|███████████▎                                                                                  | 18/149 [00:14<01:39,  1.32it/s, avg=0.09367, loss=0.09824]

trial_001 train e007:  13%|███████████▉                                                                                  | 19/149 [00:14<01:39,  1.31it/s, avg=0.09367, loss=0.09824]

trial_001 train e007:  13%|███████████▉                                                                                  | 19/149 [00:15<01:39,  1.31it/s, avg=0.09388, loss=0.09793]

trial_001 train e007:  13%|████████████▌                                                                                 | 20/149 [00:15<01:37,  1.32it/s, avg=0.09388, loss=0.09793]

trial_001 train e007:  13%|████████████▌                                                                                 | 20/149 [00:15<01:37,  1.32it/s, avg=0.09367, loss=0.08937]

trial_001 train e007:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.32it/s, avg=0.09367, loss=0.08937]

trial_001 train e007:  14%|█████████████▏                                                                                | 21/149 [00:16<01:36,  1.32it/s, avg=0.09359, loss=0.09194]

trial_001 train e007:  15%|█████████████▉                                                                                | 22/149 [00:16<01:35,  1.33it/s, avg=0.09359, loss=0.09194]

trial_001 train e007:  15%|█████████████▉                                                                                | 22/149 [00:17<01:35,  1.33it/s, avg=0.09372, loss=0.09651]

trial_001 train e007:  15%|██████████████▌                                                                               | 23/149 [00:17<01:35,  1.32it/s, avg=0.09372, loss=0.09651]

trial_001 train e007:  15%|██████████████▌                                                                               | 23/149 [00:18<01:35,  1.32it/s, avg=0.09341, loss=0.08635]

trial_001 train e007:  16%|███████████████▏                                                                              | 24/149 [00:18<01:34,  1.33it/s, avg=0.09341, loss=0.08635]

trial_001 train e007:  16%|███████████████▏                                                                              | 24/149 [00:18<01:34,  1.33it/s, avg=0.09394, loss=0.10663]

trial_001 train e007:  17%|███████████████▊                                                                              | 25/149 [00:18<01:32,  1.33it/s, avg=0.09394, loss=0.10663]

trial_001 train e007:  17%|███████████████▊                                                                              | 25/149 [00:19<01:32,  1.33it/s, avg=0.09408, loss=0.09758]

trial_001 train e007:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.36it/s, avg=0.09408, loss=0.09758]

trial_001 train e007:  17%|████████████████▍                                                                             | 26/149 [00:20<01:30,  1.36it/s, avg=0.09379, loss=0.08631]

trial_001 train e007:  18%|█████████████████                                                                             | 27/149 [00:20<01:28,  1.37it/s, avg=0.09379, loss=0.08631]

trial_001 train e007:  18%|█████████████████                                                                             | 27/149 [00:20<01:28,  1.37it/s, avg=0.09364, loss=0.08939]

trial_001 train e007:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.36it/s, avg=0.09364, loss=0.08939]

trial_001 train e007:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:28,  1.36it/s, avg=0.09405, loss=0.10566]

trial_001 train e007:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.39it/s, avg=0.09405, loss=0.10566]

trial_001 train e007:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:26,  1.39it/s, avg=0.09413, loss=0.09644]

trial_001 train e007:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.36it/s, avg=0.09413, loss=0.09644]

trial_001 train e007:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:27,  1.36it/s, avg=0.09464, loss=0.11007]

trial_001 train e007:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.35it/s, avg=0.09464, loss=0.11007]

trial_001 train e007:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.35it/s, avg=0.09447, loss=0.08907]

trial_001 train e007:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:27,  1.34it/s, avg=0.09447, loss=0.08907]

trial_001 train e007:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:27,  1.34it/s, avg=0.09494, loss=0.11000]

trial_001 train e007:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:29,  1.30it/s, avg=0.09494, loss=0.11000]

trial_001 train e007:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:29,  1.30it/s, avg=0.09527, loss=0.10617]

trial_001 train e007:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:28,  1.29it/s, avg=0.09527, loss=0.10617]

trial_001 train e007:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:28,  1.29it/s, avg=0.09508, loss=0.08858]

trial_001 train e007:  23%|██████████████████████                                                                        | 35/149 [00:26<01:26,  1.32it/s, avg=0.09508, loss=0.08858]

trial_001 train e007:  23%|██████████████████████                                                                        | 35/149 [00:27<01:26,  1.32it/s, avg=0.09493, loss=0.08974]

trial_001 train e007:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:24,  1.33it/s, avg=0.09493, loss=0.08974]

trial_001 train e007:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:24,  1.33it/s, avg=0.09468, loss=0.08556]

trial_001 train e007:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:23,  1.34it/s, avg=0.09468, loss=0.08556]

trial_001 train e007:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:23,  1.34it/s, avg=0.09437, loss=0.08308]

trial_001 train e007:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:22,  1.35it/s, avg=0.09437, loss=0.08308]

trial_001 train e007:  26%|███████████████████████▉                                                                      | 38/149 [00:29<01:22,  1.35it/s, avg=0.09432, loss=0.09236]

trial_001 train e007:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.32it/s, avg=0.09432, loss=0.09236]

trial_001 train e007:  26%|████████████████████████▌                                                                     | 39/149 [00:30<01:23,  1.32it/s, avg=0.09409, loss=0.08492]

trial_001 train e007:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:23,  1.31it/s, avg=0.09409, loss=0.08492]

trial_001 train e007:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:23,  1.31it/s, avg=0.09405, loss=0.09267]

trial_001 train e007:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:22,  1.31it/s, avg=0.09405, loss=0.09267]

trial_001 train e007:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:22,  1.31it/s, avg=0.09403, loss=0.09323]

trial_001 train e007:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:21,  1.32it/s, avg=0.09403, loss=0.09323]

trial_001 train e007:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:21,  1.32it/s, avg=0.09391, loss=0.08885]

trial_001 train e007:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:19,  1.33it/s, avg=0.09391, loss=0.08885]

trial_001 train e007:  29%|███████████████████████████▏                                                                  | 43/149 [00:33<01:19,  1.33it/s, avg=0.09394, loss=0.09511]

trial_001 train e007:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:18,  1.34it/s, avg=0.09394, loss=0.09511]

trial_001 train e007:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:18,  1.34it/s, avg=0.09386, loss=0.09041]

trial_001 train e007:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:17,  1.34it/s, avg=0.09386, loss=0.09041]

trial_001 train e007:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:17,  1.34it/s, avg=0.09414, loss=0.10675]

trial_001 train e007:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:16,  1.35it/s, avg=0.09414, loss=0.10675]

trial_001 train e007:  31%|█████████████████████████████                                                                 | 46/149 [00:35<01:16,  1.35it/s, avg=0.09399, loss=0.08692]

trial_001 train e007:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:16,  1.33it/s, avg=0.09399, loss=0.08692]

trial_001 train e007:  32%|█████████████████████████████▋                                                                | 47/149 [00:36<01:16,  1.33it/s, avg=0.09387, loss=0.08840]

trial_001 train e007:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:15,  1.33it/s, avg=0.09387, loss=0.08840]

trial_001 train e007:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:15,  1.33it/s, avg=0.09354, loss=0.07771]

trial_001 train e007:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:15,  1.32it/s, avg=0.09354, loss=0.07771]

trial_001 train e007:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:15,  1.32it/s, avg=0.09331, loss=0.08185]

trial_001 train e007:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:13,  1.35it/s, avg=0.09331, loss=0.08185]

trial_001 train e007:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:13,  1.35it/s, avg=0.09334, loss=0.09526]

trial_001 train e007:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:12,  1.34it/s, avg=0.09334, loss=0.09526]

trial_001 train e007:  34%|████████████████████████████████▏                                                             | 51/149 [00:39<01:12,  1.34it/s, avg=0.09319, loss=0.08555]

trial_001 train e007:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:12,  1.34it/s, avg=0.09319, loss=0.08555]

trial_001 train e007:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:12,  1.34it/s, avg=0.09309, loss=0.08787]

trial_001 train e007:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.36it/s, avg=0.09309, loss=0.08787]

trial_001 train e007:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:10,  1.36it/s, avg=0.09304, loss=0.09008]

trial_001 train e007:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:11,  1.32it/s, avg=0.09304, loss=0.09008]

trial_001 train e007:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:11,  1.32it/s, avg=0.09282, loss=0.08118]

trial_001 train e007:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:11,  1.31it/s, avg=0.09282, loss=0.08118]

trial_001 train e007:  37%|██████████████████████████████████▋                                                           | 55/149 [00:42<01:11,  1.31it/s, avg=0.09263, loss=0.08175]

trial_001 train e007:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:10,  1.32it/s, avg=0.09263, loss=0.08175]

trial_001 train e007:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:10,  1.32it/s, avg=0.09257, loss=0.08932]

trial_001 train e007:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:09,  1.32it/s, avg=0.09257, loss=0.08932]

trial_001 train e007:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:09,  1.32it/s, avg=0.09237, loss=0.08131]

trial_001 train e007:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:09,  1.31it/s, avg=0.09237, loss=0.08131]

trial_001 train e007:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:09,  1.31it/s, avg=0.09250, loss=0.09971]

trial_001 train e007:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:07,  1.33it/s, avg=0.09250, loss=0.09971]

trial_001 train e007:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:45<01:07,  1.33it/s, avg=0.09236, loss=0.08395]

trial_001 train e007:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:06,  1.33it/s, avg=0.09236, loss=0.08395]

trial_001 train e007:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:06,  1.33it/s, avg=0.09239, loss=0.09440]

trial_001 train e007:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:06,  1.32it/s, avg=0.09239, loss=0.09440]

trial_001 train e007:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:06,  1.32it/s, avg=0.09233, loss=0.08863]

trial_001 train e007:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:05,  1.32it/s, avg=0.09233, loss=0.08863]

trial_001 train e007:  42%|███████████████████████████████████████                                                       | 62/149 [00:47<01:05,  1.32it/s, avg=0.09231, loss=0.09139]

trial_001 train e007:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:05,  1.32it/s, avg=0.09231, loss=0.09139]

trial_001 train e007:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:48<01:05,  1.32it/s, avg=0.09226, loss=0.08862]

trial_001 train e007:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:04,  1.32it/s, avg=0.09226, loss=0.08862]

trial_001 train e007:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:04,  1.32it/s, avg=0.09225, loss=0.09193]

trial_001 train e007:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:03,  1.32it/s, avg=0.09225, loss=0.09193]

trial_001 train e007:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:03,  1.32it/s, avg=0.09249, loss=0.10833]

trial_001 train e007:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:01,  1.35it/s, avg=0.09249, loss=0.10833]

trial_001 train e007:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:50<01:01,  1.35it/s, avg=0.09215, loss=0.06918]

trial_001 train e007:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:01,  1.34it/s, avg=0.09215, loss=0.06918]

trial_001 train e007:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:51<01:01,  1.34it/s, avg=0.09201, loss=0.08323]

trial_001 train e007:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:01,  1.31it/s, avg=0.09201, loss=0.08323]

trial_001 train e007:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:01,  1.31it/s, avg=0.09192, loss=0.08574]

trial_001 train e007:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<01:00,  1.32it/s, avg=0.09192, loss=0.08574]

trial_001 train e007:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<01:00,  1.32it/s, avg=0.09189, loss=0.08939]

trial_001 train e007:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<01:00,  1.31it/s, avg=0.09189, loss=0.08939]

trial_001 train e007:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:53<01:00,  1.31it/s, avg=0.09176, loss=0.08306]

trial_001 train e007:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:59,  1.31it/s, avg=0.09176, loss=0.08306]

trial_001 train e007:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:54<00:59,  1.31it/s, avg=0.09160, loss=0.07967]

trial_001 train e007:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:59,  1.30it/s, avg=0.09160, loss=0.07967]

trial_001 train e007:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:59,  1.30it/s, avg=0.09159, loss=0.09105]

trial_001 train e007:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:57,  1.32it/s, avg=0.09159, loss=0.09105]

trial_001 train e007:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:57,  1.32it/s, avg=0.09157, loss=0.09025]

trial_001 train e007:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:56,  1.33it/s, avg=0.09157, loss=0.09025]

trial_001 train e007:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:56<00:56,  1.33it/s, avg=0.09162, loss=0.09557]

trial_001 train e007:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:56,  1.31it/s, avg=0.09162, loss=0.09557]

trial_001 train e007:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:57<00:56,  1.31it/s, avg=0.09158, loss=0.08796]

trial_001 train e007:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:55,  1.31it/s, avg=0.09158, loss=0.08796]

trial_001 train e007:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:55,  1.31it/s, avg=0.09165, loss=0.09737]

trial_001 train e007:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:54,  1.31it/s, avg=0.09165, loss=0.09737]

trial_001 train e007:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:54,  1.31it/s, avg=0.09182, loss=0.10449]

trial_001 train e007:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:53,  1.32it/s, avg=0.09182, loss=0.10449]

trial_001 train e007:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:59<00:53,  1.32it/s, avg=0.09179, loss=0.09020]

trial_001 train e007:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:53,  1.32it/s, avg=0.09179, loss=0.09020]

trial_001 train e007:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [01:00<00:53,  1.32it/s, avg=0.09188, loss=0.09848]

trial_001 train e007:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:52,  1.30it/s, avg=0.09188, loss=0.09848]

trial_001 train e007:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:01<00:52,  1.30it/s, avg=0.09202, loss=0.10300]

trial_001 train e007:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:51,  1.31it/s, avg=0.09202, loss=0.10300]

trial_001 train e007:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:51,  1.31it/s, avg=0.09218, loss=0.10585]

trial_001 train e007:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:50,  1.31it/s, avg=0.09218, loss=0.10585]

trial_001 train e007:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:02<00:50,  1.31it/s, avg=0.09217, loss=0.09088]

trial_001 train e007:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:49,  1.32it/s, avg=0.09217, loss=0.09088]

trial_001 train e007:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:03<00:49,  1.32it/s, avg=0.09202, loss=0.07961]

trial_001 train e007:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:49,  1.31it/s, avg=0.09202, loss=0.07961]

trial_001 train e007:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:04<00:49,  1.31it/s, avg=0.09202, loss=0.09218]

trial_001 train e007:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:47,  1.34it/s, avg=0.09202, loss=0.09218]

trial_001 train e007:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:47,  1.34it/s, avg=0.09194, loss=0.08521]

trial_001 train e007:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:46,  1.36it/s, avg=0.09194, loss=0.08521]

trial_001 train e007:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:05<00:46,  1.36it/s, avg=0.09201, loss=0.09785]

trial_001 train e007:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:44,  1.38it/s, avg=0.09201, loss=0.09785]

trial_001 train e007:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:06<00:44,  1.38it/s, avg=0.09201, loss=0.09192]

trial_001 train e007:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:45,  1.35it/s, avg=0.09201, loss=0.09192]

trial_001 train e007:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:45,  1.35it/s, avg=0.09215, loss=0.10465]

trial_001 train e007:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.35it/s, avg=0.09215, loss=0.10465]

trial_001 train e007:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:44,  1.35it/s, avg=0.09210, loss=0.08738]

trial_001 train e007:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:44,  1.32it/s, avg=0.09210, loss=0.08738]

trial_001 train e007:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:08<00:44,  1.32it/s, avg=0.09215, loss=0.09651]

trial_001 train e007:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:44,  1.31it/s, avg=0.09215, loss=0.09651]

trial_001 train e007:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:09<00:44,  1.31it/s, avg=0.09207, loss=0.08487]

trial_001 train e007:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.30it/s, avg=0.09207, loss=0.08487]

trial_001 train e007:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:10<00:43,  1.30it/s, avg=0.09201, loss=0.08694]

trial_001 train e007:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:43,  1.30it/s, avg=0.09201, loss=0.08694]

trial_001 train e007:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:43,  1.30it/s, avg=0.09203, loss=0.09346]

trial_001 train e007:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:42,  1.31it/s, avg=0.09203, loss=0.09346]

trial_001 train e007:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:11<00:42,  1.31it/s, avg=0.09200, loss=0.08946]

trial_001 train e007:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:41,  1.31it/s, avg=0.09200, loss=0.08946]

trial_001 train e007:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:12<00:41,  1.31it/s, avg=0.09203, loss=0.09508]

trial_001 train e007:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:40,  1.32it/s, avg=0.09203, loss=0.09508]

trial_001 train e007:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:13<00:40,  1.32it/s, avg=0.09210, loss=0.09878]

trial_001 train e007:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:39,  1.32it/s, avg=0.09210, loss=0.09878]

trial_001 train e007:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:39,  1.32it/s, avg=0.09210, loss=0.09156]

trial_001 train e007:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:38,  1.31it/s, avg=0.09210, loss=0.09156]

trial_001 train e007:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:14<00:38,  1.31it/s, avg=0.09215, loss=0.09720]

trial_001 train e007:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:36,  1.37it/s, avg=0.09215, loss=0.09720]

trial_001 train e007:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:15<00:36,  1.37it/s, avg=0.09218, loss=0.09487]

trial_001 train e007:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:35,  1.39it/s, avg=0.09218, loss=0.09487]

trial_001 train e007:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:35,  1.39it/s, avg=0.09198, loss=0.07273]

trial_001 train e007:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:34,  1.39it/s, avg=0.09198, loss=0.07273]

trial_001 train e007:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:34,  1.39it/s, avg=0.09208, loss=0.10186]

trial_001 train e007:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:33,  1.40it/s, avg=0.09208, loss=0.10186]

trial_001 train e007:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:17<00:33,  1.40it/s, avg=0.09224, loss=0.10893]

trial_001 train e007:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:33,  1.38it/s, avg=0.09224, loss=0.10893]

trial_001 train e007:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:18<00:33,  1.38it/s, avg=0.09235, loss=0.10380]

trial_001 train e007:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.35it/s, avg=0.09235, loss=0.10380]

trial_001 train e007:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.35it/s, avg=0.09246, loss=0.10360]

trial_001 train e007:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:32,  1.34it/s, avg=0.09246, loss=0.10360]

trial_001 train e007:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:32,  1.34it/s, avg=0.09245, loss=0.09078]

trial_001 train e007:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:31,  1.35it/s, avg=0.09245, loss=0.09078]

trial_001 train e007:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:20<00:31,  1.35it/s, avg=0.09243, loss=0.09113]

trial_001 train e007:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:31,  1.33it/s, avg=0.09243, loss=0.09113]

trial_001 train e007:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:21<00:31,  1.33it/s, avg=0.09240, loss=0.08851]

trial_001 train e007:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:31,  1.31it/s, avg=0.09240, loss=0.08851]

trial_001 train e007:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:31,  1.31it/s, avg=0.09249, loss=0.10237]

trial_001 train e007:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:30,  1.31it/s, avg=0.09249, loss=0.10237]

trial_001 train e007:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:30,  1.31it/s, avg=0.09246, loss=0.08955]

trial_001 train e007:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:29,  1.30it/s, avg=0.09246, loss=0.08955]

trial_001 train e007:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:23<00:29,  1.30it/s, avg=0.09240, loss=0.08547]

trial_001 train e007:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:29,  1.29it/s, avg=0.09240, loss=0.08547]

trial_001 train e007:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:24<00:29,  1.29it/s, avg=0.09240, loss=0.09229]

trial_001 train e007:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:28,  1.29it/s, avg=0.09240, loss=0.09229]

trial_001 train e007:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:25<00:28,  1.29it/s, avg=0.09239, loss=0.09166]

trial_001 train e007:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:27,  1.31it/s, avg=0.09239, loss=0.09166]

trial_001 train e007:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:27,  1.31it/s, avg=0.09227, loss=0.07817]

trial_001 train e007:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:26,  1.32it/s, avg=0.09227, loss=0.07817]

trial_001 train e007:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:26<00:26,  1.32it/s, avg=0.09232, loss=0.09880]

trial_001 train e007:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.31it/s, avg=0.09232, loss=0.09880]

trial_001 train e007:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:27<00:25,  1.31it/s, avg=0.09238, loss=0.09836]

trial_001 train e007:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.33it/s, avg=0.09238, loss=0.09836]

trial_001 train e007:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:28<00:24,  1.33it/s, avg=0.09249, loss=0.10592]

trial_001 train e007:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:24,  1.31it/s, avg=0.09249, loss=0.10592]

trial_001 train e007:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:24,  1.31it/s, avg=0.09251, loss=0.09417]

trial_001 train e007:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.30it/s, avg=0.09251, loss=0.09417]

trial_001 train e007:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:29<00:23,  1.30it/s, avg=0.09264, loss=0.10882]

trial_001 train e007:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.34it/s, avg=0.09264, loss=0.10882]

trial_001 train e007:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:30<00:22,  1.34it/s, avg=0.09258, loss=0.08488]

trial_001 train e007:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.34it/s, avg=0.09258, loss=0.08488]

trial_001 train e007:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:31<00:21,  1.34it/s, avg=0.09259, loss=0.09420]

trial_001 train e007:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:21,  1.32it/s, avg=0.09259, loss=0.09420]

trial_001 train e007:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:21,  1.32it/s, avg=0.09252, loss=0.08454]

trial_001 train e007:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:20,  1.31it/s, avg=0.09252, loss=0.08454]

trial_001 train e007:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:32<00:20,  1.31it/s, avg=0.09242, loss=0.07982]

trial_001 train e007:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.33it/s, avg=0.09242, loss=0.07982]

trial_001 train e007:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:33<00:19,  1.33it/s, avg=0.09261, loss=0.11550]

trial_001 train e007:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:18,  1.38it/s, avg=0.09261, loss=0.11550]

trial_001 train e007:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:18,  1.38it/s, avg=0.09268, loss=0.10117]

trial_001 train e007:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.38it/s, avg=0.09268, loss=0.10117]

trial_001 train e007:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:34<00:17,  1.38it/s, avg=0.09271, loss=0.09646]

trial_001 train e007:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:16,  1.36it/s, avg=0.09271, loss=0.09646]

trial_001 train e007:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:35<00:16,  1.36it/s, avg=0.09266, loss=0.08731]

trial_001 train e007:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.36it/s, avg=0.09266, loss=0.08731]

trial_001 train e007:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:36<00:16,  1.36it/s, avg=0.09263, loss=0.08828]

trial_001 train e007:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.34it/s, avg=0.09263, loss=0.08828]

trial_001 train e007:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.34it/s, avg=0.09262, loss=0.09132]

trial_001 train e007:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:14,  1.34it/s, avg=0.09262, loss=0.09132]

trial_001 train e007:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:37<00:14,  1.34it/s, avg=0.09275, loss=0.10950]

trial_001 train e007:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.34it/s, avg=0.09275, loss=0.10950]

trial_001 train e007:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:38<00:14,  1.34it/s, avg=0.09271, loss=0.08708]

trial_001 train e007:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.34it/s, avg=0.09271, loss=0.08708]

trial_001 train e007:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:39<00:13,  1.34it/s, avg=0.09273, loss=0.09646]

trial_001 train e007:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.35it/s, avg=0.09273, loss=0.09646]

trial_001 train e007:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.35it/s, avg=0.09281, loss=0.10228]

trial_001 train e007:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:11,  1.35it/s, avg=0.09281, loss=0.10228]

trial_001 train e007:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:11,  1.35it/s, avg=0.09281, loss=0.09287]

trial_001 train e007:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:11,  1.33it/s, avg=0.09281, loss=0.09287]

trial_001 train e007:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:41<00:11,  1.33it/s, avg=0.09268, loss=0.07636]

trial_001 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.31it/s, avg=0.09268, loss=0.07636]

trial_001 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:42<00:10,  1.31it/s, avg=0.09260, loss=0.08147]

trial_001 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.33it/s, avg=0.09260, loss=0.08147]

trial_001 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.33it/s, avg=0.09265, loss=0.09964]

trial_001 train e007:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:08,  1.34it/s, avg=0.09265, loss=0.09964]

trial_001 train e007:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:43<00:08,  1.34it/s, avg=0.09268, loss=0.09628]

trial_001 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.36it/s, avg=0.09268, loss=0.09628]

trial_001 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:44<00:08,  1.36it/s, avg=0.09263, loss=0.08504]

trial_001 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.37it/s, avg=0.09263, loss=0.08504]

trial_001 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:45<00:07,  1.37it/s, avg=0.09263, loss=0.09364]

trial_001 train e007:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.35it/s, avg=0.09263, loss=0.09364]

trial_001 train e007:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.35it/s, avg=0.09269, loss=0.10120]

trial_001 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:05,  1.36it/s, avg=0.09269, loss=0.10120]

trial_001 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:46<00:05,  1.36it/s, avg=0.09269, loss=0.09220]

trial_001 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.36it/s, avg=0.09269, loss=0.09220]

trial_001 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:47<00:05,  1.36it/s, avg=0.09267, loss=0.08945]

trial_001 train e007:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.34it/s, avg=0.09267, loss=0.08945]

trial_001 train e007:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:48<00:04,  1.34it/s, avg=0.09264, loss=0.08888]

trial_001 train e007:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.35it/s, avg=0.09264, loss=0.08888]

trial_001 train e007:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.35it/s, avg=0.09266, loss=0.09559]

trial_001 train e007:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:03,  1.33it/s, avg=0.09266, loss=0.09559]

trial_001 train e007:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:49<00:03,  1.33it/s, avg=0.09265, loss=0.09136]

trial_001 train e007:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.33it/s, avg=0.09265, loss=0.09136]

trial_001 train e007:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:50<00:02,  1.33it/s, avg=0.09262, loss=0.08764]

trial_001 train e007:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.32it/s, avg=0.09262, loss=0.08764]

trial_001 train e007:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:51<00:01,  1.32it/s, avg=0.09267, loss=0.10032]

trial_001 train e007:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.34it/s, avg=0.09267, loss=0.10032]

trial_001 train e007:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.34it/s, avg=0.09270, loss=0.10193]

trial_001 train e007: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:51<00:00,  1.61it/s, avg=0.09270, loss=0.10193]

trial_001 val e007:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e007:   2%|██▌                                                                                                                          | 1/50 [00:00<00:22,  2.22it/s]

trial_001 val e007:   4%|█████                                                                                                                        | 2/50 [00:00<00:21,  2.19it/s]

trial_001 val e007:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.25it/s]

trial_001 val e007:   8%|██████████                                                                                                                   | 4/50 [00:01<00:20,  2.27it/s]

trial_001 val e007:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.29it/s]

trial_001 val e007:  12%|███████████████                                                                                                              | 6/50 [00:02<00:19,  2.30it/s]

trial_001 val e007:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:18,  2.31it/s]

trial_001 val e007:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:18,  2.30it/s]

trial_001 val e007:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.31it/s]

trial_001 val e007:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.30it/s]

trial_001 val e007:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.31it/s]

trial_001 val e007:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.30it/s]

trial_001 val e007:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:16,  2.29it/s]

trial_001 val e007:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.28it/s]

trial_001 val e007:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.30it/s]

trial_001 val e007:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.30it/s]

trial_001 val e007:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.30it/s]

trial_001 val e007:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.31it/s]

trial_001 val e007:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.32it/s]

trial_001 val e007:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.33it/s]

trial_001 val e007:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.31it/s]

trial_001 val e007:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.29it/s]

trial_001 val e007:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:10<00:11,  2.31it/s]

trial_001 val e007:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.30it/s]

trial_001 val e007:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.29it/s]

trial_001 val e007:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.29it/s]

trial_001 val e007:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:10,  2.29it/s]

trial_001 val e007:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.30it/s]

trial_001 val e007:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.32it/s]

trial_001 val e007:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:13<00:08,  2.32it/s]

trial_001 val e007:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.31it/s]

trial_001 val e007:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.32it/s]

trial_001 val e007:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.32it/s]

trial_001 val e007:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.33it/s]

trial_001 val e007:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.32it/s]

trial_001 val e007:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.33it/s]

trial_001 val e007:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:16<00:05,  2.34it/s]

trial_001 val e007:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.32it/s]

trial_001 val e007:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.31it/s]

trial_001 val e007:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.32it/s]

trial_001 val e007:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.30it/s]

trial_001 val e007:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.31it/s]

trial_001 val e007:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.32it/s]

trial_001 val e007:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.32it/s]

trial_001 val e007:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.33it/s]

trial_001 val e007:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.33it/s]

trial_001 val e007:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.33it/s]

trial_001 val e007:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:20<00:00,  2.34it/s]

trial_001 val e007:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.34it/s]

trial_001 val e007: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:21<00:00,  2.35it/s]

[2026-05-28 20:18:53] [trial_001] epoch=007 | train_loss=0.092695 | val_MAE=0.100239 | val_S=0.899761 | best_S=0.902019 @epoch=4 | patience=3/5

[trial_001] epochs:   7%|████████▍                                                                                                                | 7/100 [15:36<3:26:43, 133.37s/it]

trial_001 train e008:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e008:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09132, loss=0.09132]

trial_001 train e008:   1%|▋                                                                                              | 1/149 [00:00<01:46,  1.39it/s, avg=0.09132, loss=0.09132]

trial_001 train e008:   1%|▋                                                                                              | 1/149 [00:01<01:46,  1.39it/s, avg=0.09090, loss=0.09049]

trial_001 train e008:   1%|█▎                                                                                             | 2/149 [00:01<01:52,  1.31it/s, avg=0.09090, loss=0.09049]

trial_001 train e008:   1%|█▎                                                                                             | 2/149 [00:02<01:52,  1.31it/s, avg=0.08974, loss=0.08742]

trial_001 train e008:   2%|█▉                                                                                             | 3/149 [00:02<01:51,  1.31it/s, avg=0.08974, loss=0.08742]

trial_001 train e008:   2%|█▉                                                                                             | 3/149 [00:03<01:51,  1.31it/s, avg=0.08857, loss=0.08505]

trial_001 train e008:   3%|██▌                                                                                            | 4/149 [00:03<01:48,  1.34it/s, avg=0.08857, loss=0.08505]

trial_001 train e008:   3%|██▌                                                                                            | 4/149 [00:03<01:48,  1.34it/s, avg=0.08986, loss=0.09503]

trial_001 train e008:   3%|███▏                                                                                           | 5/149 [00:03<01:48,  1.32it/s, avg=0.08986, loss=0.09503]

trial_001 train e008:   3%|███▏                                                                                           | 5/149 [00:04<01:48,  1.32it/s, avg=0.08899, loss=0.08464]

trial_001 train e008:   4%|███▊                                                                                           | 6/149 [00:04<01:48,  1.31it/s, avg=0.08899, loss=0.08464]

trial_001 train e008:   4%|███▊                                                                                           | 6/149 [00:05<01:48,  1.31it/s, avg=0.08991, loss=0.09542]

trial_001 train e008:   5%|████▍                                                                                          | 7/149 [00:05<01:47,  1.32it/s, avg=0.08991, loss=0.09542]

trial_001 train e008:   5%|████▍                                                                                          | 7/149 [00:06<01:47,  1.32it/s, avg=0.08954, loss=0.08696]

trial_001 train e008:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.35it/s, avg=0.08954, loss=0.08696]

trial_001 train e008:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.35it/s, avg=0.09095, loss=0.10226]

trial_001 train e008:   6%|█████▋                                                                                         | 9/149 [00:06<01:45,  1.33it/s, avg=0.09095, loss=0.10226]

trial_001 train e008:   6%|█████▋                                                                                         | 9/149 [00:07<01:45,  1.33it/s, avg=0.09106, loss=0.09206]

trial_001 train e008:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.36it/s, avg=0.09106, loss=0.09206]

trial_001 train e008:   7%|██████▎                                                                                       | 10/149 [00:08<01:42,  1.36it/s, avg=0.09043, loss=0.08412]

trial_001 train e008:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.35it/s, avg=0.09043, loss=0.08412]

trial_001 train e008:   7%|██████▉                                                                                       | 11/149 [00:09<01:42,  1.35it/s, avg=0.09075, loss=0.09419]

trial_001 train e008:   8%|███████▌                                                                                      | 12/149 [00:09<01:42,  1.33it/s, avg=0.09075, loss=0.09419]

trial_001 train e008:   8%|███████▌                                                                                      | 12/149 [00:09<01:42,  1.33it/s, avg=0.09156, loss=0.10136]

trial_001 train e008:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.36it/s, avg=0.09156, loss=0.10136]

trial_001 train e008:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.36it/s, avg=0.09260, loss=0.10603]

trial_001 train e008:   9%|████████▊                                                                                     | 14/149 [00:10<01:37,  1.38it/s, avg=0.09260, loss=0.10603]

trial_001 train e008:   9%|████████▊                                                                                     | 14/149 [00:11<01:37,  1.38it/s, avg=0.09248, loss=0.09085]

trial_001 train e008:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.35it/s, avg=0.09248, loss=0.09085]

trial_001 train e008:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.35it/s, avg=0.09267, loss=0.09559]

trial_001 train e008:  11%|██████████                                                                                    | 16/149 [00:11<01:39,  1.34it/s, avg=0.09267, loss=0.09559]

trial_001 train e008:  11%|██████████                                                                                    | 16/149 [00:12<01:39,  1.34it/s, avg=0.09317, loss=0.10118]

trial_001 train e008:  11%|██████████▋                                                                                   | 17/149 [00:12<01:39,  1.32it/s, avg=0.09317, loss=0.10118]

trial_001 train e008:  11%|██████████▋                                                                                   | 17/149 [00:13<01:39,  1.32it/s, avg=0.09362, loss=0.10113]

trial_001 train e008:  12%|███████████▎                                                                                  | 18/149 [00:13<01:38,  1.34it/s, avg=0.09362, loss=0.10113]

trial_001 train e008:  12%|███████████▎                                                                                  | 18/149 [00:14<01:38,  1.34it/s, avg=0.09417, loss=0.10412]

trial_001 train e008:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.36it/s, avg=0.09417, loss=0.10412]

trial_001 train e008:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.36it/s, avg=0.09438, loss=0.09832]

trial_001 train e008:  13%|████████████▌                                                                                 | 20/149 [00:14<01:36,  1.34it/s, avg=0.09438, loss=0.09832]

trial_001 train e008:  13%|████████████▌                                                                                 | 20/149 [00:15<01:36,  1.34it/s, avg=0.09476, loss=0.10239]

trial_001 train e008:  14%|█████████████▏                                                                                | 21/149 [00:15<01:34,  1.35it/s, avg=0.09476, loss=0.10239]

trial_001 train e008:  14%|█████████████▏                                                                                | 21/149 [00:16<01:34,  1.35it/s, avg=0.09404, loss=0.07902]

trial_001 train e008:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.35it/s, avg=0.09404, loss=0.07902]

trial_001 train e008:  15%|█████████████▉                                                                                | 22/149 [00:17<01:34,  1.35it/s, avg=0.09414, loss=0.09619]

trial_001 train e008:  15%|██████████████▌                                                                               | 23/149 [00:17<01:32,  1.36it/s, avg=0.09414, loss=0.09619]

trial_001 train e008:  15%|██████████████▌                                                                               | 23/149 [00:17<01:32,  1.36it/s, avg=0.09381, loss=0.08637]

trial_001 train e008:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.37it/s, avg=0.09381, loss=0.08637]

trial_001 train e008:  16%|███████████████▏                                                                              | 24/149 [00:18<01:31,  1.37it/s, avg=0.09354, loss=0.08694]

trial_001 train e008:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.09354, loss=0.08694]

trial_001 train e008:  17%|███████████████▊                                                                              | 25/149 [00:19<01:30,  1.37it/s, avg=0.09416, loss=0.10983]

trial_001 train e008:  17%|████████████████▍                                                                             | 26/149 [00:19<01:29,  1.37it/s, avg=0.09416, loss=0.10983]

trial_001 train e008:  17%|████████████████▍                                                                             | 26/149 [00:19<01:29,  1.37it/s, avg=0.09373, loss=0.08249]

trial_001 train e008:  18%|█████████████████                                                                             | 27/149 [00:19<01:27,  1.39it/s, avg=0.09373, loss=0.08249]

trial_001 train e008:  18%|█████████████████                                                                             | 27/149 [00:20<01:27,  1.39it/s, avg=0.09338, loss=0.08379]

trial_001 train e008:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:29,  1.35it/s, avg=0.09338, loss=0.08379]

trial_001 train e008:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:29,  1.35it/s, avg=0.09319, loss=0.08799]

trial_001 train e008:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:29,  1.34it/s, avg=0.09319, loss=0.08799]

trial_001 train e008:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:29,  1.34it/s, avg=0.09284, loss=0.08257]

trial_001 train e008:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:30,  1.31it/s, avg=0.09284, loss=0.08257]

trial_001 train e008:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:30,  1.31it/s, avg=0.09274, loss=0.08991]

trial_001 train e008:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:31,  1.29it/s, avg=0.09274, loss=0.08991]

trial_001 train e008:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:31,  1.29it/s, avg=0.09299, loss=0.10061]

trial_001 train e008:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:29,  1.30it/s, avg=0.09299, loss=0.10061]

trial_001 train e008:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:29,  1.30it/s, avg=0.09315, loss=0.09817]

trial_001 train e008:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:27,  1.32it/s, avg=0.09315, loss=0.09817]

trial_001 train e008:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:27,  1.32it/s, avg=0.09260, loss=0.07475]

trial_001 train e008:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:27,  1.32it/s, avg=0.09260, loss=0.07475]

trial_001 train e008:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:27,  1.32it/s, avg=0.09222, loss=0.07933]

trial_001 train e008:  23%|██████████████████████                                                                        | 35/149 [00:26<01:27,  1.30it/s, avg=0.09222, loss=0.07933]

trial_001 train e008:  23%|██████████████████████                                                                        | 35/149 [00:26<01:27,  1.30it/s, avg=0.09197, loss=0.08294]

trial_001 train e008:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:24,  1.33it/s, avg=0.09197, loss=0.08294]

trial_001 train e008:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:24,  1.33it/s, avg=0.09163, loss=0.07954]

trial_001 train e008:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:23,  1.34it/s, avg=0.09163, loss=0.07954]

trial_001 train e008:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:23,  1.34it/s, avg=0.09146, loss=0.08530]

trial_001 train e008:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:24,  1.31it/s, avg=0.09146, loss=0.08530]

trial_001 train e008:  26%|███████████████████████▉                                                                      | 38/149 [00:29<01:24,  1.31it/s, avg=0.09195, loss=0.11055]

trial_001 train e008:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.32it/s, avg=0.09195, loss=0.11055]

trial_001 train e008:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.32it/s, avg=0.09179, loss=0.08533]

trial_001 train e008:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:22,  1.33it/s, avg=0.09179, loss=0.08533]

trial_001 train e008:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:22,  1.33it/s, avg=0.09212, loss=0.10521]

trial_001 train e008:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.39it/s, avg=0.09212, loss=0.10521]

trial_001 train e008:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:17,  1.39it/s, avg=0.09232, loss=0.10084]

trial_001 train e008:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:17,  1.38it/s, avg=0.09232, loss=0.10084]

trial_001 train e008:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:17,  1.38it/s, avg=0.09226, loss=0.08962]

trial_001 train e008:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:17,  1.37it/s, avg=0.09226, loss=0.08962]

trial_001 train e008:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:17,  1.37it/s, avg=0.09230, loss=0.09388]

trial_001 train e008:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:17,  1.36it/s, avg=0.09230, loss=0.09388]

trial_001 train e008:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:17,  1.36it/s, avg=0.09245, loss=0.09919]

trial_001 train e008:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:18,  1.32it/s, avg=0.09245, loss=0.09919]

trial_001 train e008:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:18,  1.32it/s, avg=0.09221, loss=0.08146]

trial_001 train e008:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:17,  1.33it/s, avg=0.09221, loss=0.08146]

trial_001 train e008:  31%|█████████████████████████████                                                                 | 46/149 [00:35<01:17,  1.33it/s, avg=0.09200, loss=0.08211]

trial_001 train e008:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:16,  1.34it/s, avg=0.09200, loss=0.08211]

trial_001 train e008:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:16,  1.34it/s, avg=0.09207, loss=0.09567]

trial_001 train e008:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:15,  1.34it/s, avg=0.09207, loss=0.09567]

trial_001 train e008:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:15,  1.34it/s, avg=0.09219, loss=0.09762]

trial_001 train e008:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:14,  1.34it/s, avg=0.09219, loss=0.09762]

trial_001 train e008:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:14,  1.34it/s, avg=0.09213, loss=0.08916]

trial_001 train e008:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:14,  1.33it/s, avg=0.09213, loss=0.08916]

trial_001 train e008:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:14,  1.33it/s, avg=0.09204, loss=0.08801]

trial_001 train e008:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:12,  1.34it/s, avg=0.09204, loss=0.08801]

trial_001 train e008:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:12,  1.34it/s, avg=0.09196, loss=0.08738]

trial_001 train e008:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:12,  1.33it/s, avg=0.09196, loss=0.08738]

trial_001 train e008:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:12,  1.33it/s, avg=0.09181, loss=0.08420]

trial_001 train e008:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:12,  1.32it/s, avg=0.09181, loss=0.08420]

trial_001 train e008:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:12,  1.32it/s, avg=0.09196, loss=0.10016]

trial_001 train e008:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:11,  1.33it/s, avg=0.09196, loss=0.10016]

trial_001 train e008:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:11,  1.33it/s, avg=0.09179, loss=0.08262]

trial_001 train e008:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:09,  1.34it/s, avg=0.09179, loss=0.08262]

trial_001 train e008:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:09,  1.34it/s, avg=0.09156, loss=0.07887]

trial_001 train e008:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:08,  1.36it/s, avg=0.09156, loss=0.07887]

trial_001 train e008:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:08,  1.36it/s, avg=0.09141, loss=0.08291]

trial_001 train e008:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.34it/s, avg=0.09141, loss=0.08291]

trial_001 train e008:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:08,  1.34it/s, avg=0.09137, loss=0.08900]

trial_001 train e008:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:08,  1.32it/s, avg=0.09137, loss=0.08900]

trial_001 train e008:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:08,  1.32it/s, avg=0.09115, loss=0.07848]

trial_001 train e008:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:08,  1.31it/s, avg=0.09115, loss=0.07848]

trial_001 train e008:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:08,  1.31it/s, avg=0.09129, loss=0.09929]

trial_001 train e008:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:07,  1.33it/s, avg=0.09129, loss=0.09929]

trial_001 train e008:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:07,  1.33it/s, avg=0.09110, loss=0.07989]

trial_001 train e008:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:04,  1.37it/s, avg=0.09110, loss=0.07989]

trial_001 train e008:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:04,  1.37it/s, avg=0.09096, loss=0.08235]

trial_001 train e008:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:03,  1.38it/s, avg=0.09096, loss=0.08235]

trial_001 train e008:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:03,  1.38it/s, avg=0.09108, loss=0.09861]

trial_001 train e008:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.38it/s, avg=0.09108, loss=0.09861]

trial_001 train e008:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:02,  1.38it/s, avg=0.09112, loss=0.09357]

trial_001 train e008:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:01,  1.37it/s, avg=0.09112, loss=0.09357]

trial_001 train e008:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:01,  1.37it/s, avg=0.09130, loss=0.10277]

trial_001 train e008:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.37it/s, avg=0.09130, loss=0.10277]

trial_001 train e008:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:01,  1.37it/s, avg=0.09138, loss=0.09644]

trial_001 train e008:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:01,  1.36it/s, avg=0.09138, loss=0.09644]

trial_001 train e008:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:01,  1.36it/s, avg=0.09141, loss=0.09331]

trial_001 train e008:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:00,  1.35it/s, avg=0.09141, loss=0.09331]

trial_001 train e008:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:00,  1.35it/s, avg=0.09141, loss=0.09180]

trial_001 train e008:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<01:00,  1.35it/s, avg=0.09141, loss=0.09180]

trial_001 train e008:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:00,  1.35it/s, avg=0.09144, loss=0.09372]

trial_001 train e008:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.36it/s, avg=0.09144, loss=0.09372]

trial_001 train e008:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<00:58,  1.36it/s, avg=0.09145, loss=0.09191]

trial_001 train e008:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:58,  1.35it/s, avg=0.09145, loss=0.09191]

trial_001 train e008:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:58,  1.35it/s, avg=0.09149, loss=0.09456]

trial_001 train e008:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.35it/s, avg=0.09149, loss=0.09456]

trial_001 train e008:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:57,  1.35it/s, avg=0.09146, loss=0.08867]

trial_001 train e008:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:55,  1.38it/s, avg=0.09146, loss=0.08867]

trial_001 train e008:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:55,  1.38it/s, avg=0.09145, loss=0.09102]

trial_001 train e008:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:55,  1.37it/s, avg=0.09145, loss=0.09102]

trial_001 train e008:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:55,  1.37it/s, avg=0.09124, loss=0.07568]

trial_001 train e008:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:55,  1.34it/s, avg=0.09124, loss=0.07568]

trial_001 train e008:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:55,  1.34it/s, avg=0.09108, loss=0.07946]

trial_001 train e008:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:55,  1.33it/s, avg=0.09108, loss=0.07946]

trial_001 train e008:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:55,  1.33it/s, avg=0.09104, loss=0.08805]

trial_001 train e008:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:54,  1.33it/s, avg=0.09104, loss=0.08805]

trial_001 train e008:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:54,  1.33it/s, avg=0.09103, loss=0.09022]

trial_001 train e008:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:53,  1.34it/s, avg=0.09103, loss=0.09022]

trial_001 train e008:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:53,  1.34it/s, avg=0.09095, loss=0.08494]

trial_001 train e008:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:53,  1.33it/s, avg=0.09095, loss=0.08494]

trial_001 train e008:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:53,  1.33it/s, avg=0.09116, loss=0.10761]

trial_001 train e008:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:52,  1.33it/s, avg=0.09116, loss=0.10761]

trial_001 train e008:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:52,  1.33it/s, avg=0.09113, loss=0.08850]

trial_001 train e008:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:52,  1.32it/s, avg=0.09113, loss=0.08850]

trial_001 train e008:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:52,  1.32it/s, avg=0.09124, loss=0.09978]

trial_001 train e008:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:51,  1.32it/s, avg=0.09124, loss=0.09978]

trial_001 train e008:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:51,  1.32it/s, avg=0.09112, loss=0.08184]

trial_001 train e008:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:51,  1.31it/s, avg=0.09112, loss=0.08184]

trial_001 train e008:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:51,  1.31it/s, avg=0.09111, loss=0.09033]

trial_001 train e008:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:50,  1.31it/s, avg=0.09111, loss=0.09033]

trial_001 train e008:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:50,  1.31it/s, avg=0.09130, loss=0.10690]

trial_001 train e008:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:48,  1.34it/s, avg=0.09130, loss=0.10690]

trial_001 train e008:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:48,  1.34it/s, avg=0.09140, loss=0.09997]

trial_001 train e008:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:47,  1.36it/s, avg=0.09140, loss=0.09997]

trial_001 train e008:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:47,  1.36it/s, avg=0.09143, loss=0.09374]

trial_001 train e008:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:46,  1.36it/s, avg=0.09143, loss=0.09374]

trial_001 train e008:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:46,  1.36it/s, avg=0.09140, loss=0.08856]

trial_001 train e008:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:45,  1.35it/s, avg=0.09140, loss=0.08856]

trial_001 train e008:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:45,  1.35it/s, avg=0.09145, loss=0.09624]

trial_001 train e008:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:44,  1.38it/s, avg=0.09145, loss=0.09624]

trial_001 train e008:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:44,  1.38it/s, avg=0.09163, loss=0.10785]

trial_001 train e008:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.36it/s, avg=0.09163, loss=0.10785]

trial_001 train e008:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:44,  1.36it/s, avg=0.09158, loss=0.08657]

trial_001 train e008:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:44,  1.33it/s, avg=0.09158, loss=0.08657]

trial_001 train e008:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:44,  1.33it/s, avg=0.09160, loss=0.09328]

trial_001 train e008:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.35it/s, avg=0.09160, loss=0.09328]

trial_001 train e008:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:42,  1.35it/s, avg=0.09149, loss=0.08149]

trial_001 train e008:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:42,  1.33it/s, avg=0.09149, loss=0.08149]

trial_001 train e008:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:42,  1.33it/s, avg=0.09151, loss=0.09357]

trial_001 train e008:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:41,  1.36it/s, avg=0.09151, loss=0.09357]

trial_001 train e008:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:41,  1.36it/s, avg=0.09137, loss=0.07809]

trial_001 train e008:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:41,  1.34it/s, avg=0.09137, loss=0.07809]

trial_001 train e008:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:41,  1.34it/s, avg=0.09135, loss=0.09003]

trial_001 train e008:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:40,  1.34it/s, avg=0.09135, loss=0.09003]

trial_001 train e008:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:40,  1.34it/s, avg=0.09147, loss=0.10276]

trial_001 train e008:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:40,  1.32it/s, avg=0.09147, loss=0.10276]

trial_001 train e008:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:40,  1.32it/s, avg=0.09153, loss=0.09666]

trial_001 train e008:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:39,  1.31it/s, avg=0.09153, loss=0.09666]

trial_001 train e008:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:39,  1.31it/s, avg=0.09154, loss=0.09271]

trial_001 train e008:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:38,  1.33it/s, avg=0.09154, loss=0.09271]

trial_001 train e008:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:38,  1.33it/s, avg=0.09155, loss=0.09275]

trial_001 train e008:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:38,  1.31it/s, avg=0.09155, loss=0.09275]

trial_001 train e008:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:38,  1.31it/s, avg=0.09146, loss=0.08234]

trial_001 train e008:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:37,  1.30it/s, avg=0.09146, loss=0.08234]

trial_001 train e008:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:37,  1.30it/s, avg=0.09152, loss=0.09743]

trial_001 train e008:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:36,  1.31it/s, avg=0.09152, loss=0.09743]

trial_001 train e008:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:36,  1.31it/s, avg=0.09152, loss=0.09161]

trial_001 train e008:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:35,  1.33it/s, avg=0.09152, loss=0.09161]

trial_001 train e008:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:35,  1.33it/s, avg=0.09150, loss=0.09003]

trial_001 train e008:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:34,  1.33it/s, avg=0.09150, loss=0.09003]

trial_001 train e008:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:34,  1.33it/s, avg=0.09151, loss=0.09204]

trial_001 train e008:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:34,  1.31it/s, avg=0.09151, loss=0.09204]

trial_001 train e008:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:34,  1.31it/s, avg=0.09142, loss=0.08190]

trial_001 train e008:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:33,  1.30it/s, avg=0.09142, loss=0.08190]

trial_001 train e008:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:33,  1.30it/s, avg=0.09147, loss=0.09691]

trial_001 train e008:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:33,  1.30it/s, avg=0.09147, loss=0.09691]

trial_001 train e008:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:33,  1.30it/s, avg=0.09147, loss=0.09168]

trial_001 train e008:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:32,  1.30it/s, avg=0.09147, loss=0.09168]

trial_001 train e008:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:32,  1.30it/s, avg=0.09149, loss=0.09373]

trial_001 train e008:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:31,  1.31it/s, avg=0.09149, loss=0.09373]

trial_001 train e008:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:31,  1.31it/s, avg=0.09147, loss=0.08920]

trial_001 train e008:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:30,  1.31it/s, avg=0.09147, loss=0.08920]

trial_001 train e008:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:30,  1.31it/s, avg=0.09150, loss=0.09469]

trial_001 train e008:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:29,  1.30it/s, avg=0.09150, loss=0.09469]

trial_001 train e008:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:23<00:29,  1.30it/s, avg=0.09150, loss=0.09166]

trial_001 train e008:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:29,  1.29it/s, avg=0.09150, loss=0.09166]

trial_001 train e008:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:29,  1.29it/s, avg=0.09155, loss=0.09731]

trial_001 train e008:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:28,  1.29it/s, avg=0.09155, loss=0.09731]

trial_001 train e008:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:28,  1.29it/s, avg=0.09160, loss=0.09665]

trial_001 train e008:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:27,  1.31it/s, avg=0.09160, loss=0.09665]

trial_001 train e008:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:27,  1.31it/s, avg=0.09162, loss=0.09371]

trial_001 train e008:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:26,  1.31it/s, avg=0.09162, loss=0.09371]

trial_001 train e008:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:26<00:26,  1.31it/s, avg=0.09169, loss=0.10004]

trial_001 train e008:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.33it/s, avg=0.09169, loss=0.10004]

trial_001 train e008:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.33it/s, avg=0.09173, loss=0.09689]

trial_001 train e008:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:26<00:24,  1.35it/s, avg=0.09173, loss=0.09689]

trial_001 train e008:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:24,  1.35it/s, avg=0.09170, loss=0.08806]

trial_001 train e008:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:24,  1.33it/s, avg=0.09170, loss=0.08806]

trial_001 train e008:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:24,  1.33it/s, avg=0.09170, loss=0.09164]

trial_001 train e008:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.32it/s, avg=0.09170, loss=0.09164]

trial_001 train e008:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:29<00:23,  1.32it/s, avg=0.09169, loss=0.08998]

trial_001 train e008:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.31it/s, avg=0.09169, loss=0.08998]

trial_001 train e008:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.31it/s, avg=0.09170, loss=0.09333]

trial_001 train e008:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:29<00:21,  1.33it/s, avg=0.09170, loss=0.09333]

trial_001 train e008:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.33it/s, avg=0.09183, loss=0.10678]

trial_001 train e008:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:20,  1.38it/s, avg=0.09183, loss=0.10678]

trial_001 train e008:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:20,  1.38it/s, avg=0.09183, loss=0.09210]

trial_001 train e008:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:19,  1.37it/s, avg=0.09183, loss=0.09210]

trial_001 train e008:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:19,  1.37it/s, avg=0.09177, loss=0.08425]

trial_001 train e008:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:31<00:19,  1.35it/s, avg=0.09177, loss=0.08425]

trial_001 train e008:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.35it/s, avg=0.09177, loss=0.09263]

trial_001 train e008:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:32<00:18,  1.36it/s, avg=0.09177, loss=0.09263]

trial_001 train e008:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:18,  1.36it/s, avg=0.09184, loss=0.10048]

trial_001 train e008:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.38it/s, avg=0.09184, loss=0.10048]

trial_001 train e008:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:34<00:17,  1.38it/s, avg=0.09179, loss=0.08514]

trial_001 train e008:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:16,  1.35it/s, avg=0.09179, loss=0.08514]

trial_001 train e008:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:16,  1.35it/s, avg=0.09183, loss=0.09656]

trial_001 train e008:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:34<00:16,  1.33it/s, avg=0.09183, loss=0.09656]

trial_001 train e008:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.33it/s, avg=0.09184, loss=0.09362]

trial_001 train e008:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:35<00:15,  1.33it/s, avg=0.09184, loss=0.09362]

trial_001 train e008:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.33it/s, avg=0.09179, loss=0.08508]

trial_001 train e008:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:15,  1.33it/s, avg=0.09179, loss=0.08508]

trial_001 train e008:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:37<00:15,  1.33it/s, avg=0.09175, loss=0.08694]

trial_001 train e008:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.33it/s, avg=0.09175, loss=0.08694]

trial_001 train e008:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.33it/s, avg=0.09175, loss=0.09154]

trial_001 train e008:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:37<00:13,  1.33it/s, avg=0.09175, loss=0.09154]

trial_001 train e008:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.33it/s, avg=0.09190, loss=0.11132]

trial_001 train e008:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:38<00:12,  1.32it/s, avg=0.09190, loss=0.11132]

trial_001 train e008:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.32it/s, avg=0.09191, loss=0.09304]

trial_001 train e008:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:12,  1.31it/s, avg=0.09191, loss=0.09304]

trial_001 train e008:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:12,  1.31it/s, avg=0.09191, loss=0.09162]

trial_001 train e008:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:11,  1.33it/s, avg=0.09191, loss=0.09162]

trial_001 train e008:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:41<00:11,  1.33it/s, avg=0.09191, loss=0.09226]

trial_001 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.33it/s, avg=0.09191, loss=0.09226]

trial_001 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.33it/s, avg=0.09190, loss=0.09116]

trial_001 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:41<00:09,  1.33it/s, avg=0.09190, loss=0.09116]

trial_001 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.33it/s, avg=0.09184, loss=0.08312]

trial_001 train e008:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:09,  1.33it/s, avg=0.09184, loss=0.08312]

trial_001 train e008:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:43<00:09,  1.33it/s, avg=0.09177, loss=0.08307]

trial_001 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.33it/s, avg=0.09177, loss=0.08307]

trial_001 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:44<00:08,  1.33it/s, avg=0.09180, loss=0.09537]

trial_001 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.32it/s, avg=0.09180, loss=0.09537]

trial_001 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.32it/s, avg=0.09187, loss=0.10113]

trial_001 train e008:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:44<00:06,  1.32it/s, avg=0.09187, loss=0.10113]

trial_001 train e008:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.32it/s, avg=0.09179, loss=0.08153]

trial_001 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:06,  1.30it/s, avg=0.09179, loss=0.08153]

trial_001 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:46<00:06,  1.30it/s, avg=0.09176, loss=0.08735]

trial_001 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.32it/s, avg=0.09176, loss=0.08735]

trial_001 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:47<00:05,  1.32it/s, avg=0.09175, loss=0.09030]

trial_001 train e008:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.32it/s, avg=0.09175, loss=0.09030]

trial_001 train e008:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.32it/s, avg=0.09179, loss=0.09649]

trial_001 train e008:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:47<00:03,  1.33it/s, avg=0.09179, loss=0.09649]

trial_001 train e008:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.33it/s, avg=0.09173, loss=0.08418]

trial_001 train e008:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:03,  1.32it/s, avg=0.09173, loss=0.08418]

trial_001 train e008:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:49<00:03,  1.32it/s, avg=0.09169, loss=0.08512]

trial_001 train e008:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.34it/s, avg=0.09169, loss=0.08512]

trial_001 train e008:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:50<00:02,  1.34it/s, avg=0.09163, loss=0.08381]

trial_001 train e008:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.03it/s, avg=0.09163, loss=0.08381]

trial_001 train e008:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:51<00:01,  1.03it/s, avg=0.09172, loss=0.10388]

trial_001 train e008:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.03it/s, avg=0.09172, loss=0.10388]

trial_001 train e008:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:52<00:00,  1.03it/s, avg=0.09174, loss=0.10148]

trial_001 train e008: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:52<00:00,  1.12it/s, avg=0.09174, loss=0.10148]

trial_001 val e008:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e008:   2%|██▌                                                                                                                          | 1/50 [00:00<00:45,  1.08it/s]

trial_001 val e008:   4%|█████                                                                                                                        | 2/50 [00:01<00:42,  1.13it/s]

trial_001 val e008:   6%|███████▌                                                                                                                     | 3/50 [00:03<00:52,  1.12s/it]

trial_001 val e008:   8%|██████████                                                                                                                   | 4/50 [00:04<00:48,  1.05s/it]

trial_001 val e008:  10%|████████████▌                                                                                                                | 5/50 [00:05<00:51,  1.13s/it]

trial_001 val e008:  12%|███████████████                                                                                                              | 6/50 [00:06<00:45,  1.03s/it]

trial_001 val e008:  14%|█████████████████▌                                                                                                           | 7/50 [00:06<00:37,  1.13it/s]

trial_001 val e008:  16%|████████████████████                                                                                                         | 8/50 [00:07<00:31,  1.35it/s]

trial_001 val e008:  18%|██████████████████████▌                                                                                                      | 9/50 [00:07<00:26,  1.55it/s]

trial_001 val e008:  20%|████████████████████████▊                                                                                                   | 10/50 [00:08<00:23,  1.71it/s]

trial_001 val e008:  22%|███████████████████████████▎                                                                                                | 11/50 [00:08<00:21,  1.83it/s]

trial_001 val e008:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:09<00:19,  1.93it/s]

trial_001 val e008:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:09<00:18,  2.01it/s]

trial_001 val e008:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:09<00:17,  2.08it/s]

trial_001 val e008:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:10<00:16,  2.12it/s]

trial_001 val e008:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:10<00:15,  2.16it/s]

trial_001 val e008:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:11<00:15,  2.19it/s]

trial_001 val e008:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:11<00:14,  2.20it/s]

trial_001 val e008:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:12<00:13,  2.23it/s]

trial_001 val e008:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:12<00:13,  2.24it/s]

trial_001 val e008:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:13<00:12,  2.26it/s]

trial_001 val e008:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:13<00:12,  2.27it/s]

trial_001 val e008:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:13<00:11,  2.28it/s]

trial_001 val e008:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:14<00:11,  2.26it/s]

trial_001 val e008:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:14<00:11,  2.25it/s]

trial_001 val e008:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:15<00:10,  2.26it/s]

trial_001 val e008:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:15<00:10,  2.27it/s]

trial_001 val e008:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:16<00:09,  2.28it/s]

trial_001 val e008:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:16<00:09,  2.28it/s]

trial_001 val e008:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:16<00:08,  2.28it/s]

trial_001 val e008:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:17<00:08,  2.29it/s]

trial_001 val e008:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:17<00:07,  2.25it/s]

trial_001 val e008:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:18<00:07,  2.26it/s]

trial_001 val e008:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:18<00:07,  2.27it/s]

trial_001 val e008:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:19<00:06,  2.27it/s]

trial_001 val e008:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:19<00:06,  2.26it/s]

trial_001 val e008:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:20<00:05,  2.25it/s]

trial_001 val e008:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:20<00:05,  2.26it/s]

trial_001 val e008:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:20<00:04,  2.27it/s]

trial_001 val e008:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:21<00:04,  2.28it/s]

trial_001 val e008:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:21<00:03,  2.28it/s]

trial_001 val e008:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:22<00:03,  2.29it/s]

trial_001 val e008:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:22<00:03,  2.29it/s]

trial_001 val e008:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:23<00:02,  2.29it/s]

trial_001 val e008:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:23<00:02,  2.29it/s]

trial_001 val e008:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:24<00:01,  2.29it/s]

trial_001 val e008:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:24<00:01,  2.28it/s]

trial_001 val e008:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:24<00:00,  2.28it/s]

trial_001 val e008:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:25<00:00,  2.26it/s]

trial_001 val e008: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:25<00:00,  2.23it/s]

[2026-05-28 20:21:11] [trial_001] epoch=008 | train_loss=0.091743 | val_MAE=0.099275 | val_S=0.900725 | best_S=0.902019 @epoch=4 | patience=4/5

[trial_001] epochs:   8%|█████████▋                                                                                                               | 8/100 [17:54<3:26:59, 134.99s/it]

trial_001 train e009:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_001 train e009:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08436, loss=0.08436]

trial_001 train e009:   1%|▋                                                                                              | 1/149 [00:00<01:39,  1.49it/s, avg=0.08436, loss=0.08436]

trial_001 train e009:   1%|▋                                                                                              | 1/149 [00:01<01:39,  1.49it/s, avg=0.09591, loss=0.10745]

trial_001 train e009:   1%|█▎                                                                                             | 2/149 [00:01<01:41,  1.45it/s, avg=0.09591, loss=0.10745]

trial_001 train e009:   1%|█▎                                                                                             | 2/149 [00:02<01:41,  1.45it/s, avg=0.09960, loss=0.10698]

trial_001 train e009:   2%|█▉                                                                                             | 3/149 [00:02<01:41,  1.44it/s, avg=0.09960, loss=0.10698]

trial_001 train e009:   2%|█▉                                                                                             | 3/149 [00:02<01:41,  1.44it/s, avg=0.09515, loss=0.08181]

trial_001 train e009:   3%|██▌                                                                                            | 4/149 [00:02<01:44,  1.39it/s, avg=0.09515, loss=0.08181]

trial_001 train e009:   3%|██▌                                                                                            | 4/149 [00:03<01:44,  1.39it/s, avg=0.09410, loss=0.08990]

trial_001 train e009:   3%|███▏                                                                                           | 5/149 [00:03<01:42,  1.40it/s, avg=0.09410, loss=0.08990]

trial_001 train e009:   3%|███▏                                                                                           | 5/149 [00:04<01:42,  1.40it/s, avg=0.09202, loss=0.08160]

trial_001 train e009:   4%|███▊                                                                                           | 6/149 [00:04<01:45,  1.36it/s, avg=0.09202, loss=0.08160]

trial_001 train e009:   4%|███▊                                                                                           | 6/149 [00:05<01:45,  1.36it/s, avg=0.09286, loss=0.09794]

trial_001 train e009:   5%|████▍                                                                                          | 7/149 [00:05<01:46,  1.34it/s, avg=0.09286, loss=0.09794]

trial_001 train e009:   5%|████▍                                                                                          | 7/149 [00:05<01:46,  1.34it/s, avg=0.09356, loss=0.09842]

trial_001 train e009:   5%|█████                                                                                          | 8/149 [00:05<01:45,  1.34it/s, avg=0.09356, loss=0.09842]

trial_001 train e009:   5%|█████                                                                                          | 8/149 [00:06<01:45,  1.34it/s, avg=0.09342, loss=0.09228]

trial_001 train e009:   6%|█████▋                                                                                         | 9/149 [00:06<01:42,  1.37it/s, avg=0.09342, loss=0.09228]

trial_001 train e009:   6%|█████▋                                                                                         | 9/149 [00:07<01:42,  1.37it/s, avg=0.09485, loss=0.10780]

trial_001 train e009:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.09485, loss=0.10780]

trial_001 train e009:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.09422, loss=0.08788]

trial_001 train e009:   7%|██████▉                                                                                       | 11/149 [00:07<01:41,  1.36it/s, avg=0.09422, loss=0.08788]

trial_001 train e009:   7%|██████▉                                                                                       | 11/149 [00:08<01:41,  1.36it/s, avg=0.09332, loss=0.08343]

trial_001 train e009:   8%|███████▌                                                                                      | 12/149 [00:08<01:42,  1.34it/s, avg=0.09332, loss=0.08343]

trial_001 train e009:   8%|███████▌                                                                                      | 12/149 [00:09<01:42,  1.34it/s, avg=0.09316, loss=0.09127]

trial_001 train e009:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.35it/s, avg=0.09316, loss=0.09127]

trial_001 train e009:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.35it/s, avg=0.09314, loss=0.09280]

trial_001 train e009:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.33it/s, avg=0.09314, loss=0.09280]

trial_001 train e009:   9%|████████▊                                                                                     | 14/149 [00:11<01:41,  1.33it/s, avg=0.09303, loss=0.09155]

trial_001 train e009:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.33it/s, avg=0.09303, loss=0.09155]

trial_001 train e009:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.33it/s, avg=0.09244, loss=0.08354]

trial_001 train e009:  11%|██████████                                                                                    | 16/149 [00:11<01:38,  1.35it/s, avg=0.09244, loss=0.08354]

trial_001 train e009:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.35it/s, avg=0.09207, loss=0.08617]

trial_001 train e009:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.34it/s, avg=0.09207, loss=0.08617]

trial_001 train e009:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.34it/s, avg=0.09175, loss=0.08629]

trial_001 train e009:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.09175, loss=0.08629]

trial_001 train e009:  12%|███████████▎                                                                                  | 18/149 [00:14<01:37,  1.34it/s, avg=0.09170, loss=0.09085]

trial_001 train e009:  13%|███████████▉                                                                                  | 19/149 [00:14<01:38,  1.32it/s, avg=0.09170, loss=0.09085]

trial_001 train e009:  13%|███████████▉                                                                                  | 19/149 [00:14<01:38,  1.32it/s, avg=0.09170, loss=0.09165]

trial_001 train e009:  13%|████████████▌                                                                                 | 20/149 [00:14<01:34,  1.37it/s, avg=0.09170, loss=0.09165]

trial_001 train e009:  13%|████████████▌                                                                                 | 20/149 [00:15<01:34,  1.37it/s, avg=0.09118, loss=0.08073]

trial_001 train e009:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.33it/s, avg=0.09118, loss=0.08073]

trial_001 train e009:  14%|█████████████▏                                                                                | 21/149 [00:16<01:36,  1.33it/s, avg=0.09091, loss=0.08526]

trial_001 train e009:  15%|█████████████▉                                                                                | 22/149 [00:16<01:35,  1.32it/s, avg=0.09091, loss=0.08526]

trial_001 train e009:  15%|█████████████▉                                                                                | 22/149 [00:17<01:35,  1.32it/s, avg=0.09024, loss=0.07551]

trial_001 train e009:  15%|██████████████▌                                                                               | 23/149 [00:17<01:36,  1.31it/s, avg=0.09024, loss=0.07551]

trial_001 train e009:  15%|██████████████▌                                                                               | 23/149 [00:17<01:36,  1.31it/s, avg=0.09043, loss=0.09475]

trial_001 train e009:  16%|███████████████▏                                                                              | 24/149 [00:17<01:36,  1.30it/s, avg=0.09043, loss=0.09475]

trial_001 train e009:  16%|███████████████▏                                                                              | 24/149 [00:18<01:36,  1.30it/s, avg=0.09062, loss=0.09525]

trial_001 train e009:  17%|███████████████▊                                                                              | 25/149 [00:18<01:34,  1.31it/s, avg=0.09062, loss=0.09525]

trial_001 train e009:  17%|███████████████▊                                                                              | 25/149 [00:19<01:34,  1.31it/s, avg=0.09099, loss=0.10041]

trial_001 train e009:  17%|████████████████▍                                                                             | 26/149 [00:19<01:32,  1.33it/s, avg=0.09099, loss=0.10041]

trial_001 train e009:  17%|████████████████▍                                                                             | 26/149 [00:20<01:32,  1.33it/s, avg=0.09109, loss=0.09355]

trial_001 train e009:  18%|█████████████████                                                                             | 27/149 [00:20<01:33,  1.31it/s, avg=0.09109, loss=0.09355]

trial_001 train e009:  18%|█████████████████                                                                             | 27/149 [00:20<01:33,  1.31it/s, avg=0.09112, loss=0.09185]

trial_001 train e009:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:32,  1.31it/s, avg=0.09112, loss=0.09185]

trial_001 train e009:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:32,  1.31it/s, avg=0.09120, loss=0.09350]

trial_001 train e009:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:32,  1.30it/s, avg=0.09120, loss=0.09350]

trial_001 train e009:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:32,  1.30it/s, avg=0.09159, loss=0.10283]

trial_001 train e009:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:30,  1.32it/s, avg=0.09159, loss=0.10283]

trial_001 train e009:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:30,  1.32it/s, avg=0.09121, loss=0.08004]

trial_001 train e009:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:29,  1.31it/s, avg=0.09121, loss=0.08004]

trial_001 train e009:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:29,  1.31it/s, avg=0.09120, loss=0.09076]

trial_001 train e009:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:28,  1.33it/s, avg=0.09120, loss=0.09076]

trial_001 train e009:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:28,  1.33it/s, avg=0.09134, loss=0.09594]

trial_001 train e009:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:25,  1.35it/s, avg=0.09134, loss=0.09594]

trial_001 train e009:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:25,  1.35it/s, avg=0.09142, loss=0.09391]

trial_001 train e009:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:26,  1.32it/s, avg=0.09142, loss=0.09391]

trial_001 train e009:  23%|█████████████████████▍                                                                        | 34/149 [00:26<01:26,  1.32it/s, avg=0.09148, loss=0.09350]

trial_001 train e009:  23%|██████████████████████                                                                        | 35/149 [00:26<01:26,  1.32it/s, avg=0.09148, loss=0.09350]

trial_001 train e009:  23%|██████████████████████                                                                        | 35/149 [00:26<01:26,  1.32it/s, avg=0.09196, loss=0.10889]

trial_001 train e009:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:26,  1.31it/s, avg=0.09196, loss=0.10889]

trial_001 train e009:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:26,  1.31it/s, avg=0.09209, loss=0.09649]

trial_001 train e009:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:25,  1.31it/s, avg=0.09209, loss=0.09649]

trial_001 train e009:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:25,  1.31it/s, avg=0.09269, loss=0.11498]

trial_001 train e009:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:23,  1.34it/s, avg=0.09269, loss=0.11498]

trial_001 train e009:  26%|███████████████████████▉                                                                      | 38/149 [00:29<01:23,  1.34it/s, avg=0.09250, loss=0.08531]

trial_001 train e009:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.32it/s, avg=0.09250, loss=0.08531]

trial_001 train e009:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.32it/s, avg=0.09265, loss=0.09846]

trial_001 train e009:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:21,  1.34it/s, avg=0.09265, loss=0.09846]

trial_001 train e009:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:21,  1.34it/s, avg=0.09262, loss=0.09146]

trial_001 train e009:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:21,  1.33it/s, avg=0.09262, loss=0.09146]

trial_001 train e009:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:21,  1.33it/s, avg=0.09300, loss=0.10852]

trial_001 train e009:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:17,  1.37it/s, avg=0.09300, loss=0.10852]

trial_001 train e009:  28%|██████████████████████████▍                                                                   | 42/149 [00:32<01:17,  1.37it/s, avg=0.09283, loss=0.08575]

trial_001 train e009:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:16,  1.38it/s, avg=0.09283, loss=0.08575]

trial_001 train e009:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:16,  1.38it/s, avg=0.09277, loss=0.09030]

trial_001 train e009:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.34it/s, avg=0.09277, loss=0.09030]

trial_001 train e009:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:18,  1.34it/s, avg=0.09299, loss=0.10267]

trial_001 train e009:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.38it/s, avg=0.09299, loss=0.10267]

trial_001 train e009:  30%|████████████████████████████▍                                                                 | 45/149 [00:34<01:15,  1.38it/s, avg=0.09303, loss=0.09496]

trial_001 train e009:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:16,  1.35it/s, avg=0.09303, loss=0.09496]

trial_001 train e009:  31%|█████████████████████████████                                                                 | 46/149 [00:35<01:16,  1.35it/s, avg=0.09297, loss=0.09019]

trial_001 train e009:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:15,  1.35it/s, avg=0.09297, loss=0.09019]

trial_001 train e009:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:15,  1.35it/s, avg=0.09285, loss=0.08724]

trial_001 train e009:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:13,  1.38it/s, avg=0.09285, loss=0.08724]

trial_001 train e009:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:13,  1.38it/s, avg=0.09290, loss=0.09488]

trial_001 train e009:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:13,  1.35it/s, avg=0.09290, loss=0.09488]

trial_001 train e009:  33%|██████████████████████████████▉                                                               | 49/149 [00:37<01:13,  1.35it/s, avg=0.09285, loss=0.09060]

trial_001 train e009:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:13,  1.34it/s, avg=0.09285, loss=0.09060]

trial_001 train e009:  34%|███████████████████████████████▌                                                              | 50/149 [00:38<01:13,  1.34it/s, avg=0.09286, loss=0.09338]

trial_001 train e009:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:12,  1.35it/s, avg=0.09286, loss=0.09338]

trial_001 train e009:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:12,  1.35it/s, avg=0.09297, loss=0.09859]

trial_001 train e009:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:13,  1.32it/s, avg=0.09297, loss=0.09859]

trial_001 train e009:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:13,  1.32it/s, avg=0.09287, loss=0.08791]

trial_001 train e009:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:13,  1.31it/s, avg=0.09287, loss=0.08791]

trial_001 train e009:  36%|█████████████████████████████████▍                                                            | 53/149 [00:40<01:13,  1.31it/s, avg=0.09291, loss=0.09463]

trial_001 train e009:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:12,  1.32it/s, avg=0.09291, loss=0.09463]

trial_001 train e009:  36%|██████████████████████████████████                                                            | 54/149 [00:41<01:12,  1.32it/s, avg=0.09287, loss=0.09102]

trial_001 train e009:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:11,  1.31it/s, avg=0.09287, loss=0.09102]

trial_001 train e009:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:11,  1.31it/s, avg=0.09293, loss=0.09591]

trial_001 train e009:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:10,  1.31it/s, avg=0.09293, loss=0.09591]

trial_001 train e009:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:10,  1.31it/s, avg=0.09269, loss=0.07949]

trial_001 train e009:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:09,  1.33it/s, avg=0.09269, loss=0.07949]

trial_001 train e009:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<01:09,  1.33it/s, avg=0.09273, loss=0.09471]

trial_001 train e009:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:09,  1.30it/s, avg=0.09273, loss=0.09471]

trial_001 train e009:  39%|████████████████████████████████████▌                                                         | 58/149 [00:44<01:09,  1.30it/s, avg=0.09279, loss=0.09641]

trial_001 train e009:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:10,  1.28it/s, avg=0.09279, loss=0.09641]

trial_001 train e009:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:10,  1.28it/s, avg=0.09264, loss=0.08395]

trial_001 train e009:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:07,  1.31it/s, avg=0.09264, loss=0.08395]

trial_001 train e009:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:45<01:07,  1.31it/s, avg=0.09257, loss=0.08852]

trial_001 train e009:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:06,  1.32it/s, avg=0.09257, loss=0.08852]

trial_001 train e009:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:46<01:06,  1.32it/s, avg=0.09249, loss=0.08721]

trial_001 train e009:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:05,  1.33it/s, avg=0.09249, loss=0.08721]

trial_001 train e009:  42%|███████████████████████████████████████                                                       | 62/149 [00:47<01:05,  1.33it/s, avg=0.09253, loss=0.09532]

trial_001 train e009:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:04,  1.34it/s, avg=0.09253, loss=0.09532]

trial_001 train e009:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:04,  1.34it/s, avg=0.09251, loss=0.09108]

trial_001 train e009:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:03,  1.33it/s, avg=0.09251, loss=0.09108]

trial_001 train e009:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:48<01:03,  1.33it/s, avg=0.09224, loss=0.07493]

trial_001 train e009:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:03,  1.33it/s, avg=0.09224, loss=0.07493]

trial_001 train e009:  44%|█████████████████████████████████████████                                                     | 65/149 [00:49<01:03,  1.33it/s, avg=0.09223, loss=0.09163]

trial_001 train e009:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:03,  1.31it/s, avg=0.09223, loss=0.09163]

trial_001 train e009:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:50<01:03,  1.31it/s, avg=0.09241, loss=0.10430]

trial_001 train e009:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:01,  1.33it/s, avg=0.09241, loss=0.10430]

trial_001 train e009:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:01,  1.33it/s, avg=0.09261, loss=0.10604]

trial_001 train e009:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<01:00,  1.33it/s, avg=0.09261, loss=0.10604]

trial_001 train e009:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:51<01:00,  1.33it/s, avg=0.09242, loss=0.07949]

trial_001 train e009:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<01:00,  1.31it/s, avg=0.09242, loss=0.07949]

trial_001 train e009:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:52<01:00,  1.31it/s, avg=0.09220, loss=0.07714]

trial_001 train e009:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<01:00,  1.30it/s, avg=0.09220, loss=0.07714]

trial_001 train e009:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:53<01:00,  1.30it/s, avg=0.09211, loss=0.08543]

trial_001 train e009:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:58,  1.33it/s, avg=0.09211, loss=0.08543]

trial_001 train e009:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:53<00:58,  1.33it/s, avg=0.09208, loss=0.08984]

trial_001 train e009:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:59,  1.29it/s, avg=0.09208, loss=0.08984]

trial_001 train e009:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:54<00:59,  1.29it/s, avg=0.09214, loss=0.09702]

trial_001 train e009:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:59,  1.28it/s, avg=0.09214, loss=0.09702]

trial_001 train e009:  49%|██████████████████████████████████████████████                                                | 73/149 [00:55<00:59,  1.28it/s, avg=0.09196, loss=0.07839]

trial_001 train e009:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:58,  1.28it/s, avg=0.09196, loss=0.07839]

trial_001 train e009:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:56<00:58,  1.28it/s, avg=0.09184, loss=0.08339]

trial_001 train e009:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:56<00:57,  1.29it/s, avg=0.09184, loss=0.08339]

trial_001 train e009:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:57<00:57,  1.29it/s, avg=0.09191, loss=0.09663]

trial_001 train e009:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:56,  1.30it/s, avg=0.09191, loss=0.09663]

trial_001 train e009:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:57<00:56,  1.30it/s, avg=0.09193, loss=0.09395]

trial_001 train e009:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:55,  1.30it/s, avg=0.09193, loss=0.09395]

trial_001 train e009:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:58<00:55,  1.30it/s, avg=0.09205, loss=0.10105]

trial_001 train e009:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:53,  1.32it/s, avg=0.09205, loss=0.10105]

trial_001 train e009:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:59<00:53,  1.32it/s, avg=0.09215, loss=0.09997]

trial_001 train e009:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:59<00:53,  1.32it/s, avg=0.09215, loss=0.09997]

trial_001 train e009:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [01:00<00:53,  1.32it/s, avg=0.09207, loss=0.08578]

trial_001 train e009:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:51,  1.33it/s, avg=0.09207, loss=0.08578]

trial_001 train e009:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:00<00:51,  1.33it/s, avg=0.09196, loss=0.08301]

trial_001 train e009:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:51,  1.33it/s, avg=0.09196, loss=0.08301]

trial_001 train e009:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:01<00:51,  1.33it/s, avg=0.09205, loss=0.09971]

trial_001 train e009:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:01<00:50,  1.33it/s, avg=0.09205, loss=0.09971]

trial_001 train e009:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:02<00:50,  1.33it/s, avg=0.09212, loss=0.09781]

trial_001 train e009:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:02<00:50,  1.31it/s, avg=0.09212, loss=0.09781]

trial_001 train e009:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:03<00:50,  1.31it/s, avg=0.09192, loss=0.07537]

trial_001 train e009:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:50,  1.30it/s, avg=0.09192, loss=0.07537]

trial_001 train e009:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:03<00:50,  1.30it/s, avg=0.09191, loss=0.09049]

trial_001 train e009:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:49,  1.30it/s, avg=0.09191, loss=0.09049]

trial_001 train e009:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:04<00:49,  1.30it/s, avg=0.09205, loss=0.10430]

trial_001 train e009:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:04<00:47,  1.33it/s, avg=0.09205, loss=0.10430]

trial_001 train e009:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:05<00:47,  1.33it/s, avg=0.09203, loss=0.09053]

trial_001 train e009:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:05<00:46,  1.33it/s, avg=0.09203, loss=0.09053]

trial_001 train e009:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:06<00:46,  1.33it/s, avg=0.09233, loss=0.11863]

trial_001 train e009:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:44,  1.36it/s, avg=0.09233, loss=0.11863]

trial_001 train e009:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:06<00:44,  1.36it/s, avg=0.09240, loss=0.09773]

trial_001 train e009:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:45,  1.33it/s, avg=0.09240, loss=0.09773]

trial_001 train e009:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:07<00:45,  1.33it/s, avg=0.09236, loss=0.08955]

trial_001 train e009:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:07<00:44,  1.31it/s, avg=0.09236, loss=0.08955]

trial_001 train e009:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:08<00:44,  1.31it/s, avg=0.09228, loss=0.08486]

trial_001 train e009:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:08<00:44,  1.32it/s, avg=0.09228, loss=0.08486]

trial_001 train e009:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:09<00:44,  1.32it/s, avg=0.09221, loss=0.08585]

trial_001 train e009:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.31it/s, avg=0.09221, loss=0.08585]

trial_001 train e009:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:09<00:43,  1.31it/s, avg=0.09224, loss=0.09485]

trial_001 train e009:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:42,  1.33it/s, avg=0.09224, loss=0.09485]

trial_001 train e009:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:10<00:42,  1.33it/s, avg=0.09214, loss=0.08287]

trial_001 train e009:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:10<00:39,  1.39it/s, avg=0.09214, loss=0.08287]

trial_001 train e009:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:11<00:39,  1.39it/s, avg=0.09233, loss=0.10986]

trial_001 train e009:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:11<00:39,  1.38it/s, avg=0.09233, loss=0.10986]

trial_001 train e009:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:12<00:39,  1.38it/s, avg=0.09215, loss=0.07567]

trial_001 train e009:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.34it/s, avg=0.09215, loss=0.07567]

trial_001 train e009:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:12<00:39,  1.34it/s, avg=0.09213, loss=0.09002]

trial_001 train e009:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.36it/s, avg=0.09213, loss=0.09002]

trial_001 train e009:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:13<00:38,  1.36it/s, avg=0.09213, loss=0.09212]

trial_001 train e009:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:13<00:37,  1.35it/s, avg=0.09213, loss=0.09212]

trial_001 train e009:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:14<00:37,  1.35it/s, avg=0.09215, loss=0.09368]

trial_001 train e009:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:14<00:37,  1.35it/s, avg=0.09215, loss=0.09368]

trial_001 train e009:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:15<00:37,  1.35it/s, avg=0.09211, loss=0.08899]

trial_001 train e009:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:36,  1.35it/s, avg=0.09211, loss=0.08899]

trial_001 train e009:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:15<00:36,  1.35it/s, avg=0.09207, loss=0.08725]

trial_001 train e009:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:15<00:36,  1.33it/s, avg=0.09207, loss=0.08725]

trial_001 train e009:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:16<00:36,  1.33it/s, avg=0.09202, loss=0.08721]

trial_001 train e009:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:16<00:35,  1.34it/s, avg=0.09202, loss=0.08721]

trial_001 train e009:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:17<00:35,  1.34it/s, avg=0.09202, loss=0.09208]

trial_001 train e009:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:17<00:34,  1.33it/s, avg=0.09202, loss=0.09208]

trial_001 train e009:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:18<00:34,  1.33it/s, avg=0.09200, loss=0.09029]

trial_001 train e009:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.34it/s, avg=0.09200, loss=0.09029]

trial_001 train e009:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:18<00:33,  1.34it/s, avg=0.09191, loss=0.08243]

trial_001 train e009:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:18<00:33,  1.33it/s, avg=0.09191, loss=0.08243]

trial_001 train e009:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:19<00:33,  1.33it/s, avg=0.09178, loss=0.07786]

trial_001 train e009:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:19<00:32,  1.33it/s, avg=0.09178, loss=0.07786]

trial_001 train e009:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:20<00:32,  1.33it/s, avg=0.09181, loss=0.09541]

trial_001 train e009:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:20<00:31,  1.33it/s, avg=0.09181, loss=0.09541]

trial_001 train e009:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:21<00:31,  1.33it/s, avg=0.09186, loss=0.09682]

trial_001 train e009:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.34it/s, avg=0.09186, loss=0.09682]

trial_001 train e009:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:21<00:30,  1.34it/s, avg=0.09169, loss=0.07361]

trial_001 train e009:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:21<00:29,  1.35it/s, avg=0.09169, loss=0.07361]

trial_001 train e009:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:22<00:29,  1.35it/s, avg=0.09160, loss=0.08150]

trial_001 train e009:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:22<00:28,  1.36it/s, avg=0.09160, loss=0.08150]

trial_001 train e009:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:23<00:28,  1.36it/s, avg=0.09156, loss=0.08682]

trial_001 train e009:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:27,  1.37it/s, avg=0.09156, loss=0.08682]

trial_001 train e009:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:23<00:27,  1.37it/s, avg=0.09158, loss=0.09389]

trial_001 train e009:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:26,  1.39it/s, avg=0.09158, loss=0.09389]

trial_001 train e009:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:24<00:26,  1.39it/s, avg=0.09150, loss=0.08339]

trial_001 train e009:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:24<00:26,  1.37it/s, avg=0.09150, loss=0.08339]

trial_001 train e009:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:25<00:26,  1.37it/s, avg=0.09147, loss=0.08744]

trial_001 train e009:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:25<00:26,  1.33it/s, avg=0.09147, loss=0.08744]

trial_001 train e009:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:26<00:26,  1.33it/s, avg=0.09148, loss=0.09244]

trial_001 train e009:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.34it/s, avg=0.09148, loss=0.09244]

trial_001 train e009:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:26<00:25,  1.34it/s, avg=0.09162, loss=0.10812]

trial_001 train e009:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:26<00:23,  1.38it/s, avg=0.09162, loss=0.10812]

trial_001 train e009:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:27<00:23,  1.38it/s, avg=0.09163, loss=0.09322]

trial_001 train e009:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:27<00:23,  1.35it/s, avg=0.09163, loss=0.09322]

trial_001 train e009:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:28<00:23,  1.35it/s, avg=0.09167, loss=0.09527]

trial_001 train e009:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:28<00:23,  1.33it/s, avg=0.09167, loss=0.09527]

trial_001 train e009:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:29<00:23,  1.33it/s, avg=0.09169, loss=0.09475]

trial_001 train e009:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.33it/s, avg=0.09169, loss=0.09475]

trial_001 train e009:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:29<00:22,  1.33it/s, avg=0.09165, loss=0.08662]

trial_001 train e009:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:29<00:21,  1.33it/s, avg=0.09165, loss=0.08662]

trial_001 train e009:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:30<00:21,  1.33it/s, avg=0.09170, loss=0.09747]

trial_001 train e009:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:30<00:21,  1.33it/s, avg=0.09170, loss=0.09747]

trial_001 train e009:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:31<00:21,  1.33it/s, avg=0.09178, loss=0.10122]

trial_001 train e009:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:31<00:20,  1.31it/s, avg=0.09178, loss=0.10122]

trial_001 train e009:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:32<00:20,  1.31it/s, avg=0.09178, loss=0.09280]

trial_001 train e009:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:32<00:19,  1.31it/s, avg=0.09178, loss=0.09280]

trial_001 train e009:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:33<00:19,  1.31it/s, avg=0.09185, loss=0.09944]

trial_001 train e009:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:18,  1.33it/s, avg=0.09185, loss=0.09944]

trial_001 train e009:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:33<00:18,  1.33it/s, avg=0.09181, loss=0.08783]

trial_001 train e009:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:33<00:17,  1.35it/s, avg=0.09181, loss=0.08783]

trial_001 train e009:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:34<00:17,  1.35it/s, avg=0.09183, loss=0.09390]

trial_001 train e009:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:34<00:17,  1.34it/s, avg=0.09183, loss=0.09390]

trial_001 train e009:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:35<00:17,  1.34it/s, avg=0.09179, loss=0.08698]

trial_001 train e009:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.34it/s, avg=0.09179, loss=0.08698]

trial_001 train e009:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:35<00:16,  1.34it/s, avg=0.09178, loss=0.09066]

trial_001 train e009:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:35<00:15,  1.33it/s, avg=0.09178, loss=0.09066]

trial_001 train e009:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:36<00:15,  1.33it/s, avg=0.09172, loss=0.08332]

trial_001 train e009:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:36<00:14,  1.33it/s, avg=0.09172, loss=0.08332]

trial_001 train e009:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:37<00:14,  1.33it/s, avg=0.09170, loss=0.08935]

trial_001 train e009:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:37<00:14,  1.35it/s, avg=0.09170, loss=0.08935]

trial_001 train e009:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:38<00:14,  1.35it/s, avg=0.09162, loss=0.08179]

trial_001 train e009:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:38<00:13,  1.33it/s, avg=0.09162, loss=0.08179]

trial_001 train e009:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:39<00:13,  1.33it/s, avg=0.09168, loss=0.09914]

trial_001 train e009:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.31it/s, avg=0.09168, loss=0.09914]

trial_001 train e009:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:39<00:12,  1.31it/s, avg=0.09164, loss=0.08676]

trial_001 train e009:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:39<00:12,  1.32it/s, avg=0.09164, loss=0.08676]

trial_001 train e009:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:40<00:12,  1.32it/s, avg=0.09163, loss=0.09009]

trial_001 train e009:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:40<00:11,  1.32it/s, avg=0.09163, loss=0.09009]

trial_001 train e009:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:41<00:11,  1.32it/s, avg=0.09166, loss=0.09504]

trial_001 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:41<00:10,  1.33it/s, avg=0.09166, loss=0.09504]

trial_001 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:42<00:10,  1.33it/s, avg=0.09165, loss=0.09087]

trial_001 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.32it/s, avg=0.09165, loss=0.09087]

trial_001 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:42<00:09,  1.32it/s, avg=0.09164, loss=0.08946]

trial_001 train e009:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:42<00:09,  1.33it/s, avg=0.09164, loss=0.08946]

trial_001 train e009:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:43<00:09,  1.33it/s, avg=0.09152, loss=0.07523]

trial_001 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:43<00:08,  1.32it/s, avg=0.09152, loss=0.07523]

trial_001 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:44<00:08,  1.32it/s, avg=0.09154, loss=0.09547]

trial_001 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:44<00:07,  1.34it/s, avg=0.09154, loss=0.09547]

trial_001 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:45<00:07,  1.34it/s, avg=0.09146, loss=0.08016]

trial_001 train e009:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.33it/s, avg=0.09146, loss=0.08016]

trial_001 train e009:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:45<00:06,  1.33it/s, avg=0.09146, loss=0.09134]

trial_001 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:45<00:06,  1.31it/s, avg=0.09146, loss=0.09134]

trial_001 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:46<00:06,  1.31it/s, avg=0.09147, loss=0.09304]

trial_001 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:46<00:05,  1.30it/s, avg=0.09147, loss=0.09304]

trial_001 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:47<00:05,  1.30it/s, avg=0.09143, loss=0.08458]

trial_001 train e009:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:47<00:04,  1.32it/s, avg=0.09143, loss=0.08458]

trial_001 train e009:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:48<00:04,  1.32it/s, avg=0.09133, loss=0.07738]

trial_001 train e009:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.30it/s, avg=0.09133, loss=0.07738]

trial_001 train e009:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:48<00:03,  1.30it/s, avg=0.09134, loss=0.09378]

trial_001 train e009:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:48<00:03,  1.32it/s, avg=0.09134, loss=0.09378]

trial_001 train e009:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:49<00:03,  1.32it/s, avg=0.09134, loss=0.09107]

trial_001 train e009:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:49<00:02,  1.31it/s, avg=0.09134, loss=0.09107]

trial_001 train e009:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:50<00:02,  1.31it/s, avg=0.09132, loss=0.08847]

trial_001 train e009:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:50<00:01,  1.30it/s, avg=0.09132, loss=0.08847]

trial_001 train e009:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:51<00:01,  1.30it/s, avg=0.09139, loss=0.10087]

trial_001 train e009:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.33it/s, avg=0.09139, loss=0.10087]

trial_001 train e009:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:51<00:00,  1.33it/s, avg=0.09138, loss=0.08676]

trial_001 train e009: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:51<00:00,  1.60it/s, avg=0.09138, loss=0.08676]

trial_001 val e009:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_001 val e009:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.27it/s]

trial_001 val e009:   4%|█████                                                                                                                        | 2/50 [00:00<00:21,  2.28it/s]

trial_001 val e009:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.28it/s]

trial_001 val e009:   8%|██████████                                                                                                                   | 4/50 [00:01<00:20,  2.26it/s]

trial_001 val e009:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.26it/s]

trial_001 val e009:  12%|███████████████                                                                                                              | 6/50 [00:02<00:19,  2.26it/s]

trial_001 val e009:  14%|█████████████████▌                                                                                                           | 7/50 [00:03<00:19,  2.25it/s]

trial_001 val e009:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:18,  2.23it/s]

trial_001 val e009:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:18,  2.25it/s]

trial_001 val e009:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.26it/s]

trial_001 val e009:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:17,  2.26it/s]

trial_001 val e009:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.27it/s]

trial_001 val e009:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:16,  2.27it/s]

trial_001 val e009:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:06<00:15,  2.27it/s]

trial_001 val e009:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:15,  2.27it/s]

trial_001 val e009:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:07<00:15,  2.26it/s]

trial_001 val e009:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.27it/s]

trial_001 val e009:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:14,  2.23it/s]

trial_001 val e009:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:13,  2.23it/s]

trial_001 val e009:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:13,  2.23it/s]

trial_001 val e009:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:09<00:12,  2.25it/s]

trial_001 val e009:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.26it/s]

trial_001 val e009:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:10<00:11,  2.27it/s]

trial_001 val e009:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.27it/s]

trial_001 val e009:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:11<00:10,  2.27it/s]

trial_001 val e009:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:11<00:10,  2.28it/s]

trial_001 val e009:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:10,  2.29it/s]

trial_001 val e009:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:12<00:09,  2.28it/s]

trial_001 val e009:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.29it/s]

trial_001 val e009:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:13<00:08,  2.30it/s]

trial_001 val e009:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:08,  2.31it/s]

trial_001 val e009:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:14<00:07,  2.28it/s]

trial_001 val e009:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:14<00:07,  2.26it/s]

trial_001 val e009:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:15<00:07,  2.27it/s]

trial_001 val e009:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:15<00:06,  2.28it/s]

trial_001 val e009:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:06,  2.26it/s]

trial_001 val e009:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:16<00:05,  2.27it/s]

trial_001 val e009:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:16<00:05,  2.27it/s]

trial_001 val e009:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:17<00:04,  2.28it/s]

trial_001 val e009:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:17<00:04,  2.28it/s]

trial_001 val e009:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:18<00:03,  2.27it/s]

trial_001 val e009:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:18<00:03,  2.29it/s]

trial_001 val e009:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:03,  2.27it/s]

trial_001 val e009:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:19<00:02,  2.27it/s]

trial_001 val e009:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:19<00:02,  2.28it/s]

trial_001 val e009:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:20<00:01,  2.28it/s]

trial_001 val e009:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:20<00:01,  2.29it/s]

trial_001 val e009:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:21<00:00,  2.27it/s]

trial_001 val e009:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:21<00:00,  2.26it/s]

trial_001 val e009: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:22<00:00,  2.27it/s]

[2026-05-28 20:23:25] [trial_001] epoch=009 | train_loss=0.091376 | val_MAE=0.098169 | val_S=0.901831 | best_S=0.902019 @epoch=4 | patience=5/5

[2026-05-28 20:23:25] [trial_001] early stopping at epoch=9

[2026-05-28 20:23:32] [trial_001] DONE | best_epoch=4 | best_val_S=0.902019 | test_MAE=nan | test_R2=nan

[2026-05-28 20:23:33] [OPTUNA] trial_001 done | best_val_S=0.902019

[2026-05-28 20:23:34] [OPTUNA] trial_002 start | hp={'learning_rate': 0.0001016436906561294, 'r': 4, 'lora_alpha': 16, 'lora_dropout': 0.15, 'weight_decay': 0.007233619949447476, 'warmup_ratio': 0.08}

[2026-05-28 20:23:35] [trial_002] START | seed=42 | hp={'learning_rate': 0.0001016436906561294, 'r': 4, 'lora_alpha': 16, 'lora_dropout': 0.15, 'weight_decay': 0.007233619949447476, 'warmup_ratio': 0.08}

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

[trial_002] epochs:   0%|                                                                                                                                    | 0/100 [00:00<?, ?it/s]

trial_002 train e001:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e001:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.12754, loss=0.12754]

trial_002 train e001:   1%|▋                                                                                              | 1/149 [00:00<02:04,  1.19it/s, avg=0.12754, loss=0.12754]

trial_002 train e001:   1%|▋                                                                                              | 1/149 [00:01<02:04,  1.19it/s, avg=0.13171, loss=0.13588]

trial_002 train e001:   1%|█▎                                                                                             | 2/149 [00:01<01:54,  1.29it/s, avg=0.13171, loss=0.13588]

trial_002 train e001:   1%|█▎                                                                                             | 2/149 [00:02<01:54,  1.29it/s, avg=0.12874, loss=0.12280]

trial_002 train e001:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.12874, loss=0.12280]

trial_002 train e001:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.12362, loss=0.10827]

trial_002 train e001:   3%|██▌                                                                                            | 4/149 [00:02<01:46,  1.37it/s, avg=0.12362, loss=0.10827]

trial_002 train e001:   3%|██▌                                                                                            | 4/149 [00:03<01:46,  1.37it/s, avg=0.12591, loss=0.13505]

trial_002 train e001:   3%|███▏                                                                                           | 5/149 [00:03<01:43,  1.40it/s, avg=0.12591, loss=0.13505]

trial_002 train e001:   3%|███▏                                                                                           | 5/149 [00:04<01:43,  1.40it/s, avg=0.12639, loss=0.12877]

trial_002 train e001:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.40it/s, avg=0.12639, loss=0.12877]

trial_002 train e001:   4%|███▊                                                                                           | 6/149 [00:05<01:42,  1.40it/s, avg=0.12581, loss=0.12235]

trial_002 train e001:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.12581, loss=0.12235]

trial_002 train e001:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.12487, loss=0.11827]

trial_002 train e001:   5%|█████                                                                                          | 8/149 [00:05<01:40,  1.41it/s, avg=0.12487, loss=0.11827]

trial_002 train e001:   5%|█████                                                                                          | 8/149 [00:06<01:40,  1.41it/s, avg=0.12521, loss=0.12794]

trial_002 train e001:   6%|█████▋                                                                                         | 9/149 [00:06<01:39,  1.40it/s, avg=0.12521, loss=0.12794]

trial_002 train e001:   6%|█████▋                                                                                         | 9/149 [00:07<01:39,  1.40it/s, avg=0.12509, loss=0.12404]

trial_002 train e001:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.12509, loss=0.12404]

trial_002 train e001:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.12542, loss=0.12868]

trial_002 train e001:   7%|██████▉                                                                                       | 11/149 [00:07<01:40,  1.38it/s, avg=0.12542, loss=0.12868]

trial_002 train e001:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.38it/s, avg=0.12459, loss=0.11551]

trial_002 train e001:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.36it/s, avg=0.12459, loss=0.11551]

trial_002 train e001:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.36it/s, avg=0.12471, loss=0.12612]

trial_002 train e001:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.36it/s, avg=0.12471, loss=0.12612]

trial_002 train e001:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.36it/s, avg=0.12491, loss=0.12759]

trial_002 train e001:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.40it/s, avg=0.12491, loss=0.12759]

trial_002 train e001:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.40it/s, avg=0.12466, loss=0.12115]

trial_002 train e001:  10%|█████████▍                                                                                    | 15/149 [00:10<01:36,  1.39it/s, avg=0.12466, loss=0.12115]

trial_002 train e001:  10%|█████████▍                                                                                    | 15/149 [00:11<01:36,  1.39it/s, avg=0.12469, loss=0.12507]

trial_002 train e001:  11%|██████████                                                                                    | 16/149 [00:11<01:37,  1.37it/s, avg=0.12469, loss=0.12507]

trial_002 train e001:  11%|██████████                                                                                    | 16/149 [00:12<01:37,  1.37it/s, avg=0.12478, loss=0.12629]

trial_002 train e001:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.39it/s, avg=0.12478, loss=0.12629]

trial_002 train e001:  11%|██████████▋                                                                                   | 17/149 [00:13<01:35,  1.39it/s, avg=0.12493, loss=0.12744]

trial_002 train e001:  12%|███████████▎                                                                                  | 18/149 [00:13<01:33,  1.40it/s, avg=0.12493, loss=0.12744]

trial_002 train e001:  12%|███████████▎                                                                                  | 18/149 [00:13<01:33,  1.40it/s, avg=0.12536, loss=0.13306]

trial_002 train e001:  13%|███████████▉                                                                                  | 19/149 [00:13<01:31,  1.43it/s, avg=0.12536, loss=0.13306]

trial_002 train e001:  13%|███████████▉                                                                                  | 19/149 [00:14<01:31,  1.43it/s, avg=0.12553, loss=0.12872]

trial_002 train e001:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.40it/s, avg=0.12553, loss=0.12872]

trial_002 train e001:  13%|████████████▌                                                                                 | 20/149 [00:15<01:31,  1.40it/s, avg=0.12590, loss=0.13345]

trial_002 train e001:  14%|█████████████▏                                                                                | 21/149 [00:15<01:29,  1.43it/s, avg=0.12590, loss=0.13345]

trial_002 train e001:  14%|█████████████▏                                                                                | 21/149 [00:15<01:29,  1.43it/s, avg=0.12594, loss=0.12679]

trial_002 train e001:  15%|█████████████▉                                                                                | 22/149 [00:15<01:27,  1.45it/s, avg=0.12594, loss=0.12679]

trial_002 train e001:  15%|█████████████▉                                                                                | 22/149 [00:16<01:27,  1.45it/s, avg=0.12591, loss=0.12517]

trial_002 train e001:  15%|██████████████▌                                                                               | 23/149 [00:16<01:28,  1.42it/s, avg=0.12591, loss=0.12517]

trial_002 train e001:  15%|██████████████▌                                                                               | 23/149 [00:17<01:28,  1.42it/s, avg=0.12535, loss=0.11244]

trial_002 train e001:  16%|███████████████▏                                                                              | 24/149 [00:17<01:29,  1.40it/s, avg=0.12535, loss=0.11244]

trial_002 train e001:  16%|███████████████▏                                                                              | 24/149 [00:17<01:29,  1.40it/s, avg=0.12600, loss=0.14170]

trial_002 train e001:  17%|███████████████▊                                                                              | 25/149 [00:17<01:29,  1.39it/s, avg=0.12600, loss=0.14170]

trial_002 train e001:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.39it/s, avg=0.12581, loss=0.12103]

trial_002 train e001:  17%|████████████████▍                                                                             | 26/149 [00:18<01:28,  1.39it/s, avg=0.12581, loss=0.12103]

trial_002 train e001:  17%|████████████████▍                                                                             | 26/149 [00:19<01:28,  1.39it/s, avg=0.12519, loss=0.10903]

trial_002 train e001:  18%|█████████████████                                                                             | 27/149 [00:19<01:29,  1.37it/s, avg=0.12519, loss=0.10903]

trial_002 train e001:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.37it/s, avg=0.12469, loss=0.11110]

trial_002 train e001:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.37it/s, avg=0.12469, loss=0.11110]

trial_002 train e001:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.37it/s, avg=0.12477, loss=0.12710]

trial_002 train e001:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:27,  1.38it/s, avg=0.12477, loss=0.12710]

trial_002 train e001:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:27,  1.38it/s, avg=0.12441, loss=0.11387]

trial_002 train e001:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:27,  1.36it/s, avg=0.12441, loss=0.11387]

trial_002 train e001:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.36it/s, avg=0.12402, loss=0.11245]

trial_002 train e001:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:25,  1.37it/s, avg=0.12402, loss=0.11245]

trial_002 train e001:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:25,  1.37it/s, avg=0.12405, loss=0.12507]

trial_002 train e001:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.38it/s, avg=0.12405, loss=0.12507]

trial_002 train e001:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.38it/s, avg=0.12464, loss=0.14340]

trial_002 train e001:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:24,  1.37it/s, avg=0.12464, loss=0.14340]

trial_002 train e001:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.12413, loss=0.10725]

trial_002 train e001:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:23,  1.38it/s, avg=0.12413, loss=0.10725]

trial_002 train e001:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.38it/s, avg=0.12433, loss=0.13131]

trial_002 train e001:  23%|██████████████████████                                                                        | 35/149 [00:25<01:20,  1.42it/s, avg=0.12433, loss=0.13131]

trial_002 train e001:  23%|██████████████████████                                                                        | 35/149 [00:25<01:20,  1.42it/s, avg=0.12452, loss=0.13120]

trial_002 train e001:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:18,  1.43it/s, avg=0.12452, loss=0.13120]

trial_002 train e001:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:18,  1.43it/s, avg=0.12446, loss=0.12228]

trial_002 train e001:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:17,  1.45it/s, avg=0.12446, loss=0.12228]

trial_002 train e001:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:17,  1.45it/s, avg=0.12437, loss=0.12088]

trial_002 train e001:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:17,  1.44it/s, avg=0.12437, loss=0.12088]

trial_002 train e001:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:17,  1.44it/s, avg=0.12425, loss=0.11975]

trial_002 train e001:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:15,  1.45it/s, avg=0.12425, loss=0.11975]

trial_002 train e001:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:15,  1.45it/s, avg=0.12381, loss=0.10660]

trial_002 train e001:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:16,  1.42it/s, avg=0.12381, loss=0.10660]

trial_002 train e001:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:16,  1.42it/s, avg=0.12409, loss=0.13526]

trial_002 train e001:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:17,  1.40it/s, avg=0.12409, loss=0.13526]

trial_002 train e001:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.40it/s, avg=0.12436, loss=0.13559]

trial_002 train e001:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.12436, loss=0.13559]

trial_002 train e001:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.12467, loss=0.13743]

trial_002 train e001:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:14,  1.43it/s, avg=0.12467, loss=0.13743]

trial_002 train e001:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:14,  1.43it/s, avg=0.12419, loss=0.10347]

trial_002 train e001:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:14,  1.42it/s, avg=0.12419, loss=0.10347]

trial_002 train e001:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.42it/s, avg=0.12393, loss=0.11261]

trial_002 train e001:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.12393, loss=0.11261]

trial_002 train e001:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.12373, loss=0.11497]

trial_002 train e001:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:13,  1.41it/s, avg=0.12373, loss=0.11497]

trial_002 train e001:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:13,  1.41it/s, avg=0.12381, loss=0.12715]

trial_002 train e001:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.41it/s, avg=0.12381, loss=0.12715]

trial_002 train e001:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:12,  1.41it/s, avg=0.12384, loss=0.12544]

trial_002 train e001:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.39it/s, avg=0.12384, loss=0.12544]

trial_002 train e001:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:12,  1.39it/s, avg=0.12349, loss=0.10687]

trial_002 train e001:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:10,  1.42it/s, avg=0.12349, loss=0.10687]

trial_002 train e001:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:10,  1.42it/s, avg=0.12376, loss=0.13704]

trial_002 train e001:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:11,  1.39it/s, avg=0.12376, loss=0.13704]

trial_002 train e001:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:11,  1.39it/s, avg=0.12402, loss=0.13683]

trial_002 train e001:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:09,  1.40it/s, avg=0.12402, loss=0.13683]

trial_002 train e001:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:09,  1.40it/s, avg=0.12403, loss=0.12429]

trial_002 train e001:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.39it/s, avg=0.12403, loss=0.12429]

trial_002 train e001:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.39it/s, avg=0.12391, loss=0.11784]

trial_002 train e001:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:08,  1.41it/s, avg=0.12391, loss=0.11784]

trial_002 train e001:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:08,  1.41it/s, avg=0.12397, loss=0.12697]

trial_002 train e001:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:07,  1.40it/s, avg=0.12397, loss=0.12697]

trial_002 train e001:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:07,  1.40it/s, avg=0.12374, loss=0.11161]

trial_002 train e001:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.37it/s, avg=0.12374, loss=0.11161]

trial_002 train e001:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.12348, loss=0.10901]

trial_002 train e001:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:14,  1.25it/s, avg=0.12348, loss=0.10901]

trial_002 train e001:  38%|███████████████████████████████████▎                                                          | 56/149 [00:43<01:14,  1.25it/s, avg=0.12353, loss=0.12621]

trial_002 train e001:  38%|███████████████████████████████████▉                                                          | 57/149 [00:43<02:08,  1.39s/it, avg=0.12353, loss=0.12621]

trial_002 train e001:  38%|███████████████████████████████████▉                                                          | 57/149 [00:45<02:08,  1.39s/it, avg=0.12392, loss=0.14620]

trial_002 train e001:  39%|████████████████████████████████████▌                                                         | 58/149 [00:45<02:39,  1.75s/it, avg=0.12392, loss=0.14620]

trial_002 train e001:  39%|████████████████████████████████████▌                                                         | 58/149 [00:50<02:39,  1.75s/it, avg=0.12389, loss=0.12245]

trial_002 train e001:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:50<04:03,  2.70s/it, avg=0.12389, loss=0.12245]

trial_002 train e001:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:55<04:03,  2.70s/it, avg=0.12381, loss=0.11912]

trial_002 train e001:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:55<04:55,  3.32s/it, avg=0.12381, loss=0.11912]

trial_002 train e001:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:57<04:55,  3.32s/it, avg=0.12379, loss=0.12221]

trial_002 train e001:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:57<04:05,  2.79s/it, avg=0.12379, loss=0.12221]

trial_002 train e001:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:57<04:05,  2.79s/it, avg=0.12372, loss=0.11937]

trial_002 train e001:  42%|███████████████████████████████████████                                                       | 62/149 [00:57<03:09,  2.18s/it, avg=0.12372, loss=0.11937]

trial_002 train e001:  42%|███████████████████████████████████████                                                       | 62/149 [00:58<03:09,  2.18s/it, avg=0.12345, loss=0.10676]

trial_002 train e001:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:58<02:29,  1.74s/it, avg=0.12345, loss=0.10676]

trial_002 train e001:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:59<02:29,  1.74s/it, avg=0.12368, loss=0.13864]

trial_002 train e001:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:59<02:02,  1.44s/it, avg=0.12368, loss=0.13864]

trial_002 train e001:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:59<02:02,  1.44s/it, avg=0.12404, loss=0.14659]

trial_002 train e001:  44%|█████████████████████████████████████████                                                     | 65/149 [00:59<01:42,  1.22s/it, avg=0.12404, loss=0.14659]

trial_002 train e001:  44%|█████████████████████████████████████████                                                     | 65/149 [01:00<01:42,  1.22s/it, avg=0.12386, loss=0.11234]

trial_002 train e001:  44%|█████████████████████████████████████████▋                                                    | 66/149 [01:00<01:29,  1.08s/it, avg=0.12386, loss=0.11234]

trial_002 train e001:  44%|█████████████████████████████████████████▋                                                    | 66/149 [01:01<01:29,  1.08s/it, avg=0.12410, loss=0.13989]

trial_002 train e001:  45%|██████████████████████████████████████████▎                                                   | 67/149 [01:01<01:20,  1.02it/s, avg=0.12410, loss=0.13989]

trial_002 train e001:  45%|██████████████████████████████████████████▎                                                   | 67/149 [01:02<01:20,  1.02it/s, avg=0.12377, loss=0.10206]

trial_002 train e001:  46%|██████████████████████████████████████████▉                                                   | 68/149 [01:02<01:14,  1.09it/s, avg=0.12377, loss=0.10206]

trial_002 train e001:  46%|██████████████████████████████████████████▉                                                   | 68/149 [01:02<01:14,  1.09it/s, avg=0.12387, loss=0.13066]

trial_002 train e001:  46%|███████████████████████████████████████████▌                                                  | 69/149 [01:02<01:09,  1.16it/s, avg=0.12387, loss=0.13066]

trial_002 train e001:  46%|███████████████████████████████████████████▌                                                  | 69/149 [01:03<01:09,  1.16it/s, avg=0.12377, loss=0.11676]

trial_002 train e001:  47%|████████████████████████████████████████████▏                                                 | 70/149 [01:03<01:06,  1.19it/s, avg=0.12377, loss=0.11676]

trial_002 train e001:  47%|████████████████████████████████████████████▏                                                 | 70/149 [01:04<01:06,  1.19it/s, avg=0.12373, loss=0.12064]

trial_002 train e001:  48%|████████████████████████████████████████████▊                                                 | 71/149 [01:04<01:02,  1.24it/s, avg=0.12373, loss=0.12064]

trial_002 train e001:  48%|████████████████████████████████████████████▊                                                 | 71/149 [01:05<01:02,  1.24it/s, avg=0.12417, loss=0.15547]

trial_002 train e001:  48%|█████████████████████████████████████████████▍                                                | 72/149 [01:05<00:59,  1.29it/s, avg=0.12417, loss=0.15547]

trial_002 train e001:  48%|█████████████████████████████████████████████▍                                                | 72/149 [01:05<00:59,  1.29it/s, avg=0.12415, loss=0.12258]

trial_002 train e001:  49%|██████████████████████████████████████████████                                                | 73/149 [01:05<00:57,  1.31it/s, avg=0.12415, loss=0.12258]

trial_002 train e001:  49%|██████████████████████████████████████████████                                                | 73/149 [01:06<00:57,  1.31it/s, avg=0.12414, loss=0.12386]

trial_002 train e001:  50%|██████████████████████████████████████████████▋                                               | 74/149 [01:06<00:56,  1.32it/s, avg=0.12414, loss=0.12386]

trial_002 train e001:  50%|██████████████████████████████████████████████▋                                               | 74/149 [01:07<00:56,  1.32it/s, avg=0.12441, loss=0.14443]

trial_002 train e001:  50%|███████████████████████████████████████████████▎                                              | 75/149 [01:07<00:54,  1.35it/s, avg=0.12441, loss=0.14443]

trial_002 train e001:  50%|███████████████████████████████████████████████▎                                              | 75/149 [01:08<00:54,  1.35it/s, avg=0.12445, loss=0.12698]

trial_002 train e001:  51%|███████████████████████████████████████████████▉                                              | 76/149 [01:08<00:52,  1.39it/s, avg=0.12445, loss=0.12698]

trial_002 train e001:  51%|███████████████████████████████████████████████▉                                              | 76/149 [01:08<00:52,  1.39it/s, avg=0.12432, loss=0.11456]

trial_002 train e001:  52%|████████████████████████████████████████████████▌                                             | 77/149 [01:08<00:53,  1.36it/s, avg=0.12432, loss=0.11456]

trial_002 train e001:  52%|████████████████████████████████████████████████▌                                             | 77/149 [01:09<00:53,  1.36it/s, avg=0.12431, loss=0.12324]

trial_002 train e001:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [01:09<00:52,  1.34it/s, avg=0.12431, loss=0.12324]

trial_002 train e001:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [01:10<00:52,  1.34it/s, avg=0.12437, loss=0.12948]

trial_002 train e001:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [01:10<00:52,  1.33it/s, avg=0.12437, loss=0.12948]

trial_002 train e001:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [01:11<00:52,  1.33it/s, avg=0.12446, loss=0.13148]

trial_002 train e001:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:11<00:52,  1.32it/s, avg=0.12446, loss=0.13148]

trial_002 train e001:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [01:11<00:52,  1.32it/s, avg=0.12459, loss=0.13522]

trial_002 train e001:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:11<00:50,  1.34it/s, avg=0.12459, loss=0.13522]

trial_002 train e001:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:12<00:50,  1.34it/s, avg=0.12450, loss=0.11725]

trial_002 train e001:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:12<00:50,  1.34it/s, avg=0.12450, loss=0.11725]

trial_002 train e001:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:13<00:50,  1.34it/s, avg=0.12429, loss=0.10670]

trial_002 train e001:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:13<00:49,  1.35it/s, avg=0.12429, loss=0.10670]

trial_002 train e001:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:14<00:49,  1.35it/s, avg=0.12422, loss=0.11856]

trial_002 train e001:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:14<00:48,  1.33it/s, avg=0.12422, loss=0.11856]

trial_002 train e001:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:14<00:48,  1.33it/s, avg=0.12412, loss=0.11608]

trial_002 train e001:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:14<00:48,  1.33it/s, avg=0.12412, loss=0.11608]

trial_002 train e001:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:15<00:48,  1.33it/s, avg=0.12448, loss=0.15429]

trial_002 train e001:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:15<00:46,  1.36it/s, avg=0.12448, loss=0.15429]

trial_002 train e001:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:16<00:46,  1.36it/s, avg=0.12440, loss=0.11806]

trial_002 train e001:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:16<00:45,  1.37it/s, avg=0.12440, loss=0.11806]

trial_002 train e001:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:16<00:45,  1.37it/s, avg=0.12441, loss=0.12485]

trial_002 train e001:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:16<00:43,  1.39it/s, avg=0.12441, loss=0.12485]

trial_002 train e001:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:17<00:43,  1.39it/s, avg=0.12419, loss=0.10498]

trial_002 train e001:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:17<00:43,  1.36it/s, avg=0.12419, loss=0.10498]

trial_002 train e001:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:18<00:43,  1.36it/s, avg=0.12412, loss=0.11777]

trial_002 train e001:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:18<00:42,  1.38it/s, avg=0.12412, loss=0.11777]

trial_002 train e001:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:19<00:42,  1.38it/s, avg=0.12380, loss=0.09515]

trial_002 train e001:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:19<00:44,  1.29it/s, avg=0.12380, loss=0.09515]

trial_002 train e001:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:20<00:44,  1.29it/s, avg=0.12386, loss=0.12967]

trial_002 train e001:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:20<00:44,  1.29it/s, avg=0.12386, loss=0.12967]

trial_002 train e001:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:21<00:44,  1.29it/s, avg=0.12387, loss=0.12473]

trial_002 train e001:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:21<00:57,  1.03s/it, avg=0.12387, loss=0.12473]

trial_002 train e001:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:22<00:57,  1.03s/it, avg=0.12388, loss=0.12489]

trial_002 train e001:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:22<01:01,  1.11s/it, avg=0.12388, loss=0.12489]

trial_002 train e001:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:26<01:01,  1.11s/it, avg=0.12373, loss=0.10933]

trial_002 train e001:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:26<01:41,  1.88s/it, avg=0.12373, loss=0.10933]

trial_002 train e001:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:35<01:41,  1.88s/it, avg=0.12386, loss=0.13586]

trial_002 train e001:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:35<03:33,  4.03s/it, avg=0.12386, loss=0.13586]

trial_002 train e001:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:38<03:33,  4.03s/it, avg=0.12379, loss=0.11734]

trial_002 train e001:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:38<03:15,  3.76s/it, avg=0.12379, loss=0.11734]

trial_002 train e001:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:39<03:15,  3.76s/it, avg=0.12378, loss=0.12259]

trial_002 train e001:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:39<02:31,  2.96s/it, avg=0.12378, loss=0.12259]

trial_002 train e001:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:40<02:31,  2.96s/it, avg=0.12375, loss=0.12109]

trial_002 train e001:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:40<01:54,  2.28s/it, avg=0.12375, loss=0.12109]

trial_002 train e001:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:41<01:54,  2.28s/it, avg=0.12378, loss=0.12661]

trial_002 train e001:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:41<01:29,  1.82s/it, avg=0.12378, loss=0.12661]

trial_002 train e001:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:42<01:29,  1.82s/it, avg=0.12372, loss=0.11746]

trial_002 train e001:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:42<01:12,  1.50s/it, avg=0.12372, loss=0.11746]

trial_002 train e001:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:42<01:12,  1.50s/it, avg=0.12348, loss=0.09973]

trial_002 train e001:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:42<00:59,  1.28s/it, avg=0.12348, loss=0.09973]

trial_002 train e001:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:43<00:59,  1.28s/it, avg=0.12353, loss=0.12889]

trial_002 train e001:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:43<00:51,  1.13s/it, avg=0.12353, loss=0.12889]

trial_002 train e001:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:44<00:51,  1.13s/it, avg=0.12345, loss=0.11463]

trial_002 train e001:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:44<00:45,  1.01s/it, avg=0.12345, loss=0.11463]

trial_002 train e001:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:45<00:45,  1.01s/it, avg=0.12333, loss=0.11078]

trial_002 train e001:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:45<00:40,  1.08it/s, avg=0.12333, loss=0.11078]

trial_002 train e001:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:45<00:40,  1.08it/s, avg=0.12337, loss=0.12799]

trial_002 train e001:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:45<00:37,  1.15it/s, avg=0.12337, loss=0.12799]

trial_002 train e001:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:46<00:37,  1.15it/s, avg=0.12335, loss=0.12150]

trial_002 train e001:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:46<00:34,  1.22it/s, avg=0.12335, loss=0.12150]

trial_002 train e001:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:47<00:34,  1.22it/s, avg=0.12342, loss=0.13057]

trial_002 train e001:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:47<00:32,  1.25it/s, avg=0.12342, loss=0.13057]

trial_002 train e001:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:49<00:32,  1.25it/s, avg=0.12331, loss=0.11142]

trial_002 train e001:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:49<00:42,  1.07s/it, avg=0.12331, loss=0.11142]

trial_002 train e001:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:49<00:42,  1.07s/it, avg=0.12323, loss=0.11407]

trial_002 train e001:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:49<00:37,  1.03it/s, avg=0.12323, loss=0.11407]

trial_002 train e001:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:50<00:37,  1.03it/s, avg=0.12328, loss=0.12934]

trial_002 train e001:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:50<00:34,  1.11it/s, avg=0.12328, loss=0.12934]

trial_002 train e001:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:51<00:34,  1.11it/s, avg=0.12325, loss=0.12005]

trial_002 train e001:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:51<00:31,  1.17it/s, avg=0.12325, loss=0.12005]

trial_002 train e001:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:52<00:31,  1.17it/s, avg=0.12319, loss=0.11589]

trial_002 train e001:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:52<00:29,  1.21it/s, avg=0.12319, loss=0.11589]

trial_002 train e001:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:52<00:29,  1.21it/s, avg=0.12306, loss=0.10838]

trial_002 train e001:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:52<00:27,  1.25it/s, avg=0.12306, loss=0.10838]

trial_002 train e001:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:53<00:27,  1.25it/s, avg=0.12296, loss=0.11196]

trial_002 train e001:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:53<00:26,  1.27it/s, avg=0.12296, loss=0.11196]

trial_002 train e001:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:54<00:26,  1.27it/s, avg=0.12301, loss=0.12906]

trial_002 train e001:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:54<00:25,  1.32it/s, avg=0.12301, loss=0.12906]

trial_002 train e001:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:54<00:25,  1.32it/s, avg=0.12303, loss=0.12466]

trial_002 train e001:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:54<00:24,  1.32it/s, avg=0.12303, loss=0.12466]

trial_002 train e001:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:55<00:24,  1.32it/s, avg=0.12306, loss=0.12744]

trial_002 train e001:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:55<00:23,  1.33it/s, avg=0.12306, loss=0.12744]

trial_002 train e001:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:56<00:23,  1.33it/s, avg=0.12296, loss=0.11107]

trial_002 train e001:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:56<00:22,  1.35it/s, avg=0.12296, loss=0.11107]

trial_002 train e001:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:57<00:22,  1.35it/s, avg=0.12299, loss=0.12647]

trial_002 train e001:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:57<00:21,  1.36it/s, avg=0.12299, loss=0.12647]

trial_002 train e001:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:57<00:21,  1.36it/s, avg=0.12300, loss=0.12442]

trial_002 train e001:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:57<00:20,  1.37it/s, avg=0.12300, loss=0.12442]

trial_002 train e001:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:58<00:20,  1.37it/s, avg=0.12296, loss=0.11809]

trial_002 train e001:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:58<00:20,  1.32it/s, avg=0.12296, loss=0.11809]

trial_002 train e001:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:59<00:20,  1.32it/s, avg=0.12294, loss=0.11935]

trial_002 train e001:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:59<00:19,  1.31it/s, avg=0.12294, loss=0.11935]

trial_002 train e001:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [02:00<00:19,  1.31it/s, avg=0.12290, loss=0.11834]

trial_002 train e001:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [02:00<00:18,  1.35it/s, avg=0.12290, loss=0.11834]

trial_002 train e001:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [02:00<00:18,  1.35it/s, avg=0.12281, loss=0.11210]

trial_002 train e001:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [02:00<00:17,  1.36it/s, avg=0.12281, loss=0.11210]

trial_002 train e001:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [02:01<00:17,  1.36it/s, avg=0.12273, loss=0.11311]

trial_002 train e001:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [02:01<00:17,  1.35it/s, avg=0.12273, loss=0.11311]

trial_002 train e001:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [02:02<00:17,  1.35it/s, avg=0.12263, loss=0.10992]

trial_002 train e001:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [02:02<00:16,  1.35it/s, avg=0.12263, loss=0.10992]

trial_002 train e001:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [02:03<00:16,  1.35it/s, avg=0.12271, loss=0.13294]

trial_002 train e001:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [02:03<00:15,  1.37it/s, avg=0.12271, loss=0.13294]

trial_002 train e001:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [02:03<00:15,  1.37it/s, avg=0.12280, loss=0.13340]

trial_002 train e001:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [02:03<00:14,  1.36it/s, avg=0.12280, loss=0.13340]

trial_002 train e001:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [02:04<00:14,  1.36it/s, avg=0.12274, loss=0.11564]

trial_002 train e001:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [02:04<00:14,  1.33it/s, avg=0.12274, loss=0.11564]

trial_002 train e001:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [02:05<00:14,  1.33it/s, avg=0.12264, loss=0.10951]

trial_002 train e001:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [02:05<00:13,  1.33it/s, avg=0.12264, loss=0.10951]

trial_002 train e001:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [02:06<00:13,  1.33it/s, avg=0.12262, loss=0.11965]

trial_002 train e001:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [02:06<00:12,  1.32it/s, avg=0.12262, loss=0.11965]

trial_002 train e001:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [02:06<00:12,  1.32it/s, avg=0.12280, loss=0.14644]

trial_002 train e001:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [02:06<00:11,  1.35it/s, avg=0.12280, loss=0.14644]

trial_002 train e001:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [02:07<00:11,  1.35it/s, avg=0.12269, loss=0.10858]

trial_002 train e001:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [02:07<00:11,  1.34it/s, avg=0.12269, loss=0.10858]

trial_002 train e001:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [02:08<00:11,  1.34it/s, avg=0.12264, loss=0.11523]

trial_002 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [02:08<00:10,  1.35it/s, avg=0.12264, loss=0.11523]

trial_002 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [02:09<00:10,  1.35it/s, avg=0.12257, loss=0.11378]

trial_002 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [02:09<00:09,  1.34it/s, avg=0.12257, loss=0.11378]

trial_002 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [02:09<00:09,  1.34it/s, avg=0.12252, loss=0.11568]

trial_002 train e001:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [02:09<00:09,  1.27it/s, avg=0.12252, loss=0.11568]

trial_002 train e001:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [02:10<00:09,  1.27it/s, avg=0.12256, loss=0.12740]

trial_002 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [02:10<00:08,  1.31it/s, avg=0.12256, loss=0.12740]

trial_002 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [02:11<00:08,  1.31it/s, avg=0.12259, loss=0.12790]

trial_002 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [02:11<00:07,  1.34it/s, avg=0.12259, loss=0.12790]

trial_002 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [02:12<00:07,  1.34it/s, avg=0.12254, loss=0.11546]

trial_002 train e001:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [02:12<00:06,  1.35it/s, avg=0.12254, loss=0.11546]

trial_002 train e001:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [02:12<00:06,  1.35it/s, avg=0.12265, loss=0.13724]

trial_002 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [02:12<00:05,  1.36it/s, avg=0.12265, loss=0.13724]

trial_002 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [02:13<00:05,  1.36it/s, avg=0.12262, loss=0.11801]

trial_002 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [02:13<00:05,  1.38it/s, avg=0.12262, loss=0.11801]

trial_002 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [02:14<00:05,  1.38it/s, avg=0.12262, loss=0.12367]

trial_002 train e001:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [02:14<00:04,  1.38it/s, avg=0.12262, loss=0.12367]

trial_002 train e001:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [02:14<00:04,  1.38it/s, avg=0.12263, loss=0.12442]

trial_002 train e001:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [02:14<00:03,  1.39it/s, avg=0.12263, loss=0.12442]

trial_002 train e001:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [02:15<00:03,  1.39it/s, avg=0.12257, loss=0.11355]

trial_002 train e001:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [02:15<00:02,  1.37it/s, avg=0.12257, loss=0.11355]

trial_002 train e001:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [02:16<00:02,  1.37it/s, avg=0.12242, loss=0.10065]

trial_002 train e001:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [02:16<00:02,  1.39it/s, avg=0.12242, loss=0.10065]

trial_002 train e001:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [02:17<00:02,  1.39it/s, avg=0.12227, loss=0.09985]

trial_002 train e001:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [02:17<00:01,  1.37it/s, avg=0.12227, loss=0.09985]

trial_002 train e001:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [02:17<00:01,  1.37it/s, avg=0.12221, loss=0.11301]

trial_002 train e001:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [02:17<00:00,  1.36it/s, avg=0.12221, loss=0.11301]

trial_002 train e001:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [02:18<00:00,  1.36it/s, avg=0.12224, loss=0.13524]

trial_002 train e001: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [02:18<00:00,  1.66it/s, avg=0.12224, loss=0.13524]

trial_002 val e001:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e001:   2%|██▌                                                                                                                          | 1/50 [00:00<00:19,  2.48it/s]

trial_002 val e001:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.45it/s]

trial_002 val e001:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.45it/s]

trial_002 val e001:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.43it/s]

trial_002 val e001:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.43it/s]

trial_002 val e001:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.45it/s]

trial_002 val e001:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.47it/s]

trial_002 val e001:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:16,  2.49it/s]

trial_002 val e001:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.48it/s]

trial_002 val e001:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.48it/s]

trial_002 val e001:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.47it/s]

trial_002 val e001:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:16,  2.36it/s]

trial_002 val e001:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.35it/s]

trial_002 val e001:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:15,  2.38it/s]

trial_002 val e001:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.36it/s]

trial_002 val e001:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.37it/s]

trial_002 val e001:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.36it/s]

trial_002 val e001:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.37it/s]

trial_002 val e001:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:13,  2.37it/s]

trial_002 val e001:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.40it/s]

trial_002 val e001:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.38it/s]

trial_002 val e001:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.39it/s]

trial_002 val e001:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.40it/s]

trial_002 val e001:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.42it/s]

trial_002 val e001:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.44it/s]

trial_002 val e001:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.45it/s]

trial_002 val e001:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.45it/s]

trial_002 val e001:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.45it/s]

trial_002 val e001:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.46it/s]

trial_002 val e001:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.45it/s]

trial_002 val e001:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.41it/s]

trial_002 val e001:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:08,  2.23it/s]

trial_002 val e001:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.29it/s]

trial_002 val e001:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.33it/s]

trial_002 val e001:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.34it/s]

trial_002 val e001:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:05,  2.37it/s]

trial_002 val e001:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.37it/s]

trial_002 val e001:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:05,  2.38it/s]

trial_002 val e001:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.39it/s]

trial_002 val e001:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.40it/s]

trial_002 val e001:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.38it/s]

trial_002 val e001:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.35it/s]

trial_002 val e001:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.36it/s]

trial_002 val e001:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.35it/s]

trial_002 val e001:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.36it/s]

trial_002 val e001:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.33it/s]

trial_002 val e001:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.37it/s]

trial_002 val e001:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:20<00:00,  2.40it/s]

trial_002 val e001:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.42it/s]

trial_002 val e001: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.45it/s]

[2026-05-28 20:26:16] [trial_002] epoch=001 | train_loss=0.122241 | val_MAE=0.118787 | val_S=0.881213 | best_S=0.881213 @epoch=1 | patience=0/5

[trial_002] epochs:   1%|█▏                                                                                                                       | 1/100 [02:40<4:24:05, 160.05s/it]

trial_002 train e002:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e002:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.13009, loss=0.13009]

trial_002 train e002:   1%|▋                                                                                              | 1/149 [00:00<01:53,  1.30it/s, avg=0.13009, loss=0.13009]

trial_002 train e002:   1%|▋                                                                                              | 1/149 [00:01<01:53,  1.30it/s, avg=0.11985, loss=0.10962]

trial_002 train e002:   1%|█▎                                                                                             | 2/149 [00:01<01:51,  1.32it/s, avg=0.11985, loss=0.10962]

trial_002 train e002:   1%|█▎                                                                                             | 2/149 [00:02<01:51,  1.32it/s, avg=0.12140, loss=0.12449]

trial_002 train e002:   2%|█▉                                                                                             | 3/149 [00:02<01:52,  1.30it/s, avg=0.12140, loss=0.12449]

trial_002 train e002:   2%|█▉                                                                                             | 3/149 [00:03<01:52,  1.30it/s, avg=0.11801, loss=0.10786]

trial_002 train e002:   3%|██▌                                                                                            | 4/149 [00:03<01:50,  1.32it/s, avg=0.11801, loss=0.10786]

trial_002 train e002:   3%|██▌                                                                                            | 4/149 [00:03<01:50,  1.32it/s, avg=0.11778, loss=0.11684]

trial_002 train e002:   3%|███▏                                                                                           | 5/149 [00:03<01:48,  1.33it/s, avg=0.11778, loss=0.11684]

trial_002 train e002:   3%|███▏                                                                                           | 5/149 [00:04<01:48,  1.33it/s, avg=0.11838, loss=0.12141]

trial_002 train e002:   4%|███▊                                                                                           | 6/149 [00:04<01:43,  1.38it/s, avg=0.11838, loss=0.12141]

trial_002 train e002:   4%|███▊                                                                                           | 6/149 [00:05<01:43,  1.38it/s, avg=0.11985, loss=0.12868]

trial_002 train e002:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.11985, loss=0.12868]

trial_002 train e002:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.11887, loss=0.11198]

trial_002 train e002:   5%|█████                                                                                          | 8/149 [00:05<01:40,  1.41it/s, avg=0.11887, loss=0.11198]

trial_002 train e002:   5%|█████                                                                                          | 8/149 [00:06<01:40,  1.41it/s, avg=0.12035, loss=0.13222]

trial_002 train e002:   6%|█████▋                                                                                         | 9/149 [00:06<01:41,  1.38it/s, avg=0.12035, loss=0.13222]

trial_002 train e002:   6%|█████▋                                                                                         | 9/149 [00:07<01:41,  1.38it/s, avg=0.12007, loss=0.11751]

trial_002 train e002:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.12007, loss=0.11751]

trial_002 train e002:   7%|██████▎                                                                                       | 10/149 [00:08<01:39,  1.40it/s, avg=0.12066, loss=0.12651]

trial_002 train e002:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.40it/s, avg=0.12066, loss=0.12651]

trial_002 train e002:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.40it/s, avg=0.12087, loss=0.12321]

trial_002 train e002:   8%|███████▌                                                                                      | 12/149 [00:08<01:39,  1.38it/s, avg=0.12087, loss=0.12321]

trial_002 train e002:   8%|███████▌                                                                                      | 12/149 [00:09<01:39,  1.38it/s, avg=0.12140, loss=0.12777]

trial_002 train e002:   9%|████████▏                                                                                     | 13/149 [00:09<01:39,  1.37it/s, avg=0.12140, loss=0.12777]

trial_002 train e002:   9%|████████▏                                                                                     | 13/149 [00:10<01:39,  1.37it/s, avg=0.12052, loss=0.10906]

trial_002 train e002:   9%|████████▊                                                                                     | 14/149 [00:10<01:39,  1.35it/s, avg=0.12052, loss=0.10906]

trial_002 train e002:   9%|████████▊                                                                                     | 14/149 [00:11<01:39,  1.35it/s, avg=0.11959, loss=0.10664]

trial_002 train e002:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.34it/s, avg=0.11959, loss=0.10664]

trial_002 train e002:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.34it/s, avg=0.11874, loss=0.10600]

trial_002 train e002:  11%|██████████                                                                                    | 16/149 [00:11<01:37,  1.36it/s, avg=0.11874, loss=0.10600]

trial_002 train e002:  11%|██████████                                                                                    | 16/149 [00:12<01:37,  1.36it/s, avg=0.11906, loss=0.12409]

trial_002 train e002:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.35it/s, avg=0.11906, loss=0.12409]

trial_002 train e002:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.35it/s, avg=0.11871, loss=0.11286]

trial_002 train e002:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.11871, loss=0.11286]

trial_002 train e002:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.11939, loss=0.13158]

trial_002 train e002:  13%|███████████▉                                                                                  | 19/149 [00:13<01:33,  1.39it/s, avg=0.11939, loss=0.13158]

trial_002 train e002:  13%|███████████▉                                                                                  | 19/149 [00:14<01:33,  1.39it/s, avg=0.11936, loss=0.11883]

trial_002 train e002:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.38it/s, avg=0.11936, loss=0.11883]

trial_002 train e002:  13%|████████████▌                                                                                 | 20/149 [00:15<01:33,  1.38it/s, avg=0.11863, loss=0.10389]

trial_002 train e002:  14%|█████████████▏                                                                                | 21/149 [00:15<01:31,  1.40it/s, avg=0.11863, loss=0.10389]

trial_002 train e002:  14%|█████████████▏                                                                                | 21/149 [00:16<01:31,  1.40it/s, avg=0.11856, loss=0.11715]

trial_002 train e002:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.39it/s, avg=0.11856, loss=0.11715]

trial_002 train e002:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.39it/s, avg=0.11800, loss=0.10564]

trial_002 train e002:  15%|██████████████▌                                                                               | 23/149 [00:16<01:26,  1.45it/s, avg=0.11800, loss=0.10564]

trial_002 train e002:  15%|██████████████▌                                                                               | 23/149 [00:17<01:26,  1.45it/s, avg=0.11820, loss=0.12294]

trial_002 train e002:  16%|███████████████▏                                                                              | 24/149 [00:17<01:27,  1.42it/s, avg=0.11820, loss=0.12294]

trial_002 train e002:  16%|███████████████▏                                                                              | 24/149 [00:18<01:27,  1.42it/s, avg=0.11750, loss=0.10064]

trial_002 train e002:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.39it/s, avg=0.11750, loss=0.10064]

trial_002 train e002:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.39it/s, avg=0.11782, loss=0.12571]

trial_002 train e002:  17%|████████████████▍                                                                             | 26/149 [00:18<01:28,  1.40it/s, avg=0.11782, loss=0.12571]

trial_002 train e002:  17%|████████████████▍                                                                             | 26/149 [00:19<01:28,  1.40it/s, avg=0.11789, loss=0.11988]

trial_002 train e002:  18%|█████████████████                                                                             | 27/149 [00:19<01:28,  1.38it/s, avg=0.11789, loss=0.11988]

trial_002 train e002:  18%|█████████████████                                                                             | 27/149 [00:20<01:28,  1.38it/s, avg=0.11803, loss=0.12160]

trial_002 train e002:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:27,  1.38it/s, avg=0.11803, loss=0.12160]

trial_002 train e002:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:27,  1.38it/s, avg=0.11824, loss=0.12423]

trial_002 train e002:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.11824, loss=0.12423]

trial_002 train e002:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.11828, loss=0.11942]

trial_002 train e002:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:27,  1.36it/s, avg=0.11828, loss=0.11942]

trial_002 train e002:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.36it/s, avg=0.11807, loss=0.11170]

trial_002 train e002:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:26,  1.36it/s, avg=0.11807, loss=0.11170]

trial_002 train e002:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.36it/s, avg=0.11769, loss=0.10592]

trial_002 train e002:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.38it/s, avg=0.11769, loss=0.10592]

trial_002 train e002:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.38it/s, avg=0.11747, loss=0.11051]

trial_002 train e002:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:23,  1.38it/s, avg=0.11747, loss=0.11051]

trial_002 train e002:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:23,  1.38it/s, avg=0.11737, loss=0.11422]

trial_002 train e002:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:21,  1.41it/s, avg=0.11737, loss=0.11422]

trial_002 train e002:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:21,  1.41it/s, avg=0.11732, loss=0.11548]

trial_002 train e002:  23%|██████████████████████                                                                        | 35/149 [00:25<01:22,  1.38it/s, avg=0.11732, loss=0.11548]

trial_002 train e002:  23%|██████████████████████                                                                        | 35/149 [00:26<01:22,  1.38it/s, avg=0.11740, loss=0.12031]

trial_002 train e002:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.39it/s, avg=0.11740, loss=0.12031]

trial_002 train e002:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.39it/s, avg=0.11749, loss=0.12055]

trial_002 train e002:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:21,  1.38it/s, avg=0.11749, loss=0.12055]

trial_002 train e002:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:21,  1.38it/s, avg=0.11758, loss=0.12107]

trial_002 train e002:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:18,  1.41it/s, avg=0.11758, loss=0.12107]

trial_002 train e002:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:18,  1.41it/s, avg=0.11801, loss=0.13436]

trial_002 train e002:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:17,  1.42it/s, avg=0.11801, loss=0.13436]

trial_002 train e002:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:17,  1.42it/s, avg=0.11810, loss=0.12146]

trial_002 train e002:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.37it/s, avg=0.11810, loss=0.12146]

trial_002 train e002:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.37it/s, avg=0.11801, loss=0.11457]

trial_002 train e002:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:20,  1.33it/s, avg=0.11801, loss=0.11457]

trial_002 train e002:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:20,  1.33it/s, avg=0.11827, loss=0.12867]

trial_002 train e002:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:21,  1.32it/s, avg=0.11827, loss=0.12867]

trial_002 train e002:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:21,  1.32it/s, avg=0.11879, loss=0.14062]

trial_002 train e002:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:19,  1.33it/s, avg=0.11879, loss=0.14062]

trial_002 train e002:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:19,  1.33it/s, avg=0.11845, loss=0.10394]

trial_002 train e002:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.34it/s, avg=0.11845, loss=0.10394]

trial_002 train e002:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.34it/s, avg=0.11827, loss=0.11063]

trial_002 train e002:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:17,  1.34it/s, avg=0.11827, loss=0.11063]

trial_002 train e002:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:17,  1.34it/s, avg=0.11792, loss=0.10219]

trial_002 train e002:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:16,  1.35it/s, avg=0.11792, loss=0.10219]

trial_002 train e002:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:16,  1.35it/s, avg=0.11797, loss=0.12019]

trial_002 train e002:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:14,  1.36it/s, avg=0.11797, loss=0.12019]

trial_002 train e002:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:14,  1.36it/s, avg=0.11799, loss=0.11880]

trial_002 train e002:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.35it/s, avg=0.11799, loss=0.11880]

trial_002 train e002:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.35it/s, avg=0.11779, loss=0.10801]

trial_002 train e002:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:13,  1.35it/s, avg=0.11779, loss=0.10801]

trial_002 train e002:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:13,  1.35it/s, avg=0.11795, loss=0.12600]

trial_002 train e002:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:12,  1.37it/s, avg=0.11795, loss=0.12600]

trial_002 train e002:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:12,  1.37it/s, avg=0.11786, loss=0.11318]

trial_002 train e002:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:12,  1.36it/s, avg=0.11786, loss=0.11318]

trial_002 train e002:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:12,  1.36it/s, avg=0.11761, loss=0.10500]

trial_002 train e002:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:11,  1.36it/s, avg=0.11761, loss=0.10500]

trial_002 train e002:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:11,  1.36it/s, avg=0.11746, loss=0.10971]

trial_002 train e002:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:11,  1.35it/s, avg=0.11746, loss=0.10971]

trial_002 train e002:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:11,  1.35it/s, avg=0.11758, loss=0.12387]

trial_002 train e002:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.36it/s, avg=0.11758, loss=0.12387]

trial_002 train e002:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:09,  1.36it/s, avg=0.11743, loss=0.10925]

trial_002 train e002:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:10,  1.33it/s, avg=0.11743, loss=0.10925]

trial_002 train e002:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:10,  1.33it/s, avg=0.11735, loss=0.11287]

trial_002 train e002:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:12,  1.29it/s, avg=0.11735, loss=0.11287]

trial_002 train e002:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:12,  1.29it/s, avg=0.11743, loss=0.12212]

trial_002 train e002:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:10,  1.31it/s, avg=0.11743, loss=0.12212]

trial_002 train e002:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:10,  1.31it/s, avg=0.11745, loss=0.11864]

trial_002 train e002:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:09,  1.32it/s, avg=0.11745, loss=0.11864]

trial_002 train e002:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:09,  1.32it/s, avg=0.11754, loss=0.12267]

trial_002 train e002:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:07,  1.34it/s, avg=0.11754, loss=0.12267]

trial_002 train e002:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:07,  1.34it/s, avg=0.11762, loss=0.12251]

trial_002 train e002:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:05,  1.35it/s, avg=0.11762, loss=0.12251]

trial_002 train e002:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.35it/s, avg=0.11762, loss=0.11751]

trial_002 train e002:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:05,  1.35it/s, avg=0.11762, loss=0.11751]

trial_002 train e002:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:05,  1.35it/s, avg=0.11760, loss=0.11650]

trial_002 train e002:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:04,  1.36it/s, avg=0.11760, loss=0.11650]

trial_002 train e002:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.36it/s, avg=0.11775, loss=0.12668]

trial_002 train e002:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:05,  1.32it/s, avg=0.11775, loss=0.12668]

trial_002 train e002:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:05,  1.32it/s, avg=0.11782, loss=0.12232]

trial_002 train e002:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:03,  1.33it/s, avg=0.11782, loss=0.12232]

trial_002 train e002:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:03,  1.33it/s, avg=0.11801, loss=0.12996]

trial_002 train e002:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:01,  1.38it/s, avg=0.11801, loss=0.12996]

trial_002 train e002:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.38it/s, avg=0.11786, loss=0.10848]

trial_002 train e002:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:58,  1.42it/s, avg=0.11786, loss=0.10848]

trial_002 train e002:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<00:58,  1.42it/s, avg=0.11768, loss=0.10573]

trial_002 train e002:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.39it/s, avg=0.11768, loss=0.10573]

trial_002 train e002:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.39it/s, avg=0.11753, loss=0.10734]

trial_002 train e002:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:58,  1.39it/s, avg=0.11753, loss=0.10734]

trial_002 train e002:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:58,  1.39it/s, avg=0.11745, loss=0.11221]

trial_002 train e002:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:58,  1.37it/s, avg=0.11745, loss=0.11221]

trial_002 train e002:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.37it/s, avg=0.11740, loss=0.11400]

trial_002 train e002:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.34it/s, avg=0.11740, loss=0.11400]

trial_002 train e002:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:58,  1.34it/s, avg=0.11726, loss=0.10709]

trial_002 train e002:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.35it/s, avg=0.11726, loss=0.10709]

trial_002 train e002:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.35it/s, avg=0.11728, loss=0.11872]

trial_002 train e002:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:57,  1.33it/s, avg=0.11728, loss=0.11872]

trial_002 train e002:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:57,  1.33it/s, avg=0.11745, loss=0.13012]

trial_002 train e002:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:56,  1.36it/s, avg=0.11745, loss=0.13012]

trial_002 train e002:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:56,  1.36it/s, avg=0.11757, loss=0.12605]

trial_002 train e002:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:54,  1.37it/s, avg=0.11757, loss=0.12605]

trial_002 train e002:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:54,  1.37it/s, avg=0.11745, loss=0.10861]

trial_002 train e002:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:52,  1.40it/s, avg=0.11745, loss=0.10861]

trial_002 train e002:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:52,  1.40it/s, avg=0.11729, loss=0.10546]

trial_002 train e002:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:52,  1.40it/s, avg=0.11729, loss=0.10546]

trial_002 train e002:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:52,  1.40it/s, avg=0.11713, loss=0.10500]

trial_002 train e002:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:51,  1.39it/s, avg=0.11713, loss=0.10500]

trial_002 train e002:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:51,  1.39it/s, avg=0.11729, loss=0.12936]

trial_002 train e002:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.38it/s, avg=0.11729, loss=0.12936]

trial_002 train e002:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.38it/s, avg=0.11757, loss=0.13950]

trial_002 train e002:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:51,  1.37it/s, avg=0.11757, loss=0.13950]

trial_002 train e002:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:51,  1.37it/s, avg=0.11749, loss=0.11116]

trial_002 train e002:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.37it/s, avg=0.11749, loss=0.11116]

trial_002 train e002:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:50,  1.37it/s, avg=0.11745, loss=0.11446]

trial_002 train e002:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:49,  1.37it/s, avg=0.11745, loss=0.11446]

trial_002 train e002:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:49,  1.37it/s, avg=0.11743, loss=0.11553]

trial_002 train e002:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:49,  1.35it/s, avg=0.11743, loss=0.11553]

trial_002 train e002:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:49,  1.35it/s, avg=0.11760, loss=0.13196]

trial_002 train e002:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.37it/s, avg=0.11760, loss=0.13196]

trial_002 train e002:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:48,  1.37it/s, avg=0.11761, loss=0.11845]

trial_002 train e002:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:46,  1.39it/s, avg=0.11761, loss=0.11845]

trial_002 train e002:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:46,  1.39it/s, avg=0.11758, loss=0.11443]

trial_002 train e002:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:47,  1.36it/s, avg=0.11758, loss=0.11443]

trial_002 train e002:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:47,  1.36it/s, avg=0.11751, loss=0.11178]

trial_002 train e002:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:47,  1.34it/s, avg=0.11751, loss=0.11178]

trial_002 train e002:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:47,  1.34it/s, avg=0.11747, loss=0.11378]

trial_002 train e002:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:45,  1.35it/s, avg=0.11747, loss=0.11378]

trial_002 train e002:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:45,  1.35it/s, avg=0.11749, loss=0.11939]

trial_002 train e002:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.36it/s, avg=0.11749, loss=0.11939]

trial_002 train e002:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:44,  1.36it/s, avg=0.11742, loss=0.11164]

trial_002 train e002:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:42,  1.41it/s, avg=0.11742, loss=0.11164]

trial_002 train e002:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:42,  1.41it/s, avg=0.11743, loss=0.11778]

trial_002 train e002:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:42,  1.40it/s, avg=0.11743, loss=0.11778]

trial_002 train e002:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:42,  1.40it/s, avg=0.11743, loss=0.11751]

trial_002 train e002:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:41,  1.40it/s, avg=0.11743, loss=0.11751]

trial_002 train e002:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:41,  1.40it/s, avg=0.11743, loss=0.11794]

trial_002 train e002:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:40,  1.41it/s, avg=0.11743, loss=0.11794]

trial_002 train e002:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:40,  1.41it/s, avg=0.11747, loss=0.12119]

trial_002 train e002:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.37it/s, avg=0.11747, loss=0.12119]

trial_002 train e002:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.37it/s, avg=0.11749, loss=0.11952]

trial_002 train e002:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:40,  1.37it/s, avg=0.11749, loss=0.11952]

trial_002 train e002:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:40,  1.37it/s, avg=0.11727, loss=0.09597]

trial_002 train e002:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.35it/s, avg=0.11727, loss=0.09597]

trial_002 train e002:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:39,  1.35it/s, avg=0.11727, loss=0.11783]

trial_002 train e002:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.38it/s, avg=0.11727, loss=0.11783]

trial_002 train e002:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:38,  1.38it/s, avg=0.11728, loss=0.11793]

trial_002 train e002:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.35it/s, avg=0.11728, loss=0.11793]

trial_002 train e002:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.35it/s, avg=0.11719, loss=0.10858]

trial_002 train e002:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.36it/s, avg=0.11719, loss=0.10858]

trial_002 train e002:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.36it/s, avg=0.11717, loss=0.11507]

trial_002 train e002:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.11717, loss=0.11507]

trial_002 train e002:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.37it/s, avg=0.11725, loss=0.12523]

trial_002 train e002:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.35it/s, avg=0.11725, loss=0.12523]

trial_002 train e002:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.35it/s, avg=0.11725, loss=0.11704]

trial_002 train e002:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:35,  1.35it/s, avg=0.11725, loss=0.11704]

trial_002 train e002:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.35it/s, avg=0.11730, loss=0.12245]

trial_002 train e002:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:33,  1.39it/s, avg=0.11730, loss=0.12245]

trial_002 train e002:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:33,  1.39it/s, avg=0.11759, loss=0.14718]

trial_002 train e002:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:34,  1.35it/s, avg=0.11759, loss=0.14718]

trial_002 train e002:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:34,  1.35it/s, avg=0.11759, loss=0.11765]

trial_002 train e002:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:33,  1.34it/s, avg=0.11759, loss=0.11765]

trial_002 train e002:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:33,  1.34it/s, avg=0.11763, loss=0.12199]

trial_002 train e002:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:32,  1.33it/s, avg=0.11763, loss=0.12199]

trial_002 train e002:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.33it/s, avg=0.11771, loss=0.12543]

trial_002 train e002:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.35it/s, avg=0.11771, loss=0.12543]

trial_002 train e002:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:31,  1.35it/s, avg=0.11755, loss=0.10122]

trial_002 train e002:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.36it/s, avg=0.11755, loss=0.10122]

trial_002 train e002:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:30,  1.36it/s, avg=0.11741, loss=0.10235]

trial_002 train e002:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:29,  1.37it/s, avg=0.11741, loss=0.10235]

trial_002 train e002:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:29,  1.37it/s, avg=0.11742, loss=0.11870]

trial_002 train e002:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:29,  1.37it/s, avg=0.11742, loss=0.11870]

trial_002 train e002:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:29,  1.37it/s, avg=0.11757, loss=0.13392]

trial_002 train e002:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.38it/s, avg=0.11757, loss=0.13392]

trial_002 train e002:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:28,  1.38it/s, avg=0.11764, loss=0.12464]

trial_002 train e002:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.38it/s, avg=0.11764, loss=0.12464]

trial_002 train e002:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.38it/s, avg=0.11766, loss=0.12026]

trial_002 train e002:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:26,  1.38it/s, avg=0.11766, loss=0.12026]

trial_002 train e002:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:26,  1.38it/s, avg=0.11759, loss=0.10972]

trial_002 train e002:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.38it/s, avg=0.11759, loss=0.10972]

trial_002 train e002:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.38it/s, avg=0.11762, loss=0.12058]

trial_002 train e002:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.37it/s, avg=0.11762, loss=0.12058]

trial_002 train e002:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.37it/s, avg=0.11750, loss=0.10413]

trial_002 train e002:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.38it/s, avg=0.11750, loss=0.10413]

trial_002 train e002:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.38it/s, avg=0.11767, loss=0.13687]

trial_002 train e002:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.38it/s, avg=0.11767, loss=0.13687]

trial_002 train e002:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:23,  1.38it/s, avg=0.11760, loss=0.10986]

trial_002 train e002:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.38it/s, avg=0.11760, loss=0.10986]

trial_002 train e002:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.38it/s, avg=0.11768, loss=0.12693]

trial_002 train e002:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.37it/s, avg=0.11768, loss=0.12693]

trial_002 train e002:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:22,  1.37it/s, avg=0.11780, loss=0.13179]

trial_002 train e002:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.40it/s, avg=0.11780, loss=0.13179]

trial_002 train e002:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.40it/s, avg=0.11772, loss=0.10867]

trial_002 train e002:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:21,  1.37it/s, avg=0.11772, loss=0.10867]

trial_002 train e002:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.37it/s, avg=0.11757, loss=0.09981]

trial_002 train e002:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.36it/s, avg=0.11757, loss=0.09981]

trial_002 train e002:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.36it/s, avg=0.11768, loss=0.13005]

trial_002 train e002:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.36it/s, avg=0.11768, loss=0.13005]

trial_002 train e002:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:19,  1.36it/s, avg=0.11764, loss=0.11361]

trial_002 train e002:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.34it/s, avg=0.11764, loss=0.11361]

trial_002 train e002:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.34it/s, avg=0.11763, loss=0.11594]

trial_002 train e002:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.34it/s, avg=0.11763, loss=0.11594]

trial_002 train e002:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.34it/s, avg=0.11764, loss=0.11869]

trial_002 train e002:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.37it/s, avg=0.11764, loss=0.11869]

trial_002 train e002:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.37it/s, avg=0.11758, loss=0.11036]

trial_002 train e002:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.36it/s, avg=0.11758, loss=0.11036]

trial_002 train e002:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.36it/s, avg=0.11761, loss=0.12157]

trial_002 train e002:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.35it/s, avg=0.11761, loss=0.12157]

trial_002 train e002:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.35it/s, avg=0.11759, loss=0.11436]

trial_002 train e002:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.39it/s, avg=0.11759, loss=0.11436]

trial_002 train e002:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.39it/s, avg=0.11745, loss=0.10025]

trial_002 train e002:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.39it/s, avg=0.11745, loss=0.10025]

trial_002 train e002:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.39it/s, avg=0.11753, loss=0.12765]

trial_002 train e002:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.37it/s, avg=0.11753, loss=0.12765]

trial_002 train e002:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.37it/s, avg=0.11753, loss=0.11808]

trial_002 train e002:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.35it/s, avg=0.11753, loss=0.11808]

trial_002 train e002:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.35it/s, avg=0.11749, loss=0.11206]

trial_002 train e002:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.37it/s, avg=0.11749, loss=0.11206]

trial_002 train e002:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.37it/s, avg=0.11752, loss=0.12140]

trial_002 train e002:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.36it/s, avg=0.11752, loss=0.12140]

trial_002 train e002:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:11,  1.36it/s, avg=0.11762, loss=0.13041]

trial_002 train e002:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.38it/s, avg=0.11762, loss=0.13041]

trial_002 train e002:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.38it/s, avg=0.11759, loss=0.11436]

trial_002 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.40it/s, avg=0.11759, loss=0.11436]

trial_002 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.40it/s, avg=0.11749, loss=0.10404]

trial_002 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.39it/s, avg=0.11749, loss=0.10404]

trial_002 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.39it/s, avg=0.11737, loss=0.10122]

trial_002 train e002:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.38it/s, avg=0.11737, loss=0.10122]

trial_002 train e002:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.38it/s, avg=0.11742, loss=0.12366]

trial_002 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:08,  1.36it/s, avg=0.11742, loss=0.12366]

trial_002 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.36it/s, avg=0.11745, loss=0.12106]

trial_002 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.37it/s, avg=0.11745, loss=0.12106]

trial_002 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.37it/s, avg=0.11739, loss=0.10954]

trial_002 train e002:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.39it/s, avg=0.11739, loss=0.10954]

trial_002 train e002:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.39it/s, avg=0.11739, loss=0.11779]

trial_002 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.41it/s, avg=0.11739, loss=0.11779]

trial_002 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.41it/s, avg=0.11741, loss=0.11968]

trial_002 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:04,  1.42it/s, avg=0.11741, loss=0.11968]

trial_002 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:04,  1.42it/s, avg=0.11741, loss=0.11821]

trial_002 train e002:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.42it/s, avg=0.11741, loss=0.11821]

trial_002 train e002:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.42it/s, avg=0.11736, loss=0.10888]

trial_002 train e002:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.41it/s, avg=0.11736, loss=0.10888]

trial_002 train e002:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.41it/s, avg=0.11729, loss=0.10804]

trial_002 train e002:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.39it/s, avg=0.11729, loss=0.10804]

trial_002 train e002:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.39it/s, avg=0.11743, loss=0.13791]

trial_002 train e002:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.36it/s, avg=0.11743, loss=0.13791]

trial_002 train e002:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.36it/s, avg=0.11737, loss=0.10834]

trial_002 train e002:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.32it/s, avg=0.11737, loss=0.10834]

trial_002 train e002:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.32it/s, avg=0.11753, loss=0.14135]

trial_002 train e002:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.31it/s, avg=0.11753, loss=0.14135]

trial_002 train e002:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.31it/s, avg=0.11752, loss=0.11459]

trial_002 train e002: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.60it/s, avg=0.11752, loss=0.11459]

trial_002 val e002:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e002:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.43it/s]

trial_002 val e002:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.50it/s]

trial_002 val e002:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.40it/s]

trial_002 val e002:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.40it/s]

trial_002 val e002:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.43it/s]

trial_002 val e002:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.44it/s]

trial_002 val e002:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.44it/s]

trial_002 val e002:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.41it/s]

trial_002 val e002:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.44it/s]

trial_002 val e002:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.46it/s]

trial_002 val e002:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.48it/s]

trial_002 val e002:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.46it/s]

trial_002 val e002:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.42it/s]

trial_002 val e002:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.44it/s]

trial_002 val e002:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.44it/s]

trial_002 val e002:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.46it/s]

trial_002 val e002:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.46it/s]

trial_002 val e002:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.45it/s]

trial_002 val e002:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.47it/s]

trial_002 val e002:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.48it/s]

trial_002 val e002:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.47it/s]

trial_002 val e002:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.39it/s]

trial_002 val e002:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.40it/s]

trial_002 val e002:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.41it/s]

trial_002 val e002:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.44it/s]

trial_002 val e002:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.45it/s]

trial_002 val e002:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.46it/s]

trial_002 val e002:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.46it/s]

trial_002 val e002:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.47it/s]

trial_002 val e002:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.48it/s]

trial_002 val e002:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.48it/s]

trial_002 val e002:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.49it/s]

trial_002 val e002:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.50it/s]

trial_002 val e002:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.50it/s]

trial_002 val e002:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.47it/s]

trial_002 val e002:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.45it/s]

trial_002 val e002:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.45it/s]

trial_002 val e002:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.42it/s]

trial_002 val e002:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.42it/s]

trial_002 val e002:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.44it/s]

trial_002 val e002:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.46it/s]

trial_002 val e002:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.47it/s]

trial_002 val e002:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.48it/s]

trial_002 val e002:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.48it/s]

trial_002 val e002:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.49it/s]

trial_002 val e002:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.48it/s]

trial_002 val e002:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.47it/s]

trial_002 val e002:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.46it/s]

trial_002 val e002:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.43it/s]

trial_002 val e002: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.43it/s]

[2026-05-28 20:28:26] [trial_002] epoch=002 | train_loss=0.117525 | val_MAE=0.114336 | val_S=0.885664 | best_S=0.885664 @epoch=2 | patience=0/5

[trial_002] epochs:   2%|██▍                                                                                                                      | 2/100 [04:50<3:52:37, 142.42s/it]

trial_002 train e003:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e003:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10524, loss=0.10524]

trial_002 train e003:   1%|▋                                                                                              | 1/149 [00:00<01:52,  1.32it/s, avg=0.10524, loss=0.10524]

trial_002 train e003:   1%|▋                                                                                              | 1/149 [00:01<01:52,  1.32it/s, avg=0.11365, loss=0.12206]

trial_002 train e003:   1%|█▎                                                                                             | 2/149 [00:01<01:46,  1.38it/s, avg=0.11365, loss=0.12206]

trial_002 train e003:   1%|█▎                                                                                             | 2/149 [00:02<01:46,  1.38it/s, avg=0.11278, loss=0.11105]

trial_002 train e003:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.11278, loss=0.11105]

trial_002 train e003:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.11485, loss=0.12106]

trial_002 train e003:   3%|██▌                                                                                            | 4/149 [00:02<01:39,  1.45it/s, avg=0.11485, loss=0.12106]

trial_002 train e003:   3%|██▌                                                                                            | 4/149 [00:03<01:39,  1.45it/s, avg=0.11532, loss=0.11719]

trial_002 train e003:   3%|███▏                                                                                           | 5/149 [00:03<01:38,  1.46it/s, avg=0.11532, loss=0.11719]

trial_002 train e003:   3%|███▏                                                                                           | 5/149 [00:04<01:38,  1.46it/s, avg=0.11539, loss=0.11577]

trial_002 train e003:   4%|███▊                                                                                           | 6/149 [00:04<01:41,  1.41it/s, avg=0.11539, loss=0.11577]

trial_002 train e003:   4%|███▊                                                                                           | 6/149 [00:04<01:41,  1.41it/s, avg=0.11533, loss=0.11497]

trial_002 train e003:   5%|████▍                                                                                          | 7/149 [00:04<01:40,  1.41it/s, avg=0.11533, loss=0.11497]

trial_002 train e003:   5%|████▍                                                                                          | 7/149 [00:05<01:40,  1.41it/s, avg=0.11601, loss=0.12074]

trial_002 train e003:   5%|█████                                                                                          | 8/149 [00:05<01:42,  1.37it/s, avg=0.11601, loss=0.12074]

trial_002 train e003:   5%|█████                                                                                          | 8/149 [00:06<01:42,  1.37it/s, avg=0.11641, loss=0.11963]

trial_002 train e003:   6%|█████▋                                                                                         | 9/149 [00:06<01:43,  1.36it/s, avg=0.11641, loss=0.11963]

trial_002 train e003:   6%|█████▋                                                                                         | 9/149 [00:07<01:43,  1.36it/s, avg=0.11653, loss=0.11762]

trial_002 train e003:   7%|██████▎                                                                                       | 10/149 [00:07<01:43,  1.34it/s, avg=0.11653, loss=0.11762]

trial_002 train e003:   7%|██████▎                                                                                       | 10/149 [00:08<01:43,  1.34it/s, avg=0.11569, loss=0.10726]

trial_002 train e003:   7%|██████▉                                                                                       | 11/149 [00:08<01:43,  1.34it/s, avg=0.11569, loss=0.10726]

trial_002 train e003:   7%|██████▉                                                                                       | 11/149 [00:08<01:43,  1.34it/s, avg=0.11509, loss=0.10852]

trial_002 train e003:   8%|███████▌                                                                                      | 12/149 [00:08<01:41,  1.35it/s, avg=0.11509, loss=0.10852]

trial_002 train e003:   8%|███████▌                                                                                      | 12/149 [00:09<01:41,  1.35it/s, avg=0.11421, loss=0.10359]

trial_002 train e003:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.11421, loss=0.10359]

trial_002 train e003:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.11435, loss=0.11615]

trial_002 train e003:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.40it/s, avg=0.11435, loss=0.11615]

trial_002 train e003:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.40it/s, avg=0.11413, loss=0.11108]

trial_002 train e003:  10%|█████████▍                                                                                    | 15/149 [00:10<01:35,  1.41it/s, avg=0.11413, loss=0.11108]

trial_002 train e003:  10%|█████████▍                                                                                    | 15/149 [00:11<01:35,  1.41it/s, avg=0.11489, loss=0.12631]

trial_002 train e003:  11%|██████████                                                                                    | 16/149 [00:11<01:34,  1.41it/s, avg=0.11489, loss=0.12631]

trial_002 train e003:  11%|██████████                                                                                    | 16/149 [00:12<01:34,  1.41it/s, avg=0.11461, loss=0.11010]

trial_002 train e003:  11%|██████████▋                                                                                   | 17/149 [00:12<01:31,  1.45it/s, avg=0.11461, loss=0.11010]

trial_002 train e003:  11%|██████████▋                                                                                   | 17/149 [00:12<01:31,  1.45it/s, avg=0.11540, loss=0.12887]

trial_002 train e003:  12%|███████████▎                                                                                  | 18/149 [00:12<01:32,  1.42it/s, avg=0.11540, loss=0.12887]

trial_002 train e003:  12%|███████████▎                                                                                  | 18/149 [00:13<01:32,  1.42it/s, avg=0.11522, loss=0.11191]

trial_002 train e003:  13%|███████████▉                                                                                  | 19/149 [00:13<01:31,  1.42it/s, avg=0.11522, loss=0.11191]

trial_002 train e003:  13%|███████████▉                                                                                  | 19/149 [00:14<01:31,  1.42it/s, avg=0.11528, loss=0.11656]

trial_002 train e003:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.39it/s, avg=0.11528, loss=0.11656]

trial_002 train e003:  13%|████████████▌                                                                                 | 20/149 [00:15<01:33,  1.39it/s, avg=0.11608, loss=0.13205]

trial_002 train e003:  14%|█████████████▏                                                                                | 21/149 [00:15<01:33,  1.36it/s, avg=0.11608, loss=0.13205]

trial_002 train e003:  14%|█████████████▏                                                                                | 21/149 [00:15<01:33,  1.36it/s, avg=0.11580, loss=0.11000]

trial_002 train e003:  15%|█████████████▉                                                                                | 22/149 [00:15<01:33,  1.36it/s, avg=0.11580, loss=0.11000]

trial_002 train e003:  15%|█████████████▉                                                                                | 22/149 [00:16<01:33,  1.36it/s, avg=0.11600, loss=0.12019]

trial_002 train e003:  15%|██████████████▌                                                                               | 23/149 [00:16<01:33,  1.34it/s, avg=0.11600, loss=0.12019]

trial_002 train e003:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.34it/s, avg=0.11554, loss=0.10504]

trial_002 train e003:  16%|███████████████▏                                                                              | 24/149 [00:17<01:33,  1.34it/s, avg=0.11554, loss=0.10504]

trial_002 train e003:  16%|███████████████▏                                                                              | 24/149 [00:18<01:33,  1.34it/s, avg=0.11564, loss=0.11808]

trial_002 train e003:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.36it/s, avg=0.11564, loss=0.11808]

trial_002 train e003:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.36it/s, avg=0.11548, loss=0.11143]

trial_002 train e003:  17%|████████████████▍                                                                             | 26/149 [00:18<01:31,  1.34it/s, avg=0.11548, loss=0.11143]

trial_002 train e003:  17%|████████████████▍                                                                             | 26/149 [00:19<01:31,  1.34it/s, avg=0.11594, loss=0.12786]

trial_002 train e003:  18%|█████████████████                                                                             | 27/149 [00:19<01:30,  1.35it/s, avg=0.11594, loss=0.12786]

trial_002 train e003:  18%|█████████████████                                                                             | 27/149 [00:20<01:30,  1.35it/s, avg=0.11570, loss=0.10932]

trial_002 train e003:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:29,  1.34it/s, avg=0.11570, loss=0.10932]

trial_002 train e003:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:29,  1.34it/s, avg=0.11509, loss=0.09788]

trial_002 train e003:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:30,  1.33it/s, avg=0.11509, loss=0.09788]

trial_002 train e003:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:30,  1.33it/s, avg=0.11495, loss=0.11088]

trial_002 train e003:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:30,  1.32it/s, avg=0.11495, loss=0.11088]

trial_002 train e003:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:30,  1.32it/s, avg=0.11510, loss=0.11984]

trial_002 train e003:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:26,  1.36it/s, avg=0.11510, loss=0.11984]

trial_002 train e003:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.36it/s, avg=0.11479, loss=0.10510]

trial_002 train e003:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.35it/s, avg=0.11479, loss=0.10510]

trial_002 train e003:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:26,  1.35it/s, avg=0.11475, loss=0.11332]

trial_002 train e003:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.11475, loss=0.11332]

trial_002 train e003:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.11450, loss=0.10638]

trial_002 train e003:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.11450, loss=0.10638]

trial_002 train e003:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.11418, loss=0.10323]

trial_002 train e003:  23%|██████████████████████                                                                        | 35/149 [00:25<01:22,  1.38it/s, avg=0.11418, loss=0.10323]

trial_002 train e003:  23%|██████████████████████                                                                        | 35/149 [00:26<01:22,  1.38it/s, avg=0.11412, loss=0.11210]

trial_002 train e003:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:22,  1.37it/s, avg=0.11412, loss=0.11210]

trial_002 train e003:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:22,  1.37it/s, avg=0.11412, loss=0.11401]

trial_002 train e003:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:22,  1.36it/s, avg=0.11412, loss=0.11401]

trial_002 train e003:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.36it/s, avg=0.11414, loss=0.11482]

trial_002 train e003:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.38it/s, avg=0.11414, loss=0.11482]

trial_002 train e003:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:20,  1.38it/s, avg=0.11380, loss=0.10094]

trial_002 train e003:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:17,  1.41it/s, avg=0.11380, loss=0.10094]

trial_002 train e003:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:17,  1.41it/s, avg=0.11390, loss=0.11783]

trial_002 train e003:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.11390, loss=0.11783]

trial_002 train e003:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.11428, loss=0.12931]

trial_002 train e003:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:15,  1.43it/s, avg=0.11428, loss=0.12931]

trial_002 train e003:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:15,  1.43it/s, avg=0.11478, loss=0.13527]

trial_002 train e003:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:14,  1.43it/s, avg=0.11478, loss=0.13527]

trial_002 train e003:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:14,  1.43it/s, avg=0.11485, loss=0.11798]

trial_002 train e003:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.41it/s, avg=0.11485, loss=0.11798]

trial_002 train e003:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.41it/s, avg=0.11498, loss=0.12039]

trial_002 train e003:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:16,  1.38it/s, avg=0.11498, loss=0.12039]

trial_002 train e003:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:16,  1.38it/s, avg=0.11502, loss=0.11682]

trial_002 train e003:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:16,  1.37it/s, avg=0.11502, loss=0.11682]

trial_002 train e003:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:16,  1.37it/s, avg=0.11538, loss=0.13163]

trial_002 train e003:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:15,  1.36it/s, avg=0.11538, loss=0.13163]

trial_002 train e003:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:15,  1.36it/s, avg=0.11517, loss=0.10544]

trial_002 train e003:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:14,  1.37it/s, avg=0.11517, loss=0.10544]

trial_002 train e003:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:14,  1.37it/s, avg=0.11516, loss=0.11495]

trial_002 train e003:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.42it/s, avg=0.11516, loss=0.11495]

trial_002 train e003:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:11,  1.42it/s, avg=0.11538, loss=0.12594]

trial_002 train e003:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:10,  1.41it/s, avg=0.11538, loss=0.12594]

trial_002 train e003:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:10,  1.41it/s, avg=0.11545, loss=0.11871]

trial_002 train e003:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:10,  1.40it/s, avg=0.11545, loss=0.11871]

trial_002 train e003:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:10,  1.40it/s, avg=0.11517, loss=0.10104]

trial_002 train e003:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:10,  1.38it/s, avg=0.11517, loss=0.10104]

trial_002 train e003:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.38it/s, avg=0.11519, loss=0.11659]

trial_002 train e003:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:08,  1.41it/s, avg=0.11519, loss=0.11659]

trial_002 train e003:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:08,  1.41it/s, avg=0.11531, loss=0.12115]

trial_002 train e003:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:07,  1.42it/s, avg=0.11531, loss=0.12115]

trial_002 train e003:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:07,  1.42it/s, avg=0.11512, loss=0.10507]

trial_002 train e003:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:06,  1.43it/s, avg=0.11512, loss=0.10507]

trial_002 train e003:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:06,  1.43it/s, avg=0.11491, loss=0.10367]

trial_002 train e003:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:07,  1.40it/s, avg=0.11491, loss=0.10367]

trial_002 train e003:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:07,  1.40it/s, avg=0.11482, loss=0.11012]

trial_002 train e003:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.40it/s, avg=0.11482, loss=0.11012]

trial_002 train e003:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:06,  1.40it/s, avg=0.11485, loss=0.11654]

trial_002 train e003:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.41it/s, avg=0.11485, loss=0.11654]

trial_002 train e003:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.41it/s, avg=0.11461, loss=0.10061]

trial_002 train e003:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.38it/s, avg=0.11461, loss=0.10061]

trial_002 train e003:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:05,  1.38it/s, avg=0.11442, loss=0.10360]

trial_002 train e003:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:06,  1.36it/s, avg=0.11442, loss=0.10360]

trial_002 train e003:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.11448, loss=0.11776]

trial_002 train e003:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:05,  1.37it/s, avg=0.11448, loss=0.11776]

trial_002 train e003:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.37it/s, avg=0.11449, loss=0.11558]

trial_002 train e003:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.36it/s, avg=0.11449, loss=0.11558]

trial_002 train e003:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.36it/s, avg=0.11466, loss=0.12455]

trial_002 train e003:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:04,  1.35it/s, avg=0.11466, loss=0.12455]

trial_002 train e003:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:04,  1.35it/s, avg=0.11448, loss=0.10338]

trial_002 train e003:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:01,  1.39it/s, avg=0.11448, loss=0.10338]

trial_002 train e003:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:01,  1.39it/s, avg=0.11467, loss=0.12691]

trial_002 train e003:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:00,  1.39it/s, avg=0.11467, loss=0.12691]

trial_002 train e003:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:00,  1.39it/s, avg=0.11472, loss=0.11757]

trial_002 train e003:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.39it/s, avg=0.11472, loss=0.11757]

trial_002 train e003:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.39it/s, avg=0.11459, loss=0.10610]

trial_002 train e003:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.41it/s, avg=0.11459, loss=0.10610]

trial_002 train e003:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:58,  1.41it/s, avg=0.11466, loss=0.11970]

trial_002 train e003:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.41it/s, avg=0.11466, loss=0.11970]

trial_002 train e003:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.41it/s, avg=0.11459, loss=0.10982]

trial_002 train e003:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:57,  1.40it/s, avg=0.11459, loss=0.10982]

trial_002 train e003:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:57,  1.40it/s, avg=0.11462, loss=0.11654]

trial_002 train e003:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:55,  1.44it/s, avg=0.11462, loss=0.11654]

trial_002 train e003:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:55,  1.44it/s, avg=0.11477, loss=0.12552]

trial_002 train e003:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:54,  1.46it/s, avg=0.11477, loss=0.12552]

trial_002 train e003:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:54,  1.46it/s, avg=0.11479, loss=0.11597]

trial_002 train e003:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:52,  1.47it/s, avg=0.11479, loss=0.11597]

trial_002 train e003:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:52,  1.47it/s, avg=0.11469, loss=0.10730]

trial_002 train e003:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:53,  1.43it/s, avg=0.11469, loss=0.10730]

trial_002 train e003:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:53,  1.43it/s, avg=0.11463, loss=0.11034]

trial_002 train e003:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:53,  1.41it/s, avg=0.11463, loss=0.11034]

trial_002 train e003:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:53,  1.41it/s, avg=0.11461, loss=0.11356]

trial_002 train e003:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.40it/s, avg=0.11461, loss=0.11356]

trial_002 train e003:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:53,  1.40it/s, avg=0.11442, loss=0.10038]

trial_002 train e003:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.39it/s, avg=0.11442, loss=0.10038]

trial_002 train e003:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.39it/s, avg=0.11442, loss=0.11396]

trial_002 train e003:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:53,  1.37it/s, avg=0.11442, loss=0.11396]

trial_002 train e003:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:53,  1.37it/s, avg=0.11428, loss=0.10351]

trial_002 train e003:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:51,  1.39it/s, avg=0.11428, loss=0.10351]

trial_002 train e003:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:51,  1.39it/s, avg=0.11430, loss=0.11612]

trial_002 train e003:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:50,  1.41it/s, avg=0.11430, loss=0.11612]

trial_002 train e003:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:50,  1.41it/s, avg=0.11403, loss=0.09318]

trial_002 train e003:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:48,  1.43it/s, avg=0.11403, loss=0.09318]

trial_002 train e003:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:48,  1.43it/s, avg=0.11422, loss=0.12926]

trial_002 train e003:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:48,  1.42it/s, avg=0.11422, loss=0.12926]

trial_002 train e003:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:48,  1.42it/s, avg=0.11416, loss=0.10893]

trial_002 train e003:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:48,  1.41it/s, avg=0.11416, loss=0.10893]

trial_002 train e003:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:48,  1.41it/s, avg=0.11406, loss=0.10623]

trial_002 train e003:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:47,  1.40it/s, avg=0.11406, loss=0.10623]

trial_002 train e003:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:47,  1.40it/s, avg=0.11400, loss=0.10926]

trial_002 train e003:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:47,  1.39it/s, avg=0.11400, loss=0.10926]

trial_002 train e003:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:47,  1.39it/s, avg=0.11404, loss=0.11682]

trial_002 train e003:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:46,  1.39it/s, avg=0.11404, loss=0.11682]

trial_002 train e003:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:46,  1.39it/s, avg=0.11393, loss=0.10473]

trial_002 train e003:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.39it/s, avg=0.11393, loss=0.10473]

trial_002 train e003:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.39it/s, avg=0.11384, loss=0.10656]

trial_002 train e003:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.39it/s, avg=0.11384, loss=0.10656]

trial_002 train e003:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.39it/s, avg=0.11381, loss=0.11096]

trial_002 train e003:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.39it/s, avg=0.11381, loss=0.11096]

trial_002 train e003:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.39it/s, avg=0.11386, loss=0.11882]

trial_002 train e003:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.39it/s, avg=0.11386, loss=0.11882]

trial_002 train e003:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:43,  1.39it/s, avg=0.11367, loss=0.09690]

trial_002 train e003:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.38it/s, avg=0.11367, loss=0.09690]

trial_002 train e003:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.38it/s, avg=0.11395, loss=0.13812]

trial_002 train e003:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:43,  1.37it/s, avg=0.11395, loss=0.13812]

trial_002 train e003:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.37it/s, avg=0.11369, loss=0.09109]

trial_002 train e003:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.36it/s, avg=0.11369, loss=0.09109]

trial_002 train e003:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.36it/s, avg=0.11367, loss=0.11149]

trial_002 train e003:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.37it/s, avg=0.11367, loss=0.11149]

trial_002 train e003:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:41,  1.37it/s, avg=0.11357, loss=0.10445]

trial_002 train e003:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:41,  1.37it/s, avg=0.11357, loss=0.10445]

trial_002 train e003:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:41,  1.37it/s, avg=0.11364, loss=0.11959]

trial_002 train e003:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:39,  1.40it/s, avg=0.11364, loss=0.11959]

trial_002 train e003:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:39,  1.40it/s, avg=0.11358, loss=0.10879]

trial_002 train e003:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.38it/s, avg=0.11358, loss=0.10879]

trial_002 train e003:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.38it/s, avg=0.11371, loss=0.12551]

trial_002 train e003:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.37it/s, avg=0.11371, loss=0.12551]

trial_002 train e003:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.37it/s, avg=0.11377, loss=0.11963]

trial_002 train e003:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:36,  1.41it/s, avg=0.11377, loss=0.11963]

trial_002 train e003:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:36,  1.41it/s, avg=0.11362, loss=0.09869]

trial_002 train e003:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.39it/s, avg=0.11362, loss=0.09869]

trial_002 train e003:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:36,  1.39it/s, avg=0.11379, loss=0.13056]

trial_002 train e003:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:36,  1.37it/s, avg=0.11379, loss=0.13056]

trial_002 train e003:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.11374, loss=0.10868]

trial_002 train e003:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:36,  1.36it/s, avg=0.11374, loss=0.10868]

trial_002 train e003:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:36,  1.36it/s, avg=0.11390, loss=0.13028]

trial_002 train e003:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:35,  1.35it/s, avg=0.11390, loss=0.13028]

trial_002 train e003:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:35,  1.35it/s, avg=0.11368, loss=0.09187]

trial_002 train e003:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:34,  1.35it/s, avg=0.11368, loss=0.09187]

trial_002 train e003:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.35it/s, avg=0.11358, loss=0.10294]

trial_002 train e003:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:34,  1.35it/s, avg=0.11358, loss=0.10294]

trial_002 train e003:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:34,  1.35it/s, avg=0.11365, loss=0.12062]

trial_002 train e003:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:33,  1.36it/s, avg=0.11365, loss=0.12062]

trial_002 train e003:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:33,  1.36it/s, avg=0.11367, loss=0.11588]

trial_002 train e003:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:32,  1.36it/s, avg=0.11367, loss=0.11588]

trial_002 train e003:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:32,  1.36it/s, avg=0.11369, loss=0.11625]

trial_002 train e003:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:31,  1.38it/s, avg=0.11369, loss=0.11625]

trial_002 train e003:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.38it/s, avg=0.11372, loss=0.11623]

trial_002 train e003:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:30,  1.40it/s, avg=0.11372, loss=0.11623]

trial_002 train e003:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:30,  1.40it/s, avg=0.11354, loss=0.09518]

trial_002 train e003:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:29,  1.40it/s, avg=0.11354, loss=0.09518]

trial_002 train e003:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:29,  1.40it/s, avg=0.11350, loss=0.10885]

trial_002 train e003:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:28,  1.39it/s, avg=0.11350, loss=0.10885]

trial_002 train e003:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:28,  1.39it/s, avg=0.11354, loss=0.11770]

trial_002 train e003:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:28,  1.39it/s, avg=0.11354, loss=0.11770]

trial_002 train e003:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.39it/s, avg=0.11363, loss=0.12337]

trial_002 train e003:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.38it/s, avg=0.11363, loss=0.12337]

trial_002 train e003:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.38it/s, avg=0.11364, loss=0.11457]

trial_002 train e003:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.41it/s, avg=0.11364, loss=0.11457]

trial_002 train e003:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:26,  1.41it/s, avg=0.11357, loss=0.10603]

trial_002 train e003:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.40it/s, avg=0.11357, loss=0.10603]

trial_002 train e003:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:25,  1.40it/s, avg=0.11362, loss=0.11894]

trial_002 train e003:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:24,  1.40it/s, avg=0.11362, loss=0.11894]

trial_002 train e003:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:24,  1.40it/s, avg=0.11359, loss=0.11073]

trial_002 train e003:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:24,  1.40it/s, avg=0.11359, loss=0.11073]

trial_002 train e003:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.40it/s, avg=0.11343, loss=0.09487]

trial_002 train e003:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.39it/s, avg=0.11343, loss=0.09487]

trial_002 train e003:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.39it/s, avg=0.11336, loss=0.10504]

trial_002 train e003:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:23,  1.37it/s, avg=0.11336, loss=0.10504]

trial_002 train e003:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.37it/s, avg=0.11324, loss=0.09898]

trial_002 train e003:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.35it/s, avg=0.11324, loss=0.09898]

trial_002 train e003:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.35it/s, avg=0.11319, loss=0.10728]

trial_002 train e003:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:22,  1.34it/s, avg=0.11319, loss=0.10728]

trial_002 train e003:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:22,  1.34it/s, avg=0.11317, loss=0.11163]

trial_002 train e003:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:21,  1.36it/s, avg=0.11317, loss=0.11163]

trial_002 train e003:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:21,  1.36it/s, avg=0.11307, loss=0.10019]

trial_002 train e003:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:20,  1.36it/s, avg=0.11307, loss=0.10019]

trial_002 train e003:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.36it/s, avg=0.11297, loss=0.10129]

trial_002 train e003:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:20,  1.34it/s, avg=0.11297, loss=0.10129]

trial_002 train e003:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:20,  1.34it/s, avg=0.11293, loss=0.10836]

trial_002 train e003:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:19,  1.35it/s, avg=0.11293, loss=0.10836]

trial_002 train e003:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:19,  1.35it/s, avg=0.11285, loss=0.10265]

trial_002 train e003:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:18,  1.36it/s, avg=0.11285, loss=0.10265]

trial_002 train e003:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.36it/s, avg=0.11294, loss=0.12440]

trial_002 train e003:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:17,  1.39it/s, avg=0.11294, loss=0.12440]

trial_002 train e003:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.39it/s, avg=0.11290, loss=0.10797]

trial_002 train e003:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.37it/s, avg=0.11290, loss=0.10797]

trial_002 train e003:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.37it/s, avg=0.11277, loss=0.09575]

trial_002 train e003:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:16,  1.37it/s, avg=0.11277, loss=0.09575]

trial_002 train e003:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:16,  1.37it/s, avg=0.11269, loss=0.10249]

trial_002 train e003:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.38it/s, avg=0.11269, loss=0.10249]

trial_002 train e003:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.38it/s, avg=0.11269, loss=0.11246]

trial_002 train e003:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.36it/s, avg=0.11269, loss=0.11246]

trial_002 train e003:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.36it/s, avg=0.11276, loss=0.12242]

trial_002 train e003:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.38it/s, avg=0.11276, loss=0.12242]

trial_002 train e003:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.38it/s, avg=0.11285, loss=0.12428]

trial_002 train e003:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:13,  1.35it/s, avg=0.11285, loss=0.12428]

trial_002 train e003:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.35it/s, avg=0.11277, loss=0.10254]

trial_002 train e003:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.38it/s, avg=0.11277, loss=0.10254]

trial_002 train e003:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.38it/s, avg=0.11266, loss=0.09799]

trial_002 train e003:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.35it/s, avg=0.11266, loss=0.09799]

trial_002 train e003:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.35it/s, avg=0.11261, loss=0.10616]

trial_002 train e003:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:11,  1.33it/s, avg=0.11261, loss=0.10616]

trial_002 train e003:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:11,  1.33it/s, avg=0.11260, loss=0.11145]

trial_002 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.35it/s, avg=0.11260, loss=0.11145]

trial_002 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.35it/s, avg=0.11257, loss=0.10887]

trial_002 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.36it/s, avg=0.11257, loss=0.10887]

trial_002 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.36it/s, avg=0.11250, loss=0.10281]

trial_002 train e003:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.34it/s, avg=0.11250, loss=0.10281]

trial_002 train e003:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.34it/s, avg=0.11245, loss=0.10537]

trial_002 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:08,  1.32it/s, avg=0.11245, loss=0.10537]

trial_002 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:08,  1.32it/s, avg=0.11229, loss=0.09057]

trial_002 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.35it/s, avg=0.11229, loss=0.09057]

trial_002 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.35it/s, avg=0.11231, loss=0.11429]

trial_002 train e003:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.35it/s, avg=0.11231, loss=0.11429]

trial_002 train e003:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.35it/s, avg=0.11230, loss=0.11108]

trial_002 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.35it/s, avg=0.11230, loss=0.11108]

trial_002 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.35it/s, avg=0.11223, loss=0.10317]

trial_002 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:05,  1.38it/s, avg=0.11223, loss=0.10317]

trial_002 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:05,  1.38it/s, avg=0.11226, loss=0.11583]

trial_002 train e003:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.37it/s, avg=0.11226, loss=0.11583]

trial_002 train e003:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.37it/s, avg=0.11221, loss=0.10517]

trial_002 train e003:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.36it/s, avg=0.11221, loss=0.10517]

trial_002 train e003:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.36it/s, avg=0.11215, loss=0.10390]

trial_002 train e003:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.36it/s, avg=0.11215, loss=0.10390]

trial_002 train e003:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.36it/s, avg=0.11207, loss=0.10028]

trial_002 train e003:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.36it/s, avg=0.11207, loss=0.10028]

trial_002 train e003:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.36it/s, avg=0.11201, loss=0.10281]

trial_002 train e003:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.37it/s, avg=0.11201, loss=0.10281]

trial_002 train e003:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.37it/s, avg=0.11212, loss=0.12828]

trial_002 train e003:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.34it/s, avg=0.11212, loss=0.12828]

trial_002 train e003:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.34it/s, avg=0.11210, loss=0.10396]

trial_002 train e003: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:47<00:00,  1.66it/s, avg=0.11210, loss=0.10396]

trial_002 val e003:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e003:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.30it/s]

trial_002 val e003:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.40it/s]

trial_002 val e003:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.42it/s]

trial_002 val e003:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.43it/s]

trial_002 val e003:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.43it/s]

trial_002 val e003:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.39it/s]

trial_002 val e003:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:18,  2.39it/s]

trial_002 val e003:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.40it/s]

trial_002 val e003:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.41it/s]

trial_002 val e003:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.38it/s]

trial_002 val e003:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.34it/s]

trial_002 val e003:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.35it/s]

trial_002 val e003:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.37it/s]

trial_002 val e003:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:15,  2.37it/s]

trial_002 val e003:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.40it/s]

trial_002 val e003:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.37it/s]

trial_002 val e003:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.38it/s]

trial_002 val e003:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.40it/s]

trial_002 val e003:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.41it/s]

trial_002 val e003:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.42it/s]

trial_002 val e003:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.40it/s]

trial_002 val e003:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.38it/s]

trial_002 val e003:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.37it/s]

trial_002 val e003:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:10,  2.37it/s]

trial_002 val e003:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.40it/s]

trial_002 val e003:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.37it/s]

trial_002 val e003:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.36it/s]

trial_002 val e003:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.38it/s]

trial_002 val e003:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:08,  2.39it/s]

trial_002 val e003:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.41it/s]

trial_002 val e003:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.40it/s]

trial_002 val e003:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.37it/s]

trial_002 val e003:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.39it/s]

trial_002 val e003:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.41it/s]

trial_002 val e003:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.42it/s]

trial_002 val e003:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:05,  2.42it/s]

trial_002 val e003:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.41it/s]

trial_002 val e003:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:05,  2.39it/s]

trial_002 val e003:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.40it/s]

trial_002 val e003:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.42it/s]

trial_002 val e003:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.43it/s]

trial_002 val e003:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.43it/s]

trial_002 val e003:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.44it/s]

trial_002 val e003:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.45it/s]

trial_002 val e003:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.42it/s]

trial_002 val e003:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.40it/s]

trial_002 val e003:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.39it/s]

trial_002 val e003:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:20<00:00,  2.41it/s]

trial_002 val e003:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.41it/s]

trial_002 val e003: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.42it/s]

[2026-05-28 20:30:36] [trial_002] epoch=003 | train_loss=0.112097 | val_MAE=0.107089 | val_S=0.892911 | best_S=0.892911 @epoch=3 | patience=0/5

[trial_002] epochs:   3%|███▋                                                                                                                     | 3/100 [06:59<3:40:47, 136.57s/it]

trial_002 train e004:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e004:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.11814, loss=0.11814]

trial_002 train e004:   1%|▋                                                                                              | 1/149 [00:00<01:44,  1.41it/s, avg=0.11814, loss=0.11814]

trial_002 train e004:   1%|▋                                                                                              | 1/149 [00:01<01:44,  1.41it/s, avg=0.11463, loss=0.11113]

trial_002 train e004:   1%|█▎                                                                                             | 2/149 [00:01<01:42,  1.43it/s, avg=0.11463, loss=0.11113]

trial_002 train e004:   1%|█▎                                                                                             | 2/149 [00:02<01:42,  1.43it/s, avg=0.12012, loss=0.13110]

trial_002 train e004:   2%|█▉                                                                                             | 3/149 [00:02<01:42,  1.43it/s, avg=0.12012, loss=0.13110]

trial_002 train e004:   2%|█▉                                                                                             | 3/149 [00:02<01:42,  1.43it/s, avg=0.11565, loss=0.10224]

trial_002 train e004:   3%|██▌                                                                                            | 4/149 [00:02<01:44,  1.39it/s, avg=0.11565, loss=0.10224]

trial_002 train e004:   3%|██▌                                                                                            | 4/149 [00:03<01:44,  1.39it/s, avg=0.11568, loss=0.11581]

trial_002 train e004:   3%|███▏                                                                                           | 5/149 [00:03<01:46,  1.36it/s, avg=0.11568, loss=0.11581]

trial_002 train e004:   3%|███▏                                                                                           | 5/149 [00:04<01:46,  1.36it/s, avg=0.11570, loss=0.11578]

trial_002 train e004:   4%|███▊                                                                                           | 6/149 [00:04<01:45,  1.36it/s, avg=0.11570, loss=0.11578]

trial_002 train e004:   4%|███▊                                                                                           | 6/149 [00:05<01:45,  1.36it/s, avg=0.11432, loss=0.10604]

trial_002 train e004:   5%|████▍                                                                                          | 7/149 [00:05<01:43,  1.37it/s, avg=0.11432, loss=0.10604]

trial_002 train e004:   5%|████▍                                                                                          | 7/149 [00:05<01:43,  1.37it/s, avg=0.11222, loss=0.09755]

trial_002 train e004:   5%|█████                                                                                          | 8/149 [00:05<01:42,  1.37it/s, avg=0.11222, loss=0.09755]

trial_002 train e004:   5%|█████                                                                                          | 8/149 [00:06<01:42,  1.37it/s, avg=0.11122, loss=0.10323]

trial_002 train e004:   6%|█████▋                                                                                         | 9/149 [00:06<01:41,  1.38it/s, avg=0.11122, loss=0.10323]

trial_002 train e004:   6%|█████▋                                                                                         | 9/149 [00:07<01:41,  1.38it/s, avg=0.11183, loss=0.11726]

trial_002 train e004:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.43it/s, avg=0.11183, loss=0.11726]

trial_002 train e004:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.43it/s, avg=0.11181, loss=0.11169]

trial_002 train e004:   7%|██████▉                                                                                       | 11/149 [00:07<01:37,  1.41it/s, avg=0.11181, loss=0.11169]

trial_002 train e004:   7%|██████▉                                                                                       | 11/149 [00:08<01:37,  1.41it/s, avg=0.11106, loss=0.10282]

trial_002 train e004:   8%|███████▌                                                                                      | 12/149 [00:08<01:39,  1.38it/s, avg=0.11106, loss=0.10282]

trial_002 train e004:   8%|███████▌                                                                                      | 12/149 [00:09<01:39,  1.38it/s, avg=0.10967, loss=0.09296]

trial_002 train e004:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.10967, loss=0.09296]

trial_002 train e004:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.10928, loss=0.10418]

trial_002 train e004:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.10928, loss=0.10418]

trial_002 train e004:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.10959, loss=0.11386]

trial_002 train e004:  10%|█████████▍                                                                                    | 15/149 [00:10<01:38,  1.37it/s, avg=0.10959, loss=0.11386]

trial_002 train e004:  10%|█████████▍                                                                                    | 15/149 [00:11<01:38,  1.37it/s, avg=0.11017, loss=0.11896]

trial_002 train e004:  11%|██████████                                                                                    | 16/149 [00:11<01:37,  1.37it/s, avg=0.11017, loss=0.11896]

trial_002 train e004:  11%|██████████                                                                                    | 16/149 [00:12<01:37,  1.37it/s, avg=0.11037, loss=0.11358]

trial_002 train e004:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.35it/s, avg=0.11037, loss=0.11358]

trial_002 train e004:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.35it/s, avg=0.10951, loss=0.09488]

trial_002 train e004:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.10951, loss=0.09488]

trial_002 train e004:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.10908, loss=0.10139]

trial_002 train e004:  13%|███████████▉                                                                                  | 19/149 [00:13<01:37,  1.34it/s, avg=0.10908, loss=0.10139]

trial_002 train e004:  13%|███████████▉                                                                                  | 19/149 [00:14<01:37,  1.34it/s, avg=0.10915, loss=0.11051]

trial_002 train e004:  13%|████████████▌                                                                                 | 20/149 [00:14<01:36,  1.34it/s, avg=0.10915, loss=0.11051]

trial_002 train e004:  13%|████████████▌                                                                                 | 20/149 [00:15<01:36,  1.34it/s, avg=0.10886, loss=0.10297]

trial_002 train e004:  14%|█████████████▏                                                                                | 21/149 [00:15<01:34,  1.35it/s, avg=0.10886, loss=0.10297]

trial_002 train e004:  14%|█████████████▏                                                                                | 21/149 [00:16<01:34,  1.35it/s, avg=0.10887, loss=0.10913]

trial_002 train e004:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.38it/s, avg=0.10887, loss=0.10913]

trial_002 train e004:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.38it/s, avg=0.10916, loss=0.11558]

trial_002 train e004:  15%|██████████████▌                                                                               | 23/149 [00:16<01:29,  1.41it/s, avg=0.10916, loss=0.11558]

trial_002 train e004:  15%|██████████████▌                                                                               | 23/149 [00:17<01:29,  1.41it/s, avg=0.10908, loss=0.10705]

trial_002 train e004:  16%|███████████████▏                                                                              | 24/149 [00:17<01:28,  1.42it/s, avg=0.10908, loss=0.10705]

trial_002 train e004:  16%|███████████████▏                                                                              | 24/149 [00:18<01:28,  1.42it/s, avg=0.10929, loss=0.11446]

trial_002 train e004:  17%|███████████████▊                                                                              | 25/149 [00:18<01:26,  1.43it/s, avg=0.10929, loss=0.11446]

trial_002 train e004:  17%|███████████████▊                                                                              | 25/149 [00:18<01:26,  1.43it/s, avg=0.10891, loss=0.09942]

trial_002 train e004:  17%|████████████████▍                                                                             | 26/149 [00:18<01:27,  1.41it/s, avg=0.10891, loss=0.09942]

trial_002 train e004:  17%|████████████████▍                                                                             | 26/149 [00:19<01:27,  1.41it/s, avg=0.10811, loss=0.08737]

trial_002 train e004:  18%|█████████████████                                                                             | 27/149 [00:19<01:27,  1.39it/s, avg=0.10811, loss=0.08737]

trial_002 train e004:  18%|█████████████████                                                                             | 27/149 [00:20<01:27,  1.39it/s, avg=0.10856, loss=0.12055]

trial_002 train e004:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:27,  1.39it/s, avg=0.10856, loss=0.12055]

trial_002 train e004:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:27,  1.39it/s, avg=0.10889, loss=0.11822]

trial_002 train e004:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:25,  1.40it/s, avg=0.10889, loss=0.11822]

trial_002 train e004:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:25,  1.40it/s, avg=0.10928, loss=0.12067]

trial_002 train e004:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:27,  1.36it/s, avg=0.10928, loss=0.12067]

trial_002 train e004:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.36it/s, avg=0.10912, loss=0.10428]

trial_002 train e004:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:25,  1.38it/s, avg=0.10912, loss=0.10428]

trial_002 train e004:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:25,  1.38it/s, avg=0.10884, loss=0.10008]

trial_002 train e004:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.39it/s, avg=0.10884, loss=0.10008]

trial_002 train e004:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.39it/s, avg=0.10881, loss=0.10793]

trial_002 train e004:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:24,  1.38it/s, avg=0.10881, loss=0.10793]

trial_002 train e004:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.38it/s, avg=0.10825, loss=0.08982]

trial_002 train e004:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:22,  1.40it/s, avg=0.10825, loss=0.08982]

trial_002 train e004:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:22,  1.40it/s, avg=0.10853, loss=0.11779]

trial_002 train e004:  23%|██████████████████████                                                                        | 35/149 [00:25<01:22,  1.37it/s, avg=0.10853, loss=0.11779]

trial_002 train e004:  23%|██████████████████████                                                                        | 35/149 [00:26<01:22,  1.37it/s, avg=0.10837, loss=0.10288]

trial_002 train e004:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:23,  1.36it/s, avg=0.10837, loss=0.10288]

trial_002 train e004:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:23,  1.36it/s, avg=0.10810, loss=0.09837]

trial_002 train e004:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:22,  1.35it/s, avg=0.10810, loss=0.09837]

trial_002 train e004:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.35it/s, avg=0.10790, loss=0.10074]

trial_002 train e004:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:21,  1.36it/s, avg=0.10790, loss=0.10074]

trial_002 train e004:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:21,  1.36it/s, avg=0.10784, loss=0.10548]

trial_002 train e004:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:18,  1.39it/s, avg=0.10784, loss=0.10548]

trial_002 train e004:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:18,  1.39it/s, avg=0.10805, loss=0.11606]

trial_002 train e004:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:18,  1.38it/s, avg=0.10805, loss=0.11606]

trial_002 train e004:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.38it/s, avg=0.10812, loss=0.11084]

trial_002 train e004:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:18,  1.38it/s, avg=0.10812, loss=0.11084]

trial_002 train e004:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:18,  1.38it/s, avg=0.10837, loss=0.11882]

trial_002 train e004:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.10837, loss=0.11882]

trial_002 train e004:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:17,  1.38it/s, avg=0.10832, loss=0.10597]

trial_002 train e004:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:16,  1.39it/s, avg=0.10832, loss=0.10597]

trial_002 train e004:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:16,  1.39it/s, avg=0.10798, loss=0.09353]

trial_002 train e004:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:16,  1.38it/s, avg=0.10798, loss=0.09353]

trial_002 train e004:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:16,  1.38it/s, avg=0.10816, loss=0.11604]

trial_002 train e004:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.40it/s, avg=0.10816, loss=0.11604]

trial_002 train e004:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:14,  1.40it/s, avg=0.10817, loss=0.10858]

trial_002 train e004:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:12,  1.42it/s, avg=0.10817, loss=0.10858]

trial_002 train e004:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:12,  1.42it/s, avg=0.10821, loss=0.11032]

trial_002 train e004:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.39it/s, avg=0.10821, loss=0.11032]

trial_002 train e004:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.39it/s, avg=0.10829, loss=0.11199]

trial_002 train e004:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:13,  1.38it/s, avg=0.10829, loss=0.11199]

trial_002 train e004:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:13,  1.38it/s, avg=0.10831, loss=0.10923]

trial_002 train e004:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.37it/s, avg=0.10831, loss=0.10923]

trial_002 train e004:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:12,  1.37it/s, avg=0.10823, loss=0.10402]

trial_002 train e004:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:13,  1.35it/s, avg=0.10823, loss=0.10402]

trial_002 train e004:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:13,  1.35it/s, avg=0.10807, loss=0.10011]

trial_002 train e004:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:12,  1.35it/s, avg=0.10807, loss=0.10011]

trial_002 train e004:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:12,  1.35it/s, avg=0.10792, loss=0.10042]

trial_002 train e004:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.40it/s, avg=0.10792, loss=0.10042]

trial_002 train e004:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:09,  1.40it/s, avg=0.10779, loss=0.10115]

trial_002 train e004:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:08,  1.40it/s, avg=0.10779, loss=0.10115]

trial_002 train e004:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:08,  1.40it/s, avg=0.10739, loss=0.08630]

trial_002 train e004:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.37it/s, avg=0.10739, loss=0.08630]

trial_002 train e004:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.37it/s, avg=0.10745, loss=0.11032]

trial_002 train e004:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.37it/s, avg=0.10745, loss=0.11032]

trial_002 train e004:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.10743, loss=0.10653]

trial_002 train e004:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:07,  1.39it/s, avg=0.10743, loss=0.10653]

trial_002 train e004:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.39it/s, avg=0.10716, loss=0.09186]

trial_002 train e004:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:06,  1.38it/s, avg=0.10716, loss=0.09186]

trial_002 train e004:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:06,  1.38it/s, avg=0.10722, loss=0.11073]

trial_002 train e004:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:05,  1.39it/s, avg=0.10722, loss=0.11073]

trial_002 train e004:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:05,  1.39it/s, avg=0.10709, loss=0.09960]

trial_002 train e004:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:04,  1.40it/s, avg=0.10709, loss=0.09960]

trial_002 train e004:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:04,  1.40it/s, avg=0.10699, loss=0.10135]

trial_002 train e004:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:04,  1.38it/s, avg=0.10699, loss=0.10135]

trial_002 train e004:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:04,  1.38it/s, avg=0.10701, loss=0.10800]

trial_002 train e004:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.37it/s, avg=0.10701, loss=0.10800]

trial_002 train e004:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.37it/s, avg=0.10702, loss=0.10731]

trial_002 train e004:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:03,  1.37it/s, avg=0.10702, loss=0.10731]

trial_002 train e004:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:03,  1.37it/s, avg=0.10689, loss=0.09885]

trial_002 train e004:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:03,  1.36it/s, avg=0.10689, loss=0.09885]

trial_002 train e004:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:03,  1.36it/s, avg=0.10676, loss=0.09868]

trial_002 train e004:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:02,  1.36it/s, avg=0.10676, loss=0.09868]

trial_002 train e004:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:02,  1.36it/s, avg=0.10668, loss=0.10160]

trial_002 train e004:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:02,  1.34it/s, avg=0.10668, loss=0.10160]

trial_002 train e004:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:02,  1.34it/s, avg=0.10670, loss=0.10807]

trial_002 train e004:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<01:02,  1.33it/s, avg=0.10670, loss=0.10807]

trial_002 train e004:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:02,  1.33it/s, avg=0.10661, loss=0.10090]

trial_002 train e004:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<01:01,  1.33it/s, avg=0.10661, loss=0.10090]

trial_002 train e004:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:01,  1.33it/s, avg=0.10646, loss=0.09638]

trial_002 train e004:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<01:00,  1.33it/s, avg=0.10646, loss=0.09638]

trial_002 train e004:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<01:00,  1.33it/s, avg=0.10667, loss=0.12065]

trial_002 train e004:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:59,  1.36it/s, avg=0.10667, loss=0.12065]

trial_002 train e004:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:59,  1.36it/s, avg=0.10677, loss=0.11364]

trial_002 train e004:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:58,  1.35it/s, avg=0.10677, loss=0.11364]

trial_002 train e004:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.35it/s, avg=0.10690, loss=0.11617]

trial_002 train e004:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:56,  1.38it/s, avg=0.10690, loss=0.11617]

trial_002 train e004:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:56,  1.38it/s, avg=0.10679, loss=0.09933]

trial_002 train e004:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:56,  1.36it/s, avg=0.10679, loss=0.09933]

trial_002 train e004:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:56,  1.36it/s, avg=0.10663, loss=0.09448]

trial_002 train e004:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:55,  1.37it/s, avg=0.10663, loss=0.09448]

trial_002 train e004:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:55,  1.37it/s, avg=0.10672, loss=0.11367]

trial_002 train e004:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:54,  1.38it/s, avg=0.10672, loss=0.11367]

trial_002 train e004:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:54,  1.38it/s, avg=0.10685, loss=0.11651]

trial_002 train e004:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.38it/s, avg=0.10685, loss=0.11651]

trial_002 train e004:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:53,  1.38it/s, avg=0.10670, loss=0.09571]

trial_002 train e004:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:52,  1.40it/s, avg=0.10670, loss=0.09571]

trial_002 train e004:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:52,  1.40it/s, avg=0.10654, loss=0.09423]

trial_002 train e004:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:51,  1.39it/s, avg=0.10654, loss=0.09423]

trial_002 train e004:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:51,  1.39it/s, avg=0.10636, loss=0.09221]

trial_002 train e004:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.38it/s, avg=0.10636, loss=0.09221]

trial_002 train e004:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.38it/s, avg=0.10633, loss=0.10412]

trial_002 train e004:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:50,  1.38it/s, avg=0.10633, loss=0.10412]

trial_002 train e004:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:50,  1.38it/s, avg=0.10650, loss=0.12021]

trial_002 train e004:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:49,  1.39it/s, avg=0.10650, loss=0.12021]

trial_002 train e004:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:49,  1.39it/s, avg=0.10639, loss=0.09717]

trial_002 train e004:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:49,  1.37it/s, avg=0.10639, loss=0.09717]

trial_002 train e004:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:49,  1.37it/s, avg=0.10642, loss=0.10914]

trial_002 train e004:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:49,  1.35it/s, avg=0.10642, loss=0.10914]

trial_002 train e004:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:49,  1.35it/s, avg=0.10641, loss=0.10574]

trial_002 train e004:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.35it/s, avg=0.10641, loss=0.10574]

trial_002 train e004:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:48,  1.35it/s, avg=0.10645, loss=0.10937]

trial_002 train e004:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:46,  1.39it/s, avg=0.10645, loss=0.10937]

trial_002 train e004:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:46,  1.39it/s, avg=0.10648, loss=0.10894]

trial_002 train e004:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.37it/s, avg=0.10648, loss=0.10894]

trial_002 train e004:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.37it/s, avg=0.10629, loss=0.09047]

trial_002 train e004:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.38it/s, avg=0.10629, loss=0.09047]

trial_002 train e004:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:45,  1.38it/s, avg=0.10610, loss=0.08941]

trial_002 train e004:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.38it/s, avg=0.10610, loss=0.08941]

trial_002 train e004:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.38it/s, avg=0.10599, loss=0.09613]

trial_002 train e004:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:44,  1.37it/s, avg=0.10599, loss=0.09613]

trial_002 train e004:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.37it/s, avg=0.10601, loss=0.10781]

trial_002 train e004:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.36it/s, avg=0.10601, loss=0.10781]

trial_002 train e004:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:43,  1.36it/s, avg=0.10600, loss=0.10516]

trial_002 train e004:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.35it/s, avg=0.10600, loss=0.10516]

trial_002 train e004:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.35it/s, avg=0.10628, loss=0.13176]

trial_002 train e004:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.35it/s, avg=0.10628, loss=0.13176]

trial_002 train e004:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.35it/s, avg=0.10631, loss=0.10935]

trial_002 train e004:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:42,  1.33it/s, avg=0.10631, loss=0.10935]

trial_002 train e004:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:42,  1.33it/s, avg=0.10625, loss=0.10044]

trial_002 train e004:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:42,  1.33it/s, avg=0.10625, loss=0.10044]

trial_002 train e004:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:42,  1.33it/s, avg=0.10624, loss=0.10508]

trial_002 train e004:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:40,  1.37it/s, avg=0.10624, loss=0.10508]

trial_002 train e004:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:40,  1.37it/s, avg=0.10609, loss=0.09195]

trial_002 train e004:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.36it/s, avg=0.10609, loss=0.09195]

trial_002 train e004:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.36it/s, avg=0.10615, loss=0.11237]

trial_002 train e004:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.36it/s, avg=0.10615, loss=0.11237]

trial_002 train e004:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.10613, loss=0.10443]

trial_002 train e004:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:38,  1.36it/s, avg=0.10613, loss=0.10443]

trial_002 train e004:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.36it/s, avg=0.10609, loss=0.10169]

trial_002 train e004:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:36,  1.39it/s, avg=0.10609, loss=0.10169]

trial_002 train e004:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:36,  1.39it/s, avg=0.10615, loss=0.11252]

trial_002 train e004:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.10615, loss=0.11252]

trial_002 train e004:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.10614, loss=0.10432]

trial_002 train e004:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:35,  1.39it/s, avg=0.10614, loss=0.10432]

trial_002 train e004:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.39it/s, avg=0.10619, loss=0.11142]

trial_002 train e004:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.38it/s, avg=0.10619, loss=0.11142]

trial_002 train e004:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:34,  1.38it/s, avg=0.10623, loss=0.11038]

trial_002 train e004:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.38it/s, avg=0.10623, loss=0.11038]

trial_002 train e004:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.38it/s, avg=0.10612, loss=0.09540]

trial_002 train e004:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.38it/s, avg=0.10612, loss=0.09540]

trial_002 train e004:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.38it/s, avg=0.10629, loss=0.12352]

trial_002 train e004:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.39it/s, avg=0.10629, loss=0.12352]

trial_002 train e004:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:32,  1.39it/s, avg=0.10615, loss=0.09169]

trial_002 train e004:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:32,  1.37it/s, avg=0.10615, loss=0.09169]

trial_002 train e004:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.37it/s, avg=0.10602, loss=0.09220]

trial_002 train e004:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:30,  1.39it/s, avg=0.10602, loss=0.09220]

trial_002 train e004:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:30,  1.39it/s, avg=0.10611, loss=0.11530]

trial_002 train e004:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:30,  1.37it/s, avg=0.10611, loss=0.11530]

trial_002 train e004:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.37it/s, avg=0.10609, loss=0.10422]

trial_002 train e004:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:30,  1.36it/s, avg=0.10609, loss=0.10422]

trial_002 train e004:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.36it/s, avg=0.10598, loss=0.09412]

trial_002 train e004:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:28,  1.38it/s, avg=0.10598, loss=0.09412]

trial_002 train e004:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:28,  1.38it/s, avg=0.10583, loss=0.08971]

trial_002 train e004:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.39it/s, avg=0.10583, loss=0.08971]

trial_002 train e004:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.39it/s, avg=0.10583, loss=0.10589]

trial_002 train e004:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.38it/s, avg=0.10583, loss=0.10589]

trial_002 train e004:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.38it/s, avg=0.10584, loss=0.10715]

trial_002 train e004:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:27,  1.36it/s, avg=0.10584, loss=0.10715]

trial_002 train e004:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:27,  1.36it/s, avg=0.10577, loss=0.09728]

trial_002 train e004:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.38it/s, avg=0.10577, loss=0.09728]

trial_002 train e004:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.38it/s, avg=0.10571, loss=0.09943]

trial_002 train e004:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:25,  1.38it/s, avg=0.10571, loss=0.09943]

trial_002 train e004:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.38it/s, avg=0.10573, loss=0.10709]

trial_002 train e004:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.37it/s, avg=0.10573, loss=0.10709]

trial_002 train e004:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.37it/s, avg=0.10573, loss=0.10663]

trial_002 train e004:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:24,  1.37it/s, avg=0.10573, loss=0.10663]

trial_002 train e004:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.37it/s, avg=0.10561, loss=0.09178]

trial_002 train e004:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.35it/s, avg=0.10561, loss=0.09178]

trial_002 train e004:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.35it/s, avg=0.10561, loss=0.10459]

trial_002 train e004:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.37it/s, avg=0.10561, loss=0.10459]

trial_002 train e004:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.37it/s, avg=0.10568, loss=0.11464]

trial_002 train e004:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:22,  1.33it/s, avg=0.10568, loss=0.11464]

trial_002 train e004:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:22,  1.33it/s, avg=0.10556, loss=0.09066]

trial_002 train e004:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:22,  1.31it/s, avg=0.10556, loss=0.09066]

trial_002 train e004:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:22,  1.31it/s, avg=0.10563, loss=0.11479]

trial_002 train e004:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.34it/s, avg=0.10563, loss=0.11479]

trial_002 train e004:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.34it/s, avg=0.10578, loss=0.12418]

trial_002 train e004:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.36it/s, avg=0.10578, loss=0.12418]

trial_002 train e004:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.36it/s, avg=0.10592, loss=0.12228]

trial_002 train e004:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:19,  1.35it/s, avg=0.10592, loss=0.12228]

trial_002 train e004:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.35it/s, avg=0.10586, loss=0.09860]

trial_002 train e004:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.35it/s, avg=0.10586, loss=0.09860]

trial_002 train e004:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.35it/s, avg=0.10580, loss=0.09791]

trial_002 train e004:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.34it/s, avg=0.10580, loss=0.09791]

trial_002 train e004:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.34it/s, avg=0.10593, loss=0.12309]

trial_002 train e004:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:17,  1.35it/s, avg=0.10593, loss=0.12309]

trial_002 train e004:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:17,  1.35it/s, avg=0.10596, loss=0.10916]

trial_002 train e004:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:16,  1.37it/s, avg=0.10596, loss=0.10916]

trial_002 train e004:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.37it/s, avg=0.10595, loss=0.10459]

trial_002 train e004:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.37it/s, avg=0.10595, loss=0.10459]

trial_002 train e004:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.37it/s, avg=0.10596, loss=0.10755]

trial_002 train e004:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.39it/s, avg=0.10596, loss=0.10755]

trial_002 train e004:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.39it/s, avg=0.10589, loss=0.09647]

trial_002 train e004:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.38it/s, avg=0.10589, loss=0.09647]

trial_002 train e004:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.38it/s, avg=0.10586, loss=0.10227]

trial_002 train e004:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:12,  1.41it/s, avg=0.10586, loss=0.10227]

trial_002 train e004:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:12,  1.41it/s, avg=0.10577, loss=0.09422]

trial_002 train e004:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:11,  1.42it/s, avg=0.10577, loss=0.09422]

trial_002 train e004:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:11,  1.42it/s, avg=0.10586, loss=0.11739]

trial_002 train e004:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.39it/s, avg=0.10586, loss=0.11739]

trial_002 train e004:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.39it/s, avg=0.10589, loss=0.11036]

trial_002 train e004:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:10,  1.39it/s, avg=0.10589, loss=0.11036]

trial_002 train e004:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.39it/s, avg=0.10586, loss=0.10222]

trial_002 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.39it/s, avg=0.10586, loss=0.10222]

trial_002 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.39it/s, avg=0.10593, loss=0.11478]

trial_002 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.36it/s, avg=0.10593, loss=0.11478]

trial_002 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.36it/s, avg=0.10594, loss=0.10697]

trial_002 train e004:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.37it/s, avg=0.10594, loss=0.10697]

trial_002 train e004:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.37it/s, avg=0.10587, loss=0.09664]

trial_002 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:08,  1.34it/s, avg=0.10587, loss=0.09664]

trial_002 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.34it/s, avg=0.10589, loss=0.10812]

trial_002 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.31it/s, avg=0.10589, loss=0.10812]

trial_002 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.31it/s, avg=0.10582, loss=0.09695]

trial_002 train e004:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.29it/s, avg=0.10582, loss=0.09695]

trial_002 train e004:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.29it/s, avg=0.10576, loss=0.09653]

trial_002 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:06,  1.28it/s, avg=0.10576, loss=0.09653]

trial_002 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:06,  1.28it/s, avg=0.10576, loss=0.10573]

trial_002 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:05,  1.28it/s, avg=0.10576, loss=0.10573]

trial_002 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.28it/s, avg=0.10572, loss=0.10061]

trial_002 train e004:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.30it/s, avg=0.10572, loss=0.10061]

trial_002 train e004:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.30it/s, avg=0.10574, loss=0.10903]

trial_002 train e004:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.32it/s, avg=0.10574, loss=0.10903]

trial_002 train e004:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.32it/s, avg=0.10578, loss=0.11043]

trial_002 train e004:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:03,  1.32it/s, avg=0.10578, loss=0.11043]

trial_002 train e004:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:03,  1.32it/s, avg=0.10573, loss=0.09972]

trial_002 train e004:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.32it/s, avg=0.10573, loss=0.09972]

trial_002 train e004:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.32it/s, avg=0.10567, loss=0.09633]

trial_002 train e004:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.33it/s, avg=0.10567, loss=0.09633]

trial_002 train e004:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.33it/s, avg=0.10554, loss=0.08619]

trial_002 train e004:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.33it/s, avg=0.10554, loss=0.08619]

trial_002 train e004:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.33it/s, avg=0.10555, loss=0.10878]

trial_002 train e004: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.61it/s, avg=0.10555, loss=0.10878]

trial_002 val e004:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e004:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.29it/s]

trial_002 val e004:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.36it/s]

trial_002 val e004:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.43it/s]

trial_002 val e004:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.46it/s]

trial_002 val e004:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.47it/s]

trial_002 val e004:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.47it/s]

trial_002 val e004:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.44it/s]

trial_002 val e004:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.42it/s]

trial_002 val e004:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.39it/s]

trial_002 val e004:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.41it/s]

trial_002 val e004:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.35it/s]

trial_002 val e004:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.36it/s]

trial_002 val e004:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.36it/s]

trial_002 val e004:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:15,  2.39it/s]

trial_002 val e004:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.42it/s]

trial_002 val e004:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.45it/s]

trial_002 val e004:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.47it/s]

trial_002 val e004:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:12,  2.47it/s]

trial_002 val e004:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.49it/s]

trial_002 val e004:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.48it/s]

trial_002 val e004:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.47it/s]

trial_002 val e004:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.47it/s]

trial_002 val e004:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:10,  2.48it/s]

trial_002 val e004:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.46it/s]

trial_002 val e004:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.40it/s]

trial_002 val e004:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.39it/s]

trial_002 val e004:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.41it/s]

trial_002 val e004:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.41it/s]

trial_002 val e004:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.41it/s]

trial_002 val e004:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.42it/s]

trial_002 val e004:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.42it/s]

trial_002 val e004:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.38it/s]

trial_002 val e004:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.38it/s]

trial_002 val e004:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.39it/s]

trial_002 val e004:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.42it/s]

trial_002 val e004:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.43it/s]

trial_002 val e004:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.41it/s]

trial_002 val e004:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:05,  2.33it/s]

trial_002 val e004:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.34it/s]

trial_002 val e004:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.35it/s]

trial_002 val e004:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.35it/s]

trial_002 val e004:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.38it/s]

trial_002 val e004:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.41it/s]

trial_002 val e004:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.41it/s]

trial_002 val e004:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.43it/s]

trial_002 val e004:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.46it/s]

trial_002 val e004:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.47it/s]

trial_002 val e004:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.45it/s]

trial_002 val e004:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.46it/s]

trial_002 val e004: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.45it/s]

[2026-05-28 20:32:46] [trial_002] epoch=004 | train_loss=0.105548 | val_MAE=0.104406 | val_S=0.895594 | best_S=0.895594 @epoch=4 | patience=0/5

[trial_002] epochs:   4%|████▊                                                                                                                    | 4/100 [09:10<3:34:40, 134.17s/it]

trial_002 train e005:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e005:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10461, loss=0.10461]

trial_002 train e005:   1%|▋                                                                                              | 1/149 [00:00<01:52,  1.31it/s, avg=0.10461, loss=0.10461]

trial_002 train e005:   1%|▋                                                                                              | 1/149 [00:01<01:52,  1.31it/s, avg=0.10472, loss=0.10482]

trial_002 train e005:   1%|█▎                                                                                             | 2/149 [00:01<01:52,  1.31it/s, avg=0.10472, loss=0.10482]

trial_002 train e005:   1%|█▎                                                                                             | 2/149 [00:02<01:52,  1.31it/s, avg=0.10581, loss=0.10800]

trial_002 train e005:   2%|█▉                                                                                             | 3/149 [00:02<01:46,  1.37it/s, avg=0.10581, loss=0.10800]

trial_002 train e005:   2%|█▉                                                                                             | 3/149 [00:02<01:46,  1.37it/s, avg=0.10414, loss=0.09914]

trial_002 train e005:   3%|██▌                                                                                            | 4/149 [00:02<01:44,  1.39it/s, avg=0.10414, loss=0.09914]

trial_002 train e005:   3%|██▌                                                                                            | 4/149 [00:03<01:44,  1.39it/s, avg=0.10319, loss=0.09937]

trial_002 train e005:   3%|███▏                                                                                           | 5/149 [00:03<01:42,  1.41it/s, avg=0.10319, loss=0.09937]

trial_002 train e005:   3%|███▏                                                                                           | 5/149 [00:04<01:42,  1.41it/s, avg=0.10146, loss=0.09279]

trial_002 train e005:   4%|███▊                                                                                           | 6/149 [00:04<01:40,  1.42it/s, avg=0.10146, loss=0.09279]

trial_002 train e005:   4%|███▊                                                                                           | 6/149 [00:05<01:40,  1.42it/s, avg=0.10013, loss=0.09217]

trial_002 train e005:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.39it/s, avg=0.10013, loss=0.09217]

trial_002 train e005:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.39it/s, avg=0.10029, loss=0.10141]

trial_002 train e005:   5%|█████                                                                                          | 8/149 [00:05<01:42,  1.37it/s, avg=0.10029, loss=0.10141]

trial_002 train e005:   5%|█████                                                                                          | 8/149 [00:06<01:42,  1.37it/s, avg=0.10081, loss=0.10500]

trial_002 train e005:   6%|█████▋                                                                                         | 9/149 [00:06<01:43,  1.35it/s, avg=0.10081, loss=0.10500]

trial_002 train e005:   6%|█████▋                                                                                         | 9/149 [00:07<01:43,  1.35it/s, avg=0.10013, loss=0.09401]

trial_002 train e005:   7%|██████▎                                                                                       | 10/149 [00:07<01:41,  1.37it/s, avg=0.10013, loss=0.09401]

trial_002 train e005:   7%|██████▎                                                                                       | 10/149 [00:07<01:41,  1.37it/s, avg=0.10170, loss=0.11739]

trial_002 train e005:   7%|██████▉                                                                                       | 11/149 [00:07<01:38,  1.40it/s, avg=0.10170, loss=0.11739]

trial_002 train e005:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.40it/s, avg=0.10235, loss=0.10945]

trial_002 train e005:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.37it/s, avg=0.10235, loss=0.10945]

trial_002 train e005:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.37it/s, avg=0.10308, loss=0.11185]

trial_002 train e005:   9%|████████▏                                                                                     | 13/149 [00:09<01:39,  1.37it/s, avg=0.10308, loss=0.11185]

trial_002 train e005:   9%|████████▏                                                                                     | 13/149 [00:10<01:39,  1.37it/s, avg=0.10224, loss=0.09129]

trial_002 train e005:   9%|████████▊                                                                                     | 14/149 [00:10<01:39,  1.36it/s, avg=0.10224, loss=0.09129]

trial_002 train e005:   9%|████████▊                                                                                     | 14/149 [00:10<01:39,  1.36it/s, avg=0.10269, loss=0.10908]

trial_002 train e005:  10%|█████████▍                                                                                    | 15/149 [00:10<01:39,  1.34it/s, avg=0.10269, loss=0.10908]

trial_002 train e005:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.34it/s, avg=0.10314, loss=0.10990]

trial_002 train e005:  11%|██████████                                                                                    | 16/149 [00:11<01:38,  1.35it/s, avg=0.10314, loss=0.10990]

trial_002 train e005:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.35it/s, avg=0.10286, loss=0.09840]

trial_002 train e005:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.34it/s, avg=0.10286, loss=0.09840]

trial_002 train e005:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.34it/s, avg=0.10261, loss=0.09831]

trial_002 train e005:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.37it/s, avg=0.10261, loss=0.09831]

trial_002 train e005:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.37it/s, avg=0.10227, loss=0.09605]

trial_002 train e005:  13%|███████████▉                                                                                  | 19/149 [00:13<01:35,  1.36it/s, avg=0.10227, loss=0.09605]

trial_002 train e005:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.36it/s, avg=0.10223, loss=0.10163]

trial_002 train e005:  13%|████████████▌                                                                                 | 20/149 [00:14<01:35,  1.35it/s, avg=0.10223, loss=0.10163]

trial_002 train e005:  13%|████████████▌                                                                                 | 20/149 [00:15<01:35,  1.35it/s, avg=0.10222, loss=0.10196]

trial_002 train e005:  14%|█████████████▏                                                                                | 21/149 [00:15<01:35,  1.33it/s, avg=0.10222, loss=0.10196]

trial_002 train e005:  14%|█████████████▏                                                                                | 21/149 [00:16<01:35,  1.33it/s, avg=0.10281, loss=0.11520]

trial_002 train e005:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.34it/s, avg=0.10281, loss=0.11520]

trial_002 train e005:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.34it/s, avg=0.10338, loss=0.11585]

trial_002 train e005:  15%|██████████████▌                                                                               | 23/149 [00:16<01:32,  1.37it/s, avg=0.10338, loss=0.11585]

trial_002 train e005:  15%|██████████████▌                                                                               | 23/149 [00:17<01:32,  1.37it/s, avg=0.10347, loss=0.10563]

trial_002 train e005:  16%|███████████████▏                                                                              | 24/149 [00:17<01:29,  1.40it/s, avg=0.10347, loss=0.10563]

trial_002 train e005:  16%|███████████████▏                                                                              | 24/149 [00:18<01:29,  1.40it/s, avg=0.10322, loss=0.09720]

trial_002 train e005:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.10322, loss=0.09720]

trial_002 train e005:  17%|███████████████▊                                                                              | 25/149 [00:19<01:30,  1.37it/s, avg=0.10332, loss=0.10577]

trial_002 train e005:  17%|████████████████▍                                                                             | 26/149 [00:19<01:29,  1.37it/s, avg=0.10332, loss=0.10577]

trial_002 train e005:  17%|████████████████▍                                                                             | 26/149 [00:19<01:29,  1.37it/s, avg=0.10314, loss=0.09860]

trial_002 train e005:  18%|█████████████████                                                                             | 27/149 [00:19<01:27,  1.39it/s, avg=0.10314, loss=0.09860]

trial_002 train e005:  18%|█████████████████                                                                             | 27/149 [00:20<01:27,  1.39it/s, avg=0.10286, loss=0.09521]

trial_002 train e005:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:26,  1.40it/s, avg=0.10286, loss=0.09521]

trial_002 train e005:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:26,  1.40it/s, avg=0.10318, loss=0.11222]

trial_002 train e005:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:25,  1.41it/s, avg=0.10318, loss=0.11222]

trial_002 train e005:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:25,  1.41it/s, avg=0.10323, loss=0.10446]

trial_002 train e005:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:24,  1.41it/s, avg=0.10323, loss=0.10446]

trial_002 train e005:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:24,  1.41it/s, avg=0.10282, loss=0.09057]

trial_002 train e005:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:22,  1.43it/s, avg=0.10282, loss=0.09057]

trial_002 train e005:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:22,  1.43it/s, avg=0.10275, loss=0.10050]

trial_002 train e005:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:23,  1.40it/s, avg=0.10275, loss=0.10050]

trial_002 train e005:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:23,  1.40it/s, avg=0.10291, loss=0.10829]

trial_002 train e005:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.38it/s, avg=0.10291, loss=0.10829]

trial_002 train e005:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.38it/s, avg=0.10288, loss=0.10165]

trial_002 train e005:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.10288, loss=0.10165]

trial_002 train e005:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.10244, loss=0.08751]

trial_002 train e005:  23%|██████████████████████                                                                        | 35/149 [00:25<01:20,  1.41it/s, avg=0.10244, loss=0.08751]

trial_002 train e005:  23%|██████████████████████                                                                        | 35/149 [00:26<01:20,  1.41it/s, avg=0.10244, loss=0.10271]

trial_002 train e005:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.39it/s, avg=0.10244, loss=0.10271]

trial_002 train e005:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.39it/s, avg=0.10252, loss=0.10525]

trial_002 train e005:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:22,  1.36it/s, avg=0.10252, loss=0.10525]

trial_002 train e005:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.36it/s, avg=0.10266, loss=0.10795]

trial_002 train e005:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:21,  1.36it/s, avg=0.10266, loss=0.10795]

trial_002 train e005:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:21,  1.36it/s, avg=0.10277, loss=0.10699]

trial_002 train e005:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:21,  1.35it/s, avg=0.10277, loss=0.10699]

trial_002 train e005:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:21,  1.35it/s, avg=0.10256, loss=0.09406]

trial_002 train e005:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:20,  1.35it/s, avg=0.10256, loss=0.09406]

trial_002 train e005:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:20,  1.35it/s, avg=0.10293, loss=0.11772]

trial_002 train e005:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:20,  1.34it/s, avg=0.10293, loss=0.11772]

trial_002 train e005:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:20,  1.34it/s, avg=0.10292, loss=0.10251]

trial_002 train e005:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:19,  1.34it/s, avg=0.10292, loss=0.10251]

trial_002 train e005:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:19,  1.34it/s, avg=0.10303, loss=0.10784]

trial_002 train e005:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:17,  1.38it/s, avg=0.10303, loss=0.10784]

trial_002 train e005:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:17,  1.38it/s, avg=0.10320, loss=0.11037]

trial_002 train e005:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:15,  1.40it/s, avg=0.10320, loss=0.11037]

trial_002 train e005:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:15,  1.40it/s, avg=0.10309, loss=0.09817]

trial_002 train e005:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:15,  1.37it/s, avg=0.10309, loss=0.09817]

trial_002 train e005:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.37it/s, avg=0.10331, loss=0.11361]

trial_002 train e005:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.37it/s, avg=0.10331, loss=0.11361]

trial_002 train e005:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:14,  1.37it/s, avg=0.10335, loss=0.10474]

trial_002 train e005:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:14,  1.37it/s, avg=0.10335, loss=0.10474]

trial_002 train e005:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:14,  1.37it/s, avg=0.10317, loss=0.09493]

trial_002 train e005:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.35it/s, avg=0.10317, loss=0.09493]

trial_002 train e005:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.35it/s, avg=0.10316, loss=0.10280]

trial_002 train e005:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:14,  1.35it/s, avg=0.10316, loss=0.10280]

trial_002 train e005:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:14,  1.35it/s, avg=0.10315, loss=0.10252]

trial_002 train e005:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:14,  1.34it/s, avg=0.10315, loss=0.10252]

trial_002 train e005:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:14,  1.34it/s, avg=0.10303, loss=0.09690]

trial_002 train e005:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:13,  1.34it/s, avg=0.10303, loss=0.09690]

trial_002 train e005:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:13,  1.34it/s, avg=0.10287, loss=0.09506]

trial_002 train e005:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:13,  1.32it/s, avg=0.10287, loss=0.09506]

trial_002 train e005:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:13,  1.32it/s, avg=0.10297, loss=0.10817]

trial_002 train e005:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:11,  1.33it/s, avg=0.10297, loss=0.10817]

trial_002 train e005:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:11,  1.33it/s, avg=0.10290, loss=0.09895]

trial_002 train e005:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:11,  1.33it/s, avg=0.10290, loss=0.09895]

trial_002 train e005:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:11,  1.33it/s, avg=0.10280, loss=0.09719]

trial_002 train e005:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:11,  1.32it/s, avg=0.10280, loss=0.09719]

trial_002 train e005:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:11,  1.32it/s, avg=0.10273, loss=0.09910]

trial_002 train e005:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:08,  1.36it/s, avg=0.10273, loss=0.09910]

trial_002 train e005:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:08,  1.36it/s, avg=0.10291, loss=0.11326]

trial_002 train e005:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:07,  1.37it/s, avg=0.10291, loss=0.11326]

trial_002 train e005:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:07,  1.37it/s, avg=0.10297, loss=0.10631]

trial_002 train e005:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.36it/s, avg=0.10297, loss=0.10631]

trial_002 train e005:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:06,  1.36it/s, avg=0.10303, loss=0.10639]

trial_002 train e005:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:04,  1.40it/s, avg=0.10303, loss=0.10639]

trial_002 train e005:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:04,  1.40it/s, avg=0.10333, loss=0.12092]

trial_002 train e005:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:06,  1.34it/s, avg=0.10333, loss=0.12092]

trial_002 train e005:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:06,  1.34it/s, avg=0.10359, loss=0.11936]

trial_002 train e005:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:05,  1.34it/s, avg=0.10359, loss=0.11936]

trial_002 train e005:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:05,  1.34it/s, avg=0.10370, loss=0.11015]

trial_002 train e005:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:04,  1.35it/s, avg=0.10370, loss=0.11015]

trial_002 train e005:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.35it/s, avg=0.10376, loss=0.10787]

trial_002 train e005:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:03,  1.35it/s, avg=0.10376, loss=0.10787]

trial_002 train e005:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:03,  1.35it/s, avg=0.10386, loss=0.11000]

trial_002 train e005:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.39it/s, avg=0.10386, loss=0.11000]

trial_002 train e005:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:01,  1.39it/s, avg=0.10399, loss=0.11212]

trial_002 train e005:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.39it/s, avg=0.10399, loss=0.11212]

trial_002 train e005:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:00,  1.39it/s, avg=0.10383, loss=0.09329]

trial_002 train e005:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:00,  1.37it/s, avg=0.10383, loss=0.09329]

trial_002 train e005:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:00,  1.37it/s, avg=0.10376, loss=0.09932]

trial_002 train e005:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:00,  1.36it/s, avg=0.10376, loss=0.09932]

trial_002 train e005:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:00,  1.36it/s, avg=0.10361, loss=0.09398]

trial_002 train e005:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:59,  1.37it/s, avg=0.10361, loss=0.09398]

trial_002 train e005:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:59,  1.37it/s, avg=0.10358, loss=0.10132]

trial_002 train e005:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:57,  1.39it/s, avg=0.10358, loss=0.10132]

trial_002 train e005:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:57,  1.39it/s, avg=0.10335, loss=0.08736]

trial_002 train e005:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.38it/s, avg=0.10335, loss=0.08736]

trial_002 train e005:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.38it/s, avg=0.10337, loss=0.10469]

trial_002 train e005:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:55,  1.41it/s, avg=0.10337, loss=0.10469]

trial_002 train e005:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:55,  1.41it/s, avg=0.10328, loss=0.09733]

trial_002 train e005:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:54,  1.41it/s, avg=0.10328, loss=0.09733]

trial_002 train e005:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:54,  1.41it/s, avg=0.10328, loss=0.10296]

trial_002 train e005:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:53,  1.42it/s, avg=0.10328, loss=0.10296]

trial_002 train e005:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:53,  1.42it/s, avg=0.10326, loss=0.10210]

trial_002 train e005:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:52,  1.42it/s, avg=0.10326, loss=0.10210]

trial_002 train e005:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:52,  1.42it/s, avg=0.10317, loss=0.09603]

trial_002 train e005:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:52,  1.41it/s, avg=0.10317, loss=0.09603]

trial_002 train e005:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:52,  1.41it/s, avg=0.10301, loss=0.09125]

trial_002 train e005:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:51,  1.41it/s, avg=0.10301, loss=0.09125]

trial_002 train e005:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:51,  1.41it/s, avg=0.10303, loss=0.10412]

trial_002 train e005:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:51,  1.39it/s, avg=0.10303, loss=0.10412]

trial_002 train e005:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:51,  1.39it/s, avg=0.10303, loss=0.10304]

trial_002 train e005:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.39it/s, avg=0.10303, loss=0.10304]

trial_002 train e005:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.39it/s, avg=0.10313, loss=0.11089]

trial_002 train e005:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:51,  1.36it/s, avg=0.10313, loss=0.11089]

trial_002 train e005:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:51,  1.36it/s, avg=0.10325, loss=0.11301]

trial_002 train e005:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.36it/s, avg=0.10325, loss=0.11301]

trial_002 train e005:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:50,  1.36it/s, avg=0.10317, loss=0.09685]

trial_002 train e005:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.34it/s, avg=0.10317, loss=0.09685]

trial_002 train e005:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.34it/s, avg=0.10348, loss=0.12895]

trial_002 train e005:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:47,  1.40it/s, avg=0.10348, loss=0.12895]

trial_002 train e005:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:47,  1.40it/s, avg=0.10337, loss=0.09416]

trial_002 train e005:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.37it/s, avg=0.10337, loss=0.09416]

trial_002 train e005:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:48,  1.37it/s, avg=0.10331, loss=0.09838]

trial_002 train e005:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:47,  1.37it/s, avg=0.10331, loss=0.09838]

trial_002 train e005:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:47,  1.37it/s, avg=0.10321, loss=0.09452]

trial_002 train e005:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.38it/s, avg=0.10321, loss=0.09452]

trial_002 train e005:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.38it/s, avg=0.10306, loss=0.09078]

trial_002 train e005:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.38it/s, avg=0.10306, loss=0.09078]

trial_002 train e005:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:45,  1.38it/s, avg=0.10300, loss=0.09755]

trial_002 train e005:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.38it/s, avg=0.10300, loss=0.09755]

trial_002 train e005:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:44,  1.38it/s, avg=0.10305, loss=0.10733]

trial_002 train e005:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.36it/s, avg=0.10305, loss=0.10733]

trial_002 train e005:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.36it/s, avg=0.10299, loss=0.09765]

trial_002 train e005:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:44,  1.35it/s, avg=0.10299, loss=0.09765]

trial_002 train e005:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.35it/s, avg=0.10298, loss=0.10230]

trial_002 train e005:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.35it/s, avg=0.10298, loss=0.10230]

trial_002 train e005:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.35it/s, avg=0.10287, loss=0.09249]

trial_002 train e005:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.35it/s, avg=0.10287, loss=0.09249]

trial_002 train e005:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.35it/s, avg=0.10275, loss=0.09225]

trial_002 train e005:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:42,  1.35it/s, avg=0.10275, loss=0.09225]

trial_002 train e005:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:42,  1.35it/s, avg=0.10265, loss=0.09343]

trial_002 train e005:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:42,  1.33it/s, avg=0.10265, loss=0.09343]

trial_002 train e005:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:42,  1.33it/s, avg=0.10254, loss=0.09214]

trial_002 train e005:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:40,  1.36it/s, avg=0.10254, loss=0.09214]

trial_002 train e005:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:40,  1.36it/s, avg=0.10255, loss=0.10377]

trial_002 train e005:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.35it/s, avg=0.10255, loss=0.10377]

trial_002 train e005:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:39,  1.35it/s, avg=0.10248, loss=0.09519]

trial_002 train e005:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.10248, loss=0.09519]

trial_002 train e005:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.10248, loss=0.10321]

trial_002 train e005:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:38,  1.35it/s, avg=0.10248, loss=0.10321]

trial_002 train e005:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.35it/s, avg=0.10273, loss=0.12624]

trial_002 train e005:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:38,  1.34it/s, avg=0.10273, loss=0.12624]

trial_002 train e005:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:38,  1.34it/s, avg=0.10280, loss=0.10964]

trial_002 train e005:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.35it/s, avg=0.10280, loss=0.10964]

trial_002 train e005:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.35it/s, avg=0.10275, loss=0.09787]

trial_002 train e005:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.38it/s, avg=0.10275, loss=0.09787]

trial_002 train e005:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.38it/s, avg=0.10288, loss=0.11611]

trial_002 train e005:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.38it/s, avg=0.10288, loss=0.11611]

trial_002 train e005:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:34,  1.38it/s, avg=0.10276, loss=0.09120]

trial_002 train e005:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.37it/s, avg=0.10276, loss=0.09120]

trial_002 train e005:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:34,  1.37it/s, avg=0.10290, loss=0.11659]

trial_002 train e005:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.38it/s, avg=0.10290, loss=0.11659]

trial_002 train e005:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.38it/s, avg=0.10284, loss=0.09682]

trial_002 train e005:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:31,  1.41it/s, avg=0.10284, loss=0.09682]

trial_002 train e005:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:31,  1.41it/s, avg=0.10297, loss=0.11624]

trial_002 train e005:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:31,  1.40it/s, avg=0.10297, loss=0.11624]

trial_002 train e005:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:31,  1.40it/s, avg=0.10280, loss=0.08562]

trial_002 train e005:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:30,  1.41it/s, avg=0.10280, loss=0.08562]

trial_002 train e005:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:30,  1.41it/s, avg=0.10291, loss=0.11424]

trial_002 train e005:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.39it/s, avg=0.10291, loss=0.11424]

trial_002 train e005:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.39it/s, avg=0.10282, loss=0.09302]

trial_002 train e005:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:29,  1.40it/s, avg=0.10282, loss=0.09302]

trial_002 train e005:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:29,  1.40it/s, avg=0.10259, loss=0.07830]

trial_002 train e005:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:28,  1.40it/s, avg=0.10259, loss=0.07830]

trial_002 train e005:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:28,  1.40it/s, avg=0.10263, loss=0.10687]

trial_002 train e005:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:27,  1.40it/s, avg=0.10263, loss=0.10687]

trial_002 train e005:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:27,  1.40it/s, avg=0.10272, loss=0.11263]

trial_002 train e005:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.40it/s, avg=0.10272, loss=0.11263]

trial_002 train e005:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.40it/s, avg=0.10282, loss=0.11401]

trial_002 train e005:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:25,  1.43it/s, avg=0.10282, loss=0.11401]

trial_002 train e005:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:25,  1.43it/s, avg=0.10285, loss=0.10619]

trial_002 train e005:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:25,  1.40it/s, avg=0.10285, loss=0.10619]

trial_002 train e005:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:25,  1.40it/s, avg=0.10291, loss=0.10885]

trial_002 train e005:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.40it/s, avg=0.10291, loss=0.10885]

trial_002 train e005:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.40it/s, avg=0.10302, loss=0.11645]

trial_002 train e005:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.41it/s, avg=0.10302, loss=0.11645]

trial_002 train e005:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.41it/s, avg=0.10308, loss=0.10914]

trial_002 train e005:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:22,  1.44it/s, avg=0.10308, loss=0.10914]

trial_002 train e005:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:22,  1.44it/s, avg=0.10296, loss=0.08925]

trial_002 train e005:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:22,  1.43it/s, avg=0.10296, loss=0.08925]

trial_002 train e005:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:22,  1.43it/s, avg=0.10290, loss=0.09654]

trial_002 train e005:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.40it/s, avg=0.10290, loss=0.09654]

trial_002 train e005:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.40it/s, avg=0.10285, loss=0.09645]

trial_002 train e005:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:20,  1.43it/s, avg=0.10285, loss=0.09645]

trial_002 train e005:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:20,  1.43it/s, avg=0.10298, loss=0.11843]

trial_002 train e005:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:20,  1.40it/s, avg=0.10298, loss=0.11843]

trial_002 train e005:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:20,  1.40it/s, avg=0.10283, loss=0.08440]

trial_002 train e005:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.38it/s, avg=0.10283, loss=0.08440]

trial_002 train e005:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.38it/s, avg=0.10292, loss=0.11450]

trial_002 train e005:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.37it/s, avg=0.10292, loss=0.11450]

trial_002 train e005:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.37it/s, avg=0.10284, loss=0.09233]

trial_002 train e005:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:18,  1.39it/s, avg=0.10284, loss=0.09233]

trial_002 train e005:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:18,  1.39it/s, avg=0.10291, loss=0.11221]

trial_002 train e005:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:17,  1.39it/s, avg=0.10291, loss=0.11221]

trial_002 train e005:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:17,  1.39it/s, avg=0.10285, loss=0.09470]

trial_002 train e005:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:17,  1.38it/s, avg=0.10285, loss=0.09470]

trial_002 train e005:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.38it/s, avg=0.10290, loss=0.10994]

trial_002 train e005:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.40it/s, avg=0.10290, loss=0.10994]

trial_002 train e005:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.40it/s, avg=0.10281, loss=0.09083]

trial_002 train e005:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:15,  1.38it/s, avg=0.10281, loss=0.09083]

trial_002 train e005:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:15,  1.38it/s, avg=0.10267, loss=0.08514]

trial_002 train e005:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.36it/s, avg=0.10267, loss=0.08514]

trial_002 train e005:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.36it/s, avg=0.10264, loss=0.09890]

trial_002 train e005:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.37it/s, avg=0.10264, loss=0.09890]

trial_002 train e005:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.37it/s, avg=0.10271, loss=0.11184]

trial_002 train e005:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.36it/s, avg=0.10271, loss=0.11184]

trial_002 train e005:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.36it/s, avg=0.10268, loss=0.09848]

trial_002 train e005:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.37it/s, avg=0.10268, loss=0.09848]

trial_002 train e005:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.37it/s, avg=0.10260, loss=0.09247]

trial_002 train e005:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.38it/s, avg=0.10260, loss=0.09247]

trial_002 train e005:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.38it/s, avg=0.10257, loss=0.09813]

trial_002 train e005:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.40it/s, avg=0.10257, loss=0.09813]

trial_002 train e005:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.40it/s, avg=0.10258, loss=0.10420]

trial_002 train e005:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:10,  1.41it/s, avg=0.10258, loss=0.10420]

trial_002 train e005:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.41it/s, avg=0.10257, loss=0.10097]

trial_002 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:09,  1.44it/s, avg=0.10257, loss=0.10097]

trial_002 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:09,  1.44it/s, avg=0.10269, loss=0.11971]

trial_002 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.42it/s, avg=0.10269, loss=0.11971]

trial_002 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.42it/s, avg=0.10282, loss=0.12031]

trial_002 train e005:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.40it/s, avg=0.10282, loss=0.12031]

trial_002 train e005:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.40it/s, avg=0.10289, loss=0.11269]

trial_002 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:07,  1.41it/s, avg=0.10289, loss=0.11269]

trial_002 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:07,  1.41it/s, avg=0.10292, loss=0.10623]

trial_002 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.40it/s, avg=0.10292, loss=0.10623]

trial_002 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.40it/s, avg=0.10291, loss=0.10202]

trial_002 train e005:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.40it/s, avg=0.10291, loss=0.10202]

trial_002 train e005:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.40it/s, avg=0.10300, loss=0.11592]

trial_002 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.42it/s, avg=0.10300, loss=0.11592]

trial_002 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.42it/s, avg=0.10302, loss=0.10540]

trial_002 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:04,  1.43it/s, avg=0.10302, loss=0.10540]

trial_002 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:04,  1.43it/s, avg=0.10289, loss=0.08390]

trial_002 train e005:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.41it/s, avg=0.10289, loss=0.08390]

trial_002 train e005:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.41it/s, avg=0.10284, loss=0.09558]

trial_002 train e005:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.40it/s, avg=0.10284, loss=0.09558]

trial_002 train e005:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.40it/s, avg=0.10284, loss=0.10372]

trial_002 train e005:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.40it/s, avg=0.10284, loss=0.10372]

trial_002 train e005:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.40it/s, avg=0.10290, loss=0.11196]

trial_002 train e005:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.39it/s, avg=0.10290, loss=0.11196]

trial_002 train e005:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.39it/s, avg=0.10291, loss=0.10428]

trial_002 train e005:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.39it/s, avg=0.10291, loss=0.10428]

trial_002 train e005:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.39it/s, avg=0.10295, loss=0.10780]

trial_002 train e005:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.46it/s, avg=0.10295, loss=0.10780]

trial_002 train e005:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.46it/s, avg=0.10293, loss=0.09856]

trial_002 train e005: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:47<00:00,  1.75it/s, avg=0.10293, loss=0.09856]

trial_002 val e005:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e005:   2%|██▌                                                                                                                          | 1/50 [00:00<00:19,  2.48it/s]

trial_002 val e005:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.49it/s]

trial_002 val e005:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:18,  2.49it/s]

trial_002 val e005:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.45it/s]

trial_002 val e005:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.43it/s]

trial_002 val e005:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.44it/s]

trial_002 val e005:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.45it/s]

trial_002 val e005:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.46it/s]

trial_002 val e005:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.47it/s]

trial_002 val e005:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.47it/s]

trial_002 val e005:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.47it/s]

trial_002 val e005:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.47it/s]

trial_002 val e005:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:14,  2.47it/s]

trial_002 val e005:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.47it/s]

trial_002 val e005:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.48it/s]

trial_002 val e005:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.49it/s]

trial_002 val e005:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.46it/s]

trial_002 val e005:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.45it/s]

trial_002 val e005:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.41it/s]

trial_002 val e005:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.44it/s]

trial_002 val e005:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.46it/s]

trial_002 val e005:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:08<00:11,  2.48it/s]

trial_002 val e005:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:10,  2.48it/s]

trial_002 val e005:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.49it/s]

trial_002 val e005:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.49it/s]

trial_002 val e005:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.49it/s]

trial_002 val e005:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:10<00:09,  2.49it/s]

trial_002 val e005:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.49it/s]

trial_002 val e005:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.50it/s]

trial_002 val e005:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:07,  2.50it/s]

trial_002 val e005:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.48it/s]

trial_002 val e005:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:12<00:07,  2.46it/s]

trial_002 val e005:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.46it/s]

trial_002 val e005:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.47it/s]

trial_002 val e005:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.47it/s]

trial_002 val e005:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.47it/s]

trial_002 val e005:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:14<00:05,  2.48it/s]

trial_002 val e005:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.49it/s]

trial_002 val e005:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.50it/s]

trial_002 val e005:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:03,  2.50it/s]

trial_002 val e005:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.48it/s]

trial_002 val e005:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:16<00:03,  2.48it/s]

trial_002 val e005:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.46it/s]

trial_002 val e005:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.45it/s]

trial_002 val e005:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.44it/s]

trial_002 val e005:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.44it/s]

trial_002 val e005:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.46it/s]

trial_002 val e005:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.48it/s]

trial_002 val e005:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.48it/s]

trial_002 val e005: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.51it/s]

[2026-05-28 20:34:55] [trial_002] epoch=005 | train_loss=0.102935 | val_MAE=0.102852 | val_S=0.897148 | best_S=0.897148 @epoch=5 | patience=0/5

[trial_002] epochs:   5%|██████                                                                                                                   | 5/100 [11:19<3:29:21, 132.23s/it]

trial_002 train e006:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e006:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09759, loss=0.09759]

trial_002 train e006:   1%|▋                                                                                              | 1/149 [00:00<01:49,  1.35it/s, avg=0.09759, loss=0.09759]

trial_002 train e006:   1%|▋                                                                                              | 1/149 [00:01<01:49,  1.35it/s, avg=0.09419, loss=0.09080]

trial_002 train e006:   1%|█▎                                                                                             | 2/149 [00:01<01:42,  1.43it/s, avg=0.09419, loss=0.09080]

trial_002 train e006:   1%|█▎                                                                                             | 2/149 [00:02<01:42,  1.43it/s, avg=0.09646, loss=0.10101]

trial_002 train e006:   2%|█▉                                                                                             | 3/149 [00:02<01:41,  1.43it/s, avg=0.09646, loss=0.10101]

trial_002 train e006:   2%|█▉                                                                                             | 3/149 [00:02<01:41,  1.43it/s, avg=0.09853, loss=0.10472]

trial_002 train e006:   3%|██▌                                                                                            | 4/149 [00:02<01:43,  1.41it/s, avg=0.09853, loss=0.10472]

trial_002 train e006:   3%|██▌                                                                                            | 4/149 [00:03<01:43,  1.41it/s, avg=0.09996, loss=0.10570]

trial_002 train e006:   3%|███▏                                                                                           | 5/149 [00:03<01:43,  1.39it/s, avg=0.09996, loss=0.10570]

trial_002 train e006:   3%|███▏                                                                                           | 5/149 [00:04<01:43,  1.39it/s, avg=0.09919, loss=0.09535]

trial_002 train e006:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.39it/s, avg=0.09919, loss=0.09535]

trial_002 train e006:   4%|███▊                                                                                           | 6/149 [00:05<01:42,  1.39it/s, avg=0.10001, loss=0.10487]

trial_002 train e006:   5%|████▍                                                                                          | 7/149 [00:05<01:41,  1.39it/s, avg=0.10001, loss=0.10487]

trial_002 train e006:   5%|████▍                                                                                          | 7/149 [00:05<01:41,  1.39it/s, avg=0.10003, loss=0.10024]

trial_002 train e006:   5%|█████                                                                                          | 8/149 [00:05<01:40,  1.40it/s, avg=0.10003, loss=0.10024]

trial_002 train e006:   5%|█████                                                                                          | 8/149 [00:06<01:40,  1.40it/s, avg=0.10035, loss=0.10291]

trial_002 train e006:   6%|█████▋                                                                                         | 9/149 [00:06<01:39,  1.40it/s, avg=0.10035, loss=0.10291]

trial_002 train e006:   6%|█████▋                                                                                         | 9/149 [00:07<01:39,  1.40it/s, avg=0.10049, loss=0.10171]

trial_002 train e006:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.10049, loss=0.10171]

trial_002 train e006:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.10098, loss=0.10591]

trial_002 train e006:   7%|██████▉                                                                                       | 11/149 [00:07<01:39,  1.38it/s, avg=0.10098, loss=0.10591]

trial_002 train e006:   7%|██████▉                                                                                       | 11/149 [00:08<01:39,  1.38it/s, avg=0.09990, loss=0.08794]

trial_002 train e006:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.36it/s, avg=0.09990, loss=0.08794]

trial_002 train e006:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.36it/s, avg=0.10031, loss=0.10526]

trial_002 train e006:   9%|████████▏                                                                                     | 13/149 [00:09<01:39,  1.37it/s, avg=0.10031, loss=0.10526]

trial_002 train e006:   9%|████████▏                                                                                     | 13/149 [00:10<01:39,  1.37it/s, avg=0.10040, loss=0.10154]

trial_002 train e006:   9%|████████▊                                                                                     | 14/149 [00:10<01:39,  1.36it/s, avg=0.10040, loss=0.10154]

trial_002 train e006:   9%|████████▊                                                                                     | 14/149 [00:10<01:39,  1.36it/s, avg=0.10084, loss=0.10699]

trial_002 train e006:  10%|█████████▍                                                                                    | 15/149 [00:10<01:36,  1.40it/s, avg=0.10084, loss=0.10699]

trial_002 train e006:  10%|█████████▍                                                                                    | 15/149 [00:11<01:36,  1.40it/s, avg=0.10119, loss=0.10656]

trial_002 train e006:  11%|██████████                                                                                    | 16/149 [00:11<01:33,  1.42it/s, avg=0.10119, loss=0.10656]

trial_002 train e006:  11%|██████████                                                                                    | 16/149 [00:12<01:33,  1.42it/s, avg=0.09988, loss=0.07886]

trial_002 train e006:  11%|██████████▋                                                                                   | 17/149 [00:12<01:34,  1.40it/s, avg=0.09988, loss=0.07886]

trial_002 train e006:  11%|██████████▋                                                                                   | 17/149 [00:12<01:34,  1.40it/s, avg=0.09913, loss=0.08634]

trial_002 train e006:  12%|███████████▎                                                                                  | 18/149 [00:12<01:32,  1.42it/s, avg=0.09913, loss=0.08634]

trial_002 train e006:  12%|███████████▎                                                                                  | 18/149 [00:13<01:32,  1.42it/s, avg=0.09904, loss=0.09752]

trial_002 train e006:  13%|███████████▉                                                                                  | 19/149 [00:13<01:32,  1.41it/s, avg=0.09904, loss=0.09752]

trial_002 train e006:  13%|███████████▉                                                                                  | 19/149 [00:14<01:32,  1.41it/s, avg=0.09864, loss=0.09102]

trial_002 train e006:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.41it/s, avg=0.09864, loss=0.09102]

trial_002 train e006:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.41it/s, avg=0.09960, loss=0.11879]

trial_002 train e006:  14%|█████████████▏                                                                                | 21/149 [00:14<01:28,  1.44it/s, avg=0.09960, loss=0.11879]

trial_002 train e006:  14%|█████████████▏                                                                                | 21/149 [00:15<01:28,  1.44it/s, avg=0.10019, loss=0.11254]

trial_002 train e006:  15%|█████████████▉                                                                                | 22/149 [00:15<01:28,  1.44it/s, avg=0.10019, loss=0.11254]

trial_002 train e006:  15%|█████████████▉                                                                                | 22/149 [00:16<01:28,  1.44it/s, avg=0.10050, loss=0.10723]

trial_002 train e006:  15%|██████████████▌                                                                               | 23/149 [00:16<01:28,  1.42it/s, avg=0.10050, loss=0.10723]

trial_002 train e006:  15%|██████████████▌                                                                               | 23/149 [00:17<01:28,  1.42it/s, avg=0.10061, loss=0.10315]

trial_002 train e006:  16%|███████████████▏                                                                              | 24/149 [00:17<01:28,  1.41it/s, avg=0.10061, loss=0.10315]

trial_002 train e006:  16%|███████████████▏                                                                              | 24/149 [00:17<01:28,  1.41it/s, avg=0.10056, loss=0.09950]

trial_002 train e006:  17%|███████████████▊                                                                              | 25/149 [00:17<01:28,  1.41it/s, avg=0.10056, loss=0.09950]

trial_002 train e006:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.41it/s, avg=0.10021, loss=0.09147]

trial_002 train e006:  17%|████████████████▍                                                                             | 26/149 [00:18<01:27,  1.40it/s, avg=0.10021, loss=0.09147]

trial_002 train e006:  17%|████████████████▍                                                                             | 26/149 [00:19<01:27,  1.40it/s, avg=0.09993, loss=0.09259]

trial_002 train e006:  18%|█████████████████                                                                             | 27/149 [00:19<01:25,  1.42it/s, avg=0.09993, loss=0.09259]

trial_002 train e006:  18%|█████████████████                                                                             | 27/149 [00:19<01:25,  1.42it/s, avg=0.09998, loss=0.10142]

trial_002 train e006:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:25,  1.42it/s, avg=0.09998, loss=0.10142]

trial_002 train e006:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:25,  1.42it/s, avg=0.10051, loss=0.11516]

trial_002 train e006:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:22,  1.45it/s, avg=0.10051, loss=0.11516]

trial_002 train e006:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:22,  1.45it/s, avg=0.10064, loss=0.10462]

trial_002 train e006:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:22,  1.44it/s, avg=0.10064, loss=0.10462]

trial_002 train e006:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:22,  1.44it/s, avg=0.10029, loss=0.08973]

trial_002 train e006:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:23,  1.42it/s, avg=0.10029, loss=0.08973]

trial_002 train e006:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:23,  1.42it/s, avg=0.10020, loss=0.09747]

trial_002 train e006:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:23,  1.41it/s, avg=0.10020, loss=0.09747]

trial_002 train e006:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:23,  1.41it/s, avg=0.10074, loss=0.11782]

trial_002 train e006:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:22,  1.40it/s, avg=0.10074, loss=0.11782]

trial_002 train e006:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:22,  1.40it/s, avg=0.10097, loss=0.10851]

trial_002 train e006:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:23,  1.37it/s, avg=0.10097, loss=0.10851]

trial_002 train e006:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.10071, loss=0.09206]

trial_002 train e006:  23%|██████████████████████                                                                        | 35/149 [00:25<01:24,  1.35it/s, avg=0.10071, loss=0.09206]

trial_002 train e006:  23%|██████████████████████                                                                        | 35/149 [00:25<01:24,  1.35it/s, avg=0.10134, loss=0.12334]

trial_002 train e006:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:23,  1.35it/s, avg=0.10134, loss=0.12334]

trial_002 train e006:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:23,  1.35it/s, avg=0.10130, loss=0.09971]

trial_002 train e006:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:22,  1.36it/s, avg=0.10130, loss=0.09971]

trial_002 train e006:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.36it/s, avg=0.10138, loss=0.10434]

trial_002 train e006:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:21,  1.36it/s, avg=0.10138, loss=0.10434]

trial_002 train e006:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:21,  1.36it/s, avg=0.10145, loss=0.10443]

trial_002 train e006:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:17,  1.41it/s, avg=0.10145, loss=0.10443]

trial_002 train e006:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:17,  1.41it/s, avg=0.10146, loss=0.10177]

trial_002 train e006:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:18,  1.39it/s, avg=0.10146, loss=0.10177]

trial_002 train e006:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.10172, loss=0.11191]

trial_002 train e006:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:17,  1.39it/s, avg=0.10172, loss=0.11191]

trial_002 train e006:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.39it/s, avg=0.10144, loss=0.09020]

trial_002 train e006:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:16,  1.40it/s, avg=0.10144, loss=0.09020]

trial_002 train e006:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:16,  1.40it/s, avg=0.10119, loss=0.09067]

trial_002 train e006:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:17,  1.36it/s, avg=0.10119, loss=0.09067]

trial_002 train e006:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:17,  1.36it/s, avg=0.10099, loss=0.09214]

trial_002 train e006:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:14,  1.40it/s, avg=0.10099, loss=0.09214]

trial_002 train e006:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.40it/s, avg=0.10066, loss=0.08639]

trial_002 train e006:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:15,  1.38it/s, avg=0.10066, loss=0.08639]

trial_002 train e006:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:15,  1.38it/s, avg=0.10082, loss=0.10774]

trial_002 train e006:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:13,  1.40it/s, avg=0.10082, loss=0.10774]

trial_002 train e006:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:13,  1.40it/s, avg=0.10118, loss=0.11774]

trial_002 train e006:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.41it/s, avg=0.10118, loss=0.11774]

trial_002 train e006:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:12,  1.41it/s, avg=0.10114, loss=0.09947]

trial_002 train e006:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.39it/s, avg=0.10114, loss=0.09947]

trial_002 train e006:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:12,  1.39it/s, avg=0.10093, loss=0.09092]

trial_002 train e006:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.37it/s, avg=0.10093, loss=0.09092]

trial_002 train e006:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.37it/s, avg=0.10099, loss=0.10358]

trial_002 train e006:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:12,  1.37it/s, avg=0.10099, loss=0.10358]

trial_002 train e006:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:12,  1.37it/s, avg=0.10107, loss=0.10539]

trial_002 train e006:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:11,  1.38it/s, avg=0.10107, loss=0.10539]

trial_002 train e006:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:11,  1.38it/s, avg=0.10090, loss=0.09229]

trial_002 train e006:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:10,  1.37it/s, avg=0.10090, loss=0.09229]

trial_002 train e006:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.10129, loss=0.12161]

trial_002 train e006:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.10129, loss=0.12161]

trial_002 train e006:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.10139, loss=0.10660]

trial_002 train e006:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:09,  1.36it/s, avg=0.10139, loss=0.10660]

trial_002 train e006:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.36it/s, avg=0.10118, loss=0.08973]

trial_002 train e006:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.37it/s, avg=0.10118, loss=0.08973]

trial_002 train e006:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.10111, loss=0.09707]

trial_002 train e006:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:05,  1.42it/s, avg=0.10111, loss=0.09707]

trial_002 train e006:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:05,  1.42it/s, avg=0.10106, loss=0.09854]

trial_002 train e006:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:05,  1.41it/s, avg=0.10106, loss=0.09854]

trial_002 train e006:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.41it/s, avg=0.10096, loss=0.09543]

trial_002 train e006:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.40it/s, avg=0.10096, loss=0.09543]

trial_002 train e006:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:05,  1.40it/s, avg=0.10101, loss=0.10348]

trial_002 train e006:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:03,  1.41it/s, avg=0.10101, loss=0.10348]

trial_002 train e006:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:03,  1.41it/s, avg=0.10092, loss=0.09587]

trial_002 train e006:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:02,  1.42it/s, avg=0.10092, loss=0.09587]

trial_002 train e006:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:02,  1.42it/s, avg=0.10084, loss=0.09611]

trial_002 train e006:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:01,  1.42it/s, avg=0.10084, loss=0.09611]

trial_002 train e006:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:01,  1.42it/s, avg=0.10085, loss=0.10120]

trial_002 train e006:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:00,  1.43it/s, avg=0.10085, loss=0.10120]

trial_002 train e006:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:00,  1.43it/s, avg=0.10094, loss=0.10647]

trial_002 train e006:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:00,  1.43it/s, avg=0.10094, loss=0.10647]

trial_002 train e006:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:00,  1.43it/s, avg=0.10115, loss=0.11486]

trial_002 train e006:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<00:59,  1.44it/s, avg=0.10115, loss=0.11486]

trial_002 train e006:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<00:59,  1.44it/s, avg=0.10122, loss=0.10533]

trial_002 train e006:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.41it/s, avg=0.10122, loss=0.10533]

trial_002 train e006:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<00:59,  1.41it/s, avg=0.10145, loss=0.11672]

trial_002 train e006:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:59,  1.40it/s, avg=0.10145, loss=0.11672]

trial_002 train e006:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:59,  1.40it/s, avg=0.10136, loss=0.09501]

trial_002 train e006:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:58,  1.41it/s, avg=0.10136, loss=0.09501]

trial_002 train e006:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.41it/s, avg=0.10145, loss=0.10730]

trial_002 train e006:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:57,  1.41it/s, avg=0.10145, loss=0.10730]

trial_002 train e006:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:57,  1.41it/s, avg=0.10152, loss=0.10691]

trial_002 train e006:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:57,  1.40it/s, avg=0.10152, loss=0.10691]

trial_002 train e006:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:57,  1.40it/s, avg=0.10142, loss=0.09401]

trial_002 train e006:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.39it/s, avg=0.10142, loss=0.09401]

trial_002 train e006:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.39it/s, avg=0.10141, loss=0.10061]

trial_002 train e006:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:56,  1.39it/s, avg=0.10141, loss=0.10061]

trial_002 train e006:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:56,  1.39it/s, avg=0.10118, loss=0.08499]

trial_002 train e006:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:54,  1.40it/s, avg=0.10118, loss=0.08499]

trial_002 train e006:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:54,  1.40it/s, avg=0.10135, loss=0.11364]

trial_002 train e006:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:55,  1.36it/s, avg=0.10135, loss=0.11364]

trial_002 train e006:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:55,  1.36it/s, avg=0.10164, loss=0.12254]

trial_002 train e006:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:54,  1.37it/s, avg=0.10164, loss=0.12254]

trial_002 train e006:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:54,  1.37it/s, avg=0.10164, loss=0.10182]

trial_002 train e006:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:53,  1.37it/s, avg=0.10164, loss=0.10182]

trial_002 train e006:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.37it/s, avg=0.10158, loss=0.09690]

trial_002 train e006:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:51,  1.41it/s, avg=0.10158, loss=0.09690]

trial_002 train e006:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:51,  1.41it/s, avg=0.10141, loss=0.08917]

trial_002 train e006:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:50,  1.41it/s, avg=0.10141, loss=0.08917]

trial_002 train e006:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:50,  1.41it/s, avg=0.10130, loss=0.09280]

trial_002 train e006:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:51,  1.39it/s, avg=0.10130, loss=0.09280]

trial_002 train e006:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.39it/s, avg=0.10129, loss=0.10018]

trial_002 train e006:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.39it/s, avg=0.10129, loss=0.10018]

trial_002 train e006:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:50,  1.39it/s, avg=0.10125, loss=0.09838]

trial_002 train e006:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:48,  1.42it/s, avg=0.10125, loss=0.09838]

trial_002 train e006:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:48,  1.42it/s, avg=0.10127, loss=0.10248]

trial_002 train e006:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:48,  1.40it/s, avg=0.10127, loss=0.10248]

trial_002 train e006:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:48,  1.40it/s, avg=0.10140, loss=0.11167]

trial_002 train e006:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:48,  1.38it/s, avg=0.10140, loss=0.11167]

trial_002 train e006:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:48,  1.38it/s, avg=0.10114, loss=0.08011]

trial_002 train e006:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:48,  1.37it/s, avg=0.10114, loss=0.08011]

trial_002 train e006:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.37it/s, avg=0.10111, loss=0.09907]

trial_002 train e006:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:46,  1.41it/s, avg=0.10111, loss=0.09907]

trial_002 train e006:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:46,  1.41it/s, avg=0.10106, loss=0.09651]

trial_002 train e006:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:45,  1.40it/s, avg=0.10106, loss=0.09651]

trial_002 train e006:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:45,  1.40it/s, avg=0.10119, loss=0.11213]

trial_002 train e006:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.39it/s, avg=0.10119, loss=0.11213]

trial_002 train e006:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.39it/s, avg=0.10121, loss=0.10320]

trial_002 train e006:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.38it/s, avg=0.10121, loss=0.10320]

trial_002 train e006:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.38it/s, avg=0.10147, loss=0.12355]

trial_002 train e006:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:44,  1.38it/s, avg=0.10147, loss=0.12355]

trial_002 train e006:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:44,  1.38it/s, avg=0.10167, loss=0.11928]

trial_002 train e006:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:43,  1.39it/s, avg=0.10167, loss=0.11928]

trial_002 train e006:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.39it/s, avg=0.10154, loss=0.08997]

trial_002 train e006:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.39it/s, avg=0.10154, loss=0.08997]

trial_002 train e006:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:42,  1.39it/s, avg=0.10151, loss=0.09923]

trial_002 train e006:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.38it/s, avg=0.10151, loss=0.09923]

trial_002 train e006:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.38it/s, avg=0.10145, loss=0.09591]

trial_002 train e006:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:41,  1.38it/s, avg=0.10145, loss=0.09591]

trial_002 train e006:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.38it/s, avg=0.10132, loss=0.08955]

trial_002 train e006:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:39,  1.41it/s, avg=0.10132, loss=0.08955]

trial_002 train e006:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:39,  1.41it/s, avg=0.10133, loss=0.10204]

trial_002 train e006:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:38,  1.44it/s, avg=0.10133, loss=0.10204]

trial_002 train e006:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:38,  1.44it/s, avg=0.10131, loss=0.09991]

trial_002 train e006:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:37,  1.43it/s, avg=0.10131, loss=0.09991]

trial_002 train e006:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:37,  1.43it/s, avg=0.10114, loss=0.08468]

trial_002 train e006:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:37,  1.41it/s, avg=0.10114, loss=0.08468]

trial_002 train e006:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:37,  1.41it/s, avg=0.10113, loss=0.09973]

trial_002 train e006:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.39it/s, avg=0.10113, loss=0.09973]

trial_002 train e006:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:37,  1.39it/s, avg=0.10105, loss=0.09394]

trial_002 train e006:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.40it/s, avg=0.10105, loss=0.09394]

trial_002 train e006:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.40it/s, avg=0.10107, loss=0.10228]

trial_002 train e006:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:34,  1.45it/s, avg=0.10107, loss=0.10228]

trial_002 train e006:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:34,  1.45it/s, avg=0.10117, loss=0.11187]

trial_002 train e006:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:34,  1.43it/s, avg=0.10117, loss=0.11187]

trial_002 train e006:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:34,  1.43it/s, avg=0.10117, loss=0.10032]

trial_002 train e006:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:33,  1.41it/s, avg=0.10117, loss=0.10032]

trial_002 train e006:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:33,  1.41it/s, avg=0.10115, loss=0.09928]

trial_002 train e006:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:33,  1.42it/s, avg=0.10115, loss=0.09928]

trial_002 train e006:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:33,  1.42it/s, avg=0.10117, loss=0.10308]

trial_002 train e006:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:32,  1.40it/s, avg=0.10117, loss=0.10308]

trial_002 train e006:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:32,  1.40it/s, avg=0.10129, loss=0.11425]

trial_002 train e006:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.39it/s, avg=0.10129, loss=0.11425]

trial_002 train e006:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.39it/s, avg=0.10126, loss=0.09847]

trial_002 train e006:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.41it/s, avg=0.10126, loss=0.09847]

trial_002 train e006:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.41it/s, avg=0.10121, loss=0.09595]

trial_002 train e006:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:30,  1.41it/s, avg=0.10121, loss=0.09595]

trial_002 train e006:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:30,  1.41it/s, avg=0.10105, loss=0.08372]

trial_002 train e006:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:30,  1.39it/s, avg=0.10105, loss=0.08372]

trial_002 train e006:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:30,  1.39it/s, avg=0.10113, loss=0.10982]

trial_002 train e006:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:29,  1.39it/s, avg=0.10113, loss=0.10982]

trial_002 train e006:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:29,  1.39it/s, avg=0.10113, loss=0.10120]

trial_002 train e006:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:17<00:28,  1.42it/s, avg=0.10113, loss=0.10120]

trial_002 train e006:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:28,  1.42it/s, avg=0.10124, loss=0.11347]

trial_002 train e006:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:27,  1.43it/s, avg=0.10124, loss=0.11347]

trial_002 train e006:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:27,  1.43it/s, avg=0.10115, loss=0.09038]

trial_002 train e006:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.40it/s, avg=0.10115, loss=0.09038]

trial_002 train e006:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.40it/s, avg=0.10116, loss=0.10309]

trial_002 train e006:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.40it/s, avg=0.10116, loss=0.10309]

trial_002 train e006:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.40it/s, avg=0.10112, loss=0.09643]

trial_002 train e006:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:20<00:25,  1.39it/s, avg=0.10112, loss=0.09643]

trial_002 train e006:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.39it/s, avg=0.10102, loss=0.08971]

trial_002 train e006:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:25,  1.39it/s, avg=0.10102, loss=0.08971]

trial_002 train e006:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:25,  1.39it/s, avg=0.10112, loss=0.11224]

trial_002 train e006:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:24,  1.38it/s, avg=0.10112, loss=0.11224]

trial_002 train e006:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:24,  1.38it/s, avg=0.10114, loss=0.10350]

trial_002 train e006:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:22<00:23,  1.40it/s, avg=0.10114, loss=0.10350]

trial_002 train e006:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.40it/s, avg=0.10106, loss=0.09219]

trial_002 train e006:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:23,  1.38it/s, avg=0.10106, loss=0.09219]

trial_002 train e006:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:23,  1.38it/s, avg=0.10090, loss=0.08214]

trial_002 train e006:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:22,  1.38it/s, avg=0.10090, loss=0.08214]

trial_002 train e006:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.38it/s, avg=0.10097, loss=0.10867]

trial_002 train e006:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.40it/s, avg=0.10097, loss=0.10867]

trial_002 train e006:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.40it/s, avg=0.10101, loss=0.10653]

trial_002 train e006:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:20,  1.39it/s, avg=0.10101, loss=0.10653]

trial_002 train e006:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.39it/s, avg=0.10092, loss=0.08960]

trial_002 train e006:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:20,  1.39it/s, avg=0.10092, loss=0.08960]

trial_002 train e006:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:20,  1.39it/s, avg=0.10096, loss=0.10562]

trial_002 train e006:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.38it/s, avg=0.10096, loss=0.10562]

trial_002 train e006:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.38it/s, avg=0.10096, loss=0.10146]

trial_002 train e006:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:27<00:18,  1.41it/s, avg=0.10096, loss=0.10146]

trial_002 train e006:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.41it/s, avg=0.10110, loss=0.11737]

trial_002 train e006:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.41it/s, avg=0.10110, loss=0.11737]

trial_002 train e006:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.41it/s, avg=0.10104, loss=0.09445]

trial_002 train e006:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:16,  1.44it/s, avg=0.10104, loss=0.09445]

trial_002 train e006:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:16,  1.44it/s, avg=0.10111, loss=0.10934]

trial_002 train e006:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.43it/s, avg=0.10111, loss=0.10934]

trial_002 train e006:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.43it/s, avg=0.10107, loss=0.09573]

trial_002 train e006:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.41it/s, avg=0.10107, loss=0.09573]

trial_002 train e006:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.41it/s, avg=0.10108, loss=0.10275]

trial_002 train e006:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.39it/s, avg=0.10108, loss=0.10275]

trial_002 train e006:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.39it/s, avg=0.10109, loss=0.10205]

trial_002 train e006:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.40it/s, avg=0.10109, loss=0.10205]

trial_002 train e006:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.40it/s, avg=0.10105, loss=0.09686]

trial_002 train e006:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:32<00:13,  1.40it/s, avg=0.10105, loss=0.09686]

trial_002 train e006:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.40it/s, avg=0.10101, loss=0.09570]

trial_002 train e006:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:12,  1.39it/s, avg=0.10101, loss=0.09570]

trial_002 train e006:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:12,  1.39it/s, avg=0.10094, loss=0.09175]

trial_002 train e006:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.39it/s, avg=0.10094, loss=0.09175]

trial_002 train e006:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.39it/s, avg=0.10100, loss=0.10895]

trial_002 train e006:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.40it/s, avg=0.10100, loss=0.10895]

trial_002 train e006:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.40it/s, avg=0.10103, loss=0.10415]

trial_002 train e006:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.40it/s, avg=0.10103, loss=0.10415]

trial_002 train e006:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.40it/s, avg=0.10089, loss=0.08282]

trial_002 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.36it/s, avg=0.10089, loss=0.08282]

trial_002 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.36it/s, avg=0.10088, loss=0.09921]

trial_002 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.36it/s, avg=0.10088, loss=0.09921]

trial_002 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.36it/s, avg=0.10089, loss=0.10271]

trial_002 train e006:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.35it/s, avg=0.10089, loss=0.10271]

trial_002 train e006:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.35it/s, avg=0.10100, loss=0.11595]

trial_002 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:08,  1.35it/s, avg=0.10100, loss=0.11595]

trial_002 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:08,  1.35it/s, avg=0.10104, loss=0.10614]

trial_002 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.36it/s, avg=0.10104, loss=0.10614]

trial_002 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.36it/s, avg=0.10097, loss=0.09084]

trial_002 train e006:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.36it/s, avg=0.10097, loss=0.09084]

trial_002 train e006:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.36it/s, avg=0.10105, loss=0.11261]

trial_002 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.36it/s, avg=0.10105, loss=0.11261]

trial_002 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.36it/s, avg=0.10102, loss=0.09681]

trial_002 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:05,  1.35it/s, avg=0.10102, loss=0.09681]

trial_002 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:05,  1.35it/s, avg=0.10113, loss=0.11745]

trial_002 train e006:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.34it/s, avg=0.10113, loss=0.11745]

trial_002 train e006:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.34it/s, avg=0.10113, loss=0.10098]

trial_002 train e006:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.36it/s, avg=0.10113, loss=0.10098]

trial_002 train e006:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.36it/s, avg=0.10110, loss=0.09699]

trial_002 train e006:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.40it/s, avg=0.10110, loss=0.09699]

trial_002 train e006:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.40it/s, avg=0.10116, loss=0.11002]

trial_002 train e006:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.43it/s, avg=0.10116, loss=0.11002]

trial_002 train e006:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.43it/s, avg=0.10116, loss=0.10036]

trial_002 train e006:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.40it/s, avg=0.10116, loss=0.10036]

trial_002 train e006:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.40it/s, avg=0.10112, loss=0.09528]

trial_002 train e006:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.39it/s, avg=0.10112, loss=0.09528]

trial_002 train e006:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.39it/s, avg=0.10114, loss=0.10711]

trial_002 train e006: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:46<00:00,  1.69it/s, avg=0.10114, loss=0.10711]

trial_002 val e006:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e006:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.37it/s]

trial_002 val e006:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.37it/s]

trial_002 val e006:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.38it/s]

trial_002 val e006:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.41it/s]

trial_002 val e006:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.43it/s]

trial_002 val e006:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.44it/s]

trial_002 val e006:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.45it/s]

trial_002 val e006:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.46it/s]

trial_002 val e006:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.48it/s]

trial_002 val e006:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.47it/s]

trial_002 val e006:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.47it/s]

trial_002 val e006:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.47it/s]

trial_002 val e006:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:14,  2.48it/s]

trial_002 val e006:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.47it/s]

trial_002 val e006:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.44it/s]

trial_002 val e006:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.39it/s]

trial_002 val e006:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.41it/s]

trial_002 val e006:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.42it/s]

trial_002 val e006:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.45it/s]

trial_002 val e006:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.44it/s]

trial_002 val e006:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.44it/s]

trial_002 val e006:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.44it/s]

trial_002 val e006:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.44it/s]

trial_002 val e006:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.46it/s]

trial_002 val e006:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.45it/s]

trial_002 val e006:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.45it/s]

trial_002 val e006:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.45it/s]

trial_002 val e006:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.43it/s]

trial_002 val e006:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.43it/s]

trial_002 val e006:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.41it/s]

trial_002 val e006:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.42it/s]

trial_002 val e006:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.43it/s]

trial_002 val e006:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.45it/s]

trial_002 val e006:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.46it/s]

trial_002 val e006:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.47it/s]

trial_002 val e006:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.47it/s]

trial_002 val e006:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.48it/s]

trial_002 val e006:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.48it/s]

trial_002 val e006:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.48it/s]

trial_002 val e006:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.48it/s]

trial_002 val e006:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.46it/s]

trial_002 val e006:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.44it/s]

trial_002 val e006:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.44it/s]

trial_002 val e006:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.45it/s]

trial_002 val e006:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.47it/s]

trial_002 val e006:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.48it/s]

trial_002 val e006:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.49it/s]

trial_002 val e006:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.49it/s]

trial_002 val e006:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.49it/s]

trial_002 val e006: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.51it/s]

[2026-05-28 20:37:02] [trial_002] epoch=006 | train_loss=0.101136 | val_MAE=0.103110 | val_S=0.896890 | best_S=0.897148 @epoch=5 | patience=1/5

[trial_002] epochs:   6%|███████▎                                                                                                                 | 6/100 [13:25<3:24:17, 130.40s/it]

trial_002 train e007:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e007:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10392, loss=0.10392]

trial_002 train e007:   1%|▋                                                                                              | 1/149 [00:00<01:46,  1.39it/s, avg=0.10392, loss=0.10392]

trial_002 train e007:   1%|▋                                                                                              | 1/149 [00:01<01:46,  1.39it/s, avg=0.10447, loss=0.10501]

trial_002 train e007:   1%|█▎                                                                                             | 2/149 [00:01<01:45,  1.40it/s, avg=0.10447, loss=0.10501]

trial_002 train e007:   1%|█▎                                                                                             | 2/149 [00:02<01:45,  1.40it/s, avg=0.10519, loss=0.10663]

trial_002 train e007:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.10519, loss=0.10663]

trial_002 train e007:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.10247, loss=0.09432]

trial_002 train e007:   3%|██▌                                                                                            | 4/149 [00:02<01:44,  1.38it/s, avg=0.10247, loss=0.09432]

trial_002 train e007:   3%|██▌                                                                                            | 4/149 [00:03<01:44,  1.38it/s, avg=0.10227, loss=0.10148]

trial_002 train e007:   3%|███▏                                                                                           | 5/149 [00:03<01:45,  1.37it/s, avg=0.10227, loss=0.10148]

trial_002 train e007:   3%|███▏                                                                                           | 5/149 [00:04<01:45,  1.37it/s, avg=0.10472, loss=0.11696]

trial_002 train e007:   4%|███▊                                                                                           | 6/149 [00:04<01:43,  1.38it/s, avg=0.10472, loss=0.11696]

trial_002 train e007:   4%|███▊                                                                                           | 6/149 [00:05<01:43,  1.38it/s, avg=0.10419, loss=0.10100]

trial_002 train e007:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.10419, loss=0.10100]

trial_002 train e007:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.10590, loss=0.11789]

trial_002 train e007:   5%|█████                                                                                          | 8/149 [00:05<01:42,  1.37it/s, avg=0.10590, loss=0.11789]

trial_002 train e007:   5%|█████                                                                                          | 8/149 [00:06<01:42,  1.37it/s, avg=0.10464, loss=0.09453]

trial_002 train e007:   6%|█████▋                                                                                         | 9/149 [00:06<01:41,  1.38it/s, avg=0.10464, loss=0.09453]

trial_002 train e007:   6%|█████▋                                                                                         | 9/149 [00:07<01:41,  1.38it/s, avg=0.10454, loss=0.10362]

trial_002 train e007:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.10454, loss=0.10362]

trial_002 train e007:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.10265, loss=0.08381]

trial_002 train e007:   7%|██████▉                                                                                       | 11/149 [00:07<01:39,  1.39it/s, avg=0.10265, loss=0.08381]

trial_002 train e007:   7%|██████▉                                                                                       | 11/149 [00:08<01:39,  1.39it/s, avg=0.10194, loss=0.09414]

trial_002 train e007:   8%|███████▌                                                                                      | 12/149 [00:08<01:38,  1.39it/s, avg=0.10194, loss=0.09414]

trial_002 train e007:   8%|███████▌                                                                                      | 12/149 [00:09<01:38,  1.39it/s, avg=0.10193, loss=0.10185]

trial_002 train e007:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.10193, loss=0.10185]

trial_002 train e007:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.10215, loss=0.10489]

trial_002 train e007:   9%|████████▊                                                                                     | 14/149 [00:10<01:37,  1.38it/s, avg=0.10215, loss=0.10489]

trial_002 train e007:   9%|████████▊                                                                                     | 14/149 [00:10<01:37,  1.38it/s, avg=0.10095, loss=0.08423]

trial_002 train e007:  10%|█████████▍                                                                                    | 15/149 [00:10<01:37,  1.37it/s, avg=0.10095, loss=0.08423]

trial_002 train e007:  10%|█████████▍                                                                                    | 15/149 [00:11<01:37,  1.37it/s, avg=0.10085, loss=0.09939]

trial_002 train e007:  11%|██████████                                                                                    | 16/149 [00:11<01:36,  1.38it/s, avg=0.10085, loss=0.09939]

trial_002 train e007:  11%|██████████                                                                                    | 16/149 [00:12<01:36,  1.38it/s, avg=0.10087, loss=0.10107]

trial_002 train e007:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.10087, loss=0.10107]

trial_002 train e007:  11%|██████████▋                                                                                   | 17/149 [00:13<01:36,  1.37it/s, avg=0.10072, loss=0.09828]

trial_002 train e007:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.37it/s, avg=0.10072, loss=0.09828]

trial_002 train e007:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.37it/s, avg=0.10129, loss=0.11142]

trial_002 train e007:  13%|███████████▉                                                                                  | 19/149 [00:13<01:35,  1.36it/s, avg=0.10129, loss=0.11142]

trial_002 train e007:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.36it/s, avg=0.10186, loss=0.11271]

trial_002 train e007:  13%|████████████▌                                                                                 | 20/149 [00:14<01:34,  1.37it/s, avg=0.10186, loss=0.11271]

trial_002 train e007:  13%|████████████▌                                                                                 | 20/149 [00:15<01:34,  1.37it/s, avg=0.10177, loss=0.10002]

trial_002 train e007:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.38it/s, avg=0.10177, loss=0.10002]

trial_002 train e007:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.38it/s, avg=0.10178, loss=0.10209]

trial_002 train e007:  15%|█████████████▉                                                                                | 22/149 [00:15<01:32,  1.37it/s, avg=0.10178, loss=0.10209]

trial_002 train e007:  15%|█████████████▉                                                                                | 22/149 [00:16<01:32,  1.37it/s, avg=0.10195, loss=0.10558]

trial_002 train e007:  15%|██████████████▌                                                                               | 23/149 [00:16<01:32,  1.36it/s, avg=0.10195, loss=0.10558]

trial_002 train e007:  15%|██████████████▌                                                                               | 23/149 [00:17<01:32,  1.36it/s, avg=0.10172, loss=0.09641]

trial_002 train e007:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.37it/s, avg=0.10172, loss=0.09641]

trial_002 train e007:  16%|███████████████▏                                                                              | 24/149 [00:18<01:31,  1.37it/s, avg=0.10218, loss=0.11336]

trial_002 train e007:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.10218, loss=0.11336]

trial_002 train e007:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.10222, loss=0.10317]

trial_002 train e007:  17%|████████████████▍                                                                             | 26/149 [00:18<01:28,  1.39it/s, avg=0.10222, loss=0.10317]

trial_002 train e007:  17%|████████████████▍                                                                             | 26/149 [00:19<01:28,  1.39it/s, avg=0.10184, loss=0.09190]

trial_002 train e007:  18%|█████████████████                                                                             | 27/149 [00:19<01:26,  1.41it/s, avg=0.10184, loss=0.09190]

trial_002 train e007:  18%|█████████████████                                                                             | 27/149 [00:20<01:26,  1.41it/s, avg=0.10188, loss=0.10288]

trial_002 train e007:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:26,  1.40it/s, avg=0.10188, loss=0.10288]

trial_002 train e007:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:26,  1.40it/s, avg=0.10222, loss=0.11169]

trial_002 train e007:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:23,  1.43it/s, avg=0.10222, loss=0.11169]

trial_002 train e007:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:23,  1.43it/s, avg=0.10237, loss=0.10685]

trial_002 train e007:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:25,  1.40it/s, avg=0.10237, loss=0.10685]

trial_002 train e007:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:25,  1.40it/s, avg=0.10262, loss=0.11005]

trial_002 train e007:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:24,  1.40it/s, avg=0.10262, loss=0.11005]

trial_002 train e007:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:24,  1.40it/s, avg=0.10222, loss=0.08995]

trial_002 train e007:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:23,  1.40it/s, avg=0.10222, loss=0.08995]

trial_002 train e007:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:23,  1.40it/s, avg=0.10262, loss=0.11537]

trial_002 train e007:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:24,  1.37it/s, avg=0.10262, loss=0.11537]

trial_002 train e007:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.10269, loss=0.10507]

trial_002 train e007:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.10269, loss=0.10507]

trial_002 train e007:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.10237, loss=0.09156]

trial_002 train e007:  23%|██████████████████████                                                                        | 35/149 [00:25<01:22,  1.38it/s, avg=0.10237, loss=0.09156]

trial_002 train e007:  23%|██████████████████████                                                                        | 35/149 [00:26<01:22,  1.38it/s, avg=0.10224, loss=0.09750]

trial_002 train e007:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.40it/s, avg=0.10224, loss=0.09750]

trial_002 train e007:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.40it/s, avg=0.10193, loss=0.09101]

trial_002 train e007:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:19,  1.41it/s, avg=0.10193, loss=0.09101]

trial_002 train e007:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:19,  1.41it/s, avg=0.10157, loss=0.08821]

trial_002 train e007:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:18,  1.42it/s, avg=0.10157, loss=0.08821]

trial_002 train e007:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:18,  1.42it/s, avg=0.10159, loss=0.10222]

trial_002 train e007:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:18,  1.39it/s, avg=0.10159, loss=0.10222]

trial_002 train e007:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:18,  1.39it/s, avg=0.10149, loss=0.09741]

trial_002 train e007:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:19,  1.38it/s, avg=0.10149, loss=0.09741]

trial_002 train e007:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.38it/s, avg=0.10155, loss=0.10427]

trial_002 train e007:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:18,  1.37it/s, avg=0.10155, loss=0.10427]

trial_002 train e007:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:18,  1.37it/s, avg=0.10159, loss=0.10287]

trial_002 train e007:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.10159, loss=0.10287]

trial_002 train e007:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:17,  1.38it/s, avg=0.10156, loss=0.10064]

trial_002 train e007:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.40it/s, avg=0.10156, loss=0.10064]

trial_002 train e007:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.40it/s, avg=0.10151, loss=0.09907]

trial_002 train e007:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:14,  1.41it/s, avg=0.10151, loss=0.09907]

trial_002 train e007:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.41it/s, avg=0.10153, loss=0.10275]

trial_002 train e007:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.10153, loss=0.10275]

trial_002 train e007:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:13,  1.41it/s, avg=0.10180, loss=0.11373]

trial_002 train e007:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:12,  1.42it/s, avg=0.10180, loss=0.11373]

trial_002 train e007:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:12,  1.42it/s, avg=0.10157, loss=0.09091]

trial_002 train e007:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.41it/s, avg=0.10157, loss=0.09091]

trial_002 train e007:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:12,  1.41it/s, avg=0.10145, loss=0.09580]

trial_002 train e007:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.39it/s, avg=0.10145, loss=0.09580]

trial_002 train e007:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:12,  1.39it/s, avg=0.10096, loss=0.07757]

trial_002 train e007:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.38it/s, avg=0.10096, loss=0.07757]

trial_002 train e007:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:12,  1.38it/s, avg=0.10066, loss=0.08576]

trial_002 train e007:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:09,  1.42it/s, avg=0.10066, loss=0.08576]

trial_002 train e007:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:09,  1.42it/s, avg=0.10072, loss=0.10413]

trial_002 train e007:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:09,  1.41it/s, avg=0.10072, loss=0.10413]

trial_002 train e007:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:09,  1.41it/s, avg=0.10061, loss=0.09494]

trial_002 train e007:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.41it/s, avg=0.10061, loss=0.09494]

trial_002 train e007:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:09,  1.41it/s, avg=0.10042, loss=0.09055]

trial_002 train e007:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:07,  1.43it/s, avg=0.10042, loss=0.09055]

trial_002 train e007:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:07,  1.43it/s, avg=0.10050, loss=0.10452]

trial_002 train e007:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:07,  1.41it/s, avg=0.10050, loss=0.10452]

trial_002 train e007:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:07,  1.41it/s, avg=0.10031, loss=0.09015]

trial_002 train e007:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:07,  1.39it/s, avg=0.10031, loss=0.09015]

trial_002 train e007:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:07,  1.39it/s, avg=0.10019, loss=0.09327]

trial_002 train e007:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:07,  1.38it/s, avg=0.10019, loss=0.09327]

trial_002 train e007:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.38it/s, avg=0.10016, loss=0.09898]

trial_002 train e007:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:06,  1.38it/s, avg=0.10016, loss=0.09898]

trial_002 train e007:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:06,  1.38it/s, avg=0.09985, loss=0.08168]

trial_002 train e007:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:06,  1.37it/s, avg=0.09985, loss=0.08168]

trial_002 train e007:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09983, loss=0.09920]

trial_002 train e007:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:04,  1.39it/s, avg=0.09983, loss=0.09920]

trial_002 train e007:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:04,  1.39it/s, avg=0.09967, loss=0.09016]

trial_002 train e007:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:04,  1.39it/s, avg=0.09967, loss=0.09016]

trial_002 train e007:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:04,  1.39it/s, avg=0.09971, loss=0.10220]

trial_002 train e007:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:03,  1.39it/s, avg=0.09971, loss=0.10220]

trial_002 train e007:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:03,  1.39it/s, avg=0.09980, loss=0.10481]

trial_002 train e007:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:02,  1.39it/s, avg=0.09980, loss=0.10481]

trial_002 train e007:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:02,  1.39it/s, avg=0.09985, loss=0.10333]

trial_002 train e007:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:01,  1.39it/s, avg=0.09985, loss=0.10333]

trial_002 train e007:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:01,  1.39it/s, avg=0.09985, loss=0.09949]

trial_002 train e007:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.39it/s, avg=0.09985, loss=0.09949]

trial_002 train e007:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.39it/s, avg=0.09977, loss=0.09473]

trial_002 train e007:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<01:00,  1.39it/s, avg=0.09977, loss=0.09473]

trial_002 train e007:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.39it/s, avg=0.10006, loss=0.11930]

trial_002 train e007:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.42it/s, avg=0.10006, loss=0.11930]

trial_002 train e007:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:58,  1.42it/s, avg=0.09975, loss=0.07914]

trial_002 train e007:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.41it/s, avg=0.09975, loss=0.07914]

trial_002 train e007:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.41it/s, avg=0.09964, loss=0.09233]

trial_002 train e007:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:58,  1.39it/s, avg=0.09964, loss=0.09233]

trial_002 train e007:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:58,  1.39it/s, avg=0.09949, loss=0.08907]

trial_002 train e007:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:56,  1.40it/s, avg=0.09949, loss=0.08907]

trial_002 train e007:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:56,  1.40it/s, avg=0.09955, loss=0.10397]

trial_002 train e007:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:57,  1.39it/s, avg=0.09955, loss=0.10397]

trial_002 train e007:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.39it/s, avg=0.09950, loss=0.09550]

trial_002 train e007:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:56,  1.38it/s, avg=0.09950, loss=0.09550]

trial_002 train e007:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:56,  1.38it/s, avg=0.09937, loss=0.09071]

trial_002 train e007:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:56,  1.36it/s, avg=0.09937, loss=0.09071]

trial_002 train e007:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:56,  1.36it/s, avg=0.09933, loss=0.09614]

trial_002 train e007:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:55,  1.38it/s, avg=0.09933, loss=0.09614]

trial_002 train e007:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:55,  1.38it/s, avg=0.09937, loss=0.10247]

trial_002 train e007:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:54,  1.38it/s, avg=0.09937, loss=0.10247]

trial_002 train e007:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:54,  1.38it/s, avg=0.09950, loss=0.10856]

trial_002 train e007:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.37it/s, avg=0.09950, loss=0.10856]

trial_002 train e007:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.37it/s, avg=0.09943, loss=0.09434]

trial_002 train e007:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:52,  1.38it/s, avg=0.09943, loss=0.09434]

trial_002 train e007:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:52,  1.38it/s, avg=0.09950, loss=0.10507]

trial_002 train e007:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:52,  1.38it/s, avg=0.09950, loss=0.10507]

trial_002 train e007:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:52,  1.38it/s, avg=0.09959, loss=0.10666]

trial_002 train e007:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.38it/s, avg=0.09959, loss=0.10666]

trial_002 train e007:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.38it/s, avg=0.09955, loss=0.09657]

trial_002 train e007:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.38it/s, avg=0.09955, loss=0.09657]

trial_002 train e007:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:50,  1.38it/s, avg=0.09948, loss=0.09385]

trial_002 train e007:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:50,  1.36it/s, avg=0.09948, loss=0.09385]

trial_002 train e007:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.36it/s, avg=0.09955, loss=0.10504]

trial_002 train e007:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:49,  1.37it/s, avg=0.09955, loss=0.10504]

trial_002 train e007:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:49,  1.37it/s, avg=0.09972, loss=0.11364]

trial_002 train e007:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:49,  1.36it/s, avg=0.09972, loss=0.11364]

trial_002 train e007:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:49,  1.36it/s, avg=0.09964, loss=0.09288]

trial_002 train e007:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:47,  1.38it/s, avg=0.09964, loss=0.09288]

trial_002 train e007:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:47,  1.38it/s, avg=0.09946, loss=0.08480]

trial_002 train e007:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:47,  1.36it/s, avg=0.09946, loss=0.08480]

trial_002 train e007:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:47,  1.36it/s, avg=0.09951, loss=0.10349]

trial_002 train e007:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.39it/s, avg=0.09951, loss=0.10349]

trial_002 train e007:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.39it/s, avg=0.09948, loss=0.09706]

trial_002 train e007:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:44,  1.40it/s, avg=0.09948, loss=0.09706]

trial_002 train e007:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:44,  1.40it/s, avg=0.09949, loss=0.10001]

trial_002 train e007:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.38it/s, avg=0.09949, loss=0.10001]

trial_002 train e007:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.38it/s, avg=0.09945, loss=0.09594]

trial_002 train e007:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:44,  1.36it/s, avg=0.09945, loss=0.09594]

trial_002 train e007:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.36it/s, avg=0.09962, loss=0.11474]

trial_002 train e007:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.37it/s, avg=0.09962, loss=0.11474]

trial_002 train e007:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:43,  1.37it/s, avg=0.09965, loss=0.10227]

trial_002 train e007:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:44,  1.34it/s, avg=0.09965, loss=0.10227]

trial_002 train e007:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:44,  1.34it/s, avg=0.09968, loss=0.10209]

trial_002 train e007:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:43,  1.35it/s, avg=0.09968, loss=0.10209]

trial_002 train e007:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:43,  1.35it/s, avg=0.09958, loss=0.09111]

trial_002 train e007:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:42,  1.33it/s, avg=0.09958, loss=0.09111]

trial_002 train e007:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:42,  1.33it/s, avg=0.09953, loss=0.09431]

trial_002 train e007:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:42,  1.33it/s, avg=0.09953, loss=0.09431]

trial_002 train e007:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:42,  1.33it/s, avg=0.09947, loss=0.09458]

trial_002 train e007:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:41,  1.33it/s, avg=0.09947, loss=0.09458]

trial_002 train e007:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:41,  1.33it/s, avg=0.09948, loss=0.10044]

trial_002 train e007:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:40,  1.34it/s, avg=0.09948, loss=0.10044]

trial_002 train e007:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:40,  1.34it/s, avg=0.09952, loss=0.10318]

trial_002 train e007:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:39,  1.35it/s, avg=0.09952, loss=0.10318]

trial_002 train e007:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:39,  1.35it/s, avg=0.09966, loss=0.11298]

trial_002 train e007:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:38,  1.34it/s, avg=0.09966, loss=0.11298]

trial_002 train e007:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:38,  1.34it/s, avg=0.09965, loss=0.09891]

trial_002 train e007:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:37,  1.35it/s, avg=0.09965, loss=0.09891]

trial_002 train e007:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.35it/s, avg=0.09964, loss=0.09863]

trial_002 train e007:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:35,  1.41it/s, avg=0.09964, loss=0.09863]

trial_002 train e007:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:35,  1.41it/s, avg=0.09958, loss=0.09372]

trial_002 train e007:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:34,  1.43it/s, avg=0.09958, loss=0.09372]

trial_002 train e007:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:34,  1.43it/s, avg=0.09939, loss=0.07978]

trial_002 train e007:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.41it/s, avg=0.09939, loss=0.07978]

trial_002 train e007:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.41it/s, avg=0.09950, loss=0.11032]

trial_002 train e007:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:33,  1.41it/s, avg=0.09950, loss=0.11032]

trial_002 train e007:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:33,  1.41it/s, avg=0.09971, loss=0.12210]

trial_002 train e007:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.39it/s, avg=0.09971, loss=0.12210]

trial_002 train e007:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.39it/s, avg=0.09988, loss=0.11654]

trial_002 train e007:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.37it/s, avg=0.09988, loss=0.11654]

trial_002 train e007:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.37it/s, avg=0.09997, loss=0.10941]

trial_002 train e007:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:32,  1.35it/s, avg=0.09997, loss=0.10941]

trial_002 train e007:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:32,  1.35it/s, avg=0.09996, loss=0.09906]

trial_002 train e007:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:31,  1.37it/s, avg=0.09996, loss=0.09906]

trial_002 train e007:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.37it/s, avg=0.09999, loss=0.10335]

trial_002 train e007:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:30,  1.37it/s, avg=0.09999, loss=0.10335]

trial_002 train e007:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.37it/s, avg=0.09994, loss=0.09447]

trial_002 train e007:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:30,  1.36it/s, avg=0.09994, loss=0.09447]

trial_002 train e007:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:30,  1.36it/s, avg=0.10000, loss=0.10661]

trial_002 train e007:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:29,  1.36it/s, avg=0.10000, loss=0.10661]

trial_002 train e007:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:29,  1.36it/s, avg=0.10001, loss=0.10048]

trial_002 train e007:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:28,  1.35it/s, avg=0.10001, loss=0.10048]

trial_002 train e007:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.35it/s, avg=0.10002, loss=0.10214]

trial_002 train e007:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.36it/s, avg=0.10002, loss=0.10214]

trial_002 train e007:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.36it/s, avg=0.10002, loss=0.09907]

trial_002 train e007:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:26,  1.37it/s, avg=0.10002, loss=0.09907]

trial_002 train e007:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:26,  1.37it/s, avg=0.10002, loss=0.10070]

trial_002 train e007:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.39it/s, avg=0.10002, loss=0.10070]

trial_002 train e007:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:25,  1.39it/s, avg=0.09988, loss=0.08369]

trial_002 train e007:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:24,  1.41it/s, avg=0.09988, loss=0.08369]

trial_002 train e007:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:24,  1.41it/s, avg=0.09997, loss=0.11069]

trial_002 train e007:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.39it/s, avg=0.09997, loss=0.11069]

trial_002 train e007:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.39it/s, avg=0.09998, loss=0.10024]

trial_002 train e007:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.40it/s, avg=0.09998, loss=0.10024]

trial_002 train e007:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.40it/s, avg=0.10005, loss=0.10907]

trial_002 train e007:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:23,  1.38it/s, avg=0.10005, loss=0.10907]

trial_002 train e007:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.38it/s, avg=0.10007, loss=0.10210]

trial_002 train e007:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.37it/s, avg=0.10007, loss=0.10210]

trial_002 train e007:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.37it/s, avg=0.10019, loss=0.11449]

trial_002 train e007:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:21,  1.42it/s, avg=0.10019, loss=0.11449]

trial_002 train e007:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:21,  1.42it/s, avg=0.10009, loss=0.08785]

trial_002 train e007:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.43it/s, avg=0.10009, loss=0.08785]

trial_002 train e007:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:20,  1.43it/s, avg=0.10004, loss=0.09433]

trial_002 train e007:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:19,  1.40it/s, avg=0.10004, loss=0.09433]

trial_002 train e007:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:19,  1.40it/s, avg=0.10000, loss=0.09446]

trial_002 train e007:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.38it/s, avg=0.10000, loss=0.09446]

trial_002 train e007:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.38it/s, avg=0.09989, loss=0.08705]

trial_002 train e007:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.39it/s, avg=0.09989, loss=0.08705]

trial_002 train e007:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:18,  1.39it/s, avg=0.10005, loss=0.11916]

trial_002 train e007:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.43it/s, avg=0.10005, loss=0.11916]

trial_002 train e007:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:17,  1.43it/s, avg=0.10010, loss=0.10689]

trial_002 train e007:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:16,  1.42it/s, avg=0.10010, loss=0.10689]

trial_002 train e007:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:16,  1.42it/s, avg=0.10013, loss=0.10346]

trial_002 train e007:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.41it/s, avg=0.10013, loss=0.10346]

trial_002 train e007:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.41it/s, avg=0.10012, loss=0.09873]

trial_002 train e007:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.42it/s, avg=0.10012, loss=0.09873]

trial_002 train e007:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:15,  1.42it/s, avg=0.10013, loss=0.10252]

trial_002 train e007:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.40it/s, avg=0.10013, loss=0.10252]

trial_002 train e007:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.40it/s, avg=0.10006, loss=0.09021]

trial_002 train e007:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.40it/s, avg=0.10006, loss=0.09021]

trial_002 train e007:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.40it/s, avg=0.10018, loss=0.11565]

trial_002 train e007:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.40it/s, avg=0.10018, loss=0.11565]

trial_002 train e007:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.40it/s, avg=0.10008, loss=0.08706]

trial_002 train e007:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:12,  1.39it/s, avg=0.10008, loss=0.08706]

trial_002 train e007:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:12,  1.39it/s, avg=0.10012, loss=0.10540]

trial_002 train e007:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.39it/s, avg=0.10012, loss=0.10540]

trial_002 train e007:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.39it/s, avg=0.10019, loss=0.10930]

trial_002 train e007:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.38it/s, avg=0.10019, loss=0.10930]

trial_002 train e007:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.38it/s, avg=0.10021, loss=0.10303]

trial_002 train e007:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.37it/s, avg=0.10021, loss=0.10303]

trial_002 train e007:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:10,  1.37it/s, avg=0.10010, loss=0.08562]

trial_002 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.36it/s, avg=0.10010, loss=0.08562]

trial_002 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.36it/s, avg=0.10007, loss=0.09609]

trial_002 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.39it/s, avg=0.10007, loss=0.09609]

trial_002 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.39it/s, avg=0.10010, loss=0.10467]

trial_002 train e007:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.39it/s, avg=0.10010, loss=0.10467]

trial_002 train e007:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.39it/s, avg=0.10011, loss=0.10107]

trial_002 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:07,  1.40it/s, avg=0.10011, loss=0.10107]

trial_002 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:07,  1.40it/s, avg=0.10008, loss=0.09603]

trial_002 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.42it/s, avg=0.10008, loss=0.09603]

trial_002 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.42it/s, avg=0.10007, loss=0.09895]

trial_002 train e007:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.39it/s, avg=0.10007, loss=0.09895]

trial_002 train e007:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.39it/s, avg=0.10006, loss=0.09813]

trial_002 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.41it/s, avg=0.10006, loss=0.09813]

trial_002 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.41it/s, avg=0.10002, loss=0.09420]

trial_002 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:04,  1.42it/s, avg=0.10002, loss=0.09420]

trial_002 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:04,  1.42it/s, avg=0.10000, loss=0.09734]

trial_002 train e007:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.39it/s, avg=0.10000, loss=0.09734]

trial_002 train e007:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.39it/s, avg=0.09991, loss=0.08694]

trial_002 train e007:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.41it/s, avg=0.09991, loss=0.08694]

trial_002 train e007:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.41it/s, avg=0.09991, loss=0.09970]

trial_002 train e007:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.39it/s, avg=0.09991, loss=0.09970]

trial_002 train e007:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.39it/s, avg=0.09984, loss=0.09048]

trial_002 train e007:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.39it/s, avg=0.09984, loss=0.09048]

trial_002 train e007:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.39it/s, avg=0.09987, loss=0.10321]

trial_002 train e007:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.37it/s, avg=0.09987, loss=0.10321]

trial_002 train e007:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.37it/s, avg=0.09986, loss=0.09967]

trial_002 train e007:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.38it/s, avg=0.09986, loss=0.09967]

trial_002 train e007:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.38it/s, avg=0.09989, loss=0.10879]

trial_002 train e007: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:47<00:00,  1.69it/s, avg=0.09989, loss=0.10879]

trial_002 val e007:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e007:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.34it/s]

trial_002 val e007:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.36it/s]

trial_002 val e007:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.34it/s]

trial_002 val e007:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.38it/s]

trial_002 val e007:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.40it/s]

trial_002 val e007:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.41it/s]

trial_002 val e007:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.41it/s]

trial_002 val e007:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.43it/s]

trial_002 val e007:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.43it/s]

trial_002 val e007:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.41it/s]

trial_002 val e007:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.38it/s]

trial_002 val e007:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:15,  2.39it/s]

trial_002 val e007:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.37it/s]

trial_002 val e007:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:15,  2.36it/s]

trial_002 val e007:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.38it/s]

trial_002 val e007:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.40it/s]

trial_002 val e007:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.41it/s]

trial_002 val e007:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.41it/s]

trial_002 val e007:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.42it/s]

trial_002 val e007:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.43it/s]

trial_002 val e007:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.39it/s]

trial_002 val e007:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.33it/s]

trial_002 val e007:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.37it/s]

trial_002 val e007:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:10,  2.38it/s]

trial_002 val e007:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.41it/s]

trial_002 val e007:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.43it/s]

trial_002 val e007:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.45it/s]

trial_002 val e007:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.46it/s]

trial_002 val e007:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:08,  2.47it/s]

trial_002 val e007:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.48it/s]

trial_002 val e007:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.48it/s]

trial_002 val e007:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.48it/s]

trial_002 val e007:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.48it/s]

trial_002 val e007:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.48it/s]

trial_002 val e007:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.48it/s]

trial_002 val e007:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.48it/s]

trial_002 val e007:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.45it/s]

trial_002 val e007:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.44it/s]

trial_002 val e007:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.44it/s]

trial_002 val e007:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.46it/s]

trial_002 val e007:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.47it/s]

trial_002 val e007:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.47it/s]

trial_002 val e007:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.48it/s]

trial_002 val e007:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.48it/s]

trial_002 val e007:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.48it/s]

trial_002 val e007:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.48it/s]

trial_002 val e007:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.48it/s]

trial_002 val e007:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.47it/s]

trial_002 val e007:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.47it/s]

trial_002 val e007: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.49it/s]

[2026-05-28 20:39:11] [trial_002] epoch=007 | train_loss=0.099889 | val_MAE=0.100945 | val_S=0.899055 | best_S=0.899055 @epoch=7 | patience=0/5

[trial_002] epochs:   7%|████████▍                                                                                                                | 7/100 [15:34<3:21:23, 129.93s/it]

trial_002 train e008:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e008:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09483, loss=0.09483]

trial_002 train e008:   1%|▋                                                                                              | 1/149 [00:00<01:38,  1.50it/s, avg=0.09483, loss=0.09483]

trial_002 train e008:   1%|▋                                                                                              | 1/149 [00:01<01:38,  1.50it/s, avg=0.09975, loss=0.10467]

trial_002 train e008:   1%|█▎                                                                                             | 2/149 [00:01<01:42,  1.44it/s, avg=0.09975, loss=0.10467]

trial_002 train e008:   1%|█▎                                                                                             | 2/149 [00:02<01:42,  1.44it/s, avg=0.09745, loss=0.09286]

trial_002 train e008:   2%|█▉                                                                                             | 3/149 [00:02<01:44,  1.39it/s, avg=0.09745, loss=0.09286]

trial_002 train e008:   2%|█▉                                                                                             | 3/149 [00:02<01:44,  1.39it/s, avg=0.09554, loss=0.08978]

trial_002 train e008:   3%|██▌                                                                                            | 4/149 [00:02<01:42,  1.41it/s, avg=0.09554, loss=0.08978]

trial_002 train e008:   3%|██▌                                                                                            | 4/149 [00:03<01:42,  1.41it/s, avg=0.09628, loss=0.09927]

trial_002 train e008:   3%|███▏                                                                                           | 5/149 [00:03<01:43,  1.39it/s, avg=0.09628, loss=0.09927]

trial_002 train e008:   3%|███▏                                                                                           | 5/149 [00:04<01:43,  1.39it/s, avg=0.09564, loss=0.09240]

trial_002 train e008:   4%|███▊                                                                                           | 6/149 [00:04<01:44,  1.37it/s, avg=0.09564, loss=0.09240]

trial_002 train e008:   4%|███▊                                                                                           | 6/149 [00:05<01:44,  1.37it/s, avg=0.09694, loss=0.10474]

trial_002 train e008:   5%|████▍                                                                                          | 7/149 [00:05<01:43,  1.37it/s, avg=0.09694, loss=0.10474]

trial_002 train e008:   5%|████▍                                                                                          | 7/149 [00:05<01:43,  1.37it/s, avg=0.09655, loss=0.09384]

trial_002 train e008:   5%|█████                                                                                          | 8/149 [00:05<01:39,  1.41it/s, avg=0.09655, loss=0.09384]

trial_002 train e008:   5%|█████                                                                                          | 8/149 [00:06<01:39,  1.41it/s, avg=0.09831, loss=0.11238]

trial_002 train e008:   6%|█████▋                                                                                         | 9/149 [00:06<01:40,  1.39it/s, avg=0.09831, loss=0.11238]

trial_002 train e008:   6%|█████▋                                                                                         | 9/149 [00:07<01:40,  1.39it/s, avg=0.09799, loss=0.09517]

trial_002 train e008:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.42it/s, avg=0.09799, loss=0.09517]

trial_002 train e008:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.42it/s, avg=0.09805, loss=0.09863]

trial_002 train e008:   7%|██████▉                                                                                       | 11/149 [00:07<01:37,  1.42it/s, avg=0.09805, loss=0.09863]

trial_002 train e008:   7%|██████▉                                                                                       | 11/149 [00:08<01:37,  1.42it/s, avg=0.09793, loss=0.09656]

trial_002 train e008:   8%|███████▌                                                                                      | 12/149 [00:08<01:38,  1.39it/s, avg=0.09793, loss=0.09656]

trial_002 train e008:   8%|███████▌                                                                                      | 12/149 [00:09<01:38,  1.39it/s, avg=0.09793, loss=0.09792]

trial_002 train e008:   9%|████████▏                                                                                     | 13/149 [00:09<01:35,  1.42it/s, avg=0.09793, loss=0.09792]

trial_002 train e008:   9%|████████▏                                                                                     | 13/149 [00:09<01:35,  1.42it/s, avg=0.09867, loss=0.10837]

trial_002 train e008:   9%|████████▊                                                                                     | 14/149 [00:09<01:33,  1.45it/s, avg=0.09867, loss=0.10837]

trial_002 train e008:   9%|████████▊                                                                                     | 14/149 [00:10<01:33,  1.45it/s, avg=0.09926, loss=0.10752]

trial_002 train e008:  10%|█████████▍                                                                                    | 15/149 [00:10<01:36,  1.39it/s, avg=0.09926, loss=0.10752]

trial_002 train e008:  10%|█████████▍                                                                                    | 15/149 [00:11<01:36,  1.39it/s, avg=0.09935, loss=0.10073]

trial_002 train e008:  11%|██████████                                                                                    | 16/149 [00:11<01:35,  1.39it/s, avg=0.09935, loss=0.10073]

trial_002 train e008:  11%|██████████                                                                                    | 16/149 [00:12<01:35,  1.39it/s, avg=0.10032, loss=0.11576]

trial_002 train e008:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.39it/s, avg=0.10032, loss=0.11576]

trial_002 train e008:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.39it/s, avg=0.10072, loss=0.10755]

trial_002 train e008:  12%|███████████▎                                                                                  | 18/149 [00:12<01:33,  1.39it/s, avg=0.10072, loss=0.10755]

trial_002 train e008:  12%|███████████▎                                                                                  | 18/149 [00:13<01:33,  1.39it/s, avg=0.10123, loss=0.11045]

trial_002 train e008:  13%|███████████▉                                                                                  | 19/149 [00:13<01:31,  1.42it/s, avg=0.10123, loss=0.11045]

trial_002 train e008:  13%|███████████▉                                                                                  | 19/149 [00:14<01:31,  1.42it/s, avg=0.10136, loss=0.10375]

trial_002 train e008:  13%|████████████▌                                                                                 | 20/149 [00:14<01:32,  1.39it/s, avg=0.10136, loss=0.10375]

trial_002 train e008:  13%|████████████▌                                                                                 | 20/149 [00:14<01:32,  1.39it/s, avg=0.10167, loss=0.10783]

trial_002 train e008:  14%|█████████████▏                                                                                | 21/149 [00:14<01:31,  1.39it/s, avg=0.10167, loss=0.10783]

trial_002 train e008:  14%|█████████████▏                                                                                | 21/149 [00:15<01:31,  1.39it/s, avg=0.10076, loss=0.08181]

trial_002 train e008:  15%|█████████████▉                                                                                | 22/149 [00:15<01:31,  1.38it/s, avg=0.10076, loss=0.08181]

trial_002 train e008:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.38it/s, avg=0.10077, loss=0.10089]

trial_002 train e008:  15%|██████████████▌                                                                               | 23/149 [00:16<01:29,  1.41it/s, avg=0.10077, loss=0.10089]

trial_002 train e008:  15%|██████████████▌                                                                               | 23/149 [00:17<01:29,  1.41it/s, avg=0.10062, loss=0.09710]

trial_002 train e008:  16%|███████████████▏                                                                              | 24/149 [00:17<01:27,  1.42it/s, avg=0.10062, loss=0.09710]

trial_002 train e008:  16%|███████████████▏                                                                              | 24/149 [00:17<01:27,  1.42it/s, avg=0.10011, loss=0.08793]

trial_002 train e008:  17%|███████████████▊                                                                              | 25/149 [00:17<01:27,  1.42it/s, avg=0.10011, loss=0.08793]

trial_002 train e008:  17%|███████████████▊                                                                              | 25/149 [00:18<01:27,  1.42it/s, avg=0.10072, loss=0.11610]

trial_002 train e008:  17%|████████████████▍                                                                             | 26/149 [00:18<01:26,  1.41it/s, avg=0.10072, loss=0.11610]

trial_002 train e008:  17%|████████████████▍                                                                             | 26/149 [00:19<01:26,  1.41it/s, avg=0.10033, loss=0.09006]

trial_002 train e008:  18%|█████████████████                                                                             | 27/149 [00:19<01:24,  1.44it/s, avg=0.10033, loss=0.09006]

trial_002 train e008:  18%|█████████████████                                                                             | 27/149 [00:19<01:24,  1.44it/s, avg=0.10003, loss=0.09197]

trial_002 train e008:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:26,  1.41it/s, avg=0.10003, loss=0.09197]

trial_002 train e008:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:26,  1.41it/s, avg=0.09997, loss=0.09824]

trial_002 train e008:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:25,  1.40it/s, avg=0.09997, loss=0.09824]

trial_002 train e008:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:25,  1.40it/s, avg=0.09976, loss=0.09364]

trial_002 train e008:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:26,  1.38it/s, avg=0.09976, loss=0.09364]

trial_002 train e008:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:26,  1.38it/s, avg=0.09947, loss=0.09072]

trial_002 train e008:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:24,  1.39it/s, avg=0.09947, loss=0.09072]

trial_002 train e008:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:24,  1.39it/s, avg=0.09975, loss=0.10843]

trial_002 train e008:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:23,  1.41it/s, avg=0.09975, loss=0.10843]

trial_002 train e008:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:23,  1.41it/s, avg=0.10002, loss=0.10867]

trial_002 train e008:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:20,  1.43it/s, avg=0.10002, loss=0.10867]

trial_002 train e008:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:20,  1.43it/s, avg=0.09958, loss=0.08518]

trial_002 train e008:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:20,  1.43it/s, avg=0.09958, loss=0.08518]

trial_002 train e008:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:20,  1.43it/s, avg=0.09925, loss=0.08791]

trial_002 train e008:  23%|██████████████████████                                                                        | 35/149 [00:24<01:21,  1.40it/s, avg=0.09925, loss=0.08791]

trial_002 train e008:  23%|██████████████████████                                                                        | 35/149 [00:25<01:21,  1.40it/s, avg=0.09892, loss=0.08736]

trial_002 train e008:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:20,  1.41it/s, avg=0.09892, loss=0.08736]

trial_002 train e008:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.41it/s, avg=0.09870, loss=0.09092]

trial_002 train e008:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:19,  1.41it/s, avg=0.09870, loss=0.09092]

trial_002 train e008:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:19,  1.41it/s, avg=0.09856, loss=0.09347]

trial_002 train e008:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.38it/s, avg=0.09856, loss=0.09347]

trial_002 train e008:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.38it/s, avg=0.09900, loss=0.11552]

trial_002 train e008:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:19,  1.38it/s, avg=0.09900, loss=0.11552]

trial_002 train e008:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:19,  1.38it/s, avg=0.09884, loss=0.09251]

trial_002 train e008:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:18,  1.38it/s, avg=0.09884, loss=0.09251]

trial_002 train e008:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.38it/s, avg=0.09911, loss=0.11019]

trial_002 train e008:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:14,  1.45it/s, avg=0.09911, loss=0.11019]

trial_002 train e008:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:14,  1.45it/s, avg=0.09919, loss=0.10229]

trial_002 train e008:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:15,  1.43it/s, avg=0.09919, loss=0.10229]

trial_002 train e008:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:15,  1.43it/s, avg=0.09912, loss=0.09626]

trial_002 train e008:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:14,  1.42it/s, avg=0.09912, loss=0.09626]

trial_002 train e008:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:14,  1.42it/s, avg=0.09925, loss=0.10495]

trial_002 train e008:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:14,  1.41it/s, avg=0.09925, loss=0.10495]

trial_002 train e008:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.41it/s, avg=0.09940, loss=0.10588]

trial_002 train e008:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.39it/s, avg=0.09940, loss=0.10588]

trial_002 train e008:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.39it/s, avg=0.09919, loss=0.08958]

trial_002 train e008:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:13,  1.40it/s, avg=0.09919, loss=0.08958]

trial_002 train e008:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:13,  1.40it/s, avg=0.09910, loss=0.09506]

trial_002 train e008:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:13,  1.40it/s, avg=0.09910, loss=0.09506]

trial_002 train e008:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.40it/s, avg=0.09911, loss=0.09983]

trial_002 train e008:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.39it/s, avg=0.09911, loss=0.09983]

trial_002 train e008:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.39it/s, avg=0.09915, loss=0.10097]

trial_002 train e008:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:11,  1.39it/s, avg=0.09915, loss=0.10097]

trial_002 train e008:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:11,  1.39it/s, avg=0.09920, loss=0.10149]

trial_002 train e008:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:11,  1.38it/s, avg=0.09920, loss=0.10149]

trial_002 train e008:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:11,  1.38it/s, avg=0.09913, loss=0.09552]

trial_002 train e008:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:10,  1.38it/s, avg=0.09913, loss=0.09552]

trial_002 train e008:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.38it/s, avg=0.09901, loss=0.09284]

trial_002 train e008:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.39it/s, avg=0.09901, loss=0.09284]

trial_002 train e008:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.39it/s, avg=0.09876, loss=0.08615]

trial_002 train e008:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:10,  1.37it/s, avg=0.09876, loss=0.08615]

trial_002 train e008:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.37it/s, avg=0.09906, loss=0.11488]

trial_002 train e008:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:09,  1.36it/s, avg=0.09906, loss=0.11488]

trial_002 train e008:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.36it/s, avg=0.09886, loss=0.08799]

trial_002 train e008:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.38it/s, avg=0.09886, loss=0.08799]

trial_002 train e008:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.38it/s, avg=0.09863, loss=0.08572]

trial_002 train e008:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:06,  1.41it/s, avg=0.09863, loss=0.08572]

trial_002 train e008:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.41it/s, avg=0.09850, loss=0.09163]

trial_002 train e008:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:06,  1.39it/s, avg=0.09850, loss=0.09163]

trial_002 train e008:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:06,  1.39it/s, avg=0.09850, loss=0.09810]

trial_002 train e008:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:06,  1.37it/s, avg=0.09850, loss=0.09810]

trial_002 train e008:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09826, loss=0.08484]

trial_002 train e008:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:06,  1.36it/s, avg=0.09826, loss=0.08484]

trial_002 train e008:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:06,  1.36it/s, avg=0.09833, loss=0.10221]

trial_002 train e008:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:04,  1.39it/s, avg=0.09833, loss=0.10221]

trial_002 train e008:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:04,  1.39it/s, avg=0.09808, loss=0.08289]

trial_002 train e008:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:01,  1.43it/s, avg=0.09808, loss=0.08289]

trial_002 train e008:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:01,  1.43it/s, avg=0.09788, loss=0.08562]

trial_002 train e008:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:00,  1.43it/s, avg=0.09788, loss=0.08562]

trial_002 train e008:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:00,  1.43it/s, avg=0.09800, loss=0.10560]

trial_002 train e008:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<00:59,  1.44it/s, avg=0.09800, loss=0.10560]

trial_002 train e008:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<00:59,  1.44it/s, avg=0.09817, loss=0.10875]

trial_002 train e008:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<00:59,  1.43it/s, avg=0.09817, loss=0.10875]

trial_002 train e008:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<00:59,  1.43it/s, avg=0.09827, loss=0.10482]

trial_002 train e008:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.42it/s, avg=0.09827, loss=0.10482]

trial_002 train e008:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<00:59,  1.42it/s, avg=0.09838, loss=0.10556]

trial_002 train e008:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.41it/s, avg=0.09838, loss=0.10556]

trial_002 train e008:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.41it/s, avg=0.09839, loss=0.09920]

trial_002 train e008:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:58,  1.40it/s, avg=0.09839, loss=0.09920]

trial_002 train e008:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.40it/s, avg=0.09835, loss=0.09550]

trial_002 train e008:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:57,  1.42it/s, avg=0.09835, loss=0.09550]

trial_002 train e008:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:57,  1.42it/s, avg=0.09846, loss=0.10588]

trial_002 train e008:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:56,  1.41it/s, avg=0.09846, loss=0.10588]

trial_002 train e008:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:56,  1.41it/s, avg=0.09845, loss=0.09815]

trial_002 train e008:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:49<00:56,  1.40it/s, avg=0.09845, loss=0.09815]

trial_002 train e008:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.40it/s, avg=0.09845, loss=0.09812]

trial_002 train e008:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:55,  1.40it/s, avg=0.09845, loss=0.09812]

trial_002 train e008:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:55,  1.40it/s, avg=0.09840, loss=0.09469]

trial_002 train e008:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:53,  1.43it/s, avg=0.09840, loss=0.09469]

trial_002 train e008:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:53,  1.43it/s, avg=0.09838, loss=0.09742]

trial_002 train e008:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:53,  1.42it/s, avg=0.09838, loss=0.09742]

trial_002 train e008:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:53,  1.42it/s, avg=0.09823, loss=0.08739]

trial_002 train e008:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:53,  1.41it/s, avg=0.09823, loss=0.08739]

trial_002 train e008:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.41it/s, avg=0.09814, loss=0.09088]

trial_002 train e008:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:52,  1.41it/s, avg=0.09814, loss=0.09088]

trial_002 train e008:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:52,  1.41it/s, avg=0.09809, loss=0.09459]

trial_002 train e008:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:52,  1.39it/s, avg=0.09809, loss=0.09459]

trial_002 train e008:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:52,  1.39it/s, avg=0.09801, loss=0.09231]

trial_002 train e008:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:52,  1.38it/s, avg=0.09801, loss=0.09231]

trial_002 train e008:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:52,  1.38it/s, avg=0.09794, loss=0.09196]

trial_002 train e008:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:51,  1.37it/s, avg=0.09794, loss=0.09196]

trial_002 train e008:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.37it/s, avg=0.09805, loss=0.10669]

trial_002 train e008:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.37it/s, avg=0.09805, loss=0.10669]

trial_002 train e008:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:50,  1.37it/s, avg=0.09807, loss=0.09957]

trial_002 train e008:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:50,  1.36it/s, avg=0.09807, loss=0.09957]

trial_002 train e008:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:50,  1.36it/s, avg=0.09824, loss=0.11176]

trial_002 train e008:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:50,  1.35it/s, avg=0.09824, loss=0.11176]

trial_002 train e008:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:50,  1.35it/s, avg=0.09805, loss=0.08296]

trial_002 train e008:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:49,  1.35it/s, avg=0.09805, loss=0.08296]

trial_002 train e008:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:49,  1.35it/s, avg=0.09813, loss=0.10432]

trial_002 train e008:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:49,  1.34it/s, avg=0.09813, loss=0.10432]

trial_002 train e008:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:49,  1.34it/s, avg=0.09828, loss=0.11107]

trial_002 train e008:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:47,  1.36it/s, avg=0.09828, loss=0.11107]

trial_002 train e008:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:47,  1.36it/s, avg=0.09837, loss=0.10631]

trial_002 train e008:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:46,  1.38it/s, avg=0.09837, loss=0.10631]

trial_002 train e008:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.38it/s, avg=0.09837, loss=0.09838]

trial_002 train e008:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.38it/s, avg=0.09837, loss=0.09838]

trial_002 train e008:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.38it/s, avg=0.09830, loss=0.09155]

trial_002 train e008:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.38it/s, avg=0.09830, loss=0.09155]

trial_002 train e008:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.38it/s, avg=0.09828, loss=0.09716]

trial_002 train e008:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:43,  1.41it/s, avg=0.09828, loss=0.09716]

trial_002 train e008:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.41it/s, avg=0.09848, loss=0.11589]

trial_002 train e008:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:43,  1.39it/s, avg=0.09848, loss=0.11589]

trial_002 train e008:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.39it/s, avg=0.09847, loss=0.09743]

trial_002 train e008:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:43,  1.35it/s, avg=0.09847, loss=0.09743]

trial_002 train e008:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.35it/s, avg=0.09849, loss=0.10059]

trial_002 train e008:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.35it/s, avg=0.09849, loss=0.10059]

trial_002 train e008:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.35it/s, avg=0.09835, loss=0.08552]

trial_002 train e008:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:42,  1.34it/s, avg=0.09835, loss=0.08552]

trial_002 train e008:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:42,  1.34it/s, avg=0.09849, loss=0.11098]

trial_002 train e008:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:40,  1.38it/s, avg=0.09849, loss=0.11098]

trial_002 train e008:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:40,  1.38it/s, avg=0.09838, loss=0.08821]

trial_002 train e008:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:40,  1.36it/s, avg=0.09838, loss=0.08821]

trial_002 train e008:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:40,  1.36it/s, avg=0.09837, loss=0.09746]

trial_002 train e008:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.37it/s, avg=0.09837, loss=0.09746]

trial_002 train e008:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.37it/s, avg=0.09850, loss=0.11070]

trial_002 train e008:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:39,  1.35it/s, avg=0.09850, loss=0.11070]

trial_002 train e008:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:39,  1.35it/s, avg=0.09860, loss=0.10848]

trial_002 train e008:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:38,  1.35it/s, avg=0.09860, loss=0.10848]

trial_002 train e008:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:38,  1.35it/s, avg=0.09863, loss=0.10164]

trial_002 train e008:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:37,  1.37it/s, avg=0.09863, loss=0.10164]

trial_002 train e008:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.37it/s, avg=0.09866, loss=0.10113]

trial_002 train e008:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:36,  1.35it/s, avg=0.09866, loss=0.10113]

trial_002 train e008:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:36,  1.35it/s, avg=0.09857, loss=0.08987]

trial_002 train e008:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:36,  1.35it/s, avg=0.09857, loss=0.08987]

trial_002 train e008:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:36,  1.35it/s, avg=0.09870, loss=0.11187]

trial_002 train e008:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:35,  1.36it/s, avg=0.09870, loss=0.11187]

trial_002 train e008:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:35,  1.36it/s, avg=0.09866, loss=0.09474]

trial_002 train e008:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:34,  1.38it/s, avg=0.09866, loss=0.09474]

trial_002 train e008:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:34,  1.38it/s, avg=0.09866, loss=0.09816]

trial_002 train e008:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:33,  1.37it/s, avg=0.09866, loss=0.09816]

trial_002 train e008:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.37it/s, avg=0.09865, loss=0.09838]

trial_002 train e008:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:33,  1.35it/s, avg=0.09865, loss=0.09838]

trial_002 train e008:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:33,  1.35it/s, avg=0.09855, loss=0.08749]

trial_002 train e008:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:32,  1.34it/s, avg=0.09855, loss=0.08749]

trial_002 train e008:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:32,  1.34it/s, avg=0.09858, loss=0.10237]

trial_002 train e008:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:32,  1.32it/s, avg=0.09858, loss=0.10237]

trial_002 train e008:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:32,  1.32it/s, avg=0.09855, loss=0.09455]

trial_002 train e008:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:31,  1.32it/s, avg=0.09855, loss=0.09455]

trial_002 train e008:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:31,  1.32it/s, avg=0.09861, loss=0.10591]

trial_002 train e008:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:30,  1.33it/s, avg=0.09861, loss=0.10591]

trial_002 train e008:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:30,  1.33it/s, avg=0.09856, loss=0.09240]

trial_002 train e008:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:30,  1.32it/s, avg=0.09856, loss=0.09240]

trial_002 train e008:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:30,  1.32it/s, avg=0.09858, loss=0.10147]

trial_002 train e008:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:29,  1.32it/s, avg=0.09858, loss=0.10147]

trial_002 train e008:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:29,  1.32it/s, avg=0.09861, loss=0.10169]

trial_002 train e008:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:28,  1.33it/s, avg=0.09861, loss=0.10169]

trial_002 train e008:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:28,  1.33it/s, avg=0.09872, loss=0.11064]

trial_002 train e008:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:27,  1.32it/s, avg=0.09872, loss=0.11064]

trial_002 train e008:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:27,  1.32it/s, avg=0.09880, loss=0.10831]

trial_002 train e008:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:26,  1.34it/s, avg=0.09880, loss=0.10831]

trial_002 train e008:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.34it/s, avg=0.09880, loss=0.09829]

trial_002 train e008:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:26,  1.34it/s, avg=0.09880, loss=0.09829]

trial_002 train e008:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:26,  1.34it/s, avg=0.09891, loss=0.11123]

trial_002 train e008:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.36it/s, avg=0.09891, loss=0.11123]

trial_002 train e008:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.36it/s, avg=0.09894, loss=0.10218]

trial_002 train e008:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.39it/s, avg=0.09894, loss=0.10218]

trial_002 train e008:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.39it/s, avg=0.09891, loss=0.09582]

trial_002 train e008:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:23,  1.36it/s, avg=0.09891, loss=0.09582]

trial_002 train e008:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.36it/s, avg=0.09892, loss=0.09998]

trial_002 train e008:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.35it/s, avg=0.09892, loss=0.09998]

trial_002 train e008:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.35it/s, avg=0.09888, loss=0.09442]

trial_002 train e008:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:22,  1.35it/s, avg=0.09888, loss=0.09442]

trial_002 train e008:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:22,  1.35it/s, avg=0.09894, loss=0.10647]

trial_002 train e008:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:21,  1.37it/s, avg=0.09894, loss=0.10647]

trial_002 train e008:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:21,  1.37it/s, avg=0.09904, loss=0.11122]

trial_002 train e008:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:19,  1.42it/s, avg=0.09904, loss=0.11122]

trial_002 train e008:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:19,  1.42it/s, avg=0.09901, loss=0.09511]

trial_002 train e008:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.40it/s, avg=0.09901, loss=0.09511]

trial_002 train e008:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.40it/s, avg=0.09893, loss=0.08843]

trial_002 train e008:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.39it/s, avg=0.09893, loss=0.08843]

trial_002 train e008:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:18,  1.39it/s, avg=0.09892, loss=0.09858]

trial_002 train e008:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.39it/s, avg=0.09892, loss=0.09858]

trial_002 train e008:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:17,  1.39it/s, avg=0.09895, loss=0.10203]

trial_002 train e008:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:16,  1.42it/s, avg=0.09895, loss=0.10203]

trial_002 train e008:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:16,  1.42it/s, avg=0.09893, loss=0.09697]

trial_002 train e008:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.39it/s, avg=0.09893, loss=0.09697]

trial_002 train e008:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.39it/s, avg=0.09896, loss=0.10201]

trial_002 train e008:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:16,  1.36it/s, avg=0.09896, loss=0.10201]

trial_002 train e008:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:16,  1.36it/s, avg=0.09896, loss=0.09897]

trial_002 train e008:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.35it/s, avg=0.09896, loss=0.09897]

trial_002 train e008:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.35it/s, avg=0.09891, loss=0.09278]

trial_002 train e008:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.34it/s, avg=0.09891, loss=0.09278]

trial_002 train e008:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.34it/s, avg=0.09886, loss=0.09211]

trial_002 train e008:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:14,  1.35it/s, avg=0.09886, loss=0.09211]

trial_002 train e008:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:14,  1.35it/s, avg=0.09884, loss=0.09666]

trial_002 train e008:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:13,  1.35it/s, avg=0.09884, loss=0.09666]

trial_002 train e008:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.35it/s, avg=0.09898, loss=0.11775]

trial_002 train e008:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.33it/s, avg=0.09898, loss=0.11775]

trial_002 train e008:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.33it/s, avg=0.09902, loss=0.10376]

trial_002 train e008:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.35it/s, avg=0.09902, loss=0.10376]

trial_002 train e008:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.35it/s, avg=0.09899, loss=0.09509]

trial_002 train e008:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.37it/s, avg=0.09899, loss=0.09509]

trial_002 train e008:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:10,  1.37it/s, avg=0.09895, loss=0.09390]

trial_002 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.36it/s, avg=0.09895, loss=0.09390]

trial_002 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.36it/s, avg=0.09895, loss=0.09860]

trial_002 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.35it/s, avg=0.09895, loss=0.09860]

trial_002 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.35it/s, avg=0.09893, loss=0.09591]

trial_002 train e008:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.35it/s, avg=0.09893, loss=0.09591]

trial_002 train e008:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.35it/s, avg=0.09887, loss=0.09168]

trial_002 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:08,  1.36it/s, avg=0.09887, loss=0.09168]

trial_002 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:08,  1.36it/s, avg=0.09893, loss=0.10633]

trial_002 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.35it/s, avg=0.09893, loss=0.10633]

trial_002 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.35it/s, avg=0.09898, loss=0.10608]

trial_002 train e008:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.35it/s, avg=0.09898, loss=0.10608]

trial_002 train e008:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.35it/s, avg=0.09890, loss=0.08729]

trial_002 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.34it/s, avg=0.09890, loss=0.08729]

trial_002 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.34it/s, avg=0.09888, loss=0.09712]

trial_002 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:05,  1.36it/s, avg=0.09888, loss=0.09712]

trial_002 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:05,  1.36it/s, avg=0.09888, loss=0.09863]

trial_002 train e008:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.35it/s, avg=0.09888, loss=0.09863]

trial_002 train e008:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.35it/s, avg=0.09895, loss=0.10882]

trial_002 train e008:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.33it/s, avg=0.09895, loss=0.10882]

trial_002 train e008:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.33it/s, avg=0.09891, loss=0.09312]

trial_002 train e008:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:03,  1.33it/s, avg=0.09891, loss=0.09312]

trial_002 train e008:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:03,  1.33it/s, avg=0.09888, loss=0.09452]

trial_002 train e008:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.36it/s, avg=0.09888, loss=0.09452]

trial_002 train e008:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.36it/s, avg=0.09883, loss=0.09196]

trial_002 train e008:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.35it/s, avg=0.09883, loss=0.09196]

trial_002 train e008:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.35it/s, avg=0.09892, loss=0.11189]

trial_002 train e008:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.42it/s, avg=0.09892, loss=0.11189]

trial_002 train e008:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.42it/s, avg=0.09894, loss=0.10568]

trial_002 train e008: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:47<00:00,  1.68it/s, avg=0.09894, loss=0.10568]

trial_002 val e008:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e008:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.40it/s]

trial_002 val e008:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.45it/s]

trial_002 val e008:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.42it/s]

trial_002 val e008:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.35it/s]

trial_002 val e008:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.39it/s]

trial_002 val e008:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.41it/s]

trial_002 val e008:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.42it/s]

trial_002 val e008:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.44it/s]

trial_002 val e008:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.44it/s]

trial_002 val e008:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.45it/s]

trial_002 val e008:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.46it/s]

trial_002 val e008:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.40it/s]

trial_002 val e008:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.40it/s]

trial_002 val e008:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.41it/s]

trial_002 val e008:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.42it/s]

trial_002 val e008:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.42it/s]

trial_002 val e008:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.42it/s]

trial_002 val e008:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.38it/s]

trial_002 val e008:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.39it/s]

trial_002 val e008:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.40it/s]

trial_002 val e008:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.41it/s]

trial_002 val e008:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.42it/s]

trial_002 val e008:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.43it/s]

trial_002 val e008:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.44it/s]

trial_002 val e008:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.45it/s]

trial_002 val e008:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.41it/s]

trial_002 val e008:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.39it/s]

trial_002 val e008:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.41it/s]

trial_002 val e008:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.43it/s]

trial_002 val e008:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.42it/s]

trial_002 val e008:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.42it/s]

trial_002 val e008:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.37it/s]

trial_002 val e008:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.38it/s]

trial_002 val e008:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.38it/s]

trial_002 val e008:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.39it/s]

trial_002 val e008:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.40it/s]

trial_002 val e008:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.36it/s]

trial_002 val e008:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:05,  2.37it/s]

trial_002 val e008:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.40it/s]

trial_002 val e008:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.43it/s]

trial_002 val e008:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.43it/s]

trial_002 val e008:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.45it/s]

trial_002 val e008:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.43it/s]

trial_002 val e008:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.39it/s]

trial_002 val e008:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.40it/s]

trial_002 val e008:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.42it/s]

trial_002 val e008:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.44it/s]

trial_002 val e008:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.46it/s]

trial_002 val e008:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.47it/s]

trial_002 val e008: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.49it/s]

[2026-05-28 20:41:20] [trial_002] epoch=008 | train_loss=0.098941 | val_MAE=0.100625 | val_S=0.899375 | best_S=0.899375 @epoch=8 | patience=0/5

[trial_002] epochs:   8%|█████████▋                                                                                                               | 8/100 [17:44<3:18:58, 129.77s/it]

trial_002 train e009:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e009:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09279, loss=0.09279]

trial_002 train e009:   1%|▋                                                                                              | 1/149 [00:00<01:39,  1.49it/s, avg=0.09279, loss=0.09279]

trial_002 train e009:   1%|▋                                                                                              | 1/149 [00:01<01:39,  1.49it/s, avg=0.09872, loss=0.10464]

trial_002 train e009:   1%|█▎                                                                                             | 2/149 [00:01<01:40,  1.47it/s, avg=0.09872, loss=0.10464]

trial_002 train e009:   1%|█▎                                                                                             | 2/149 [00:02<01:40,  1.47it/s, avg=0.10323, loss=0.11227]

trial_002 train e009:   2%|█▉                                                                                             | 3/149 [00:02<01:39,  1.46it/s, avg=0.10323, loss=0.11227]

trial_002 train e009:   2%|█▉                                                                                             | 3/149 [00:02<01:39,  1.46it/s, avg=0.10133, loss=0.09561]

trial_002 train e009:   3%|██▌                                                                                            | 4/149 [00:02<01:42,  1.41it/s, avg=0.10133, loss=0.09561]

trial_002 train e009:   3%|██▌                                                                                            | 4/149 [00:03<01:42,  1.41it/s, avg=0.10095, loss=0.09941]

trial_002 train e009:   3%|███▏                                                                                           | 5/149 [00:03<01:40,  1.43it/s, avg=0.10095, loss=0.09941]

trial_002 train e009:   3%|███▏                                                                                           | 5/149 [00:04<01:40,  1.43it/s, avg=0.09997, loss=0.09506]

trial_002 train e009:   4%|███▊                                                                                           | 6/149 [00:04<01:43,  1.38it/s, avg=0.09997, loss=0.09506]

trial_002 train e009:   4%|███▊                                                                                           | 6/149 [00:04<01:43,  1.38it/s, avg=0.10094, loss=0.10679]

trial_002 train e009:   5%|████▍                                                                                          | 7/149 [00:04<01:41,  1.39it/s, avg=0.10094, loss=0.10679]

trial_002 train e009:   5%|████▍                                                                                          | 7/149 [00:05<01:41,  1.39it/s, avg=0.10135, loss=0.10421]

trial_002 train e009:   5%|█████                                                                                          | 8/149 [00:05<01:41,  1.39it/s, avg=0.10135, loss=0.10421]

trial_002 train e009:   5%|█████                                                                                          | 8/149 [00:06<01:41,  1.39it/s, avg=0.10142, loss=0.10202]

trial_002 train e009:   6%|█████▋                                                                                         | 9/149 [00:06<01:38,  1.42it/s, avg=0.10142, loss=0.10202]

trial_002 train e009:   6%|█████▋                                                                                         | 9/149 [00:07<01:38,  1.42it/s, avg=0.10264, loss=0.11357]

trial_002 train e009:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.42it/s, avg=0.10264, loss=0.11357]

trial_002 train e009:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.42it/s, avg=0.10221, loss=0.09788]

trial_002 train e009:   7%|██████▉                                                                                       | 11/149 [00:07<01:38,  1.40it/s, avg=0.10221, loss=0.09788]

trial_002 train e009:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.40it/s, avg=0.10144, loss=0.09299]

trial_002 train e009:   8%|███████▌                                                                                      | 12/149 [00:08<01:39,  1.37it/s, avg=0.10144, loss=0.09299]

trial_002 train e009:   8%|███████▌                                                                                      | 12/149 [00:09<01:39,  1.37it/s, avg=0.10151, loss=0.10243]

trial_002 train e009:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.10151, loss=0.10243]

trial_002 train e009:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.10100, loss=0.09430]

trial_002 train e009:   9%|████████▊                                                                                     | 14/149 [00:10<01:40,  1.35it/s, avg=0.10100, loss=0.09430]

trial_002 train e009:   9%|████████▊                                                                                     | 14/149 [00:10<01:40,  1.35it/s, avg=0.10100, loss=0.10103]

trial_002 train e009:  10%|█████████▍                                                                                    | 15/149 [00:10<01:37,  1.37it/s, avg=0.10100, loss=0.10103]

trial_002 train e009:  10%|█████████▍                                                                                    | 15/149 [00:11<01:37,  1.37it/s, avg=0.10007, loss=0.08611]

trial_002 train e009:  11%|██████████                                                                                    | 16/149 [00:11<01:36,  1.38it/s, avg=0.10007, loss=0.08611]

trial_002 train e009:  11%|██████████                                                                                    | 16/149 [00:12<01:36,  1.38it/s, avg=0.09939, loss=0.08846]

trial_002 train e009:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.09939, loss=0.08846]

trial_002 train e009:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.09888, loss=0.09027]

trial_002 train e009:  12%|███████████▎                                                                                  | 18/149 [00:12<01:37,  1.34it/s, avg=0.09888, loss=0.09027]

trial_002 train e009:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.09898, loss=0.10079]

trial_002 train e009:  13%|███████████▉                                                                                  | 19/149 [00:13<01:38,  1.33it/s, avg=0.09898, loss=0.10079]

trial_002 train e009:  13%|███████████▉                                                                                  | 19/149 [00:14<01:38,  1.33it/s, avg=0.09861, loss=0.09147]

trial_002 train e009:  13%|████████████▌                                                                                 | 20/149 [00:14<01:34,  1.36it/s, avg=0.09861, loss=0.09147]

trial_002 train e009:  13%|████████████▌                                                                                 | 20/149 [00:15<01:34,  1.36it/s, avg=0.09817, loss=0.08938]

trial_002 train e009:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.33it/s, avg=0.09817, loss=0.08938]

trial_002 train e009:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.33it/s, avg=0.09764, loss=0.08667]

trial_002 train e009:  15%|█████████████▉                                                                                | 22/149 [00:15<01:34,  1.34it/s, avg=0.09764, loss=0.08667]

trial_002 train e009:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.34it/s, avg=0.09682, loss=0.07878]

trial_002 train e009:  15%|██████████████▌                                                                               | 23/149 [00:16<01:35,  1.32it/s, avg=0.09682, loss=0.07878]

trial_002 train e009:  15%|██████████████▌                                                                               | 23/149 [00:17<01:35,  1.32it/s, avg=0.09701, loss=0.10123]

trial_002 train e009:  16%|███████████████▏                                                                              | 24/149 [00:17<01:34,  1.32it/s, avg=0.09701, loss=0.10123]

trial_002 train e009:  16%|███████████████▏                                                                              | 24/149 [00:18<01:34,  1.32it/s, avg=0.09736, loss=0.10573]

trial_002 train e009:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.35it/s, avg=0.09736, loss=0.10573]

trial_002 train e009:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.35it/s, avg=0.09790, loss=0.11145]

trial_002 train e009:  17%|████████████████▍                                                                             | 26/149 [00:18<01:30,  1.35it/s, avg=0.09790, loss=0.11145]

trial_002 train e009:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.35it/s, avg=0.09804, loss=0.10163]

trial_002 train e009:  18%|█████████████████                                                                             | 27/149 [00:19<01:31,  1.34it/s, avg=0.09804, loss=0.10163]

trial_002 train e009:  18%|█████████████████                                                                             | 27/149 [00:20<01:31,  1.34it/s, avg=0.09813, loss=0.10057]

trial_002 train e009:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:30,  1.34it/s, avg=0.09813, loss=0.10057]

trial_002 train e009:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:30,  1.34it/s, avg=0.09855, loss=0.11039]

trial_002 train e009:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:30,  1.33it/s, avg=0.09855, loss=0.11039]

trial_002 train e009:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:30,  1.33it/s, avg=0.09873, loss=0.10409]

trial_002 train e009:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:28,  1.34it/s, avg=0.09873, loss=0.10409]

trial_002 train e009:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:28,  1.34it/s, avg=0.09843, loss=0.08927]

trial_002 train e009:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:27,  1.35it/s, avg=0.09843, loss=0.08927]

trial_002 train e009:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.35it/s, avg=0.09833, loss=0.09537]

trial_002 train e009:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:25,  1.37it/s, avg=0.09833, loss=0.09537]

trial_002 train e009:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:25,  1.37it/s, avg=0.09839, loss=0.10034]

trial_002 train e009:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:23,  1.39it/s, avg=0.09839, loss=0.10034]

trial_002 train e009:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:23,  1.39it/s, avg=0.09842, loss=0.09913]

trial_002 train e009:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.09842, loss=0.09913]

trial_002 train e009:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.09833, loss=0.09531]

trial_002 train e009:  23%|██████████████████████                                                                        | 35/149 [00:25<01:23,  1.36it/s, avg=0.09833, loss=0.09531]

trial_002 train e009:  23%|██████████████████████                                                                        | 35/149 [00:26<01:23,  1.36it/s, avg=0.09878, loss=0.11469]

trial_002 train e009:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:22,  1.37it/s, avg=0.09878, loss=0.11469]

trial_002 train e009:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:22,  1.37it/s, avg=0.09886, loss=0.10163]

trial_002 train e009:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.36it/s, avg=0.09886, loss=0.10163]

trial_002 train e009:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.36it/s, avg=0.09938, loss=0.11858]

trial_002 train e009:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.38it/s, avg=0.09938, loss=0.11858]

trial_002 train e009:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:20,  1.38it/s, avg=0.09924, loss=0.09383]

trial_002 train e009:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:20,  1.36it/s, avg=0.09924, loss=0.09383]

trial_002 train e009:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:20,  1.36it/s, avg=0.09948, loss=0.10910]

trial_002 train e009:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.38it/s, avg=0.09948, loss=0.10910]

trial_002 train e009:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.38it/s, avg=0.09973, loss=0.10982]

trial_002 train e009:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:20,  1.34it/s, avg=0.09973, loss=0.10982]

trial_002 train e009:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:20,  1.34it/s, avg=0.10016, loss=0.11775]

trial_002 train e009:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:16,  1.39it/s, avg=0.10016, loss=0.11775]

trial_002 train e009:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:16,  1.39it/s, avg=0.10001, loss=0.09338]

trial_002 train e009:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.40it/s, avg=0.10001, loss=0.09338]

trial_002 train e009:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:15,  1.40it/s, avg=0.09984, loss=0.09253]

trial_002 train e009:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:17,  1.36it/s, avg=0.09984, loss=0.09253]

trial_002 train e009:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:17,  1.36it/s, avg=0.09999, loss=0.10689]

trial_002 train e009:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.40it/s, avg=0.09999, loss=0.10689]

trial_002 train e009:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:14,  1.40it/s, avg=0.09992, loss=0.09657]

trial_002 train e009:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.38it/s, avg=0.09992, loss=0.09657]

trial_002 train e009:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:14,  1.38it/s, avg=0.09981, loss=0.09466]

trial_002 train e009:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.38it/s, avg=0.09981, loss=0.09466]

trial_002 train e009:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.38it/s, avg=0.09964, loss=0.09172]

trial_002 train e009:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.40it/s, avg=0.09964, loss=0.09172]

trial_002 train e009:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:12,  1.40it/s, avg=0.09991, loss=0.11306]

trial_002 train e009:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:13,  1.37it/s, avg=0.09991, loss=0.11306]

trial_002 train e009:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:13,  1.37it/s, avg=0.09986, loss=0.09729]

trial_002 train e009:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:12,  1.37it/s, avg=0.09986, loss=0.09729]

trial_002 train e009:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:12,  1.37it/s, avg=0.09985, loss=0.09941]

trial_002 train e009:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.40it/s, avg=0.09985, loss=0.09941]

trial_002 train e009:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.40it/s, avg=0.10001, loss=0.10836]

trial_002 train e009:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:10,  1.38it/s, avg=0.10001, loss=0.10836]

trial_002 train e009:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.38it/s, avg=0.09986, loss=0.09198]

trial_002 train e009:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.09986, loss=0.09198]

trial_002 train e009:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.36it/s, avg=0.10002, loss=0.10856]

trial_002 train e009:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:10,  1.35it/s, avg=0.10002, loss=0.10856]

trial_002 train e009:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:10,  1.35it/s, avg=0.10011, loss=0.10504]

trial_002 train e009:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:09,  1.35it/s, avg=0.10011, loss=0.10504]

trial_002 train e009:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:09,  1.35it/s, avg=0.10019, loss=0.10410]

trial_002 train e009:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:09,  1.34it/s, avg=0.10019, loss=0.10410]

trial_002 train e009:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:09,  1.34it/s, avg=0.09990, loss=0.08371]

trial_002 train e009:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:07,  1.37it/s, avg=0.09990, loss=0.08371]

trial_002 train e009:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:07,  1.37it/s, avg=0.09995, loss=0.10314]

trial_002 train e009:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:07,  1.36it/s, avg=0.09995, loss=0.10314]

trial_002 train e009:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:07,  1.36it/s, avg=0.10005, loss=0.10568]

trial_002 train e009:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:07,  1.34it/s, avg=0.10005, loss=0.10568]

trial_002 train e009:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:07,  1.34it/s, avg=0.09987, loss=0.08911]

trial_002 train e009:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:05,  1.35it/s, avg=0.09987, loss=0.08911]

trial_002 train e009:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.35it/s, avg=0.09976, loss=0.09351]

trial_002 train e009:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.35it/s, avg=0.09976, loss=0.09351]

trial_002 train e009:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:04,  1.35it/s, avg=0.09967, loss=0.09426]

trial_002 train e009:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:03,  1.36it/s, avg=0.09967, loss=0.09426]

trial_002 train e009:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:03,  1.36it/s, avg=0.09967, loss=0.09927]

trial_002 train e009:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.38it/s, avg=0.09967, loss=0.09927]

trial_002 train e009:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.38it/s, avg=0.09965, loss=0.09825]

trial_002 train e009:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:02,  1.37it/s, avg=0.09965, loss=0.09825]

trial_002 train e009:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:02,  1.37it/s, avg=0.09948, loss=0.08882]

trial_002 train e009:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:01,  1.37it/s, avg=0.09948, loss=0.08882]

trial_002 train e009:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.37it/s, avg=0.09949, loss=0.10028]

trial_002 train e009:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:01,  1.35it/s, avg=0.09949, loss=0.10028]

trial_002 train e009:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:01,  1.35it/s, avg=0.09966, loss=0.11093]

trial_002 train e009:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:59,  1.37it/s, avg=0.09966, loss=0.11093]

trial_002 train e009:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:59,  1.37it/s, avg=0.09983, loss=0.11102]

trial_002 train e009:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:58,  1.38it/s, avg=0.09983, loss=0.11102]

trial_002 train e009:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:58,  1.38it/s, avg=0.09967, loss=0.08874]

trial_002 train e009:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:58,  1.36it/s, avg=0.09967, loss=0.08874]

trial_002 train e009:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.36it/s, avg=0.09960, loss=0.09508]

trial_002 train e009:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:59,  1.34it/s, avg=0.09960, loss=0.09508]

trial_002 train e009:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:59,  1.34it/s, avg=0.09952, loss=0.09365]

trial_002 train e009:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:56,  1.38it/s, avg=0.09952, loss=0.09365]

trial_002 train e009:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:56,  1.38it/s, avg=0.09948, loss=0.09659]

trial_002 train e009:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:56,  1.36it/s, avg=0.09948, loss=0.09659]

trial_002 train e009:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:56,  1.36it/s, avg=0.09956, loss=0.10533]

trial_002 train e009:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:56,  1.35it/s, avg=0.09956, loss=0.10533]

trial_002 train e009:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:56,  1.35it/s, avg=0.09938, loss=0.08640]

trial_002 train e009:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:55,  1.34it/s, avg=0.09938, loss=0.08640]

trial_002 train e009:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:55,  1.34it/s, avg=0.09926, loss=0.09048]

trial_002 train e009:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:54,  1.35it/s, avg=0.09926, loss=0.09048]

trial_002 train e009:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:54,  1.35it/s, avg=0.09929, loss=0.10114]

trial_002 train e009:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:53,  1.36it/s, avg=0.09929, loss=0.10114]

trial_002 train e009:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:53,  1.36it/s, avg=0.09923, loss=0.09458]

trial_002 train e009:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:54,  1.33it/s, avg=0.09923, loss=0.09458]

trial_002 train e009:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:54,  1.33it/s, avg=0.09930, loss=0.10515]

trial_002 train e009:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:53,  1.33it/s, avg=0.09930, loss=0.10515]

trial_002 train e009:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:53,  1.33it/s, avg=0.09940, loss=0.10731]

trial_002 train e009:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:52,  1.33it/s, avg=0.09940, loss=0.10731]

trial_002 train e009:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:52,  1.33it/s, avg=0.09933, loss=0.09387]

trial_002 train e009:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:51,  1.35it/s, avg=0.09933, loss=0.09387]

trial_002 train e009:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:51,  1.35it/s, avg=0.09920, loss=0.08844]

trial_002 train e009:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.35it/s, avg=0.09920, loss=0.08844]

trial_002 train e009:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:50,  1.35it/s, avg=0.09926, loss=0.10430]

trial_002 train e009:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:49,  1.35it/s, avg=0.09926, loss=0.10430]

trial_002 train e009:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:49,  1.35it/s, avg=0.09933, loss=0.10473]

trial_002 train e009:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:49,  1.34it/s, avg=0.09933, loss=0.10473]

trial_002 train e009:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:49,  1.34it/s, avg=0.09911, loss=0.08104]

trial_002 train e009:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:49,  1.33it/s, avg=0.09911, loss=0.08104]

trial_002 train e009:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:49,  1.33it/s, avg=0.09905, loss=0.09404]

trial_002 train e009:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:49,  1.29it/s, avg=0.09905, loss=0.09404]

trial_002 train e009:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:49,  1.29it/s, avg=0.09918, loss=0.11042]

trial_002 train e009:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:47,  1.31it/s, avg=0.09918, loss=0.11042]

trial_002 train e009:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:47,  1.31it/s, avg=0.09917, loss=0.09853]

trial_002 train e009:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:46,  1.33it/s, avg=0.09917, loss=0.09853]

trial_002 train e009:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:46,  1.33it/s, avg=0.09943, loss=0.12195]

trial_002 train e009:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.37it/s, avg=0.09943, loss=0.12195]

trial_002 train e009:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:44,  1.37it/s, avg=0.09943, loss=0.09872]

trial_002 train e009:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.35it/s, avg=0.09943, loss=0.09872]

trial_002 train e009:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.35it/s, avg=0.09947, loss=0.10368]

trial_002 train e009:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:44,  1.33it/s, avg=0.09947, loss=0.10368]

trial_002 train e009:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:44,  1.33it/s, avg=0.09930, loss=0.08420]

trial_002 train e009:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:43,  1.32it/s, avg=0.09930, loss=0.08420]

trial_002 train e009:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:43,  1.32it/s, avg=0.09927, loss=0.09603]

trial_002 train e009:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:43,  1.32it/s, avg=0.09927, loss=0.09603]

trial_002 train e009:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:43,  1.32it/s, avg=0.09933, loss=0.10460]

trial_002 train e009:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:41,  1.34it/s, avg=0.09933, loss=0.10460]

trial_002 train e009:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:41,  1.34it/s, avg=0.09920, loss=0.08710]

trial_002 train e009:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.40it/s, avg=0.09920, loss=0.08710]

trial_002 train e009:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.40it/s, avg=0.09934, loss=0.11329]

trial_002 train e009:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:38,  1.39it/s, avg=0.09934, loss=0.11329]

trial_002 train e009:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:38,  1.39it/s, avg=0.09918, loss=0.08337]

trial_002 train e009:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:39,  1.35it/s, avg=0.09918, loss=0.08337]

trial_002 train e009:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:39,  1.35it/s, avg=0.09918, loss=0.09944]

trial_002 train e009:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.36it/s, avg=0.09918, loss=0.09944]

trial_002 train e009:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.36it/s, avg=0.09922, loss=0.10264]

trial_002 train e009:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.36it/s, avg=0.09922, loss=0.10264]

trial_002 train e009:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.36it/s, avg=0.09930, loss=0.10744]

trial_002 train e009:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.09930, loss=0.10744]

trial_002 train e009:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.37it/s, avg=0.09924, loss=0.09310]

trial_002 train e009:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.37it/s, avg=0.09924, loss=0.09310]

trial_002 train e009:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:35,  1.37it/s, avg=0.09919, loss=0.09464]

trial_002 train e009:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.35it/s, avg=0.09919, loss=0.09464]

trial_002 train e009:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.35it/s, avg=0.09914, loss=0.09405]

trial_002 train e009:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.37it/s, avg=0.09914, loss=0.09405]

trial_002 train e009:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:34,  1.37it/s, avg=0.09910, loss=0.09532]

trial_002 train e009:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.37it/s, avg=0.09910, loss=0.09532]

trial_002 train e009:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:33,  1.37it/s, avg=0.09912, loss=0.10063]

trial_002 train e009:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:32,  1.38it/s, avg=0.09912, loss=0.10063]

trial_002 train e009:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:32,  1.38it/s, avg=0.09900, loss=0.08700]

trial_002 train e009:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.36it/s, avg=0.09900, loss=0.08700]

trial_002 train e009:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.36it/s, avg=0.09893, loss=0.09083]

trial_002 train e009:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.37it/s, avg=0.09893, loss=0.09083]

trial_002 train e009:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:31,  1.37it/s, avg=0.09902, loss=0.10900]

trial_002 train e009:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.37it/s, avg=0.09902, loss=0.10900]

trial_002 train e009:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:30,  1.37it/s, avg=0.09906, loss=0.10334]

trial_002 train e009:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:29,  1.37it/s, avg=0.09906, loss=0.10334]

trial_002 train e009:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:29,  1.37it/s, avg=0.09884, loss=0.07508]

trial_002 train e009:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:28,  1.38it/s, avg=0.09884, loss=0.07508]

trial_002 train e009:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:28,  1.38it/s, avg=0.09881, loss=0.09518]

trial_002 train e009:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:27,  1.39it/s, avg=0.09881, loss=0.09518]

trial_002 train e009:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:27,  1.39it/s, avg=0.09874, loss=0.09131]

trial_002 train e009:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.40it/s, avg=0.09874, loss=0.09131]

trial_002 train e009:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:27,  1.40it/s, avg=0.09873, loss=0.09782]

trial_002 train e009:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:25,  1.42it/s, avg=0.09873, loss=0.09782]

trial_002 train e009:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:25,  1.42it/s, avg=0.09866, loss=0.09118]

trial_002 train e009:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:25,  1.40it/s, avg=0.09866, loss=0.09118]

trial_002 train e009:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:25,  1.40it/s, avg=0.09860, loss=0.09075]

trial_002 train e009:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.37it/s, avg=0.09860, loss=0.09075]

trial_002 train e009:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.37it/s, avg=0.09861, loss=0.10034]

trial_002 train e009:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.39it/s, avg=0.09861, loss=0.10034]

trial_002 train e009:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.39it/s, avg=0.09872, loss=0.11085]

trial_002 train e009:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.43it/s, avg=0.09872, loss=0.11085]

trial_002 train e009:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:23,  1.43it/s, avg=0.09872, loss=0.09905]

trial_002 train e009:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.39it/s, avg=0.09872, loss=0.09905]

trial_002 train e009:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.39it/s, avg=0.09879, loss=0.10762]

trial_002 train e009:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.37it/s, avg=0.09879, loss=0.10762]

trial_002 train e009:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:22,  1.37it/s, avg=0.09883, loss=0.10292]

trial_002 train e009:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.37it/s, avg=0.09883, loss=0.10292]

trial_002 train e009:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.37it/s, avg=0.09878, loss=0.09266]

trial_002 train e009:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:21,  1.38it/s, avg=0.09878, loss=0.09266]

trial_002 train e009:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.38it/s, avg=0.09883, loss=0.10467]

trial_002 train e009:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.37it/s, avg=0.09883, loss=0.10467]

trial_002 train e009:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.37it/s, avg=0.09891, loss=0.10865]

trial_002 train e009:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:20,  1.33it/s, avg=0.09891, loss=0.10865]

trial_002 train e009:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:20,  1.33it/s, avg=0.09889, loss=0.09687]

trial_002 train e009:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.33it/s, avg=0.09889, loss=0.09687]

trial_002 train e009:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.33it/s, avg=0.09897, loss=0.10848]

trial_002 train e009:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.36it/s, avg=0.09897, loss=0.10848]

trial_002 train e009:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.36it/s, avg=0.09888, loss=0.08839]

trial_002 train e009:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.39it/s, avg=0.09888, loss=0.08839]

trial_002 train e009:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.39it/s, avg=0.09887, loss=0.09763]

trial_002 train e009:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.38it/s, avg=0.09887, loss=0.09763]

trial_002 train e009:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:16,  1.38it/s, avg=0.09883, loss=0.09313]

trial_002 train e009:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.37it/s, avg=0.09883, loss=0.09313]

trial_002 train e009:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.37it/s, avg=0.09877, loss=0.09133]

trial_002 train e009:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.36it/s, avg=0.09877, loss=0.09133]

trial_002 train e009:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.36it/s, avg=0.09868, loss=0.08675]

trial_002 train e009:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.36it/s, avg=0.09868, loss=0.08675]

trial_002 train e009:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.36it/s, avg=0.09866, loss=0.09682]

trial_002 train e009:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.36it/s, avg=0.09866, loss=0.09682]

trial_002 train e009:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:13,  1.36it/s, avg=0.09858, loss=0.08743]

trial_002 train e009:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.34it/s, avg=0.09858, loss=0.08743]

trial_002 train e009:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.34it/s, avg=0.09862, loss=0.10383]

trial_002 train e009:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.33it/s, avg=0.09862, loss=0.10383]

trial_002 train e009:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.33it/s, avg=0.09856, loss=0.09107]

trial_002 train e009:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.34it/s, avg=0.09856, loss=0.09107]

trial_002 train e009:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:11,  1.34it/s, avg=0.09857, loss=0.09938]

trial_002 train e009:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:11,  1.36it/s, avg=0.09857, loss=0.09938]

trial_002 train e009:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:11,  1.36it/s, avg=0.09860, loss=0.10374]

trial_002 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.38it/s, avg=0.09860, loss=0.10374]

trial_002 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.38it/s, avg=0.09855, loss=0.09076]

trial_002 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.37it/s, avg=0.09855, loss=0.09076]

trial_002 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.37it/s, avg=0.09857, loss=0.10121]

trial_002 train e009:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.36it/s, avg=0.09857, loss=0.10121]

trial_002 train e009:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:41<00:08,  1.36it/s, avg=0.09844, loss=0.08173]

trial_002 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.35it/s, avg=0.09844, loss=0.08173]

trial_002 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.35it/s, avg=0.09846, loss=0.10021]

trial_002 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.38it/s, avg=0.09846, loss=0.10021]

trial_002 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.38it/s, avg=0.09837, loss=0.08595]

trial_002 train e009:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.40it/s, avg=0.09837, loss=0.08595]

trial_002 train e009:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.40it/s, avg=0.09835, loss=0.09535]

trial_002 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.37it/s, avg=0.09835, loss=0.09535]

trial_002 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:44<00:05,  1.37it/s, avg=0.09839, loss=0.10512]

trial_002 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.37it/s, avg=0.09839, loss=0.10512]

trial_002 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.37it/s, avg=0.09833, loss=0.08871]

trial_002 train e009:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.38it/s, avg=0.09833, loss=0.08871]

trial_002 train e009:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.38it/s, avg=0.09824, loss=0.08628]

trial_002 train e009:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.36it/s, avg=0.09824, loss=0.08628]

trial_002 train e009:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:46<00:03,  1.36it/s, avg=0.09824, loss=0.09849]

trial_002 train e009:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.34it/s, avg=0.09824, loss=0.09849]

trial_002 train e009:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:47<00:02,  1.34it/s, avg=0.09823, loss=0.09572]

trial_002 train e009:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.35it/s, avg=0.09823, loss=0.09572]

trial_002 train e009:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.35it/s, avg=0.09821, loss=0.09563]

trial_002 train e009:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.34it/s, avg=0.09821, loss=0.09563]

trial_002 train e009:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.34it/s, avg=0.09826, loss=0.10587]

trial_002 train e009:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.38it/s, avg=0.09826, loss=0.10587]

trial_002 train e009:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.38it/s, avg=0.09826, loss=0.09813]

trial_002 train e009: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.66it/s, avg=0.09826, loss=0.09813]

trial_002 val e009:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e009:   2%|██▌                                                                                                                          | 1/50 [00:00<00:19,  2.54it/s]

trial_002 val e009:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.48it/s]

trial_002 val e009:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:18,  2.49it/s]

trial_002 val e009:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.49it/s]

trial_002 val e009:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.49it/s]

trial_002 val e009:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.49it/s]

trial_002 val e009:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.45it/s]

trial_002 val e009:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.42it/s]

trial_002 val e009:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.42it/s]

trial_002 val e009:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.42it/s]

trial_002 val e009:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.43it/s]

trial_002 val e009:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.45it/s]

trial_002 val e009:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.46it/s]

trial_002 val e009:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.46it/s]

trial_002 val e009:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.46it/s]

trial_002 val e009:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.47it/s]

trial_002 val e009:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.48it/s]

trial_002 val e009:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:12,  2.48it/s]

trial_002 val e009:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.48it/s]

trial_002 val e009:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.38it/s]

trial_002 val e009:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.38it/s]

trial_002 val e009:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.39it/s]

trial_002 val e009:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.42it/s]

trial_002 val e009:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.41it/s]

trial_002 val e009:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.45it/s]

trial_002 val e009:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.40it/s]

trial_002 val e009:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.41it/s]

trial_002 val e009:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.41it/s]

trial_002 val e009:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.43it/s]

trial_002 val e009:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.43it/s]

trial_002 val e009:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.44it/s]

trial_002 val e009:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.45it/s]

trial_002 val e009:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.45it/s]

trial_002 val e009:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.44it/s]

trial_002 val e009:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.39it/s]

trial_002 val e009:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.40it/s]

trial_002 val e009:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.42it/s]

trial_002 val e009:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.43it/s]

trial_002 val e009:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.44it/s]

trial_002 val e009:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.43it/s]

trial_002 val e009:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.40it/s]

trial_002 val e009:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.38it/s]

trial_002 val e009:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.40it/s]

trial_002 val e009:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.42it/s]

trial_002 val e009:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.43it/s]

trial_002 val e009:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.44it/s]

trial_002 val e009:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.44it/s]

trial_002 val e009:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.44it/s]

trial_002 val e009:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.37it/s]

trial_002 val e009: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.40it/s]

[2026-05-28 20:43:31] [trial_002] epoch=009 | train_loss=0.098260 | val_MAE=0.099118 | val_S=0.900882 | best_S=0.900882 @epoch=9 | patience=0/5

[trial_002] epochs:   9%|██████████▉                                                                                                              | 9/100 [19:54<3:17:12, 130.03s/it]

trial_002 train e010:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e010:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09020, loss=0.09020]

trial_002 train e010:   1%|▋                                                                                              | 1/149 [00:00<01:39,  1.48it/s, avg=0.09020, loss=0.09020]

trial_002 train e010:   1%|▋                                                                                              | 1/149 [00:01<01:39,  1.48it/s, avg=0.09364, loss=0.09708]

trial_002 train e010:   1%|█▎                                                                                             | 2/149 [00:01<01:44,  1.40it/s, avg=0.09364, loss=0.09708]

trial_002 train e010:   1%|█▎                                                                                             | 2/149 [00:02<01:44,  1.40it/s, avg=0.09185, loss=0.08826]

trial_002 train e010:   2%|█▉                                                                                             | 3/149 [00:02<01:46,  1.38it/s, avg=0.09185, loss=0.08826]

trial_002 train e010:   2%|█▉                                                                                             | 3/149 [00:02<01:46,  1.38it/s, avg=0.09004, loss=0.08461]

trial_002 train e010:   3%|██▌                                                                                            | 4/149 [00:02<01:43,  1.40it/s, avg=0.09004, loss=0.08461]

trial_002 train e010:   3%|██▌                                                                                            | 4/149 [00:03<01:43,  1.40it/s, avg=0.09099, loss=0.09478]

trial_002 train e010:   3%|███▏                                                                                           | 5/149 [00:03<01:42,  1.40it/s, avg=0.09099, loss=0.09478]

trial_002 train e010:   3%|███▏                                                                                           | 5/149 [00:04<01:42,  1.40it/s, avg=0.09400, loss=0.10905]

trial_002 train e010:   4%|███▊                                                                                           | 6/149 [00:04<01:40,  1.42it/s, avg=0.09400, loss=0.10905]

trial_002 train e010:   4%|███▊                                                                                           | 6/149 [00:04<01:40,  1.42it/s, avg=0.09301, loss=0.08707]

trial_002 train e010:   5%|████▍                                                                                          | 7/149 [00:04<01:41,  1.40it/s, avg=0.09301, loss=0.08707]

trial_002 train e010:   5%|████▍                                                                                          | 7/149 [00:05<01:41,  1.40it/s, avg=0.09436, loss=0.10385]

trial_002 train e010:   5%|█████                                                                                          | 8/149 [00:05<01:44,  1.35it/s, avg=0.09436, loss=0.10385]

trial_002 train e010:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.35it/s, avg=0.09441, loss=0.09481]

trial_002 train e010:   6%|█████▋                                                                                         | 9/149 [00:06<01:42,  1.37it/s, avg=0.09441, loss=0.09481]

trial_002 train e010:   6%|█████▋                                                                                         | 9/149 [00:07<01:42,  1.37it/s, avg=0.09477, loss=0.09800]

trial_002 train e010:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.36it/s, avg=0.09477, loss=0.09800]

trial_002 train e010:   7%|██████▎                                                                                       | 10/149 [00:08<01:42,  1.36it/s, avg=0.09434, loss=0.09004]

trial_002 train e010:   7%|██████▉                                                                                       | 11/149 [00:08<01:43,  1.33it/s, avg=0.09434, loss=0.09004]

trial_002 train e010:   7%|██████▉                                                                                       | 11/149 [00:08<01:43,  1.33it/s, avg=0.09494, loss=0.10149]

trial_002 train e010:   8%|███████▌                                                                                      | 12/149 [00:08<01:41,  1.35it/s, avg=0.09494, loss=0.10149]

trial_002 train e010:   8%|███████▌                                                                                      | 12/149 [00:09<01:41,  1.35it/s, avg=0.09409, loss=0.08399]

trial_002 train e010:   9%|████████▏                                                                                     | 13/149 [00:09<01:42,  1.33it/s, avg=0.09409, loss=0.08399]

trial_002 train e010:   9%|████████▏                                                                                     | 13/149 [00:10<01:42,  1.33it/s, avg=0.09430, loss=0.09690]

trial_002 train e010:   9%|████████▊                                                                                     | 14/149 [00:10<01:42,  1.32it/s, avg=0.09430, loss=0.09690]

trial_002 train e010:   9%|████████▊                                                                                     | 14/149 [00:11<01:42,  1.32it/s, avg=0.09423, loss=0.09327]

trial_002 train e010:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.34it/s, avg=0.09423, loss=0.09327]

trial_002 train e010:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.34it/s, avg=0.09435, loss=0.09626]

trial_002 train e010:  11%|██████████                                                                                    | 16/149 [00:11<01:38,  1.36it/s, avg=0.09435, loss=0.09626]

trial_002 train e010:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.36it/s, avg=0.09474, loss=0.10083]

trial_002 train e010:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.34it/s, avg=0.09474, loss=0.10083]

trial_002 train e010:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.34it/s, avg=0.09490, loss=0.09765]

trial_002 train e010:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.09490, loss=0.09765]

trial_002 train e010:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.09458, loss=0.08884]

trial_002 train e010:  13%|███████████▉                                                                                  | 19/149 [00:13<01:37,  1.34it/s, avg=0.09458, loss=0.08884]

trial_002 train e010:  13%|███████████▉                                                                                  | 19/149 [00:14<01:37,  1.34it/s, avg=0.09515, loss=0.10608]

trial_002 train e010:  13%|████████████▌                                                                                 | 20/149 [00:14<01:39,  1.29it/s, avg=0.09515, loss=0.10608]

trial_002 train e010:  13%|████████████▌                                                                                 | 20/149 [00:15<01:39,  1.29it/s, avg=0.09588, loss=0.11031]

trial_002 train e010:  14%|█████████████▏                                                                                | 21/149 [00:15<01:37,  1.31it/s, avg=0.09588, loss=0.11031]

trial_002 train e010:  14%|█████████████▏                                                                                | 21/149 [00:16<01:37,  1.31it/s, avg=0.09556, loss=0.08895]

trial_002 train e010:  15%|█████████████▉                                                                                | 22/149 [00:16<01:35,  1.33it/s, avg=0.09556, loss=0.08895]

trial_002 train e010:  15%|█████████████▉                                                                                | 22/149 [00:17<01:35,  1.33it/s, avg=0.09539, loss=0.09171]

trial_002 train e010:  15%|██████████████▌                                                                               | 23/149 [00:17<01:34,  1.34it/s, avg=0.09539, loss=0.09171]

trial_002 train e010:  15%|██████████████▌                                                                               | 23/149 [00:17<01:34,  1.34it/s, avg=0.09536, loss=0.09464]

trial_002 train e010:  16%|███████████████▏                                                                              | 24/149 [00:17<01:32,  1.35it/s, avg=0.09536, loss=0.09464]

trial_002 train e010:  16%|███████████████▏                                                                              | 24/149 [00:18<01:32,  1.35it/s, avg=0.09554, loss=0.09988]

trial_002 train e010:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.39it/s, avg=0.09554, loss=0.09988]

trial_002 train e010:  17%|███████████████▊                                                                              | 25/149 [00:19<01:29,  1.39it/s, avg=0.09620, loss=0.11268]

trial_002 train e010:  17%|████████████████▍                                                                             | 26/149 [00:19<01:31,  1.35it/s, avg=0.09620, loss=0.11268]

trial_002 train e010:  17%|████████████████▍                                                                             | 26/149 [00:20<01:31,  1.35it/s, avg=0.09649, loss=0.10396]

trial_002 train e010:  18%|█████████████████                                                                             | 27/149 [00:20<01:32,  1.31it/s, avg=0.09649, loss=0.10396]

trial_002 train e010:  18%|█████████████████                                                                             | 27/149 [00:20<01:32,  1.31it/s, avg=0.09634, loss=0.09230]

trial_002 train e010:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:31,  1.32it/s, avg=0.09634, loss=0.09230]

trial_002 train e010:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:31,  1.32it/s, avg=0.09694, loss=0.11391]

trial_002 train e010:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:29,  1.34it/s, avg=0.09694, loss=0.11391]

trial_002 train e010:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:29,  1.34it/s, avg=0.09723, loss=0.10559]

trial_002 train e010:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:29,  1.33it/s, avg=0.09723, loss=0.10559]

trial_002 train e010:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:29,  1.33it/s, avg=0.09698, loss=0.08939]

trial_002 train e010:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:26,  1.37it/s, avg=0.09698, loss=0.08939]

trial_002 train e010:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.37it/s, avg=0.09767, loss=0.11903]

trial_002 train e010:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:27,  1.34it/s, avg=0.09767, loss=0.11903]

trial_002 train e010:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:27,  1.34it/s, avg=0.09747, loss=0.09115]

trial_002 train e010:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:26,  1.34it/s, avg=0.09747, loss=0.09115]

trial_002 train e010:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:26,  1.34it/s, avg=0.09777, loss=0.10773]

trial_002 train e010:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.09777, loss=0.10773]

trial_002 train e010:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.09733, loss=0.08233]

trial_002 train e010:  23%|██████████████████████                                                                        | 35/149 [00:25<01:24,  1.34it/s, avg=0.09733, loss=0.08233]

trial_002 train e010:  23%|██████████████████████                                                                        | 35/149 [00:26<01:24,  1.34it/s, avg=0.09724, loss=0.09401]

trial_002 train e010:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:22,  1.36it/s, avg=0.09724, loss=0.09401]

trial_002 train e010:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:22,  1.36it/s, avg=0.09733, loss=0.10042]

trial_002 train e010:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:23,  1.34it/s, avg=0.09733, loss=0.10042]

trial_002 train e010:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:23,  1.34it/s, avg=0.09766, loss=0.11002]

trial_002 train e010:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:22,  1.35it/s, avg=0.09766, loss=0.11002]

trial_002 train e010:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:22,  1.35it/s, avg=0.09732, loss=0.08442]

trial_002 train e010:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:21,  1.35it/s, avg=0.09732, loss=0.08442]

trial_002 train e010:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:21,  1.35it/s, avg=0.09741, loss=0.10094]

trial_002 train e010:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.38it/s, avg=0.09741, loss=0.10094]

trial_002 train e010:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:19,  1.38it/s, avg=0.09755, loss=0.10328]

trial_002 train e010:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.39it/s, avg=0.09755, loss=0.10328]

trial_002 train e010:  28%|█████████████████████████▊                                                                    | 41/149 [00:31<01:17,  1.39it/s, avg=0.09751, loss=0.09589]

trial_002 train e010:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:18,  1.37it/s, avg=0.09751, loss=0.09589]

trial_002 train e010:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:18,  1.37it/s, avg=0.09761, loss=0.10183]

trial_002 train e010:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:17,  1.37it/s, avg=0.09761, loss=0.10183]

trial_002 train e010:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:17,  1.37it/s, avg=0.09776, loss=0.10415]

trial_002 train e010:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.42it/s, avg=0.09776, loss=0.10415]

trial_002 train e010:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:14,  1.42it/s, avg=0.09738, loss=0.08052]

trial_002 train e010:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.38it/s, avg=0.09738, loss=0.08052]

trial_002 train e010:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.38it/s, avg=0.09716, loss=0.08724]

trial_002 train e010:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:13,  1.41it/s, avg=0.09716, loss=0.08724]

trial_002 train e010:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:13,  1.41it/s, avg=0.09696, loss=0.08756]

trial_002 train e010:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:12,  1.40it/s, avg=0.09696, loss=0.08756]

trial_002 train e010:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:12,  1.40it/s, avg=0.09726, loss=0.11152]

trial_002 train e010:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:13,  1.38it/s, avg=0.09726, loss=0.11152]

trial_002 train e010:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:13,  1.38it/s, avg=0.09736, loss=0.10203]

trial_002 train e010:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:13,  1.36it/s, avg=0.09736, loss=0.10203]

trial_002 train e010:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:13,  1.36it/s, avg=0.09754, loss=0.10652]

trial_002 train e010:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:11,  1.38it/s, avg=0.09754, loss=0.10652]

trial_002 train e010:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:11,  1.38it/s, avg=0.09749, loss=0.09488]

trial_002 train e010:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:11,  1.37it/s, avg=0.09749, loss=0.09488]

trial_002 train e010:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:11,  1.37it/s, avg=0.09732, loss=0.08886]

trial_002 train e010:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.09732, loss=0.08886]

trial_002 train e010:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.09749, loss=0.10623]

trial_002 train e010:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:09,  1.39it/s, avg=0.09749, loss=0.10623]

trial_002 train e010:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:09,  1.39it/s, avg=0.09740, loss=0.09253]

trial_002 train e010:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.37it/s, avg=0.09740, loss=0.09253]

trial_002 train e010:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:09,  1.37it/s, avg=0.09742, loss=0.09869]

trial_002 train e010:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:09,  1.36it/s, avg=0.09742, loss=0.09869]

trial_002 train e010:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:09,  1.36it/s, avg=0.09740, loss=0.09628]

trial_002 train e010:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.38it/s, avg=0.09740, loss=0.09628]

trial_002 train e010:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.38it/s, avg=0.09748, loss=0.10169]

trial_002 train e010:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.40it/s, avg=0.09748, loss=0.10169]

trial_002 train e010:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:05,  1.40it/s, avg=0.09720, loss=0.08157]

trial_002 train e010:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09720, loss=0.08157]

trial_002 train e010:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:06,  1.37it/s, avg=0.09712, loss=0.09259]

trial_002 train e010:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:05,  1.38it/s, avg=0.09712, loss=0.09259]

trial_002 train e010:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:05,  1.38it/s, avg=0.09688, loss=0.08230]

trial_002 train e010:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.35it/s, avg=0.09688, loss=0.08230]

trial_002 train e010:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.35it/s, avg=0.09694, loss=0.10074]

trial_002 train e010:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:05,  1.34it/s, avg=0.09694, loss=0.10074]

trial_002 train e010:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:05,  1.34it/s, avg=0.09710, loss=0.10692]

trial_002 train e010:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:04,  1.36it/s, avg=0.09710, loss=0.10692]

trial_002 train e010:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.36it/s, avg=0.09720, loss=0.10320]

trial_002 train e010:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:03,  1.35it/s, avg=0.09720, loss=0.10320]

trial_002 train e010:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:03,  1.35it/s, avg=0.09738, loss=0.10895]

trial_002 train e010:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:02,  1.37it/s, avg=0.09738, loss=0.10895]

trial_002 train e010:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:02,  1.37it/s, avg=0.09722, loss=0.08668]

trial_002 train e010:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:01,  1.36it/s, avg=0.09722, loss=0.08668]

trial_002 train e010:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.36it/s, avg=0.09715, loss=0.09300]

trial_002 train e010:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:01,  1.35it/s, avg=0.09715, loss=0.09300]

trial_002 train e010:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:01,  1.35it/s, avg=0.09739, loss=0.11325]

trial_002 train e010:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:01,  1.33it/s, avg=0.09739, loss=0.11325]

trial_002 train e010:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<01:01,  1.33it/s, avg=0.09724, loss=0.08677]

trial_002 train e010:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<01:00,  1.33it/s, avg=0.09724, loss=0.08677]

trial_002 train e010:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<01:00,  1.33it/s, avg=0.09740, loss=0.10840]

trial_002 train e010:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:58,  1.37it/s, avg=0.09740, loss=0.10840]

trial_002 train e010:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.37it/s, avg=0.09767, loss=0.11649]

trial_002 train e010:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.37it/s, avg=0.09767, loss=0.11649]

trial_002 train e010:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:57,  1.37it/s, avg=0.09773, loss=0.10160]

trial_002 train e010:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.36it/s, avg=0.09773, loss=0.10160]

trial_002 train e010:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.36it/s, avg=0.09775, loss=0.09942]

trial_002 train e010:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:56,  1.36it/s, avg=0.09775, loss=0.09942]

trial_002 train e010:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:56,  1.36it/s, avg=0.09770, loss=0.09394]

trial_002 train e010:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:55,  1.37it/s, avg=0.09770, loss=0.09394]

trial_002 train e010:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:55,  1.37it/s, avg=0.09769, loss=0.09691]

trial_002 train e010:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:54,  1.37it/s, avg=0.09769, loss=0.09691]

trial_002 train e010:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:54,  1.37it/s, avg=0.09764, loss=0.09385]

trial_002 train e010:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:54,  1.36it/s, avg=0.09764, loss=0.09385]

trial_002 train e010:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:54,  1.36it/s, avg=0.09764, loss=0.09769]

trial_002 train e010:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:52,  1.38it/s, avg=0.09764, loss=0.09769]

trial_002 train e010:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:52,  1.38it/s, avg=0.09760, loss=0.09474]

trial_002 train e010:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:52,  1.36it/s, avg=0.09760, loss=0.09474]

trial_002 train e010:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:52,  1.36it/s, avg=0.09749, loss=0.08922]

trial_002 train e010:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:52,  1.36it/s, avg=0.09749, loss=0.08922]

trial_002 train e010:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:58<00:52,  1.36it/s, avg=0.09754, loss=0.10114]

trial_002 train e010:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:50,  1.40it/s, avg=0.09754, loss=0.10114]

trial_002 train e010:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:50,  1.40it/s, avg=0.09744, loss=0.08936]

trial_002 train e010:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:49,  1.40it/s, avg=0.09744, loss=0.08936]

trial_002 train e010:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:49,  1.40it/s, avg=0.09739, loss=0.09343]

trial_002 train e010:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:48,  1.40it/s, avg=0.09739, loss=0.09343]

trial_002 train e010:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:48,  1.40it/s, avg=0.09763, loss=0.11770]

trial_002 train e010:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:47,  1.40it/s, avg=0.09763, loss=0.11770]

trial_002 train e010:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:47,  1.40it/s, avg=0.09757, loss=0.09223]

trial_002 train e010:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:47,  1.38it/s, avg=0.09757, loss=0.09223]

trial_002 train e010:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:47,  1.38it/s, avg=0.09757, loss=0.09755]

trial_002 train e010:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:48,  1.34it/s, avg=0.09757, loss=0.09755]

trial_002 train e010:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:48,  1.34it/s, avg=0.09754, loss=0.09513]

trial_002 train e010:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:47,  1.35it/s, avg=0.09754, loss=0.09513]

trial_002 train e010:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:47,  1.35it/s, avg=0.09753, loss=0.09634]

trial_002 train e010:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:46,  1.35it/s, avg=0.09753, loss=0.09634]

trial_002 train e010:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:46,  1.35it/s, avg=0.09758, loss=0.10218]

trial_002 train e010:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:45,  1.37it/s, avg=0.09758, loss=0.10218]

trial_002 train e010:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:45,  1.37it/s, avg=0.09757, loss=0.09654]

trial_002 train e010:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.37it/s, avg=0.09757, loss=0.09654]

trial_002 train e010:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:44,  1.37it/s, avg=0.09763, loss=0.10350]

trial_002 train e010:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:43,  1.37it/s, avg=0.09763, loss=0.10350]

trial_002 train e010:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:43,  1.37it/s, avg=0.09775, loss=0.10849]

trial_002 train e010:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.35it/s, avg=0.09775, loss=0.10849]

trial_002 train e010:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.35it/s, avg=0.09774, loss=0.09675]

trial_002 train e010:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.35it/s, avg=0.09774, loss=0.09675]

trial_002 train e010:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.35it/s, avg=0.09783, loss=0.10602]

trial_002 train e010:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:41,  1.36it/s, avg=0.09783, loss=0.10602]

trial_002 train e010:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:41,  1.36it/s, avg=0.09786, loss=0.10025]

trial_002 train e010:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:41,  1.36it/s, avg=0.09786, loss=0.10025]

trial_002 train e010:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:41,  1.36it/s, avg=0.09773, loss=0.08525]

trial_002 train e010:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.38it/s, avg=0.09773, loss=0.08525]

trial_002 train e010:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.38it/s, avg=0.09773, loss=0.09855]

trial_002 train e010:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:38,  1.39it/s, avg=0.09773, loss=0.09855]

trial_002 train e010:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:38,  1.39it/s, avg=0.09778, loss=0.10240]

trial_002 train e010:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:37,  1.40it/s, avg=0.09778, loss=0.10240]

trial_002 train e010:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:37,  1.40it/s, avg=0.09780, loss=0.09901]

trial_002 train e010:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:37,  1.39it/s, avg=0.09780, loss=0.09901]

trial_002 train e010:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:37,  1.39it/s, avg=0.09779, loss=0.09708]

trial_002 train e010:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.37it/s, avg=0.09779, loss=0.09708]

trial_002 train e010:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.37it/s, avg=0.09772, loss=0.09123]

trial_002 train e010:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.38it/s, avg=0.09772, loss=0.09123]

trial_002 train e010:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.38it/s, avg=0.09752, loss=0.07762]

trial_002 train e010:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.36it/s, avg=0.09752, loss=0.07762]

trial_002 train e010:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:35,  1.36it/s, avg=0.09753, loss=0.09835]

trial_002 train e010:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09753, loss=0.09835]

trial_002 train e010:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09752, loss=0.09709]

trial_002 train e010:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.36it/s, avg=0.09752, loss=0.09709]

trial_002 train e010:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:34,  1.36it/s, avg=0.09753, loss=0.09844]

trial_002 train e010:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.37it/s, avg=0.09753, loss=0.09844]

trial_002 train e010:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:33,  1.37it/s, avg=0.09747, loss=0.09045]

trial_002 train e010:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:33,  1.35it/s, avg=0.09747, loss=0.09045]

trial_002 train e010:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:33,  1.35it/s, avg=0.09750, loss=0.10086]

trial_002 train e010:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.37it/s, avg=0.09750, loss=0.10086]

trial_002 train e010:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.37it/s, avg=0.09742, loss=0.08954]

trial_002 train e010:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:30,  1.40it/s, avg=0.09742, loss=0.08954]

trial_002 train e010:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:30,  1.40it/s, avg=0.09728, loss=0.08204]

trial_002 train e010:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.38it/s, avg=0.09728, loss=0.08204]

trial_002 train e010:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:30,  1.38it/s, avg=0.09726, loss=0.09503]

trial_002 train e010:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:29,  1.39it/s, avg=0.09726, loss=0.09503]

trial_002 train e010:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:29,  1.39it/s, avg=0.09723, loss=0.09456]

trial_002 train e010:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:28,  1.41it/s, avg=0.09723, loss=0.09456]

trial_002 train e010:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:28,  1.41it/s, avg=0.09728, loss=0.10205]

trial_002 train e010:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.39it/s, avg=0.09728, loss=0.10205]

trial_002 train e010:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:28,  1.39it/s, avg=0.09726, loss=0.09538]

trial_002 train e010:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.37it/s, avg=0.09726, loss=0.09538]

trial_002 train e010:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:27,  1.37it/s, avg=0.09728, loss=0.09959]

trial_002 train e010:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:26,  1.37it/s, avg=0.09728, loss=0.09959]

trial_002 train e010:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:26,  1.37it/s, avg=0.09720, loss=0.08853]

trial_002 train e010:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.38it/s, avg=0.09720, loss=0.08853]

trial_002 train e010:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.38it/s, avg=0.09715, loss=0.09096]

trial_002 train e010:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.38it/s, avg=0.09715, loss=0.09096]

trial_002 train e010:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.38it/s, avg=0.09713, loss=0.09519]

trial_002 train e010:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:23,  1.43it/s, avg=0.09713, loss=0.09519]

trial_002 train e010:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:23,  1.43it/s, avg=0.09699, loss=0.08120]

trial_002 train e010:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.41it/s, avg=0.09699, loss=0.08120]

trial_002 train e010:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:23,  1.41it/s, avg=0.09716, loss=0.11673]

trial_002 train e010:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:22,  1.42it/s, avg=0.09716, loss=0.11673]

trial_002 train e010:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:22,  1.42it/s, avg=0.09713, loss=0.09379]

trial_002 train e010:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.38it/s, avg=0.09713, loss=0.09379]

trial_002 train e010:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:22,  1.38it/s, avg=0.09706, loss=0.08812]

trial_002 train e010:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.38it/s, avg=0.09706, loss=0.08812]

trial_002 train e010:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.38it/s, avg=0.09715, loss=0.10765]

trial_002 train e010:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:20,  1.42it/s, avg=0.09715, loss=0.10765]

trial_002 train e010:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:20,  1.42it/s, avg=0.09714, loss=0.09584]

trial_002 train e010:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:19,  1.43it/s, avg=0.09714, loss=0.09584]

trial_002 train e010:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:19,  1.43it/s, avg=0.09717, loss=0.10082]

trial_002 train e010:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.38it/s, avg=0.09717, loss=0.10082]

trial_002 train e010:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.38it/s, avg=0.09729, loss=0.11252]

trial_002 train e010:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:18,  1.37it/s, avg=0.09729, loss=0.11252]

trial_002 train e010:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:18,  1.37it/s, avg=0.09725, loss=0.09241]

trial_002 train e010:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.38it/s, avg=0.09725, loss=0.09241]

trial_002 train e010:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.38it/s, avg=0.09712, loss=0.08091]

trial_002 train e010:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.36it/s, avg=0.09712, loss=0.08091]

trial_002 train e010:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.36it/s, avg=0.09708, loss=0.09196]

trial_002 train e010:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:17,  1.35it/s, avg=0.09708, loss=0.09196]

trial_002 train e010:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:17,  1.35it/s, avg=0.09706, loss=0.09480]

trial_002 train e010:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:16,  1.35it/s, avg=0.09706, loss=0.09480]

trial_002 train e010:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.35it/s, avg=0.09710, loss=0.10140]

trial_002 train e010:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.37it/s, avg=0.09710, loss=0.10140]

trial_002 train e010:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.37it/s, avg=0.09698, loss=0.08206]

trial_002 train e010:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.35it/s, avg=0.09698, loss=0.08206]

trial_002 train e010:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.35it/s, avg=0.09697, loss=0.09567]

trial_002 train e010:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:14,  1.35it/s, avg=0.09697, loss=0.09567]

trial_002 train e010:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:14,  1.35it/s, avg=0.09698, loss=0.09775]

trial_002 train e010:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.35it/s, avg=0.09698, loss=0.09775]

trial_002 train e010:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.35it/s, avg=0.09701, loss=0.10186]

trial_002 train e010:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.35it/s, avg=0.09701, loss=0.10186]

trial_002 train e010:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.35it/s, avg=0.09697, loss=0.09149]

trial_002 train e010:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:12,  1.33it/s, avg=0.09697, loss=0.09149]

trial_002 train e010:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:12,  1.33it/s, avg=0.09701, loss=0.10275]

trial_002 train e010:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:11,  1.33it/s, avg=0.09701, loss=0.10275]

trial_002 train e010:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:11,  1.33it/s, avg=0.09699, loss=0.09362]

trial_002 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.34it/s, avg=0.09699, loss=0.09362]

trial_002 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.34it/s, avg=0.09695, loss=0.09119]

trial_002 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.37it/s, avg=0.09695, loss=0.09119]

trial_002 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.37it/s, avg=0.09690, loss=0.09062]

trial_002 train e010:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.37it/s, avg=0.09690, loss=0.09062]

trial_002 train e010:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:41<00:08,  1.37it/s, avg=0.09685, loss=0.09026]

trial_002 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.35it/s, avg=0.09685, loss=0.09026]

trial_002 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.35it/s, avg=0.09682, loss=0.09217]

trial_002 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.36it/s, avg=0.09682, loss=0.09217]

trial_002 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.36it/s, avg=0.09687, loss=0.10428]

trial_002 train e010:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.34it/s, avg=0.09687, loss=0.10428]

trial_002 train e010:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.34it/s, avg=0.09687, loss=0.09601]

trial_002 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.39it/s, avg=0.09687, loss=0.09601]

trial_002 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.39it/s, avg=0.09680, loss=0.08760]

trial_002 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:04,  1.40it/s, avg=0.09680, loss=0.08760]

trial_002 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:04,  1.40it/s, avg=0.09679, loss=0.09579]

trial_002 train e010:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.40it/s, avg=0.09679, loss=0.09579]

trial_002 train e010:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.40it/s, avg=0.09682, loss=0.10076]

trial_002 train e010:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.38it/s, avg=0.09682, loss=0.10076]

trial_002 train e010:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:46<00:03,  1.38it/s, avg=0.09683, loss=0.09768]

trial_002 train e010:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.41it/s, avg=0.09683, loss=0.09768]

trial_002 train e010:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.41it/s, avg=0.09682, loss=0.09649]

trial_002 train e010:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.38it/s, avg=0.09682, loss=0.09649]

trial_002 train e010:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.38it/s, avg=0.09685, loss=0.10013]

trial_002 train e010:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.37it/s, avg=0.09685, loss=0.10013]

trial_002 train e010:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.37it/s, avg=0.09685, loss=0.09670]

trial_002 train e010:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.35it/s, avg=0.09685, loss=0.09670]

trial_002 train e010:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.35it/s, avg=0.09694, loss=0.13207]

trial_002 train e010: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.64it/s, avg=0.09694, loss=0.13207]

trial_002 val e010:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e010:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.39it/s]

trial_002 val e010:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.44it/s]

trial_002 val e010:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.46it/s]

trial_002 val e010:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.47it/s]

trial_002 val e010:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.48it/s]

trial_002 val e010:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.48it/s]

trial_002 val e010:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.47it/s]

trial_002 val e010:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:16,  2.47it/s]

trial_002 val e010:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.47it/s]

trial_002 val e010:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.46it/s]

trial_002 val e010:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.39it/s]

trial_002 val e010:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.38it/s]

trial_002 val e010:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.40it/s]

trial_002 val e010:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.42it/s]

trial_002 val e010:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.44it/s]

trial_002 val e010:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.46it/s]

trial_002 val e010:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.47it/s]

trial_002 val e010:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:12,  2.48it/s]

trial_002 val e010:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.49it/s]

trial_002 val e010:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.49it/s]

trial_002 val e010:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.50it/s]

trial_002 val e010:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:08<00:11,  2.48it/s]

trial_002 val e010:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:10,  2.47it/s]

trial_002 val e010:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.45it/s]

trial_002 val e010:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.43it/s]

trial_002 val e010:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.43it/s]

trial_002 val e010:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.45it/s]

trial_002 val e010:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.46it/s]

trial_002 val e010:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.45it/s]

trial_002 val e010:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.47it/s]

trial_002 val e010:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.48it/s]

trial_002 val e010:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.48it/s]

trial_002 val e010:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.49it/s]

trial_002 val e010:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.49it/s]

trial_002 val e010:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.50it/s]

trial_002 val e010:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.49it/s]

trial_002 val e010:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.49it/s]

trial_002 val e010:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.46it/s]

trial_002 val e010:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.45it/s]

trial_002 val e010:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.45it/s]

trial_002 val e010:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.41it/s]

trial_002 val e010:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.41it/s]

trial_002 val e010:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.42it/s]

trial_002 val e010:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.43it/s]

trial_002 val e010:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.45it/s]

trial_002 val e010:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.46it/s]

trial_002 val e010:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.47it/s]

trial_002 val e010:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.47it/s]

trial_002 val e010:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.48it/s]

trial_002 val e010: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.50it/s]

[2026-05-28 20:45:41] [trial_002] epoch=010 | train_loss=0.096941 | val_MAE=0.099001 | val_S=0.900999 | best_S=0.900999 @epoch=10 | patience=0/5

[trial_002] epochs:  10%|████████████                                                                                                            | 10/100 [22:04<3:15:04, 130.05s/it]

trial_002 train e011:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e011:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08459, loss=0.08459]

trial_002 train e011:   1%|▋                                                                                              | 1/149 [00:00<01:50,  1.34it/s, avg=0.08459, loss=0.08459]

trial_002 train e011:   1%|▋                                                                                              | 1/149 [00:01<01:50,  1.34it/s, avg=0.09321, loss=0.10183]

trial_002 train e011:   1%|█▎                                                                                             | 2/149 [00:01<01:46,  1.38it/s, avg=0.09321, loss=0.10183]

trial_002 train e011:   1%|█▎                                                                                             | 2/149 [00:02<01:46,  1.38it/s, avg=0.09612, loss=0.10194]

trial_002 train e011:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.09612, loss=0.10194]

trial_002 train e011:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.38it/s, avg=0.09784, loss=0.10300]

trial_002 train e011:   3%|██▌                                                                                            | 4/149 [00:02<01:44,  1.38it/s, avg=0.09784, loss=0.10300]

trial_002 train e011:   3%|██▌                                                                                            | 4/149 [00:03<01:44,  1.38it/s, avg=0.09725, loss=0.09489]

trial_002 train e011:   3%|███▏                                                                                           | 5/149 [00:03<01:44,  1.37it/s, avg=0.09725, loss=0.09489]

trial_002 train e011:   3%|███▏                                                                                           | 5/149 [00:04<01:44,  1.37it/s, avg=0.09942, loss=0.11028]

trial_002 train e011:   4%|███▊                                                                                           | 6/149 [00:04<01:40,  1.42it/s, avg=0.09942, loss=0.11028]

trial_002 train e011:   4%|███▊                                                                                           | 6/149 [00:05<01:40,  1.42it/s, avg=0.09861, loss=0.09374]

trial_002 train e011:   5%|████▍                                                                                          | 7/149 [00:05<01:40,  1.41it/s, avg=0.09861, loss=0.09374]

trial_002 train e011:   5%|████▍                                                                                          | 7/149 [00:05<01:40,  1.41it/s, avg=0.09975, loss=0.10777]

trial_002 train e011:   5%|█████                                                                                          | 8/149 [00:05<01:41,  1.39it/s, avg=0.09975, loss=0.10777]

trial_002 train e011:   5%|█████                                                                                          | 8/149 [00:06<01:41,  1.39it/s, avg=0.09853, loss=0.08873]

trial_002 train e011:   6%|█████▋                                                                                         | 9/149 [00:06<01:40,  1.40it/s, avg=0.09853, loss=0.08873]

trial_002 train e011:   6%|█████▋                                                                                         | 9/149 [00:07<01:40,  1.40it/s, avg=0.09835, loss=0.09672]

trial_002 train e011:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.39it/s, avg=0.09835, loss=0.09672]

trial_002 train e011:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.39it/s, avg=0.09765, loss=0.09066]

trial_002 train e011:   7%|██████▉                                                                                       | 11/149 [00:07<01:40,  1.38it/s, avg=0.09765, loss=0.09066]

trial_002 train e011:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.38it/s, avg=0.09696, loss=0.08933]

trial_002 train e011:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.36it/s, avg=0.09696, loss=0.08933]

trial_002 train e011:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.36it/s, avg=0.09634, loss=0.08894]

trial_002 train e011:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.09634, loss=0.08894]

trial_002 train e011:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.09567, loss=0.08693]

trial_002 train e011:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.38it/s, avg=0.09567, loss=0.08693]

trial_002 train e011:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.38it/s, avg=0.09527, loss=0.08963]

trial_002 train e011:  10%|█████████▍                                                                                    | 15/149 [00:10<01:38,  1.36it/s, avg=0.09527, loss=0.08963]

trial_002 train e011:  10%|█████████▍                                                                                    | 15/149 [00:11<01:38,  1.36it/s, avg=0.09509, loss=0.09245]

trial_002 train e011:  11%|██████████                                                                                    | 16/149 [00:11<01:38,  1.35it/s, avg=0.09509, loss=0.09245]

trial_002 train e011:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.35it/s, avg=0.09431, loss=0.08185]

trial_002 train e011:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.34it/s, avg=0.09431, loss=0.08185]

trial_002 train e011:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.34it/s, avg=0.09395, loss=0.08773]

trial_002 train e011:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.09395, loss=0.08773]

trial_002 train e011:  12%|███████████▎                                                                                  | 18/149 [00:13<01:37,  1.34it/s, avg=0.09386, loss=0.09227]

trial_002 train e011:  13%|███████████▉                                                                                  | 19/149 [00:13<01:35,  1.36it/s, avg=0.09386, loss=0.09227]

trial_002 train e011:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.36it/s, avg=0.09322, loss=0.08107]

trial_002 train e011:  13%|████████████▌                                                                                 | 20/149 [00:14<01:35,  1.35it/s, avg=0.09322, loss=0.08107]

trial_002 train e011:  13%|████████████▌                                                                                 | 20/149 [00:15<01:35,  1.35it/s, avg=0.09415, loss=0.11283]

trial_002 train e011:  14%|█████████████▏                                                                                | 21/149 [00:15<01:33,  1.38it/s, avg=0.09415, loss=0.11283]

trial_002 train e011:  14%|█████████████▏                                                                                | 21/149 [00:15<01:33,  1.38it/s, avg=0.09437, loss=0.09889]

trial_002 train e011:  15%|█████████████▉                                                                                | 22/149 [00:15<01:30,  1.41it/s, avg=0.09437, loss=0.09889]

trial_002 train e011:  15%|█████████████▉                                                                                | 22/149 [00:16<01:30,  1.41it/s, avg=0.09467, loss=0.10128]

trial_002 train e011:  15%|██████████████▌                                                                               | 23/149 [00:16<01:31,  1.37it/s, avg=0.09467, loss=0.10128]

trial_002 train e011:  15%|██████████████▌                                                                               | 23/149 [00:17<01:31,  1.37it/s, avg=0.09481, loss=0.09797]

trial_002 train e011:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.36it/s, avg=0.09481, loss=0.09797]

trial_002 train e011:  16%|███████████████▏                                                                              | 24/149 [00:18<01:31,  1.36it/s, avg=0.09505, loss=0.10083]

trial_002 train e011:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.38it/s, avg=0.09505, loss=0.10083]

trial_002 train e011:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.38it/s, avg=0.09507, loss=0.09569]

trial_002 train e011:  17%|████████████████▍                                                                             | 26/149 [00:18<01:30,  1.36it/s, avg=0.09507, loss=0.09569]

trial_002 train e011:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.36it/s, avg=0.09505, loss=0.09444]

trial_002 train e011:  18%|█████████████████                                                                             | 27/149 [00:19<01:29,  1.37it/s, avg=0.09505, loss=0.09444]

trial_002 train e011:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.37it/s, avg=0.09492, loss=0.09149]

trial_002 train e011:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:27,  1.38it/s, avg=0.09492, loss=0.09149]

trial_002 train e011:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:27,  1.38it/s, avg=0.09512, loss=0.10064]

trial_002 train e011:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:28,  1.36it/s, avg=0.09512, loss=0.10064]

trial_002 train e011:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:28,  1.36it/s, avg=0.09510, loss=0.09462]

trial_002 train e011:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:29,  1.33it/s, avg=0.09510, loss=0.09462]

trial_002 train e011:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:29,  1.33it/s, avg=0.09462, loss=0.08014]

trial_002 train e011:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:28,  1.33it/s, avg=0.09462, loss=0.08014]

trial_002 train e011:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:28,  1.33it/s, avg=0.09453, loss=0.09187]

trial_002 train e011:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:28,  1.32it/s, avg=0.09453, loss=0.09187]

trial_002 train e011:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:28,  1.32it/s, avg=0.09496, loss=0.10867]

trial_002 train e011:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:27,  1.32it/s, avg=0.09496, loss=0.10867]

trial_002 train e011:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:27,  1.32it/s, avg=0.09491, loss=0.09313]

trial_002 train e011:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.09491, loss=0.09313]

trial_002 train e011:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.09549, loss=0.11526]

trial_002 train e011:  23%|██████████████████████                                                                        | 35/149 [00:25<01:21,  1.40it/s, avg=0.09549, loss=0.11526]

trial_002 train e011:  23%|██████████████████████                                                                        | 35/149 [00:26<01:21,  1.40it/s, avg=0.09544, loss=0.09356]

trial_002 train e011:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.38it/s, avg=0.09544, loss=0.09356]

trial_002 train e011:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.38it/s, avg=0.09529, loss=0.09009]

trial_002 train e011:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:20,  1.39it/s, avg=0.09529, loss=0.09009]

trial_002 train e011:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:20,  1.39it/s, avg=0.09555, loss=0.10515]

trial_002 train e011:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.38it/s, avg=0.09555, loss=0.10515]

trial_002 train e011:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:20,  1.38it/s, avg=0.09562, loss=0.09823]

trial_002 train e011:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:18,  1.39it/s, avg=0.09562, loss=0.09823]

trial_002 train e011:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:18,  1.39it/s, avg=0.09566, loss=0.09717]

trial_002 train e011:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.37it/s, avg=0.09566, loss=0.09717]

trial_002 train e011:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.37it/s, avg=0.09572, loss=0.09822]

trial_002 train e011:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:19,  1.36it/s, avg=0.09572, loss=0.09822]

trial_002 train e011:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:19,  1.36it/s, avg=0.09602, loss=0.10835]

trial_002 train e011:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:18,  1.36it/s, avg=0.09602, loss=0.10835]

trial_002 train e011:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:18,  1.36it/s, avg=0.09613, loss=0.10072]

trial_002 train e011:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:16,  1.38it/s, avg=0.09613, loss=0.10072]

trial_002 train e011:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:16,  1.38it/s, avg=0.09651, loss=0.11308]

trial_002 train e011:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.42it/s, avg=0.09651, loss=0.11308]

trial_002 train e011:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.42it/s, avg=0.09627, loss=0.08539]

trial_002 train e011:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.09627, loss=0.08539]

trial_002 train e011:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:13,  1.41it/s, avg=0.09616, loss=0.09133]

trial_002 train e011:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.38it/s, avg=0.09616, loss=0.09133]

trial_002 train e011:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:14,  1.38it/s, avg=0.09609, loss=0.09304]

trial_002 train e011:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.39it/s, avg=0.09609, loss=0.09304]

trial_002 train e011:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.39it/s, avg=0.09620, loss=0.10117]

trial_002 train e011:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:14,  1.36it/s, avg=0.09620, loss=0.10117]

trial_002 train e011:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.36it/s, avg=0.09626, loss=0.09932]

trial_002 train e011:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:11,  1.40it/s, avg=0.09626, loss=0.09932]

trial_002 train e011:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:11,  1.40it/s, avg=0.09621, loss=0.09339]

trial_002 train e011:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:12,  1.37it/s, avg=0.09621, loss=0.09339]

trial_002 train e011:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:12,  1.37it/s, avg=0.09640, loss=0.10618]

trial_002 train e011:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:12,  1.35it/s, avg=0.09640, loss=0.10618]

trial_002 train e011:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:12,  1.35it/s, avg=0.09629, loss=0.09068]

trial_002 train e011:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:11,  1.35it/s, avg=0.09629, loss=0.09068]

trial_002 train e011:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:11,  1.35it/s, avg=0.09606, loss=0.08425]

trial_002 train e011:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:11,  1.34it/s, avg=0.09606, loss=0.08425]

trial_002 train e011:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:11,  1.34it/s, avg=0.09608, loss=0.09668]

trial_002 train e011:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.36it/s, avg=0.09608, loss=0.09668]

trial_002 train e011:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:09,  1.36it/s, avg=0.09614, loss=0.09935]

trial_002 train e011:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.36it/s, avg=0.09614, loss=0.09935]

trial_002 train e011:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.36it/s, avg=0.09615, loss=0.09714]

trial_002 train e011:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:09,  1.34it/s, avg=0.09615, loss=0.09714]

trial_002 train e011:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:09,  1.34it/s, avg=0.09625, loss=0.10187]

trial_002 train e011:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:08,  1.35it/s, avg=0.09625, loss=0.10187]

trial_002 train e011:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.35it/s, avg=0.09650, loss=0.11032]

trial_002 train e011:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09650, loss=0.11032]

trial_002 train e011:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:06,  1.37it/s, avg=0.09640, loss=0.09109]

trial_002 train e011:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09640, loss=0.09109]

trial_002 train e011:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09636, loss=0.09364]

trial_002 train e011:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:05,  1.36it/s, avg=0.09636, loss=0.09364]

trial_002 train e011:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.36it/s, avg=0.09639, loss=0.09809]

trial_002 train e011:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.36it/s, avg=0.09639, loss=0.09809]

trial_002 train e011:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:04,  1.36it/s, avg=0.09669, loss=0.11508]

trial_002 train e011:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:03,  1.38it/s, avg=0.09669, loss=0.11508]

trial_002 train e011:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:03,  1.38it/s, avg=0.09661, loss=0.09207]

trial_002 train e011:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:02,  1.38it/s, avg=0.09661, loss=0.09207]

trial_002 train e011:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.38it/s, avg=0.09643, loss=0.08491]

trial_002 train e011:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.37it/s, avg=0.09643, loss=0.08491]

trial_002 train e011:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:01,  1.37it/s, avg=0.09647, loss=0.09914]

trial_002 train e011:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:01,  1.36it/s, avg=0.09647, loss=0.09914]

trial_002 train e011:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.36it/s, avg=0.09636, loss=0.08922]

trial_002 train e011:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:00,  1.38it/s, avg=0.09636, loss=0.08922]

trial_002 train e011:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:00,  1.38it/s, avg=0.09640, loss=0.09862]

trial_002 train e011:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:59,  1.37it/s, avg=0.09640, loss=0.09862]

trial_002 train e011:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:59,  1.37it/s, avg=0.09642, loss=0.09822]

trial_002 train e011:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:58,  1.39it/s, avg=0.09642, loss=0.09822]

trial_002 train e011:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:58,  1.39it/s, avg=0.09638, loss=0.09364]

trial_002 train e011:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:57,  1.39it/s, avg=0.09638, loss=0.09364]

trial_002 train e011:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:57,  1.39it/s, avg=0.09641, loss=0.09823]

trial_002 train e011:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.35it/s, avg=0.09641, loss=0.09823]

trial_002 train e011:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.35it/s, avg=0.09621, loss=0.08247]

trial_002 train e011:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:57,  1.35it/s, avg=0.09621, loss=0.08247]

trial_002 train e011:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.35it/s, avg=0.09620, loss=0.09511]

trial_002 train e011:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:57,  1.33it/s, avg=0.09620, loss=0.09511]

trial_002 train e011:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:57,  1.33it/s, avg=0.09608, loss=0.08765]

trial_002 train e011:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:57,  1.31it/s, avg=0.09608, loss=0.08765]

trial_002 train e011:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:57,  1.31it/s, avg=0.09624, loss=0.10808]

trial_002 train e011:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:56,  1.33it/s, avg=0.09624, loss=0.10808]

trial_002 train e011:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:56,  1.33it/s, avg=0.09621, loss=0.09345]

trial_002 train e011:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:52,  1.40it/s, avg=0.09621, loss=0.09345]

trial_002 train e011:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:52,  1.40it/s, avg=0.09620, loss=0.09545]

trial_002 train e011:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:52,  1.38it/s, avg=0.09620, loss=0.09545]

trial_002 train e011:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:52,  1.38it/s, avg=0.09604, loss=0.08413]

trial_002 train e011:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:52,  1.37it/s, avg=0.09604, loss=0.08413]

trial_002 train e011:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:52,  1.37it/s, avg=0.09603, loss=0.09550]

trial_002 train e011:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.39it/s, avg=0.09603, loss=0.09550]

trial_002 train e011:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.39it/s, avg=0.09607, loss=0.09890]

trial_002 train e011:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:50,  1.39it/s, avg=0.09607, loss=0.09890]

trial_002 train e011:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:50,  1.39it/s, avg=0.09598, loss=0.08900]

trial_002 train e011:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.36it/s, avg=0.09598, loss=0.08900]

trial_002 train e011:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:50,  1.36it/s, avg=0.09599, loss=0.09697]

trial_002 train e011:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.36it/s, avg=0.09599, loss=0.09697]

trial_002 train e011:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.36it/s, avg=0.09596, loss=0.09302]

trial_002 train e011:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:50,  1.34it/s, avg=0.09596, loss=0.09302]

trial_002 train e011:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:50,  1.34it/s, avg=0.09593, loss=0.09400]

trial_002 train e011:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.36it/s, avg=0.09593, loss=0.09400]

trial_002 train e011:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:48,  1.36it/s, avg=0.09590, loss=0.09343]

trial_002 train e011:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:47,  1.37it/s, avg=0.09590, loss=0.09343]

trial_002 train e011:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:47,  1.37it/s, avg=0.09585, loss=0.09164]

trial_002 train e011:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.37it/s, avg=0.09585, loss=0.09164]

trial_002 train e011:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.37it/s, avg=0.09578, loss=0.08959]

trial_002 train e011:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:46,  1.36it/s, avg=0.09578, loss=0.08959]

trial_002 train e011:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:46,  1.36it/s, avg=0.09575, loss=0.09349]

trial_002 train e011:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:45,  1.35it/s, avg=0.09575, loss=0.09349]

trial_002 train e011:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:45,  1.35it/s, avg=0.09584, loss=0.10340]

trial_002 train e011:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:45,  1.35it/s, avg=0.09584, loss=0.10340]

trial_002 train e011:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:45,  1.35it/s, avg=0.09570, loss=0.08318]

trial_002 train e011:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.36it/s, avg=0.09570, loss=0.08318]

trial_002 train e011:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.36it/s, avg=0.09575, loss=0.10008]

trial_002 train e011:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.36it/s, avg=0.09575, loss=0.10008]

trial_002 train e011:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.36it/s, avg=0.09579, loss=0.09936]

trial_002 train e011:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.36it/s, avg=0.09579, loss=0.09936]

trial_002 train e011:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.36it/s, avg=0.09595, loss=0.11038]

trial_002 train e011:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:41,  1.37it/s, avg=0.09595, loss=0.11038]

trial_002 train e011:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:41,  1.37it/s, avg=0.09595, loss=0.09669]

trial_002 train e011:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.37it/s, avg=0.09595, loss=0.09669]

trial_002 train e011:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.37it/s, avg=0.09595, loss=0.09535]

trial_002 train e011:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:39,  1.39it/s, avg=0.09595, loss=0.09535]

trial_002 train e011:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.39it/s, avg=0.09593, loss=0.09410]

trial_002 train e011:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.37it/s, avg=0.09593, loss=0.09410]

trial_002 train e011:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:39,  1.37it/s, avg=0.09581, loss=0.08509]

trial_002 train e011:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.09581, loss=0.08509]

trial_002 train e011:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.09585, loss=0.09963]

trial_002 train e011:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:37,  1.38it/s, avg=0.09585, loss=0.09963]

trial_002 train e011:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:37,  1.38it/s, avg=0.09593, loss=0.10335]

trial_002 train e011:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.37it/s, avg=0.09593, loss=0.10335]

trial_002 train e011:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.37it/s, avg=0.09599, loss=0.10230]

trial_002 train e011:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.09599, loss=0.10230]

trial_002 train e011:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.37it/s, avg=0.09617, loss=0.11318]

trial_002 train e011:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.36it/s, avg=0.09617, loss=0.11318]

trial_002 train e011:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.36it/s, avg=0.09635, loss=0.11461]

trial_002 train e011:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.41it/s, avg=0.09635, loss=0.11461]

trial_002 train e011:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:34,  1.41it/s, avg=0.09630, loss=0.09171]

trial_002 train e011:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:33,  1.41it/s, avg=0.09630, loss=0.09171]

trial_002 train e011:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:33,  1.41it/s, avg=0.09633, loss=0.09898]

trial_002 train e011:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.37it/s, avg=0.09633, loss=0.09898]

trial_002 train e011:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.37it/s, avg=0.09625, loss=0.08786]

trial_002 train e011:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.38it/s, avg=0.09625, loss=0.08786]

trial_002 train e011:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:32,  1.38it/s, avg=0.09630, loss=0.10184]

trial_002 train e011:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:31,  1.39it/s, avg=0.09630, loss=0.10184]

trial_002 train e011:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:31,  1.39it/s, avg=0.09638, loss=0.10445]

trial_002 train e011:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:30,  1.41it/s, avg=0.09638, loss=0.10445]

trial_002 train e011:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:30,  1.41it/s, avg=0.09636, loss=0.09447]

trial_002 train e011:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:29,  1.42it/s, avg=0.09636, loss=0.09447]

trial_002 train e011:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:29,  1.42it/s, avg=0.09631, loss=0.09132]

trial_002 train e011:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:27,  1.47it/s, avg=0.09631, loss=0.09132]

trial_002 train e011:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:27,  1.47it/s, avg=0.09630, loss=0.09521]

trial_002 train e011:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:28,  1.42it/s, avg=0.09630, loss=0.09521]

trial_002 train e011:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:28,  1.42it/s, avg=0.09623, loss=0.08820]

trial_002 train e011:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.37it/s, avg=0.09623, loss=0.08820]

trial_002 train e011:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.37it/s, avg=0.09624, loss=0.09719]

trial_002 train e011:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.36it/s, avg=0.09624, loss=0.09719]

trial_002 train e011:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.36it/s, avg=0.09612, loss=0.08306]

trial_002 train e011:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:26,  1.38it/s, avg=0.09612, loss=0.08306]

trial_002 train e011:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:26,  1.38it/s, avg=0.09610, loss=0.09372]

trial_002 train e011:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:25,  1.41it/s, avg=0.09610, loss=0.09372]

trial_002 train e011:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:25,  1.41it/s, avg=0.09618, loss=0.10545]

trial_002 train e011:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:24,  1.41it/s, avg=0.09618, loss=0.10545]

trial_002 train e011:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:24,  1.41it/s, avg=0.09600, loss=0.07576]

trial_002 train e011:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.37it/s, avg=0.09600, loss=0.07576]

trial_002 train e011:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.37it/s, avg=0.09602, loss=0.09758]

trial_002 train e011:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.38it/s, avg=0.09602, loss=0.09758]

trial_002 train e011:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:23,  1.38it/s, avg=0.09599, loss=0.09304]

trial_002 train e011:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.35it/s, avg=0.09599, loss=0.09304]

trial_002 train e011:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.35it/s, avg=0.09600, loss=0.09685]

trial_002 train e011:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.35it/s, avg=0.09600, loss=0.09685]

trial_002 train e011:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.35it/s, avg=0.09598, loss=0.09326]

trial_002 train e011:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:22,  1.34it/s, avg=0.09598, loss=0.09326]

trial_002 train e011:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:22,  1.34it/s, avg=0.09600, loss=0.09837]

trial_002 train e011:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:21,  1.33it/s, avg=0.09600, loss=0.09837]

trial_002 train e011:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.33it/s, avg=0.09603, loss=0.10050]

trial_002 train e011:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.34it/s, avg=0.09603, loss=0.10050]

trial_002 train e011:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.34it/s, avg=0.09597, loss=0.08800]

trial_002 train e011:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.36it/s, avg=0.09597, loss=0.08800]

trial_002 train e011:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.36it/s, avg=0.09593, loss=0.09102]

trial_002 train e011:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:19,  1.35it/s, avg=0.09593, loss=0.09102]

trial_002 train e011:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.35it/s, avg=0.09602, loss=0.10741]

trial_002 train e011:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.35it/s, avg=0.09602, loss=0.10741]

trial_002 train e011:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.35it/s, avg=0.09592, loss=0.08354]

trial_002 train e011:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.36it/s, avg=0.09592, loss=0.08354]

trial_002 train e011:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.36it/s, avg=0.09590, loss=0.09338]

trial_002 train e011:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.36it/s, avg=0.09590, loss=0.09338]

trial_002 train e011:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.36it/s, avg=0.09598, loss=0.10579]

trial_002 train e011:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:16,  1.35it/s, avg=0.09598, loss=0.10579]

trial_002 train e011:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.35it/s, avg=0.09598, loss=0.09650]

trial_002 train e011:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.36it/s, avg=0.09598, loss=0.09650]

trial_002 train e011:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.36it/s, avg=0.09594, loss=0.09037]

trial_002 train e011:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.37it/s, avg=0.09594, loss=0.09037]

trial_002 train e011:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.37it/s, avg=0.09593, loss=0.09465]

trial_002 train e011:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.36it/s, avg=0.09593, loss=0.09465]

trial_002 train e011:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.36it/s, avg=0.09589, loss=0.09129]

trial_002 train e011:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.36it/s, avg=0.09589, loss=0.09129]

trial_002 train e011:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.36it/s, avg=0.09586, loss=0.09126]

trial_002 train e011:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.34it/s, avg=0.09586, loss=0.09126]

trial_002 train e011:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.34it/s, avg=0.09592, loss=0.10362]

trial_002 train e011:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.35it/s, avg=0.09592, loss=0.10362]

trial_002 train e011:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.35it/s, avg=0.09586, loss=0.08762]

trial_002 train e011:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:11,  1.36it/s, avg=0.09586, loss=0.08762]

trial_002 train e011:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:11,  1.36it/s, avg=0.09580, loss=0.08827]

trial_002 train e011:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.36it/s, avg=0.09580, loss=0.08827]

trial_002 train e011:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.36it/s, avg=0.09575, loss=0.08932]

trial_002 train e011:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.36it/s, avg=0.09575, loss=0.08932]

trial_002 train e011:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.36it/s, avg=0.09595, loss=0.12279]

trial_002 train e011:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.38it/s, avg=0.09595, loss=0.12279]

trial_002 train e011:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.38it/s, avg=0.09595, loss=0.09601]

trial_002 train e011:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:07,  1.38it/s, avg=0.09595, loss=0.09601]

trial_002 train e011:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:07,  1.38it/s, avg=0.09602, loss=0.10598]

trial_002 train e011:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.35it/s, avg=0.09602, loss=0.10598]

trial_002 train e011:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.35it/s, avg=0.09608, loss=0.10412]

trial_002 train e011:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.35it/s, avg=0.09608, loss=0.10412]

trial_002 train e011:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.35it/s, avg=0.09615, loss=0.10590]

trial_002 train e011:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.37it/s, avg=0.09615, loss=0.10590]

trial_002 train e011:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.37it/s, avg=0.09610, loss=0.08858]

trial_002 train e011:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:05,  1.36it/s, avg=0.09610, loss=0.08858]

trial_002 train e011:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.36it/s, avg=0.09606, loss=0.09064]

trial_002 train e011:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.36it/s, avg=0.09606, loss=0.09064]

trial_002 train e011:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.36it/s, avg=0.09613, loss=0.10635]

trial_002 train e011:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.39it/s, avg=0.09613, loss=0.10635]

trial_002 train e011:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.39it/s, avg=0.09606, loss=0.08637]

trial_002 train e011:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.37it/s, avg=0.09606, loss=0.08637]

trial_002 train e011:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.37it/s, avg=0.09608, loss=0.09942]

trial_002 train e011:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.36it/s, avg=0.09608, loss=0.09942]

trial_002 train e011:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.36it/s, avg=0.09605, loss=0.09067]

trial_002 train e011:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.40it/s, avg=0.09605, loss=0.09067]

trial_002 train e011:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.40it/s, avg=0.09608, loss=0.10143]

trial_002 train e011:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.39it/s, avg=0.09608, loss=0.10143]

trial_002 train e011:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.39it/s, avg=0.09607, loss=0.08931]

trial_002 train e011: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.67it/s, avg=0.09607, loss=0.08931]

trial_002 val e011:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e011:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.40it/s]

trial_002 val e011:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.46it/s]

trial_002 val e011:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:18,  2.48it/s]

trial_002 val e011:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.49it/s]

trial_002 val e011:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.41it/s]

trial_002 val e011:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.43it/s]

trial_002 val e011:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.45it/s]

trial_002 val e011:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.47it/s]

trial_002 val e011:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.45it/s]

trial_002 val e011:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.45it/s]

trial_002 val e011:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.46it/s]

trial_002 val e011:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.47it/s]

trial_002 val e011:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:14,  2.48it/s]

trial_002 val e011:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.49it/s]

trial_002 val e011:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.49it/s]

trial_002 val e011:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.49it/s]

trial_002 val e011:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.50it/s]

trial_002 val e011:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:12,  2.50it/s]

trial_002 val e011:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.50it/s]

trial_002 val e011:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.50it/s]

trial_002 val e011:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.47it/s]

trial_002 val e011:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:08<00:11,  2.46it/s]

trial_002 val e011:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.45it/s]

trial_002 val e011:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.46it/s]

trial_002 val e011:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.47it/s]

trial_002 val e011:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.48it/s]

trial_002 val e011:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:10<00:09,  2.49it/s]

trial_002 val e011:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.50it/s]

trial_002 val e011:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.50it/s]

trial_002 val e011:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:07,  2.51it/s]

trial_002 val e011:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.50it/s]

trial_002 val e011:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:12<00:07,  2.50it/s]

trial_002 val e011:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.46it/s]

trial_002 val e011:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.43it/s]

trial_002 val e011:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.36it/s]

trial_002 val e011:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.34it/s]

trial_002 val e011:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.36it/s]

trial_002 val e011:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:05,  2.40it/s]

trial_002 val e011:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.42it/s]

trial_002 val e011:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.44it/s]

trial_002 val e011:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.45it/s]

trial_002 val e011:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.46it/s]

trial_002 val e011:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.46it/s]

trial_002 val e011:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.46it/s]

trial_002 val e011:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.46it/s]

trial_002 val e011:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.47it/s]

trial_002 val e011:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.48it/s]

trial_002 val e011:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.43it/s]

trial_002 val e011:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.39it/s]

trial_002 val e011: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.39it/s]

[2026-05-28 20:47:51] [trial_002] epoch=011 | train_loss=0.096066 | val_MAE=0.098420 | val_S=0.901580 | best_S=0.901580 @epoch=11 | patience=0/5

[trial_002] epochs:  11%|█████████████▏                                                                                                          | 11/100 [24:14<3:12:53, 130.04s/it]

trial_002 train e012:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e012:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10706, loss=0.10706]

trial_002 train e012:   1%|▋                                                                                              | 1/149 [00:00<01:36,  1.54it/s, avg=0.10706, loss=0.10706]

trial_002 train e012:   1%|▋                                                                                              | 1/149 [00:01<01:36,  1.54it/s, avg=0.10205, loss=0.09704]

trial_002 train e012:   1%|█▎                                                                                             | 2/149 [00:01<01:43,  1.42it/s, avg=0.10205, loss=0.09704]

trial_002 train e012:   1%|█▎                                                                                             | 2/149 [00:02<01:43,  1.42it/s, avg=0.10501, loss=0.11092]

trial_002 train e012:   2%|█▉                                                                                             | 3/149 [00:02<01:44,  1.39it/s, avg=0.10501, loss=0.11092]

trial_002 train e012:   2%|█▉                                                                                             | 3/149 [00:02<01:44,  1.39it/s, avg=0.09975, loss=0.08397]

trial_002 train e012:   3%|██▌                                                                                            | 4/149 [00:02<01:43,  1.40it/s, avg=0.09975, loss=0.08397]

trial_002 train e012:   3%|██▌                                                                                            | 4/149 [00:03<01:43,  1.40it/s, avg=0.09852, loss=0.09360]

trial_002 train e012:   3%|███▏                                                                                           | 5/149 [00:03<01:45,  1.37it/s, avg=0.09852, loss=0.09360]

trial_002 train e012:   3%|███▏                                                                                           | 5/149 [00:04<01:45,  1.37it/s, avg=0.10068, loss=0.11148]

trial_002 train e012:   4%|███▊                                                                                           | 6/149 [00:04<01:44,  1.37it/s, avg=0.10068, loss=0.11148]

trial_002 train e012:   4%|███▊                                                                                           | 6/149 [00:05<01:44,  1.37it/s, avg=0.09934, loss=0.09129]

trial_002 train e012:   5%|████▍                                                                                          | 7/149 [00:05<01:44,  1.36it/s, avg=0.09934, loss=0.09129]

trial_002 train e012:   5%|████▍                                                                                          | 7/149 [00:05<01:44,  1.36it/s, avg=0.09776, loss=0.08672]

trial_002 train e012:   5%|█████                                                                                          | 8/149 [00:05<01:42,  1.38it/s, avg=0.09776, loss=0.08672]

trial_002 train e012:   5%|█████                                                                                          | 8/149 [00:06<01:42,  1.38it/s, avg=0.09913, loss=0.11005]

trial_002 train e012:   6%|█████▋                                                                                         | 9/149 [00:06<01:41,  1.39it/s, avg=0.09913, loss=0.11005]

trial_002 train e012:   6%|█████▋                                                                                         | 9/149 [00:07<01:41,  1.39it/s, avg=0.09832, loss=0.09110]

trial_002 train e012:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.09832, loss=0.09110]

trial_002 train e012:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.09760, loss=0.09034]

trial_002 train e012:   7%|██████▉                                                                                       | 11/149 [00:07<01:42,  1.35it/s, avg=0.09760, loss=0.09034]

trial_002 train e012:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.35it/s, avg=0.09786, loss=0.10075]

trial_002 train e012:   8%|███████▌                                                                                      | 12/149 [00:08<01:41,  1.35it/s, avg=0.09786, loss=0.10075]

trial_002 train e012:   8%|███████▌                                                                                      | 12/149 [00:09<01:41,  1.35it/s, avg=0.09758, loss=0.09421]

trial_002 train e012:   9%|████████▏                                                                                     | 13/149 [00:09<01:41,  1.34it/s, avg=0.09758, loss=0.09421]

trial_002 train e012:   9%|████████▏                                                                                     | 13/149 [00:10<01:41,  1.34it/s, avg=0.09887, loss=0.11570]

trial_002 train e012:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.34it/s, avg=0.09887, loss=0.11570]

trial_002 train e012:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.34it/s, avg=0.09876, loss=0.09720]

trial_002 train e012:  10%|█████████▍                                                                                    | 15/149 [00:10<01:40,  1.34it/s, avg=0.09876, loss=0.09720]

trial_002 train e012:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.34it/s, avg=0.09872, loss=0.09815]

trial_002 train e012:  11%|██████████                                                                                    | 16/149 [00:11<01:39,  1.33it/s, avg=0.09872, loss=0.09815]

trial_002 train e012:  11%|██████████                                                                                    | 16/149 [00:12<01:39,  1.33it/s, avg=0.09823, loss=0.09032]

trial_002 train e012:  11%|██████████▋                                                                                   | 17/149 [00:12<01:39,  1.33it/s, avg=0.09823, loss=0.09032]

trial_002 train e012:  11%|██████████▋                                                                                   | 17/149 [00:13<01:39,  1.33it/s, avg=0.09792, loss=0.09271]

trial_002 train e012:  12%|███████████▎                                                                                  | 18/149 [00:13<01:39,  1.32it/s, avg=0.09792, loss=0.09271]

trial_002 train e012:  12%|███████████▎                                                                                  | 18/149 [00:14<01:39,  1.32it/s, avg=0.09802, loss=0.09985]

trial_002 train e012:  13%|███████████▉                                                                                  | 19/149 [00:14<01:39,  1.31it/s, avg=0.09802, loss=0.09985]

trial_002 train e012:  13%|███████████▉                                                                                  | 19/149 [00:14<01:39,  1.31it/s, avg=0.09714, loss=0.08039]

trial_002 train e012:  13%|████████████▌                                                                                 | 20/149 [00:14<01:37,  1.32it/s, avg=0.09714, loss=0.08039]

trial_002 train e012:  13%|████████████▌                                                                                 | 20/149 [00:15<01:37,  1.32it/s, avg=0.09705, loss=0.09523]

trial_002 train e012:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.32it/s, avg=0.09705, loss=0.09523]

trial_002 train e012:  14%|█████████████▏                                                                                | 21/149 [00:16<01:36,  1.32it/s, avg=0.09761, loss=0.10942]

trial_002 train e012:  15%|█████████████▉                                                                                | 22/149 [00:16<01:35,  1.33it/s, avg=0.09761, loss=0.10942]

trial_002 train e012:  15%|█████████████▉                                                                                | 22/149 [00:17<01:35,  1.33it/s, avg=0.09774, loss=0.10049]

trial_002 train e012:  15%|██████████████▌                                                                               | 23/149 [00:17<01:34,  1.33it/s, avg=0.09774, loss=0.10049]

trial_002 train e012:  15%|██████████████▌                                                                               | 23/149 [00:17<01:34,  1.33it/s, avg=0.09801, loss=0.10431]

trial_002 train e012:  16%|███████████████▏                                                                              | 24/149 [00:17<01:34,  1.33it/s, avg=0.09801, loss=0.10431]

trial_002 train e012:  16%|███████████████▏                                                                              | 24/149 [00:18<01:34,  1.33it/s, avg=0.09772, loss=0.09076]

trial_002 train e012:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.36it/s, avg=0.09772, loss=0.09076]

trial_002 train e012:  17%|███████████████▊                                                                              | 25/149 [00:19<01:31,  1.36it/s, avg=0.09784, loss=0.10086]

trial_002 train e012:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.36it/s, avg=0.09784, loss=0.10086]

trial_002 train e012:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.36it/s, avg=0.09754, loss=0.08966]

trial_002 train e012:  18%|█████████████████                                                                             | 27/149 [00:19<01:29,  1.36it/s, avg=0.09754, loss=0.08966]

trial_002 train e012:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.36it/s, avg=0.09730, loss=0.09071]

trial_002 train e012:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:29,  1.36it/s, avg=0.09730, loss=0.09071]

trial_002 train e012:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:29,  1.36it/s, avg=0.09758, loss=0.10547]

trial_002 train e012:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:28,  1.35it/s, avg=0.09758, loss=0.10547]

trial_002 train e012:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:28,  1.35it/s, avg=0.09741, loss=0.09263]

trial_002 train e012:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:28,  1.35it/s, avg=0.09741, loss=0.09263]

trial_002 train e012:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:28,  1.35it/s, avg=0.09758, loss=0.10268]

trial_002 train e012:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:27,  1.34it/s, avg=0.09758, loss=0.10268]

trial_002 train e012:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.34it/s, avg=0.09734, loss=0.08988]

trial_002 train e012:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:27,  1.34it/s, avg=0.09734, loss=0.08988]

trial_002 train e012:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:27,  1.34it/s, avg=0.09733, loss=0.09701]

trial_002 train e012:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:27,  1.33it/s, avg=0.09733, loss=0.09701]

trial_002 train e012:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:27,  1.33it/s, avg=0.09705, loss=0.08790]

trial_002 train e012:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.09705, loss=0.08790]

trial_002 train e012:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.09705, loss=0.09685]

trial_002 train e012:  23%|██████████████████████                                                                        | 35/149 [00:25<01:22,  1.38it/s, avg=0.09705, loss=0.09685]

trial_002 train e012:  23%|██████████████████████                                                                        | 35/149 [00:26<01:22,  1.38it/s, avg=0.09669, loss=0.08414]

trial_002 train e012:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.40it/s, avg=0.09669, loss=0.08414]

trial_002 train e012:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:20,  1.40it/s, avg=0.09685, loss=0.10256]

trial_002 train e012:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:19,  1.40it/s, avg=0.09685, loss=0.10256]

trial_002 train e012:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:19,  1.40it/s, avg=0.09692, loss=0.09959]

trial_002 train e012:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:19,  1.39it/s, avg=0.09692, loss=0.09959]

trial_002 train e012:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:19,  1.39it/s, avg=0.09673, loss=0.08942]

trial_002 train e012:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:19,  1.38it/s, avg=0.09673, loss=0.08942]

trial_002 train e012:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:19,  1.38it/s, avg=0.09693, loss=0.10462]

trial_002 train e012:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.09693, loss=0.10462]

trial_002 train e012:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:18,  1.39it/s, avg=0.09664, loss=0.08499]

trial_002 train e012:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.40it/s, avg=0.09664, loss=0.08499]

trial_002 train e012:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.40it/s, avg=0.09672, loss=0.10023]

trial_002 train e012:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:18,  1.36it/s, avg=0.09672, loss=0.10023]

trial_002 train e012:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:18,  1.36it/s, avg=0.09676, loss=0.09840]

trial_002 train e012:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:16,  1.38it/s, avg=0.09676, loss=0.09840]

trial_002 train e012:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:16,  1.38it/s, avg=0.09643, loss=0.08236]

trial_002 train e012:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:17,  1.35it/s, avg=0.09643, loss=0.08236]

trial_002 train e012:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:17,  1.35it/s, avg=0.09667, loss=0.10722]

trial_002 train e012:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.37it/s, avg=0.09667, loss=0.10722]

trial_002 train e012:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.37it/s, avg=0.09681, loss=0.10289]

trial_002 train e012:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.39it/s, avg=0.09681, loss=0.10289]

trial_002 train e012:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:14,  1.39it/s, avg=0.09712, loss=0.11162]

trial_002 train e012:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:15,  1.35it/s, avg=0.09712, loss=0.11162]

trial_002 train e012:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:15,  1.35it/s, avg=0.09712, loss=0.09702]

trial_002 train e012:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.36it/s, avg=0.09712, loss=0.09702]

trial_002 train e012:  32%|██████████████████████████████▎                                                               | 48/149 [00:36<01:14,  1.36it/s, avg=0.09694, loss=0.08830]

trial_002 train e012:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:12,  1.38it/s, avg=0.09694, loss=0.08830]

trial_002 train e012:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:12,  1.38it/s, avg=0.09677, loss=0.08843]

trial_002 train e012:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:13,  1.35it/s, avg=0.09677, loss=0.08843]

trial_002 train e012:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:13,  1.35it/s, avg=0.09651, loss=0.08372]

trial_002 train e012:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:14,  1.32it/s, avg=0.09651, loss=0.08372]

trial_002 train e012:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:14,  1.32it/s, avg=0.09649, loss=0.09527]

trial_002 train e012:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:13,  1.32it/s, avg=0.09649, loss=0.09527]

trial_002 train e012:  35%|████████████████████████████████▊                                                             | 52/149 [00:39<01:13,  1.32it/s, avg=0.09660, loss=0.10242]

trial_002 train e012:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.35it/s, avg=0.09660, loss=0.10242]

trial_002 train e012:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.35it/s, avg=0.09676, loss=0.10501]

trial_002 train e012:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:10,  1.34it/s, avg=0.09676, loss=0.10501]

trial_002 train e012:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:10,  1.34it/s, avg=0.09683, loss=0.10079]

trial_002 train e012:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:10,  1.33it/s, avg=0.09683, loss=0.10079]

trial_002 train e012:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:10,  1.33it/s, avg=0.09661, loss=0.08422]

trial_002 train e012:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:09,  1.34it/s, avg=0.09661, loss=0.08422]

trial_002 train e012:  38%|███████████████████████████████████▎                                                          | 56/149 [00:42<01:09,  1.34it/s, avg=0.09660, loss=0.09646]

trial_002 train e012:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.34it/s, avg=0.09660, loss=0.09646]

trial_002 train e012:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.34it/s, avg=0.09665, loss=0.09932]

trial_002 train e012:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:08,  1.34it/s, avg=0.09665, loss=0.09932]

trial_002 train e012:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:08,  1.34it/s, avg=0.09667, loss=0.09753]

trial_002 train e012:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:04,  1.39it/s, avg=0.09667, loss=0.09753]

trial_002 train e012:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:04,  1.39it/s, avg=0.09662, loss=0.09410]

trial_002 train e012:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:04,  1.38it/s, avg=0.09662, loss=0.09410]

trial_002 train e012:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:04,  1.38it/s, avg=0.09648, loss=0.08787]

trial_002 train e012:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:05,  1.34it/s, avg=0.09648, loss=0.08787]

trial_002 train e012:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:05,  1.34it/s, avg=0.09630, loss=0.08545]

trial_002 train e012:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:04,  1.35it/s, avg=0.09630, loss=0.08545]

trial_002 train e012:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.35it/s, avg=0.09638, loss=0.10144]

trial_002 train e012:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:03,  1.35it/s, avg=0.09638, loss=0.10144]

trial_002 train e012:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:03,  1.35it/s, avg=0.09620, loss=0.08446]

trial_002 train e012:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:02,  1.36it/s, avg=0.09620, loss=0.08446]

trial_002 train e012:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:02,  1.36it/s, avg=0.09610, loss=0.08980]

trial_002 train e012:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:02,  1.34it/s, avg=0.09610, loss=0.08980]

trial_002 train e012:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:02,  1.34it/s, avg=0.09593, loss=0.08489]

trial_002 train e012:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:00,  1.37it/s, avg=0.09593, loss=0.08489]

trial_002 train e012:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<01:00,  1.37it/s, avg=0.09605, loss=0.10433]

trial_002 train e012:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.40it/s, avg=0.09605, loss=0.10433]

trial_002 train e012:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:50<00:58,  1.40it/s, avg=0.09588, loss=0.08453]

trial_002 train e012:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:58,  1.38it/s, avg=0.09588, loss=0.08453]

trial_002 train e012:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:58,  1.38it/s, avg=0.09593, loss=0.09934]

trial_002 train e012:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:57,  1.38it/s, avg=0.09593, loss=0.09934]

trial_002 train e012:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:57,  1.38it/s, avg=0.09600, loss=0.10081]

trial_002 train e012:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.38it/s, avg=0.09600, loss=0.10081]

trial_002 train e012:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:57,  1.38it/s, avg=0.09593, loss=0.09091]

trial_002 train e012:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:56,  1.39it/s, avg=0.09593, loss=0.09091]

trial_002 train e012:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:56,  1.39it/s, avg=0.09595, loss=0.09743]

trial_002 train e012:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:54,  1.41it/s, avg=0.09595, loss=0.09743]

trial_002 train e012:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:54,  1.41it/s, avg=0.09582, loss=0.08650]

trial_002 train e012:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:54,  1.41it/s, avg=0.09582, loss=0.08650]

trial_002 train e012:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:54,  1.41it/s, avg=0.09575, loss=0.09028]

trial_002 train e012:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:52,  1.43it/s, avg=0.09575, loss=0.09028]

trial_002 train e012:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:55<00:52,  1.43it/s, avg=0.09582, loss=0.10116]

trial_002 train e012:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:52,  1.40it/s, avg=0.09582, loss=0.10116]

trial_002 train e012:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:52,  1.40it/s, avg=0.09592, loss=0.10324]

trial_002 train e012:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:51,  1.43it/s, avg=0.09592, loss=0.10324]

trial_002 train e012:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:51,  1.43it/s, avg=0.09599, loss=0.10175]

trial_002 train e012:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:51,  1.39it/s, avg=0.09599, loss=0.10175]

trial_002 train e012:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:51,  1.39it/s, avg=0.09603, loss=0.09851]

trial_002 train e012:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.38it/s, avg=0.09603, loss=0.09851]

trial_002 train e012:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.38it/s, avg=0.09609, loss=0.10085]

trial_002 train e012:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:49,  1.40it/s, avg=0.09609, loss=0.10085]

trial_002 train e012:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:49,  1.40it/s, avg=0.09596, loss=0.08583]

trial_002 train e012:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.37it/s, avg=0.09596, loss=0.08583]

trial_002 train e012:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:50,  1.37it/s, avg=0.09572, loss=0.07661]

trial_002 train e012:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.34it/s, avg=0.09572, loss=0.07661]

trial_002 train e012:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:50,  1.34it/s, avg=0.09584, loss=0.10532]

trial_002 train e012:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:50,  1.34it/s, avg=0.09584, loss=0.10532]

trial_002 train e012:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:50,  1.34it/s, avg=0.09582, loss=0.09454]

trial_002 train e012:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:49,  1.32it/s, avg=0.09582, loss=0.09454]

trial_002 train e012:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:49,  1.32it/s, avg=0.09588, loss=0.10098]

trial_002 train e012:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:47,  1.38it/s, avg=0.09588, loss=0.10098]

trial_002 train e012:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:47,  1.38it/s, avg=0.09600, loss=0.10590]

trial_002 train e012:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.37it/s, avg=0.09600, loss=0.10590]

trial_002 train e012:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:46,  1.37it/s, avg=0.09600, loss=0.09596]

trial_002 train e012:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:46,  1.35it/s, avg=0.09600, loss=0.09596]

trial_002 train e012:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:46,  1.35it/s, avg=0.09617, loss=0.11097]

trial_002 train e012:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:46,  1.34it/s, avg=0.09617, loss=0.11097]

trial_002 train e012:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:46,  1.34it/s, avg=0.09620, loss=0.09843]

trial_002 train e012:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:46,  1.32it/s, avg=0.09620, loss=0.09843]

trial_002 train e012:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:46,  1.32it/s, avg=0.09617, loss=0.09382]

trial_002 train e012:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:45,  1.33it/s, avg=0.09617, loss=0.09382]

trial_002 train e012:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:45,  1.33it/s, avg=0.09609, loss=0.08847]

trial_002 train e012:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:44,  1.32it/s, avg=0.09609, loss=0.08847]

trial_002 train e012:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:44,  1.32it/s, avg=0.09605, loss=0.09275]

trial_002 train e012:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:43,  1.35it/s, avg=0.09605, loss=0.09275]

trial_002 train e012:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:43,  1.35it/s, avg=0.09594, loss=0.08560]

trial_002 train e012:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:42,  1.34it/s, avg=0.09594, loss=0.08560]

trial_002 train e012:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:42,  1.34it/s, avg=0.09583, loss=0.08617]

trial_002 train e012:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:41,  1.34it/s, avg=0.09583, loss=0.08617]

trial_002 train e012:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:41,  1.34it/s, avg=0.09581, loss=0.09393]

trial_002 train e012:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:40,  1.35it/s, avg=0.09581, loss=0.09393]

trial_002 train e012:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:40,  1.35it/s, avg=0.09576, loss=0.09108]

trial_002 train e012:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:40,  1.34it/s, avg=0.09576, loss=0.09108]

trial_002 train e012:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:40,  1.34it/s, avg=0.09573, loss=0.09272]

trial_002 train e012:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:39,  1.34it/s, avg=0.09573, loss=0.09272]

trial_002 train e012:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:39,  1.34it/s, avg=0.09576, loss=0.09894]

trial_002 train e012:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.36it/s, avg=0.09576, loss=0.09894]

trial_002 train e012:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.36it/s, avg=0.09573, loss=0.09238]

trial_002 train e012:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:36,  1.38it/s, avg=0.09573, loss=0.09238]

trial_002 train e012:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:36,  1.38it/s, avg=0.09569, loss=0.09243]

trial_002 train e012:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.09569, loss=0.09243]

trial_002 train e012:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.37it/s, avg=0.09567, loss=0.09322]

trial_002 train e012:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.38it/s, avg=0.09567, loss=0.09322]

trial_002 train e012:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:35,  1.38it/s, avg=0.09563, loss=0.09148]

trial_002 train e012:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09563, loss=0.09148]

trial_002 train e012:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09551, loss=0.08326]

trial_002 train e012:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.37it/s, avg=0.09551, loss=0.08326]

trial_002 train e012:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:34,  1.37it/s, avg=0.09549, loss=0.09334]

trial_002 train e012:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.36it/s, avg=0.09549, loss=0.09334]

trial_002 train e012:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:33,  1.36it/s, avg=0.09545, loss=0.09209]

trial_002 train e012:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:32,  1.37it/s, avg=0.09545, loss=0.09209]

trial_002 train e012:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:32,  1.37it/s, avg=0.09542, loss=0.09242]

trial_002 train e012:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.36it/s, avg=0.09542, loss=0.09242]

trial_002 train e012:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.36it/s, avg=0.09539, loss=0.09167]

trial_002 train e012:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.35it/s, avg=0.09539, loss=0.09167]

trial_002 train e012:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:31,  1.35it/s, avg=0.09535, loss=0.09092]

trial_002 train e012:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:31,  1.35it/s, avg=0.09535, loss=0.09092]

trial_002 train e012:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:31,  1.35it/s, avg=0.09542, loss=0.10295]

trial_002 train e012:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.36it/s, avg=0.09542, loss=0.10295]

trial_002 train e012:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:30,  1.36it/s, avg=0.09545, loss=0.09948]

trial_002 train e012:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:29,  1.37it/s, avg=0.09545, loss=0.09948]

trial_002 train e012:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:29,  1.37it/s, avg=0.09548, loss=0.09874]

trial_002 train e012:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.37it/s, avg=0.09548, loss=0.09874]

trial_002 train e012:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:28,  1.37it/s, avg=0.09560, loss=0.10817]

trial_002 train e012:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:27,  1.36it/s, avg=0.09560, loss=0.10817]

trial_002 train e012:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:27,  1.36it/s, avg=0.09567, loss=0.10361]

trial_002 train e012:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:26,  1.38it/s, avg=0.09567, loss=0.10361]

trial_002 train e012:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:26,  1.38it/s, avg=0.09559, loss=0.08690]

trial_002 train e012:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.35it/s, avg=0.09559, loss=0.08690]

trial_002 train e012:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.35it/s, avg=0.09564, loss=0.10107]

trial_002 train e012:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:24,  1.40it/s, avg=0.09564, loss=0.10107]

trial_002 train e012:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:24,  1.40it/s, avg=0.09556, loss=0.08590]

trial_002 train e012:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.37it/s, avg=0.09556, loss=0.08590]

trial_002 train e012:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:25<00:24,  1.37it/s, avg=0.09552, loss=0.09107]

trial_002 train e012:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.37it/s, avg=0.09552, loss=0.09107]

trial_002 train e012:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.37it/s, avg=0.09559, loss=0.10386]

trial_002 train e012:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.35it/s, avg=0.09559, loss=0.10386]

trial_002 train e012:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.35it/s, avg=0.09562, loss=0.09917]

trial_002 train e012:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:23,  1.34it/s, avg=0.09562, loss=0.09917]

trial_002 train e012:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:23,  1.34it/s, avg=0.09559, loss=0.09271]

trial_002 train e012:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.37it/s, avg=0.09559, loss=0.09271]

trial_002 train e012:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:28<00:21,  1.37it/s, avg=0.09555, loss=0.09011]

trial_002 train e012:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.36it/s, avg=0.09555, loss=0.09011]

trial_002 train e012:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.36it/s, avg=0.09552, loss=0.09259]

trial_002 train e012:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:19,  1.42it/s, avg=0.09552, loss=0.09259]

trial_002 train e012:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:19,  1.42it/s, avg=0.09559, loss=0.10377]

trial_002 train e012:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.41it/s, avg=0.09559, loss=0.10377]

trial_002 train e012:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:19,  1.41it/s, avg=0.09556, loss=0.09101]

trial_002 train e012:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:18,  1.39it/s, avg=0.09556, loss=0.09101]

trial_002 train e012:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:31<00:18,  1.39it/s, avg=0.09551, loss=0.08994]

trial_002 train e012:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.37it/s, avg=0.09551, loss=0.08994]

trial_002 train e012:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.37it/s, avg=0.09551, loss=0.09510]

trial_002 train e012:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.38it/s, avg=0.09551, loss=0.09510]

trial_002 train e012:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.38it/s, avg=0.09548, loss=0.09183]

trial_002 train e012:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.39it/s, avg=0.09548, loss=0.09183]

trial_002 train e012:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:16,  1.39it/s, avg=0.09546, loss=0.09311]

trial_002 train e012:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.37it/s, avg=0.09546, loss=0.09311]

trial_002 train e012:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.37it/s, avg=0.09535, loss=0.08098]

trial_002 train e012:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.37it/s, avg=0.09535, loss=0.08098]

trial_002 train e012:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.37it/s, avg=0.09535, loss=0.09645]

trial_002 train e012:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.36it/s, avg=0.09535, loss=0.09645]

trial_002 train e012:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.36it/s, avg=0.09543, loss=0.10561]

trial_002 train e012:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.36it/s, avg=0.09543, loss=0.10561]

trial_002 train e012:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:13,  1.36it/s, avg=0.09536, loss=0.08529]

trial_002 train e012:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.37it/s, avg=0.09536, loss=0.08529]

trial_002 train e012:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.37it/s, avg=0.09532, loss=0.09058]

trial_002 train e012:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.36it/s, avg=0.09532, loss=0.09058]

trial_002 train e012:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.36it/s, avg=0.09539, loss=0.10409]

trial_002 train e012:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.38it/s, avg=0.09539, loss=0.10409]

trial_002 train e012:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:11,  1.38it/s, avg=0.09548, loss=0.10855]

trial_002 train e012:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.37it/s, avg=0.09548, loss=0.10855]

trial_002 train e012:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:39<00:10,  1.37it/s, avg=0.09554, loss=0.10374]

trial_002 train e012:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.35it/s, avg=0.09554, loss=0.10374]

trial_002 train e012:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.35it/s, avg=0.09543, loss=0.07940]

trial_002 train e012:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.37it/s, avg=0.09543, loss=0.07940]

trial_002 train e012:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.37it/s, avg=0.09543, loss=0.09658]

trial_002 train e012:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.37it/s, avg=0.09543, loss=0.09658]

trial_002 train e012:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:41<00:08,  1.37it/s, avg=0.09534, loss=0.08227]

trial_002 train e012:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:07,  1.38it/s, avg=0.09534, loss=0.08227]

trial_002 train e012:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:07,  1.38it/s, avg=0.09532, loss=0.09298]

trial_002 train e012:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.39it/s, avg=0.09532, loss=0.09298]

trial_002 train e012:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.39it/s, avg=0.09515, loss=0.07149]

trial_002 train e012:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.37it/s, avg=0.09515, loss=0.07149]

trial_002 train e012:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.37it/s, avg=0.09518, loss=0.09915]

trial_002 train e012:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.37it/s, avg=0.09518, loss=0.09915]

trial_002 train e012:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:44<00:05,  1.37it/s, avg=0.09521, loss=0.09967]

trial_002 train e012:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.40it/s, avg=0.09521, loss=0.09967]

trial_002 train e012:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.40it/s, avg=0.09528, loss=0.10467]

trial_002 train e012:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.37it/s, avg=0.09528, loss=0.10467]

trial_002 train e012:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.37it/s, avg=0.09518, loss=0.08102]

trial_002 train e012:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.34it/s, avg=0.09518, loss=0.08102]

trial_002 train e012:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:46<00:03,  1.34it/s, avg=0.09517, loss=0.09404]

trial_002 train e012:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.35it/s, avg=0.09517, loss=0.09404]

trial_002 train e012:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:47<00:02,  1.35it/s, avg=0.09527, loss=0.11018]

trial_002 train e012:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.32it/s, avg=0.09527, loss=0.11018]

trial_002 train e012:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.32it/s, avg=0.09530, loss=0.09946]

trial_002 train e012:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.33it/s, avg=0.09530, loss=0.09946]

trial_002 train e012:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.33it/s, avg=0.09524, loss=0.08635]

trial_002 train e012:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.34it/s, avg=0.09524, loss=0.08635]

trial_002 train e012:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.34it/s, avg=0.09522, loss=0.08866]

trial_002 train e012: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.65it/s, avg=0.09522, loss=0.08866]

trial_002 val e012:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e012:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.34it/s]

trial_002 val e012:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.38it/s]

trial_002 val e012:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.36it/s]

trial_002 val e012:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.39it/s]

trial_002 val e012:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.40it/s]

trial_002 val e012:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.42it/s]

trial_002 val e012:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.42it/s]

trial_002 val e012:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.37it/s]

trial_002 val e012:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.37it/s]

trial_002 val e012:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.39it/s]

trial_002 val e012:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.41it/s]

trial_002 val e012:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.43it/s]

trial_002 val e012:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.44it/s]

trial_002 val e012:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.45it/s]

trial_002 val e012:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.45it/s]

trial_002 val e012:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.42it/s]

trial_002 val e012:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.42it/s]

trial_002 val e012:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.42it/s]

trial_002 val e012:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.42it/s]

trial_002 val e012:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.41it/s]

trial_002 val e012:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.40it/s]

trial_002 val e012:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:12,  2.33it/s]

trial_002 val e012:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.34it/s]

trial_002 val e012:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:10,  2.37it/s]

trial_002 val e012:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.35it/s]

trial_002 val e012:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.35it/s]

trial_002 val e012:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.38it/s]

trial_002 val e012:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.40it/s]

trial_002 val e012:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:08,  2.40it/s]

trial_002 val e012:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.42it/s]

trial_002 val e012:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.41it/s]

trial_002 val e012:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.39it/s]

trial_002 val e012:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.38it/s]

trial_002 val e012:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.38it/s]

trial_002 val e012:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.41it/s]

trial_002 val e012:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:05,  2.42it/s]

trial_002 val e012:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.45it/s]

trial_002 val e012:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.48it/s]

trial_002 val e012:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.50it/s]

trial_002 val e012:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:03,  2.51it/s]

trial_002 val e012:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.52it/s]

trial_002 val e012:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.53it/s]

trial_002 val e012:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.53it/s]

trial_002 val e012:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.53it/s]

trial_002 val e012:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.50it/s]

trial_002 val e012:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.48it/s]

trial_002 val e012:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.48it/s]

trial_002 val e012:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.46it/s]

trial_002 val e012:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.44it/s]

trial_002 val e012: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.43it/s]

[2026-05-28 20:50:01] [trial_002] epoch=012 | train_loss=0.095224 | val_MAE=0.098906 | val_S=0.901094 | best_S=0.901580 @epoch=11 | patience=1/5

[trial_002] epochs:  12%|██████████████▍                                                                                                         | 12/100 [26:24<3:10:36, 129.95s/it]

trial_002 train e013:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e013:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09426, loss=0.09426]

trial_002 train e013:   1%|▋                                                                                              | 1/149 [00:00<01:42,  1.44it/s, avg=0.09426, loss=0.09426]

trial_002 train e013:   1%|▋                                                                                              | 1/149 [00:01<01:42,  1.44it/s, avg=0.09189, loss=0.08952]

trial_002 train e013:   1%|█▎                                                                                             | 2/149 [00:01<01:48,  1.36it/s, avg=0.09189, loss=0.08952]

trial_002 train e013:   1%|█▎                                                                                             | 2/149 [00:02<01:48,  1.36it/s, avg=0.09265, loss=0.09418]

trial_002 train e013:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.09265, loss=0.09418]

trial_002 train e013:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.09343, loss=0.09576]

trial_002 train e013:   3%|██▌                                                                                            | 4/149 [00:02<01:48,  1.34it/s, avg=0.09343, loss=0.09576]

trial_002 train e013:   3%|██▌                                                                                            | 4/149 [00:03<01:48,  1.34it/s, avg=0.09423, loss=0.09744]

trial_002 train e013:   3%|███▏                                                                                           | 5/149 [00:03<01:42,  1.40it/s, avg=0.09423, loss=0.09744]

trial_002 train e013:   3%|███▏                                                                                           | 5/149 [00:04<01:42,  1.40it/s, avg=0.09636, loss=0.10698]

trial_002 train e013:   4%|███▊                                                                                           | 6/149 [00:04<01:41,  1.41it/s, avg=0.09636, loss=0.10698]

trial_002 train e013:   4%|███▊                                                                                           | 6/149 [00:05<01:41,  1.41it/s, avg=0.09475, loss=0.08508]

trial_002 train e013:   5%|████▍                                                                                          | 7/149 [00:05<01:39,  1.43it/s, avg=0.09475, loss=0.08508]

trial_002 train e013:   5%|████▍                                                                                          | 7/149 [00:05<01:39,  1.43it/s, avg=0.09595, loss=0.10439]

trial_002 train e013:   5%|█████                                                                                          | 8/149 [00:05<01:41,  1.38it/s, avg=0.09595, loss=0.10439]

trial_002 train e013:   5%|█████                                                                                          | 8/149 [00:06<01:41,  1.38it/s, avg=0.09422, loss=0.08034]

trial_002 train e013:   6%|█████▋                                                                                         | 9/149 [00:06<01:42,  1.37it/s, avg=0.09422, loss=0.08034]

trial_002 train e013:   6%|█████▋                                                                                         | 9/149 [00:07<01:42,  1.37it/s, avg=0.09420, loss=0.09402]

trial_002 train e013:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.36it/s, avg=0.09420, loss=0.09402]

trial_002 train e013:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.36it/s, avg=0.09438, loss=0.09625]

trial_002 train e013:   7%|██████▉                                                                                       | 11/149 [00:07<01:40,  1.37it/s, avg=0.09438, loss=0.09625]

trial_002 train e013:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.37it/s, avg=0.09478, loss=0.09911]

trial_002 train e013:   8%|███████▌                                                                                      | 12/149 [00:08<01:38,  1.40it/s, avg=0.09478, loss=0.09911]

trial_002 train e013:   8%|███████▌                                                                                      | 12/149 [00:09<01:38,  1.40it/s, avg=0.09632, loss=0.11489]

trial_002 train e013:   9%|████████▏                                                                                     | 13/149 [00:09<01:36,  1.41it/s, avg=0.09632, loss=0.11489]

trial_002 train e013:   9%|████████▏                                                                                     | 13/149 [00:10<01:36,  1.41it/s, avg=0.09621, loss=0.09471]

trial_002 train e013:   9%|████████▊                                                                                     | 14/149 [00:10<01:39,  1.35it/s, avg=0.09621, loss=0.09471]

trial_002 train e013:   9%|████████▊                                                                                     | 14/149 [00:10<01:39,  1.35it/s, avg=0.09575, loss=0.08927]

trial_002 train e013:  10%|█████████▍                                                                                    | 15/149 [00:10<01:39,  1.35it/s, avg=0.09575, loss=0.08927]

trial_002 train e013:  10%|█████████▍                                                                                    | 15/149 [00:11<01:39,  1.35it/s, avg=0.09509, loss=0.08532]

trial_002 train e013:  11%|██████████                                                                                    | 16/149 [00:11<01:39,  1.34it/s, avg=0.09509, loss=0.08532]

trial_002 train e013:  11%|██████████                                                                                    | 16/149 [00:12<01:39,  1.34it/s, avg=0.09454, loss=0.08572]

trial_002 train e013:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.34it/s, avg=0.09454, loss=0.08572]

trial_002 train e013:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.34it/s, avg=0.09562, loss=0.11398]

trial_002 train e013:  12%|███████████▎                                                                                  | 18/149 [00:13<01:31,  1.43it/s, avg=0.09562, loss=0.11398]

trial_002 train e013:  12%|███████████▎                                                                                  | 18/149 [00:13<01:31,  1.43it/s, avg=0.09521, loss=0.08771]

trial_002 train e013:  13%|███████████▉                                                                                  | 19/149 [00:13<01:31,  1.43it/s, avg=0.09521, loss=0.08771]

trial_002 train e013:  13%|███████████▉                                                                                  | 19/149 [00:14<01:31,  1.43it/s, avg=0.09546, loss=0.10030]

trial_002 train e013:  13%|████████████▌                                                                                 | 20/149 [00:14<01:32,  1.40it/s, avg=0.09546, loss=0.10030]

trial_002 train e013:  13%|████████████▌                                                                                 | 20/149 [00:15<01:32,  1.40it/s, avg=0.09513, loss=0.08857]

trial_002 train e013:  14%|█████████████▏                                                                                | 21/149 [00:15<01:31,  1.40it/s, avg=0.09513, loss=0.08857]

trial_002 train e013:  14%|█████████████▏                                                                                | 21/149 [00:15<01:31,  1.40it/s, avg=0.09578, loss=0.10926]

trial_002 train e013:  15%|█████████████▉                                                                                | 22/149 [00:15<01:30,  1.40it/s, avg=0.09578, loss=0.10926]

trial_002 train e013:  15%|█████████████▉                                                                                | 22/149 [00:16<01:30,  1.40it/s, avg=0.09524, loss=0.08356]

trial_002 train e013:  15%|██████████████▌                                                                               | 23/149 [00:16<01:31,  1.38it/s, avg=0.09524, loss=0.08356]

trial_002 train e013:  15%|██████████████▌                                                                               | 23/149 [00:17<01:31,  1.38it/s, avg=0.09456, loss=0.07882]

trial_002 train e013:  16%|███████████████▏                                                                              | 24/149 [00:17<01:30,  1.37it/s, avg=0.09456, loss=0.07882]

trial_002 train e013:  16%|███████████████▏                                                                              | 24/149 [00:18<01:30,  1.37it/s, avg=0.09485, loss=0.10187]

trial_002 train e013:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.09485, loss=0.10187]

trial_002 train e013:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.09485, loss=0.09467]

trial_002 train e013:  17%|████████████████▍                                                                             | 26/149 [00:18<01:29,  1.37it/s, avg=0.09485, loss=0.09467]

trial_002 train e013:  17%|████████████████▍                                                                             | 26/149 [00:19<01:29,  1.37it/s, avg=0.09490, loss=0.09638]

trial_002 train e013:  18%|█████████████████                                                                             | 27/149 [00:19<01:29,  1.36it/s, avg=0.09490, loss=0.09638]

trial_002 train e013:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.36it/s, avg=0.09508, loss=0.09996]

trial_002 train e013:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.36it/s, avg=0.09508, loss=0.09996]

trial_002 train e013:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:28,  1.36it/s, avg=0.09482, loss=0.08750]

trial_002 train e013:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.09482, loss=0.08750]

trial_002 train e013:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.09459, loss=0.08801]

trial_002 train e013:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:27,  1.35it/s, avg=0.09459, loss=0.08801]

trial_002 train e013:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.35it/s, avg=0.09462, loss=0.09549]

trial_002 train e013:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:26,  1.36it/s, avg=0.09462, loss=0.09549]

trial_002 train e013:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.36it/s, avg=0.09448, loss=0.08991]

trial_002 train e013:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.38it/s, avg=0.09448, loss=0.08991]

trial_002 train e013:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.38it/s, avg=0.09467, loss=0.10090]

trial_002 train e013:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:24,  1.37it/s, avg=0.09467, loss=0.10090]

trial_002 train e013:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.09446, loss=0.08742]

trial_002 train e013:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.09446, loss=0.08742]

trial_002 train e013:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.09393, loss=0.07612]

trial_002 train e013:  23%|██████████████████████                                                                        | 35/149 [00:25<01:22,  1.39it/s, avg=0.09393, loss=0.07612]

trial_002 train e013:  23%|██████████████████████                                                                        | 35/149 [00:26<01:22,  1.39it/s, avg=0.09373, loss=0.08659]

trial_002 train e013:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.40it/s, avg=0.09373, loss=0.08659]

trial_002 train e013:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.40it/s, avg=0.09366, loss=0.09123]

trial_002 train e013:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:21,  1.37it/s, avg=0.09366, loss=0.09123]

trial_002 train e013:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:21,  1.37it/s, avg=0.09398, loss=0.10591]

trial_002 train e013:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:21,  1.35it/s, avg=0.09398, loss=0.10591]

trial_002 train e013:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:21,  1.35it/s, avg=0.09448, loss=0.11321]

trial_002 train e013:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:20,  1.37it/s, avg=0.09448, loss=0.11321]

trial_002 train e013:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:20,  1.37it/s, avg=0.09461, loss=0.09975]

trial_002 train e013:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.09461, loss=0.09975]

trial_002 train e013:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.09465, loss=0.09630]

trial_002 train e013:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:18,  1.38it/s, avg=0.09465, loss=0.09630]

trial_002 train e013:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:18,  1.38it/s, avg=0.09464, loss=0.09408]

trial_002 train e013:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.09464, loss=0.09408]

trial_002 train e013:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:17,  1.38it/s, avg=0.09455, loss=0.09104]

trial_002 train e013:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:18,  1.35it/s, avg=0.09455, loss=0.09104]

trial_002 train e013:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:18,  1.35it/s, avg=0.09427, loss=0.08190]

trial_002 train e013:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.35it/s, avg=0.09427, loss=0.08190]

trial_002 train e013:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.35it/s, avg=0.09420, loss=0.09153]

trial_002 train e013:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:17,  1.35it/s, avg=0.09420, loss=0.09153]

trial_002 train e013:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:17,  1.35it/s, avg=0.09414, loss=0.09110]

trial_002 train e013:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:16,  1.35it/s, avg=0.09414, loss=0.09110]

trial_002 train e013:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:16,  1.35it/s, avg=0.09392, loss=0.08386]

trial_002 train e013:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:15,  1.35it/s, avg=0.09392, loss=0.08386]

trial_002 train e013:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:15,  1.35it/s, avg=0.09385, loss=0.09085]

trial_002 train e013:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:15,  1.35it/s, avg=0.09385, loss=0.09085]

trial_002 train e013:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:15,  1.35it/s, avg=0.09403, loss=0.10251]

trial_002 train e013:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:14,  1.34it/s, avg=0.09403, loss=0.10251]

trial_002 train e013:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:14,  1.34it/s, avg=0.09393, loss=0.08888]

trial_002 train e013:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:12,  1.36it/s, avg=0.09393, loss=0.08888]

trial_002 train e013:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:12,  1.36it/s, avg=0.09406, loss=0.10047]

trial_002 train e013:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:13,  1.34it/s, avg=0.09406, loss=0.10047]

trial_002 train e013:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:13,  1.34it/s, avg=0.09432, loss=0.10774]

trial_002 train e013:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:11,  1.36it/s, avg=0.09432, loss=0.10774]

trial_002 train e013:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:11,  1.36it/s, avg=0.09461, loss=0.10995]

trial_002 train e013:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:09,  1.38it/s, avg=0.09461, loss=0.10995]

trial_002 train e013:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:09,  1.38it/s, avg=0.09491, loss=0.11050]

trial_002 train e013:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.38it/s, avg=0.09491, loss=0.11050]

trial_002 train e013:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:09,  1.38it/s, avg=0.09493, loss=0.09620]

trial_002 train e013:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.09493, loss=0.09620]

trial_002 train e013:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.09519, loss=0.10949]

trial_002 train e013:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:07,  1.37it/s, avg=0.09519, loss=0.10949]

trial_002 train e013:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.37it/s, avg=0.09503, loss=0.08603]

trial_002 train e013:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:09,  1.33it/s, avg=0.09503, loss=0.08603]

trial_002 train e013:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:09,  1.33it/s, avg=0.09486, loss=0.08527]

trial_002 train e013:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:07,  1.36it/s, avg=0.09486, loss=0.08527]

trial_002 train e013:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:07,  1.36it/s, avg=0.09476, loss=0.08873]

trial_002 train e013:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09476, loss=0.08873]

trial_002 train e013:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09482, loss=0.09870]

trial_002 train e013:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:04,  1.37it/s, avg=0.09482, loss=0.09870]

trial_002 train e013:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:04,  1.37it/s, avg=0.09488, loss=0.09842]

trial_002 train e013:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.37it/s, avg=0.09488, loss=0.09842]

trial_002 train e013:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:04,  1.37it/s, avg=0.09485, loss=0.09286]

trial_002 train e013:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:03,  1.37it/s, avg=0.09485, loss=0.09286]

trial_002 train e013:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:03,  1.37it/s, avg=0.09483, loss=0.09324]

trial_002 train e013:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:02,  1.37it/s, avg=0.09483, loss=0.09324]

trial_002 train e013:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.37it/s, avg=0.09499, loss=0.10559]

trial_002 train e013:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.38it/s, avg=0.09499, loss=0.10559]

trial_002 train e013:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:01,  1.38it/s, avg=0.09513, loss=0.10404]

trial_002 train e013:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.39it/s, avg=0.09513, loss=0.10404]

trial_002 train e013:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:00,  1.39it/s, avg=0.09514, loss=0.09557]

trial_002 train e013:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:58,  1.41it/s, avg=0.09514, loss=0.09557]

trial_002 train e013:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:58,  1.41it/s, avg=0.09496, loss=0.08317]

trial_002 train e013:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:56,  1.44it/s, avg=0.09496, loss=0.08317]

trial_002 train e013:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:56,  1.44it/s, avg=0.09490, loss=0.09088]

trial_002 train e013:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:54,  1.48it/s, avg=0.09490, loss=0.09088]

trial_002 train e013:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:54,  1.48it/s, avg=0.09467, loss=0.07922]

trial_002 train e013:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:54,  1.47it/s, avg=0.09467, loss=0.07922]

trial_002 train e013:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:54,  1.47it/s, avg=0.09476, loss=0.10077]

trial_002 train e013:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:52,  1.50it/s, avg=0.09476, loss=0.10077]

trial_002 train e013:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:52,  1.50it/s, avg=0.09455, loss=0.07976]

trial_002 train e013:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:51,  1.50it/s, avg=0.09455, loss=0.07976]

trial_002 train e013:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:51,  1.50it/s, avg=0.09453, loss=0.09332]

trial_002 train e013:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:51,  1.51it/s, avg=0.09453, loss=0.09332]

trial_002 train e013:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:51,  1.51it/s, avg=0.09451, loss=0.09295]

trial_002 train e013:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:50,  1.50it/s, avg=0.09451, loss=0.09295]

trial_002 train e013:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:50,  1.50it/s, avg=0.09473, loss=0.11078]

trial_002 train e013:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:49,  1.51it/s, avg=0.09473, loss=0.11078]

trial_002 train e013:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:49,  1.51it/s, avg=0.09461, loss=0.08585]

trial_002 train e013:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:48,  1.52it/s, avg=0.09461, loss=0.08585]

trial_002 train e013:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:48,  1.52it/s, avg=0.09471, loss=0.10206]

trial_002 train e013:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:47,  1.54it/s, avg=0.09471, loss=0.10206]

trial_002 train e013:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:47,  1.54it/s, avg=0.09494, loss=0.11235]

trial_002 train e013:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:47,  1.52it/s, avg=0.09494, loss=0.11235]

trial_002 train e013:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:47,  1.52it/s, avg=0.09488, loss=0.09072]

trial_002 train e013:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:47,  1.50it/s, avg=0.09488, loss=0.09072]

trial_002 train e013:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:47,  1.50it/s, avg=0.09503, loss=0.10656]

trial_002 train e013:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:46,  1.50it/s, avg=0.09503, loss=0.10656]

trial_002 train e013:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:46,  1.50it/s, avg=0.09503, loss=0.09507]

trial_002 train e013:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:45,  1.52it/s, avg=0.09503, loss=0.09507]

trial_002 train e013:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:45,  1.52it/s, avg=0.09507, loss=0.09814]

trial_002 train e013:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:44,  1.52it/s, avg=0.09507, loss=0.09814]

trial_002 train e013:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:44,  1.52it/s, avg=0.09530, loss=0.11369]

trial_002 train e013:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:44,  1.50it/s, avg=0.09530, loss=0.11369]

trial_002 train e013:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:44,  1.50it/s, avg=0.09521, loss=0.08759]

trial_002 train e013:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:43,  1.52it/s, avg=0.09521, loss=0.08759]

trial_002 train e013:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:43,  1.52it/s, avg=0.09526, loss=0.09987]

trial_002 train e013:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:59<00:42,  1.54it/s, avg=0.09526, loss=0.09987]

trial_002 train e013:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:42,  1.54it/s, avg=0.09501, loss=0.07421]

trial_002 train e013:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:42,  1.52it/s, avg=0.09501, loss=0.07421]

trial_002 train e013:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:42,  1.52it/s, avg=0.09484, loss=0.07996]

trial_002 train e013:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:41,  1.52it/s, avg=0.09484, loss=0.07996]

trial_002 train e013:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:41,  1.52it/s, avg=0.09479, loss=0.09070]

trial_002 train e013:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:01<00:40,  1.53it/s, avg=0.09479, loss=0.09070]

trial_002 train e013:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:40,  1.53it/s, avg=0.09481, loss=0.09659]

trial_002 train e013:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:40,  1.52it/s, avg=0.09481, loss=0.09659]

trial_002 train e013:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:40,  1.52it/s, avg=0.09480, loss=0.09410]

trial_002 train e013:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:39,  1.50it/s, avg=0.09480, loss=0.09410]

trial_002 train e013:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:39,  1.50it/s, avg=0.09464, loss=0.07987]

trial_002 train e013:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:03<00:39,  1.50it/s, avg=0.09464, loss=0.07987]

trial_002 train e013:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:39,  1.50it/s, avg=0.09469, loss=0.09914]

trial_002 train e013:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:04<00:38,  1.52it/s, avg=0.09469, loss=0.09914]

trial_002 train e013:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:38,  1.52it/s, avg=0.09462, loss=0.08873]

trial_002 train e013:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:37,  1.50it/s, avg=0.09462, loss=0.08873]

trial_002 train e013:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:37,  1.50it/s, avg=0.09462, loss=0.09438]

trial_002 train e013:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:05<00:38,  1.47it/s, avg=0.09462, loss=0.09438]

trial_002 train e013:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:38,  1.47it/s, avg=0.09479, loss=0.11101]

trial_002 train e013:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:06<00:37,  1.46it/s, avg=0.09479, loss=0.11101]

trial_002 train e013:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:37,  1.46it/s, avg=0.09478, loss=0.09345]

trial_002 train e013:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:35,  1.50it/s, avg=0.09478, loss=0.09345]

trial_002 train e013:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:35,  1.50it/s, avg=0.09477, loss=0.09365]

trial_002 train e013:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:07<00:34,  1.53it/s, avg=0.09477, loss=0.09365]

trial_002 train e013:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:34,  1.53it/s, avg=0.09470, loss=0.08860]

trial_002 train e013:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:08<00:33,  1.54it/s, avg=0.09470, loss=0.08860]

trial_002 train e013:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:33,  1.54it/s, avg=0.09477, loss=0.10066]

trial_002 train e013:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:09<00:33,  1.54it/s, avg=0.09477, loss=0.10066]

trial_002 train e013:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:09<00:33,  1.54it/s, avg=0.09468, loss=0.08658]

trial_002 train e013:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:09<00:32,  1.52it/s, avg=0.09468, loss=0.08658]

trial_002 train e013:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:32,  1.52it/s, avg=0.09467, loss=0.09377]

trial_002 train e013:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:10<00:32,  1.51it/s, avg=0.09467, loss=0.09377]

trial_002 train e013:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:32,  1.51it/s, avg=0.09467, loss=0.09451]

trial_002 train e013:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:11<00:32,  1.48it/s, avg=0.09467, loss=0.09451]

trial_002 train e013:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:11<00:32,  1.48it/s, avg=0.09450, loss=0.07728]

trial_002 train e013:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:11<00:31,  1.49it/s, avg=0.09450, loss=0.07728]

trial_002 train e013:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:31,  1.49it/s, avg=0.09462, loss=0.10681]

trial_002 train e013:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:12<00:31,  1.48it/s, avg=0.09462, loss=0.10681]

trial_002 train e013:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:31,  1.48it/s, avg=0.09458, loss=0.08989]

trial_002 train e013:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:13<00:30,  1.48it/s, avg=0.09458, loss=0.08989]

trial_002 train e013:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:13<00:30,  1.48it/s, avg=0.09460, loss=0.09727]

trial_002 train e013:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:13<00:30,  1.46it/s, avg=0.09460, loss=0.09727]

trial_002 train e013:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:14<00:30,  1.46it/s, avg=0.09454, loss=0.08776]

trial_002 train e013:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:14<00:29,  1.46it/s, avg=0.09454, loss=0.08776]

trial_002 train e013:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:29,  1.46it/s, avg=0.09464, loss=0.10571]

trial_002 train e013:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:15<00:28,  1.47it/s, avg=0.09464, loss=0.10571]

trial_002 train e013:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:15<00:28,  1.47it/s, avg=0.09459, loss=0.08938]

trial_002 train e013:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:15<00:27,  1.49it/s, avg=0.09459, loss=0.08938]

trial_002 train e013:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:16<00:27,  1.49it/s, avg=0.09469, loss=0.10537]

trial_002 train e013:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:16<00:27,  1.45it/s, avg=0.09469, loss=0.10537]

trial_002 train e013:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:17<00:27,  1.45it/s, avg=0.09468, loss=0.09334]

trial_002 train e013:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:17<00:25,  1.52it/s, avg=0.09468, loss=0.09334]

trial_002 train e013:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:17<00:25,  1.52it/s, avg=0.09470, loss=0.09718]

trial_002 train e013:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:17<00:25,  1.50it/s, avg=0.09470, loss=0.09718]

trial_002 train e013:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:18<00:25,  1.50it/s, avg=0.09487, loss=0.11343]

trial_002 train e013:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:18<00:23,  1.54it/s, avg=0.09487, loss=0.11343]

trial_002 train e013:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:19<00:23,  1.54it/s, avg=0.09490, loss=0.09816]

trial_002 train e013:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:19<00:23,  1.55it/s, avg=0.09490, loss=0.09816]

trial_002 train e013:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:19<00:23,  1.55it/s, avg=0.09513, loss=0.12184]

trial_002 train e013:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:19<00:22,  1.54it/s, avg=0.09513, loss=0.12184]

trial_002 train e013:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:20<00:22,  1.54it/s, avg=0.09503, loss=0.08375]

trial_002 train e013:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:20<00:22,  1.50it/s, avg=0.09503, loss=0.08375]

trial_002 train e013:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:21<00:22,  1.50it/s, avg=0.09501, loss=0.09264]

trial_002 train e013:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:21<00:22,  1.47it/s, avg=0.09501, loss=0.09264]

trial_002 train e013:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:21<00:22,  1.47it/s, avg=0.09495, loss=0.08712]

trial_002 train e013:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:21<00:22,  1.45it/s, avg=0.09495, loss=0.08712]

trial_002 train e013:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:22<00:22,  1.45it/s, avg=0.09489, loss=0.08816]

trial_002 train e013:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:22<00:20,  1.50it/s, avg=0.09489, loss=0.08816]

trial_002 train e013:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:23<00:20,  1.50it/s, avg=0.09488, loss=0.09383]

trial_002 train e013:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:23<00:20,  1.49it/s, avg=0.09488, loss=0.09383]

trial_002 train e013:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:23<00:20,  1.49it/s, avg=0.09488, loss=0.09451]

trial_002 train e013:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:23<00:19,  1.48it/s, avg=0.09488, loss=0.09451]

trial_002 train e013:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:24<00:19,  1.48it/s, avg=0.09499, loss=0.10807]

trial_002 train e013:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:24<00:18,  1.51it/s, avg=0.09499, loss=0.10807]

trial_002 train e013:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:25<00:18,  1.51it/s, avg=0.09487, loss=0.08115]

trial_002 train e013:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:25<00:17,  1.51it/s, avg=0.09487, loss=0.08115]

trial_002 train e013:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:25<00:17,  1.51it/s, avg=0.09493, loss=0.10136]

trial_002 train e013:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:25<00:16,  1.53it/s, avg=0.09493, loss=0.10136]

trial_002 train e013:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:26<00:16,  1.53it/s, avg=0.09486, loss=0.08627]

trial_002 train e013:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:26<00:16,  1.51it/s, avg=0.09486, loss=0.08627]

trial_002 train e013:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:27<00:16,  1.51it/s, avg=0.09476, loss=0.08241]

trial_002 train e013:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:27<00:16,  1.49it/s, avg=0.09476, loss=0.08241]

trial_002 train e013:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:28<00:16,  1.49it/s, avg=0.09475, loss=0.09432]

trial_002 train e013:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:28<00:15,  1.44it/s, avg=0.09475, loss=0.09432]

trial_002 train e013:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:28<00:15,  1.44it/s, avg=0.09464, loss=0.08007]

trial_002 train e013:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:28<00:15,  1.44it/s, avg=0.09464, loss=0.08007]

trial_002 train e013:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:29<00:15,  1.44it/s, avg=0.09463, loss=0.09364]

trial_002 train e013:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:29<00:14,  1.41it/s, avg=0.09463, loss=0.09364]

trial_002 train e013:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:30<00:14,  1.41it/s, avg=0.09464, loss=0.09573]

trial_002 train e013:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:30<00:14,  1.40it/s, avg=0.09464, loss=0.09573]

trial_002 train e013:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:30<00:14,  1.40it/s, avg=0.09466, loss=0.09703]

trial_002 train e013:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:30<00:13,  1.38it/s, avg=0.09466, loss=0.09703]

trial_002 train e013:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:31<00:13,  1.38it/s, avg=0.09474, loss=0.10601]

trial_002 train e013:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:31<00:12,  1.42it/s, avg=0.09474, loss=0.10601]

trial_002 train e013:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:32<00:12,  1.42it/s, avg=0.09488, loss=0.11279]

trial_002 train e013:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:32<00:12,  1.39it/s, avg=0.09488, loss=0.11279]

trial_002 train e013:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:33<00:12,  1.39it/s, avg=0.09485, loss=0.09048]

trial_002 train e013:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:33<00:11,  1.37it/s, avg=0.09485, loss=0.09048]

trial_002 train e013:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:33<00:11,  1.37it/s, avg=0.09493, loss=0.10561]

trial_002 train e013:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:33<00:11,  1.36it/s, avg=0.09493, loss=0.10561]

trial_002 train e013:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:34<00:11,  1.36it/s, avg=0.09489, loss=0.09042]

trial_002 train e013:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:34<00:10,  1.35it/s, avg=0.09489, loss=0.09042]

trial_002 train e013:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:35<00:10,  1.35it/s, avg=0.09492, loss=0.09864]

trial_002 train e013:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:35<00:09,  1.37it/s, avg=0.09492, loss=0.09864]

trial_002 train e013:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:35<00:09,  1.37it/s, avg=0.09488, loss=0.08905]

trial_002 train e013:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:35<00:08,  1.39it/s, avg=0.09488, loss=0.08905]

trial_002 train e013:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:36<00:08,  1.39it/s, avg=0.09490, loss=0.09739]

trial_002 train e013:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:36<00:08,  1.36it/s, avg=0.09490, loss=0.09739]

trial_002 train e013:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:37<00:08,  1.36it/s, avg=0.09487, loss=0.09143]

trial_002 train e013:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:37<00:07,  1.33it/s, avg=0.09487, loss=0.09143]

trial_002 train e013:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:38<00:07,  1.33it/s, avg=0.09492, loss=0.10210]

trial_002 train e013:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:38<00:06,  1.33it/s, avg=0.09492, loss=0.10210]

trial_002 train e013:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:39<00:06,  1.33it/s, avg=0.09503, loss=0.10970]

trial_002 train e013:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:39<00:06,  1.32it/s, avg=0.09503, loss=0.10970]

trial_002 train e013:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:39<00:06,  1.32it/s, avg=0.09502, loss=0.09421]

trial_002 train e013:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:39<00:05,  1.35it/s, avg=0.09502, loss=0.09421]

trial_002 train e013:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:40<00:05,  1.35it/s, avg=0.09497, loss=0.08828]

trial_002 train e013:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:40<00:04,  1.36it/s, avg=0.09497, loss=0.08828]

trial_002 train e013:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:41<00:04,  1.36it/s, avg=0.09490, loss=0.08414]

trial_002 train e013:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:41<00:03,  1.34it/s, avg=0.09490, loss=0.08414]

trial_002 train e013:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:41<00:03,  1.34it/s, avg=0.09484, loss=0.08655]

trial_002 train e013:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:41<00:02,  1.36it/s, avg=0.09484, loss=0.08655]

trial_002 train e013:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:42<00:02,  1.36it/s, avg=0.09491, loss=0.10481]

trial_002 train e013:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:42<00:02,  1.36it/s, avg=0.09491, loss=0.10481]

trial_002 train e013:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:43<00:02,  1.36it/s, avg=0.09490, loss=0.09284]

trial_002 train e013:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:43<00:01,  1.39it/s, avg=0.09490, loss=0.09284]

trial_002 train e013:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:44<00:01,  1.39it/s, avg=0.09491, loss=0.09657]

trial_002 train e013:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:44<00:00,  1.36it/s, avg=0.09491, loss=0.09657]

trial_002 train e013:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:44<00:00,  1.36it/s, avg=0.09491, loss=0.09410]

trial_002 train e013: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:44<00:00,  1.63it/s, avg=0.09491, loss=0.09410]

trial_002 val e013:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e013:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.33it/s]

trial_002 val e013:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.33it/s]

trial_002 val e013:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.35it/s]

trial_002 val e013:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.38it/s]

trial_002 val e013:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.36it/s]

trial_002 val e013:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.40it/s]

trial_002 val e013:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.39it/s]

trial_002 val e013:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.36it/s]

trial_002 val e013:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.28it/s]

trial_002 val e013:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:17,  2.28it/s]

trial_002 val e013:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.33it/s]

trial_002 val e013:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.37it/s]

trial_002 val e013:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.40it/s]

trial_002 val e013:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.42it/s]

trial_002 val e013:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.42it/s]

trial_002 val e013:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.37it/s]

trial_002 val e013:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.39it/s]

trial_002 val e013:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.39it/s]

trial_002 val e013:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:08<00:12,  2.40it/s]

trial_002 val e013:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.42it/s]

trial_002 val e013:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.40it/s]

trial_002 val e013:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.34it/s]

trial_002 val e013:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.36it/s]

trial_002 val e013:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:10,  2.39it/s]

trial_002 val e013:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.41it/s]

trial_002 val e013:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.44it/s]

trial_002 val e013:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.42it/s]

trial_002 val e013:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.38it/s]

trial_002 val e013:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:08,  2.39it/s]

trial_002 val e013:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.39it/s]

trial_002 val e013:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:13<00:07,  2.42it/s]

trial_002 val e013:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.43it/s]

trial_002 val e013:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.41it/s]

trial_002 val e013:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.37it/s]

trial_002 val e013:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.37it/s]

trial_002 val e013:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:05,  2.40it/s]

trial_002 val e013:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.40it/s]

trial_002 val e013:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.41it/s]

trial_002 val e013:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.36it/s]

trial_002 val e013:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.37it/s]

trial_002 val e013:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.38it/s]

trial_002 val e013:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.39it/s]

trial_002 val e013:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:18<00:02,  2.39it/s]

trial_002 val e013:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.38it/s]

trial_002 val e013:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.39it/s]

trial_002 val e013:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.41it/s]

trial_002 val e013:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.41it/s]

trial_002 val e013:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:20<00:00,  2.40it/s]

trial_002 val e013:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.37it/s]

trial_002 val e013: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.40it/s]

[2026-05-28 20:52:06] [trial_002] epoch=013 | train_loss=0.094905 | val_MAE=0.098938 | val_S=0.901062 | best_S=0.901580 @epoch=11 | patience=2/5

[trial_002] epochs:  13%|███████████████▌                                                                                                        | 13/100 [28:30<3:06:31, 128.64s/it]

trial_002 train e014:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e014:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08662, loss=0.08662]

trial_002 train e014:   1%|▋                                                                                              | 1/149 [00:00<01:39,  1.48it/s, avg=0.08662, loss=0.08662]

trial_002 train e014:   1%|▋                                                                                              | 1/149 [00:01<01:39,  1.48it/s, avg=0.08802, loss=0.08942]

trial_002 train e014:   1%|█▎                                                                                             | 2/149 [00:01<01:43,  1.42it/s, avg=0.08802, loss=0.08942]

trial_002 train e014:   1%|█▎                                                                                             | 2/149 [00:02<01:43,  1.42it/s, avg=0.09271, loss=0.10210]

trial_002 train e014:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.39it/s, avg=0.09271, loss=0.10210]

trial_002 train e014:   2%|█▉                                                                                             | 3/149 [00:02<01:45,  1.39it/s, avg=0.09740, loss=0.11145]

trial_002 train e014:   3%|██▌                                                                                            | 4/149 [00:02<01:46,  1.36it/s, avg=0.09740, loss=0.11145]

trial_002 train e014:   3%|██▌                                                                                            | 4/149 [00:03<01:46,  1.36it/s, avg=0.09762, loss=0.09848]

trial_002 train e014:   3%|███▏                                                                                           | 5/149 [00:03<01:43,  1.39it/s, avg=0.09762, loss=0.09848]

trial_002 train e014:   3%|███▏                                                                                           | 5/149 [00:04<01:43,  1.39it/s, avg=0.09644, loss=0.09056]

trial_002 train e014:   4%|███▊                                                                                           | 6/149 [00:04<01:45,  1.36it/s, avg=0.09644, loss=0.09056]

trial_002 train e014:   4%|███▊                                                                                           | 6/149 [00:05<01:45,  1.36it/s, avg=0.09466, loss=0.08401]

trial_002 train e014:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.09466, loss=0.08401]

trial_002 train e014:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.09470, loss=0.09494]

trial_002 train e014:   5%|█████                                                                                          | 8/149 [00:05<01:42,  1.37it/s, avg=0.09470, loss=0.09494]

trial_002 train e014:   5%|█████                                                                                          | 8/149 [00:06<01:42,  1.37it/s, avg=0.09543, loss=0.10131]

trial_002 train e014:   6%|█████▋                                                                                         | 9/149 [00:06<01:40,  1.39it/s, avg=0.09543, loss=0.10131]

trial_002 train e014:   6%|█████▋                                                                                         | 9/149 [00:07<01:40,  1.39it/s, avg=0.09417, loss=0.08280]

trial_002 train e014:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.39it/s, avg=0.09417, loss=0.08280]

trial_002 train e014:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.39it/s, avg=0.09470, loss=0.10002]

trial_002 train e014:   7%|██████▉                                                                                       | 11/149 [00:07<01:39,  1.38it/s, avg=0.09470, loss=0.10002]

trial_002 train e014:   7%|██████▉                                                                                       | 11/149 [00:08<01:39,  1.38it/s, avg=0.09487, loss=0.09673]

trial_002 train e014:   8%|███████▌                                                                                      | 12/149 [00:08<01:38,  1.39it/s, avg=0.09487, loss=0.09673]

trial_002 train e014:   8%|███████▌                                                                                      | 12/149 [00:09<01:38,  1.39it/s, avg=0.09481, loss=0.09408]

trial_002 train e014:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.35it/s, avg=0.09481, loss=0.09408]

trial_002 train e014:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.35it/s, avg=0.09481, loss=0.09484]

trial_002 train e014:   9%|████████▊                                                                                     | 14/149 [00:10<01:42,  1.32it/s, avg=0.09481, loss=0.09484]

trial_002 train e014:   9%|████████▊                                                                                     | 14/149 [00:10<01:42,  1.32it/s, avg=0.09526, loss=0.10157]

trial_002 train e014:  10%|█████████▍                                                                                    | 15/149 [00:10<01:41,  1.32it/s, avg=0.09526, loss=0.10157]

trial_002 train e014:  10%|█████████▍                                                                                    | 15/149 [00:11<01:41,  1.32it/s, avg=0.09490, loss=0.08950]

trial_002 train e014:  11%|██████████                                                                                    | 16/149 [00:11<01:40,  1.32it/s, avg=0.09490, loss=0.08950]

trial_002 train e014:  11%|██████████                                                                                    | 16/149 [00:12<01:40,  1.32it/s, avg=0.09542, loss=0.10371]

trial_002 train e014:  11%|██████████▋                                                                                   | 17/149 [00:12<01:38,  1.34it/s, avg=0.09542, loss=0.10371]

trial_002 train e014:  11%|██████████▋                                                                                   | 17/149 [00:13<01:38,  1.34it/s, avg=0.09552, loss=0.09717]

trial_002 train e014:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.38it/s, avg=0.09552, loss=0.09717]

trial_002 train e014:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.38it/s, avg=0.09666, loss=0.11716]

trial_002 train e014:  13%|███████████▉                                                                                  | 19/149 [00:13<01:33,  1.39it/s, avg=0.09666, loss=0.11716]

trial_002 train e014:  13%|███████████▉                                                                                  | 19/149 [00:14<01:33,  1.39it/s, avg=0.09686, loss=0.10069]

trial_002 train e014:  13%|████████████▌                                                                                 | 20/149 [00:14<01:34,  1.36it/s, avg=0.09686, loss=0.10069]

trial_002 train e014:  13%|████████████▌                                                                                 | 20/149 [00:15<01:34,  1.36it/s, avg=0.09668, loss=0.09302]

trial_002 train e014:  14%|█████████████▏                                                                                | 21/149 [00:15<01:35,  1.34it/s, avg=0.09668, loss=0.09302]

trial_002 train e014:  14%|█████████████▏                                                                                | 21/149 [00:16<01:35,  1.34it/s, avg=0.09604, loss=0.08272]

trial_002 train e014:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.34it/s, avg=0.09604, loss=0.08272]

trial_002 train e014:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.34it/s, avg=0.09616, loss=0.09889]

trial_002 train e014:  15%|██████████████▌                                                                               | 23/149 [00:16<01:33,  1.35it/s, avg=0.09616, loss=0.09889]

trial_002 train e014:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.35it/s, avg=0.09649, loss=0.10388]

trial_002 train e014:  16%|███████████████▏                                                                              | 24/149 [00:17<01:30,  1.39it/s, avg=0.09649, loss=0.10388]

trial_002 train e014:  16%|███████████████▏                                                                              | 24/149 [00:18<01:30,  1.39it/s, avg=0.09625, loss=0.09067]

trial_002 train e014:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.38it/s, avg=0.09625, loss=0.09067]

trial_002 train e014:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.38it/s, avg=0.09600, loss=0.08961]

trial_002 train e014:  17%|████████████████▍                                                                             | 26/149 [00:18<01:29,  1.38it/s, avg=0.09600, loss=0.08961]

trial_002 train e014:  17%|████████████████▍                                                                             | 26/149 [00:19<01:29,  1.38it/s, avg=0.09613, loss=0.09961]

trial_002 train e014:  18%|█████████████████                                                                             | 27/149 [00:19<01:28,  1.37it/s, avg=0.09613, loss=0.09961]

trial_002 train e014:  18%|█████████████████                                                                             | 27/149 [00:20<01:28,  1.37it/s, avg=0.09623, loss=0.09897]

trial_002 train e014:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.37it/s, avg=0.09623, loss=0.09897]

trial_002 train e014:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:28,  1.37it/s, avg=0.09661, loss=0.10706]

trial_002 train e014:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:25,  1.40it/s, avg=0.09661, loss=0.10706]

trial_002 train e014:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:25,  1.40it/s, avg=0.09662, loss=0.09687]

trial_002 train e014:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:25,  1.39it/s, avg=0.09662, loss=0.09687]

trial_002 train e014:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:25,  1.39it/s, avg=0.09698, loss=0.10805]

trial_002 train e014:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:25,  1.39it/s, avg=0.09698, loss=0.10805]

trial_002 train e014:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:25,  1.39it/s, avg=0.09680, loss=0.09124]

trial_002 train e014:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:25,  1.37it/s, avg=0.09680, loss=0.09124]

trial_002 train e014:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:25,  1.37it/s, avg=0.09687, loss=0.09894]

trial_002 train e014:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.09687, loss=0.09894]

trial_002 train e014:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.09674, loss=0.09246]

trial_002 train e014:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:23,  1.37it/s, avg=0.09674, loss=0.09246]

trial_002 train e014:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.09676, loss=0.09737]

trial_002 train e014:  23%|██████████████████████                                                                        | 35/149 [00:25<01:23,  1.37it/s, avg=0.09676, loss=0.09737]

trial_002 train e014:  23%|██████████████████████                                                                        | 35/149 [00:26<01:23,  1.37it/s, avg=0.09636, loss=0.08237]

trial_002 train e014:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:24,  1.34it/s, avg=0.09636, loss=0.08237]

trial_002 train e014:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:24,  1.34it/s, avg=0.09646, loss=0.09997]

trial_002 train e014:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.35it/s, avg=0.09646, loss=0.09997]

trial_002 train e014:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:22,  1.35it/s, avg=0.09612, loss=0.08371]

trial_002 train e014:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:23,  1.33it/s, avg=0.09612, loss=0.08371]

trial_002 train e014:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:23,  1.33it/s, avg=0.09617, loss=0.09791]

trial_002 train e014:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:23,  1.32it/s, avg=0.09617, loss=0.09791]

trial_002 train e014:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:23,  1.32it/s, avg=0.09641, loss=0.10580]

trial_002 train e014:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:21,  1.33it/s, avg=0.09641, loss=0.10580]

trial_002 train e014:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:21,  1.33it/s, avg=0.09628, loss=0.09101]

trial_002 train e014:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:20,  1.34it/s, avg=0.09628, loss=0.09101]

trial_002 train e014:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:20,  1.34it/s, avg=0.09629, loss=0.09672]

trial_002 train e014:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:19,  1.35it/s, avg=0.09629, loss=0.09672]

trial_002 train e014:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:19,  1.35it/s, avg=0.09617, loss=0.09138]

trial_002 train e014:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:16,  1.39it/s, avg=0.09617, loss=0.09138]

trial_002 train e014:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:16,  1.39it/s, avg=0.09623, loss=0.09854]

trial_002 train e014:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:16,  1.37it/s, avg=0.09623, loss=0.09854]

trial_002 train e014:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:16,  1.37it/s, avg=0.09627, loss=0.09845]

trial_002 train e014:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:15,  1.37it/s, avg=0.09627, loss=0.09845]

trial_002 train e014:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.37it/s, avg=0.09601, loss=0.08401]

trial_002 train e014:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:15,  1.36it/s, avg=0.09601, loss=0.08401]

trial_002 train e014:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:15,  1.36it/s, avg=0.09590, loss=0.09075]

trial_002 train e014:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:15,  1.35it/s, avg=0.09590, loss=0.09075]

trial_002 train e014:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:15,  1.35it/s, avg=0.09588, loss=0.09492]

trial_002 train e014:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.35it/s, avg=0.09588, loss=0.09492]

trial_002 train e014:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.35it/s, avg=0.09567, loss=0.08574]

trial_002 train e014:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:14,  1.34it/s, avg=0.09567, loss=0.08574]

trial_002 train e014:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:14,  1.34it/s, avg=0.09592, loss=0.10846]

trial_002 train e014:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:13,  1.34it/s, avg=0.09592, loss=0.10846]

trial_002 train e014:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:13,  1.34it/s, avg=0.09596, loss=0.09781]

trial_002 train e014:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:11,  1.37it/s, avg=0.09596, loss=0.09781]

trial_002 train e014:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:11,  1.37it/s, avg=0.09630, loss=0.11347]

trial_002 train e014:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:09,  1.40it/s, avg=0.09630, loss=0.11347]

trial_002 train e014:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:09,  1.40it/s, avg=0.09637, loss=0.10000]

trial_002 train e014:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:09,  1.39it/s, avg=0.09637, loss=0.10000]

trial_002 train e014:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:09,  1.39it/s, avg=0.09631, loss=0.09347]

trial_002 train e014:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.38it/s, avg=0.09631, loss=0.09347]

trial_002 train e014:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:09,  1.38it/s, avg=0.09633, loss=0.09724]

trial_002 train e014:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.38it/s, avg=0.09633, loss=0.09724]

trial_002 train e014:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:08,  1.38it/s, avg=0.09612, loss=0.08437]

trial_002 train e014:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:08,  1.35it/s, avg=0.09612, loss=0.08437]

trial_002 train e014:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:08,  1.35it/s, avg=0.09600, loss=0.08922]

trial_002 train e014:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:07,  1.35it/s, avg=0.09600, loss=0.08922]

trial_002 train e014:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:07,  1.35it/s, avg=0.09595, loss=0.09307]

trial_002 train e014:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:07,  1.34it/s, avg=0.09595, loss=0.09307]

trial_002 train e014:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:07,  1.34it/s, avg=0.09606, loss=0.10234]

trial_002 train e014:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:07,  1.34it/s, avg=0.09606, loss=0.10234]

trial_002 train e014:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:07,  1.34it/s, avg=0.09601, loss=0.09359]

trial_002 train e014:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:05,  1.36it/s, avg=0.09601, loss=0.09359]

trial_002 train e014:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.36it/s, avg=0.09597, loss=0.09321]

trial_002 train e014:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:04,  1.36it/s, avg=0.09597, loss=0.09321]

trial_002 train e014:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:04,  1.36it/s, avg=0.09583, loss=0.08717]

trial_002 train e014:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:04,  1.35it/s, avg=0.09583, loss=0.08717]

trial_002 train e014:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.35it/s, avg=0.09585, loss=0.09737]

trial_002 train e014:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:03,  1.36it/s, avg=0.09585, loss=0.09737]

trial_002 train e014:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:03,  1.36it/s, avg=0.09597, loss=0.10317]

trial_002 train e014:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.38it/s, avg=0.09597, loss=0.10317]

trial_002 train e014:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:01,  1.38it/s, avg=0.09574, loss=0.08137]

trial_002 train e014:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:01,  1.37it/s, avg=0.09574, loss=0.08137]

trial_002 train e014:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.37it/s, avg=0.09558, loss=0.08524]

trial_002 train e014:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:59,  1.38it/s, avg=0.09558, loss=0.08524]

trial_002 train e014:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<00:59,  1.38it/s, avg=0.09548, loss=0.08896]

trial_002 train e014:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:59,  1.38it/s, avg=0.09548, loss=0.08896]

trial_002 train e014:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:59,  1.38it/s, avg=0.09539, loss=0.08914]

trial_002 train e014:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:59,  1.36it/s, avg=0.09539, loss=0.08914]

trial_002 train e014:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:59,  1.36it/s, avg=0.09518, loss=0.08120]

trial_002 train e014:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:58,  1.37it/s, avg=0.09518, loss=0.08120]

trial_002 train e014:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.37it/s, avg=0.09544, loss=0.11306]

trial_002 train e014:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.35it/s, avg=0.09544, loss=0.11306]

trial_002 train e014:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:58,  1.35it/s, avg=0.09542, loss=0.09374]

trial_002 train e014:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.35it/s, avg=0.09542, loss=0.09374]

trial_002 train e014:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.35it/s, avg=0.09533, loss=0.08942]

trial_002 train e014:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:56,  1.37it/s, avg=0.09533, loss=0.08942]

trial_002 train e014:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:56,  1.37it/s, avg=0.09544, loss=0.10337]

trial_002 train e014:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:55,  1.37it/s, avg=0.09544, loss=0.10337]

trial_002 train e014:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:55,  1.37it/s, avg=0.09562, loss=0.10869]

trial_002 train e014:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:54,  1.37it/s, avg=0.09562, loss=0.10869]

trial_002 train e014:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:54,  1.37it/s, avg=0.09555, loss=0.09034]

trial_002 train e014:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:54,  1.37it/s, avg=0.09555, loss=0.09034]

trial_002 train e014:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:54,  1.37it/s, avg=0.09555, loss=0.09565]

trial_002 train e014:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:54,  1.34it/s, avg=0.09555, loss=0.09565]

trial_002 train e014:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:54,  1.34it/s, avg=0.09551, loss=0.09243]

trial_002 train e014:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:53,  1.36it/s, avg=0.09551, loss=0.09243]

trial_002 train e014:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:53,  1.36it/s, avg=0.09535, loss=0.08279]

trial_002 train e014:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.37it/s, avg=0.09535, loss=0.08279]

trial_002 train e014:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.37it/s, avg=0.09512, loss=0.07716]

trial_002 train e014:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:50,  1.37it/s, avg=0.09512, loss=0.07716]

trial_002 train e014:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:50,  1.37it/s, avg=0.09526, loss=0.10655]

trial_002 train e014:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.36it/s, avg=0.09526, loss=0.10655]

trial_002 train e014:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:50,  1.36it/s, avg=0.09530, loss=0.09840]

trial_002 train e014:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.36it/s, avg=0.09530, loss=0.09840]

trial_002 train e014:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:50,  1.36it/s, avg=0.09513, loss=0.08175]

trial_002 train e014:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:48,  1.37it/s, avg=0.09513, loss=0.08175]

trial_002 train e014:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:48,  1.37it/s, avg=0.09505, loss=0.08803]

trial_002 train e014:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:47,  1.39it/s, avg=0.09505, loss=0.08803]

trial_002 train e014:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:47,  1.39it/s, avg=0.09503, loss=0.09356]

trial_002 train e014:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:46,  1.40it/s, avg=0.09503, loss=0.09356]

trial_002 train e014:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:46,  1.40it/s, avg=0.09491, loss=0.08472]

trial_002 train e014:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:45,  1.39it/s, avg=0.09491, loss=0.08472]

trial_002 train e014:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:45,  1.39it/s, avg=0.09489, loss=0.09356]

trial_002 train e014:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.39it/s, avg=0.09489, loss=0.09356]

trial_002 train e014:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:45,  1.39it/s, avg=0.09486, loss=0.09222]

trial_002 train e014:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.41it/s, avg=0.09486, loss=0.09222]

trial_002 train e014:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:44,  1.41it/s, avg=0.09484, loss=0.09295]

trial_002 train e014:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.38it/s, avg=0.09484, loss=0.09295]

trial_002 train e014:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:44,  1.38it/s, avg=0.09472, loss=0.08376]

trial_002 train e014:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.36it/s, avg=0.09472, loss=0.08376]

trial_002 train e014:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.36it/s, avg=0.09456, loss=0.08090]

trial_002 train e014:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.37it/s, avg=0.09456, loss=0.08090]

trial_002 train e014:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.37it/s, avg=0.09437, loss=0.07719]

trial_002 train e014:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.35it/s, avg=0.09437, loss=0.07719]

trial_002 train e014:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.35it/s, avg=0.09426, loss=0.08392]

trial_002 train e014:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:41,  1.36it/s, avg=0.09426, loss=0.08392]

trial_002 train e014:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:41,  1.36it/s, avg=0.09425, loss=0.09304]

trial_002 train e014:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:41,  1.34it/s, avg=0.09425, loss=0.09304]

trial_002 train e014:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:41,  1.34it/s, avg=0.09443, loss=0.11154]

trial_002 train e014:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:41,  1.33it/s, avg=0.09443, loss=0.11154]

trial_002 train e014:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:41,  1.33it/s, avg=0.09437, loss=0.08856]

trial_002 train e014:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:40,  1.33it/s, avg=0.09437, loss=0.08856]

trial_002 train e014:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:40,  1.33it/s, avg=0.09446, loss=0.10300]

trial_002 train e014:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:39,  1.34it/s, avg=0.09446, loss=0.10300]

trial_002 train e014:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:39,  1.34it/s, avg=0.09446, loss=0.09464]

trial_002 train e014:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.35it/s, avg=0.09446, loss=0.09464]

trial_002 train e014:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.35it/s, avg=0.09453, loss=0.10116]

trial_002 train e014:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.35it/s, avg=0.09453, loss=0.10116]

trial_002 train e014:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.35it/s, avg=0.09453, loss=0.09479]

trial_002 train e014:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:35,  1.39it/s, avg=0.09453, loss=0.09479]

trial_002 train e014:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:35,  1.39it/s, avg=0.09443, loss=0.08472]

trial_002 train e014:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.37it/s, avg=0.09443, loss=0.08472]

trial_002 train e014:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:35,  1.37it/s, avg=0.09444, loss=0.09464]

trial_002 train e014:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09444, loss=0.09464]

trial_002 train e014:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09445, loss=0.09577]

trial_002 train e014:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.36it/s, avg=0.09445, loss=0.09577]

trial_002 train e014:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:34,  1.36it/s, avg=0.09450, loss=0.10021]

trial_002 train e014:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:34,  1.34it/s, avg=0.09450, loss=0.10021]

trial_002 train e014:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:34,  1.34it/s, avg=0.09456, loss=0.10027]

trial_002 train e014:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:33,  1.35it/s, avg=0.09456, loss=0.10027]

trial_002 train e014:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:33,  1.35it/s, avg=0.09447, loss=0.08516]

trial_002 train e014:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:33,  1.33it/s, avg=0.09447, loss=0.08516]

trial_002 train e014:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:33,  1.33it/s, avg=0.09455, loss=0.10254]

trial_002 train e014:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:32,  1.32it/s, avg=0.09455, loss=0.10254]

trial_002 train e014:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:32,  1.32it/s, avg=0.09454, loss=0.09434]

trial_002 train e014:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:31,  1.32it/s, avg=0.09454, loss=0.09434]

trial_002 train e014:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:31,  1.32it/s, avg=0.09443, loss=0.08227]

trial_002 train e014:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.34it/s, avg=0.09443, loss=0.08227]

trial_002 train e014:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:30,  1.34it/s, avg=0.09438, loss=0.08927]

trial_002 train e014:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:30,  1.33it/s, avg=0.09438, loss=0.08927]

trial_002 train e014:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:30,  1.33it/s, avg=0.09438, loss=0.09372]

trial_002 train e014:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:29,  1.30it/s, avg=0.09438, loss=0.09372]

trial_002 train e014:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:29,  1.30it/s, avg=0.09434, loss=0.09066]

trial_002 train e014:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:29,  1.30it/s, avg=0.09434, loss=0.09066]

trial_002 train e014:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:29,  1.30it/s, avg=0.09430, loss=0.08987]

trial_002 train e014:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:28,  1.29it/s, avg=0.09430, loss=0.08987]

trial_002 train e014:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:28,  1.29it/s, avg=0.09430, loss=0.09438]

trial_002 train e014:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:27,  1.30it/s, avg=0.09430, loss=0.09438]

trial_002 train e014:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:27,  1.30it/s, avg=0.09420, loss=0.08241]

trial_002 train e014:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:26,  1.31it/s, avg=0.09420, loss=0.08241]

trial_002 train e014:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:26,  1.31it/s, avg=0.09420, loss=0.09457]

trial_002 train e014:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.36it/s, avg=0.09420, loss=0.09457]

trial_002 train e014:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:25<00:24,  1.36it/s, avg=0.09416, loss=0.08975]

trial_002 train e014:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:23,  1.38it/s, avg=0.09416, loss=0.08975]

trial_002 train e014:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:26<00:23,  1.38it/s, avg=0.09414, loss=0.09156]

trial_002 train e014:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.38it/s, avg=0.09414, loss=0.09156]

trial_002 train e014:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.38it/s, avg=0.09420, loss=0.10093]

trial_002 train e014:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.36it/s, avg=0.09420, loss=0.10093]

trial_002 train e014:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:22,  1.36it/s, avg=0.09414, loss=0.08752]

trial_002 train e014:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.37it/s, avg=0.09414, loss=0.08752]

trial_002 train e014:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:28<00:21,  1.37it/s, avg=0.09417, loss=0.09727]

trial_002 train e014:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.36it/s, avg=0.09417, loss=0.09727]

trial_002 train e014:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.36it/s, avg=0.09423, loss=0.10193]

trial_002 train e014:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.37it/s, avg=0.09423, loss=0.10193]

trial_002 train e014:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.37it/s, avg=0.09416, loss=0.08470]

trial_002 train e014:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:20,  1.35it/s, avg=0.09416, loss=0.08470]

trial_002 train e014:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:20,  1.35it/s, avg=0.09421, loss=0.10117]

trial_002 train e014:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.33it/s, avg=0.09421, loss=0.10117]

trial_002 train e014:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:31<00:19,  1.33it/s, avg=0.09420, loss=0.09283]

trial_002 train e014:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.33it/s, avg=0.09420, loss=0.09283]

trial_002 train e014:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:32<00:18,  1.33it/s, avg=0.09426, loss=0.10099]

trial_002 train e014:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:18,  1.31it/s, avg=0.09426, loss=0.10099]

trial_002 train e014:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:18,  1.31it/s, avg=0.09426, loss=0.09529]

trial_002 train e014:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:17,  1.33it/s, avg=0.09426, loss=0.09529]

trial_002 train e014:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:17,  1.33it/s, avg=0.09433, loss=0.10301]

trial_002 train e014:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.35it/s, avg=0.09433, loss=0.10301]

trial_002 train e014:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:34<00:16,  1.35it/s, avg=0.09441, loss=0.10415]

trial_002 train e014:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.34it/s, avg=0.09441, loss=0.10415]

trial_002 train e014:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.34it/s, avg=0.09444, loss=0.09893]

trial_002 train e014:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.34it/s, avg=0.09444, loss=0.09893]

trial_002 train e014:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.34it/s, avg=0.09444, loss=0.09347]

trial_002 train e014:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:14,  1.34it/s, avg=0.09444, loss=0.09347]

trial_002 train e014:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:14,  1.34it/s, avg=0.09441, loss=0.09028]

trial_002 train e014:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.33it/s, avg=0.09441, loss=0.09028]

trial_002 train e014:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:37<00:13,  1.33it/s, avg=0.09434, loss=0.08621]

trial_002 train e014:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.34it/s, avg=0.09434, loss=0.08621]

trial_002 train e014:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:38<00:12,  1.34it/s, avg=0.09432, loss=0.09126]

trial_002 train e014:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:12,  1.31it/s, avg=0.09432, loss=0.09126]

trial_002 train e014:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:12,  1.31it/s, avg=0.09435, loss=0.09895]

trial_002 train e014:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:11,  1.32it/s, avg=0.09435, loss=0.09895]

trial_002 train e014:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:39<00:11,  1.32it/s, avg=0.09445, loss=0.10701]

trial_002 train e014:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.33it/s, avg=0.09445, loss=0.10701]

trial_002 train e014:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:40<00:10,  1.33it/s, avg=0.09443, loss=0.09206]

trial_002 train e014:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.36it/s, avg=0.09443, loss=0.09206]

trial_002 train e014:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.36it/s, avg=0.09442, loss=0.09316]

trial_002 train e014:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.36it/s, avg=0.09442, loss=0.09316]

trial_002 train e014:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:41<00:08,  1.36it/s, avg=0.09446, loss=0.10033]

trial_002 train e014:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.35it/s, avg=0.09446, loss=0.10033]

trial_002 train e014:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:42<00:08,  1.35it/s, avg=0.09454, loss=0.10426]

trial_002 train e014:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.37it/s, avg=0.09454, loss=0.10426]

trial_002 train e014:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:43<00:07,  1.37it/s, avg=0.09455, loss=0.09727]

trial_002 train e014:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.36it/s, avg=0.09455, loss=0.09727]

trial_002 train e014:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.36it/s, avg=0.09458, loss=0.09758]

trial_002 train e014:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.39it/s, avg=0.09458, loss=0.09758]

trial_002 train e014:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:44<00:05,  1.39it/s, avg=0.09452, loss=0.08625]

trial_002 train e014:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.38it/s, avg=0.09452, loss=0.08625]

trial_002 train e014:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:45<00:05,  1.38it/s, avg=0.09451, loss=0.09369]

trial_002 train e014:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.38it/s, avg=0.09451, loss=0.09369]

trial_002 train e014:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:46<00:04,  1.38it/s, avg=0.09446, loss=0.08670]

trial_002 train e014:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:46<00:03,  1.37it/s, avg=0.09446, loss=0.08670]

trial_002 train e014:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:46<00:03,  1.37it/s, avg=0.09437, loss=0.08194]

trial_002 train e014:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.37it/s, avg=0.09437, loss=0.08194]

trial_002 train e014:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:47<00:02,  1.37it/s, avg=0.09442, loss=0.10142]

trial_002 train e014:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.40it/s, avg=0.09442, loss=0.10142]

trial_002 train e014:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:48<00:02,  1.40it/s, avg=0.09446, loss=0.09990]

trial_002 train e014:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.39it/s, avg=0.09446, loss=0.09990]

trial_002 train e014:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.39it/s, avg=0.09441, loss=0.08824]

trial_002 train e014:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.36it/s, avg=0.09441, loss=0.08824]

trial_002 train e014:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:49<00:00,  1.36it/s, avg=0.09444, loss=0.10259]

trial_002 train e014: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:49<00:00,  1.65it/s, avg=0.09444, loss=0.10259]

trial_002 val e014:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e014:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.31it/s]

trial_002 val e014:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.40it/s]

trial_002 val e014:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.43it/s]

trial_002 val e014:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.41it/s]

trial_002 val e014:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.39it/s]

trial_002 val e014:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.40it/s]

trial_002 val e014:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.42it/s]

trial_002 val e014:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.44it/s]

trial_002 val e014:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.44it/s]

trial_002 val e014:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.40it/s]

trial_002 val e014:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.36it/s]

trial_002 val e014:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:16,  2.34it/s]

trial_002 val e014:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.37it/s]

trial_002 val e014:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:15,  2.38it/s]

trial_002 val e014:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.37it/s]

trial_002 val e014:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.38it/s]

trial_002 val e014:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.39it/s]

trial_002 val e014:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.39it/s]

trial_002 val e014:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.43it/s]

trial_002 val e014:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.43it/s]

trial_002 val e014:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.43it/s]

trial_002 val e014:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.39it/s]

trial_002 val e014:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.40it/s]

trial_002 val e014:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:11,  2.35it/s]

trial_002 val e014:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.39it/s]

trial_002 val e014:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.39it/s]

trial_002 val e014:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.38it/s]

trial_002 val e014:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.38it/s]

trial_002 val e014:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:08,  2.40it/s]

trial_002 val e014:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.41it/s]

trial_002 val e014:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.43it/s]

trial_002 val e014:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.43it/s]

trial_002 val e014:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.44it/s]

trial_002 val e014:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.43it/s]

trial_002 val e014:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.36it/s]

trial_002 val e014:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:05,  2.36it/s]

trial_002 val e014:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.36it/s]

trial_002 val e014:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:05,  2.34it/s]

trial_002 val e014:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.36it/s]

trial_002 val e014:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.38it/s]

trial_002 val e014:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.39it/s]

trial_002 val e014:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.41it/s]

trial_002 val e014:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.43it/s]

trial_002 val e014:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.45it/s]

trial_002 val e014:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.46it/s]

trial_002 val e014:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.47it/s]

trial_002 val e014:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.48it/s]

trial_002 val e014:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.48it/s]

trial_002 val e014:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.47it/s]

trial_002 val e014: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.43it/s]

[2026-05-28 20:54:18] [trial_002] epoch=014 | train_loss=0.094437 | val_MAE=0.097869 | val_S=0.902131 | best_S=0.902131 @epoch=14 | patience=0/5

[trial_002] epochs:  14%|████████████████▊                                                                                                       | 14/100 [30:41<3:05:32, 129.45s/it]

trial_002 train e015:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e015:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08653, loss=0.08653]

trial_002 train e015:   1%|▋                                                                                              | 1/149 [00:00<01:53,  1.30it/s, avg=0.08653, loss=0.08653]

trial_002 train e015:   1%|▋                                                                                              | 1/149 [00:01<01:53,  1.30it/s, avg=0.08969, loss=0.09285]

trial_002 train e015:   1%|█▎                                                                                             | 2/149 [00:01<01:50,  1.33it/s, avg=0.08969, loss=0.09285]

trial_002 train e015:   1%|█▎                                                                                             | 2/149 [00:02<01:50,  1.33it/s, avg=0.08788, loss=0.08426]

trial_002 train e015:   2%|█▉                                                                                             | 3/149 [00:02<01:49,  1.33it/s, avg=0.08788, loss=0.08426]

trial_002 train e015:   2%|█▉                                                                                             | 3/149 [00:02<01:49,  1.33it/s, avg=0.09058, loss=0.09866]

trial_002 train e015:   3%|██▌                                                                                            | 4/149 [00:02<01:48,  1.34it/s, avg=0.09058, loss=0.09866]

trial_002 train e015:   3%|██▌                                                                                            | 4/149 [00:03<01:48,  1.34it/s, avg=0.09323, loss=0.10383]

trial_002 train e015:   3%|███▏                                                                                           | 5/149 [00:03<01:47,  1.34it/s, avg=0.09323, loss=0.10383]

trial_002 train e015:   3%|███▏                                                                                           | 5/149 [00:04<01:47,  1.34it/s, avg=0.09233, loss=0.08784]

trial_002 train e015:   4%|███▊                                                                                           | 6/149 [00:04<01:47,  1.33it/s, avg=0.09233, loss=0.08784]

trial_002 train e015:   4%|███▊                                                                                           | 6/149 [00:05<01:47,  1.33it/s, avg=0.09413, loss=0.10496]

trial_002 train e015:   5%|████▍                                                                                          | 7/149 [00:05<01:45,  1.35it/s, avg=0.09413, loss=0.10496]

trial_002 train e015:   5%|████▍                                                                                          | 7/149 [00:05<01:45,  1.35it/s, avg=0.09312, loss=0.08599]

trial_002 train e015:   5%|█████                                                                                          | 8/149 [00:05<01:43,  1.36it/s, avg=0.09312, loss=0.08599]

trial_002 train e015:   5%|█████                                                                                          | 8/149 [00:06<01:43,  1.36it/s, avg=0.09418, loss=0.10266]

trial_002 train e015:   6%|█████▋                                                                                         | 9/149 [00:06<01:43,  1.36it/s, avg=0.09418, loss=0.10266]

trial_002 train e015:   6%|█████▋                                                                                         | 9/149 [00:07<01:43,  1.36it/s, avg=0.09537, loss=0.10612]

trial_002 train e015:   7%|██████▎                                                                                       | 10/149 [00:07<01:43,  1.34it/s, avg=0.09537, loss=0.10612]

trial_002 train e015:   7%|██████▎                                                                                       | 10/149 [00:08<01:43,  1.34it/s, avg=0.09504, loss=0.09174]

trial_002 train e015:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.35it/s, avg=0.09504, loss=0.09174]

trial_002 train e015:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.35it/s, avg=0.09409, loss=0.08362]

trial_002 train e015:   8%|███████▌                                                                                      | 12/149 [00:08<01:41,  1.34it/s, avg=0.09409, loss=0.08362]

trial_002 train e015:   8%|███████▌                                                                                      | 12/149 [00:09<01:41,  1.34it/s, avg=0.09345, loss=0.08571]

trial_002 train e015:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.35it/s, avg=0.09345, loss=0.08571]

trial_002 train e015:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.35it/s, avg=0.09327, loss=0.09097]

trial_002 train e015:   9%|████████▊                                                                                     | 14/149 [00:10<01:40,  1.34it/s, avg=0.09327, loss=0.09097]

trial_002 train e015:   9%|████████▊                                                                                     | 14/149 [00:11<01:40,  1.34it/s, avg=0.09277, loss=0.08573]

trial_002 train e015:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.34it/s, avg=0.09277, loss=0.08573]

trial_002 train e015:  10%|█████████▍                                                                                    | 15/149 [00:11<01:40,  1.34it/s, avg=0.09252, loss=0.08876]

trial_002 train e015:  11%|██████████                                                                                    | 16/149 [00:11<01:39,  1.34it/s, avg=0.09252, loss=0.08876]

trial_002 train e015:  11%|██████████                                                                                    | 16/149 [00:12<01:39,  1.34it/s, avg=0.09271, loss=0.09586]

trial_002 train e015:  11%|██████████▋                                                                                   | 17/149 [00:12<01:37,  1.35it/s, avg=0.09271, loss=0.09586]

trial_002 train e015:  11%|██████████▋                                                                                   | 17/149 [00:13<01:37,  1.35it/s, avg=0.09228, loss=0.08499]

trial_002 train e015:  12%|███████████▎                                                                                  | 18/149 [00:13<01:38,  1.33it/s, avg=0.09228, loss=0.08499]

trial_002 train e015:  12%|███████████▎                                                                                  | 18/149 [00:14<01:38,  1.33it/s, avg=0.09201, loss=0.08710]

trial_002 train e015:  13%|███████████▉                                                                                  | 19/149 [00:14<01:37,  1.33it/s, avg=0.09201, loss=0.08710]

trial_002 train e015:  13%|███████████▉                                                                                  | 19/149 [00:14<01:37,  1.33it/s, avg=0.09266, loss=0.10491]

trial_002 train e015:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.38it/s, avg=0.09266, loss=0.10491]

trial_002 train e015:  13%|████████████▌                                                                                 | 20/149 [00:15<01:33,  1.38it/s, avg=0.09222, loss=0.08361]

trial_002 train e015:  14%|█████████████▏                                                                                | 21/149 [00:15<01:35,  1.35it/s, avg=0.09222, loss=0.08361]

trial_002 train e015:  14%|█████████████▏                                                                                | 21/149 [00:16<01:35,  1.35it/s, avg=0.09251, loss=0.09852]

trial_002 train e015:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.35it/s, avg=0.09251, loss=0.09852]

trial_002 train e015:  15%|█████████████▉                                                                                | 22/149 [00:17<01:34,  1.35it/s, avg=0.09273, loss=0.09745]

trial_002 train e015:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.35it/s, avg=0.09273, loss=0.09745]

trial_002 train e015:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.35it/s, avg=0.09234, loss=0.08355]

trial_002 train e015:  16%|███████████████▏                                                                              | 24/149 [00:17<01:32,  1.35it/s, avg=0.09234, loss=0.08355]

trial_002 train e015:  16%|███████████████▏                                                                              | 24/149 [00:18<01:32,  1.35it/s, avg=0.09318, loss=0.11326]

trial_002 train e015:  17%|███████████████▊                                                                              | 25/149 [00:18<01:29,  1.39it/s, avg=0.09318, loss=0.11326]

trial_002 train e015:  17%|███████████████▊                                                                              | 25/149 [00:19<01:29,  1.39it/s, avg=0.09315, loss=0.09237]

trial_002 train e015:  17%|████████████████▍                                                                             | 26/149 [00:19<01:28,  1.39it/s, avg=0.09315, loss=0.09237]

trial_002 train e015:  17%|████████████████▍                                                                             | 26/149 [00:19<01:28,  1.39it/s, avg=0.09285, loss=0.08520]

trial_002 train e015:  18%|█████████████████                                                                             | 27/149 [00:19<01:27,  1.39it/s, avg=0.09285, loss=0.08520]

trial_002 train e015:  18%|█████████████████                                                                             | 27/149 [00:20<01:27,  1.39it/s, avg=0.09288, loss=0.09347]

trial_002 train e015:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:29,  1.36it/s, avg=0.09288, loss=0.09347]

trial_002 train e015:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:29,  1.36it/s, avg=0.09268, loss=0.08707]

trial_002 train e015:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:27,  1.37it/s, avg=0.09268, loss=0.08707]

trial_002 train e015:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:27,  1.37it/s, avg=0.09272, loss=0.09396]

trial_002 train e015:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.36it/s, avg=0.09272, loss=0.09396]

trial_002 train e015:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.36it/s, avg=0.09281, loss=0.09550]

trial_002 train e015:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:27,  1.35it/s, avg=0.09281, loss=0.09550]

trial_002 train e015:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.35it/s, avg=0.09305, loss=0.10061]

trial_002 train e015:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:25,  1.37it/s, avg=0.09305, loss=0.10061]

trial_002 train e015:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:25,  1.37it/s, avg=0.09348, loss=0.10705]

trial_002 train e015:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:23,  1.38it/s, avg=0.09348, loss=0.10705]

trial_002 train e015:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:23,  1.38it/s, avg=0.09327, loss=0.08640]

trial_002 train e015:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:22,  1.40it/s, avg=0.09327, loss=0.08640]

trial_002 train e015:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:22,  1.40it/s, avg=0.09334, loss=0.09587]

trial_002 train e015:  23%|██████████████████████                                                                        | 35/149 [00:25<01:20,  1.42it/s, avg=0.09334, loss=0.09587]

trial_002 train e015:  23%|██████████████████████                                                                        | 35/149 [00:26<01:20,  1.42it/s, avg=0.09332, loss=0.09258]

trial_002 train e015:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.39it/s, avg=0.09332, loss=0.09258]

trial_002 train e015:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:21,  1.39it/s, avg=0.09293, loss=0.07887]

trial_002 train e015:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:21,  1.38it/s, avg=0.09293, loss=0.07887]

trial_002 train e015:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:21,  1.38it/s, avg=0.09321, loss=0.10346]

trial_002 train e015:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.38it/s, avg=0.09321, loss=0.10346]

trial_002 train e015:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:20,  1.38it/s, avg=0.09313, loss=0.09008]

trial_002 train e015:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:19,  1.38it/s, avg=0.09313, loss=0.09008]

trial_002 train e015:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:19,  1.38it/s, avg=0.09327, loss=0.09878]

trial_002 train e015:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.38it/s, avg=0.09327, loss=0.09878]

trial_002 train e015:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:18,  1.38it/s, avg=0.09310, loss=0.08654]

trial_002 train e015:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.40it/s, avg=0.09310, loss=0.08654]

trial_002 train e015:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.40it/s, avg=0.09310, loss=0.09284]

trial_002 train e015:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.09310, loss=0.09284]

trial_002 train e015:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:17,  1.38it/s, avg=0.09296, loss=0.08702]

trial_002 train e015:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:17,  1.37it/s, avg=0.09296, loss=0.08702]

trial_002 train e015:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:17,  1.37it/s, avg=0.09302, loss=0.09585]

trial_002 train e015:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:17,  1.36it/s, avg=0.09302, loss=0.09585]

trial_002 train e015:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:17,  1.36it/s, avg=0.09273, loss=0.07975]

trial_002 train e015:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:16,  1.36it/s, avg=0.09273, loss=0.07975]

trial_002 train e015:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:16,  1.36it/s, avg=0.09284, loss=0.09775]

trial_002 train e015:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.38it/s, avg=0.09284, loss=0.09775]

trial_002 train e015:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:14,  1.38it/s, avg=0.09302, loss=0.10149]

trial_002 train e015:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:13,  1.39it/s, avg=0.09302, loss=0.10149]

trial_002 train e015:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:13,  1.39it/s, avg=0.09285, loss=0.08466]

trial_002 train e015:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.36it/s, avg=0.09285, loss=0.08466]

trial_002 train e015:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.36it/s, avg=0.09303, loss=0.10174]

trial_002 train e015:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:13,  1.36it/s, avg=0.09303, loss=0.10174]

trial_002 train e015:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:13,  1.36it/s, avg=0.09288, loss=0.08561]

trial_002 train e015:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:12,  1.37it/s, avg=0.09288, loss=0.08561]

trial_002 train e015:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:12,  1.37it/s, avg=0.09298, loss=0.09783]

trial_002 train e015:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.38it/s, avg=0.09298, loss=0.09783]

trial_002 train e015:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:10,  1.38it/s, avg=0.09269, loss=0.07819]

trial_002 train e015:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.09269, loss=0.07819]

trial_002 train e015:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.09265, loss=0.09057]

trial_002 train e015:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:09,  1.38it/s, avg=0.09265, loss=0.09057]

trial_002 train e015:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:09,  1.38it/s, avg=0.09274, loss=0.09735]

trial_002 train e015:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:08,  1.39it/s, avg=0.09274, loss=0.09735]

trial_002 train e015:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:08,  1.39it/s, avg=0.09260, loss=0.08524]

trial_002 train e015:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:09,  1.36it/s, avg=0.09260, loss=0.08524]

trial_002 train e015:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:09,  1.36it/s, avg=0.09252, loss=0.08797]

trial_002 train e015:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.37it/s, avg=0.09252, loss=0.08797]

trial_002 train e015:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:07,  1.37it/s, avg=0.09263, loss=0.09902]

trial_002 train e015:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:06,  1.39it/s, avg=0.09263, loss=0.09902]

trial_002 train e015:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:06,  1.39it/s, avg=0.09276, loss=0.09962]

trial_002 train e015:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09276, loss=0.09962]

trial_002 train e015:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:06,  1.37it/s, avg=0.09286, loss=0.09909]

trial_002 train e015:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09286, loss=0.09909]

trial_002 train e015:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09304, loss=0.10354]

trial_002 train e015:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:05,  1.36it/s, avg=0.09304, loss=0.10354]

trial_002 train e015:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.36it/s, avg=0.09339, loss=0.11411]

trial_002 train e015:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:03,  1.39it/s, avg=0.09339, loss=0.11411]

trial_002 train e015:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:03,  1.39it/s, avg=0.09336, loss=0.09182]

trial_002 train e015:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:02,  1.39it/s, avg=0.09336, loss=0.09182]

trial_002 train e015:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:02,  1.39it/s, avg=0.09334, loss=0.09224]

trial_002 train e015:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.39it/s, avg=0.09334, loss=0.09224]

trial_002 train e015:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.39it/s, avg=0.09327, loss=0.08887]

trial_002 train e015:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.38it/s, avg=0.09327, loss=0.08887]

trial_002 train e015:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:01,  1.38it/s, avg=0.09334, loss=0.09740]

trial_002 train e015:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<00:59,  1.40it/s, avg=0.09334, loss=0.09740]

trial_002 train e015:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<00:59,  1.40it/s, avg=0.09303, loss=0.07324]

trial_002 train e015:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:59,  1.38it/s, avg=0.09303, loss=0.07324]

trial_002 train e015:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:59,  1.38it/s, avg=0.09298, loss=0.08953]

trial_002 train e015:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.41it/s, avg=0.09298, loss=0.08953]

trial_002 train e015:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.41it/s, avg=0.09314, loss=0.10385]

trial_002 train e015:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:58,  1.37it/s, avg=0.09314, loss=0.10385]

trial_002 train e015:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:58,  1.37it/s, avg=0.09324, loss=0.09995]

trial_002 train e015:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:58,  1.36it/s, avg=0.09324, loss=0.09995]

trial_002 train e015:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.36it/s, avg=0.09327, loss=0.09568]

trial_002 train e015:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.38it/s, avg=0.09327, loss=0.09568]

trial_002 train e015:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.38it/s, avg=0.09340, loss=0.10199]

trial_002 train e015:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:55,  1.41it/s, avg=0.09340, loss=0.10199]

trial_002 train e015:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:55,  1.41it/s, avg=0.09366, loss=0.11213]

trial_002 train e015:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:54,  1.40it/s, avg=0.09366, loss=0.11213]

trial_002 train e015:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:54,  1.40it/s, avg=0.09369, loss=0.09599]

trial_002 train e015:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:53,  1.41it/s, avg=0.09369, loss=0.09599]

trial_002 train e015:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:53,  1.41it/s, avg=0.09374, loss=0.09765]

trial_002 train e015:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.40it/s, avg=0.09374, loss=0.09765]

trial_002 train e015:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:53,  1.40it/s, avg=0.09364, loss=0.08629]

trial_002 train e015:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.38it/s, avg=0.09364, loss=0.08629]

trial_002 train e015:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:53,  1.38it/s, avg=0.09349, loss=0.08244]

trial_002 train e015:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:53,  1.37it/s, avg=0.09349, loss=0.08244]

trial_002 train e015:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:53,  1.37it/s, avg=0.09343, loss=0.08857]

trial_002 train e015:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:53,  1.35it/s, avg=0.09343, loss=0.08857]

trial_002 train e015:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:53,  1.35it/s, avg=0.09343, loss=0.09329]

trial_002 train e015:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:52,  1.36it/s, avg=0.09343, loss=0.09329]

trial_002 train e015:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:52,  1.36it/s, avg=0.09344, loss=0.09441]

trial_002 train e015:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:51,  1.35it/s, avg=0.09344, loss=0.09441]

trial_002 train e015:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:51,  1.35it/s, avg=0.09343, loss=0.09274]

trial_002 train e015:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:52,  1.32it/s, avg=0.09343, loss=0.09274]

trial_002 train e015:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:52,  1.32it/s, avg=0.09341, loss=0.09197]

trial_002 train e015:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:52,  1.28it/s, avg=0.09341, loss=0.09197]

trial_002 train e015:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:52,  1.28it/s, avg=0.09338, loss=0.09093]

trial_002 train e015:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:51,  1.29it/s, avg=0.09338, loss=0.09093]

trial_002 train e015:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:51,  1.29it/s, avg=0.09341, loss=0.09574]

trial_002 train e015:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:50,  1.30it/s, avg=0.09341, loss=0.09574]

trial_002 train e015:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:50,  1.30it/s, avg=0.09345, loss=0.09626]

trial_002 train e015:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:49,  1.31it/s, avg=0.09345, loss=0.09626]

trial_002 train e015:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:49,  1.31it/s, avg=0.09352, loss=0.09955]

trial_002 train e015:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:49,  1.29it/s, avg=0.09352, loss=0.09955]

trial_002 train e015:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:49,  1.29it/s, avg=0.09362, loss=0.10252]

trial_002 train e015:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:47,  1.32it/s, avg=0.09362, loss=0.10252]

trial_002 train e015:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:47,  1.32it/s, avg=0.09363, loss=0.09417]

trial_002 train e015:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:45,  1.36it/s, avg=0.09363, loss=0.09417]

trial_002 train e015:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:45,  1.36it/s, avg=0.09362, loss=0.09312]

trial_002 train e015:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:45,  1.35it/s, avg=0.09362, loss=0.09312]

trial_002 train e015:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:45,  1.35it/s, avg=0.09345, loss=0.07860]

trial_002 train e015:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.34it/s, avg=0.09345, loss=0.07860]

trial_002 train e015:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:44,  1.34it/s, avg=0.09341, loss=0.08932]

trial_002 train e015:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:44,  1.32it/s, avg=0.09341, loss=0.08932]

trial_002 train e015:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:44,  1.32it/s, avg=0.09325, loss=0.07937]

trial_002 train e015:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:44,  1.31it/s, avg=0.09325, loss=0.07937]

trial_002 train e015:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:44,  1.31it/s, avg=0.09323, loss=0.09129]

trial_002 train e015:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:43,  1.31it/s, avg=0.09323, loss=0.09129]

trial_002 train e015:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:43,  1.31it/s, avg=0.09324, loss=0.09365]

trial_002 train e015:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:42,  1.33it/s, avg=0.09324, loss=0.09365]

trial_002 train e015:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:42,  1.33it/s, avg=0.09329, loss=0.09808]

trial_002 train e015:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:41,  1.33it/s, avg=0.09329, loss=0.09808]

trial_002 train e015:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:41,  1.33it/s, avg=0.09337, loss=0.10115]

trial_002 train e015:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:40,  1.34it/s, avg=0.09337, loss=0.10115]

trial_002 train e015:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:40,  1.34it/s, avg=0.09352, loss=0.10735]

trial_002 train e015:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:39,  1.33it/s, avg=0.09352, loss=0.10735]

trial_002 train e015:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:39,  1.33it/s, avg=0.09348, loss=0.08986]

trial_002 train e015:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:38,  1.35it/s, avg=0.09348, loss=0.08986]

trial_002 train e015:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:12<00:38,  1.35it/s, avg=0.09345, loss=0.09093]

trial_002 train e015:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.36it/s, avg=0.09345, loss=0.09093]

trial_002 train e015:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.36it/s, avg=0.09333, loss=0.08106]

trial_002 train e015:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.36it/s, avg=0.09333, loss=0.08106]

trial_002 train e015:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.36it/s, avg=0.09341, loss=0.10098]

trial_002 train e015:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.36it/s, avg=0.09341, loss=0.10098]

trial_002 train e015:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:35,  1.36it/s, avg=0.09333, loss=0.08551]

trial_002 train e015:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:34,  1.37it/s, avg=0.09333, loss=0.08551]

trial_002 train e015:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:34,  1.37it/s, avg=0.09351, loss=0.11154]

trial_002 train e015:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:33,  1.40it/s, avg=0.09351, loss=0.11154]

trial_002 train e015:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:33,  1.40it/s, avg=0.09344, loss=0.08656]

trial_002 train e015:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:34,  1.35it/s, avg=0.09344, loss=0.08656]

trial_002 train e015:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:34,  1.35it/s, avg=0.09339, loss=0.08816]

trial_002 train e015:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:33,  1.35it/s, avg=0.09339, loss=0.08816]

trial_002 train e015:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:33,  1.35it/s, avg=0.09335, loss=0.08964]

trial_002 train e015:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:31,  1.39it/s, avg=0.09335, loss=0.08964]

trial_002 train e015:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:31,  1.39it/s, avg=0.09330, loss=0.08749]

trial_002 train e015:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.36it/s, avg=0.09330, loss=0.08749]

trial_002 train e015:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:31,  1.36it/s, avg=0.09346, loss=0.11061]

trial_002 train e015:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.37it/s, avg=0.09346, loss=0.11061]

trial_002 train e015:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:30,  1.37it/s, avg=0.09347, loss=0.09492]

trial_002 train e015:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.35it/s, avg=0.09347, loss=0.09492]

trial_002 train e015:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:20<00:30,  1.35it/s, avg=0.09346, loss=0.09272]

trial_002 train e015:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:29,  1.36it/s, avg=0.09346, loss=0.09272]

trial_002 train e015:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:29,  1.36it/s, avg=0.09335, loss=0.08074]

trial_002 train e015:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:29,  1.34it/s, avg=0.09335, loss=0.08074]

trial_002 train e015:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:29,  1.34it/s, avg=0.09328, loss=0.08573]

trial_002 train e015:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:28,  1.33it/s, avg=0.09328, loss=0.08573]

trial_002 train e015:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:28,  1.33it/s, avg=0.09330, loss=0.09575]

trial_002 train e015:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:27,  1.35it/s, avg=0.09330, loss=0.09575]

trial_002 train e015:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:23<00:27,  1.35it/s, avg=0.09331, loss=0.09403]

trial_002 train e015:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.35it/s, avg=0.09331, loss=0.09403]

trial_002 train e015:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.35it/s, avg=0.09327, loss=0.08861]

trial_002 train e015:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.36it/s, avg=0.09327, loss=0.08861]

trial_002 train e015:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.36it/s, avg=0.09331, loss=0.09824]

trial_002 train e015:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:25,  1.34it/s, avg=0.09331, loss=0.09824]

trial_002 train e015:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:25<00:25,  1.34it/s, avg=0.09339, loss=0.10210]

trial_002 train e015:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.36it/s, avg=0.09339, loss=0.10210]

trial_002 train e015:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.36it/s, avg=0.09345, loss=0.10105]

trial_002 train e015:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:22,  1.40it/s, avg=0.09345, loss=0.10105]

trial_002 train e015:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:22,  1.40it/s, avg=0.09350, loss=0.09852]

trial_002 train e015:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.38it/s, avg=0.09350, loss=0.09852]

trial_002 train e015:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:22,  1.38it/s, avg=0.09346, loss=0.08908]

trial_002 train e015:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.37it/s, avg=0.09346, loss=0.08908]

trial_002 train e015:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:28<00:21,  1.37it/s, avg=0.09350, loss=0.09831]

trial_002 train e015:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.38it/s, avg=0.09350, loss=0.09831]

trial_002 train e015:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.38it/s, avg=0.09342, loss=0.08368]

trial_002 train e015:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.37it/s, avg=0.09342, loss=0.08368]

trial_002 train e015:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.37it/s, avg=0.09339, loss=0.09009]

trial_002 train e015:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.37it/s, avg=0.09339, loss=0.09009]

trial_002 train e015:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:19,  1.37it/s, avg=0.09343, loss=0.09829]

trial_002 train e015:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:18,  1.37it/s, avg=0.09343, loss=0.09829]

trial_002 train e015:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:31<00:18,  1.37it/s, avg=0.09348, loss=0.09996]

trial_002 train e015:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:17,  1.39it/s, avg=0.09348, loss=0.09996]

trial_002 train e015:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:17,  1.39it/s, avg=0.09352, loss=0.09872]

trial_002 train e015:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:16,  1.41it/s, avg=0.09352, loss=0.09872]

trial_002 train e015:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:16,  1.41it/s, avg=0.09355, loss=0.09735]

trial_002 train e015:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.38it/s, avg=0.09355, loss=0.09735]

trial_002 train e015:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:16,  1.38it/s, avg=0.09352, loss=0.08897]

trial_002 train e015:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.36it/s, avg=0.09352, loss=0.08897]

trial_002 train e015:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:34<00:16,  1.36it/s, avg=0.09361, loss=0.10525]

trial_002 train e015:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.36it/s, avg=0.09361, loss=0.10525]

trial_002 train e015:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.36it/s, avg=0.09368, loss=0.10236]

trial_002 train e015:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.41it/s, avg=0.09368, loss=0.10236]

trial_002 train e015:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.41it/s, avg=0.09363, loss=0.08729]

trial_002 train e015:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.43it/s, avg=0.09363, loss=0.08729]

trial_002 train e015:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:13,  1.43it/s, avg=0.09361, loss=0.09139]

trial_002 train e015:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:12,  1.43it/s, avg=0.09361, loss=0.09139]

trial_002 train e015:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:12,  1.43it/s, avg=0.09359, loss=0.09117]

trial_002 train e015:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.41it/s, avg=0.09359, loss=0.09117]

trial_002 train e015:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.41it/s, avg=0.09365, loss=0.10165]

trial_002 train e015:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.41it/s, avg=0.09365, loss=0.10165]

trial_002 train e015:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:11,  1.41it/s, avg=0.09367, loss=0.09528]

trial_002 train e015:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.39it/s, avg=0.09367, loss=0.09528]

trial_002 train e015:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.39it/s, avg=0.09366, loss=0.09231]

trial_002 train e015:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.37it/s, avg=0.09366, loss=0.09231]

trial_002 train e015:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.37it/s, avg=0.09361, loss=0.08692]

trial_002 train e015:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.36it/s, avg=0.09361, loss=0.08692]

trial_002 train e015:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.36it/s, avg=0.09354, loss=0.08495]

trial_002 train e015:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.38it/s, avg=0.09354, loss=0.08495]

trial_002 train e015:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:41<00:08,  1.38it/s, avg=0.09351, loss=0.08954]

trial_002 train e015:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:07,  1.39it/s, avg=0.09351, loss=0.08954]

trial_002 train e015:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:07,  1.39it/s, avg=0.09347, loss=0.08685]

trial_002 train e015:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.38it/s, avg=0.09347, loss=0.08685]

trial_002 train e015:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.38it/s, avg=0.09341, loss=0.08589]

trial_002 train e015:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.37it/s, avg=0.09341, loss=0.08589]

trial_002 train e015:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.37it/s, avg=0.09351, loss=0.10716]

trial_002 train e015:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.41it/s, avg=0.09351, loss=0.10716]

trial_002 train e015:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:44<00:05,  1.41it/s, avg=0.09353, loss=0.09635]

trial_002 train e015:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.39it/s, avg=0.09353, loss=0.09635]

trial_002 train e015:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.39it/s, avg=0.09348, loss=0.08684]

trial_002 train e015:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.39it/s, avg=0.09348, loss=0.08684]

trial_002 train e015:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.39it/s, avg=0.09354, loss=0.10099]

trial_002 train e015:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.36it/s, avg=0.09354, loss=0.10099]

trial_002 train e015:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:46<00:03,  1.36it/s, avg=0.09350, loss=0.08820]

trial_002 train e015:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.38it/s, avg=0.09350, loss=0.08820]

trial_002 train e015:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.38it/s, avg=0.09352, loss=0.09722]

trial_002 train e015:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.38it/s, avg=0.09352, loss=0.09722]

trial_002 train e015:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.38it/s, avg=0.09357, loss=0.10099]

trial_002 train e015:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.35it/s, avg=0.09357, loss=0.10099]

trial_002 train e015:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.35it/s, avg=0.09360, loss=0.09786]

trial_002 train e015:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.35it/s, avg=0.09360, loss=0.09786]

trial_002 train e015:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.35it/s, avg=0.09360, loss=0.09107]

trial_002 train e015: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.60it/s, avg=0.09360, loss=0.09107]

trial_002 val e015:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e015:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.34it/s]

trial_002 val e015:   4%|█████                                                                                                                        | 2/50 [00:00<00:20,  2.38it/s]

trial_002 val e015:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.41it/s]

trial_002 val e015:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.43it/s]

trial_002 val e015:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.43it/s]

trial_002 val e015:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.43it/s]

trial_002 val e015:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.42it/s]

trial_002 val e015:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.41it/s]

trial_002 val e015:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.42it/s]

trial_002 val e015:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.44it/s]

trial_002 val e015:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.44it/s]

trial_002 val e015:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.46it/s]

trial_002 val e015:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.46it/s]

trial_002 val e015:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.42it/s]

trial_002 val e015:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.39it/s]

trial_002 val e015:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.41it/s]

trial_002 val e015:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.39it/s]

trial_002 val e015:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.41it/s]

trial_002 val e015:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.42it/s]

trial_002 val e015:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.43it/s]

trial_002 val e015:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.43it/s]

trial_002 val e015:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.44it/s]

trial_002 val e015:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.45it/s]

trial_002 val e015:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.46it/s]

trial_002 val e015:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.45it/s]

trial_002 val e015:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.38it/s]

trial_002 val e015:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.37it/s]

trial_002 val e015:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.38it/s]

trial_002 val e015:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:09,  2.32it/s]

trial_002 val e015:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.34it/s]

trial_002 val e015:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:08,  2.35it/s]

trial_002 val e015:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.37it/s]

trial_002 val e015:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.40it/s]

trial_002 val e015:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.42it/s]

trial_002 val e015:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.40it/s]

trial_002 val e015:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.42it/s]

trial_002 val e015:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.43it/s]

trial_002 val e015:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.44it/s]

trial_002 val e015:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.45it/s]

trial_002 val e015:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.43it/s]

trial_002 val e015:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.40it/s]

trial_002 val e015:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.40it/s]

trial_002 val e015:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.41it/s]

trial_002 val e015:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.43it/s]

trial_002 val e015:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.45it/s]

trial_002 val e015:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.45it/s]

trial_002 val e015:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.46it/s]

trial_002 val e015:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.46it/s]

trial_002 val e015:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.48it/s]

trial_002 val e015: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.50it/s]

[2026-05-28 20:56:27] [trial_002] epoch=015 | train_loss=0.093597 | val_MAE=0.098438 | val_S=0.901562 | best_S=0.902131 @epoch=14 | patience=1/5

[trial_002] epochs:  15%|██████████████████                                                                                                      | 15/100 [32:51<3:03:27, 129.50s/it]

trial_002 train e016:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e016:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09596, loss=0.09596]

trial_002 train e016:   1%|▋                                                                                              | 1/149 [00:00<01:50,  1.34it/s, avg=0.09596, loss=0.09596]

trial_002 train e016:   1%|▋                                                                                              | 1/149 [00:01<01:50,  1.34it/s, avg=0.09630, loss=0.09665]

trial_002 train e016:   1%|█▎                                                                                             | 2/149 [00:01<01:51,  1.32it/s, avg=0.09630, loss=0.09665]

trial_002 train e016:   1%|█▎                                                                                             | 2/149 [00:02<01:51,  1.32it/s, avg=0.09234, loss=0.08441]

trial_002 train e016:   2%|█▉                                                                                             | 3/149 [00:02<01:48,  1.35it/s, avg=0.09234, loss=0.08441]

trial_002 train e016:   2%|█▉                                                                                             | 3/149 [00:02<01:48,  1.35it/s, avg=0.09149, loss=0.08893]

trial_002 train e016:   3%|██▌                                                                                            | 4/149 [00:02<01:46,  1.36it/s, avg=0.09149, loss=0.08893]

trial_002 train e016:   3%|██▌                                                                                            | 4/149 [00:03<01:46,  1.36it/s, avg=0.09231, loss=0.09562]

trial_002 train e016:   3%|███▏                                                                                           | 5/149 [00:03<01:45,  1.37it/s, avg=0.09231, loss=0.09562]

trial_002 train e016:   3%|███▏                                                                                           | 5/149 [00:04<01:45,  1.37it/s, avg=0.09173, loss=0.08880]

trial_002 train e016:   4%|███▊                                                                                           | 6/149 [00:04<01:44,  1.37it/s, avg=0.09173, loss=0.08880]

trial_002 train e016:   4%|███▊                                                                                           | 6/149 [00:05<01:44,  1.37it/s, avg=0.09279, loss=0.09915]

trial_002 train e016:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.39it/s, avg=0.09279, loss=0.09915]

trial_002 train e016:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.39it/s, avg=0.09238, loss=0.08949]

trial_002 train e016:   5%|█████                                                                                          | 8/149 [00:05<01:43,  1.36it/s, avg=0.09238, loss=0.08949]

trial_002 train e016:   5%|█████                                                                                          | 8/149 [00:06<01:43,  1.36it/s, avg=0.09203, loss=0.08927]

trial_002 train e016:   6%|█████▋                                                                                         | 9/149 [00:06<01:42,  1.37it/s, avg=0.09203, loss=0.08927]

trial_002 train e016:   6%|█████▋                                                                                         | 9/149 [00:07<01:42,  1.37it/s, avg=0.09269, loss=0.09857]

trial_002 train e016:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.35it/s, avg=0.09269, loss=0.09857]

trial_002 train e016:   7%|██████▎                                                                                       | 10/149 [00:08<01:42,  1.35it/s, avg=0.09231, loss=0.08858]

trial_002 train e016:   7%|██████▉                                                                                       | 11/149 [00:08<01:41,  1.36it/s, avg=0.09231, loss=0.08858]

trial_002 train e016:   7%|██████▉                                                                                       | 11/149 [00:08<01:41,  1.36it/s, avg=0.09206, loss=0.08933]

trial_002 train e016:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.36it/s, avg=0.09206, loss=0.08933]

trial_002 train e016:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.36it/s, avg=0.09300, loss=0.10424]

trial_002 train e016:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.09300, loss=0.10424]

trial_002 train e016:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.09441, loss=0.11280]

trial_002 train e016:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.09441, loss=0.11280]

trial_002 train e016:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.09319, loss=0.07610]

trial_002 train e016:  10%|█████████▍                                                                                    | 15/149 [00:10<01:37,  1.37it/s, avg=0.09319, loss=0.07610]

trial_002 train e016:  10%|█████████▍                                                                                    | 15/149 [00:11<01:37,  1.37it/s, avg=0.09351, loss=0.09823]

trial_002 train e016:  11%|██████████                                                                                    | 16/149 [00:11<01:38,  1.36it/s, avg=0.09351, loss=0.09823]

trial_002 train e016:  11%|██████████                                                                                    | 16/149 [00:12<01:38,  1.36it/s, avg=0.09337, loss=0.09110]

trial_002 train e016:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.39it/s, avg=0.09337, loss=0.09110]

trial_002 train e016:  11%|██████████▋                                                                                   | 17/149 [00:13<01:35,  1.39it/s, avg=0.09330, loss=0.09221]

trial_002 train e016:  12%|███████████▎                                                                                  | 18/149 [00:13<01:34,  1.38it/s, avg=0.09330, loss=0.09221]

trial_002 train e016:  12%|███████████▎                                                                                  | 18/149 [00:13<01:34,  1.38it/s, avg=0.09356, loss=0.09813]

trial_002 train e016:  13%|███████████▉                                                                                  | 19/149 [00:13<01:35,  1.36it/s, avg=0.09356, loss=0.09813]

trial_002 train e016:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.36it/s, avg=0.09359, loss=0.09413]

trial_002 train e016:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.37it/s, avg=0.09359, loss=0.09413]

trial_002 train e016:  13%|████████████▌                                                                                 | 20/149 [00:15<01:33,  1.37it/s, avg=0.09384, loss=0.09887]

trial_002 train e016:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.39it/s, avg=0.09384, loss=0.09887]

trial_002 train e016:  14%|█████████████▏                                                                                | 21/149 [00:16<01:32,  1.39it/s, avg=0.09324, loss=0.08069]

trial_002 train e016:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.39it/s, avg=0.09324, loss=0.08069]

trial_002 train e016:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.39it/s, avg=0.09337, loss=0.09613]

trial_002 train e016:  15%|██████████████▌                                                                               | 23/149 [00:16<01:30,  1.39it/s, avg=0.09337, loss=0.09613]

trial_002 train e016:  15%|██████████████▌                                                                               | 23/149 [00:17<01:30,  1.39it/s, avg=0.09342, loss=0.09458]

trial_002 train e016:  16%|███████████████▏                                                                              | 24/149 [00:17<01:29,  1.40it/s, avg=0.09342, loss=0.09458]

trial_002 train e016:  16%|███████████████▏                                                                              | 24/149 [00:18<01:29,  1.40it/s, avg=0.09343, loss=0.09380]

trial_002 train e016:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.40it/s, avg=0.09343, loss=0.09380]

trial_002 train e016:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.40it/s, avg=0.09327, loss=0.08914]

trial_002 train e016:  17%|████████████████▍                                                                             | 26/149 [00:18<01:27,  1.41it/s, avg=0.09327, loss=0.08914]

trial_002 train e016:  17%|████████████████▍                                                                             | 26/149 [00:19<01:27,  1.41it/s, avg=0.09297, loss=0.08539]

trial_002 train e016:  18%|█████████████████                                                                             | 27/149 [00:19<01:28,  1.38it/s, avg=0.09297, loss=0.08539]

trial_002 train e016:  18%|█████████████████                                                                             | 27/149 [00:20<01:28,  1.38it/s, avg=0.09280, loss=0.08796]

trial_002 train e016:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:26,  1.39it/s, avg=0.09280, loss=0.08796]

trial_002 train e016:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:26,  1.39it/s, avg=0.09295, loss=0.09726]

trial_002 train e016:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.09295, loss=0.09726]

trial_002 train e016:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.09287, loss=0.09071]

trial_002 train e016:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:26,  1.37it/s, avg=0.09287, loss=0.09071]

trial_002 train e016:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:26,  1.37it/s, avg=0.09310, loss=0.09985]

trial_002 train e016:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:26,  1.36it/s, avg=0.09310, loss=0.09985]

trial_002 train e016:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.36it/s, avg=0.09285, loss=0.08520]

trial_002 train e016:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.36it/s, avg=0.09285, loss=0.08520]

trial_002 train e016:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:26,  1.36it/s, avg=0.09318, loss=0.10372]

trial_002 train e016:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.09318, loss=0.10372]

trial_002 train e016:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.09297, loss=0.08610]

trial_002 train e016:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.09297, loss=0.08610]

trial_002 train e016:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.09297, loss=0.09282]

trial_002 train e016:  23%|██████████████████████                                                                        | 35/149 [00:25<01:24,  1.35it/s, avg=0.09297, loss=0.09282]

trial_002 train e016:  23%|██████████████████████                                                                        | 35/149 [00:26<01:24,  1.35it/s, avg=0.09286, loss=0.08909]

trial_002 train e016:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:24,  1.34it/s, avg=0.09286, loss=0.08909]

trial_002 train e016:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:24,  1.34it/s, avg=0.09284, loss=0.09190]

trial_002 train e016:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:23,  1.35it/s, avg=0.09284, loss=0.09190]

trial_002 train e016:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:23,  1.35it/s, avg=0.09279, loss=0.09118]

trial_002 train e016:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:21,  1.36it/s, avg=0.09279, loss=0.09118]

trial_002 train e016:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:21,  1.36it/s, avg=0.09255, loss=0.08326]

trial_002 train e016:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:20,  1.37it/s, avg=0.09255, loss=0.08326]

trial_002 train e016:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:20,  1.37it/s, avg=0.09258, loss=0.09374]

trial_002 train e016:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.37it/s, avg=0.09258, loss=0.09374]

trial_002 train e016:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.37it/s, avg=0.09228, loss=0.08021]

trial_002 train e016:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:16,  1.41it/s, avg=0.09228, loss=0.08021]

trial_002 train e016:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:16,  1.41it/s, avg=0.09284, loss=0.11579]

trial_002 train e016:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:16,  1.39it/s, avg=0.09284, loss=0.11579]

trial_002 train e016:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:16,  1.39it/s, avg=0.09291, loss=0.09602]

trial_002 train e016:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.41it/s, avg=0.09291, loss=0.09602]

trial_002 train e016:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.41it/s, avg=0.09287, loss=0.09098]

trial_002 train e016:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:15,  1.39it/s, avg=0.09287, loss=0.09098]

trial_002 train e016:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:15,  1.39it/s, avg=0.09292, loss=0.09553]

trial_002 train e016:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:15,  1.38it/s, avg=0.09292, loss=0.09553]

trial_002 train e016:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:15,  1.38it/s, avg=0.09323, loss=0.10703]

trial_002 train e016:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:13,  1.41it/s, avg=0.09323, loss=0.10703]

trial_002 train e016:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:13,  1.41it/s, avg=0.09303, loss=0.08387]

trial_002 train e016:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:14,  1.37it/s, avg=0.09303, loss=0.08387]

trial_002 train e016:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:14,  1.37it/s, avg=0.09283, loss=0.08344]

trial_002 train e016:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:14,  1.35it/s, avg=0.09283, loss=0.08344]

trial_002 train e016:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:14,  1.35it/s, avg=0.09306, loss=0.10383]

trial_002 train e016:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.38it/s, avg=0.09306, loss=0.10383]

trial_002 train e016:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:12,  1.38it/s, avg=0.09290, loss=0.08531]

trial_002 train e016:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:12,  1.36it/s, avg=0.09290, loss=0.08531]

trial_002 train e016:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:12,  1.36it/s, avg=0.09286, loss=0.09068]

trial_002 train e016:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.39it/s, avg=0.09286, loss=0.09068]

trial_002 train e016:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.39it/s, avg=0.09289, loss=0.09464]

trial_002 train e016:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:11,  1.36it/s, avg=0.09289, loss=0.09464]

trial_002 train e016:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:11,  1.36it/s, avg=0.09299, loss=0.09799]

trial_002 train e016:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.09299, loss=0.09799]

trial_002 train e016:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.36it/s, avg=0.09307, loss=0.09714]

trial_002 train e016:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:09,  1.36it/s, avg=0.09307, loss=0.09714]

trial_002 train e016:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:09,  1.36it/s, avg=0.09287, loss=0.08244]

trial_002 train e016:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:10,  1.34it/s, avg=0.09287, loss=0.08244]

trial_002 train e016:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:10,  1.34it/s, avg=0.09267, loss=0.08170]

trial_002 train e016:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:10,  1.32it/s, avg=0.09267, loss=0.08170]

trial_002 train e016:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:10,  1.32it/s, avg=0.09263, loss=0.09050]

trial_002 train e016:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:09,  1.33it/s, avg=0.09263, loss=0.09050]

trial_002 train e016:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:09,  1.33it/s, avg=0.09280, loss=0.10198]

trial_002 train e016:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09280, loss=0.10198]

trial_002 train e016:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:06,  1.37it/s, avg=0.09277, loss=0.09098]

trial_002 train e016:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09277, loss=0.09098]

trial_002 train e016:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:06,  1.36it/s, avg=0.09287, loss=0.09904]

trial_002 train e016:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:05,  1.36it/s, avg=0.09287, loss=0.09904]

trial_002 train e016:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:05,  1.36it/s, avg=0.09308, loss=0.10576]

trial_002 train e016:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:03,  1.38it/s, avg=0.09308, loss=0.10576]

trial_002 train e016:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:03,  1.38it/s, avg=0.09306, loss=0.09174]

trial_002 train e016:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:02,  1.39it/s, avg=0.09306, loss=0.09174]

trial_002 train e016:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:02,  1.39it/s, avg=0.09302, loss=0.09069]

trial_002 train e016:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:02,  1.38it/s, avg=0.09302, loss=0.09069]

trial_002 train e016:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:02,  1.38it/s, avg=0.09295, loss=0.08837]

trial_002 train e016:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.38it/s, avg=0.09295, loss=0.08837]

trial_002 train e016:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:01,  1.38it/s, avg=0.09281, loss=0.08380]

trial_002 train e016:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.40it/s, avg=0.09281, loss=0.08380]

trial_002 train e016:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:00,  1.40it/s, avg=0.09291, loss=0.09970]

trial_002 train e016:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:00,  1.38it/s, avg=0.09291, loss=0.09970]

trial_002 train e016:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:00,  1.38it/s, avg=0.09302, loss=0.10039]

trial_002 train e016:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<01:00,  1.37it/s, avg=0.09302, loss=0.10039]

trial_002 train e016:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<01:00,  1.37it/s, avg=0.09304, loss=0.09397]

trial_002 train e016:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:59,  1.36it/s, avg=0.09304, loss=0.09397]

trial_002 train e016:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:59,  1.36it/s, avg=0.09304, loss=0.09293]

trial_002 train e016:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:59,  1.35it/s, avg=0.09304, loss=0.09293]

trial_002 train e016:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:59,  1.35it/s, avg=0.09293, loss=0.08522]

trial_002 train e016:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.35it/s, avg=0.09293, loss=0.08522]

trial_002 train e016:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.35it/s, avg=0.09295, loss=0.09461]

trial_002 train e016:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:57,  1.36it/s, avg=0.09295, loss=0.09461]

trial_002 train e016:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.36it/s, avg=0.09290, loss=0.08910]

trial_002 train e016:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:57,  1.33it/s, avg=0.09290, loss=0.08910]

trial_002 train e016:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:57,  1.33it/s, avg=0.09286, loss=0.09062]

trial_002 train e016:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:56,  1.34it/s, avg=0.09286, loss=0.09062]

trial_002 train e016:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:56,  1.34it/s, avg=0.09276, loss=0.08531]

trial_002 train e016:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:56,  1.33it/s, avg=0.09276, loss=0.08531]

trial_002 train e016:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:56,  1.33it/s, avg=0.09264, loss=0.08333]

trial_002 train e016:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:55,  1.32it/s, avg=0.09264, loss=0.08333]

trial_002 train e016:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:55,  1.32it/s, avg=0.09291, loss=0.11352]

trial_002 train e016:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:53,  1.35it/s, avg=0.09291, loss=0.11352]

trial_002 train e016:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:53,  1.35it/s, avg=0.09277, loss=0.08239]

trial_002 train e016:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:53,  1.35it/s, avg=0.09277, loss=0.08239]

trial_002 train e016:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:53,  1.35it/s, avg=0.09295, loss=0.10643]

trial_002 train e016:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.37it/s, avg=0.09295, loss=0.10643]

trial_002 train e016:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.37it/s, avg=0.09305, loss=0.10067]

trial_002 train e016:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:51,  1.36it/s, avg=0.09305, loss=0.10067]

trial_002 train e016:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:51,  1.36it/s, avg=0.09295, loss=0.08555]

trial_002 train e016:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:49,  1.38it/s, avg=0.09295, loss=0.08555]

trial_002 train e016:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:49,  1.38it/s, avg=0.09295, loss=0.09260]

trial_002 train e016:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:49,  1.37it/s, avg=0.09295, loss=0.09260]

trial_002 train e016:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:49,  1.37it/s, avg=0.09312, loss=0.10674]

trial_002 train e016:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:49,  1.36it/s, avg=0.09312, loss=0.10674]

trial_002 train e016:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:49,  1.36it/s, avg=0.09321, loss=0.10069]

trial_002 train e016:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.36it/s, avg=0.09321, loss=0.10069]

trial_002 train e016:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:48,  1.36it/s, avg=0.09302, loss=0.07708]

trial_002 train e016:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:47,  1.37it/s, avg=0.09302, loss=0.07708]

trial_002 train e016:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:47,  1.37it/s, avg=0.09306, loss=0.09656]

trial_002 train e016:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:47,  1.35it/s, avg=0.09306, loss=0.09656]

trial_002 train e016:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:47,  1.35it/s, avg=0.09302, loss=0.08971]

trial_002 train e016:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:46,  1.36it/s, avg=0.09302, loss=0.08971]

trial_002 train e016:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:46,  1.36it/s, avg=0.09303, loss=0.09384]

trial_002 train e016:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:45,  1.36it/s, avg=0.09303, loss=0.09384]

trial_002 train e016:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:45,  1.36it/s, avg=0.09292, loss=0.08361]

trial_002 train e016:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:45,  1.34it/s, avg=0.09292, loss=0.08361]

trial_002 train e016:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:45,  1.34it/s, avg=0.09293, loss=0.09336]

trial_002 train e016:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:45,  1.33it/s, avg=0.09293, loss=0.09336]

trial_002 train e016:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:45,  1.33it/s, avg=0.09292, loss=0.09262]

trial_002 train e016:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.36it/s, avg=0.09292, loss=0.09262]

trial_002 train e016:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.36it/s, avg=0.09285, loss=0.08665]

trial_002 train e016:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.36it/s, avg=0.09285, loss=0.08665]

trial_002 train e016:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.36it/s, avg=0.09272, loss=0.08010]

trial_002 train e016:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:42,  1.35it/s, avg=0.09272, loss=0.08010]

trial_002 train e016:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:42,  1.35it/s, avg=0.09265, loss=0.08670]

trial_002 train e016:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.37it/s, avg=0.09265, loss=0.08670]

trial_002 train e016:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.37it/s, avg=0.09271, loss=0.09825]

trial_002 train e016:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:39,  1.38it/s, avg=0.09271, loss=0.09825]

trial_002 train e016:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.38it/s, avg=0.09268, loss=0.08932]

trial_002 train e016:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.38it/s, avg=0.09268, loss=0.08932]

trial_002 train e016:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:39,  1.38it/s, avg=0.09264, loss=0.08965]

trial_002 train e016:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.09264, loss=0.08965]

trial_002 train e016:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.09275, loss=0.10270]

trial_002 train e016:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:37,  1.39it/s, avg=0.09275, loss=0.10270]

trial_002 train e016:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:37,  1.39it/s, avg=0.09265, loss=0.08334]

trial_002 train e016:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:36,  1.39it/s, avg=0.09265, loss=0.08334]

trial_002 train e016:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:36,  1.39it/s, avg=0.09266, loss=0.09303]

trial_002 train e016:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.09266, loss=0.09303]

trial_002 train e016:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.37it/s, avg=0.09278, loss=0.10553]

trial_002 train e016:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.36it/s, avg=0.09278, loss=0.10553]

trial_002 train e016:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.36it/s, avg=0.09275, loss=0.08917]

trial_002 train e016:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.39it/s, avg=0.09275, loss=0.08917]

trial_002 train e016:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:34,  1.39it/s, avg=0.09279, loss=0.09657]

trial_002 train e016:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:33,  1.40it/s, avg=0.09279, loss=0.09657]

trial_002 train e016:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:33,  1.40it/s, avg=0.09290, loss=0.10439]

trial_002 train e016:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:32,  1.41it/s, avg=0.09290, loss=0.10439]

trial_002 train e016:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:32,  1.41it/s, avg=0.09302, loss=0.10577]

trial_002 train e016:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:32,  1.38it/s, avg=0.09302, loss=0.10577]

trial_002 train e016:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:32,  1.38it/s, avg=0.09292, loss=0.08205]

trial_002 train e016:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:31,  1.38it/s, avg=0.09292, loss=0.08205]

trial_002 train e016:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:31,  1.38it/s, avg=0.09289, loss=0.09035]

trial_002 train e016:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.35it/s, avg=0.09289, loss=0.09035]

trial_002 train e016:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:31,  1.35it/s, avg=0.09293, loss=0.09644]

trial_002 train e016:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:31,  1.34it/s, avg=0.09293, loss=0.09644]

trial_002 train e016:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:31,  1.34it/s, avg=0.09289, loss=0.08908]

trial_002 train e016:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.33it/s, avg=0.09289, loss=0.08908]

trial_002 train e016:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.33it/s, avg=0.09295, loss=0.09951]

trial_002 train e016:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:29,  1.35it/s, avg=0.09295, loss=0.09951]

trial_002 train e016:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:29,  1.35it/s, avg=0.09298, loss=0.09629]

trial_002 train e016:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.37it/s, avg=0.09298, loss=0.09629]

trial_002 train e016:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:28,  1.37it/s, avg=0.09290, loss=0.08344]

trial_002 train e016:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:28,  1.35it/s, avg=0.09290, loss=0.08344]

trial_002 train e016:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:28,  1.35it/s, avg=0.09285, loss=0.08827]

trial_002 train e016:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:27,  1.35it/s, avg=0.09285, loss=0.08827]

trial_002 train e016:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:27,  1.35it/s, avg=0.09278, loss=0.08421]

trial_002 train e016:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.36it/s, avg=0.09278, loss=0.08421]

trial_002 train e016:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.36it/s, avg=0.09264, loss=0.07722]

trial_002 train e016:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.36it/s, avg=0.09264, loss=0.07722]

trial_002 train e016:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.36it/s, avg=0.09267, loss=0.09631]

trial_002 train e016:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.37it/s, avg=0.09267, loss=0.09631]

trial_002 train e016:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:24,  1.37it/s, avg=0.09269, loss=0.09462]

trial_002 train e016:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:24,  1.37it/s, avg=0.09269, loss=0.09462]

trial_002 train e016:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.37it/s, avg=0.09281, loss=0.10668]

trial_002 train e016:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.36it/s, avg=0.09281, loss=0.10668]

trial_002 train e016:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.36it/s, avg=0.09280, loss=0.09126]

trial_002 train e016:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.39it/s, avg=0.09280, loss=0.09126]

trial_002 train e016:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.39it/s, avg=0.09286, loss=0.10043]

trial_002 train e016:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:21,  1.41it/s, avg=0.09286, loss=0.10043]

trial_002 train e016:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.41it/s, avg=0.09291, loss=0.09856]

trial_002 train e016:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:20,  1.43it/s, avg=0.09291, loss=0.09856]

trial_002 train e016:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:20,  1.43it/s, avg=0.09285, loss=0.08525]

trial_002 train e016:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.39it/s, avg=0.09285, loss=0.08525]

trial_002 train e016:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.39it/s, avg=0.09296, loss=0.10741]

trial_002 train e016:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:20,  1.34it/s, avg=0.09296, loss=0.10741]

trial_002 train e016:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:20,  1.34it/s, avg=0.09295, loss=0.09057]

trial_002 train e016:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:19,  1.33it/s, avg=0.09295, loss=0.09057]

trial_002 train e016:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.33it/s, avg=0.09293, loss=0.09155]

trial_002 train e016:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.33it/s, avg=0.09293, loss=0.09155]

trial_002 train e016:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.33it/s, avg=0.09292, loss=0.09114]

trial_002 train e016:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.36it/s, avg=0.09292, loss=0.09114]

trial_002 train e016:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.36it/s, avg=0.09284, loss=0.08295]

trial_002 train e016:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:17,  1.34it/s, avg=0.09284, loss=0.08295]

trial_002 train e016:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:17,  1.34it/s, avg=0.09293, loss=0.10393]

trial_002 train e016:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.31it/s, avg=0.09293, loss=0.10393]

trial_002 train e016:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.31it/s, avg=0.09291, loss=0.09062]

trial_002 train e016:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.33it/s, avg=0.09291, loss=0.09062]

trial_002 train e016:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.33it/s, avg=0.09279, loss=0.07790]

trial_002 train e016:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:15,  1.31it/s, avg=0.09279, loss=0.07790]

trial_002 train e016:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:15,  1.31it/s, avg=0.09291, loss=0.10752]

trial_002 train e016:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:14,  1.31it/s, avg=0.09291, loss=0.10752]

trial_002 train e016:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:14,  1.31it/s, avg=0.09299, loss=0.10433]

trial_002 train e016:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.32it/s, avg=0.09299, loss=0.10433]

trial_002 train e016:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.32it/s, avg=0.09308, loss=0.10412]

trial_002 train e016:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.32it/s, avg=0.09308, loss=0.10412]

trial_002 train e016:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.32it/s, avg=0.09305, loss=0.08883]

trial_002 train e016:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:12,  1.32it/s, avg=0.09305, loss=0.08883]

trial_002 train e016:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:12,  1.32it/s, avg=0.09298, loss=0.08476]

trial_002 train e016:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:11,  1.34it/s, avg=0.09298, loss=0.08476]

trial_002 train e016:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:39<00:11,  1.34it/s, avg=0.09298, loss=0.09295]

trial_002 train e016:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.35it/s, avg=0.09298, loss=0.09295]

trial_002 train e016:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.35it/s, avg=0.09301, loss=0.09662]

trial_002 train e016:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.34it/s, avg=0.09301, loss=0.09662]

trial_002 train e016:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.34it/s, avg=0.09305, loss=0.09856]

trial_002 train e016:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.34it/s, avg=0.09305, loss=0.09856]

trial_002 train e016:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:41<00:08,  1.34it/s, avg=0.09305, loss=0.09350]

trial_002 train e016:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.36it/s, avg=0.09305, loss=0.09350]

trial_002 train e016:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:08,  1.36it/s, avg=0.09293, loss=0.07593]

trial_002 train e016:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.35it/s, avg=0.09293, loss=0.07593]

trial_002 train e016:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.35it/s, avg=0.09279, loss=0.07351]

trial_002 train e016:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.35it/s, avg=0.09279, loss=0.07351]

trial_002 train e016:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:43<00:06,  1.35it/s, avg=0.09284, loss=0.09992]

trial_002 train e016:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.38it/s, avg=0.09284, loss=0.09992]

trial_002 train e016:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:44<00:05,  1.38it/s, avg=0.09283, loss=0.09036]

trial_002 train e016:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.39it/s, avg=0.09283, loss=0.09036]

trial_002 train e016:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.39it/s, avg=0.09282, loss=0.09137]

trial_002 train e016:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.38it/s, avg=0.09282, loss=0.09137]

trial_002 train e016:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:45<00:04,  1.38it/s, avg=0.09286, loss=0.09938]

trial_002 train e016:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.38it/s, avg=0.09286, loss=0.09938]

trial_002 train e016:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:46<00:03,  1.38it/s, avg=0.09284, loss=0.08921]

trial_002 train e016:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.36it/s, avg=0.09284, loss=0.08921]

trial_002 train e016:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:47<00:02,  1.36it/s, avg=0.09281, loss=0.08833]

trial_002 train e016:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.37it/s, avg=0.09281, loss=0.08833]

trial_002 train e016:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.37it/s, avg=0.09281, loss=0.09405]

trial_002 train e016:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.37it/s, avg=0.09281, loss=0.09405]

trial_002 train e016:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:48<00:01,  1.37it/s, avg=0.09278, loss=0.08804]

trial_002 train e016:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.39it/s, avg=0.09278, loss=0.08804]

trial_002 train e016:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.39it/s, avg=0.09274, loss=0.07795]

trial_002 train e016: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.66it/s, avg=0.09274, loss=0.07795]

trial_002 val e016:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e016:   2%|██▌                                                                                                                          | 1/50 [00:00<00:21,  2.32it/s]

trial_002 val e016:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.43it/s]

trial_002 val e016:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.46it/s]

trial_002 val e016:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.45it/s]

trial_002 val e016:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.41it/s]

trial_002 val e016:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.40it/s]

trial_002 val e016:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:18,  2.37it/s]

trial_002 val e016:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.39it/s]

trial_002 val e016:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.42it/s]

trial_002 val e016:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.44it/s]

trial_002 val e016:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.46it/s]

trial_002 val e016:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.47it/s]

trial_002 val e016:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:14,  2.48it/s]

trial_002 val e016:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.49it/s]

trial_002 val e016:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.49it/s]

trial_002 val e016:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.50it/s]

trial_002 val e016:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.46it/s]

trial_002 val e016:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.44it/s]

trial_002 val e016:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.45it/s]

trial_002 val e016:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.47it/s]

trial_002 val e016:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.48it/s]

trial_002 val e016:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:08<00:11,  2.49it/s]

trial_002 val e016:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:10,  2.48it/s]

trial_002 val e016:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.49it/s]

trial_002 val e016:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.50it/s]

trial_002 val e016:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.50it/s]

trial_002 val e016:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:10<00:09,  2.51it/s]

trial_002 val e016:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.50it/s]

trial_002 val e016:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.50it/s]

trial_002 val e016:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.50it/s]

trial_002 val e016:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.45it/s]

trial_002 val e016:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.44it/s]

trial_002 val e016:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.43it/s]

trial_002 val e016:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.44it/s]

trial_002 val e016:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.45it/s]

trial_002 val e016:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.46it/s]

trial_002 val e016:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.47it/s]

trial_002 val e016:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.47it/s]

trial_002 val e016:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.47it/s]

trial_002 val e016:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.47it/s]

trial_002 val e016:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.47it/s]

trial_002 val e016:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.47it/s]

trial_002 val e016:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.47it/s]

trial_002 val e016:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.39it/s]

trial_002 val e016:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.39it/s]

trial_002 val e016:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.38it/s]

trial_002 val e016:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.41it/s]

trial_002 val e016:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.43it/s]

trial_002 val e016:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.44it/s]

trial_002 val e016: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.46it/s]

[2026-05-28 20:58:37] [trial_002] epoch=016 | train_loss=0.092741 | val_MAE=0.098924 | val_S=0.901076 | best_S=0.902131 @epoch=14 | patience=2/5

[trial_002] epochs:  16%|███████████████████▏                                                                                                    | 16/100 [35:00<3:01:13, 129.45s/it]

trial_002 train e017:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e017:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09071, loss=0.09071]

trial_002 train e017:   1%|▋                                                                                              | 1/149 [00:00<01:52,  1.32it/s, avg=0.09071, loss=0.09071]

trial_002 train e017:   1%|▋                                                                                              | 1/149 [00:01<01:52,  1.32it/s, avg=0.09025, loss=0.08979]

trial_002 train e017:   1%|█▎                                                                                             | 2/149 [00:01<01:49,  1.35it/s, avg=0.09025, loss=0.08979]

trial_002 train e017:   1%|█▎                                                                                             | 2/149 [00:02<01:49,  1.35it/s, avg=0.08816, loss=0.08398]

trial_002 train e017:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.08816, loss=0.08398]

trial_002 train e017:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.08617, loss=0.08022]

trial_002 train e017:   3%|██▌                                                                                            | 4/149 [00:02<01:45,  1.37it/s, avg=0.08617, loss=0.08022]

trial_002 train e017:   3%|██▌                                                                                            | 4/149 [00:03<01:45,  1.37it/s, avg=0.08542, loss=0.08242]

trial_002 train e017:   3%|███▏                                                                                           | 5/149 [00:03<01:46,  1.35it/s, avg=0.08542, loss=0.08242]

trial_002 train e017:   3%|███▏                                                                                           | 5/149 [00:04<01:46,  1.35it/s, avg=0.08731, loss=0.09672]

trial_002 train e017:   4%|███▊                                                                                           | 6/149 [00:04<01:44,  1.37it/s, avg=0.08731, loss=0.09672]

trial_002 train e017:   4%|███▊                                                                                           | 6/149 [00:05<01:44,  1.37it/s, avg=0.08693, loss=0.08465]

trial_002 train e017:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.39it/s, avg=0.08693, loss=0.08465]

trial_002 train e017:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.39it/s, avg=0.08849, loss=0.09947]

trial_002 train e017:   5%|█████                                                                                          | 8/149 [00:05<01:39,  1.42it/s, avg=0.08849, loss=0.09947]

trial_002 train e017:   5%|█████                                                                                          | 8/149 [00:06<01:39,  1.42it/s, avg=0.09007, loss=0.10269]

trial_002 train e017:   6%|█████▋                                                                                         | 9/149 [00:06<01:38,  1.42it/s, avg=0.09007, loss=0.10269]

trial_002 train e017:   6%|█████▋                                                                                         | 9/149 [00:07<01:38,  1.42it/s, avg=0.08982, loss=0.08758]

trial_002 train e017:   7%|██████▎                                                                                       | 10/149 [00:07<01:38,  1.41it/s, avg=0.08982, loss=0.08758]

trial_002 train e017:   7%|██████▎                                                                                       | 10/149 [00:07<01:38,  1.41it/s, avg=0.09102, loss=0.10303]

trial_002 train e017:   7%|██████▉                                                                                       | 11/149 [00:07<01:38,  1.40it/s, avg=0.09102, loss=0.10303]

trial_002 train e017:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.40it/s, avg=0.09166, loss=0.09862]

trial_002 train e017:   8%|███████▌                                                                                      | 12/149 [00:08<01:39,  1.38it/s, avg=0.09166, loss=0.09862]

trial_002 train e017:   8%|███████▌                                                                                      | 12/149 [00:09<01:39,  1.38it/s, avg=0.09154, loss=0.09013]

trial_002 train e017:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.09154, loss=0.09013]

trial_002 train e017:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.09134, loss=0.08877]

trial_002 train e017:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.38it/s, avg=0.09134, loss=0.08877]

trial_002 train e017:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.38it/s, avg=0.09152, loss=0.09399]

trial_002 train e017:  10%|█████████▍                                                                                    | 15/149 [00:10<01:38,  1.36it/s, avg=0.09152, loss=0.09399]

trial_002 train e017:  10%|█████████▍                                                                                    | 15/149 [00:11<01:38,  1.36it/s, avg=0.09102, loss=0.08362]

trial_002 train e017:  11%|██████████                                                                                    | 16/149 [00:11<01:37,  1.37it/s, avg=0.09102, loss=0.08362]

trial_002 train e017:  11%|██████████                                                                                    | 16/149 [00:12<01:37,  1.37it/s, avg=0.09102, loss=0.09094]

trial_002 train e017:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.09102, loss=0.09094]

trial_002 train e017:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.09077, loss=0.08649]

trial_002 train e017:  12%|███████████▎                                                                                  | 18/149 [00:12<01:33,  1.41it/s, avg=0.09077, loss=0.08649]

trial_002 train e017:  12%|███████████▎                                                                                  | 18/149 [00:13<01:33,  1.41it/s, avg=0.09086, loss=0.09247]

trial_002 train e017:  13%|███████████▉                                                                                  | 19/149 [00:13<01:32,  1.40it/s, avg=0.09086, loss=0.09247]

trial_002 train e017:  13%|███████████▉                                                                                  | 19/149 [00:14<01:32,  1.40it/s, avg=0.09084, loss=0.09045]

trial_002 train e017:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.41it/s, avg=0.09084, loss=0.09045]

trial_002 train e017:  13%|████████████▌                                                                                 | 20/149 [00:15<01:31,  1.41it/s, avg=0.09129, loss=0.10037]

trial_002 train e017:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.39it/s, avg=0.09129, loss=0.10037]

trial_002 train e017:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.39it/s, avg=0.09137, loss=0.09309]

trial_002 train e017:  15%|█████████████▉                                                                                | 22/149 [00:15<01:32,  1.37it/s, avg=0.09137, loss=0.09309]

trial_002 train e017:  15%|█████████████▉                                                                                | 22/149 [00:16<01:32,  1.37it/s, avg=0.09178, loss=0.10080]

trial_002 train e017:  15%|██████████████▌                                                                               | 23/149 [00:16<01:30,  1.39it/s, avg=0.09178, loss=0.10080]

trial_002 train e017:  15%|██████████████▌                                                                               | 23/149 [00:17<01:30,  1.39it/s, avg=0.09237, loss=0.10581]

trial_002 train e017:  16%|███████████████▏                                                                              | 24/149 [00:17<01:30,  1.39it/s, avg=0.09237, loss=0.10581]

trial_002 train e017:  16%|███████████████▏                                                                              | 24/149 [00:18<01:30,  1.39it/s, avg=0.09213, loss=0.08641]

trial_002 train e017:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.09213, loss=0.08641]

trial_002 train e017:  17%|███████████████▊                                                                              | 25/149 [00:18<01:30,  1.37it/s, avg=0.09230, loss=0.09662]

trial_002 train e017:  17%|████████████████▍                                                                             | 26/149 [00:18<01:28,  1.38it/s, avg=0.09230, loss=0.09662]

trial_002 train e017:  17%|████████████████▍                                                                             | 26/149 [00:19<01:28,  1.38it/s, avg=0.09251, loss=0.09790]

trial_002 train e017:  18%|█████████████████                                                                             | 27/149 [00:19<01:28,  1.38it/s, avg=0.09251, loss=0.09790]

trial_002 train e017:  18%|█████████████████                                                                             | 27/149 [00:20<01:28,  1.38it/s, avg=0.09223, loss=0.08466]

trial_002 train e017:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.36it/s, avg=0.09223, loss=0.08466]

trial_002 train e017:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:28,  1.36it/s, avg=0.09237, loss=0.09645]

trial_002 train e017:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:29,  1.34it/s, avg=0.09237, loss=0.09645]

trial_002 train e017:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:29,  1.34it/s, avg=0.09216, loss=0.08596]

trial_002 train e017:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:26,  1.38it/s, avg=0.09216, loss=0.08596]

trial_002 train e017:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:26,  1.38it/s, avg=0.09212, loss=0.09106]

trial_002 train e017:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:25,  1.38it/s, avg=0.09212, loss=0.09106]

trial_002 train e017:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:25,  1.38it/s, avg=0.09248, loss=0.10349]

trial_002 train e017:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.36it/s, avg=0.09248, loss=0.10349]

trial_002 train e017:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.36it/s, avg=0.09258, loss=0.09596]

trial_002 train e017:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:24,  1.37it/s, avg=0.09258, loss=0.09596]

trial_002 train e017:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.09256, loss=0.09181]

trial_002 train e017:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:24,  1.36it/s, avg=0.09256, loss=0.09181]

trial_002 train e017:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.09262, loss=0.09452]

trial_002 train e017:  23%|██████████████████████                                                                        | 35/149 [00:25<01:25,  1.33it/s, avg=0.09262, loss=0.09452]

trial_002 train e017:  23%|██████████████████████                                                                        | 35/149 [00:26<01:25,  1.33it/s, avg=0.09239, loss=0.08459]

trial_002 train e017:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:26,  1.31it/s, avg=0.09239, loss=0.08459]

trial_002 train e017:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:26,  1.31it/s, avg=0.09268, loss=0.10287]

trial_002 train e017:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:23,  1.34it/s, avg=0.09268, loss=0.10287]

trial_002 train e017:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:23,  1.34it/s, avg=0.09269, loss=0.09305]

trial_002 train e017:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:22,  1.34it/s, avg=0.09269, loss=0.09305]

trial_002 train e017:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:22,  1.34it/s, avg=0.09268, loss=0.09241]

trial_002 train e017:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:22,  1.33it/s, avg=0.09268, loss=0.09241]

trial_002 train e017:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:22,  1.33it/s, avg=0.09290, loss=0.10136]

trial_002 train e017:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:21,  1.34it/s, avg=0.09290, loss=0.10136]

trial_002 train e017:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:21,  1.34it/s, avg=0.09284, loss=0.09056]

trial_002 train e017:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:20,  1.35it/s, avg=0.09284, loss=0.09056]

trial_002 train e017:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:20,  1.35it/s, avg=0.09256, loss=0.08097]

trial_002 train e017:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:18,  1.36it/s, avg=0.09256, loss=0.08097]

trial_002 train e017:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:18,  1.36it/s, avg=0.09252, loss=0.09093]

trial_002 train e017:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:19,  1.33it/s, avg=0.09252, loss=0.09093]

trial_002 train e017:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:19,  1.33it/s, avg=0.09249, loss=0.09103]

trial_002 train e017:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.33it/s, avg=0.09249, loss=0.09103]

trial_002 train e017:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:18,  1.33it/s, avg=0.09264, loss=0.09931]

trial_002 train e017:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:16,  1.35it/s, avg=0.09264, loss=0.09931]

trial_002 train e017:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:16,  1.35it/s, avg=0.09280, loss=0.10017]

trial_002 train e017:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:15,  1.36it/s, avg=0.09280, loss=0.10017]

trial_002 train e017:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:15,  1.36it/s, avg=0.09250, loss=0.07855]

trial_002 train e017:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:15,  1.35it/s, avg=0.09250, loss=0.07855]

trial_002 train e017:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:15,  1.35it/s, avg=0.09279, loss=0.10674]

trial_002 train e017:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:12,  1.39it/s, avg=0.09279, loss=0.10674]

trial_002 train e017:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:12,  1.39it/s, avg=0.09263, loss=0.08482]

trial_002 train e017:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.37it/s, avg=0.09263, loss=0.08482]

trial_002 train e017:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:12,  1.37it/s, avg=0.09260, loss=0.09113]

trial_002 train e017:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:13,  1.34it/s, avg=0.09260, loss=0.09113]

trial_002 train e017:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:13,  1.34it/s, avg=0.09277, loss=0.10135]

trial_002 train e017:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:11,  1.38it/s, avg=0.09277, loss=0.10135]

trial_002 train e017:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:11,  1.38it/s, avg=0.09287, loss=0.09771]

trial_002 train e017:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.39it/s, avg=0.09287, loss=0.09771]

trial_002 train e017:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:09,  1.39it/s, avg=0.09293, loss=0.09595]

trial_002 train e017:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.09293, loss=0.09595]

trial_002 train e017:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.36it/s, avg=0.09293, loss=0.09323]

trial_002 train e017:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:10,  1.36it/s, avg=0.09293, loss=0.09323]

trial_002 train e017:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:10,  1.36it/s, avg=0.09268, loss=0.07906]

trial_002 train e017:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.09268, loss=0.07906]

trial_002 train e017:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.09247, loss=0.08070]

trial_002 train e017:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:08,  1.35it/s, avg=0.09247, loss=0.08070]

trial_002 train e017:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:08,  1.35it/s, avg=0.09230, loss=0.08277]

trial_002 train e017:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:08,  1.34it/s, avg=0.09230, loss=0.08277]

trial_002 train e017:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.34it/s, avg=0.09236, loss=0.09618]

trial_002 train e017:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09236, loss=0.09618]

trial_002 train e017:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:06,  1.37it/s, avg=0.09219, loss=0.08203]

trial_002 train e017:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:05,  1.37it/s, avg=0.09219, loss=0.08203]

trial_002 train e017:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:05,  1.37it/s, avg=0.09213, loss=0.08863]

trial_002 train e017:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:04,  1.39it/s, avg=0.09213, loss=0.08863]

trial_002 train e017:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:04,  1.39it/s, avg=0.09215, loss=0.09331]

trial_002 train e017:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:02,  1.42it/s, avg=0.09215, loss=0.09331]

trial_002 train e017:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:02,  1.42it/s, avg=0.09229, loss=0.10116]

trial_002 train e017:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:00,  1.43it/s, avg=0.09229, loss=0.10116]

trial_002 train e017:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:00,  1.43it/s, avg=0.09241, loss=0.09963]

trial_002 train e017:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:01,  1.40it/s, avg=0.09241, loss=0.09963]

trial_002 train e017:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:01,  1.40it/s, avg=0.09245, loss=0.09490]

trial_002 train e017:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:00,  1.41it/s, avg=0.09245, loss=0.09490]

trial_002 train e017:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:00,  1.41it/s, avg=0.09240, loss=0.08913]

trial_002 train e017:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<00:59,  1.41it/s, avg=0.09240, loss=0.08913]

trial_002 train e017:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<00:59,  1.41it/s, avg=0.09222, loss=0.08068]

trial_002 train e017:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:59,  1.39it/s, avg=0.09222, loss=0.08068]

trial_002 train e017:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:59,  1.39it/s, avg=0.09220, loss=0.09113]

trial_002 train e017:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.39it/s, avg=0.09220, loss=0.09113]

trial_002 train e017:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.39it/s, avg=0.09211, loss=0.08562]

trial_002 train e017:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:59,  1.37it/s, avg=0.09211, loss=0.08562]

trial_002 train e017:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:59,  1.37it/s, avg=0.09231, loss=0.10589]

trial_002 train e017:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:57,  1.39it/s, avg=0.09231, loss=0.10589]

trial_002 train e017:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:57,  1.39it/s, avg=0.09214, loss=0.08038]

trial_002 train e017:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.38it/s, avg=0.09214, loss=0.08038]

trial_002 train e017:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:57,  1.38it/s, avg=0.09216, loss=0.09361]

trial_002 train e017:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:57,  1.36it/s, avg=0.09216, loss=0.09361]

trial_002 train e017:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:57,  1.36it/s, avg=0.09220, loss=0.09505]

trial_002 train e017:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:57,  1.33it/s, avg=0.09220, loss=0.09505]

trial_002 train e017:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:57,  1.33it/s, avg=0.09211, loss=0.08556]

trial_002 train e017:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:57,  1.32it/s, avg=0.09211, loss=0.08556]

trial_002 train e017:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:57,  1.32it/s, avg=0.09209, loss=0.09099]

trial_002 train e017:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:56,  1.33it/s, avg=0.09209, loss=0.09099]

trial_002 train e017:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:56,  1.33it/s, avg=0.09224, loss=0.10296]

trial_002 train e017:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:54,  1.36it/s, avg=0.09224, loss=0.10296]

trial_002 train e017:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:54,  1.36it/s, avg=0.09207, loss=0.07988]

trial_002 train e017:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:53,  1.36it/s, avg=0.09207, loss=0.07988]

trial_002 train e017:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:53,  1.36it/s, avg=0.09211, loss=0.09456]

trial_002 train e017:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:53,  1.35it/s, avg=0.09211, loss=0.09456]

trial_002 train e017:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:53,  1.35it/s, avg=0.09230, loss=0.10763]

trial_002 train e017:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:53,  1.32it/s, avg=0.09230, loss=0.10763]

trial_002 train e017:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:53,  1.32it/s, avg=0.09217, loss=0.08133]

trial_002 train e017:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:52,  1.34it/s, avg=0.09217, loss=0.08133]

trial_002 train e017:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:52,  1.34it/s, avg=0.09211, loss=0.08771]

trial_002 train e017:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:52,  1.32it/s, avg=0.09211, loss=0.08771]

trial_002 train e017:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:52,  1.32it/s, avg=0.09191, loss=0.07623]

trial_002 train e017:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:51,  1.32it/s, avg=0.09191, loss=0.07623]

trial_002 train e017:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:51,  1.32it/s, avg=0.09196, loss=0.09542]

trial_002 train e017:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:50,  1.34it/s, avg=0.09196, loss=0.09542]

trial_002 train e017:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:50,  1.34it/s, avg=0.09202, loss=0.09745]

trial_002 train e017:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.35it/s, avg=0.09202, loss=0.09745]

trial_002 train e017:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:48,  1.35it/s, avg=0.09186, loss=0.07795]

trial_002 train e017:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:48,  1.33it/s, avg=0.09186, loss=0.07795]

trial_002 train e017:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:48,  1.33it/s, avg=0.09187, loss=0.09304]

trial_002 train e017:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.39it/s, avg=0.09187, loss=0.09304]

trial_002 train e017:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:46,  1.39it/s, avg=0.09192, loss=0.09650]

trial_002 train e017:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.40it/s, avg=0.09192, loss=0.09650]

trial_002 train e017:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:45,  1.40it/s, avg=0.09184, loss=0.08500]

trial_002 train e017:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.40it/s, avg=0.09184, loss=0.08500]

trial_002 train e017:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:44,  1.40it/s, avg=0.09181, loss=0.08920]

trial_002 train e017:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:44,  1.37it/s, avg=0.09181, loss=0.08920]

trial_002 train e017:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:44,  1.37it/s, avg=0.09173, loss=0.08480]

trial_002 train e017:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.36it/s, avg=0.09173, loss=0.08480]

trial_002 train e017:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:44,  1.36it/s, avg=0.09168, loss=0.08704]

trial_002 train e017:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:43,  1.35it/s, avg=0.09168, loss=0.08704]

trial_002 train e017:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.35it/s, avg=0.09168, loss=0.09181]

trial_002 train e017:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.35it/s, avg=0.09168, loss=0.09181]

trial_002 train e017:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.35it/s, avg=0.09168, loss=0.09094]

trial_002 train e017:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:41,  1.38it/s, avg=0.09168, loss=0.09094]

trial_002 train e017:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:41,  1.38it/s, avg=0.09174, loss=0.09800]

trial_002 train e017:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.39it/s, avg=0.09174, loss=0.09800]

trial_002 train e017:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:40,  1.39it/s, avg=0.09172, loss=0.08945]

trial_002 train e017:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:40,  1.37it/s, avg=0.09172, loss=0.08945]

trial_002 train e017:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:40,  1.37it/s, avg=0.09168, loss=0.08836]

trial_002 train e017:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.37it/s, avg=0.09168, loss=0.08836]

trial_002 train e017:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:39,  1.37it/s, avg=0.09171, loss=0.09393]

trial_002 train e017:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:39,  1.35it/s, avg=0.09171, loss=0.09393]

trial_002 train e017:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:39,  1.35it/s, avg=0.09171, loss=0.09209]

trial_002 train e017:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:39,  1.31it/s, avg=0.09171, loss=0.09209]

trial_002 train e017:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:39,  1.31it/s, avg=0.09182, loss=0.10263]

trial_002 train e017:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.35it/s, avg=0.09182, loss=0.10263]

trial_002 train e017:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.35it/s, avg=0.09193, loss=0.10217]

trial_002 train e017:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.37it/s, avg=0.09193, loss=0.10217]

trial_002 train e017:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.37it/s, avg=0.09203, loss=0.10185]

trial_002 train e017:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.36it/s, avg=0.09203, loss=0.10185]

trial_002 train e017:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:36,  1.36it/s, avg=0.09202, loss=0.09126]

trial_002 train e017:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:35,  1.35it/s, avg=0.09202, loss=0.09126]

trial_002 train e017:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.35it/s, avg=0.09206, loss=0.09652]

trial_002 train e017:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:35,  1.33it/s, avg=0.09206, loss=0.09652]

trial_002 train e017:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:35,  1.33it/s, avg=0.09195, loss=0.07996]

trial_002 train e017:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:34,  1.34it/s, avg=0.09195, loss=0.07996]

trial_002 train e017:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:34,  1.34it/s, avg=0.09175, loss=0.07184]

trial_002 train e017:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:33,  1.34it/s, avg=0.09175, loss=0.07184]

trial_002 train e017:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:33,  1.34it/s, avg=0.09182, loss=0.09892]

trial_002 train e017:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:32,  1.35it/s, avg=0.09182, loss=0.09892]

trial_002 train e017:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:32,  1.35it/s, avg=0.09176, loss=0.08572]

trial_002 train e017:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.35it/s, avg=0.09176, loss=0.08572]

trial_002 train e017:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:31,  1.35it/s, avg=0.09175, loss=0.09076]

trial_002 train e017:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:30,  1.36it/s, avg=0.09175, loss=0.09076]

trial_002 train e017:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:30,  1.36it/s, avg=0.09165, loss=0.08008]

trial_002 train e017:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.35it/s, avg=0.09165, loss=0.08008]

trial_002 train e017:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:30,  1.35it/s, avg=0.09171, loss=0.09835]

trial_002 train e017:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:29,  1.37it/s, avg=0.09171, loss=0.09835]

trial_002 train e017:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:29,  1.37it/s, avg=0.09178, loss=0.09987]

trial_002 train e017:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:28,  1.37it/s, avg=0.09178, loss=0.09987]

trial_002 train e017:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:28,  1.37it/s, avg=0.09177, loss=0.09083]

trial_002 train e017:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:28,  1.35it/s, avg=0.09177, loss=0.09083]

trial_002 train e017:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:22<00:28,  1.35it/s, avg=0.09172, loss=0.08600]

trial_002 train e017:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:27,  1.35it/s, avg=0.09172, loss=0.08600]

trial_002 train e017:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:27,  1.35it/s, avg=0.09172, loss=0.09115]

trial_002 train e017:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.34it/s, avg=0.09172, loss=0.09115]

trial_002 train e017:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:26,  1.34it/s, avg=0.09182, loss=0.10396]

trial_002 train e017:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:25,  1.35it/s, avg=0.09182, loss=0.10396]

trial_002 train e017:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:25,  1.35it/s, avg=0.09186, loss=0.09577]

trial_002 train e017:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:25,  1.35it/s, avg=0.09186, loss=0.09577]

trial_002 train e017:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:25<00:25,  1.35it/s, avg=0.09191, loss=0.09735]

trial_002 train e017:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.35it/s, avg=0.09191, loss=0.09735]

trial_002 train e017:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:24,  1.35it/s, avg=0.09204, loss=0.10728]

trial_002 train e017:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.36it/s, avg=0.09204, loss=0.10728]

trial_002 train e017:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.36it/s, avg=0.09208, loss=0.09760]

trial_002 train e017:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:23,  1.34it/s, avg=0.09208, loss=0.09760]

trial_002 train e017:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:27<00:23,  1.34it/s, avg=0.09208, loss=0.09105]

trial_002 train e017:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:22,  1.34it/s, avg=0.09208, loss=0.09105]

trial_002 train e017:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:28<00:22,  1.34it/s, avg=0.09209, loss=0.09446]

trial_002 train e017:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.35it/s, avg=0.09209, loss=0.09446]

trial_002 train e017:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.35it/s, avg=0.09207, loss=0.08953]

trial_002 train e017:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.35it/s, avg=0.09207, loss=0.08953]

trial_002 train e017:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.35it/s, avg=0.09209, loss=0.09380]

trial_002 train e017:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.37it/s, avg=0.09209, loss=0.09380]

trial_002 train e017:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:30<00:19,  1.37it/s, avg=0.09205, loss=0.08714]

trial_002 train e017:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.36it/s, avg=0.09205, loss=0.08714]

trial_002 train e017:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:19,  1.36it/s, avg=0.09203, loss=0.09015]

trial_002 train e017:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.37it/s, avg=0.09203, loss=0.09015]

trial_002 train e017:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.37it/s, avg=0.09208, loss=0.09754]

trial_002 train e017:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.36it/s, avg=0.09208, loss=0.09754]

trial_002 train e017:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.36it/s, avg=0.09218, loss=0.10510]

trial_002 train e017:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.37it/s, avg=0.09218, loss=0.10510]

trial_002 train e017:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:33<00:16,  1.37it/s, avg=0.09222, loss=0.09721]

trial_002 train e017:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.36it/s, avg=0.09222, loss=0.09721]

trial_002 train e017:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:16,  1.36it/s, avg=0.09225, loss=0.09616]

trial_002 train e017:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.38it/s, avg=0.09225, loss=0.09616]

trial_002 train e017:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.38it/s, avg=0.09224, loss=0.09132]

trial_002 train e017:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.37it/s, avg=0.09224, loss=0.09132]

trial_002 train e017:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:35<00:14,  1.37it/s, avg=0.09216, loss=0.08151]

trial_002 train e017:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.36it/s, avg=0.09216, loss=0.08151]

trial_002 train e017:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:36<00:13,  1.36it/s, avg=0.09216, loss=0.09194]

trial_002 train e017:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.35it/s, avg=0.09216, loss=0.09194]

trial_002 train e017:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.35it/s, avg=0.09209, loss=0.08289]

trial_002 train e017:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.40it/s, avg=0.09209, loss=0.08289]

trial_002 train e017:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.40it/s, avg=0.09211, loss=0.09526]

trial_002 train e017:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.39it/s, avg=0.09211, loss=0.09526]

trial_002 train e017:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:38<00:11,  1.39it/s, avg=0.09206, loss=0.08568]

trial_002 train e017:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.40it/s, avg=0.09206, loss=0.08568]

trial_002 train e017:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.40it/s, avg=0.09207, loss=0.09221]

trial_002 train e017:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:09,  1.42it/s, avg=0.09207, loss=0.09221]

trial_002 train e017:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:09,  1.42it/s, avg=0.09212, loss=0.09974]

trial_002 train e017:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.40it/s, avg=0.09212, loss=0.09974]

trial_002 train e017:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:40<00:09,  1.40it/s, avg=0.09217, loss=0.09887]

trial_002 train e017:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.42it/s, avg=0.09217, loss=0.09887]

trial_002 train e017:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.42it/s, avg=0.09226, loss=0.10467]

trial_002 train e017:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:07,  1.44it/s, avg=0.09226, loss=0.10467]

trial_002 train e017:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:07,  1.44it/s, avg=0.09238, loss=0.10930]

trial_002 train e017:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:06,  1.48it/s, avg=0.09238, loss=0.10930]

trial_002 train e017:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:06,  1.48it/s, avg=0.09245, loss=0.10165]

trial_002 train e017:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.47it/s, avg=0.09245, loss=0.10165]

trial_002 train e017:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.47it/s, avg=0.09244, loss=0.09031]

trial_002 train e017:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.50it/s, avg=0.09244, loss=0.09031]

trial_002 train e017:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.50it/s, avg=0.09245, loss=0.09429]

trial_002 train e017:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:04,  1.52it/s, avg=0.09245, loss=0.09429]

trial_002 train e017:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:04,  1.52it/s, avg=0.09242, loss=0.08909]

trial_002 train e017:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:03,  1.50it/s, avg=0.09242, loss=0.08909]

trial_002 train e017:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:03,  1.50it/s, avg=0.09236, loss=0.08265]

trial_002 train e017:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.51it/s, avg=0.09236, loss=0.08265]

trial_002 train e017:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.51it/s, avg=0.09240, loss=0.09913]

trial_002 train e017:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.52it/s, avg=0.09240, loss=0.09913]

trial_002 train e017:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.52it/s, avg=0.09245, loss=0.09930]

trial_002 train e017:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:01,  1.52it/s, avg=0.09245, loss=0.09930]

trial_002 train e017:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:01,  1.52it/s, avg=0.09242, loss=0.08857]

trial_002 train e017:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.52it/s, avg=0.09242, loss=0.08857]

trial_002 train e017:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.52it/s, avg=0.09242, loss=0.09108]

trial_002 train e017:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.47it/s, avg=0.09242, loss=0.09108]

trial_002 train e017:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.47it/s, avg=0.09238, loss=0.08018]

trial_002 train e017: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:47<00:00,  1.76it/s, avg=0.09238, loss=0.08018]

trial_002 val e017:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e017:   2%|██▌                                                                                                                          | 1/50 [00:00<00:17,  2.80it/s]

trial_002 val e017:   4%|█████                                                                                                                        | 2/50 [00:00<00:16,  2.91it/s]

trial_002 val e017:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:17,  2.76it/s]

trial_002 val e017:   8%|██████████                                                                                                                   | 4/50 [00:01<00:17,  2.67it/s]

trial_002 val e017:  10%|████████████▌                                                                                                                | 5/50 [00:01<00:16,  2.77it/s]

trial_002 val e017:  12%|███████████████                                                                                                              | 6/50 [00:02<00:15,  2.82it/s]

trial_002 val e017:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:14,  2.87it/s]

trial_002 val e017:  16%|████████████████████                                                                                                         | 8/50 [00:02<00:14,  2.89it/s]

trial_002 val e017:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:14,  2.88it/s]

trial_002 val e017:  20%|████████████████████████▊                                                                                                   | 10/50 [00:03<00:13,  2.90it/s]

trial_002 val e017:  22%|███████████████████████████▎                                                                                                | 11/50 [00:03<00:13,  2.89it/s]

trial_002 val e017:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:13,  2.90it/s]

trial_002 val e017:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:04<00:12,  2.91it/s]

trial_002 val e017:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:04<00:12,  2.90it/s]

trial_002 val e017:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:05<00:12,  2.91it/s]

trial_002 val e017:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:05<00:11,  2.90it/s]

trial_002 val e017:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:05<00:11,  2.88it/s]

trial_002 val e017:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:06<00:11,  2.89it/s]

trial_002 val e017:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:06<00:10,  2.90it/s]

trial_002 val e017:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:06<00:10,  2.89it/s]

trial_002 val e017:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:07<00:09,  2.90it/s]

trial_002 val e017:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:07<00:09,  2.92it/s]

trial_002 val e017:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:07<00:09,  2.93it/s]

trial_002 val e017:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:08<00:08,  2.94it/s]

trial_002 val e017:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:08<00:08,  2.91it/s]

trial_002 val e017:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:09<00:08,  2.92it/s]

trial_002 val e017:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:09<00:07,  2.90it/s]

trial_002 val e017:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:09<00:07,  2.91it/s]

trial_002 val e017:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:10<00:07,  2.92it/s]

trial_002 val e017:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:10<00:06,  2.93it/s]

trial_002 val e017:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:10<00:06,  2.91it/s]

trial_002 val e017:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:11<00:06,  2.91it/s]

trial_002 val e017:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:11<00:05,  2.90it/s]

trial_002 val e017:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:11<00:05,  2.89it/s]

trial_002 val e017:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:12<00:05,  2.91it/s]

trial_002 val e017:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:12<00:04,  2.93it/s]

trial_002 val e017:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:12<00:04,  2.93it/s]

trial_002 val e017:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:13<00:04,  2.93it/s]

trial_002 val e017:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:13<00:03,  2.91it/s]

trial_002 val e017:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:13<00:03,  2.92it/s]

trial_002 val e017:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:14<00:03,  2.92it/s]

trial_002 val e017:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:14<00:02,  2.92it/s]

trial_002 val e017:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:14<00:02,  2.94it/s]

trial_002 val e017:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:15<00:02,  2.95it/s]

trial_002 val e017:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:15<00:01,  2.96it/s]

trial_002 val e017:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:15<00:01,  2.91it/s]

trial_002 val e017:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:16<00:01,  2.91it/s]

trial_002 val e017:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:16<00:00,  2.83it/s]

trial_002 val e017:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:16<00:00,  2.84it/s]

trial_002 val e017: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:17<00:00,  2.87it/s]

[2026-05-28 21:00:42] [trial_002] epoch=017 | train_loss=0.092382 | val_MAE=0.099176 | val_S=0.900824 | best_S=0.902131 @epoch=14 | patience=3/5

[trial_002] epochs:  17%|████████████████████▍                                                                                                   | 17/100 [37:05<2:57:20, 128.20s/it]

trial_002 train e018:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e018:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08571, loss=0.08571]

trial_002 train e018:   1%|▋                                                                                              | 1/149 [00:00<01:33,  1.58it/s, avg=0.08571, loss=0.08571]

trial_002 train e018:   1%|▋                                                                                              | 1/149 [00:01<01:33,  1.58it/s, avg=0.09236, loss=0.09901]

trial_002 train e018:   1%|█▎                                                                                             | 2/149 [00:01<01:33,  1.58it/s, avg=0.09236, loss=0.09901]

trial_002 train e018:   1%|█▎                                                                                             | 2/149 [00:01<01:33,  1.58it/s, avg=0.08829, loss=0.08016]

trial_002 train e018:   2%|█▉                                                                                             | 3/149 [00:01<01:34,  1.55it/s, avg=0.08829, loss=0.08016]

trial_002 train e018:   2%|█▉                                                                                             | 3/149 [00:02<01:34,  1.55it/s, avg=0.08572, loss=0.07801]

trial_002 train e018:   3%|██▌                                                                                            | 4/149 [00:02<01:34,  1.53it/s, avg=0.08572, loss=0.07801]

trial_002 train e018:   3%|██▌                                                                                            | 4/149 [00:03<01:34,  1.53it/s, avg=0.08812, loss=0.09770]

trial_002 train e018:   3%|███▏                                                                                           | 5/149 [00:03<01:34,  1.53it/s, avg=0.08812, loss=0.09770]

trial_002 train e018:   3%|███▏                                                                                           | 5/149 [00:03<01:34,  1.53it/s, avg=0.08818, loss=0.08852]

trial_002 train e018:   4%|███▊                                                                                           | 6/149 [00:03<01:34,  1.52it/s, avg=0.08818, loss=0.08852]

trial_002 train e018:   4%|███▊                                                                                           | 6/149 [00:04<01:34,  1.52it/s, avg=0.09188, loss=0.11404]

trial_002 train e018:   5%|████▍                                                                                          | 7/149 [00:04<01:32,  1.53it/s, avg=0.09188, loss=0.11404]

trial_002 train e018:   5%|████▍                                                                                          | 7/149 [00:05<01:32,  1.53it/s, avg=0.09247, loss=0.09665]

trial_002 train e018:   5%|█████                                                                                          | 8/149 [00:05<01:30,  1.56it/s, avg=0.09247, loss=0.09665]

trial_002 train e018:   5%|█████                                                                                          | 8/149 [00:05<01:30,  1.56it/s, avg=0.09185, loss=0.08689]

trial_002 train e018:   6%|█████▋                                                                                         | 9/149 [00:05<01:30,  1.54it/s, avg=0.09185, loss=0.08689]

trial_002 train e018:   6%|█████▋                                                                                         | 9/149 [00:06<01:30,  1.54it/s, avg=0.09349, loss=0.10823]

trial_002 train e018:   7%|██████▎                                                                                       | 10/149 [00:06<01:30,  1.53it/s, avg=0.09349, loss=0.10823]

trial_002 train e018:   7%|██████▎                                                                                       | 10/149 [00:07<01:30,  1.53it/s, avg=0.09426, loss=0.10191]

trial_002 train e018:   7%|██████▉                                                                                       | 11/149 [00:07<01:31,  1.51it/s, avg=0.09426, loss=0.10191]

trial_002 train e018:   7%|██████▉                                                                                       | 11/149 [00:07<01:31,  1.51it/s, avg=0.09464, loss=0.09887]

trial_002 train e018:   8%|███████▌                                                                                      | 12/149 [00:07<01:30,  1.51it/s, avg=0.09464, loss=0.09887]

trial_002 train e018:   8%|███████▌                                                                                      | 12/149 [00:08<01:30,  1.51it/s, avg=0.09431, loss=0.09038]

trial_002 train e018:   9%|████████▏                                                                                     | 13/149 [00:08<01:30,  1.50it/s, avg=0.09431, loss=0.09038]

trial_002 train e018:   9%|████████▏                                                                                     | 13/149 [00:09<01:30,  1.50it/s, avg=0.09409, loss=0.09126]

trial_002 train e018:   9%|████████▊                                                                                     | 14/149 [00:09<01:29,  1.51it/s, avg=0.09409, loss=0.09126]

trial_002 train e018:   9%|████████▊                                                                                     | 14/149 [00:09<01:29,  1.51it/s, avg=0.09333, loss=0.08263]

trial_002 train e018:  10%|█████████▍                                                                                    | 15/149 [00:09<01:29,  1.50it/s, avg=0.09333, loss=0.08263]

trial_002 train e018:  10%|█████████▍                                                                                    | 15/149 [00:10<01:29,  1.50it/s, avg=0.09268, loss=0.08296]

trial_002 train e018:  11%|██████████                                                                                    | 16/149 [00:10<01:28,  1.50it/s, avg=0.09268, loss=0.08296]

trial_002 train e018:  11%|██████████                                                                                    | 16/149 [00:11<01:28,  1.50it/s, avg=0.09228, loss=0.08592]

trial_002 train e018:  11%|██████████▋                                                                                   | 17/149 [00:11<01:27,  1.50it/s, avg=0.09228, loss=0.08592]

trial_002 train e018:  11%|██████████▋                                                                                   | 17/149 [00:11<01:27,  1.50it/s, avg=0.09233, loss=0.09315]

trial_002 train e018:  12%|███████████▎                                                                                  | 18/149 [00:11<01:28,  1.49it/s, avg=0.09233, loss=0.09315]

trial_002 train e018:  12%|███████████▎                                                                                  | 18/149 [00:12<01:28,  1.49it/s, avg=0.09260, loss=0.09732]

trial_002 train e018:  13%|███████████▉                                                                                  | 19/149 [00:12<01:29,  1.45it/s, avg=0.09260, loss=0.09732]

trial_002 train e018:  13%|███████████▉                                                                                  | 19/149 [00:13<01:29,  1.45it/s, avg=0.09175, loss=0.07563]

trial_002 train e018:  13%|████████████▌                                                                                 | 20/149 [00:13<01:28,  1.46it/s, avg=0.09175, loss=0.07563]

trial_002 train e018:  13%|████████████▌                                                                                 | 20/149 [00:13<01:28,  1.46it/s, avg=0.09257, loss=0.10900]

trial_002 train e018:  14%|█████████████▏                                                                                | 21/149 [00:13<01:27,  1.46it/s, avg=0.09257, loss=0.10900]

trial_002 train e018:  14%|█████████████▏                                                                                | 21/149 [00:14<01:27,  1.46it/s, avg=0.09240, loss=0.08877]

trial_002 train e018:  15%|█████████████▉                                                                                | 22/149 [00:14<01:28,  1.43it/s, avg=0.09240, loss=0.08877]

trial_002 train e018:  15%|█████████████▉                                                                                | 22/149 [00:15<01:28,  1.43it/s, avg=0.09207, loss=0.08490]

trial_002 train e018:  15%|██████████████▌                                                                               | 23/149 [00:15<01:26,  1.45it/s, avg=0.09207, loss=0.08490]

trial_002 train e018:  15%|██████████████▌                                                                               | 23/149 [00:16<01:26,  1.45it/s, avg=0.09215, loss=0.09391]

trial_002 train e018:  16%|███████████████▏                                                                              | 24/149 [00:16<01:25,  1.46it/s, avg=0.09215, loss=0.09391]

trial_002 train e018:  16%|███████████████▏                                                                              | 24/149 [00:16<01:25,  1.46it/s, avg=0.09183, loss=0.08418]

trial_002 train e018:  17%|███████████████▊                                                                              | 25/149 [00:16<01:26,  1.44it/s, avg=0.09183, loss=0.08418]

trial_002 train e018:  17%|███████████████▊                                                                              | 25/149 [00:17<01:26,  1.44it/s, avg=0.09166, loss=0.08749]

trial_002 train e018:  17%|████████████████▍                                                                             | 26/149 [00:17<01:25,  1.43it/s, avg=0.09166, loss=0.08749]

trial_002 train e018:  17%|████████████████▍                                                                             | 26/149 [00:18<01:25,  1.43it/s, avg=0.09157, loss=0.08926]

trial_002 train e018:  18%|█████████████████                                                                             | 27/149 [00:18<01:24,  1.45it/s, avg=0.09157, loss=0.08926]

trial_002 train e018:  18%|█████████████████                                                                             | 27/149 [00:18<01:24,  1.45it/s, avg=0.09101, loss=0.07596]

trial_002 train e018:  19%|█████████████████▋                                                                            | 28/149 [00:18<01:26,  1.40it/s, avg=0.09101, loss=0.07596]

trial_002 train e018:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:26,  1.40it/s, avg=0.09093, loss=0.08866]

trial_002 train e018:  19%|██████████████████▎                                                                           | 29/149 [00:19<01:28,  1.36it/s, avg=0.09093, loss=0.08866]

trial_002 train e018:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:28,  1.36it/s, avg=0.09113, loss=0.09690]

trial_002 train e018:  20%|██████████████████▉                                                                           | 30/149 [00:20<01:27,  1.36it/s, avg=0.09113, loss=0.09690]

trial_002 train e018:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:27,  1.36it/s, avg=0.09115, loss=0.09160]

trial_002 train e018:  21%|███████████████████▌                                                                          | 31/149 [00:21<01:26,  1.36it/s, avg=0.09115, loss=0.09160]

trial_002 train e018:  21%|███████████████████▌                                                                          | 31/149 [00:21<01:26,  1.36it/s, avg=0.09139, loss=0.09898]

trial_002 train e018:  21%|████████████████████▏                                                                         | 32/149 [00:21<01:23,  1.41it/s, avg=0.09139, loss=0.09898]

trial_002 train e018:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:23,  1.41it/s, avg=0.09119, loss=0.08474]

trial_002 train e018:  22%|████████████████████▊                                                                         | 33/149 [00:22<01:24,  1.38it/s, avg=0.09119, loss=0.08474]

trial_002 train e018:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:24,  1.38it/s, avg=0.09153, loss=0.10283]

trial_002 train e018:  23%|█████████████████████▍                                                                        | 34/149 [00:23<01:23,  1.37it/s, avg=0.09153, loss=0.10283]

trial_002 train e018:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:23,  1.37it/s, avg=0.09148, loss=0.08952]

trial_002 train e018:  23%|██████████████████████                                                                        | 35/149 [00:24<01:23,  1.37it/s, avg=0.09148, loss=0.08952]

trial_002 train e018:  23%|██████████████████████                                                                        | 35/149 [00:24<01:23,  1.37it/s, avg=0.09169, loss=0.09937]

trial_002 train e018:  24%|██████████████████████▋                                                                       | 36/149 [00:24<01:22,  1.36it/s, avg=0.09169, loss=0.09937]

trial_002 train e018:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:22,  1.36it/s, avg=0.09116, loss=0.07196]

trial_002 train e018:  25%|███████████████████████▎                                                                      | 37/149 [00:25<01:22,  1.36it/s, avg=0.09116, loss=0.07196]

trial_002 train e018:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:22,  1.36it/s, avg=0.09111, loss=0.08914]

trial_002 train e018:  26%|███████████████████████▉                                                                      | 38/149 [00:26<01:21,  1.36it/s, avg=0.09111, loss=0.08914]

trial_002 train e018:  26%|███████████████████████▉                                                                      | 38/149 [00:26<01:21,  1.36it/s, avg=0.09137, loss=0.10134]

trial_002 train e018:  26%|████████████████████████▌                                                                     | 39/149 [00:26<01:20,  1.36it/s, avg=0.09137, loss=0.10134]

trial_002 train e018:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:20,  1.36it/s, avg=0.09153, loss=0.09765]

trial_002 train e018:  27%|█████████████████████████▏                                                                    | 40/149 [00:27<01:20,  1.35it/s, avg=0.09153, loss=0.09765]

trial_002 train e018:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:20,  1.35it/s, avg=0.09133, loss=0.08361]

trial_002 train e018:  28%|█████████████████████████▊                                                                    | 41/149 [00:28<01:20,  1.34it/s, avg=0.09133, loss=0.08361]

trial_002 train e018:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:20,  1.34it/s, avg=0.09111, loss=0.08187]

trial_002 train e018:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:18,  1.36it/s, avg=0.09111, loss=0.08187]

trial_002 train e018:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:18,  1.36it/s, avg=0.09152, loss=0.10870]

trial_002 train e018:  29%|███████████████████████████▏                                                                  | 43/149 [00:29<01:17,  1.37it/s, avg=0.09152, loss=0.10870]

trial_002 train e018:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:17,  1.37it/s, avg=0.09169, loss=0.09920]

trial_002 train e018:  30%|███████████████████████████▊                                                                  | 44/149 [00:30<01:15,  1.39it/s, avg=0.09169, loss=0.09920]

trial_002 train e018:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:15,  1.39it/s, avg=0.09177, loss=0.09535]

trial_002 train e018:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:15,  1.39it/s, avg=0.09177, loss=0.09535]

trial_002 train e018:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:15,  1.39it/s, avg=0.09212, loss=0.10750]

trial_002 train e018:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:14,  1.39it/s, avg=0.09212, loss=0.10750]

trial_002 train e018:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:14,  1.39it/s, avg=0.09229, loss=0.10051]

trial_002 train e018:  32%|█████████████████████████████▋                                                                | 47/149 [00:32<01:11,  1.42it/s, avg=0.09229, loss=0.10051]

trial_002 train e018:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:11,  1.42it/s, avg=0.09234, loss=0.09444]

trial_002 train e018:  32%|██████████████████████████████▎                                                               | 48/149 [00:33<01:11,  1.42it/s, avg=0.09234, loss=0.09444]

trial_002 train e018:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.42it/s, avg=0.09209, loss=0.07999]

trial_002 train e018:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:10,  1.42it/s, avg=0.09209, loss=0.07999]

trial_002 train e018:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:10,  1.42it/s, avg=0.09185, loss=0.08002]

trial_002 train e018:  34%|███████████████████████████████▌                                                              | 50/149 [00:34<01:10,  1.41it/s, avg=0.09185, loss=0.08002]

trial_002 train e018:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:10,  1.41it/s, avg=0.09166, loss=0.08228]

trial_002 train e018:  34%|████████████████████████████████▏                                                             | 51/149 [00:35<01:10,  1.39it/s, avg=0.09166, loss=0.08228]

trial_002 train e018:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:10,  1.39it/s, avg=0.09177, loss=0.09759]

trial_002 train e018:  35%|████████████████████████████████▊                                                             | 52/149 [00:36<01:09,  1.40it/s, avg=0.09177, loss=0.09759]

trial_002 train e018:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.40it/s, avg=0.09190, loss=0.09876]

trial_002 train e018:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:10,  1.36it/s, avg=0.09190, loss=0.09876]

trial_002 train e018:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:10,  1.36it/s, avg=0.09221, loss=0.10828]

trial_002 train e018:  36%|██████████████████████████████████                                                            | 54/149 [00:37<01:10,  1.34it/s, avg=0.09221, loss=0.10828]

trial_002 train e018:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:10,  1.34it/s, avg=0.09221, loss=0.09220]

trial_002 train e018:  37%|██████████████████████████████████▋                                                           | 55/149 [00:38<01:08,  1.38it/s, avg=0.09221, loss=0.09220]

trial_002 train e018:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.38it/s, avg=0.09223, loss=0.09357]

trial_002 train e018:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:07,  1.39it/s, avg=0.09223, loss=0.09357]

trial_002 train e018:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:07,  1.39it/s, avg=0.09231, loss=0.09676]

trial_002 train e018:  38%|███████████████████████████████████▉                                                          | 57/149 [00:39<01:07,  1.37it/s, avg=0.09231, loss=0.09676]

trial_002 train e018:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:07,  1.37it/s, avg=0.09248, loss=0.10231]

trial_002 train e018:  39%|████████████████████████████████████▌                                                         | 58/149 [00:40<01:06,  1.36it/s, avg=0.09248, loss=0.10231]

trial_002 train e018:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:06,  1.36it/s, avg=0.09267, loss=0.10359]

trial_002 train e018:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:41<01:06,  1.36it/s, avg=0.09267, loss=0.10359]

trial_002 train e018:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:06,  1.36it/s, avg=0.09269, loss=0.09366]

trial_002 train e018:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:06,  1.34it/s, avg=0.09269, loss=0.09366]

trial_002 train e018:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:06,  1.34it/s, avg=0.09264, loss=0.08964]

trial_002 train e018:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:42<01:04,  1.37it/s, avg=0.09264, loss=0.08964]

trial_002 train e018:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:04,  1.37it/s, avg=0.09265, loss=0.09316]

trial_002 train e018:  42%|███████████████████████████████████████                                                       | 62/149 [00:43<01:02,  1.38it/s, avg=0.09265, loss=0.09316]

trial_002 train e018:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:02,  1.38it/s, avg=0.09253, loss=0.08545]

trial_002 train e018:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<01:02,  1.37it/s, avg=0.09253, loss=0.08545]

trial_002 train e018:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:02,  1.37it/s, avg=0.09244, loss=0.08674]

trial_002 train e018:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<01:03,  1.33it/s, avg=0.09244, loss=0.08674]

trial_002 train e018:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<01:03,  1.33it/s, avg=0.09240, loss=0.09003]

trial_002 train e018:  44%|█████████████████████████████████████████                                                     | 65/149 [00:45<01:03,  1.33it/s, avg=0.09240, loss=0.09003]

trial_002 train e018:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<01:03,  1.33it/s, avg=0.09227, loss=0.08324]

trial_002 train e018:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<01:02,  1.32it/s, avg=0.09227, loss=0.08324]

trial_002 train e018:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<01:02,  1.32it/s, avg=0.09248, loss=0.10634]

trial_002 train e018:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<01:01,  1.34it/s, avg=0.09248, loss=0.10634]

trial_002 train e018:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<01:01,  1.34it/s, avg=0.09224, loss=0.07652]

trial_002 train e018:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<01:00,  1.33it/s, avg=0.09224, loss=0.07652]

trial_002 train e018:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<01:00,  1.33it/s, avg=0.09224, loss=0.09234]

trial_002 train e018:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:48<01:01,  1.31it/s, avg=0.09224, loss=0.09234]

trial_002 train e018:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<01:01,  1.31it/s, avg=0.09231, loss=0.09721]

trial_002 train e018:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:49<00:59,  1.33it/s, avg=0.09231, loss=0.09721]

trial_002 train e018:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:59,  1.33it/s, avg=0.09232, loss=0.09274]

trial_002 train e018:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:59,  1.32it/s, avg=0.09232, loss=0.09274]

trial_002 train e018:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:59,  1.32it/s, avg=0.09233, loss=0.09303]

trial_002 train e018:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:57,  1.33it/s, avg=0.09233, loss=0.09303]

trial_002 train e018:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:57,  1.33it/s, avg=0.09244, loss=0.10006]

trial_002 train e018:  49%|██████████████████████████████████████████████                                                | 73/149 [00:51<00:55,  1.37it/s, avg=0.09244, loss=0.10006]

trial_002 train e018:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:55,  1.37it/s, avg=0.09240, loss=0.08996]

trial_002 train e018:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:53,  1.40it/s, avg=0.09240, loss=0.08996]

trial_002 train e018:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.40it/s, avg=0.09252, loss=0.10122]

trial_002 train e018:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:54,  1.35it/s, avg=0.09252, loss=0.10122]

trial_002 train e018:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:54,  1.35it/s, avg=0.09246, loss=0.08818]

trial_002 train e018:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:54,  1.34it/s, avg=0.09246, loss=0.08818]

trial_002 train e018:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:54,  1.34it/s, avg=0.09242, loss=0.08882]

trial_002 train e018:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:54,  1.33it/s, avg=0.09242, loss=0.08882]

trial_002 train e018:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:54,  1.33it/s, avg=0.09234, loss=0.08657]

trial_002 train e018:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:52,  1.36it/s, avg=0.09234, loss=0.08657]

trial_002 train e018:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:52,  1.36it/s, avg=0.09229, loss=0.08850]

trial_002 train e018:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:52,  1.34it/s, avg=0.09229, loss=0.08850]

trial_002 train e018:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:52,  1.34it/s, avg=0.09237, loss=0.09891]

trial_002 train e018:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:52,  1.32it/s, avg=0.09237, loss=0.09891]

trial_002 train e018:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:52,  1.32it/s, avg=0.09244, loss=0.09730]

trial_002 train e018:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:51,  1.33it/s, avg=0.09244, loss=0.09730]

trial_002 train e018:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:51,  1.33it/s, avg=0.09254, loss=0.10065]

trial_002 train e018:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:51,  1.31it/s, avg=0.09254, loss=0.10065]

trial_002 train e018:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:51,  1.31it/s, avg=0.09231, loss=0.07414]

trial_002 train e018:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:50,  1.29it/s, avg=0.09231, loss=0.07414]

trial_002 train e018:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:50,  1.29it/s, avg=0.09228, loss=0.08908]

trial_002 train e018:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:48,  1.33it/s, avg=0.09228, loss=0.08908]

trial_002 train e018:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:48,  1.33it/s, avg=0.09211, loss=0.07804]

trial_002 train e018:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:47,  1.34it/s, avg=0.09211, loss=0.07804]

trial_002 train e018:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:47,  1.34it/s, avg=0.09201, loss=0.08405]

trial_002 train e018:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:46,  1.35it/s, avg=0.09201, loss=0.08405]

trial_002 train e018:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:46,  1.35it/s, avg=0.09196, loss=0.08763]

trial_002 train e018:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.38it/s, avg=0.09196, loss=0.08763]

trial_002 train e018:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.38it/s, avg=0.09183, loss=0.08025]

trial_002 train e018:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.40it/s, avg=0.09183, loss=0.08025]

trial_002 train e018:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.40it/s, avg=0.09178, loss=0.08703]

trial_002 train e018:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:43,  1.38it/s, avg=0.09178, loss=0.08703]

trial_002 train e018:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.38it/s, avg=0.09178, loss=0.09236]

trial_002 train e018:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.40it/s, avg=0.09178, loss=0.09236]

trial_002 train e018:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:42,  1.40it/s, avg=0.09199, loss=0.11035]

trial_002 train e018:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.37it/s, avg=0.09199, loss=0.11035]

trial_002 train e018:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.37it/s, avg=0.09201, loss=0.09450]

trial_002 train e018:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:41,  1.36it/s, avg=0.09201, loss=0.09450]

trial_002 train e018:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.36it/s, avg=0.09210, loss=0.09974]

trial_002 train e018:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:41,  1.35it/s, avg=0.09210, loss=0.09974]

trial_002 train e018:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:41,  1.35it/s, avg=0.09207, loss=0.08971]

trial_002 train e018:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:39,  1.39it/s, avg=0.09207, loss=0.08971]

trial_002 train e018:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:39,  1.39it/s, avg=0.09212, loss=0.09679]

trial_002 train e018:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.37it/s, avg=0.09212, loss=0.09679]

trial_002 train e018:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.37it/s, avg=0.09205, loss=0.08486]

trial_002 train e018:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:39,  1.35it/s, avg=0.09205, loss=0.08486]

trial_002 train e018:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:39,  1.35it/s, avg=0.09204, loss=0.09140]

trial_002 train e018:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:38,  1.34it/s, avg=0.09204, loss=0.09140]

trial_002 train e018:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:38,  1.34it/s, avg=0.09201, loss=0.08953]

trial_002 train e018:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:37,  1.36it/s, avg=0.09201, loss=0.08953]

trial_002 train e018:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.36it/s, avg=0.09201, loss=0.09193]

trial_002 train e018:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:36,  1.36it/s, avg=0.09201, loss=0.09193]

trial_002 train e018:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:36,  1.36it/s, avg=0.09207, loss=0.09785]

trial_002 train e018:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:36,  1.35it/s, avg=0.09207, loss=0.09785]

trial_002 train e018:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:36,  1.35it/s, avg=0.09221, loss=0.10625]

trial_002 train e018:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.38it/s, avg=0.09221, loss=0.10625]

trial_002 train e018:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.38it/s, avg=0.09224, loss=0.09463]

trial_002 train e018:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:34,  1.38it/s, avg=0.09224, loss=0.09463]

trial_002 train e018:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:34,  1.38it/s, avg=0.09213, loss=0.08180]

trial_002 train e018:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.38it/s, avg=0.09213, loss=0.08180]

trial_002 train e018:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.38it/s, avg=0.09207, loss=0.08503]

trial_002 train e018:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.37it/s, avg=0.09207, loss=0.08503]

trial_002 train e018:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.37it/s, avg=0.09210, loss=0.09538]

trial_002 train e018:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:32,  1.35it/s, avg=0.09210, loss=0.09538]

trial_002 train e018:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:32,  1.35it/s, avg=0.09211, loss=0.09390]

trial_002 train e018:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:31,  1.35it/s, avg=0.09211, loss=0.09390]

trial_002 train e018:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:31,  1.35it/s, avg=0.09201, loss=0.08119]

trial_002 train e018:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:31,  1.34it/s, avg=0.09201, loss=0.08119]

trial_002 train e018:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:31,  1.34it/s, avg=0.09202, loss=0.09324]

trial_002 train e018:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:30,  1.36it/s, avg=0.09202, loss=0.09324]

trial_002 train e018:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:30,  1.36it/s, avg=0.09210, loss=0.09980]

trial_002 train e018:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:29,  1.35it/s, avg=0.09210, loss=0.09980]

trial_002 train e018:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:29,  1.35it/s, avg=0.09202, loss=0.08355]

trial_002 train e018:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:28,  1.35it/s, avg=0.09202, loss=0.08355]

trial_002 train e018:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:28,  1.35it/s, avg=0.09216, loss=0.10780]

trial_002 train e018:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:28,  1.34it/s, avg=0.09216, loss=0.10780]

trial_002 train e018:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:28,  1.34it/s, avg=0.09214, loss=0.09015]

trial_002 train e018:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:27,  1.34it/s, avg=0.09214, loss=0.09015]

trial_002 train e018:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:27,  1.34it/s, avg=0.09220, loss=0.09837]

trial_002 train e018:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:26,  1.33it/s, avg=0.09220, loss=0.09837]

trial_002 train e018:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:26,  1.33it/s, avg=0.09221, loss=0.09386]

trial_002 train e018:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:26,  1.32it/s, avg=0.09221, loss=0.09386]

trial_002 train e018:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:26,  1.32it/s, avg=0.09227, loss=0.09839]

trial_002 train e018:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:25,  1.32it/s, avg=0.09227, loss=0.09839]

trial_002 train e018:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:25,  1.32it/s, avg=0.09223, loss=0.08768]

trial_002 train e018:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:24,  1.32it/s, avg=0.09223, loss=0.08768]

trial_002 train e018:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:24,  1.32it/s, avg=0.09231, loss=0.10200]

trial_002 train e018:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:24,  1.33it/s, avg=0.09231, loss=0.10200]

trial_002 train e018:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:24,  1.33it/s, avg=0.09238, loss=0.10058]

trial_002 train e018:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:23,  1.33it/s, avg=0.09238, loss=0.10058]

trial_002 train e018:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:23,  1.33it/s, avg=0.09236, loss=0.09010]

trial_002 train e018:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:22,  1.33it/s, avg=0.09236, loss=0.09010]

trial_002 train e018:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:22,  1.33it/s, avg=0.09238, loss=0.09524]

trial_002 train e018:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:21,  1.37it/s, avg=0.09238, loss=0.09524]

trial_002 train e018:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:21,  1.37it/s, avg=0.09239, loss=0.09322]

trial_002 train e018:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:20,  1.40it/s, avg=0.09239, loss=0.09322]

trial_002 train e018:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.40it/s, avg=0.09242, loss=0.09539]

trial_002 train e018:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.40it/s, avg=0.09242, loss=0.09539]

trial_002 train e018:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.40it/s, avg=0.09241, loss=0.09174]

trial_002 train e018:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.38it/s, avg=0.09241, loss=0.09174]

trial_002 train e018:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:18,  1.38it/s, avg=0.09246, loss=0.09817]

trial_002 train e018:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.41it/s, avg=0.09246, loss=0.09817]

trial_002 train e018:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:17,  1.41it/s, avg=0.09246, loss=0.09238]

trial_002 train e018:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:17,  1.40it/s, avg=0.09246, loss=0.09238]

trial_002 train e018:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.40it/s, avg=0.09240, loss=0.08527]

trial_002 train e018:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.38it/s, avg=0.09240, loss=0.08527]

trial_002 train e018:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.38it/s, avg=0.09236, loss=0.08776]

trial_002 train e018:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:16,  1.36it/s, avg=0.09236, loss=0.08776]

trial_002 train e018:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:16,  1.36it/s, avg=0.09230, loss=0.08456]

trial_002 train e018:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.36it/s, avg=0.09230, loss=0.08456]

trial_002 train e018:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.36it/s, avg=0.09225, loss=0.08559]

trial_002 train e018:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.38it/s, avg=0.09225, loss=0.08559]

trial_002 train e018:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.38it/s, avg=0.09217, loss=0.08186]

trial_002 train e018:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.37it/s, avg=0.09217, loss=0.08186]

trial_002 train e018:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.37it/s, avg=0.09217, loss=0.09255]

trial_002 train e018:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:13,  1.38it/s, avg=0.09217, loss=0.09255]

trial_002 train e018:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.38it/s, avg=0.09216, loss=0.09122]

trial_002 train e018:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:11,  1.42it/s, avg=0.09216, loss=0.09122]

trial_002 train e018:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:11,  1.42it/s, avg=0.09214, loss=0.08944]

trial_002 train e018:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.38it/s, avg=0.09214, loss=0.08944]

trial_002 train e018:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.38it/s, avg=0.09209, loss=0.08529]

trial_002 train e018:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.37it/s, avg=0.09209, loss=0.08529]

trial_002 train e018:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:10,  1.37it/s, avg=0.09224, loss=0.11248]

trial_002 train e018:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.38it/s, avg=0.09224, loss=0.11248]

trial_002 train e018:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.38it/s, avg=0.09238, loss=0.11013]

trial_002 train e018:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.41it/s, avg=0.09238, loss=0.11013]

trial_002 train e018:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.41it/s, avg=0.09238, loss=0.09356]

trial_002 train e018:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.43it/s, avg=0.09238, loss=0.09356]

trial_002 train e018:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.43it/s, avg=0.09238, loss=0.09234]

trial_002 train e018:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:07,  1.40it/s, avg=0.09238, loss=0.09234]

trial_002 train e018:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:07,  1.40it/s, avg=0.09238, loss=0.09227]

trial_002 train e018:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.41it/s, avg=0.09238, loss=0.09227]

trial_002 train e018:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.41it/s, avg=0.09237, loss=0.09111]

trial_002 train e018:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.39it/s, avg=0.09237, loss=0.09111]

trial_002 train e018:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.39it/s, avg=0.09242, loss=0.09848]

trial_002 train e018:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.40it/s, avg=0.09242, loss=0.09848]

trial_002 train e018:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.40it/s, avg=0.09241, loss=0.09189]

trial_002 train e018:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:05,  1.38it/s, avg=0.09241, loss=0.09189]

trial_002 train e018:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:05,  1.38it/s, avg=0.09244, loss=0.09561]

trial_002 train e018:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.39it/s, avg=0.09244, loss=0.09561]

trial_002 train e018:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.39it/s, avg=0.09247, loss=0.09775]

trial_002 train e018:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.39it/s, avg=0.09247, loss=0.09775]

trial_002 train e018:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.39it/s, avg=0.09242, loss=0.08465]

trial_002 train e018:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.40it/s, avg=0.09242, loss=0.08465]

trial_002 train e018:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.40it/s, avg=0.09236, loss=0.08420]

trial_002 train e018:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.40it/s, avg=0.09236, loss=0.08420]

trial_002 train e018:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.40it/s, avg=0.09230, loss=0.08304]

trial_002 train e018:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.36it/s, avg=0.09230, loss=0.08304]

trial_002 train e018:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.36it/s, avg=0.09244, loss=0.11318]

trial_002 train e018:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.37it/s, avg=0.09244, loss=0.11318]

trial_002 train e018:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.37it/s, avg=0.09240, loss=0.07699]

trial_002 train e018: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:47<00:00,  1.65it/s, avg=0.09240, loss=0.07699]

trial_002 val e018:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e018:   2%|██▌                                                                                                                          | 1/50 [00:00<00:22,  2.19it/s]

trial_002 val e018:   4%|█████                                                                                                                        | 2/50 [00:00<00:21,  2.24it/s]

trial_002 val e018:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:20,  2.28it/s]

trial_002 val e018:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.35it/s]

trial_002 val e018:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.39it/s]

trial_002 val e018:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.42it/s]

trial_002 val e018:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.41it/s]

trial_002 val e018:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.38it/s]

trial_002 val e018:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.39it/s]

trial_002 val e018:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.41it/s]

trial_002 val e018:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.42it/s]

trial_002 val e018:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:05<00:15,  2.43it/s]

trial_002 val e018:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.44it/s]

trial_002 val e018:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.44it/s]

trial_002 val e018:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.43it/s]

trial_002 val e018:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.39it/s]

trial_002 val e018:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.37it/s]

trial_002 val e018:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.41it/s]

trial_002 val e018:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.43it/s]

trial_002 val e018:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.44it/s]

trial_002 val e018:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.45it/s]

trial_002 val e018:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.46it/s]

trial_002 val e018:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:10,  2.47it/s]

trial_002 val e018:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.47it/s]

trial_002 val e018:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.48it/s]

trial_002 val e018:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.46it/s]

trial_002 val e018:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.40it/s]

trial_002 val e018:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.38it/s]

trial_002 val e018:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:08,  2.38it/s]

trial_002 val e018:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.41it/s]

trial_002 val e018:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.40it/s]

trial_002 val e018:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.38it/s]

trial_002 val e018:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.39it/s]

trial_002 val e018:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.39it/s]

trial_002 val e018:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.39it/s]

trial_002 val e018:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.41it/s]

trial_002 val e018:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.37it/s]

trial_002 val e018:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:05,  2.38it/s]

trial_002 val e018:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.39it/s]

trial_002 val e018:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.41it/s]

trial_002 val e018:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.43it/s]

trial_002 val e018:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.42it/s]

trial_002 val e018:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.36it/s]

trial_002 val e018:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.38it/s]

trial_002 val e018:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.40it/s]

trial_002 val e018:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.41it/s]

trial_002 val e018:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.42it/s]

trial_002 val e018:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.43it/s]

trial_002 val e018:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.44it/s]

trial_002 val e018: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.43it/s]

[2026-05-28 21:02:50] [trial_002] epoch=018 | train_loss=0.092399 | val_MAE=0.098768 | val_S=0.901232 | best_S=0.902131 @epoch=14 | patience=4/5

[trial_002] epochs:  18%|█████████████████████▌                                                                                                  | 18/100 [39:14<2:55:10, 128.18s/it]

trial_002 train e019:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_002 train e019:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09381, loss=0.09381]

trial_002 train e019:   1%|▋                                                                                              | 1/149 [00:00<01:43,  1.43it/s, avg=0.09381, loss=0.09381]

trial_002 train e019:   1%|▋                                                                                              | 1/149 [00:01<01:43,  1.43it/s, avg=0.09253, loss=0.09126]

trial_002 train e019:   1%|█▎                                                                                             | 2/149 [00:01<01:46,  1.38it/s, avg=0.09253, loss=0.09126]

trial_002 train e019:   1%|█▎                                                                                             | 2/149 [00:02<01:46,  1.38it/s, avg=0.09420, loss=0.09752]

trial_002 train e019:   2%|█▉                                                                                             | 3/149 [00:02<01:48,  1.35it/s, avg=0.09420, loss=0.09752]

trial_002 train e019:   2%|█▉                                                                                             | 3/149 [00:02<01:48,  1.35it/s, avg=0.09717, loss=0.10610]

trial_002 train e019:   3%|██▌                                                                                            | 4/149 [00:02<01:47,  1.35it/s, avg=0.09717, loss=0.10610]

trial_002 train e019:   3%|██▌                                                                                            | 4/149 [00:03<01:47,  1.35it/s, avg=0.09556, loss=0.08913]

trial_002 train e019:   3%|███▏                                                                                           | 5/149 [00:03<01:45,  1.37it/s, avg=0.09556, loss=0.08913]

trial_002 train e019:   3%|███▏                                                                                           | 5/149 [00:04<01:45,  1.37it/s, avg=0.09603, loss=0.09838]

trial_002 train e019:   4%|███▊                                                                                           | 6/149 [00:04<01:45,  1.36it/s, avg=0.09603, loss=0.09838]

trial_002 train e019:   4%|███▊                                                                                           | 6/149 [00:05<01:45,  1.36it/s, avg=0.09455, loss=0.08562]

trial_002 train e019:   5%|████▍                                                                                          | 7/149 [00:05<01:44,  1.35it/s, avg=0.09455, loss=0.08562]

trial_002 train e019:   5%|████▍                                                                                          | 7/149 [00:05<01:44,  1.35it/s, avg=0.09362, loss=0.08711]

trial_002 train e019:   5%|█████                                                                                          | 8/149 [00:05<01:43,  1.36it/s, avg=0.09362, loss=0.08711]

trial_002 train e019:   5%|█████                                                                                          | 8/149 [00:06<01:43,  1.36it/s, avg=0.09559, loss=0.11137]

trial_002 train e019:   6%|█████▋                                                                                         | 9/149 [00:06<01:40,  1.40it/s, avg=0.09559, loss=0.11137]

trial_002 train e019:   6%|█████▋                                                                                         | 9/149 [00:07<01:40,  1.40it/s, avg=0.09443, loss=0.08395]

trial_002 train e019:   7%|██████▎                                                                                       | 10/149 [00:07<01:43,  1.35it/s, avg=0.09443, loss=0.08395]

trial_002 train e019:   7%|██████▎                                                                                       | 10/149 [00:08<01:43,  1.35it/s, avg=0.09372, loss=0.08669]

trial_002 train e019:   7%|██████▉                                                                                       | 11/149 [00:08<01:41,  1.36it/s, avg=0.09372, loss=0.08669]

trial_002 train e019:   7%|██████▉                                                                                       | 11/149 [00:08<01:41,  1.36it/s, avg=0.09365, loss=0.09288]

trial_002 train e019:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.36it/s, avg=0.09365, loss=0.09288]

trial_002 train e019:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.36it/s, avg=0.09342, loss=0.09063]

trial_002 train e019:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.35it/s, avg=0.09342, loss=0.09063]

trial_002 train e019:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.35it/s, avg=0.09301, loss=0.08763]

trial_002 train e019:   9%|████████▊                                                                                     | 14/149 [00:10<01:41,  1.33it/s, avg=0.09301, loss=0.08763]

trial_002 train e019:   9%|████████▊                                                                                     | 14/149 [00:11<01:41,  1.33it/s, avg=0.09316, loss=0.09537]

trial_002 train e019:  10%|█████████▍                                                                                    | 15/149 [00:11<01:41,  1.32it/s, avg=0.09316, loss=0.09537]

trial_002 train e019:  10%|█████████▍                                                                                    | 15/149 [00:11<01:41,  1.32it/s, avg=0.09256, loss=0.08358]

trial_002 train e019:  11%|██████████                                                                                    | 16/149 [00:11<01:39,  1.33it/s, avg=0.09256, loss=0.08358]

trial_002 train e019:  11%|██████████                                                                                    | 16/149 [00:12<01:39,  1.33it/s, avg=0.09245, loss=0.09055]

trial_002 train e019:  11%|██████████▋                                                                                   | 17/149 [00:12<01:39,  1.32it/s, avg=0.09245, loss=0.09055]

trial_002 train e019:  11%|██████████▋                                                                                   | 17/149 [00:13<01:39,  1.32it/s, avg=0.09272, loss=0.09744]

trial_002 train e019:  12%|███████████▎                                                                                  | 18/149 [00:13<01:39,  1.31it/s, avg=0.09272, loss=0.09744]

trial_002 train e019:  12%|███████████▎                                                                                  | 18/149 [00:14<01:39,  1.31it/s, avg=0.09187, loss=0.07654]

trial_002 train e019:  13%|███████████▉                                                                                  | 19/149 [00:14<01:37,  1.33it/s, avg=0.09187, loss=0.07654]

trial_002 train e019:  13%|███████████▉                                                                                  | 19/149 [00:14<01:37,  1.33it/s, avg=0.09170, loss=0.08848]

trial_002 train e019:  13%|████████████▌                                                                                 | 20/149 [00:14<01:36,  1.34it/s, avg=0.09170, loss=0.08848]

trial_002 train e019:  13%|████████████▌                                                                                 | 20/149 [00:15<01:36,  1.34it/s, avg=0.09257, loss=0.10994]

trial_002 train e019:  14%|█████████████▏                                                                                | 21/149 [00:15<01:36,  1.33it/s, avg=0.09257, loss=0.10994]

trial_002 train e019:  14%|█████████████▏                                                                                | 21/149 [00:16<01:36,  1.33it/s, avg=0.09214, loss=0.08318]

trial_002 train e019:  15%|█████████████▉                                                                                | 22/149 [00:16<01:34,  1.35it/s, avg=0.09214, loss=0.08318]

trial_002 train e019:  15%|█████████████▉                                                                                | 22/149 [00:17<01:34,  1.35it/s, avg=0.09234, loss=0.09666]

trial_002 train e019:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.35it/s, avg=0.09234, loss=0.09666]

trial_002 train e019:  15%|██████████████▌                                                                               | 23/149 [00:17<01:33,  1.35it/s, avg=0.09283, loss=0.10415]

trial_002 train e019:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.37it/s, avg=0.09283, loss=0.10415]

trial_002 train e019:  16%|███████████████▏                                                                              | 24/149 [00:18<01:31,  1.37it/s, avg=0.09255, loss=0.08585]

trial_002 train e019:  17%|███████████████▊                                                                              | 25/149 [00:18<01:32,  1.34it/s, avg=0.09255, loss=0.08585]

trial_002 train e019:  17%|███████████████▊                                                                              | 25/149 [00:19<01:32,  1.34it/s, avg=0.09198, loss=0.07776]

trial_002 train e019:  17%|████████████████▍                                                                             | 26/149 [00:19<01:33,  1.32it/s, avg=0.09198, loss=0.07776]

trial_002 train e019:  17%|████████████████▍                                                                             | 26/149 [00:20<01:33,  1.32it/s, avg=0.09170, loss=0.08422]

trial_002 train e019:  18%|█████████████████                                                                             | 27/149 [00:20<01:31,  1.33it/s, avg=0.09170, loss=0.08422]

trial_002 train e019:  18%|█████████████████                                                                             | 27/149 [00:20<01:31,  1.33it/s, avg=0.09166, loss=0.09066]

trial_002 train e019:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:31,  1.32it/s, avg=0.09166, loss=0.09066]

trial_002 train e019:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:31,  1.32it/s, avg=0.09162, loss=0.09064]

trial_002 train e019:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:30,  1.33it/s, avg=0.09162, loss=0.09064]

trial_002 train e019:  19%|██████████████████▎                                                                           | 29/149 [00:22<01:30,  1.33it/s, avg=0.09151, loss=0.08835]

trial_002 train e019:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:29,  1.33it/s, avg=0.09151, loss=0.08835]

trial_002 train e019:  20%|██████████████████▉                                                                           | 30/149 [00:23<01:29,  1.33it/s, avg=0.09160, loss=0.09411]

trial_002 train e019:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.35it/s, avg=0.09160, loss=0.09411]

trial_002 train e019:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:27,  1.35it/s, avg=0.09166, loss=0.09357]

trial_002 train e019:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:26,  1.35it/s, avg=0.09166, loss=0.09357]

trial_002 train e019:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:26,  1.35it/s, avg=0.09132, loss=0.08037]

trial_002 train e019:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:26,  1.34it/s, avg=0.09132, loss=0.08037]

trial_002 train e019:  22%|████████████████████▊                                                                         | 33/149 [00:25<01:26,  1.34it/s, avg=0.09113, loss=0.08483]

trial_002 train e019:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.09113, loss=0.08483]

trial_002 train e019:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:24,  1.36it/s, avg=0.09101, loss=0.08707]

trial_002 train e019:  23%|██████████████████████                                                                        | 35/149 [00:25<01:22,  1.38it/s, avg=0.09101, loss=0.08707]

trial_002 train e019:  23%|██████████████████████                                                                        | 35/149 [00:26<01:22,  1.38it/s, avg=0.09111, loss=0.09468]

trial_002 train e019:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:22,  1.37it/s, avg=0.09111, loss=0.09468]

trial_002 train e019:  24%|██████████████████████▋                                                                       | 36/149 [00:27<01:22,  1.37it/s, avg=0.09128, loss=0.09717]

trial_002 train e019:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:20,  1.39it/s, avg=0.09128, loss=0.09717]

trial_002 train e019:  25%|███████████████████████▎                                                                      | 37/149 [00:28<01:20,  1.39it/s, avg=0.09117, loss=0.08729]

trial_002 train e019:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:20,  1.39it/s, avg=0.09117, loss=0.08729]

trial_002 train e019:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:20,  1.39it/s, avg=0.09117, loss=0.09100]

trial_002 train e019:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:17,  1.42it/s, avg=0.09117, loss=0.09100]

trial_002 train e019:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:17,  1.42it/s, avg=0.09110, loss=0.08846]

trial_002 train e019:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:16,  1.42it/s, avg=0.09110, loss=0.08846]

trial_002 train e019:  27%|█████████████████████████▏                                                                    | 40/149 [00:30<01:16,  1.42it/s, avg=0.09111, loss=0.09141]

trial_002 train e019:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.40it/s, avg=0.09111, loss=0.09141]

trial_002 train e019:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.40it/s, avg=0.09102, loss=0.08729]

trial_002 train e019:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:16,  1.40it/s, avg=0.09102, loss=0.08729]

trial_002 train e019:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:16,  1.40it/s, avg=0.09098, loss=0.08935]

trial_002 train e019:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:16,  1.38it/s, avg=0.09098, loss=0.08935]

trial_002 train e019:  29%|███████████████████████████▏                                                                  | 43/149 [00:32<01:16,  1.38it/s, avg=0.09100, loss=0.09192]

trial_002 train e019:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.41it/s, avg=0.09100, loss=0.09192]

trial_002 train e019:  30%|███████████████████████████▊                                                                  | 44/149 [00:33<01:14,  1.41it/s, avg=0.09095, loss=0.08858]

trial_002 train e019:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:14,  1.40it/s, avg=0.09095, loss=0.08858]

trial_002 train e019:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:14,  1.40it/s, avg=0.09053, loss=0.07184]

trial_002 train e019:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.38it/s, avg=0.09053, loss=0.07184]

trial_002 train e019:  31%|█████████████████████████████                                                                 | 46/149 [00:34<01:14,  1.38it/s, avg=0.09078, loss=0.10226]

trial_002 train e019:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:11,  1.42it/s, avg=0.09078, loss=0.10226]

trial_002 train e019:  32%|█████████████████████████████▋                                                                | 47/149 [00:35<01:11,  1.42it/s, avg=0.09085, loss=0.09418]

trial_002 train e019:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:13,  1.38it/s, avg=0.09085, loss=0.09418]

trial_002 train e019:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:13,  1.38it/s, avg=0.09114, loss=0.10509]

trial_002 train e019:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:10,  1.41it/s, avg=0.09114, loss=0.10509]

trial_002 train e019:  33%|██████████████████████████████▉                                                               | 49/149 [00:36<01:10,  1.41it/s, avg=0.09113, loss=0.09057]

trial_002 train e019:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:11,  1.39it/s, avg=0.09113, loss=0.09057]

trial_002 train e019:  34%|███████████████████████████████▌                                                              | 50/149 [00:37<01:11,  1.39it/s, avg=0.09139, loss=0.10438]

trial_002 train e019:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:08,  1.43it/s, avg=0.09139, loss=0.10438]

trial_002 train e019:  34%|████████████████████████████████▏                                                             | 51/149 [00:38<01:08,  1.43it/s, avg=0.09166, loss=0.10548]

trial_002 train e019:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.09166, loss=0.10548]

trial_002 train e019:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:10,  1.37it/s, avg=0.09148, loss=0.08208]

trial_002 train e019:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.09148, loss=0.08208]

trial_002 train e019:  36%|█████████████████████████████████▍                                                            | 53/149 [00:39<01:10,  1.36it/s, avg=0.09143, loss=0.08863]

trial_002 train e019:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:10,  1.35it/s, avg=0.09143, loss=0.08863]

trial_002 train e019:  36%|██████████████████████████████████                                                            | 54/149 [00:40<01:10,  1.35it/s, avg=0.09156, loss=0.09863]

trial_002 train e019:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:08,  1.37it/s, avg=0.09156, loss=0.09863]

trial_002 train e019:  37%|██████████████████████████████████▋                                                           | 55/149 [00:41<01:08,  1.37it/s, avg=0.09146, loss=0.08607]

trial_002 train e019:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:09,  1.33it/s, avg=0.09146, loss=0.08607]

trial_002 train e019:  38%|███████████████████████████████████▎                                                          | 56/149 [00:41<01:09,  1.33it/s, avg=0.09151, loss=0.09442]

trial_002 train e019:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:08,  1.34it/s, avg=0.09151, loss=0.09442]

trial_002 train e019:  38%|███████████████████████████████████▉                                                          | 57/149 [00:42<01:08,  1.34it/s, avg=0.09140, loss=0.08503]

trial_002 train e019:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:06,  1.37it/s, avg=0.09140, loss=0.08503]

trial_002 train e019:  39%|████████████████████████████████████▌                                                         | 58/149 [00:43<01:06,  1.37it/s, avg=0.09141, loss=0.09180]

trial_002 train e019:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:05,  1.37it/s, avg=0.09141, loss=0.09180]

trial_002 train e019:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:44<01:05,  1.37it/s, avg=0.09139, loss=0.09040]

trial_002 train e019:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:04,  1.37it/s, avg=0.09139, loss=0.09040]

trial_002 train e019:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:44<01:04,  1.37it/s, avg=0.09148, loss=0.09664]

trial_002 train e019:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:05,  1.34it/s, avg=0.09148, loss=0.09664]

trial_002 train e019:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:45<01:05,  1.34it/s, avg=0.09143, loss=0.08881]

trial_002 train e019:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:04,  1.35it/s, avg=0.09143, loss=0.08881]

trial_002 train e019:  42%|███████████████████████████████████████                                                       | 62/149 [00:46<01:04,  1.35it/s, avg=0.09153, loss=0.09730]

trial_002 train e019:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:46<01:05,  1.32it/s, avg=0.09153, loss=0.09730]

trial_002 train e019:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:47<01:05,  1.32it/s, avg=0.09163, loss=0.09786]

trial_002 train e019:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:03,  1.35it/s, avg=0.09163, loss=0.09786]

trial_002 train e019:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:47<01:03,  1.35it/s, avg=0.09167, loss=0.09462]

trial_002 train e019:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:01,  1.36it/s, avg=0.09167, loss=0.09462]

trial_002 train e019:  44%|█████████████████████████████████████████                                                     | 65/149 [00:48<01:01,  1.36it/s, avg=0.09163, loss=0.08870]

trial_002 train e019:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:59,  1.39it/s, avg=0.09163, loss=0.08870]

trial_002 train e019:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:49<00:59,  1.39it/s, avg=0.09146, loss=0.08033]

trial_002 train e019:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.40it/s, avg=0.09146, loss=0.08033]

trial_002 train e019:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:49<00:58,  1.40it/s, avg=0.09135, loss=0.08419]

trial_002 train e019:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:58,  1.39it/s, avg=0.09135, loss=0.08419]

trial_002 train e019:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:50<00:58,  1.39it/s, avg=0.09116, loss=0.07807]

trial_002 train e019:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:58,  1.37it/s, avg=0.09116, loss=0.07807]

trial_002 train e019:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:51<00:58,  1.37it/s, avg=0.09116, loss=0.09107]

trial_002 train e019:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:56,  1.40it/s, avg=0.09116, loss=0.09107]

trial_002 train e019:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:52<00:56,  1.40it/s, avg=0.09124, loss=0.09728]

trial_002 train e019:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:56,  1.38it/s, avg=0.09124, loss=0.09728]

trial_002 train e019:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:52<00:56,  1.38it/s, avg=0.09135, loss=0.09861]

trial_002 train e019:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:53,  1.44it/s, avg=0.09135, loss=0.09861]

trial_002 train e019:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:53<00:53,  1.44it/s, avg=0.09145, loss=0.09883]

trial_002 train e019:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:52,  1.45it/s, avg=0.09145, loss=0.09883]

trial_002 train e019:  49%|██████████████████████████████████████████████                                                | 73/149 [00:54<00:52,  1.45it/s, avg=0.09138, loss=0.08636]

trial_002 train e019:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:53,  1.40it/s, avg=0.09138, loss=0.08636]

trial_002 train e019:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:54<00:53,  1.40it/s, avg=0.09147, loss=0.09787]

trial_002 train e019:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.38it/s, avg=0.09147, loss=0.09787]

trial_002 train e019:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:55<00:53,  1.38it/s, avg=0.09145, loss=0.09053]

trial_002 train e019:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:53,  1.36it/s, avg=0.09145, loss=0.09053]

trial_002 train e019:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:56<00:53,  1.36it/s, avg=0.09158, loss=0.10157]

trial_002 train e019:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:52,  1.37it/s, avg=0.09158, loss=0.10157]

trial_002 train e019:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:57<00:52,  1.37it/s, avg=0.09154, loss=0.08794]

trial_002 train e019:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.37it/s, avg=0.09154, loss=0.08794]

trial_002 train e019:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:57<00:51,  1.37it/s, avg=0.09159, loss=0.09585]

trial_002 train e019:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:51,  1.36it/s, avg=0.09159, loss=0.09585]

trial_002 train e019:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:58<00:51,  1.36it/s, avg=0.09152, loss=0.08613]

trial_002 train e019:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:51,  1.35it/s, avg=0.09152, loss=0.08613]

trial_002 train e019:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:59<00:51,  1.35it/s, avg=0.09162, loss=0.09918]

trial_002 train e019:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:50,  1.34it/s, avg=0.09162, loss=0.09918]

trial_002 train e019:  54%|███████████████████████████████████████████████████                                           | 81/149 [01:00<00:50,  1.34it/s, avg=0.09154, loss=0.08525]

trial_002 train e019:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:50,  1.33it/s, avg=0.09154, loss=0.08525]

trial_002 train e019:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [01:00<00:50,  1.33it/s, avg=0.09178, loss=0.11171]

trial_002 train e019:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.35it/s, avg=0.09178, loss=0.11171]

trial_002 train e019:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:01<00:48,  1.35it/s, avg=0.09163, loss=0.07872]

trial_002 train e019:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:48,  1.33it/s, avg=0.09163, loss=0.07872]

trial_002 train e019:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:02<00:48,  1.33it/s, avg=0.09152, loss=0.08254]

trial_002 train e019:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:02<00:49,  1.30it/s, avg=0.09152, loss=0.08254]

trial_002 train e019:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:03<00:49,  1.30it/s, avg=0.09139, loss=0.08040]

trial_002 train e019:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:48,  1.29it/s, avg=0.09139, loss=0.08040]

trial_002 train e019:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:03<00:48,  1.29it/s, avg=0.09132, loss=0.08534]

trial_002 train e019:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:47,  1.30it/s, avg=0.09132, loss=0.08534]

trial_002 train e019:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:04<00:47,  1.30it/s, avg=0.09123, loss=0.08322]

trial_002 train e019:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:45,  1.33it/s, avg=0.09123, loss=0.08322]

trial_002 train e019:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:05<00:45,  1.33it/s, avg=0.09123, loss=0.09127]

trial_002 train e019:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:05<00:45,  1.33it/s, avg=0.09123, loss=0.09127]

trial_002 train e019:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:06<00:45,  1.33it/s, avg=0.09134, loss=0.10116]

trial_002 train e019:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.35it/s, avg=0.09134, loss=0.10116]

trial_002 train e019:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:06<00:43,  1.35it/s, avg=0.09140, loss=0.09638]

trial_002 train e019:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:42,  1.36it/s, avg=0.09140, loss=0.09638]

trial_002 train e019:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:07<00:42,  1.36it/s, avg=0.09132, loss=0.08463]

trial_002 train e019:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:07<00:42,  1.36it/s, avg=0.09132, loss=0.08463]

trial_002 train e019:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:08<00:42,  1.36it/s, avg=0.09127, loss=0.08643]

trial_002 train e019:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:08<00:41,  1.36it/s, avg=0.09127, loss=0.08643]

trial_002 train e019:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:09<00:41,  1.36it/s, avg=0.09144, loss=0.10725]

trial_002 train e019:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.38it/s, avg=0.09144, loss=0.10725]

trial_002 train e019:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:09<00:39,  1.38it/s, avg=0.09150, loss=0.09743]

trial_002 train e019:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:39,  1.37it/s, avg=0.09150, loss=0.09743]

trial_002 train e019:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:10<00:39,  1.37it/s, avg=0.09142, loss=0.08364]

trial_002 train e019:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:10<00:38,  1.36it/s, avg=0.09142, loss=0.08364]

trial_002 train e019:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:11<00:38,  1.36it/s, avg=0.09144, loss=0.09363]

trial_002 train e019:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:37,  1.39it/s, avg=0.09144, loss=0.09363]

trial_002 train e019:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:11<00:37,  1.39it/s, avg=0.09157, loss=0.10355]

trial_002 train e019:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:37,  1.37it/s, avg=0.09157, loss=0.10355]

trial_002 train e019:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:12<00:37,  1.37it/s, avg=0.09144, loss=0.07923]

trial_002 train e019:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:12<00:36,  1.38it/s, avg=0.09144, loss=0.07923]

trial_002 train e019:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:13<00:36,  1.38it/s, avg=0.09146, loss=0.09350]

trial_002 train e019:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:13<00:35,  1.38it/s, avg=0.09146, loss=0.09350]

trial_002 train e019:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:14<00:35,  1.38it/s, avg=0.09144, loss=0.08886]

trial_002 train e019:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09144, loss=0.08886]

trial_002 train e019:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:14<00:35,  1.36it/s, avg=0.09135, loss=0.08198]

trial_002 train e019:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:33,  1.38it/s, avg=0.09135, loss=0.08198]

trial_002 train e019:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:15<00:33,  1.38it/s, avg=0.09134, loss=0.09071]

trial_002 train e019:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:15<00:33,  1.37it/s, avg=0.09134, loss=0.09071]

trial_002 train e019:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:16<00:33,  1.37it/s, avg=0.09130, loss=0.08687]

trial_002 train e019:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:16<00:32,  1.38it/s, avg=0.09130, loss=0.08687]

trial_002 train e019:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:17<00:32,  1.38it/s, avg=0.09139, loss=0.10114]

trial_002 train e019:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:31,  1.40it/s, avg=0.09139, loss=0.10114]

trial_002 train e019:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:17<00:31,  1.40it/s, avg=0.09136, loss=0.08828]

trial_002 train e019:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:17<00:30,  1.42it/s, avg=0.09136, loss=0.08828]

trial_002 train e019:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:18<00:30,  1.42it/s, avg=0.09127, loss=0.08184]

trial_002 train e019:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:18<00:29,  1.41it/s, avg=0.09127, loss=0.08184]

trial_002 train e019:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:19<00:29,  1.41it/s, avg=0.09138, loss=0.10308]

trial_002 train e019:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:28,  1.42it/s, avg=0.09138, loss=0.10308]

trial_002 train e019:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:19<00:28,  1.42it/s, avg=0.09138, loss=0.09076]

trial_002 train e019:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:28,  1.42it/s, avg=0.09138, loss=0.09076]

trial_002 train e019:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:20<00:28,  1.42it/s, avg=0.09135, loss=0.08895]

trial_002 train e019:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:20<00:27,  1.39it/s, avg=0.09135, loss=0.08895]

trial_002 train e019:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:21<00:27,  1.39it/s, avg=0.09126, loss=0.08144]

trial_002 train e019:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:26,  1.41it/s, avg=0.09126, loss=0.08144]

trial_002 train e019:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:21<00:26,  1.41it/s, avg=0.09137, loss=0.10351]

trial_002 train e019:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:26,  1.40it/s, avg=0.09137, loss=0.10351]

trial_002 train e019:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:22<00:26,  1.40it/s, avg=0.09144, loss=0.09905]

trial_002 train e019:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:22<00:25,  1.43it/s, avg=0.09144, loss=0.09905]

trial_002 train e019:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:23<00:25,  1.43it/s, avg=0.09158, loss=0.10702]

trial_002 train e019:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:23<00:24,  1.44it/s, avg=0.09158, loss=0.10702]

trial_002 train e019:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:24<00:24,  1.44it/s, avg=0.09156, loss=0.08972]

trial_002 train e019:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:23,  1.42it/s, avg=0.09156, loss=0.08972]

trial_002 train e019:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:24<00:23,  1.42it/s, avg=0.09146, loss=0.07991]

trial_002 train e019:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:24<00:23,  1.41it/s, avg=0.09146, loss=0.07991]

trial_002 train e019:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:25<00:23,  1.41it/s, avg=0.09153, loss=0.09985]

trial_002 train e019:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:25<00:23,  1.38it/s, avg=0.09153, loss=0.09985]

trial_002 train e019:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:26<00:23,  1.38it/s, avg=0.09153, loss=0.09124]

trial_002 train e019:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.38it/s, avg=0.09153, loss=0.09124]

trial_002 train e019:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:26<00:22,  1.38it/s, avg=0.09156, loss=0.09520]

trial_002 train e019:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:21,  1.38it/s, avg=0.09156, loss=0.09520]

trial_002 train e019:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:27<00:21,  1.38it/s, avg=0.09145, loss=0.07877]

trial_002 train e019:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:27<00:21,  1.37it/s, avg=0.09145, loss=0.07877]

trial_002 train e019:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:28<00:21,  1.37it/s, avg=0.09150, loss=0.09650]

trial_002 train e019:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:28<00:20,  1.39it/s, avg=0.09150, loss=0.09650]

trial_002 train e019:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:29<00:20,  1.39it/s, avg=0.09157, loss=0.09988]

trial_002 train e019:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.38it/s, avg=0.09157, loss=0.09988]

trial_002 train e019:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:29<00:19,  1.38it/s, avg=0.09161, loss=0.09769]

trial_002 train e019:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:29<00:18,  1.41it/s, avg=0.09161, loss=0.09769]

trial_002 train e019:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:30<00:18,  1.41it/s, avg=0.09161, loss=0.09117]

trial_002 train e019:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:30<00:18,  1.38it/s, avg=0.09161, loss=0.09117]

trial_002 train e019:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:31<00:18,  1.38it/s, avg=0.09150, loss=0.07739]

trial_002 train e019:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:31<00:17,  1.37it/s, avg=0.09150, loss=0.07739]

trial_002 train e019:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:32<00:17,  1.37it/s, avg=0.09157, loss=0.10011]

trial_002 train e019:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.39it/s, avg=0.09157, loss=0.10011]

trial_002 train e019:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:32<00:16,  1.39it/s, avg=0.09160, loss=0.09623]

trial_002 train e019:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:32<00:15,  1.42it/s, avg=0.09160, loss=0.09623]

trial_002 train e019:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:33<00:15,  1.42it/s, avg=0.09157, loss=0.08721]

trial_002 train e019:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:33<00:15,  1.40it/s, avg=0.09157, loss=0.08721]

trial_002 train e019:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:34<00:15,  1.40it/s, avg=0.09148, loss=0.08048]

trial_002 train e019:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.38it/s, avg=0.09148, loss=0.08048]

trial_002 train e019:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:34<00:14,  1.38it/s, avg=0.09153, loss=0.09752]

trial_002 train e019:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.36it/s, avg=0.09153, loss=0.09752]

trial_002 train e019:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:35<00:13,  1.36it/s, avg=0.09153, loss=0.09144]

trial_002 train e019:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:35<00:13,  1.38it/s, avg=0.09153, loss=0.09144]

trial_002 train e019:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:36<00:13,  1.38it/s, avg=0.09149, loss=0.08668]

trial_002 train e019:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:36<00:12,  1.36it/s, avg=0.09149, loss=0.08668]

trial_002 train e019:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:37<00:12,  1.36it/s, avg=0.09147, loss=0.08917]

trial_002 train e019:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.41it/s, avg=0.09147, loss=0.08917]

trial_002 train e019:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:37<00:11,  1.41it/s, avg=0.09153, loss=0.09841]

trial_002 train e019:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:37<00:10,  1.41it/s, avg=0.09153, loss=0.09841]

trial_002 train e019:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:38<00:10,  1.41it/s, avg=0.09152, loss=0.09072]

trial_002 train e019:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:38<00:10,  1.39it/s, avg=0.09152, loss=0.09072]

trial_002 train e019:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:39<00:10,  1.39it/s, avg=0.09163, loss=0.10587]

trial_002 train e019:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.41it/s, avg=0.09163, loss=0.10587]

trial_002 train e019:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:39<00:09,  1.41it/s, avg=0.09171, loss=0.10285]

trial_002 train e019:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.40it/s, avg=0.09171, loss=0.10285]

trial_002 train e019:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:40<00:08,  1.40it/s, avg=0.09167, loss=0.08606]

trial_002 train e019:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:40<00:07,  1.40it/s, avg=0.09167, loss=0.08606]

trial_002 train e019:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:41<00:07,  1.40it/s, avg=0.09166, loss=0.09144]

trial_002 train e019:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:41<00:07,  1.38it/s, avg=0.09166, loss=0.09144]

trial_002 train e019:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:42<00:07,  1.38it/s, avg=0.09168, loss=0.09438]

trial_002 train e019:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.39it/s, avg=0.09168, loss=0.09438]

trial_002 train e019:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:42<00:06,  1.39it/s, avg=0.09172, loss=0.09683]

trial_002 train e019:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:42<00:05,  1.41it/s, avg=0.09172, loss=0.09683]

trial_002 train e019:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:43<00:05,  1.41it/s, avg=0.09162, loss=0.07750]

trial_002 train e019:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:43<00:05,  1.38it/s, avg=0.09162, loss=0.07750]

trial_002 train e019:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:44<00:05,  1.38it/s, avg=0.09162, loss=0.09198]

trial_002 train e019:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.40it/s, avg=0.09162, loss=0.09198]

trial_002 train e019:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:44<00:04,  1.40it/s, avg=0.09165, loss=0.09487]

trial_002 train e019:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.41it/s, avg=0.09165, loss=0.09487]

trial_002 train e019:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:45<00:03,  1.41it/s, avg=0.09169, loss=0.09856]

trial_002 train e019:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:45<00:02,  1.41it/s, avg=0.09169, loss=0.09856]

trial_002 train e019:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:46<00:02,  1.41it/s, avg=0.09183, loss=0.11198]

trial_002 train e019:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:46<00:02,  1.39it/s, avg=0.09183, loss=0.11198]

trial_002 train e019:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:47<00:02,  1.39it/s, avg=0.09173, loss=0.07715]

trial_002 train e019:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.36it/s, avg=0.09173, loss=0.07715]

trial_002 train e019:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:47<00:01,  1.36it/s, avg=0.09163, loss=0.07730]

trial_002 train e019:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:47<00:00,  1.37it/s, avg=0.09163, loss=0.07730]

trial_002 train e019:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:48<00:00,  1.37it/s, avg=0.09166, loss=0.10021]

trial_002 train e019: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:48<00:00,  1.66it/s, avg=0.09166, loss=0.10021]

trial_002 val e019:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_002 val e019:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.41it/s]

trial_002 val e019:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.45it/s]

trial_002 val e019:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.47it/s]

trial_002 val e019:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.48it/s]

trial_002 val e019:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.45it/s]

trial_002 val e019:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.46it/s]

trial_002 val e019:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.47it/s]

trial_002 val e019:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:16,  2.48it/s]

trial_002 val e019:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.44it/s]

trial_002 val e019:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.43it/s]

trial_002 val e019:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.44it/s]

trial_002 val e019:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.43it/s]

trial_002 val e019:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.45it/s]

trial_002 val e019:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.46it/s]

trial_002 val e019:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.46it/s]

trial_002 val e019:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.47it/s]

trial_002 val e019:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.48it/s]

trial_002 val e019:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:12,  2.48it/s]

trial_002 val e019:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.49it/s]

trial_002 val e019:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:11,  2.51it/s]

trial_002 val e019:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.52it/s]

trial_002 val e019:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:08<00:11,  2.52it/s]

trial_002 val e019:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:10,  2.49it/s]

trial_002 val e019:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.44it/s]

trial_002 val e019:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.46it/s]

trial_002 val e019:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.46it/s]

trial_002 val e019:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:10<00:09,  2.45it/s]

trial_002 val e019:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.45it/s]

trial_002 val e019:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.47it/s]

trial_002 val e019:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.48it/s]

trial_002 val e019:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.48it/s]

trial_002 val e019:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:12<00:07,  2.48it/s]

trial_002 val e019:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.48it/s]

trial_002 val e019:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.48it/s]

trial_002 val e019:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.48it/s]

trial_002 val e019:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.46it/s]

trial_002 val e019:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.44it/s]

trial_002 val e019:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.46it/s]

trial_002 val e019:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.46it/s]

trial_002 val e019:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.47it/s]

trial_002 val e019:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.48it/s]

trial_002 val e019:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.48it/s]

trial_002 val e019:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.49it/s]

trial_002 val e019:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.50it/s]

trial_002 val e019:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.50it/s]

trial_002 val e019:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.50it/s]

trial_002 val e019:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.50it/s]

trial_002 val e019:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.40it/s]

trial_002 val e019:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.40it/s]

trial_002 val e019: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.44it/s]

[2026-05-28 21:04:59] [trial_002] epoch=019 | train_loss=0.091658 | val_MAE=0.098320 | val_S=0.901680 | best_S=0.902131 @epoch=14 | patience=5/5

[2026-05-28 21:04:59] [trial_002] early stopping at epoch=19

[2026-05-28 21:05:05] [trial_002] DONE | best_epoch=14 | best_val_S=0.902131 | test_MAE=nan | test_R2=nan

[2026-05-28 21:05:07] [OPTUNA] trial_002 done | best_val_S=0.902131

[2026-05-28 21:05:08] [OPTUNA] trial_003 start | hp={'learning_rate': 0.00025305525892573504, 'r': 4, 'lora_alpha': 32, 'lora_dropout': 0.0, 'weight_decay': 0.003116037615666865, 'warmup_ratio': 0.1}

[2026-05-28 21:05:09] [trial_003] START | seed=42 | hp={'learning_rate': 0.00025305525892573504, 'r': 4, 'lora_alpha': 32, 'lora_dropout': 0.0, 'weight_decay': 0.003116037615666865, 'warmup_ratio': 0.1}

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

[trial_003] epochs:   0%|                                                                                                                                    | 0/100 [00:00<?, ?it/s]

trial_003 train e001:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e001:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.12767, loss=0.12767]

trial_003 train e001:   1%|▋                                                                                              | 1/149 [00:00<02:03,  1.19it/s, avg=0.12767, loss=0.12767]

trial_003 train e001:   1%|▋                                                                                              | 1/149 [00:01<02:03,  1.19it/s, avg=0.13173, loss=0.13578]

trial_003 train e001:   1%|█▎                                                                                             | 2/149 [00:01<01:53,  1.30it/s, avg=0.13173, loss=0.13578]

trial_003 train e001:   1%|█▎                                                                                             | 2/149 [00:02<01:53,  1.30it/s, avg=0.12880, loss=0.12296]

trial_003 train e001:   2%|█▉                                                                                             | 3/149 [00:02<01:46,  1.37it/s, avg=0.12880, loss=0.12296]

trial_003 train e001:   2%|█▉                                                                                             | 3/149 [00:02<01:46,  1.37it/s, avg=0.12364, loss=0.10813]

trial_003 train e001:   3%|██▌                                                                                            | 4/149 [00:02<01:45,  1.38it/s, avg=0.12364, loss=0.10813]

trial_003 train e001:   3%|██▌                                                                                            | 4/149 [00:03<01:45,  1.38it/s, avg=0.12597, loss=0.13530]

trial_003 train e001:   3%|███▏                                                                                           | 5/149 [00:03<01:44,  1.38it/s, avg=0.12597, loss=0.13530]

trial_003 train e001:   3%|███▏                                                                                           | 5/149 [00:04<01:44,  1.38it/s, avg=0.12642, loss=0.12865]

trial_003 train e001:   4%|███▊                                                                                           | 6/149 [00:04<01:43,  1.38it/s, avg=0.12642, loss=0.12865]

trial_003 train e001:   4%|███▊                                                                                           | 6/149 [00:05<01:43,  1.38it/s, avg=0.12581, loss=0.12220]

trial_003 train e001:   5%|████▍                                                                                          | 7/149 [00:05<01:44,  1.36it/s, avg=0.12581, loss=0.12220]

trial_003 train e001:   5%|████▍                                                                                          | 7/149 [00:05<01:44,  1.36it/s, avg=0.12489, loss=0.11843]

trial_003 train e001:   5%|█████                                                                                          | 8/149 [00:05<01:44,  1.34it/s, avg=0.12489, loss=0.11843]

trial_003 train e001:   5%|█████                                                                                          | 8/149 [00:06<01:44,  1.34it/s, avg=0.12524, loss=0.12804]

trial_003 train e001:   6%|█████▋                                                                                         | 9/149 [00:06<01:45,  1.33it/s, avg=0.12524, loss=0.12804]

trial_003 train e001:   6%|█████▋                                                                                         | 9/149 [00:07<01:45,  1.33it/s, avg=0.12511, loss=0.12393]

trial_003 train e001:   7%|██████▎                                                                                       | 10/149 [00:07<01:42,  1.35it/s, avg=0.12511, loss=0.12393]

trial_003 train e001:   7%|██████▎                                                                                       | 10/149 [00:08<01:42,  1.35it/s, avg=0.12544, loss=0.12878]

trial_003 train e001:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.37it/s, avg=0.12544, loss=0.12878]

trial_003 train e001:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.37it/s, avg=0.12462, loss=0.11554]

trial_003 train e001:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.36it/s, avg=0.12462, loss=0.11554]

trial_003 train e001:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.36it/s, avg=0.12470, loss=0.12568]

trial_003 train e001:   9%|████████▏                                                                                     | 13/149 [00:09<01:40,  1.36it/s, avg=0.12470, loss=0.12568]

trial_003 train e001:   9%|████████▏                                                                                     | 13/149 [00:10<01:40,  1.36it/s, avg=0.12492, loss=0.12781]

trial_003 train e001:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.40it/s, avg=0.12492, loss=0.12781]

trial_003 train e001:   9%|████████▊                                                                                     | 14/149 [00:11<01:36,  1.40it/s, avg=0.12468, loss=0.12123]

trial_003 train e001:  10%|█████████▍                                                                                    | 15/149 [00:11<01:36,  1.39it/s, avg=0.12468, loss=0.12123]

trial_003 train e001:  10%|█████████▍                                                                                    | 15/149 [00:11<01:36,  1.39it/s, avg=0.12468, loss=0.12475]

trial_003 train e001:  11%|██████████                                                                                    | 16/149 [00:11<01:36,  1.37it/s, avg=0.12468, loss=0.12475]

trial_003 train e001:  11%|██████████                                                                                    | 16/149 [00:12<01:36,  1.37it/s, avg=0.12478, loss=0.12634]

trial_003 train e001:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.12478, loss=0.12634]

trial_003 train e001:  11%|██████████▋                                                                                   | 17/149 [00:13<01:36,  1.37it/s, avg=0.12491, loss=0.12719]

trial_003 train e001:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.37it/s, avg=0.12491, loss=0.12719]

trial_003 train e001:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.37it/s, avg=0.12533, loss=0.13282]

trial_003 train e001:  13%|███████████▉                                                                                  | 19/149 [00:13<01:33,  1.40it/s, avg=0.12533, loss=0.13282]

trial_003 train e001:  13%|███████████▉                                                                                  | 19/149 [00:14<01:33,  1.40it/s, avg=0.12550, loss=0.12867]

trial_003 train e001:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.37it/s, avg=0.12550, loss=0.12867]

trial_003 train e001:  13%|████████████▌                                                                                 | 20/149 [00:15<01:33,  1.37it/s, avg=0.12587, loss=0.13346]

trial_003 train e001:  14%|█████████████▏                                                                                | 21/149 [00:15<01:31,  1.39it/s, avg=0.12587, loss=0.13346]

trial_003 train e001:  14%|█████████████▏                                                                                | 21/149 [00:16<01:31,  1.39it/s, avg=0.12591, loss=0.12657]

trial_003 train e001:  15%|█████████████▉                                                                                | 22/149 [00:16<01:30,  1.41it/s, avg=0.12591, loss=0.12657]

trial_003 train e001:  15%|█████████████▉                                                                                | 22/149 [00:16<01:30,  1.41it/s, avg=0.12587, loss=0.12496]

trial_003 train e001:  15%|██████████████▌                                                                               | 23/149 [00:16<01:31,  1.38it/s, avg=0.12587, loss=0.12496]

trial_003 train e001:  15%|██████████████▌                                                                               | 23/149 [00:17<01:31,  1.38it/s, avg=0.12531, loss=0.11258]

trial_003 train e001:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.37it/s, avg=0.12531, loss=0.11258]

trial_003 train e001:  16%|███████████████▏                                                                              | 24/149 [00:18<01:31,  1.37it/s, avg=0.12598, loss=0.14191]

trial_003 train e001:  17%|███████████████▊                                                                              | 25/149 [00:18<01:31,  1.35it/s, avg=0.12598, loss=0.14191]

trial_003 train e001:  17%|███████████████▊                                                                              | 25/149 [00:19<01:31,  1.35it/s, avg=0.12579, loss=0.12107]

trial_003 train e001:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.36it/s, avg=0.12579, loss=0.12107]

trial_003 train e001:  17%|████████████████▍                                                                             | 26/149 [00:19<01:30,  1.36it/s, avg=0.12516, loss=0.10896]

trial_003 train e001:  18%|█████████████████                                                                             | 27/149 [00:19<01:29,  1.36it/s, avg=0.12516, loss=0.10896]

trial_003 train e001:  18%|█████████████████                                                                             | 27/149 [00:20<01:29,  1.36it/s, avg=0.12467, loss=0.11122]

trial_003 train e001:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:28,  1.37it/s, avg=0.12467, loss=0.11122]

trial_003 train e001:  19%|█████████████████▋                                                                            | 28/149 [00:21<01:28,  1.37it/s, avg=0.12475, loss=0.12705]

trial_003 train e001:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:27,  1.38it/s, avg=0.12475, loss=0.12705]

trial_003 train e001:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:27,  1.38it/s, avg=0.12438, loss=0.11383]

trial_003 train e001:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:27,  1.36it/s, avg=0.12438, loss=0.11383]

trial_003 train e001:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.36it/s, avg=0.12399, loss=0.11227]

trial_003 train e001:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:26,  1.37it/s, avg=0.12399, loss=0.11227]

trial_003 train e001:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:26,  1.37it/s, avg=0.12401, loss=0.12454]

trial_003 train e001:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:25,  1.37it/s, avg=0.12401, loss=0.12454]

trial_003 train e001:  21%|████████████████████▏                                                                         | 32/149 [00:24<01:25,  1.37it/s, avg=0.12459, loss=0.14301]

trial_003 train e001:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.38it/s, avg=0.12459, loss=0.14301]

trial_003 train e001:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.38it/s, avg=0.12407, loss=0.10713]

trial_003 train e001:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:22,  1.40it/s, avg=0.12407, loss=0.10713]

trial_003 train e001:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:22,  1.40it/s, avg=0.12428, loss=0.13133]

trial_003 train e001:  23%|██████████████████████                                                                        | 35/149 [00:25<01:19,  1.43it/s, avg=0.12428, loss=0.13133]

trial_003 train e001:  23%|██████████████████████                                                                        | 35/149 [00:26<01:19,  1.43it/s, avg=0.12446, loss=0.13093]

trial_003 train e001:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:18,  1.43it/s, avg=0.12446, loss=0.13093]

trial_003 train e001:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:18,  1.43it/s, avg=0.12440, loss=0.12205]

trial_003 train e001:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:17,  1.45it/s, avg=0.12440, loss=0.12205]

trial_003 train e001:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:17,  1.45it/s, avg=0.12430, loss=0.12053]

trial_003 train e001:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:18,  1.41it/s, avg=0.12430, loss=0.12053]

trial_003 train e001:  26%|███████████████████████▉                                                                      | 38/149 [00:28<01:18,  1.41it/s, avg=0.12418, loss=0.11979]

trial_003 train e001:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:17,  1.43it/s, avg=0.12418, loss=0.11979]

trial_003 train e001:  26%|████████████████████████▌                                                                     | 39/149 [00:29<01:17,  1.43it/s, avg=0.12373, loss=0.10622]

trial_003 train e001:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.12373, loss=0.10622]

trial_003 train e001:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.12402, loss=0.13532]

trial_003 train e001:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:17,  1.39it/s, avg=0.12402, loss=0.13532]

trial_003 train e001:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:17,  1.39it/s, avg=0.12429, loss=0.13544]

trial_003 train e001:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:16,  1.39it/s, avg=0.12429, loss=0.13544]

trial_003 train e001:  28%|██████████████████████████▍                                                                   | 42/149 [00:31<01:16,  1.39it/s, avg=0.12458, loss=0.13694]

trial_003 train e001:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:14,  1.43it/s, avg=0.12458, loss=0.13694]

trial_003 train e001:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:14,  1.43it/s, avg=0.12409, loss=0.10291]

trial_003 train e001:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:14,  1.42it/s, avg=0.12409, loss=0.10291]

trial_003 train e001:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.42it/s, avg=0.12383, loss=0.11230]

trial_003 train e001:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.40it/s, avg=0.12383, loss=0.11230]

trial_003 train e001:  30%|████████████████████████████▍                                                                 | 45/149 [00:33<01:14,  1.40it/s, avg=0.12364, loss=0.11521]

trial_003 train e001:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.39it/s, avg=0.12364, loss=0.11521]

trial_003 train e001:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:14,  1.39it/s, avg=0.12370, loss=0.12668]

trial_003 train e001:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.41it/s, avg=0.12370, loss=0.12668]

trial_003 train e001:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:12,  1.41it/s, avg=0.12373, loss=0.12501]

trial_003 train e001:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.41it/s, avg=0.12373, loss=0.12501]

trial_003 train e001:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:11,  1.41it/s, avg=0.12338, loss=0.10663]

trial_003 train e001:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:08,  1.45it/s, avg=0.12338, loss=0.10663]

trial_003 train e001:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:08,  1.45it/s, avg=0.12364, loss=0.13632]

trial_003 train e001:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:07,  1.47it/s, avg=0.12364, loss=0.13632]

trial_003 train e001:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:07,  1.47it/s, avg=0.12389, loss=0.13637]

trial_003 train e001:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:06,  1.47it/s, avg=0.12389, loss=0.13637]

trial_003 train e001:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:06,  1.47it/s, avg=0.12389, loss=0.12392]

trial_003 train e001:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:06,  1.45it/s, avg=0.12389, loss=0.12392]

trial_003 train e001:  35%|████████████████████████████████▊                                                             | 52/149 [00:38<01:06,  1.45it/s, avg=0.12377, loss=0.11745]

trial_003 train e001:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:06,  1.44it/s, avg=0.12377, loss=0.11745]

trial_003 train e001:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:06,  1.44it/s, avg=0.12382, loss=0.12636]

trial_003 train e001:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:07,  1.41it/s, avg=0.12382, loss=0.12636]

trial_003 train e001:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:07,  1.41it/s, avg=0.12358, loss=0.11090]

trial_003 train e001:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:07,  1.39it/s, avg=0.12358, loss=0.11090]

trial_003 train e001:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:07,  1.39it/s, avg=0.12332, loss=0.10902]

trial_003 train e001:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.40it/s, avg=0.12332, loss=0.10902]

trial_003 train e001:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.40it/s, avg=0.12337, loss=0.12596]

trial_003 train e001:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:05,  1.40it/s, avg=0.12337, loss=0.12596]

trial_003 train e001:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.40it/s, avg=0.12376, loss=0.14619]

trial_003 train e001:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:04,  1.40it/s, avg=0.12376, loss=0.14619]

trial_003 train e001:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:04,  1.40it/s, avg=0.12373, loss=0.12162]

trial_003 train e001:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:04,  1.40it/s, avg=0.12373, loss=0.12162]

trial_003 train e001:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:43<01:04,  1.40it/s, avg=0.12363, loss=0.11807]

trial_003 train e001:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:02,  1.42it/s, avg=0.12363, loss=0.11807]

trial_003 train e001:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:02,  1.42it/s, avg=0.12359, loss=0.12127]

trial_003 train e001:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:03,  1.39it/s, avg=0.12359, loss=0.12127]

trial_003 train e001:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:03,  1.39it/s, avg=0.12352, loss=0.11873]

trial_003 train e001:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:01,  1.41it/s, avg=0.12352, loss=0.11873]

trial_003 train e001:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:01,  1.41it/s, avg=0.12324, loss=0.10642]

trial_003 train e001:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:00,  1.42it/s, avg=0.12324, loss=0.10642]

trial_003 train e001:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:00,  1.42it/s, avg=0.12348, loss=0.13834]

trial_003 train e001:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<01:00,  1.41it/s, avg=0.12348, loss=0.13834]

trial_003 train e001:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:00,  1.41it/s, avg=0.12382, loss=0.14587]

trial_003 train e001:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.42it/s, avg=0.12382, loss=0.14587]

trial_003 train e001:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<00:59,  1.42it/s, avg=0.12364, loss=0.11164]

trial_003 train e001:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:59,  1.40it/s, avg=0.12364, loss=0.11164]

trial_003 train e001:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<00:59,  1.40it/s, avg=0.12387, loss=0.13877]

trial_003 train e001:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:59,  1.37it/s, avg=0.12387, loss=0.13877]

trial_003 train e001:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:59,  1.37it/s, avg=0.12354, loss=0.10153]

trial_003 train e001:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:59,  1.37it/s, avg=0.12354, loss=0.10153]

trial_003 train e001:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:59,  1.37it/s, avg=0.12363, loss=0.12963]

trial_003 train e001:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:58,  1.36it/s, avg=0.12363, loss=0.12963]

trial_003 train e001:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:58,  1.36it/s, avg=0.12351, loss=0.11558]

trial_003 train e001:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:58,  1.35it/s, avg=0.12351, loss=0.11558]

trial_003 train e001:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:51<00:58,  1.35it/s, avg=0.12346, loss=0.11956]

trial_003 train e001:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:57,  1.37it/s, avg=0.12346, loss=0.11956]

trial_003 train e001:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:57,  1.37it/s, avg=0.12389, loss=0.15449]

trial_003 train e001:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:55,  1.39it/s, avg=0.12389, loss=0.15449]

trial_003 train e001:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:55,  1.39it/s, avg=0.12386, loss=0.12212]

trial_003 train e001:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:54,  1.40it/s, avg=0.12386, loss=0.12212]

trial_003 train e001:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:54,  1.40it/s, avg=0.12385, loss=0.12286]

trial_003 train e001:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.40it/s, avg=0.12385, loss=0.12286]

trial_003 train e001:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.40it/s, avg=0.12412, loss=0.14414]

trial_003 train e001:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:52,  1.41it/s, avg=0.12412, loss=0.14414]

trial_003 train e001:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:52,  1.41it/s, avg=0.12415, loss=0.12624]

trial_003 train e001:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:51,  1.41it/s, avg=0.12415, loss=0.12624]

trial_003 train e001:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:51,  1.41it/s, avg=0.12402, loss=0.11403]

trial_003 train e001:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:50,  1.42it/s, avg=0.12402, loss=0.11403]

trial_003 train e001:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:56<00:50,  1.42it/s, avg=0.12400, loss=0.12282]

trial_003 train e001:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.39it/s, avg=0.12400, loss=0.12282]

trial_003 train e001:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.39it/s, avg=0.12405, loss=0.12802]

trial_003 train e001:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:51,  1.37it/s, avg=0.12405, loss=0.12802]

trial_003 train e001:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:51,  1.37it/s, avg=0.12414, loss=0.13135]

trial_003 train e001:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:50,  1.36it/s, avg=0.12414, loss=0.13135]

trial_003 train e001:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.36it/s, avg=0.12427, loss=0.13484]

trial_003 train e001:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:49,  1.37it/s, avg=0.12427, loss=0.13484]

trial_003 train e001:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:59<00:49,  1.37it/s, avg=0.12418, loss=0.11679]

trial_003 train e001:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:49,  1.36it/s, avg=0.12418, loss=0.11679]

trial_003 train e001:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:49,  1.36it/s, avg=0.12396, loss=0.10554]

trial_003 train e001:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:48,  1.36it/s, avg=0.12396, loss=0.10554]

trial_003 train e001:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:48,  1.36it/s, avg=0.12388, loss=0.11754]

trial_003 train e001:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:48,  1.35it/s, avg=0.12388, loss=0.11754]

trial_003 train e001:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:01<00:48,  1.35it/s, avg=0.12378, loss=0.11515]

trial_003 train e001:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:47,  1.35it/s, avg=0.12378, loss=0.11515]

trial_003 train e001:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:47,  1.35it/s, avg=0.12411, loss=0.15254]

trial_003 train e001:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.38it/s, avg=0.12411, loss=0.15254]

trial_003 train e001:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.38it/s, avg=0.12404, loss=0.11739]

trial_003 train e001:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.39it/s, avg=0.12404, loss=0.11739]

trial_003 train e001:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.39it/s, avg=0.12403, loss=0.12334]

trial_003 train e001:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.41it/s, avg=0.12403, loss=0.12334]

trial_003 train e001:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:04<00:43,  1.41it/s, avg=0.12379, loss=0.10311]

trial_003 train e001:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.39it/s, avg=0.12379, loss=0.10311]

trial_003 train e001:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.39it/s, avg=0.12371, loss=0.11630]

trial_003 train e001:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:41,  1.42it/s, avg=0.12371, loss=0.11630]

trial_003 train e001:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:41,  1.42it/s, avg=0.12338, loss=0.09390]

trial_003 train e001:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:41,  1.40it/s, avg=0.12338, loss=0.09390]

trial_003 train e001:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:06<00:41,  1.40it/s, avg=0.12343, loss=0.12773]

trial_003 train e001:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:40,  1.40it/s, avg=0.12343, loss=0.12773]

trial_003 train e001:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:40,  1.40it/s, avg=0.12344, loss=0.12421]

trial_003 train e001:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:40,  1.40it/s, avg=0.12344, loss=0.12421]

trial_003 train e001:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:40,  1.40it/s, avg=0.12343, loss=0.12308]

trial_003 train e001:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:39,  1.38it/s, avg=0.12343, loss=0.12308]

trial_003 train e001:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:39,  1.38it/s, avg=0.12327, loss=0.10748]

trial_003 train e001:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:38,  1.39it/s, avg=0.12327, loss=0.10748]

trial_003 train e001:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:09<00:38,  1.39it/s, avg=0.12338, loss=0.13425]

trial_003 train e001:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.39it/s, avg=0.12338, loss=0.13425]

trial_003 train e001:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.39it/s, avg=0.12331, loss=0.11687]

trial_003 train e001:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.40it/s, avg=0.12331, loss=0.11687]

trial_003 train e001:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:37,  1.40it/s, avg=0.12328, loss=0.12010]

trial_003 train e001:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.40it/s, avg=0.12328, loss=0.12010]

trial_003 train e001:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:11<00:36,  1.40it/s, avg=0.12325, loss=0.12062]

trial_003 train e001:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:35,  1.41it/s, avg=0.12325, loss=0.12062]

trial_003 train e001:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:35,  1.41it/s, avg=0.12327, loss=0.12518]

trial_003 train e001:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:35,  1.37it/s, avg=0.12327, loss=0.12518]

trial_003 train e001:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:35,  1.37it/s, avg=0.12321, loss=0.11681]

trial_003 train e001:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.38it/s, avg=0.12321, loss=0.11681]

trial_003 train e001:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.38it/s, avg=0.12296, loss=0.09827]

trial_003 train e001:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:33,  1.39it/s, avg=0.12296, loss=0.09827]

trial_003 train e001:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:14<00:33,  1.39it/s, avg=0.12301, loss=0.12732]

trial_003 train e001:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.39it/s, avg=0.12301, loss=0.12732]

trial_003 train e001:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.39it/s, avg=0.12292, loss=0.11370]

trial_003 train e001:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:31,  1.41it/s, avg=0.12292, loss=0.11370]

trial_003 train e001:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:31,  1.41it/s, avg=0.12278, loss=0.10872]

trial_003 train e001:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.41it/s, avg=0.12278, loss=0.10872]

trial_003 train e001:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:16<00:31,  1.41it/s, avg=0.12281, loss=0.12584]

trial_003 train e001:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:30,  1.39it/s, avg=0.12281, loss=0.12584]

trial_003 train e001:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:30,  1.39it/s, avg=0.12279, loss=0.12010]

trial_003 train e001:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:29,  1.42it/s, avg=0.12279, loss=0.12010]

trial_003 train e001:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:29,  1.42it/s, avg=0.12284, loss=0.12889]

trial_003 train e001:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:29,  1.41it/s, avg=0.12284, loss=0.12889]

trial_003 train e001:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:29,  1.41it/s, avg=0.12273, loss=0.11051]

trial_003 train e001:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:27,  1.43it/s, avg=0.12273, loss=0.11051]

trial_003 train e001:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:19<00:27,  1.43it/s, avg=0.12263, loss=0.11220]

trial_003 train e001:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:27,  1.42it/s, avg=0.12263, loss=0.11220]

trial_003 train e001:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:27,  1.42it/s, avg=0.12268, loss=0.12746]

trial_003 train e001:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:26,  1.44it/s, avg=0.12268, loss=0.12746]

trial_003 train e001:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:26,  1.44it/s, avg=0.12263, loss=0.11792]

trial_003 train e001:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.42it/s, avg=0.12263, loss=0.11792]

trial_003 train e001:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:26,  1.42it/s, avg=0.12257, loss=0.11562]

trial_003 train e001:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.40it/s, avg=0.12257, loss=0.11562]

trial_003 train e001:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.40it/s, avg=0.12243, loss=0.10688]

trial_003 train e001:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.42it/s, avg=0.12243, loss=0.10688]

trial_003 train e001:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:24,  1.42it/s, avg=0.12234, loss=0.11116]

trial_003 train e001:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:24,  1.41it/s, avg=0.12234, loss=0.11116]

trial_003 train e001:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.41it/s, avg=0.12239, loss=0.12830]

trial_003 train e001:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:22,  1.44it/s, avg=0.12239, loss=0.12830]

trial_003 train e001:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:22,  1.44it/s, avg=0.12238, loss=0.12176]

trial_003 train e001:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:22,  1.41it/s, avg=0.12238, loss=0.12176]

trial_003 train e001:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:22,  1.41it/s, avg=0.12242, loss=0.12679]

trial_003 train e001:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:22,  1.41it/s, avg=0.12242, loss=0.12679]

trial_003 train e001:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.41it/s, avg=0.12230, loss=0.10836]

trial_003 train e001:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.41it/s, avg=0.12230, loss=0.10836]

trial_003 train e001:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:21,  1.41it/s, avg=0.12231, loss=0.12356]

trial_003 train e001:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.41it/s, avg=0.12231, loss=0.12356]

trial_003 train e001:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.41it/s, avg=0.12231, loss=0.12150]

trial_003 train e001:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:19,  1.43it/s, avg=0.12231, loss=0.12150]

trial_003 train e001:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:19,  1.43it/s, avg=0.12226, loss=0.11637]

trial_003 train e001:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.39it/s, avg=0.12226, loss=0.11637]

trial_003 train e001:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.39it/s, avg=0.12223, loss=0.11868]

trial_003 train e001:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:19,  1.36it/s, avg=0.12223, loss=0.11868]

trial_003 train e001:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:19,  1.36it/s, avg=0.12218, loss=0.11578]

trial_003 train e001:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.41it/s, avg=0.12218, loss=0.11578]

trial_003 train e001:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.41it/s, avg=0.12208, loss=0.11020]

trial_003 train e001:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:16,  1.42it/s, avg=0.12208, loss=0.11020]

trial_003 train e001:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:16,  1.42it/s, avg=0.12200, loss=0.11161]

trial_003 train e001:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.42it/s, avg=0.12200, loss=0.11161]

trial_003 train e001:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:31<00:16,  1.42it/s, avg=0.12188, loss=0.10763]

trial_003 train e001:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.40it/s, avg=0.12188, loss=0.10763]

trial_003 train e001:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.40it/s, avg=0.12195, loss=0.13027]

trial_003 train e001:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:14,  1.41it/s, avg=0.12195, loss=0.13027]

trial_003 train e001:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:14,  1.41it/s, avg=0.12204, loss=0.13327]

trial_003 train e001:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.41it/s, avg=0.12204, loss=0.13327]

trial_003 train e001:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.41it/s, avg=0.12197, loss=0.11278]

trial_003 train e001:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.37it/s, avg=0.12197, loss=0.11278]

trial_003 train e001:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:34<00:13,  1.37it/s, avg=0.12186, loss=0.10762]

trial_003 train e001:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:13,  1.36it/s, avg=0.12186, loss=0.10762]

trial_003 train e001:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:13,  1.36it/s, avg=0.12182, loss=0.11734]

trial_003 train e001:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.35it/s, avg=0.12182, loss=0.11734]

trial_003 train e001:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.35it/s, avg=0.12198, loss=0.14323]

trial_003 train e001:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.38it/s, avg=0.12198, loss=0.14323]

trial_003 train e001:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:36<00:11,  1.38it/s, avg=0.12186, loss=0.10573]

trial_003 train e001:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.37it/s, avg=0.12186, loss=0.10573]

trial_003 train e001:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.37it/s, avg=0.12180, loss=0.11355]

trial_003 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.38it/s, avg=0.12180, loss=0.11355]

trial_003 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.38it/s, avg=0.12172, loss=0.11135]

trial_003 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.37it/s, avg=0.12172, loss=0.11135]

trial_003 train e001:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.37it/s, avg=0.12166, loss=0.11311]

trial_003 train e001:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.36it/s, avg=0.12166, loss=0.11311]

trial_003 train e001:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:39<00:08,  1.36it/s, avg=0.12168, loss=0.12485]

trial_003 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:08,  1.37it/s, avg=0.12168, loss=0.12485]

trial_003 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:08,  1.37it/s, avg=0.12171, loss=0.12504]

trial_003 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.40it/s, avg=0.12171, loss=0.12504]

trial_003 train e001:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.40it/s, avg=0.12164, loss=0.11280]

trial_003 train e001:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.40it/s, avg=0.12164, loss=0.11280]

trial_003 train e001:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.40it/s, avg=0.12173, loss=0.13360]

trial_003 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.41it/s, avg=0.12173, loss=0.13360]

trial_003 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.41it/s, avg=0.12169, loss=0.11553]

trial_003 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:04,  1.42it/s, avg=0.12169, loss=0.11553]

trial_003 train e001:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:04,  1.42it/s, avg=0.12169, loss=0.12287]

trial_003 train e001:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.42it/s, avg=0.12169, loss=0.12287]

trial_003 train e001:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.42it/s, avg=0.12171, loss=0.12395]

trial_003 train e001:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.43it/s, avg=0.12171, loss=0.12395]

trial_003 train e001:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:44<00:03,  1.43it/s, avg=0.12163, loss=0.11013]

trial_003 train e001:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.38it/s, avg=0.12163, loss=0.11013]

trial_003 train e001:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.38it/s, avg=0.12148, loss=0.09944]

trial_003 train e001:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.39it/s, avg=0.12148, loss=0.09944]

trial_003 train e001:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.39it/s, avg=0.12133, loss=0.09922]

trial_003 train e001:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.39it/s, avg=0.12133, loss=0.09922]

trial_003 train e001:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.39it/s, avg=0.12126, loss=0.11168]

trial_003 train e001:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.39it/s, avg=0.12126, loss=0.11168]

trial_003 train e001:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.39it/s, avg=0.12129, loss=0.13097]

trial_003 train e001: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:46<00:00,  1.69it/s, avg=0.12129, loss=0.13097]

trial_003 val e001:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e001:   2%|██▌                                                                                                                          | 1/50 [00:00<00:20,  2.44it/s]

trial_003 val e001:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.44it/s]

trial_003 val e001:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.46it/s]

trial_003 val e001:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.45it/s]

trial_003 val e001:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.46it/s]

trial_003 val e001:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.46it/s]

trial_003 val e001:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.43it/s]

trial_003 val e001:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.38it/s]

trial_003 val e001:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.38it/s]

trial_003 val e001:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.39it/s]

trial_003 val e001:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.42it/s]

trial_003 val e001:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.43it/s]

trial_003 val e001:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.43it/s]

trial_003 val e001:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.44it/s]

trial_003 val e001:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.45it/s]

trial_003 val e001:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.45it/s]

trial_003 val e001:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.46it/s]

trial_003 val e001:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:12,  2.46it/s]

trial_003 val e001:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.47it/s]

trial_003 val e001:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.46it/s]

trial_003 val e001:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.44it/s]

trial_003 val e001:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.42it/s]

trial_003 val e001:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.43it/s]

trial_003 val e001:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.44it/s]

trial_003 val e001:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.44it/s]

trial_003 val e001:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.44it/s]

trial_003 val e001:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.45it/s]

trial_003 val e001:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.46it/s]

trial_003 val e001:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.45it/s]

trial_003 val e001:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.44it/s]

trial_003 val e001:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.41it/s]

trial_003 val e001:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.42it/s]

trial_003 val e001:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.42it/s]

trial_003 val e001:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.40it/s]

trial_003 val e001:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.37it/s]

trial_003 val e001:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.39it/s]

trial_003 val e001:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.40it/s]

trial_003 val e001:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.42it/s]

trial_003 val e001:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.43it/s]

trial_003 val e001:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.43it/s]

trial_003 val e001:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.44it/s]

trial_003 val e001:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.45it/s]

trial_003 val e001:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.45it/s]

trial_003 val e001:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.43it/s]

trial_003 val e001:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.43it/s]

trial_003 val e001:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.42it/s]

trial_003 val e001:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.41it/s]

trial_003 val e001:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.42it/s]

trial_003 val e001:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.44it/s]

trial_003 val e001: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.46it/s]

[2026-05-28 21:07:17] [trial_003] epoch=001 | train_loss=0.121287 | val_MAE=0.116468 | val_S=0.883532 | best_S=0.883532 @epoch=1 | patience=0/5

[trial_003] epochs:   1%|█▏                                                                                                                       | 1/100 [02:08<3:31:21, 128.09s/it]

trial_003 train e002:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e002:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.12797, loss=0.12797]

trial_003 train e002:   1%|▋                                                                                              | 1/149 [00:00<01:48,  1.37it/s, avg=0.12797, loss=0.12797]

trial_003 train e002:   1%|▋                                                                                              | 1/149 [00:01<01:48,  1.37it/s, avg=0.11687, loss=0.10576]

trial_003 train e002:   1%|█▎                                                                                             | 2/149 [00:01<01:47,  1.37it/s, avg=0.11687, loss=0.10576]

trial_003 train e002:   1%|█▎                                                                                             | 2/149 [00:02<01:47,  1.37it/s, avg=0.11931, loss=0.12421]

trial_003 train e002:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.11931, loss=0.12421]

trial_003 train e002:   2%|█▉                                                                                             | 3/149 [00:02<01:47,  1.36it/s, avg=0.11519, loss=0.10280]

trial_003 train e002:   3%|██▌                                                                                            | 4/149 [00:02<01:47,  1.35it/s, avg=0.11519, loss=0.10280]

trial_003 train e002:   3%|██▌                                                                                            | 4/149 [00:03<01:47,  1.35it/s, avg=0.11492, loss=0.11386]

trial_003 train e002:   3%|███▏                                                                                           | 5/149 [00:03<01:47,  1.34it/s, avg=0.11492, loss=0.11386]

trial_003 train e002:   3%|███▏                                                                                           | 5/149 [00:04<01:47,  1.34it/s, avg=0.11545, loss=0.11811]

trial_003 train e002:   4%|███▊                                                                                           | 6/149 [00:04<01:43,  1.38it/s, avg=0.11545, loss=0.11811]

trial_003 train e002:   4%|███▊                                                                                           | 6/149 [00:05<01:43,  1.38it/s, avg=0.11707, loss=0.12679]

trial_003 train e002:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.11707, loss=0.12679]

trial_003 train e002:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.38it/s, avg=0.11608, loss=0.10913]

trial_003 train e002:   5%|█████                                                                                          | 8/149 [00:05<01:39,  1.42it/s, avg=0.11608, loss=0.10913]

trial_003 train e002:   5%|█████                                                                                          | 8/149 [00:06<01:39,  1.42it/s, avg=0.11744, loss=0.12829]

trial_003 train e002:   6%|█████▋                                                                                         | 9/149 [00:06<01:40,  1.39it/s, avg=0.11744, loss=0.12829]

trial_003 train e002:   6%|█████▋                                                                                         | 9/149 [00:07<01:40,  1.39it/s, avg=0.11716, loss=0.11471]

trial_003 train e002:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.42it/s, avg=0.11716, loss=0.11471]

trial_003 train e002:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.42it/s, avg=0.11788, loss=0.12504]

trial_003 train e002:   7%|██████▉                                                                                       | 11/149 [00:07<01:37,  1.42it/s, avg=0.11788, loss=0.12504]

trial_003 train e002:   7%|██████▉                                                                                       | 11/149 [00:08<01:37,  1.42it/s, avg=0.11830, loss=0.12290]

trial_003 train e002:   8%|███████▌                                                                                      | 12/149 [00:08<01:36,  1.42it/s, avg=0.11830, loss=0.12290]

trial_003 train e002:   8%|███████▌                                                                                      | 12/149 [00:09<01:36,  1.42it/s, avg=0.11887, loss=0.12581]

trial_003 train e002:   9%|████████▏                                                                                     | 13/149 [00:09<01:36,  1.41it/s, avg=0.11887, loss=0.12581]

trial_003 train e002:   9%|████████▏                                                                                     | 13/149 [00:10<01:36,  1.41it/s, avg=0.11799, loss=0.10643]

trial_003 train e002:   9%|████████▊                                                                                     | 14/149 [00:10<01:35,  1.41it/s, avg=0.11799, loss=0.10643]

trial_003 train e002:   9%|████████▊                                                                                     | 14/149 [00:10<01:35,  1.41it/s, avg=0.11720, loss=0.10617]

trial_003 train e002:  10%|█████████▍                                                                                    | 15/149 [00:10<01:36,  1.39it/s, avg=0.11720, loss=0.10617]

trial_003 train e002:  10%|█████████▍                                                                                    | 15/149 [00:11<01:36,  1.39it/s, avg=0.11632, loss=0.10313]

trial_003 train e002:  11%|██████████                                                                                    | 16/149 [00:11<01:34,  1.41it/s, avg=0.11632, loss=0.10313]

trial_003 train e002:  11%|██████████                                                                                    | 16/149 [00:12<01:34,  1.41it/s, avg=0.11660, loss=0.12107]

trial_003 train e002:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.39it/s, avg=0.11660, loss=0.12107]

trial_003 train e002:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.39it/s, avg=0.11624, loss=0.11022]

trial_003 train e002:  12%|███████████▎                                                                                  | 18/149 [00:12<01:34,  1.39it/s, avg=0.11624, loss=0.11022]

trial_003 train e002:  12%|███████████▎                                                                                  | 18/149 [00:13<01:34,  1.39it/s, avg=0.11690, loss=0.12866]

trial_003 train e002:  13%|███████████▉                                                                                  | 19/149 [00:13<01:31,  1.43it/s, avg=0.11690, loss=0.12866]

trial_003 train e002:  13%|███████████▉                                                                                  | 19/149 [00:14<01:31,  1.43it/s, avg=0.11689, loss=0.11665]

trial_003 train e002:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.41it/s, avg=0.11689, loss=0.11665]

trial_003 train e002:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.41it/s, avg=0.11618, loss=0.10204]

trial_003 train e002:  14%|█████████████▏                                                                                | 21/149 [00:14<01:29,  1.42it/s, avg=0.11618, loss=0.10204]

trial_003 train e002:  14%|█████████████▏                                                                                | 21/149 [00:15<01:29,  1.42it/s, avg=0.11608, loss=0.11397]

trial_003 train e002:  15%|█████████████▉                                                                                | 22/149 [00:15<01:28,  1.43it/s, avg=0.11608, loss=0.11397]

trial_003 train e002:  15%|█████████████▉                                                                                | 22/149 [00:16<01:28,  1.43it/s, avg=0.11557, loss=0.10436]

trial_003 train e002:  15%|██████████████▌                                                                               | 23/149 [00:16<01:24,  1.48it/s, avg=0.11557, loss=0.10436]

trial_003 train e002:  15%|██████████████▌                                                                               | 23/149 [00:17<01:24,  1.48it/s, avg=0.11576, loss=0.12009]

trial_003 train e002:  16%|███████████████▏                                                                              | 24/149 [00:17<01:25,  1.46it/s, avg=0.11576, loss=0.12009]

trial_003 train e002:  16%|███████████████▏                                                                              | 24/149 [00:17<01:25,  1.46it/s, avg=0.11512, loss=0.09991]

trial_003 train e002:  17%|███████████████▊                                                                              | 25/149 [00:17<01:27,  1.42it/s, avg=0.11512, loss=0.09991]

trial_003 train e002:  17%|███████████████▊                                                                              | 25/149 [00:18<01:27,  1.42it/s, avg=0.11547, loss=0.12405]

trial_003 train e002:  17%|████████████████▍                                                                             | 26/149 [00:18<01:25,  1.43it/s, avg=0.11547, loss=0.12405]

trial_003 train e002:  17%|████████████████▍                                                                             | 26/149 [00:19<01:25,  1.43it/s, avg=0.11556, loss=0.11811]

trial_003 train e002:  18%|█████████████████                                                                             | 27/149 [00:19<01:26,  1.41it/s, avg=0.11556, loss=0.11811]

trial_003 train e002:  18%|█████████████████                                                                             | 27/149 [00:19<01:26,  1.41it/s, avg=0.11567, loss=0.11837]

trial_003 train e002:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:26,  1.41it/s, avg=0.11567, loss=0.11837]

trial_003 train e002:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:26,  1.41it/s, avg=0.11593, loss=0.12339]

trial_003 train e002:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:25,  1.40it/s, avg=0.11593, loss=0.12339]

trial_003 train e002:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:25,  1.40it/s, avg=0.11599, loss=0.11764]

trial_003 train e002:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:25,  1.39it/s, avg=0.11599, loss=0.11764]

trial_003 train e002:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:25,  1.39it/s, avg=0.11571, loss=0.10734]

trial_003 train e002:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:22,  1.43it/s, avg=0.11571, loss=0.10734]

trial_003 train e002:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:22,  1.43it/s, avg=0.11539, loss=0.10551]

trial_003 train e002:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:20,  1.46it/s, avg=0.11539, loss=0.10551]

trial_003 train e002:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:20,  1.46it/s, avg=0.11511, loss=0.10617]

trial_003 train e002:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:17,  1.50it/s, avg=0.11511, loss=0.10617]

trial_003 train e002:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:17,  1.50it/s, avg=0.11502, loss=0.11193]

trial_003 train e002:  23%|█████████████████████▍                                                                        | 34/149 [00:23<01:15,  1.53it/s, avg=0.11502, loss=0.11193]

trial_003 train e002:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:15,  1.53it/s, avg=0.11496, loss=0.11295]

trial_003 train e002:  23%|██████████████████████                                                                        | 35/149 [00:24<01:16,  1.48it/s, avg=0.11496, loss=0.11295]

trial_003 train e002:  23%|██████████████████████                                                                        | 35/149 [00:25<01:16,  1.48it/s, avg=0.11499, loss=0.11609]

trial_003 train e002:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:14,  1.53it/s, avg=0.11499, loss=0.11609]

trial_003 train e002:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:14,  1.53it/s, avg=0.11504, loss=0.11669]

trial_003 train e002:  25%|███████████████████████▎                                                                      | 37/149 [00:25<01:14,  1.50it/s, avg=0.11504, loss=0.11669]

trial_003 train e002:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:14,  1.50it/s, avg=0.11509, loss=0.11722]

trial_003 train e002:  26%|███████████████████████▉                                                                      | 38/149 [00:26<01:13,  1.52it/s, avg=0.11509, loss=0.11722]

trial_003 train e002:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:13,  1.52it/s, avg=0.11552, loss=0.13165]

trial_003 train e002:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:12,  1.52it/s, avg=0.11552, loss=0.13165]

trial_003 train e002:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:12,  1.52it/s, avg=0.11556, loss=0.11724]

trial_003 train e002:  27%|█████████████████████████▏                                                                    | 40/149 [00:27<01:11,  1.52it/s, avg=0.11556, loss=0.11724]

trial_003 train e002:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:11,  1.52it/s, avg=0.11546, loss=0.11160]

trial_003 train e002:  28%|█████████████████████████▊                                                                    | 41/149 [00:28<01:12,  1.48it/s, avg=0.11546, loss=0.11160]

trial_003 train e002:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:12,  1.48it/s, avg=0.11570, loss=0.12516]

trial_003 train e002:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:12,  1.47it/s, avg=0.11570, loss=0.12516]

trial_003 train e002:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:12,  1.47it/s, avg=0.11615, loss=0.13543]

trial_003 train e002:  29%|███████████████████████████▏                                                                  | 43/149 [00:29<01:11,  1.48it/s, avg=0.11615, loss=0.13543]

trial_003 train e002:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:11,  1.48it/s, avg=0.11583, loss=0.10189]

trial_003 train e002:  30%|███████████████████████████▊                                                                  | 44/149 [00:30<01:11,  1.46it/s, avg=0.11583, loss=0.10189]

trial_003 train e002:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:11,  1.46it/s, avg=0.11566, loss=0.10837]

trial_003 train e002:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:11,  1.45it/s, avg=0.11566, loss=0.10837]

trial_003 train e002:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:11,  1.45it/s, avg=0.11534, loss=0.10056]

trial_003 train e002:  31%|█████████████████████████████                                                                 | 46/149 [00:31<01:09,  1.49it/s, avg=0.11534, loss=0.10056]

trial_003 train e002:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:09,  1.49it/s, avg=0.11536, loss=0.11628]

trial_003 train e002:  32%|█████████████████████████████▋                                                                | 47/149 [00:32<01:09,  1.47it/s, avg=0.11536, loss=0.11628]

trial_003 train e002:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:09,  1.47it/s, avg=0.11535, loss=0.11520]

trial_003 train e002:  32%|██████████████████████████████▎                                                               | 48/149 [00:33<01:07,  1.50it/s, avg=0.11535, loss=0.11520]

trial_003 train e002:  32%|██████████████████████████████▎                                                               | 48/149 [00:33<01:07,  1.50it/s, avg=0.11520, loss=0.10805]

trial_003 train e002:  33%|██████████████████████████████▉                                                               | 49/149 [00:33<01:05,  1.52it/s, avg=0.11520, loss=0.10805]

trial_003 train e002:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:05,  1.52it/s, avg=0.11534, loss=0.12225]

trial_003 train e002:  34%|███████████████████████████████▌                                                              | 50/149 [00:34<01:06,  1.50it/s, avg=0.11534, loss=0.12225]

trial_003 train e002:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:06,  1.50it/s, avg=0.11525, loss=0.11056]

trial_003 train e002:  34%|████████████████████████████████▏                                                             | 51/149 [00:35<01:05,  1.49it/s, avg=0.11525, loss=0.11056]

trial_003 train e002:  34%|████████████████████████████████▏                                                             | 51/149 [00:35<01:05,  1.49it/s, avg=0.11502, loss=0.10326]

trial_003 train e002:  35%|████████████████████████████████▊                                                             | 52/149 [00:35<01:04,  1.50it/s, avg=0.11502, loss=0.10326]

trial_003 train e002:  35%|████████████████████████████████▊                                                             | 52/149 [00:36<01:04,  1.50it/s, avg=0.11488, loss=0.10748]

trial_003 train e002:  36%|█████████████████████████████████▍                                                            | 53/149 [00:36<01:05,  1.47it/s, avg=0.11488, loss=0.10748]

trial_003 train e002:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:05,  1.47it/s, avg=0.11500, loss=0.12135]

trial_003 train e002:  36%|██████████████████████████████████                                                            | 54/149 [00:37<01:03,  1.50it/s, avg=0.11500, loss=0.12135]

trial_003 train e002:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:03,  1.50it/s, avg=0.11480, loss=0.10412]

trial_003 train e002:  37%|██████████████████████████████████▋                                                           | 55/149 [00:38<01:04,  1.46it/s, avg=0.11480, loss=0.10412]

trial_003 train e002:  37%|██████████████████████████████████▋                                                           | 55/149 [00:38<01:04,  1.46it/s, avg=0.11479, loss=0.11438]

trial_003 train e002:  38%|███████████████████████████████████▎                                                          | 56/149 [00:38<01:04,  1.44it/s, avg=0.11479, loss=0.11438]

trial_003 train e002:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:04,  1.44it/s, avg=0.11493, loss=0.12240]

trial_003 train e002:  38%|███████████████████████████████████▉                                                          | 57/149 [00:39<01:03,  1.44it/s, avg=0.11493, loss=0.12240]

trial_003 train e002:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:03,  1.44it/s, avg=0.11488, loss=0.11234]

trial_003 train e002:  39%|████████████████████████████████████▌                                                         | 58/149 [00:40<01:04,  1.42it/s, avg=0.11488, loss=0.11234]

trial_003 train e002:  39%|████████████████████████████████████▌                                                         | 58/149 [00:40<01:04,  1.42it/s, avg=0.11497, loss=0.12013]

trial_003 train e002:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:40<01:00,  1.48it/s, avg=0.11497, loss=0.12013]

trial_003 train e002:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:41<01:00,  1.48it/s, avg=0.11504, loss=0.11937]

trial_003 train e002:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:41<00:59,  1.50it/s, avg=0.11504, loss=0.11937]

trial_003 train e002:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<00:59,  1.50it/s, avg=0.11502, loss=0.11354]

trial_003 train e002:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:42<00:59,  1.48it/s, avg=0.11502, loss=0.11354]

trial_003 train e002:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:42<00:59,  1.48it/s, avg=0.11499, loss=0.11321]

trial_003 train e002:  42%|███████████████████████████████████████                                                       | 62/149 [00:42<00:58,  1.50it/s, avg=0.11499, loss=0.11321]

trial_003 train e002:  42%|███████████████████████████████████████                                                       | 62/149 [00:43<00:58,  1.50it/s, avg=0.11511, loss=0.12287]

trial_003 train e002:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:43<00:58,  1.48it/s, avg=0.11511, loss=0.12287]

trial_003 train e002:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<00:58,  1.48it/s, avg=0.11516, loss=0.11825]

trial_003 train e002:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:44<00:57,  1.47it/s, avg=0.11516, loss=0.11825]

trial_003 train e002:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:44<00:57,  1.47it/s, avg=0.11532, loss=0.12511]

trial_003 train e002:  44%|█████████████████████████████████████████                                                     | 65/149 [00:44<00:55,  1.52it/s, avg=0.11532, loss=0.12511]

trial_003 train e002:  44%|█████████████████████████████████████████                                                     | 65/149 [00:45<00:55,  1.52it/s, avg=0.11518, loss=0.10645]

trial_003 train e002:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:45<00:52,  1.58it/s, avg=0.11518, loss=0.10645]

trial_003 train e002:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<00:52,  1.58it/s, avg=0.11493, loss=0.09797]

trial_003 train e002:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:46<00:52,  1.57it/s, avg=0.11493, loss=0.09797]

trial_003 train e002:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:46<00:52,  1.57it/s, avg=0.11479, loss=0.10573]

trial_003 train e002:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:46<00:51,  1.57it/s, avg=0.11479, loss=0.10573]

trial_003 train e002:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:47<00:51,  1.57it/s, avg=0.11472, loss=0.10985]

trial_003 train e002:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:47<00:52,  1.53it/s, avg=0.11472, loss=0.10985]

trial_003 train e002:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:48<00:52,  1.53it/s, avg=0.11460, loss=0.10610]

trial_003 train e002:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:48<00:52,  1.49it/s, avg=0.11460, loss=0.10610]

trial_003 train e002:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:48<00:52,  1.49it/s, avg=0.11441, loss=0.10127]

trial_003 train e002:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:48<00:50,  1.53it/s, avg=0.11441, loss=0.10127]

trial_003 train e002:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:49<00:50,  1.53it/s, avg=0.11446, loss=0.11839]

trial_003 train e002:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:49<00:50,  1.52it/s, avg=0.11446, loss=0.11839]

trial_003 train e002:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:49<00:50,  1.52it/s, avg=0.11464, loss=0.12753]

trial_003 train e002:  49%|██████████████████████████████████████████████                                                | 73/149 [00:49<00:48,  1.57it/s, avg=0.11464, loss=0.12753]

trial_003 train e002:  49%|██████████████████████████████████████████████                                                | 73/149 [00:50<00:48,  1.57it/s, avg=0.11475, loss=0.12246]

trial_003 train e002:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:50<00:47,  1.59it/s, avg=0.11475, loss=0.12246]

trial_003 train e002:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:51<00:47,  1.59it/s, avg=0.11461, loss=0.10428]

trial_003 train e002:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:51<00:45,  1.61it/s, avg=0.11461, loss=0.10428]

trial_003 train e002:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:51<00:45,  1.61it/s, avg=0.11443, loss=0.10082]

trial_003 train e002:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:51<00:45,  1.61it/s, avg=0.11443, loss=0.10082]

trial_003 train e002:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:52<00:45,  1.61it/s, avg=0.11427, loss=0.10233]

trial_003 train e002:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:52<00:45,  1.57it/s, avg=0.11427, loss=0.10233]

trial_003 train e002:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:53<00:45,  1.57it/s, avg=0.11443, loss=0.12703]

trial_003 train e002:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:53<00:46,  1.53it/s, avg=0.11443, loss=0.12703]

trial_003 train e002:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:53<00:46,  1.53it/s, avg=0.11473, loss=0.13817]

trial_003 train e002:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:53<00:45,  1.54it/s, avg=0.11473, loss=0.13817]

trial_003 train e002:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:54<00:45,  1.54it/s, avg=0.11463, loss=0.10607]

trial_003 train e002:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:54<00:45,  1.52it/s, avg=0.11463, loss=0.10607]

trial_003 train e002:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:55<00:45,  1.52it/s, avg=0.11457, loss=0.11004]

trial_003 train e002:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:55<00:45,  1.50it/s, avg=0.11457, loss=0.11004]

trial_003 train e002:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:55<00:45,  1.50it/s, avg=0.11447, loss=0.10630]

trial_003 train e002:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:55<00:44,  1.50it/s, avg=0.11447, loss=0.10630]

trial_003 train e002:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:56<00:44,  1.50it/s, avg=0.11460, loss=0.12537]

trial_003 train e002:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:56<00:43,  1.53it/s, avg=0.11460, loss=0.12537]

trial_003 train e002:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:57<00:43,  1.53it/s, avg=0.11464, loss=0.11812]

trial_003 train e002:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:57<00:41,  1.56it/s, avg=0.11464, loss=0.11812]

trial_003 train e002:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:57<00:41,  1.56it/s, avg=0.11458, loss=0.10929]

trial_003 train e002:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [00:57<00:41,  1.54it/s, avg=0.11458, loss=0.10929]

trial_003 train e002:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [00:58<00:41,  1.54it/s, avg=0.11453, loss=0.11009]

trial_003 train e002:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [00:58<00:41,  1.52it/s, avg=0.11453, loss=0.11009]

trial_003 train e002:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [00:58<00:41,  1.52it/s, avg=0.11448, loss=0.11087]

trial_003 train e002:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [00:58<00:39,  1.55it/s, avg=0.11448, loss=0.11087]

trial_003 train e002:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [00:59<00:39,  1.55it/s, avg=0.11446, loss=0.11199]

trial_003 train e002:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [00:59<00:39,  1.55it/s, avg=0.11446, loss=0.11199]

trial_003 train e002:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:00<00:39,  1.55it/s, avg=0.11439, loss=0.10829]

trial_003 train e002:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:00<00:37,  1.61it/s, avg=0.11439, loss=0.10829]

trial_003 train e002:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:00<00:37,  1.61it/s, avg=0.11438, loss=0.11362]

trial_003 train e002:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:00<00:37,  1.56it/s, avg=0.11438, loss=0.11362]

trial_003 train e002:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:01<00:37,  1.56it/s, avg=0.11437, loss=0.11343]

trial_003 train e002:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:01<00:38,  1.52it/s, avg=0.11437, loss=0.11343]

trial_003 train e002:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:02<00:38,  1.52it/s, avg=0.11437, loss=0.11460]

trial_003 train e002:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:02<00:38,  1.48it/s, avg=0.11437, loss=0.11460]

trial_003 train e002:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:03<00:38,  1.48it/s, avg=0.11444, loss=0.12122]

trial_003 train e002:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:03<00:38,  1.44it/s, avg=0.11444, loss=0.12122]

trial_003 train e002:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:03<00:38,  1.44it/s, avg=0.11444, loss=0.11426]

trial_003 train e002:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:03<00:38,  1.44it/s, avg=0.11444, loss=0.11426]

trial_003 train e002:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:04<00:38,  1.44it/s, avg=0.11420, loss=0.09113]

trial_003 train e002:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:04<00:38,  1.39it/s, avg=0.11420, loss=0.09113]

trial_003 train e002:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:05<00:38,  1.39it/s, avg=0.11420, loss=0.11473]

trial_003 train e002:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:05<00:37,  1.42it/s, avg=0.11420, loss=0.11473]

trial_003 train e002:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:05<00:37,  1.42it/s, avg=0.11421, loss=0.11454]

trial_003 train e002:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:05<00:37,  1.40it/s, avg=0.11421, loss=0.11454]

trial_003 train e002:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:06<00:37,  1.40it/s, avg=0.11414, loss=0.10747]

trial_003 train e002:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:06<00:36,  1.40it/s, avg=0.11414, loss=0.10747]

trial_003 train e002:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:07<00:36,  1.40it/s, avg=0.11410, loss=0.11014]

trial_003 train e002:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:07<00:35,  1.41it/s, avg=0.11410, loss=0.11014]

trial_003 train e002:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:08<00:35,  1.41it/s, avg=0.11414, loss=0.11799]

trial_003 train e002:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:08<00:35,  1.39it/s, avg=0.11414, loss=0.11799]

trial_003 train e002:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:08<00:35,  1.39it/s, avg=0.11412, loss=0.11305]

trial_003 train e002:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:08<00:34,  1.41it/s, avg=0.11412, loss=0.11305]

trial_003 train e002:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:09<00:34,  1.41it/s, avg=0.11417, loss=0.11836]

trial_003 train e002:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:09<00:33,  1.41it/s, avg=0.11417, loss=0.11836]

trial_003 train e002:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:10<00:33,  1.41it/s, avg=0.11436, loss=0.13455]

trial_003 train e002:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:10<00:33,  1.36it/s, avg=0.11436, loss=0.13455]

trial_003 train e002:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:10<00:33,  1.36it/s, avg=0.11434, loss=0.11236]

trial_003 train e002:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:10<00:33,  1.36it/s, avg=0.11434, loss=0.11236]

trial_003 train e002:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:11<00:33,  1.36it/s, avg=0.11436, loss=0.11637]

trial_003 train e002:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:11<00:32,  1.34it/s, avg=0.11436, loss=0.11637]

trial_003 train e002:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:12<00:32,  1.34it/s, avg=0.11437, loss=0.11519]

trial_003 train e002:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:12<00:32,  1.34it/s, avg=0.11437, loss=0.11519]

trial_003 train e002:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:13<00:32,  1.34it/s, avg=0.11421, loss=0.09754]

trial_003 train e002:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:13<00:30,  1.37it/s, avg=0.11421, loss=0.09754]

trial_003 train e002:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:13<00:30,  1.37it/s, avg=0.11408, loss=0.10002]

trial_003 train e002:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:13<00:29,  1.39it/s, avg=0.11408, loss=0.10002]

trial_003 train e002:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:14<00:29,  1.39it/s, avg=0.11409, loss=0.11431]

trial_003 train e002:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:14<00:28,  1.39it/s, avg=0.11409, loss=0.11431]

trial_003 train e002:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:15<00:28,  1.39it/s, avg=0.11420, loss=0.12660]

trial_003 train e002:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:15<00:28,  1.38it/s, avg=0.11420, loss=0.12660]

trial_003 train e002:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:16<00:28,  1.38it/s, avg=0.11424, loss=0.11868]

trial_003 train e002:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:16<00:27,  1.38it/s, avg=0.11424, loss=0.11868]

trial_003 train e002:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:16<00:27,  1.38it/s, avg=0.11425, loss=0.11542]

trial_003 train e002:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:16<00:26,  1.38it/s, avg=0.11425, loss=0.11542]

trial_003 train e002:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:17<00:26,  1.38it/s, avg=0.11415, loss=0.10298]

trial_003 train e002:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:17<00:25,  1.39it/s, avg=0.11415, loss=0.10298]

trial_003 train e002:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:18<00:25,  1.39it/s, avg=0.11418, loss=0.11776]

trial_003 train e002:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:18<00:25,  1.39it/s, avg=0.11418, loss=0.11776]

trial_003 train e002:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:18<00:25,  1.39it/s, avg=0.11403, loss=0.09690]

trial_003 train e002:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:18<00:24,  1.40it/s, avg=0.11403, loss=0.09690]

trial_003 train e002:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:19<00:24,  1.40it/s, avg=0.11415, loss=0.12813]

trial_003 train e002:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:19<00:23,  1.40it/s, avg=0.11415, loss=0.12813]

trial_003 train e002:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:20<00:23,  1.40it/s, avg=0.11408, loss=0.10523]

trial_003 train e002:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:20<00:22,  1.40it/s, avg=0.11408, loss=0.10523]

trial_003 train e002:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:21<00:22,  1.40it/s, avg=0.11417, loss=0.12519]

trial_003 train e002:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:21<00:22,  1.39it/s, avg=0.11417, loss=0.12519]

trial_003 train e002:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:21<00:22,  1.39it/s, avg=0.11429, loss=0.12877]

trial_003 train e002:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:21<00:21,  1.41it/s, avg=0.11429, loss=0.12877]

trial_003 train e002:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:22<00:21,  1.41it/s, avg=0.11419, loss=0.10209]

trial_003 train e002:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:22<00:20,  1.39it/s, avg=0.11419, loss=0.10209]

trial_003 train e002:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:23<00:20,  1.39it/s, avg=0.11399, loss=0.09014]

trial_003 train e002:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:23<00:20,  1.38it/s, avg=0.11399, loss=0.09014]

trial_003 train e002:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:23<00:20,  1.38it/s, avg=0.11407, loss=0.12398]

trial_003 train e002:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:23<00:19,  1.38it/s, avg=0.11407, loss=0.12398]

trial_003 train e002:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:24<00:19,  1.38it/s, avg=0.11395, loss=0.09857]

trial_003 train e002:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:24<00:19,  1.36it/s, avg=0.11395, loss=0.09857]

trial_003 train e002:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:25<00:19,  1.36it/s, avg=0.11393, loss=0.11121]

trial_003 train e002:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:25<00:18,  1.37it/s, avg=0.11393, loss=0.11121]

trial_003 train e002:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:26<00:18,  1.37it/s, avg=0.11393, loss=0.11427]

trial_003 train e002:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:26<00:17,  1.38it/s, avg=0.11393, loss=0.11427]

trial_003 train e002:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:26<00:17,  1.38it/s, avg=0.11382, loss=0.09972]

trial_003 train e002:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:26<00:16,  1.38it/s, avg=0.11382, loss=0.09972]

trial_003 train e002:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:27<00:16,  1.38it/s, avg=0.11384, loss=0.11642]

trial_003 train e002:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:27<00:16,  1.35it/s, avg=0.11384, loss=0.11642]

trial_003 train e002:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:28<00:16,  1.35it/s, avg=0.11380, loss=0.10919]

trial_003 train e002:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:28<00:15,  1.38it/s, avg=0.11380, loss=0.10919]

trial_003 train e002:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:29<00:15,  1.38it/s, avg=0.11368, loss=0.09813]

trial_003 train e002:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:29<00:14,  1.38it/s, avg=0.11368, loss=0.09813]

trial_003 train e002:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:29<00:14,  1.38it/s, avg=0.11374, loss=0.12098]

trial_003 train e002:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:29<00:13,  1.37it/s, avg=0.11374, loss=0.12098]

trial_003 train e002:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:30<00:13,  1.37it/s, avg=0.11373, loss=0.11245]

trial_003 train e002:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:30<00:13,  1.36it/s, avg=0.11373, loss=0.11245]

trial_003 train e002:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:31<00:13,  1.36it/s, avg=0.11367, loss=0.10625]

trial_003 train e002:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:31<00:12,  1.39it/s, avg=0.11367, loss=0.10625]

trial_003 train e002:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:31<00:12,  1.39it/s, avg=0.11368, loss=0.11482]

trial_003 train e002:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:31<00:11,  1.41it/s, avg=0.11368, loss=0.11482]

trial_003 train e002:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:32<00:11,  1.41it/s, avg=0.11379, loss=0.12910]

trial_003 train e002:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:32<00:10,  1.44it/s, avg=0.11379, loss=0.12910]

trial_003 train e002:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:33<00:10,  1.44it/s, avg=0.11379, loss=0.11272]

trial_003 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:33<00:09,  1.47it/s, avg=0.11379, loss=0.11272]

trial_003 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:33<00:09,  1.47it/s, avg=0.11370, loss=0.10260]

trial_003 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:33<00:08,  1.47it/s, avg=0.11370, loss=0.10260]

trial_003 train e002:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:34<00:08,  1.47it/s, avg=0.11358, loss=0.09635]

trial_003 train e002:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:34<00:08,  1.50it/s, avg=0.11358, loss=0.09635]

trial_003 train e002:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:35<00:08,  1.50it/s, avg=0.11357, loss=0.11248]

trial_003 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:35<00:07,  1.52it/s, avg=0.11357, loss=0.11248]

trial_003 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:35<00:07,  1.52it/s, avg=0.11356, loss=0.11214]

trial_003 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:35<00:06,  1.55it/s, avg=0.11356, loss=0.11214]

trial_003 train e002:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:36<00:06,  1.55it/s, avg=0.11350, loss=0.10485]

trial_003 train e002:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:36<00:05,  1.56it/s, avg=0.11350, loss=0.10485]

trial_003 train e002:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:37<00:05,  1.56it/s, avg=0.11343, loss=0.10492]

trial_003 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:37<00:05,  1.57it/s, avg=0.11343, loss=0.10492]

trial_003 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:37<00:05,  1.57it/s, avg=0.11342, loss=0.11130]

trial_003 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:37<00:04,  1.58it/s, avg=0.11342, loss=0.11130]

trial_003 train e002:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:38<00:04,  1.58it/s, avg=0.11346, loss=0.11871]

trial_003 train e002:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:38<00:03,  1.59it/s, avg=0.11346, loss=0.11871]

trial_003 train e002:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:38<00:03,  1.59it/s, avg=0.11339, loss=0.10361]

trial_003 train e002:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:38<00:03,  1.58it/s, avg=0.11339, loss=0.10361]

trial_003 train e002:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:39<00:03,  1.58it/s, avg=0.11330, loss=0.10069]

trial_003 train e002:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:39<00:02,  1.57it/s, avg=0.11330, loss=0.10069]

trial_003 train e002:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:40<00:02,  1.57it/s, avg=0.11339, loss=0.12664]

trial_003 train e002:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:40<00:01,  1.55it/s, avg=0.11339, loss=0.12664]

trial_003 train e002:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:40<00:01,  1.55it/s, avg=0.11335, loss=0.10696]

trial_003 train e002:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:40<00:01,  1.53it/s, avg=0.11335, loss=0.10696]

trial_003 train e002:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:41<00:01,  1.53it/s, avg=0.11340, loss=0.12146]

trial_003 train e002:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:41<00:00,  1.52it/s, avg=0.11340, loss=0.12146]

trial_003 train e002:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:41<00:00,  1.52it/s, avg=0.11338, loss=0.10395]

trial_003 train e002: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:41<00:00,  1.86it/s, avg=0.11338, loss=0.10395]

trial_003 val e002:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e002:   2%|██▌                                                                                                                          | 1/50 [00:00<00:16,  2.91it/s]

trial_003 val e002:   4%|█████                                                                                                                        | 2/50 [00:00<00:16,  2.85it/s]

trial_003 val e002:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:16,  2.88it/s]

trial_003 val e002:   8%|██████████                                                                                                                   | 4/50 [00:01<00:15,  2.91it/s]

trial_003 val e002:  10%|████████████▌                                                                                                                | 5/50 [00:01<00:15,  2.93it/s]

trial_003 val e002:  12%|███████████████                                                                                                              | 6/50 [00:02<00:14,  2.94it/s]

trial_003 val e002:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:14,  2.94it/s]

trial_003 val e002:  16%|████████████████████                                                                                                         | 8/50 [00:02<00:14,  2.95it/s]

trial_003 val e002:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:13,  2.95it/s]

trial_003 val e002:  20%|████████████████████████▊                                                                                                   | 10/50 [00:03<00:13,  2.95it/s]

trial_003 val e002:  22%|███████████████████████████▎                                                                                                | 11/50 [00:03<00:13,  2.95it/s]

trial_003 val e002:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:12,  2.95it/s]

trial_003 val e002:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:04<00:12,  2.96it/s]

trial_003 val e002:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:04<00:12,  2.96it/s]

trial_003 val e002:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:05<00:11,  2.93it/s]

trial_003 val e002:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:05<00:11,  2.94it/s]

trial_003 val e002:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:05<00:11,  2.84it/s]

trial_003 val e002:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:06<00:11,  2.85it/s]

trial_003 val e002:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:06<00:10,  2.88it/s]

trial_003 val e002:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:06<00:10,  2.90it/s]

trial_003 val e002:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:07<00:09,  2.92it/s]

trial_003 val e002:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:07<00:09,  2.94it/s]

trial_003 val e002:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:07<00:09,  2.94it/s]

trial_003 val e002:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:08<00:08,  2.95it/s]

trial_003 val e002:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:08<00:08,  2.96it/s]

trial_003 val e002:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:08<00:08,  2.96it/s]

trial_003 val e002:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:09<00:07,  2.96it/s]

trial_003 val e002:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:09<00:07,  2.96it/s]

trial_003 val e002:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:09<00:07,  2.96it/s]

trial_003 val e002:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:10<00:06,  2.95it/s]

trial_003 val e002:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:10<00:06,  2.95it/s]

trial_003 val e002:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:10<00:06,  2.96it/s]

trial_003 val e002:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:11<00:05,  2.94it/s]

trial_003 val e002:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:11<00:05,  2.94it/s]

trial_003 val e002:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:11<00:05,  2.93it/s]

trial_003 val e002:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:12<00:04,  2.94it/s]

trial_003 val e002:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:12<00:04,  2.94it/s]

trial_003 val e002:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:12<00:04,  2.95it/s]

trial_003 val e002:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:13<00:03,  2.95it/s]

trial_003 val e002:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:13<00:03,  2.96it/s]

trial_003 val e002:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:13<00:03,  2.96it/s]

trial_003 val e002:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:14<00:02,  2.94it/s]

trial_003 val e002:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:14<00:02,  2.95it/s]

trial_003 val e002:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:14<00:02,  2.95it/s]

trial_003 val e002:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:15<00:01,  2.96it/s]

trial_003 val e002:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:15<00:01,  2.96it/s]

trial_003 val e002:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:15<00:01,  2.97it/s]

trial_003 val e002:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:16<00:00,  2.97it/s]

trial_003 val e002:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:16<00:00,  2.95it/s]

trial_003 val e002: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:16<00:00,  2.98it/s]

[2026-05-28 21:09:17] [trial_003] epoch=002 | train_loss=0.113378 | val_MAE=0.106747 | val_S=0.893253 | best_S=0.893253 @epoch=2 | patience=0/5

[trial_003] epochs:   2%|██▍                                                                                                                      | 2/100 [04:07<3:21:04, 123.10s/it]

trial_003 train e003:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e003:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10054, loss=0.10054]

trial_003 train e003:   1%|▋                                                                                              | 1/149 [00:00<01:37,  1.51it/s, avg=0.10054, loss=0.10054]

trial_003 train e003:   1%|▋                                                                                              | 1/149 [00:01<01:37,  1.51it/s, avg=0.10275, loss=0.10496]

trial_003 train e003:   1%|█▎                                                                                             | 2/149 [00:01<01:37,  1.50it/s, avg=0.10275, loss=0.10496]

trial_003 train e003:   1%|█▎                                                                                             | 2/149 [00:01<01:37,  1.50it/s, avg=0.10572, loss=0.11165]

trial_003 train e003:   2%|█▉                                                                                             | 3/149 [00:01<01:35,  1.52it/s, avg=0.10572, loss=0.11165]

trial_003 train e003:   2%|█▉                                                                                             | 3/149 [00:02<01:35,  1.52it/s, avg=0.10890, loss=0.11844]

trial_003 train e003:   3%|██▌                                                                                            | 4/149 [00:02<01:31,  1.59it/s, avg=0.10890, loss=0.11844]

trial_003 train e003:   3%|██▌                                                                                            | 4/149 [00:03<01:31,  1.59it/s, avg=0.10980, loss=0.11339]

trial_003 train e003:   3%|███▏                                                                                           | 5/149 [00:03<01:31,  1.57it/s, avg=0.10980, loss=0.11339]

trial_003 train e003:   3%|███▏                                                                                           | 5/149 [00:03<01:31,  1.57it/s, avg=0.10928, loss=0.10672]

trial_003 train e003:   4%|███▊                                                                                           | 6/149 [00:03<01:33,  1.53it/s, avg=0.10928, loss=0.10672]

trial_003 train e003:   4%|███▊                                                                                           | 6/149 [00:04<01:33,  1.53it/s, avg=0.10926, loss=0.10915]

trial_003 train e003:   5%|████▍                                                                                          | 7/149 [00:04<01:32,  1.54it/s, avg=0.10926, loss=0.10915]

trial_003 train e003:   5%|████▍                                                                                          | 7/149 [00:05<01:32,  1.54it/s, avg=0.10945, loss=0.11077]

trial_003 train e003:   5%|█████                                                                                          | 8/149 [00:05<01:34,  1.49it/s, avg=0.10945, loss=0.11077]

trial_003 train e003:   5%|█████                                                                                          | 8/149 [00:05<01:34,  1.49it/s, avg=0.10902, loss=0.10560]

trial_003 train e003:   6%|█████▋                                                                                         | 9/149 [00:05<01:36,  1.45it/s, avg=0.10902, loss=0.10560]

trial_003 train e003:   6%|█████▋                                                                                         | 9/149 [00:06<01:36,  1.45it/s, avg=0.10900, loss=0.10882]

trial_003 train e003:   7%|██████▎                                                                                       | 10/149 [00:06<01:37,  1.43it/s, avg=0.10900, loss=0.10882]

trial_003 train e003:   7%|██████▎                                                                                       | 10/149 [00:07<01:37,  1.43it/s, avg=0.10958, loss=0.11539]

trial_003 train e003:   7%|██████▉                                                                                       | 11/149 [00:07<01:34,  1.45it/s, avg=0.10958, loss=0.11539]

trial_003 train e003:   7%|██████▉                                                                                       | 11/149 [00:08<01:34,  1.45it/s, avg=0.10885, loss=0.10080]

trial_003 train e003:   8%|███████▌                                                                                      | 12/149 [00:08<01:32,  1.48it/s, avg=0.10885, loss=0.10080]

trial_003 train e003:   8%|███████▌                                                                                      | 12/149 [00:08<01:32,  1.48it/s, avg=0.10795, loss=0.09716]

trial_003 train e003:   9%|████████▏                                                                                     | 13/149 [00:08<01:31,  1.49it/s, avg=0.10795, loss=0.09716]

trial_003 train e003:   9%|████████▏                                                                                     | 13/149 [00:09<01:31,  1.49it/s, avg=0.10792, loss=0.10752]

trial_003 train e003:   9%|████████▊                                                                                     | 14/149 [00:09<01:29,  1.50it/s, avg=0.10792, loss=0.10752]

trial_003 train e003:   9%|████████▊                                                                                     | 14/149 [00:09<01:29,  1.50it/s, avg=0.10781, loss=0.10628]

trial_003 train e003:  10%|█████████▍                                                                                    | 15/149 [00:09<01:29,  1.50it/s, avg=0.10781, loss=0.10628]

trial_003 train e003:  10%|█████████▍                                                                                    | 15/149 [00:10<01:29,  1.50it/s, avg=0.10803, loss=0.11125]

trial_003 train e003:  11%|██████████                                                                                    | 16/149 [00:10<01:28,  1.51it/s, avg=0.10803, loss=0.11125]

trial_003 train e003:  11%|██████████                                                                                    | 16/149 [00:11<01:28,  1.51it/s, avg=0.10769, loss=0.10232]

trial_003 train e003:  11%|██████████▋                                                                                   | 17/149 [00:11<01:23,  1.58it/s, avg=0.10769, loss=0.10232]

trial_003 train e003:  11%|██████████▋                                                                                   | 17/149 [00:11<01:23,  1.58it/s, avg=0.10817, loss=0.11631]

trial_003 train e003:  12%|███████████▎                                                                                  | 18/149 [00:11<01:23,  1.57it/s, avg=0.10817, loss=0.11631]

trial_003 train e003:  12%|███████████▎                                                                                  | 18/149 [00:12<01:23,  1.57it/s, avg=0.10811, loss=0.10709]

trial_003 train e003:  13%|███████████▉                                                                                  | 19/149 [00:12<01:24,  1.53it/s, avg=0.10811, loss=0.10709]

trial_003 train e003:  13%|███████████▉                                                                                  | 19/149 [00:13<01:24,  1.53it/s, avg=0.10818, loss=0.10952]

trial_003 train e003:  13%|████████████▌                                                                                 | 20/149 [00:13<01:27,  1.47it/s, avg=0.10818, loss=0.10952]

trial_003 train e003:  13%|████████████▌                                                                                 | 20/149 [00:14<01:27,  1.47it/s, avg=0.10886, loss=0.12250]

trial_003 train e003:  14%|█████████████▏                                                                                | 21/149 [00:14<01:28,  1.45it/s, avg=0.10886, loss=0.12250]

trial_003 train e003:  14%|█████████████▏                                                                                | 21/149 [00:14<01:28,  1.45it/s, avg=0.10846, loss=0.09998]

trial_003 train e003:  15%|█████████████▉                                                                                | 22/149 [00:14<01:28,  1.44it/s, avg=0.10846, loss=0.09998]

trial_003 train e003:  15%|█████████████▉                                                                                | 22/149 [00:15<01:28,  1.44it/s, avg=0.10861, loss=0.11178]

trial_003 train e003:  15%|██████████████▌                                                                               | 23/149 [00:15<01:29,  1.41it/s, avg=0.10861, loss=0.11178]

trial_003 train e003:  15%|██████████████▌                                                                               | 23/149 [00:16<01:29,  1.41it/s, avg=0.10795, loss=0.09298]

trial_003 train e003:  16%|███████████████▏                                                                              | 24/149 [00:16<01:28,  1.41it/s, avg=0.10795, loss=0.09298]

trial_003 train e003:  16%|███████████████▏                                                                              | 24/149 [00:16<01:28,  1.41it/s, avg=0.10790, loss=0.10673]

trial_003 train e003:  17%|███████████████▊                                                                              | 25/149 [00:16<01:27,  1.42it/s, avg=0.10790, loss=0.10673]

trial_003 train e003:  17%|███████████████▊                                                                              | 25/149 [00:17<01:27,  1.42it/s, avg=0.10766, loss=0.10149]

trial_003 train e003:  17%|████████████████▍                                                                             | 26/149 [00:17<01:26,  1.41it/s, avg=0.10766, loss=0.10149]

trial_003 train e003:  17%|████████████████▍                                                                             | 26/149 [00:18<01:26,  1.41it/s, avg=0.10786, loss=0.11323]

trial_003 train e003:  18%|█████████████████                                                                             | 27/149 [00:18<01:26,  1.41it/s, avg=0.10786, loss=0.11323]

trial_003 train e003:  18%|█████████████████                                                                             | 27/149 [00:19<01:26,  1.41it/s, avg=0.10775, loss=0.10467]

trial_003 train e003:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:26,  1.40it/s, avg=0.10775, loss=0.10467]

trial_003 train e003:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:26,  1.40it/s, avg=0.10717, loss=0.09090]

trial_003 train e003:  19%|██████████████████▎                                                                           | 29/149 [00:19<01:25,  1.40it/s, avg=0.10717, loss=0.09090]

trial_003 train e003:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:25,  1.40it/s, avg=0.10695, loss=0.10065]

trial_003 train e003:  20%|██████████████████▉                                                                           | 30/149 [00:20<01:26,  1.38it/s, avg=0.10695, loss=0.10065]

trial_003 train e003:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:26,  1.38it/s, avg=0.10706, loss=0.11017]

trial_003 train e003:  21%|███████████████████▌                                                                          | 31/149 [00:21<01:24,  1.40it/s, avg=0.10706, loss=0.11017]

trial_003 train e003:  21%|███████████████████▌                                                                          | 31/149 [00:21<01:24,  1.40it/s, avg=0.10687, loss=0.10121]

trial_003 train e003:  21%|████████████████████▏                                                                         | 32/149 [00:21<01:24,  1.39it/s, avg=0.10687, loss=0.10121]

trial_003 train e003:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:24,  1.39it/s, avg=0.10681, loss=0.10484]

trial_003 train e003:  22%|████████████████████▊                                                                         | 33/149 [00:22<01:21,  1.42it/s, avg=0.10681, loss=0.10484]

trial_003 train e003:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:21,  1.42it/s, avg=0.10630, loss=0.08951]

trial_003 train e003:  23%|█████████████████████▍                                                                        | 34/149 [00:23<01:22,  1.40it/s, avg=0.10630, loss=0.08951]

trial_003 train e003:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:22,  1.40it/s, avg=0.10597, loss=0.09456]

trial_003 train e003:  23%|██████████████████████                                                                        | 35/149 [00:24<01:20,  1.41it/s, avg=0.10597, loss=0.09456]

trial_003 train e003:  23%|██████████████████████                                                                        | 35/149 [00:24<01:20,  1.41it/s, avg=0.10568, loss=0.09557]

trial_003 train e003:  24%|██████████████████████▋                                                                       | 36/149 [00:24<01:20,  1.41it/s, avg=0.10568, loss=0.09557]

trial_003 train e003:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:20,  1.41it/s, avg=0.10543, loss=0.09660]

trial_003 train e003:  25%|███████████████████████▎                                                                      | 37/149 [00:25<01:20,  1.39it/s, avg=0.10543, loss=0.09660]

trial_003 train e003:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:20,  1.39it/s, avg=0.10546, loss=0.10653]

trial_003 train e003:  26%|███████████████████████▉                                                                      | 38/149 [00:26<01:18,  1.41it/s, avg=0.10546, loss=0.10653]

trial_003 train e003:  26%|███████████████████████▉                                                                      | 38/149 [00:26<01:18,  1.41it/s, avg=0.10512, loss=0.09195]

trial_003 train e003:  26%|████████████████████████▌                                                                     | 39/149 [00:26<01:17,  1.42it/s, avg=0.10512, loss=0.09195]

trial_003 train e003:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:17,  1.42it/s, avg=0.10505, loss=0.10260]

trial_003 train e003:  27%|█████████████████████████▏                                                                    | 40/149 [00:27<01:19,  1.38it/s, avg=0.10505, loss=0.10260]

trial_003 train e003:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:19,  1.38it/s, avg=0.10552, loss=0.12421]

trial_003 train e003:  28%|█████████████████████████▊                                                                    | 41/149 [00:28<01:15,  1.42it/s, avg=0.10552, loss=0.12421]

trial_003 train e003:  28%|█████████████████████████▊                                                                    | 41/149 [00:28<01:15,  1.42it/s, avg=0.10585, loss=0.11930]

trial_003 train e003:  28%|██████████████████████████▍                                                                   | 42/149 [00:28<01:14,  1.43it/s, avg=0.10585, loss=0.11930]

trial_003 train e003:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:14,  1.43it/s, avg=0.10575, loss=0.10177]

trial_003 train e003:  29%|███████████████████████████▏                                                                  | 43/149 [00:29<01:15,  1.40it/s, avg=0.10575, loss=0.10177]

trial_003 train e003:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:15,  1.40it/s, avg=0.10613, loss=0.12230]

trial_003 train e003:  30%|███████████████████████████▊                                                                  | 44/149 [00:30<01:16,  1.38it/s, avg=0.10613, loss=0.12230]

trial_003 train e003:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:16,  1.38it/s, avg=0.10616, loss=0.10755]

trial_003 train e003:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:15,  1.37it/s, avg=0.10616, loss=0.10755]

trial_003 train e003:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:15,  1.37it/s, avg=0.10625, loss=0.11041]

trial_003 train e003:  31%|█████████████████████████████                                                                 | 46/149 [00:31<01:15,  1.36it/s, avg=0.10625, loss=0.11041]

trial_003 train e003:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:15,  1.36it/s, avg=0.10605, loss=0.09674]

trial_003 train e003:  32%|█████████████████████████████▋                                                                | 47/149 [00:32<01:15,  1.35it/s, avg=0.10605, loss=0.09674]

trial_003 train e003:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:15,  1.35it/s, avg=0.10614, loss=0.11045]

trial_003 train e003:  32%|██████████████████████████████▎                                                               | 48/149 [00:33<01:11,  1.41it/s, avg=0.10614, loss=0.11045]

trial_003 train e003:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.41it/s, avg=0.10638, loss=0.11791]

trial_003 train e003:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:10,  1.41it/s, avg=0.10638, loss=0.11791]

trial_003 train e003:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:10,  1.41it/s, avg=0.10655, loss=0.11478]

trial_003 train e003:  34%|███████████████████████████████▌                                                              | 50/149 [00:34<01:10,  1.41it/s, avg=0.10655, loss=0.11478]

trial_003 train e003:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:10,  1.41it/s, avg=0.10635, loss=0.09649]

trial_003 train e003:  34%|████████████████████████████████▏                                                             | 51/149 [00:35<01:10,  1.39it/s, avg=0.10635, loss=0.09649]

trial_003 train e003:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:10,  1.39it/s, avg=0.10643, loss=0.11007]

trial_003 train e003:  35%|████████████████████████████████▊                                                             | 52/149 [00:36<01:07,  1.44it/s, avg=0.10643, loss=0.11007]

trial_003 train e003:  35%|████████████████████████████████▊                                                             | 52/149 [00:36<01:07,  1.44it/s, avg=0.10648, loss=0.10949]

trial_003 train e003:  36%|█████████████████████████████████▍                                                            | 53/149 [00:36<01:06,  1.45it/s, avg=0.10648, loss=0.10949]

trial_003 train e003:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:06,  1.45it/s, avg=0.10635, loss=0.09937]

trial_003 train e003:  36%|██████████████████████████████████                                                            | 54/149 [00:37<01:05,  1.45it/s, avg=0.10635, loss=0.09937]

trial_003 train e003:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:05,  1.45it/s, avg=0.10624, loss=0.10041]

trial_003 train e003:  37%|██████████████████████████████████▋                                                           | 55/149 [00:38<01:06,  1.41it/s, avg=0.10624, loss=0.10041]

trial_003 train e003:  37%|██████████████████████████████████▋                                                           | 55/149 [00:38<01:06,  1.41it/s, avg=0.10616, loss=0.10150]

trial_003 train e003:  38%|███████████████████████████████████▎                                                          | 56/149 [00:38<01:06,  1.41it/s, avg=0.10616, loss=0.10150]

trial_003 train e003:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:06,  1.41it/s, avg=0.10625, loss=0.11129]

trial_003 train e003:  38%|███████████████████████████████████▉                                                          | 57/149 [00:39<01:05,  1.41it/s, avg=0.10625, loss=0.11129]

trial_003 train e003:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:05,  1.41it/s, avg=0.10598, loss=0.09077]

trial_003 train e003:  39%|████████████████████████████████████▌                                                         | 58/149 [00:40<01:05,  1.40it/s, avg=0.10598, loss=0.09077]

trial_003 train e003:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.40it/s, avg=0.10587, loss=0.09921]

trial_003 train e003:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:41<01:04,  1.39it/s, avg=0.10587, loss=0.09921]

trial_003 train e003:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:41<01:04,  1.39it/s, avg=0.10584, loss=0.10435]

trial_003 train e003:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:41<01:04,  1.39it/s, avg=0.10584, loss=0.10435]

trial_003 train e003:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:04,  1.39it/s, avg=0.10587, loss=0.10748]

trial_003 train e003:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:42<01:04,  1.37it/s, avg=0.10587, loss=0.10748]

trial_003 train e003:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:04,  1.37it/s, avg=0.10601, loss=0.11465]

trial_003 train e003:  42%|███████████████████████████████████████                                                       | 62/149 [00:43<01:03,  1.36it/s, avg=0.10601, loss=0.11465]

trial_003 train e003:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:03,  1.36it/s, avg=0.10587, loss=0.09705]

trial_003 train e003:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<01:01,  1.39it/s, avg=0.10587, loss=0.09705]

trial_003 train e003:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<01:01,  1.39it/s, avg=0.10608, loss=0.11927]

trial_003 train e003:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:44<01:01,  1.39it/s, avg=0.10608, loss=0.11927]

trial_003 train e003:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<01:01,  1.39it/s, avg=0.10608, loss=0.10653]

trial_003 train e003:  44%|█████████████████████████████████████████                                                     | 65/149 [00:45<01:00,  1.38it/s, avg=0.10608, loss=0.10653]

trial_003 train e003:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<01:00,  1.38it/s, avg=0.10603, loss=0.10260]

trial_003 train e003:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<00:59,  1.40it/s, avg=0.10603, loss=0.10260]

trial_003 train e003:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<00:59,  1.40it/s, avg=0.10599, loss=0.10294]

trial_003 train e003:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:46<00:58,  1.41it/s, avg=0.10599, loss=0.10294]

trial_003 train e003:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:58,  1.41it/s, avg=0.10596, loss=0.10458]

trial_003 train e003:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:47<00:57,  1.41it/s, avg=0.10596, loss=0.10458]

trial_003 train e003:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:57,  1.41it/s, avg=0.10608, loss=0.11418]

trial_003 train e003:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:48<00:56,  1.43it/s, avg=0.10608, loss=0.11418]

trial_003 train e003:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:48<00:56,  1.43it/s, avg=0.10631, loss=0.12210]

trial_003 train e003:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:48<00:55,  1.43it/s, avg=0.10631, loss=0.12210]

trial_003 train e003:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:49<00:55,  1.43it/s, avg=0.10631, loss=0.10608]

trial_003 train e003:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:49<00:54,  1.44it/s, avg=0.10631, loss=0.10608]

trial_003 train e003:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:54,  1.44it/s, avg=0.10622, loss=0.09994]

trial_003 train e003:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:50<00:54,  1.42it/s, avg=0.10622, loss=0.09994]

trial_003 train e003:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:54,  1.42it/s, avg=0.10601, loss=0.09080]

trial_003 train e003:  49%|██████████████████████████████████████████████                                                | 73/149 [00:51<00:54,  1.40it/s, avg=0.10601, loss=0.09080]

trial_003 train e003:  49%|██████████████████████████████████████████████                                                | 73/149 [00:51<00:54,  1.40it/s, avg=0.10597, loss=0.10325]

trial_003 train e003:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:51<00:53,  1.40it/s, avg=0.10597, loss=0.10325]

trial_003 train e003:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:53,  1.40it/s, avg=0.10590, loss=0.10053]

trial_003 train e003:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:52<00:52,  1.40it/s, avg=0.10590, loss=0.10053]

trial_003 train e003:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:52,  1.40it/s, avg=0.10594, loss=0.10897]

trial_003 train e003:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:53<00:53,  1.37it/s, avg=0.10594, loss=0.10897]

trial_003 train e003:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:53,  1.37it/s, avg=0.10583, loss=0.09747]

trial_003 train e003:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:51,  1.40it/s, avg=0.10583, loss=0.09747]

trial_003 train e003:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:51,  1.40it/s, avg=0.10585, loss=0.10761]

trial_003 train e003:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:54<00:50,  1.40it/s, avg=0.10585, loss=0.10761]

trial_003 train e003:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:50,  1.40it/s, avg=0.10565, loss=0.08993]

trial_003 train e003:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:55<00:48,  1.43it/s, avg=0.10565, loss=0.08993]

trial_003 train e003:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:48,  1.43it/s, avg=0.10567, loss=0.10741]

trial_003 train e003:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:56<00:48,  1.42it/s, avg=0.10567, loss=0.10741]

trial_003 train e003:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:56<00:48,  1.42it/s, avg=0.10559, loss=0.09928]

trial_003 train e003:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:56<00:47,  1.43it/s, avg=0.10559, loss=0.09928]

trial_003 train e003:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:47,  1.43it/s, avg=0.10549, loss=0.09680]

trial_003 train e003:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:57<00:47,  1.42it/s, avg=0.10549, loss=0.09680]

trial_003 train e003:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:47,  1.42it/s, avg=0.10544, loss=0.10117]

trial_003 train e003:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:58<00:46,  1.42it/s, avg=0.10544, loss=0.10117]

trial_003 train e003:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:58<00:46,  1.42it/s, avg=0.10549, loss=0.10975]

trial_003 train e003:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:58<00:45,  1.41it/s, avg=0.10549, loss=0.10975]

trial_003 train e003:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:59<00:45,  1.41it/s, avg=0.10547, loss=0.10408]

trial_003 train e003:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [00:59<00:45,  1.41it/s, avg=0.10547, loss=0.10408]

trial_003 train e003:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:45,  1.41it/s, avg=0.10540, loss=0.09975]

trial_003 train e003:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:00<00:44,  1.40it/s, avg=0.10540, loss=0.09975]

trial_003 train e003:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:44,  1.40it/s, avg=0.10540, loss=0.10513]

trial_003 train e003:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:01<00:44,  1.39it/s, avg=0.10540, loss=0.10513]

trial_003 train e003:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:01<00:44,  1.39it/s, avg=0.10547, loss=0.11142]

trial_003 train e003:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:01<00:43,  1.40it/s, avg=0.10547, loss=0.11142]

trial_003 train e003:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:43,  1.40it/s, avg=0.10536, loss=0.09621]

trial_003 train e003:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:02<00:42,  1.40it/s, avg=0.10536, loss=0.09621]

trial_003 train e003:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:42,  1.40it/s, avg=0.10563, loss=0.12917]

trial_003 train e003:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:03<00:42,  1.40it/s, avg=0.10563, loss=0.12917]

trial_003 train e003:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:03<00:42,  1.40it/s, avg=0.10559, loss=0.10216]

trial_003 train e003:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:03<00:41,  1.39it/s, avg=0.10559, loss=0.10216]

trial_003 train e003:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:04<00:41,  1.39it/s, avg=0.10566, loss=0.11160]

trial_003 train e003:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:04<00:40,  1.39it/s, avg=0.10566, loss=0.11160]

trial_003 train e003:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:40,  1.39it/s, avg=0.10554, loss=0.09489]

trial_003 train e003:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:05<00:40,  1.37it/s, avg=0.10554, loss=0.09489]

trial_003 train e003:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:40,  1.37it/s, avg=0.10563, loss=0.11352]

trial_003 train e003:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:06<00:39,  1.39it/s, avg=0.10563, loss=0.11352]

trial_003 train e003:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:06<00:39,  1.39it/s, avg=0.10563, loss=0.10620]

trial_003 train e003:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:06<00:39,  1.38it/s, avg=0.10563, loss=0.10620]

trial_003 train e003:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:39,  1.38it/s, avg=0.10573, loss=0.11479]

trial_003 train e003:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:07<00:38,  1.38it/s, avg=0.10573, loss=0.11479]

trial_003 train e003:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:38,  1.38it/s, avg=0.10576, loss=0.10892]

trial_003 train e003:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:08<00:36,  1.41it/s, avg=0.10576, loss=0.10892]

trial_003 train e003:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:08<00:36,  1.41it/s, avg=0.10554, loss=0.08436]

trial_003 train e003:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:08<00:36,  1.39it/s, avg=0.10554, loss=0.08436]

trial_003 train e003:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:09<00:36,  1.39it/s, avg=0.10569, loss=0.11993]

trial_003 train e003:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:09<00:36,  1.38it/s, avg=0.10569, loss=0.11993]

trial_003 train e003:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:36,  1.38it/s, avg=0.10559, loss=0.09646]

trial_003 train e003:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:10<00:35,  1.38it/s, avg=0.10559, loss=0.09646]

trial_003 train e003:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:35,  1.38it/s, avg=0.10570, loss=0.11602]

trial_003 train e003:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:11<00:35,  1.35it/s, avg=0.10570, loss=0.11602]

trial_003 train e003:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:11<00:35,  1.35it/s, avg=0.10548, loss=0.08388]

trial_003 train e003:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:11<00:34,  1.35it/s, avg=0.10548, loss=0.08388]

trial_003 train e003:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:34,  1.35it/s, avg=0.10538, loss=0.09447]

trial_003 train e003:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:12<00:34,  1.34it/s, avg=0.10538, loss=0.09447]

trial_003 train e003:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:34,  1.34it/s, avg=0.10537, loss=0.10416]

trial_003 train e003:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:13<00:32,  1.38it/s, avg=0.10537, loss=0.10416]

trial_003 train e003:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.38it/s, avg=0.10541, loss=0.10988]

trial_003 train e003:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:14<00:31,  1.40it/s, avg=0.10541, loss=0.10988]

trial_003 train e003:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:14<00:31,  1.40it/s, avg=0.10550, loss=0.11488]

trial_003 train e003:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:14<00:30,  1.41it/s, avg=0.10550, loss=0.11488]

trial_003 train e003:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:30,  1.41it/s, avg=0.10553, loss=0.10947]

trial_003 train e003:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:15<00:29,  1.42it/s, avg=0.10553, loss=0.10947]

trial_003 train e003:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:29,  1.42it/s, avg=0.10539, loss=0.08960]

trial_003 train e003:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:16<00:29,  1.41it/s, avg=0.10539, loss=0.08960]

trial_003 train e003:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:16<00:29,  1.41it/s, avg=0.10529, loss=0.09513]

trial_003 train e003:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:16<00:28,  1.40it/s, avg=0.10529, loss=0.09513]

trial_003 train e003:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:17<00:28,  1.40it/s, avg=0.10532, loss=0.10774]

trial_003 train e003:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:17<00:27,  1.40it/s, avg=0.10532, loss=0.10774]

trial_003 train e003:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:27,  1.40it/s, avg=0.10537, loss=0.11157]

trial_003 train e003:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:18<00:27,  1.40it/s, avg=0.10537, loss=0.11157]

trial_003 train e003:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.40it/s, avg=0.10540, loss=0.10859]

trial_003 train e003:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:19<00:25,  1.43it/s, avg=0.10540, loss=0.10859]

trial_003 train e003:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:19<00:25,  1.43it/s, avg=0.10530, loss=0.09419]

trial_003 train e003:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:19<00:25,  1.42it/s, avg=0.10530, loss=0.09419]

trial_003 train e003:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:20<00:25,  1.42it/s, avg=0.10533, loss=0.10901]

trial_003 train e003:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:20<00:24,  1.42it/s, avg=0.10533, loss=0.10901]

trial_003 train e003:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.42it/s, avg=0.10538, loss=0.11093]

trial_003 train e003:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:21<00:24,  1.41it/s, avg=0.10538, loss=0.11093]

trial_003 train e003:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:21<00:24,  1.41it/s, avg=0.10534, loss=0.10102]

trial_003 train e003:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:21<00:23,  1.40it/s, avg=0.10534, loss=0.10102]

trial_003 train e003:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:22<00:23,  1.40it/s, avg=0.10532, loss=0.10200]

trial_003 train e003:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:22<00:23,  1.34it/s, avg=0.10532, loss=0.10200]

trial_003 train e003:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:23,  1.34it/s, avg=0.10523, loss=0.09536]

trial_003 train e003:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:23<00:23,  1.34it/s, avg=0.10523, loss=0.09536]

trial_003 train e003:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:23,  1.34it/s, avg=0.10524, loss=0.10616]

trial_003 train e003:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:24<00:22,  1.33it/s, avg=0.10524, loss=0.10616]

trial_003 train e003:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:24<00:22,  1.33it/s, avg=0.10525, loss=0.10632]

trial_003 train e003:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:24<00:21,  1.35it/s, avg=0.10525, loss=0.10632]

trial_003 train e003:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:21,  1.35it/s, avg=0.10510, loss=0.08767]

trial_003 train e003:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:25<00:20,  1.36it/s, avg=0.10510, loss=0.08767]

trial_003 train e003:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:20,  1.36it/s, avg=0.10498, loss=0.08945]

trial_003 train e003:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:26<00:19,  1.35it/s, avg=0.10498, loss=0.08945]

trial_003 train e003:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.35it/s, avg=0.10497, loss=0.10422]

trial_003 train e003:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:27<00:19,  1.36it/s, avg=0.10497, loss=0.10422]

trial_003 train e003:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:27<00:19,  1.36it/s, avg=0.10488, loss=0.09378]

trial_003 train e003:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:27<00:18,  1.36it/s, avg=0.10488, loss=0.09378]

trial_003 train e003:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:18,  1.36it/s, avg=0.10497, loss=0.11588]

trial_003 train e003:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:28<00:17,  1.40it/s, avg=0.10497, loss=0.11588]

trial_003 train e003:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:17,  1.40it/s, avg=0.10496, loss=0.10384]

trial_003 train e003:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:29<00:16,  1.40it/s, avg=0.10496, loss=0.10384]

trial_003 train e003:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:29<00:16,  1.40it/s, avg=0.10485, loss=0.09089]

trial_003 train e003:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:29<00:15,  1.40it/s, avg=0.10485, loss=0.09089]

trial_003 train e003:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.40it/s, avg=0.10485, loss=0.10477]

trial_003 train e003:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:30<00:14,  1.41it/s, avg=0.10485, loss=0.10477]

trial_003 train e003:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:14,  1.41it/s, avg=0.10485, loss=0.10489]

trial_003 train e003:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:31<00:14,  1.40it/s, avg=0.10485, loss=0.10489]

trial_003 train e003:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.40it/s, avg=0.10492, loss=0.11499]

trial_003 train e003:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:32<00:13,  1.44it/s, avg=0.10492, loss=0.11499]

trial_003 train e003:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:32<00:13,  1.44it/s, avg=0.10500, loss=0.11439]

trial_003 train e003:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:32<00:12,  1.42it/s, avg=0.10500, loss=0.11439]

trial_003 train e003:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:12,  1.42it/s, avg=0.10492, loss=0.09539]

trial_003 train e003:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:33<00:11,  1.45it/s, avg=0.10492, loss=0.09539]

trial_003 train e003:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:11,  1.45it/s, avg=0.10479, loss=0.08752]

trial_003 train e003:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:34<00:11,  1.41it/s, avg=0.10479, loss=0.08752]

trial_003 train e003:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:34<00:11,  1.41it/s, avg=0.10477, loss=0.10100]

trial_003 train e003:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:34<00:10,  1.38it/s, avg=0.10477, loss=0.10100]

trial_003 train e003:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.38it/s, avg=0.10474, loss=0.10151]

trial_003 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:35<00:09,  1.40it/s, avg=0.10474, loss=0.10151]

trial_003 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:09,  1.40it/s, avg=0.10473, loss=0.10359]

trial_003 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:36<00:09,  1.41it/s, avg=0.10473, loss=0.10359]

trial_003 train e003:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.41it/s, avg=0.10468, loss=0.09698]

trial_003 train e003:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:37<00:08,  1.39it/s, avg=0.10468, loss=0.09698]

trial_003 train e003:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:37<00:08,  1.39it/s, avg=0.10461, loss=0.09588]

trial_003 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:37<00:08,  1.37it/s, avg=0.10461, loss=0.09588]

trial_003 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:08,  1.37it/s, avg=0.10449, loss=0.08765]

trial_003 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:38<00:07,  1.39it/s, avg=0.10449, loss=0.08765]

trial_003 train e003:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.39it/s, avg=0.10451, loss=0.10788]

trial_003 train e003:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:39<00:06,  1.39it/s, avg=0.10451, loss=0.10788]

trial_003 train e003:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:39<00:06,  1.39it/s, avg=0.10446, loss=0.09737]

trial_003 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:39<00:05,  1.39it/s, avg=0.10446, loss=0.09737]

trial_003 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:40<00:05,  1.39it/s, avg=0.10442, loss=0.09894]

trial_003 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:40<00:04,  1.43it/s, avg=0.10442, loss=0.09894]

trial_003 train e003:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:04,  1.43it/s, avg=0.10441, loss=0.10250]

trial_003 train e003:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:41<00:04,  1.39it/s, avg=0.10441, loss=0.10250]

trial_003 train e003:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.39it/s, avg=0.10441, loss=0.10376]

trial_003 train e003:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:42<00:03,  1.40it/s, avg=0.10441, loss=0.10376]

trial_003 train e003:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:42<00:03,  1.40it/s, avg=0.10438, loss=0.10073]

trial_003 train e003:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:42<00:02,  1.38it/s, avg=0.10438, loss=0.10073]

trial_003 train e003:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.38it/s, avg=0.10434, loss=0.09779]

trial_003 train e003:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:43<00:02,  1.39it/s, avg=0.10434, loss=0.09779]

trial_003 train e003:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.39it/s, avg=0.10428, loss=0.09581]

trial_003 train e003:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:44<00:01,  1.40it/s, avg=0.10428, loss=0.09581]

trial_003 train e003:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:44<00:01,  1.40it/s, avg=0.10441, loss=0.12351]

trial_003 train e003:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:44<00:00,  1.42it/s, avg=0.10441, loss=0.12351]

trial_003 train e003:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.42it/s, avg=0.10439, loss=0.09820]

trial_003 train e003: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:45<00:00,  1.70it/s, avg=0.10439, loss=0.09820]

trial_003 val e003:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e003:   2%|██▌                                                                                                                          | 1/50 [00:00<00:18,  2.67it/s]

trial_003 val e003:   4%|█████                                                                                                                        | 2/50 [00:00<00:16,  2.84it/s]

trial_003 val e003:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:16,  2.87it/s]

trial_003 val e003:   8%|██████████                                                                                                                   | 4/50 [00:01<00:15,  2.90it/s]

trial_003 val e003:  10%|████████████▌                                                                                                                | 5/50 [00:01<00:15,  2.92it/s]

trial_003 val e003:  12%|███████████████                                                                                                              | 6/50 [00:02<00:14,  2.94it/s]

trial_003 val e003:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:14,  2.95it/s]

trial_003 val e003:  16%|████████████████████                                                                                                         | 8/50 [00:02<00:14,  2.96it/s]

trial_003 val e003:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:13,  2.97it/s]

trial_003 val e003:  20%|████████████████████████▊                                                                                                   | 10/50 [00:03<00:13,  2.96it/s]

trial_003 val e003:  22%|███████████████████████████▎                                                                                                | 11/50 [00:03<00:13,  2.95it/s]

trial_003 val e003:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:12,  2.95it/s]

trial_003 val e003:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:04<00:12,  2.90it/s]

trial_003 val e003:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:04<00:12,  2.91it/s]

trial_003 val e003:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:05<00:11,  2.92it/s]

trial_003 val e003:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:05<00:11,  2.92it/s]

trial_003 val e003:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:05<00:11,  2.93it/s]

trial_003 val e003:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:06<00:10,  2.91it/s]

trial_003 val e003:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:06<00:10,  2.92it/s]

trial_003 val e003:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:06<00:10,  2.90it/s]

trial_003 val e003:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:07<00:09,  2.91it/s]

trial_003 val e003:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:07<00:09,  2.93it/s]

trial_003 val e003:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:07<00:09,  2.92it/s]

trial_003 val e003:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:08<00:08,  2.93it/s]

trial_003 val e003:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:08<00:08,  2.90it/s]

trial_003 val e003:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:08<00:08,  2.90it/s]

trial_003 val e003:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:09<00:07,  2.88it/s]

trial_003 val e003:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:09<00:07,  2.90it/s]

trial_003 val e003:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:09<00:07,  2.89it/s]

trial_003 val e003:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:10<00:06,  2.92it/s]

trial_003 val e003:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:10<00:06,  2.94it/s]

trial_003 val e003:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:10<00:06,  2.93it/s]

trial_003 val e003:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:11<00:05,  2.94it/s]

trial_003 val e003:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:11<00:05,  2.94it/s]

trial_003 val e003:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:11<00:05,  2.95it/s]

trial_003 val e003:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:12<00:04,  2.95it/s]

trial_003 val e003:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:12<00:04,  2.95it/s]

trial_003 val e003:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:12<00:04,  2.96it/s]

trial_003 val e003:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:13<00:03,  2.96it/s]

trial_003 val e003:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:13<00:03,  2.96it/s]

trial_003 val e003:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:14<00:03,  2.96it/s]

trial_003 val e003:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:14<00:02,  2.96it/s]

trial_003 val e003:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:14<00:02,  2.97it/s]

trial_003 val e003:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:15<00:02,  2.95it/s]

trial_003 val e003:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:15<00:01,  2.89it/s]

trial_003 val e003:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:15<00:01,  2.92it/s]

trial_003 val e003:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:16<00:01,  2.92it/s]

trial_003 val e003:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:16<00:00,  2.93it/s]

trial_003 val e003:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:16<00:00,  2.95it/s]

trial_003 val e003: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:17<00:00,  2.98it/s]

[2026-05-28 21:11:20] [trial_003] epoch=003 | train_loss=0.104391 | val_MAE=0.104084 | val_S=0.895916 | best_S=0.895916 @epoch=3 | patience=0/5

[trial_003] epochs:   3%|███▋                                                                                                                     | 3/100 [06:10<3:18:57, 123.06s/it]

trial_003 train e004:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e004:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.10683, loss=0.10683]

trial_003 train e004:   1%|▋                                                                                              | 1/149 [00:00<01:30,  1.63it/s, avg=0.10683, loss=0.10683]

trial_003 train e004:   1%|▋                                                                                              | 1/149 [00:01<01:30,  1.63it/s, avg=0.10782, loss=0.10881]

trial_003 train e004:   1%|█▎                                                                                             | 2/149 [00:01<01:33,  1.57it/s, avg=0.10782, loss=0.10881]

trial_003 train e004:   1%|█▎                                                                                             | 2/149 [00:01<01:33,  1.57it/s, avg=0.11441, loss=0.12760]

trial_003 train e004:   2%|█▉                                                                                             | 3/149 [00:01<01:31,  1.59it/s, avg=0.11441, loss=0.12760]

trial_003 train e004:   2%|█▉                                                                                             | 3/149 [00:02<01:31,  1.59it/s, avg=0.11033, loss=0.09807]

trial_003 train e004:   3%|██▌                                                                                            | 4/149 [00:02<01:33,  1.55it/s, avg=0.11033, loss=0.09807]

trial_003 train e004:   3%|██▌                                                                                            | 4/149 [00:03<01:33,  1.55it/s, avg=0.10840, loss=0.10069]

trial_003 train e004:   3%|███▏                                                                                           | 5/149 [00:03<01:35,  1.50it/s, avg=0.10840, loss=0.10069]

trial_003 train e004:   3%|███▏                                                                                           | 5/149 [00:03<01:35,  1.50it/s, avg=0.10879, loss=0.11076]

trial_003 train e004:   4%|███▊                                                                                           | 6/149 [00:03<01:33,  1.52it/s, avg=0.10879, loss=0.11076]

trial_003 train e004:   4%|███▊                                                                                           | 6/149 [00:04<01:33,  1.52it/s, avg=0.10698, loss=0.09611]

trial_003 train e004:   5%|████▍                                                                                          | 7/149 [00:04<01:33,  1.52it/s, avg=0.10698, loss=0.09611]

trial_003 train e004:   5%|████▍                                                                                          | 7/149 [00:05<01:33,  1.52it/s, avg=0.10502, loss=0.09128]

trial_003 train e004:   5%|█████                                                                                          | 8/149 [00:05<01:32,  1.53it/s, avg=0.10502, loss=0.09128]

trial_003 train e004:   5%|█████                                                                                          | 8/149 [00:05<01:32,  1.53it/s, avg=0.10409, loss=0.09663]

trial_003 train e004:   6%|█████▋                                                                                         | 9/149 [00:05<01:30,  1.54it/s, avg=0.10409, loss=0.09663]

trial_003 train e004:   6%|█████▋                                                                                         | 9/149 [00:06<01:30,  1.54it/s, avg=0.10496, loss=0.11279]

trial_003 train e004:   7%|██████▎                                                                                       | 10/149 [00:06<01:26,  1.61it/s, avg=0.10496, loss=0.11279]

trial_003 train e004:   7%|██████▎                                                                                       | 10/149 [00:07<01:26,  1.61it/s, avg=0.10543, loss=0.11014]

trial_003 train e004:   7%|██████▉                                                                                       | 11/149 [00:07<01:26,  1.59it/s, avg=0.10543, loss=0.11014]

trial_003 train e004:   7%|██████▉                                                                                       | 11/149 [00:07<01:26,  1.59it/s, avg=0.10474, loss=0.09719]

trial_003 train e004:   8%|███████▌                                                                                      | 12/149 [00:07<01:27,  1.57it/s, avg=0.10474, loss=0.09719]

trial_003 train e004:   8%|███████▌                                                                                      | 12/149 [00:08<01:27,  1.57it/s, avg=0.10345, loss=0.08792]

trial_003 train e004:   9%|████████▏                                                                                     | 13/149 [00:08<01:27,  1.55it/s, avg=0.10345, loss=0.08792]

trial_003 train e004:   9%|████████▏                                                                                     | 13/149 [00:09<01:27,  1.55it/s, avg=0.10333, loss=0.10189]

trial_003 train e004:   9%|████████▊                                                                                     | 14/149 [00:09<01:26,  1.56it/s, avg=0.10333, loss=0.10189]

trial_003 train e004:   9%|████████▊                                                                                     | 14/149 [00:09<01:26,  1.56it/s, avg=0.10372, loss=0.10909]

trial_003 train e004:  10%|█████████▍                                                                                    | 15/149 [00:09<01:26,  1.55it/s, avg=0.10372, loss=0.10909]

trial_003 train e004:  10%|█████████▍                                                                                    | 15/149 [00:10<01:26,  1.55it/s, avg=0.10456, loss=0.11725]

trial_003 train e004:  11%|██████████                                                                                    | 16/149 [00:10<01:25,  1.56it/s, avg=0.10456, loss=0.11725]

trial_003 train e004:  11%|██████████                                                                                    | 16/149 [00:10<01:25,  1.56it/s, avg=0.10499, loss=0.11187]

trial_003 train e004:  11%|██████████▋                                                                                   | 17/149 [00:10<01:25,  1.54it/s, avg=0.10499, loss=0.11187]

trial_003 train e004:  11%|██████████▋                                                                                   | 17/149 [00:11<01:25,  1.54it/s, avg=0.10416, loss=0.08989]

trial_003 train e004:  12%|███████████▎                                                                                  | 18/149 [00:11<01:25,  1.53it/s, avg=0.10416, loss=0.08989]

trial_003 train e004:  12%|███████████▎                                                                                  | 18/149 [00:12<01:25,  1.53it/s, avg=0.10375, loss=0.09638]

trial_003 train e004:  13%|███████████▉                                                                                  | 19/149 [00:12<01:24,  1.54it/s, avg=0.10375, loss=0.09638]

trial_003 train e004:  13%|███████████▉                                                                                  | 19/149 [00:12<01:24,  1.54it/s, avg=0.10367, loss=0.10218]

trial_003 train e004:  13%|████████████▌                                                                                 | 20/149 [00:12<01:24,  1.53it/s, avg=0.10367, loss=0.10218]

trial_003 train e004:  13%|████████████▌                                                                                 | 20/149 [00:13<01:24,  1.53it/s, avg=0.10340, loss=0.09800]

trial_003 train e004:  14%|█████████████▏                                                                                | 21/149 [00:13<01:23,  1.53it/s, avg=0.10340, loss=0.09800]

trial_003 train e004:  14%|█████████████▏                                                                                | 21/149 [00:14<01:23,  1.53it/s, avg=0.10342, loss=0.10391]

trial_003 train e004:  15%|█████████████▉                                                                                | 22/149 [00:14<01:23,  1.53it/s, avg=0.10342, loss=0.10391]

trial_003 train e004:  15%|█████████████▉                                                                                | 22/149 [00:14<01:23,  1.53it/s, avg=0.10410, loss=0.11911]

trial_003 train e004:  15%|██████████████▌                                                                               | 23/149 [00:14<01:22,  1.53it/s, avg=0.10410, loss=0.11911]

trial_003 train e004:  15%|██████████████▌                                                                               | 23/149 [00:15<01:22,  1.53it/s, avg=0.10415, loss=0.10533]

trial_003 train e004:  16%|███████████████▏                                                                              | 24/149 [00:15<01:20,  1.55it/s, avg=0.10415, loss=0.10533]

trial_003 train e004:  16%|███████████████▏                                                                              | 24/149 [00:16<01:20,  1.55it/s, avg=0.10417, loss=0.10449]

trial_003 train e004:  17%|███████████████▊                                                                              | 25/149 [00:16<01:20,  1.55it/s, avg=0.10417, loss=0.10449]

trial_003 train e004:  17%|███████████████▊                                                                              | 25/149 [00:16<01:20,  1.55it/s, avg=0.10398, loss=0.09930]

trial_003 train e004:  17%|████████████████▍                                                                             | 26/149 [00:16<01:19,  1.55it/s, avg=0.10398, loss=0.09930]

trial_003 train e004:  17%|████████████████▍                                                                             | 26/149 [00:17<01:19,  1.55it/s, avg=0.10322, loss=0.08337]

trial_003 train e004:  18%|█████████████████                                                                             | 27/149 [00:17<01:19,  1.54it/s, avg=0.10322, loss=0.08337]

trial_003 train e004:  18%|█████████████████                                                                             | 27/149 [00:18<01:19,  1.54it/s, avg=0.10365, loss=0.11529]

trial_003 train e004:  19%|█████████████████▋                                                                            | 28/149 [00:18<01:17,  1.56it/s, avg=0.10365, loss=0.11529]

trial_003 train e004:  19%|█████████████████▋                                                                            | 28/149 [00:18<01:17,  1.56it/s, avg=0.10392, loss=0.11156]

trial_003 train e004:  19%|██████████████████▎                                                                           | 29/149 [00:18<01:19,  1.50it/s, avg=0.10392, loss=0.11156]

trial_003 train e004:  19%|██████████████████▎                                                                           | 29/149 [00:19<01:19,  1.50it/s, avg=0.10439, loss=0.11811]

trial_003 train e004:  20%|██████████████████▉                                                                           | 30/149 [00:19<01:21,  1.46it/s, avg=0.10439, loss=0.11811]

trial_003 train e004:  20%|██████████████████▉                                                                           | 30/149 [00:20<01:21,  1.46it/s, avg=0.10431, loss=0.10164]

trial_003 train e004:  21%|███████████████████▌                                                                          | 31/149 [00:20<01:17,  1.52it/s, avg=0.10431, loss=0.10164]

trial_003 train e004:  21%|███████████████████▌                                                                          | 31/149 [00:20<01:17,  1.52it/s, avg=0.10419, loss=0.10053]

trial_003 train e004:  21%|████████████████████▏                                                                         | 32/149 [00:20<01:17,  1.51it/s, avg=0.10419, loss=0.10053]

trial_003 train e004:  21%|████████████████████▏                                                                         | 32/149 [00:21<01:17,  1.51it/s, avg=0.10426, loss=0.10659]

trial_003 train e004:  22%|████████████████████▊                                                                         | 33/149 [00:21<01:17,  1.50it/s, avg=0.10426, loss=0.10659]

trial_003 train e004:  22%|████████████████████▊                                                                         | 33/149 [00:22<01:17,  1.50it/s, avg=0.10374, loss=0.08647]

trial_003 train e004:  23%|█████████████████████▍                                                                        | 34/149 [00:22<01:15,  1.53it/s, avg=0.10374, loss=0.08647]

trial_003 train e004:  23%|█████████████████████▍                                                                        | 34/149 [00:22<01:15,  1.53it/s, avg=0.10401, loss=0.11321]

trial_003 train e004:  23%|██████████████████████                                                                        | 35/149 [00:22<01:16,  1.49it/s, avg=0.10401, loss=0.11321]

trial_003 train e004:  23%|██████████████████████                                                                        | 35/149 [00:23<01:16,  1.49it/s, avg=0.10388, loss=0.09946]

trial_003 train e004:  24%|██████████████████████▋                                                                       | 36/149 [00:23<01:17,  1.46it/s, avg=0.10388, loss=0.09946]

trial_003 train e004:  24%|██████████████████████▋                                                                       | 36/149 [00:24<01:17,  1.46it/s, avg=0.10372, loss=0.09797]

trial_003 train e004:  25%|███████████████████████▎                                                                      | 37/149 [00:24<01:18,  1.43it/s, avg=0.10372, loss=0.09797]

trial_003 train e004:  25%|███████████████████████▎                                                                      | 37/149 [00:24<01:18,  1.43it/s, avg=0.10356, loss=0.09746]

trial_003 train e004:  26%|███████████████████████▉                                                                      | 38/149 [00:24<01:18,  1.41it/s, avg=0.10356, loss=0.09746]

trial_003 train e004:  26%|███████████████████████▉                                                                      | 38/149 [00:25<01:18,  1.41it/s, avg=0.10346, loss=0.09962]

trial_003 train e004:  26%|████████████████████████▌                                                                     | 39/149 [00:25<01:16,  1.43it/s, avg=0.10346, loss=0.09962]

trial_003 train e004:  26%|████████████████████████▌                                                                     | 39/149 [00:26<01:16,  1.43it/s, avg=0.10365, loss=0.11103]

trial_003 train e004:  27%|█████████████████████████▏                                                                    | 40/149 [00:26<01:16,  1.42it/s, avg=0.10365, loss=0.11103]

trial_003 train e004:  27%|█████████████████████████▏                                                                    | 40/149 [00:27<01:16,  1.42it/s, avg=0.10364, loss=0.10342]

trial_003 train e004:  28%|█████████████████████████▊                                                                    | 41/149 [00:27<01:16,  1.42it/s, avg=0.10364, loss=0.10342]

trial_003 train e004:  28%|█████████████████████████▊                                                                    | 41/149 [00:27<01:16,  1.42it/s, avg=0.10398, loss=0.11794]

trial_003 train e004:  28%|██████████████████████████▍                                                                   | 42/149 [00:27<01:15,  1.41it/s, avg=0.10398, loss=0.11794]

trial_003 train e004:  28%|██████████████████████████▍                                                                   | 42/149 [00:28<01:15,  1.41it/s, avg=0.10399, loss=0.10446]

trial_003 train e004:  29%|███████████████████████████▏                                                                  | 43/149 [00:28<01:13,  1.44it/s, avg=0.10399, loss=0.10446]

trial_003 train e004:  29%|███████████████████████████▏                                                                  | 43/149 [00:29<01:13,  1.44it/s, avg=0.10376, loss=0.09366]

trial_003 train e004:  30%|███████████████████████████▊                                                                  | 44/149 [00:29<01:13,  1.42it/s, avg=0.10376, loss=0.09366]

trial_003 train e004:  30%|███████████████████████████▊                                                                  | 44/149 [00:29<01:13,  1.42it/s, avg=0.10397, loss=0.11353]

trial_003 train e004:  30%|████████████████████████████▍                                                                 | 45/149 [00:29<01:12,  1.44it/s, avg=0.10397, loss=0.11353]

trial_003 train e004:  30%|████████████████████████████▍                                                                 | 45/149 [00:30<01:12,  1.44it/s, avg=0.10398, loss=0.10434]

trial_003 train e004:  31%|█████████████████████████████                                                                 | 46/149 [00:30<01:10,  1.46it/s, avg=0.10398, loss=0.10434]

trial_003 train e004:  31%|█████████████████████████████                                                                 | 46/149 [00:31<01:10,  1.46it/s, avg=0.10402, loss=0.10590]

trial_003 train e004:  32%|█████████████████████████████▋                                                                | 47/149 [00:31<01:11,  1.43it/s, avg=0.10402, loss=0.10590]

trial_003 train e004:  32%|█████████████████████████████▋                                                                | 47/149 [00:31<01:11,  1.43it/s, avg=0.10413, loss=0.10909]

trial_003 train e004:  32%|██████████████████████████████▎                                                               | 48/149 [00:31<01:11,  1.42it/s, avg=0.10413, loss=0.10909]

trial_003 train e004:  32%|██████████████████████████████▎                                                               | 48/149 [00:32<01:11,  1.42it/s, avg=0.10419, loss=0.10736]

trial_003 train e004:  33%|██████████████████████████████▉                                                               | 49/149 [00:32<01:10,  1.42it/s, avg=0.10419, loss=0.10736]

trial_003 train e004:  33%|██████████████████████████████▉                                                               | 49/149 [00:33<01:10,  1.42it/s, avg=0.10409, loss=0.09877]

trial_003 train e004:  34%|███████████████████████████████▌                                                              | 50/149 [00:33<01:10,  1.41it/s, avg=0.10409, loss=0.09877]

trial_003 train e004:  34%|███████████████████████████████▌                                                              | 50/149 [00:34<01:10,  1.41it/s, avg=0.10395, loss=0.09697]

trial_003 train e004:  34%|████████████████████████████████▏                                                             | 51/149 [00:34<01:09,  1.40it/s, avg=0.10395, loss=0.09697]

trial_003 train e004:  34%|████████████████████████████████▏                                                             | 51/149 [00:34<01:09,  1.40it/s, avg=0.10389, loss=0.10102]

trial_003 train e004:  35%|████████████████████████████████▊                                                             | 52/149 [00:34<01:07,  1.44it/s, avg=0.10389, loss=0.10102]

trial_003 train e004:  35%|████████████████████████████████▊                                                             | 52/149 [00:35<01:07,  1.44it/s, avg=0.10374, loss=0.09609]

trial_003 train e004:  36%|█████████████████████████████████▍                                                            | 53/149 [00:35<01:06,  1.45it/s, avg=0.10374, loss=0.09609]

trial_003 train e004:  36%|█████████████████████████████████▍                                                            | 53/149 [00:36<01:06,  1.45it/s, avg=0.10345, loss=0.08789]

trial_003 train e004:  36%|██████████████████████████████████                                                            | 54/149 [00:36<01:07,  1.40it/s, avg=0.10345, loss=0.08789]

trial_003 train e004:  36%|██████████████████████████████████                                                            | 54/149 [00:36<01:07,  1.40it/s, avg=0.10354, loss=0.10818]

trial_003 train e004:  37%|██████████████████████████████████▋                                                           | 55/149 [00:36<01:06,  1.41it/s, avg=0.10354, loss=0.10818]

trial_003 train e004:  37%|██████████████████████████████████▋                                                           | 55/149 [00:37<01:06,  1.41it/s, avg=0.10348, loss=0.10019]

trial_003 train e004:  38%|███████████████████████████████████▎                                                          | 56/149 [00:37<01:05,  1.43it/s, avg=0.10348, loss=0.10019]

trial_003 train e004:  38%|███████████████████████████████████▎                                                          | 56/149 [00:38<01:05,  1.43it/s, avg=0.10320, loss=0.08779]

trial_003 train e004:  38%|███████████████████████████████████▉                                                          | 57/149 [00:38<01:04,  1.42it/s, avg=0.10320, loss=0.08779]

trial_003 train e004:  38%|███████████████████████████████████▉                                                          | 57/149 [00:38<01:04,  1.42it/s, avg=0.10332, loss=0.11006]

trial_003 train e004:  39%|████████████████████████████████████▌                                                         | 58/149 [00:38<01:03,  1.44it/s, avg=0.10332, loss=0.11006]

trial_003 train e004:  39%|████████████████████████████████████▌                                                         | 58/149 [00:39<01:03,  1.44it/s, avg=0.10324, loss=0.09881]

trial_003 train e004:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:39<01:02,  1.45it/s, avg=0.10324, loss=0.09881]

trial_003 train e004:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:40<01:02,  1.45it/s, avg=0.10315, loss=0.09761]

trial_003 train e004:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:40<01:02,  1.42it/s, avg=0.10315, loss=0.09761]

trial_003 train e004:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:41<01:02,  1.42it/s, avg=0.10324, loss=0.10859]

trial_003 train e004:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:41<01:02,  1.41it/s, avg=0.10324, loss=0.10859]

trial_003 train e004:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:41<01:02,  1.41it/s, avg=0.10322, loss=0.10207]

trial_003 train e004:  42%|███████████████████████████████████████                                                       | 62/149 [00:41<01:03,  1.38it/s, avg=0.10322, loss=0.10207]

trial_003 train e004:  42%|███████████████████████████████████████                                                       | 62/149 [00:42<01:03,  1.38it/s, avg=0.10314, loss=0.09842]

trial_003 train e004:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:42<01:02,  1.39it/s, avg=0.10314, loss=0.09842]

trial_003 train e004:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:43<01:02,  1.39it/s, avg=0.10300, loss=0.09425]

trial_003 train e004:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:43<01:00,  1.39it/s, avg=0.10300, loss=0.09425]

trial_003 train e004:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:44<01:00,  1.39it/s, avg=0.10290, loss=0.09658]

trial_003 train e004:  44%|█████████████████████████████████████████                                                     | 65/149 [00:44<01:00,  1.38it/s, avg=0.10290, loss=0.09658]

trial_003 train e004:  44%|█████████████████████████████████████████                                                     | 65/149 [00:44<01:00,  1.38it/s, avg=0.10295, loss=0.10578]

trial_003 train e004:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:44<01:00,  1.37it/s, avg=0.10295, loss=0.10578]

trial_003 train e004:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:45<01:00,  1.37it/s, avg=0.10287, loss=0.09792]

trial_003 train e004:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:45<00:59,  1.38it/s, avg=0.10287, loss=0.09792]

trial_003 train e004:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:46<00:59,  1.38it/s, avg=0.10270, loss=0.09078]

trial_003 train e004:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:46<00:58,  1.39it/s, avg=0.10270, loss=0.09078]

trial_003 train e004:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:46<00:58,  1.39it/s, avg=0.10289, loss=0.11634]

trial_003 train e004:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:46<00:57,  1.40it/s, avg=0.10289, loss=0.11634]

trial_003 train e004:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:47<00:57,  1.40it/s, avg=0.10297, loss=0.10797]

trial_003 train e004:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:47<00:57,  1.38it/s, avg=0.10297, loss=0.10797]

trial_003 train e004:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:48<00:57,  1.38it/s, avg=0.10313, loss=0.11461]

trial_003 train e004:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:48<00:55,  1.41it/s, avg=0.10313, loss=0.11461]

trial_003 train e004:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:49<00:55,  1.41it/s, avg=0.10303, loss=0.09580]

trial_003 train e004:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:49<00:55,  1.39it/s, avg=0.10303, loss=0.09580]

trial_003 train e004:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:49<00:55,  1.39it/s, avg=0.10284, loss=0.08939]

trial_003 train e004:  49%|██████████████████████████████████████████████                                                | 73/149 [00:49<00:53,  1.41it/s, avg=0.10284, loss=0.08939]

trial_003 train e004:  49%|██████████████████████████████████████████████                                                | 73/149 [00:50<00:53,  1.41it/s, avg=0.10294, loss=0.11001]

trial_003 train e004:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:50<00:52,  1.42it/s, avg=0.10294, loss=0.11001]

trial_003 train e004:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:51<00:52,  1.42it/s, avg=0.10308, loss=0.11380]

trial_003 train e004:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:51<00:52,  1.41it/s, avg=0.10308, loss=0.11380]

trial_003 train e004:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:51<00:52,  1.41it/s, avg=0.10298, loss=0.09540]

trial_003 train e004:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:51<00:51,  1.43it/s, avg=0.10298, loss=0.09540]

trial_003 train e004:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:52<00:51,  1.43it/s, avg=0.10285, loss=0.09278]

trial_003 train e004:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:52<00:50,  1.42it/s, avg=0.10285, loss=0.09278]

trial_003 train e004:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:53<00:50,  1.42it/s, avg=0.10269, loss=0.09072]

trial_003 train e004:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:53<00:50,  1.41it/s, avg=0.10269, loss=0.09072]

trial_003 train e004:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:53<00:50,  1.41it/s, avg=0.10271, loss=0.10429]

trial_003 train e004:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:54<00:49,  1.41it/s, avg=0.10271, loss=0.10429]

trial_003 train e004:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:54<00:49,  1.41it/s, avg=0.10291, loss=0.11808]

trial_003 train e004:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:54<00:48,  1.42it/s, avg=0.10291, loss=0.11808]

trial_003 train e004:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:55<00:48,  1.42it/s, avg=0.10281, loss=0.09512]

trial_003 train e004:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:55<00:47,  1.42it/s, avg=0.10281, loss=0.09512]

trial_003 train e004:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:56<00:47,  1.42it/s, avg=0.10283, loss=0.10470]

trial_003 train e004:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:56<00:47,  1.40it/s, avg=0.10283, loss=0.10470]

trial_003 train e004:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:56<00:47,  1.40it/s, avg=0.10282, loss=0.10203]

trial_003 train e004:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:56<00:46,  1.40it/s, avg=0.10282, loss=0.10203]

trial_003 train e004:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:57<00:46,  1.40it/s, avg=0.10281, loss=0.10191]

trial_003 train e004:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:57<00:44,  1.45it/s, avg=0.10281, loss=0.10191]

trial_003 train e004:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:58<00:44,  1.45it/s, avg=0.10289, loss=0.10923]

trial_003 train e004:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [00:58<00:45,  1.41it/s, avg=0.10289, loss=0.10923]

trial_003 train e004:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [00:58<00:45,  1.41it/s, avg=0.10274, loss=0.08984]

trial_003 train e004:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [00:58<00:44,  1.42it/s, avg=0.10274, loss=0.08984]

trial_003 train e004:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [00:59<00:44,  1.42it/s, avg=0.10254, loss=0.08526]

trial_003 train e004:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [00:59<00:43,  1.42it/s, avg=0.10254, loss=0.08526]

trial_003 train e004:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:00<00:43,  1.42it/s, avg=0.10241, loss=0.09156]

trial_003 train e004:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:00<00:42,  1.42it/s, avg=0.10241, loss=0.09156]

trial_003 train e004:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:01<00:42,  1.42it/s, avg=0.10240, loss=0.10115]

trial_003 train e004:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:01<00:42,  1.41it/s, avg=0.10240, loss=0.10115]

trial_003 train e004:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:01<00:42,  1.41it/s, avg=0.10245, loss=0.10700]

trial_003 train e004:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:01<00:42,  1.40it/s, avg=0.10245, loss=0.10700]

trial_003 train e004:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:02<00:42,  1.40it/s, avg=0.10266, loss=0.12175]

trial_003 train e004:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:02<00:41,  1.40it/s, avg=0.10266, loss=0.12175]

trial_003 train e004:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:03<00:41,  1.40it/s, avg=0.10272, loss=0.10826]

trial_003 train e004:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:03<00:41,  1.38it/s, avg=0.10272, loss=0.10826]

trial_003 train e004:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:03<00:41,  1.38it/s, avg=0.10265, loss=0.09635]

trial_003 train e004:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:03<00:40,  1.37it/s, avg=0.10265, loss=0.09635]

trial_003 train e004:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:04<00:40,  1.37it/s, avg=0.10266, loss=0.10331]

trial_003 train e004:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:04<00:39,  1.41it/s, avg=0.10266, loss=0.10331]

trial_003 train e004:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:05<00:39,  1.41it/s, avg=0.10250, loss=0.08780]

trial_003 train e004:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:05<00:38,  1.41it/s, avg=0.10250, loss=0.08780]

trial_003 train e004:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:06<00:38,  1.41it/s, avg=0.10253, loss=0.10508]

trial_003 train e004:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:06<00:37,  1.42it/s, avg=0.10253, loss=0.10508]

trial_003 train e004:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:06<00:37,  1.42it/s, avg=0.10250, loss=0.10009]

trial_003 train e004:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:06<00:36,  1.41it/s, avg=0.10250, loss=0.10009]

trial_003 train e004:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:07<00:36,  1.41it/s, avg=0.10247, loss=0.09908]

trial_003 train e004:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:07<00:35,  1.44it/s, avg=0.10247, loss=0.09908]

trial_003 train e004:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:08<00:35,  1.44it/s, avg=0.10256, loss=0.11171]

trial_003 train e004:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:08<00:35,  1.41it/s, avg=0.10256, loss=0.11171]

trial_003 train e004:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:08<00:35,  1.41it/s, avg=0.10250, loss=0.09639]

trial_003 train e004:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:08<00:34,  1.43it/s, avg=0.10250, loss=0.09639]

trial_003 train e004:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:09<00:34,  1.43it/s, avg=0.10255, loss=0.10747]

trial_003 train e004:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:09<00:33,  1.43it/s, avg=0.10255, loss=0.10747]

trial_003 train e004:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:10<00:33,  1.43it/s, avg=0.10259, loss=0.10612]

trial_003 train e004:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:10<00:33,  1.42it/s, avg=0.10259, loss=0.10612]

trial_003 train e004:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:10<00:33,  1.42it/s, avg=0.10250, loss=0.09370]

trial_003 train e004:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:10<00:32,  1.42it/s, avg=0.10250, loss=0.09370]

trial_003 train e004:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:11<00:32,  1.42it/s, avg=0.10265, loss=0.11815]

trial_003 train e004:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:11<00:31,  1.45it/s, avg=0.10265, loss=0.11815]

trial_003 train e004:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:12<00:31,  1.45it/s, avg=0.10251, loss=0.08846]

trial_003 train e004:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:12<00:31,  1.42it/s, avg=0.10251, loss=0.08846]

trial_003 train e004:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:13<00:31,  1.42it/s, avg=0.10236, loss=0.08620]

trial_003 train e004:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:13<00:30,  1.43it/s, avg=0.10236, loss=0.08620]

trial_003 train e004:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:13<00:30,  1.43it/s, avg=0.10241, loss=0.10714]

trial_003 train e004:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:13<00:29,  1.42it/s, avg=0.10241, loss=0.10714]

trial_003 train e004:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:14<00:29,  1.42it/s, avg=0.10235, loss=0.09682]

trial_003 train e004:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:14<00:29,  1.40it/s, avg=0.10235, loss=0.09682]

trial_003 train e004:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:15<00:29,  1.40it/s, avg=0.10226, loss=0.09216]

trial_003 train e004:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:15<00:28,  1.41it/s, avg=0.10226, loss=0.09216]

trial_003 train e004:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:15<00:28,  1.41it/s, avg=0.10212, loss=0.08691]

trial_003 train e004:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:15<00:27,  1.42it/s, avg=0.10212, loss=0.08691]

trial_003 train e004:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:16<00:27,  1.42it/s, avg=0.10211, loss=0.10121]

trial_003 train e004:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:16<00:26,  1.41it/s, avg=0.10211, loss=0.10121]

trial_003 train e004:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:17<00:26,  1.41it/s, avg=0.10212, loss=0.10352]

trial_003 train e004:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:17<00:26,  1.41it/s, avg=0.10212, loss=0.10352]

trial_003 train e004:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:18<00:26,  1.41it/s, avg=0.10210, loss=0.09977]

trial_003 train e004:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:18<00:25,  1.42it/s, avg=0.10210, loss=0.09977]

trial_003 train e004:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:18<00:25,  1.42it/s, avg=0.10211, loss=0.10272]

trial_003 train e004:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:18<00:24,  1.42it/s, avg=0.10211, loss=0.10272]

trial_003 train e004:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:19<00:24,  1.42it/s, avg=0.10215, loss=0.10684]

trial_003 train e004:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:19<00:24,  1.41it/s, avg=0.10215, loss=0.10684]

trial_003 train e004:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:20<00:24,  1.41it/s, avg=0.10212, loss=0.09843]

trial_003 train e004:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:20<00:23,  1.40it/s, avg=0.10212, loss=0.09843]

trial_003 train e004:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:20<00:23,  1.40it/s, avg=0.10202, loss=0.09035]

trial_003 train e004:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:20<00:23,  1.38it/s, avg=0.10202, loss=0.09035]

trial_003 train e004:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:21<00:23,  1.38it/s, avg=0.10202, loss=0.10263]

trial_003 train e004:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:21<00:21,  1.42it/s, avg=0.10202, loss=0.10263]

trial_003 train e004:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:22<00:21,  1.42it/s, avg=0.10209, loss=0.10996]

trial_003 train e004:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:22<00:21,  1.41it/s, avg=0.10209, loss=0.10996]

trial_003 train e004:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:23<00:21,  1.41it/s, avg=0.10201, loss=0.09196]

trial_003 train e004:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:23<00:20,  1.38it/s, avg=0.10201, loss=0.09196]

trial_003 train e004:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:23<00:20,  1.38it/s, avg=0.10207, loss=0.11007]

trial_003 train e004:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:23<00:20,  1.39it/s, avg=0.10207, loss=0.11007]

trial_003 train e004:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:24<00:20,  1.39it/s, avg=0.10223, loss=0.12086]

trial_003 train e004:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:24<00:19,  1.39it/s, avg=0.10223, loss=0.12086]

trial_003 train e004:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:25<00:19,  1.39it/s, avg=0.10234, loss=0.11642]

trial_003 train e004:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:25<00:18,  1.38it/s, avg=0.10234, loss=0.11642]

trial_003 train e004:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:25<00:18,  1.38it/s, avg=0.10224, loss=0.08991]

trial_003 train e004:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:25<00:18,  1.36it/s, avg=0.10224, loss=0.08991]

trial_003 train e004:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:26<00:18,  1.36it/s, avg=0.10220, loss=0.09703]

trial_003 train e004:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:26<00:17,  1.37it/s, avg=0.10220, loss=0.09703]

trial_003 train e004:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:27<00:17,  1.37it/s, avg=0.10233, loss=0.11867]

trial_003 train e004:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:27<00:16,  1.40it/s, avg=0.10233, loss=0.11867]

trial_003 train e004:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:28<00:16,  1.40it/s, avg=0.10236, loss=0.10653]

trial_003 train e004:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:28<00:15,  1.43it/s, avg=0.10236, loss=0.10653]

trial_003 train e004:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:28<00:15,  1.43it/s, avg=0.10236, loss=0.10210]

trial_003 train e004:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:28<00:14,  1.40it/s, avg=0.10236, loss=0.10210]

trial_003 train e004:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:29<00:14,  1.40it/s, avg=0.10235, loss=0.10053]

trial_003 train e004:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:29<00:14,  1.41it/s, avg=0.10235, loss=0.10053]

trial_003 train e004:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:30<00:14,  1.41it/s, avg=0.10226, loss=0.09118]

trial_003 train e004:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:30<00:13,  1.40it/s, avg=0.10226, loss=0.09118]

trial_003 train e004:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:30<00:13,  1.40it/s, avg=0.10221, loss=0.09510]

trial_003 train e004:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:30<00:12,  1.43it/s, avg=0.10221, loss=0.09510]

trial_003 train e004:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:31<00:12,  1.43it/s, avg=0.10214, loss=0.09298]

trial_003 train e004:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:31<00:11,  1.43it/s, avg=0.10214, loss=0.09298]

trial_003 train e004:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:32<00:11,  1.43it/s, avg=0.10218, loss=0.10758]

trial_003 train e004:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:32<00:11,  1.41it/s, avg=0.10218, loss=0.10758]

trial_003 train e004:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:32<00:11,  1.41it/s, avg=0.10223, loss=0.10935]

trial_003 train e004:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:32<00:10,  1.43it/s, avg=0.10223, loss=0.10935]

trial_003 train e004:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:33<00:10,  1.43it/s, avg=0.10223, loss=0.10212]

trial_003 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:33<00:09,  1.46it/s, avg=0.10223, loss=0.10212]

trial_003 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:34<00:09,  1.46it/s, avg=0.10231, loss=0.11299]

trial_003 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:34<00:09,  1.41it/s, avg=0.10231, loss=0.11299]

trial_003 train e004:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:35<00:09,  1.41it/s, avg=0.10232, loss=0.10338]

trial_003 train e004:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:35<00:08,  1.42it/s, avg=0.10232, loss=0.10338]

trial_003 train e004:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:35<00:08,  1.42it/s, avg=0.10227, loss=0.09527]

trial_003 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:35<00:07,  1.43it/s, avg=0.10227, loss=0.09527]

trial_003 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:36<00:07,  1.43it/s, avg=0.10228, loss=0.10385]

trial_003 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:36<00:07,  1.41it/s, avg=0.10228, loss=0.10385]

trial_003 train e004:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:37<00:07,  1.41it/s, avg=0.10219, loss=0.08989]

trial_003 train e004:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:37<00:06,  1.40it/s, avg=0.10219, loss=0.08989]

trial_003 train e004:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:37<00:06,  1.40it/s, avg=0.10212, loss=0.09246]

trial_003 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:37<00:05,  1.43it/s, avg=0.10212, loss=0.09246]

trial_003 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:38<00:05,  1.43it/s, avg=0.10216, loss=0.10807]

trial_003 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:38<00:04,  1.43it/s, avg=0.10216, loss=0.10807]

trial_003 train e004:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:39<00:04,  1.43it/s, avg=0.10215, loss=0.10014]

trial_003 train e004:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:39<00:04,  1.43it/s, avg=0.10215, loss=0.10014]

trial_003 train e004:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:39<00:04,  1.43it/s, avg=0.10219, loss=0.10824]

trial_003 train e004:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:39<00:03,  1.46it/s, avg=0.10219, loss=0.10824]

trial_003 train e004:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:40<00:03,  1.46it/s, avg=0.10222, loss=0.10711]

trial_003 train e004:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:40<00:02,  1.47it/s, avg=0.10222, loss=0.10711]

trial_003 train e004:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:41<00:02,  1.47it/s, avg=0.10217, loss=0.09412]

trial_003 train e004:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:41<00:02,  1.48it/s, avg=0.10217, loss=0.09412]

trial_003 train e004:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:41<00:02,  1.48it/s, avg=0.10209, loss=0.09078]

trial_003 train e004:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:41<00:01,  1.50it/s, avg=0.10209, loss=0.09078]

trial_003 train e004:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:42<00:01,  1.50it/s, avg=0.10200, loss=0.08820]

trial_003 train e004:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:42<00:00,  1.52it/s, avg=0.10200, loss=0.08820]

trial_003 train e004:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:42<00:00,  1.52it/s, avg=0.10201, loss=0.10869]

trial_003 train e004: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:42<00:00,  1.85it/s, avg=0.10201, loss=0.10869]

trial_003 val e004:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e004:   2%|██▌                                                                                                                          | 1/50 [00:00<00:16,  2.98it/s]

trial_003 val e004:   4%|█████                                                                                                                        | 2/50 [00:00<00:16,  2.96it/s]

trial_003 val e004:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:15,  2.98it/s]

trial_003 val e004:   8%|██████████                                                                                                                   | 4/50 [00:01<00:15,  2.98it/s]

trial_003 val e004:  10%|████████████▌                                                                                                                | 5/50 [00:01<00:15,  2.97it/s]

trial_003 val e004:  12%|███████████████                                                                                                              | 6/50 [00:02<00:14,  2.96it/s]

trial_003 val e004:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:14,  2.97it/s]

trial_003 val e004:  16%|████████████████████                                                                                                         | 8/50 [00:02<00:14,  2.97it/s]

trial_003 val e004:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:13,  2.94it/s]

trial_003 val e004:  20%|████████████████████████▊                                                                                                   | 10/50 [00:03<00:14,  2.84it/s]

trial_003 val e004:  22%|███████████████████████████▎                                                                                                | 11/50 [00:03<00:13,  2.88it/s]

trial_003 val e004:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:13,  2.90it/s]

trial_003 val e004:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:04<00:13,  2.84it/s]

trial_003 val e004:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:04<00:12,  2.85it/s]

trial_003 val e004:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:05<00:12,  2.89it/s]

trial_003 val e004:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:05<00:11,  2.92it/s]

trial_003 val e004:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:05<00:11,  2.94it/s]

trial_003 val e004:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:06<00:10,  2.95it/s]

trial_003 val e004:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:06<00:10,  2.96it/s]

trial_003 val e004:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:06<00:10,  2.96it/s]

trial_003 val e004:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:07<00:09,  2.95it/s]

trial_003 val e004:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:07<00:09,  2.95it/s]

trial_003 val e004:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:07<00:09,  2.96it/s]

trial_003 val e004:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:08<00:08,  2.97it/s]

trial_003 val e004:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:08<00:08,  2.97it/s]

trial_003 val e004:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:08<00:08,  2.97it/s]

trial_003 val e004:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:09<00:07,  2.98it/s]

trial_003 val e004:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:09<00:07,  2.94it/s]

trial_003 val e004:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:09<00:07,  2.74it/s]

trial_003 val e004:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:10<00:07,  2.79it/s]

trial_003 val e004:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:10<00:06,  2.84it/s]

trial_003 val e004:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:10<00:06,  2.88it/s]

trial_003 val e004:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:11<00:05,  2.91it/s]

trial_003 val e004:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:11<00:05,  2.94it/s]

trial_003 val e004:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:11<00:05,  2.96it/s]

trial_003 val e004:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:12<00:04,  2.95it/s]

trial_003 val e004:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:12<00:04,  2.97it/s]

trial_003 val e004:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:12<00:04,  2.96it/s]

trial_003 val e004:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:13<00:03,  2.96it/s]

trial_003 val e004:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:13<00:03,  2.96it/s]

trial_003 val e004:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:13<00:03,  2.96it/s]

trial_003 val e004:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:14<00:02,  2.96it/s]

trial_003 val e004:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:14<00:02,  2.97it/s]

trial_003 val e004:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:15<00:02,  2.96it/s]

trial_003 val e004:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:15<00:01,  2.93it/s]

trial_003 val e004:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:15<00:01,  2.95it/s]

trial_003 val e004:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:16<00:01,  2.92it/s]

trial_003 val e004:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:16<00:00,  2.94it/s]

trial_003 val e004:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:16<00:00,  2.95it/s]

trial_003 val e004: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:17<00:00,  2.98it/s]

[2026-05-28 21:13:21] [trial_003] epoch=004 | train_loss=0.102015 | val_MAE=0.101654 | val_S=0.898346 | best_S=0.898346 @epoch=4 | patience=0/5

[trial_003] epochs:   4%|████▊                                                                                                                    | 4/100 [08:11<3:15:21, 122.10s/it]

trial_003 train e005:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e005:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09856, loss=0.09856]

trial_003 train e005:   1%|▋                                                                                              | 1/149 [00:00<01:39,  1.49it/s, avg=0.09856, loss=0.09856]

trial_003 train e005:   1%|▋                                                                                              | 1/149 [00:01<01:39,  1.49it/s, avg=0.10113, loss=0.10371]

trial_003 train e005:   1%|█▎                                                                                             | 2/149 [00:01<01:39,  1.48it/s, avg=0.10113, loss=0.10371]

trial_003 train e005:   1%|█▎                                                                                             | 2/149 [00:01<01:39,  1.48it/s, avg=0.10149, loss=0.10220]

trial_003 train e005:   2%|█▉                                                                                             | 3/149 [00:01<01:35,  1.54it/s, avg=0.10149, loss=0.10220]

trial_003 train e005:   2%|█▉                                                                                             | 3/149 [00:02<01:35,  1.54it/s, avg=0.09998, loss=0.09545]

trial_003 train e005:   3%|██▌                                                                                            | 4/149 [00:02<01:35,  1.52it/s, avg=0.09998, loss=0.09545]

trial_003 train e005:   3%|██▌                                                                                            | 4/149 [00:03<01:35,  1.52it/s, avg=0.09908, loss=0.09549]

trial_003 train e005:   3%|███▏                                                                                           | 5/149 [00:03<01:32,  1.56it/s, avg=0.09908, loss=0.09549]

trial_003 train e005:   3%|███▏                                                                                           | 5/149 [00:03<01:32,  1.56it/s, avg=0.09770, loss=0.09080]

trial_003 train e005:   4%|███▊                                                                                           | 6/149 [00:03<01:33,  1.53it/s, avg=0.09770, loss=0.09080]

trial_003 train e005:   4%|███▊                                                                                           | 6/149 [00:04<01:33,  1.53it/s, avg=0.09635, loss=0.08820]

trial_003 train e005:   5%|████▍                                                                                          | 7/149 [00:04<01:34,  1.51it/s, avg=0.09635, loss=0.08820]

trial_003 train e005:   5%|████▍                                                                                          | 7/149 [00:05<01:34,  1.51it/s, avg=0.09589, loss=0.09269]

trial_003 train e005:   5%|█████                                                                                          | 8/149 [00:05<01:35,  1.48it/s, avg=0.09589, loss=0.09269]

trial_003 train e005:   5%|█████                                                                                          | 8/149 [00:06<01:35,  1.48it/s, avg=0.09630, loss=0.09963]

trial_003 train e005:   6%|█████▋                                                                                         | 9/149 [00:06<01:36,  1.45it/s, avg=0.09630, loss=0.09963]

trial_003 train e005:   6%|█████▋                                                                                         | 9/149 [00:06<01:36,  1.45it/s, avg=0.09594, loss=0.09267]

trial_003 train e005:   7%|██████▎                                                                                       | 10/149 [00:06<01:34,  1.46it/s, avg=0.09594, loss=0.09267]

trial_003 train e005:   7%|██████▎                                                                                       | 10/149 [00:07<01:34,  1.46it/s, avg=0.09739, loss=0.11192]

trial_003 train e005:   7%|██████▉                                                                                       | 11/149 [00:07<01:30,  1.52it/s, avg=0.09739, loss=0.11192]

trial_003 train e005:   7%|██████▉                                                                                       | 11/149 [00:08<01:30,  1.52it/s, avg=0.09795, loss=0.10406]

trial_003 train e005:   8%|███████▌                                                                                      | 12/149 [00:08<01:32,  1.48it/s, avg=0.09795, loss=0.10406]

trial_003 train e005:   8%|███████▌                                                                                      | 12/149 [00:08<01:32,  1.48it/s, avg=0.09863, loss=0.10680]

trial_003 train e005:   9%|████████▏                                                                                     | 13/149 [00:08<01:32,  1.46it/s, avg=0.09863, loss=0.10680]

trial_003 train e005:   9%|████████▏                                                                                     | 13/149 [00:09<01:32,  1.46it/s, avg=0.09809, loss=0.09110]

trial_003 train e005:   9%|████████▊                                                                                     | 14/149 [00:09<01:31,  1.47it/s, avg=0.09809, loss=0.09110]

trial_003 train e005:   9%|████████▊                                                                                     | 14/149 [00:10<01:31,  1.47it/s, avg=0.09882, loss=0.10895]

trial_003 train e005:  10%|█████████▍                                                                                    | 15/149 [00:10<01:32,  1.46it/s, avg=0.09882, loss=0.10895]

trial_003 train e005:  10%|█████████▍                                                                                    | 15/149 [00:10<01:32,  1.46it/s, avg=0.09928, loss=0.10617]

trial_003 train e005:  11%|██████████                                                                                    | 16/149 [00:10<01:31,  1.45it/s, avg=0.09928, loss=0.10617]

trial_003 train e005:  11%|██████████                                                                                    | 16/149 [00:11<01:31,  1.45it/s, avg=0.09891, loss=0.09313]

trial_003 train e005:  11%|██████████▋                                                                                   | 17/149 [00:11<01:32,  1.43it/s, avg=0.09891, loss=0.09313]

trial_003 train e005:  11%|██████████▋                                                                                   | 17/149 [00:12<01:32,  1.43it/s, avg=0.09876, loss=0.09618]

trial_003 train e005:  12%|███████████▎                                                                                  | 18/149 [00:12<01:28,  1.47it/s, avg=0.09876, loss=0.09618]

trial_003 train e005:  12%|███████████▎                                                                                  | 18/149 [00:12<01:28,  1.47it/s, avg=0.09851, loss=0.09392]

trial_003 train e005:  13%|███████████▉                                                                                  | 19/149 [00:12<01:30,  1.44it/s, avg=0.09851, loss=0.09392]

trial_003 train e005:  13%|███████████▉                                                                                  | 19/149 [00:13<01:30,  1.44it/s, avg=0.09859, loss=0.10009]

trial_003 train e005:  13%|████████████▌                                                                                 | 20/149 [00:13<01:29,  1.45it/s, avg=0.09859, loss=0.10009]

trial_003 train e005:  13%|████████████▌                                                                                 | 20/149 [00:14<01:29,  1.45it/s, avg=0.09880, loss=0.10316]

trial_003 train e005:  14%|█████████████▏                                                                                | 21/149 [00:14<01:30,  1.41it/s, avg=0.09880, loss=0.10316]

trial_003 train e005:  14%|█████████████▏                                                                                | 21/149 [00:14<01:30,  1.41it/s, avg=0.09938, loss=0.11147]

trial_003 train e005:  15%|█████████████▉                                                                                | 22/149 [00:15<01:29,  1.42it/s, avg=0.09938, loss=0.11147]

trial_003 train e005:  15%|█████████████▉                                                                                | 22/149 [00:15<01:29,  1.42it/s, avg=0.09989, loss=0.11112]

trial_003 train e005:  15%|██████████████▌                                                                               | 23/149 [00:15<01:28,  1.42it/s, avg=0.09989, loss=0.11112]

trial_003 train e005:  15%|██████████████▌                                                                               | 23/149 [00:16<01:28,  1.42it/s, avg=0.09999, loss=0.10229]

trial_003 train e005:  16%|███████████████▏                                                                              | 24/149 [00:16<01:26,  1.44it/s, avg=0.09999, loss=0.10229]

trial_003 train e005:  16%|███████████████▏                                                                              | 24/149 [00:17<01:26,  1.44it/s, avg=0.09977, loss=0.09438]

trial_003 train e005:  17%|███████████████▊                                                                              | 25/149 [00:17<01:27,  1.41it/s, avg=0.09977, loss=0.09438]

trial_003 train e005:  17%|███████████████▊                                                                              | 25/149 [00:17<01:27,  1.41it/s, avg=0.09980, loss=0.10075]

trial_003 train e005:  17%|████████████████▍                                                                             | 26/149 [00:17<01:27,  1.40it/s, avg=0.09980, loss=0.10075]

trial_003 train e005:  17%|████████████████▍                                                                             | 26/149 [00:18<01:27,  1.40it/s, avg=0.09965, loss=0.09560]

trial_003 train e005:  18%|█████████████████                                                                             | 27/149 [00:18<01:26,  1.41it/s, avg=0.09965, loss=0.09560]

trial_003 train e005:  18%|█████████████████                                                                             | 27/149 [00:19<01:26,  1.41it/s, avg=0.09939, loss=0.09250]

trial_003 train e005:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:25,  1.42it/s, avg=0.09939, loss=0.09250]

trial_003 train e005:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:25,  1.42it/s, avg=0.09966, loss=0.10712]

trial_003 train e005:  19%|██████████████████▎                                                                           | 29/149 [00:19<01:26,  1.40it/s, avg=0.09966, loss=0.10712]

trial_003 train e005:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:26,  1.40it/s, avg=0.09991, loss=0.10717]

trial_003 train e005:  20%|██████████████████▉                                                                           | 30/149 [00:20<01:24,  1.41it/s, avg=0.09991, loss=0.10717]

trial_003 train e005:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:24,  1.41it/s, avg=0.09967, loss=0.09256]

trial_003 train e005:  21%|███████████████████▌                                                                          | 31/149 [00:21<01:22,  1.44it/s, avg=0.09967, loss=0.09256]

trial_003 train e005:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:22,  1.44it/s, avg=0.09963, loss=0.09830]

trial_003 train e005:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:22,  1.42it/s, avg=0.09963, loss=0.09830]

trial_003 train e005:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:22,  1.42it/s, avg=0.09974, loss=0.10335]

trial_003 train e005:  22%|████████████████████▊                                                                         | 33/149 [00:22<01:22,  1.40it/s, avg=0.09974, loss=0.10335]

trial_003 train e005:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:22,  1.40it/s, avg=0.09973, loss=0.09937]

trial_003 train e005:  23%|█████████████████████▍                                                                        | 34/149 [00:23<01:22,  1.39it/s, avg=0.09973, loss=0.09937]

trial_003 train e005:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:22,  1.39it/s, avg=0.09935, loss=0.08629]

trial_003 train e005:  23%|██████████████████████                                                                        | 35/149 [00:24<01:19,  1.43it/s, avg=0.09935, loss=0.08629]

trial_003 train e005:  23%|██████████████████████                                                                        | 35/149 [00:24<01:19,  1.43it/s, avg=0.09940, loss=0.10128]

trial_003 train e005:  24%|██████████████████████▋                                                                       | 36/149 [00:24<01:20,  1.40it/s, avg=0.09940, loss=0.10128]

trial_003 train e005:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:20,  1.40it/s, avg=0.09945, loss=0.10124]

trial_003 train e005:  25%|███████████████████████▎                                                                      | 37/149 [00:25<01:22,  1.36it/s, avg=0.09945, loss=0.10124]

trial_003 train e005:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:22,  1.36it/s, avg=0.09966, loss=0.10750]

trial_003 train e005:  26%|███████████████████████▉                                                                      | 38/149 [00:26<01:20,  1.38it/s, avg=0.09966, loss=0.10750]

trial_003 train e005:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.38it/s, avg=0.09976, loss=0.10341]

trial_003 train e005:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:20,  1.36it/s, avg=0.09976, loss=0.10341]

trial_003 train e005:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:20,  1.36it/s, avg=0.09954, loss=0.09090]

trial_003 train e005:  27%|█████████████████████████▏                                                                    | 40/149 [00:27<01:20,  1.35it/s, avg=0.09954, loss=0.09090]

trial_003 train e005:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:20,  1.35it/s, avg=0.09981, loss=0.11072]

trial_003 train e005:  28%|█████████████████████████▊                                                                    | 41/149 [00:28<01:20,  1.35it/s, avg=0.09981, loss=0.11072]

trial_003 train e005:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:20,  1.35it/s, avg=0.09989, loss=0.10332]

trial_003 train e005:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:18,  1.36it/s, avg=0.09989, loss=0.10332]

trial_003 train e005:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:18,  1.36it/s, avg=0.09998, loss=0.10362]

trial_003 train e005:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:15,  1.40it/s, avg=0.09998, loss=0.10362]

trial_003 train e005:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:15,  1.40it/s, avg=0.09999, loss=0.10044]

trial_003 train e005:  30%|███████████████████████████▊                                                                  | 44/149 [00:30<01:13,  1.43it/s, avg=0.09999, loss=0.10044]

trial_003 train e005:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:13,  1.43it/s, avg=0.10000, loss=0.10052]

trial_003 train e005:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:14,  1.39it/s, avg=0.10000, loss=0.10052]

trial_003 train e005:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.39it/s, avg=0.10029, loss=0.11307]

trial_003 train e005:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:13,  1.40it/s, avg=0.10029, loss=0.11307]

trial_003 train e005:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:13,  1.40it/s, avg=0.10038, loss=0.10474]

trial_003 train e005:  32%|█████████████████████████████▋                                                                | 47/149 [00:32<01:13,  1.40it/s, avg=0.10038, loss=0.10474]

trial_003 train e005:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:13,  1.40it/s, avg=0.10025, loss=0.09400]

trial_003 train e005:  32%|██████████████████████████████▎                                                               | 48/149 [00:33<01:12,  1.39it/s, avg=0.10025, loss=0.09400]

trial_003 train e005:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.39it/s, avg=0.10022, loss=0.09887]

trial_003 train e005:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:12,  1.38it/s, avg=0.10022, loss=0.09887]

trial_003 train e005:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.38it/s, avg=0.10023, loss=0.10058]

trial_003 train e005:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:12,  1.37it/s, avg=0.10023, loss=0.10058]

trial_003 train e005:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:12,  1.37it/s, avg=0.10012, loss=0.09495]

trial_003 train e005:  34%|████████████████████████████████▏                                                             | 51/149 [00:35<01:12,  1.36it/s, avg=0.10012, loss=0.09495]

trial_003 train e005:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:12,  1.36it/s, avg=0.09996, loss=0.09146]

trial_003 train e005:  35%|████████████████████████████████▊                                                             | 52/149 [00:36<01:11,  1.35it/s, avg=0.09996, loss=0.09146]

trial_003 train e005:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:11,  1.35it/s, avg=0.09999, loss=0.10187]

trial_003 train e005:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:10,  1.36it/s, avg=0.09999, loss=0.10187]

trial_003 train e005:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.09992, loss=0.09616]

trial_003 train e005:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:10,  1.35it/s, avg=0.09992, loss=0.09616]

trial_003 train e005:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:10,  1.35it/s, avg=0.09979, loss=0.09274]

trial_003 train e005:  37%|██████████████████████████████████▋                                                           | 55/149 [00:38<01:09,  1.35it/s, avg=0.09979, loss=0.09274]

trial_003 train e005:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:09,  1.35it/s, avg=0.09976, loss=0.09819]

trial_003 train e005:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:06,  1.39it/s, avg=0.09976, loss=0.09819]

trial_003 train e005:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.39it/s, avg=0.09995, loss=0.11065]

trial_003 train e005:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:06,  1.39it/s, avg=0.09995, loss=0.11065]

trial_003 train e005:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:06,  1.39it/s, avg=0.10003, loss=0.10435]

trial_003 train e005:  39%|████████████████████████████████████▌                                                         | 58/149 [00:40<01:05,  1.39it/s, avg=0.10003, loss=0.10435]

trial_003 train e005:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.39it/s, avg=0.10004, loss=0.10071]

trial_003 train e005:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:41<01:03,  1.41it/s, avg=0.10004, loss=0.10071]

trial_003 train e005:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:03,  1.41it/s, avg=0.10031, loss=0.11625]

trial_003 train e005:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:04,  1.37it/s, avg=0.10031, loss=0.11625]

trial_003 train e005:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:04,  1.37it/s, avg=0.10056, loss=0.11576]

trial_003 train e005:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:04,  1.37it/s, avg=0.10056, loss=0.11576]

trial_003 train e005:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:04,  1.37it/s, avg=0.10061, loss=0.10330]

trial_003 train e005:  42%|███████████████████████████████████████                                                       | 62/149 [00:43<01:03,  1.37it/s, avg=0.10061, loss=0.10330]

trial_003 train e005:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:03,  1.37it/s, avg=0.10063, loss=0.10214]

trial_003 train e005:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<01:02,  1.38it/s, avg=0.10063, loss=0.10214]

trial_003 train e005:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:02,  1.38it/s, avg=0.10068, loss=0.10333]

trial_003 train e005:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<00:59,  1.42it/s, avg=0.10068, loss=0.10333]

trial_003 train e005:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<00:59,  1.42it/s, avg=0.10085, loss=0.11179]

trial_003 train e005:  44%|█████████████████████████████████████████                                                     | 65/149 [00:45<00:59,  1.41it/s, avg=0.10085, loss=0.11179]

trial_003 train e005:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.41it/s, avg=0.10072, loss=0.09263]

trial_003 train e005:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<00:59,  1.41it/s, avg=0.10072, loss=0.09263]

trial_003 train e005:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:59,  1.41it/s, avg=0.10074, loss=0.10167]

trial_003 train e005:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:58,  1.40it/s, avg=0.10074, loss=0.10167]

trial_003 train e005:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.40it/s, avg=0.10054, loss=0.08759]

trial_003 train e005:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:58,  1.39it/s, avg=0.10054, loss=0.08759]

trial_003 train e005:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:58,  1.39it/s, avg=0.10051, loss=0.09827]

trial_003 train e005:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:48<00:57,  1.40it/s, avg=0.10051, loss=0.09827]

trial_003 train e005:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:57,  1.40it/s, avg=0.10031, loss=0.08649]

trial_003 train e005:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:49<00:56,  1.39it/s, avg=0.10031, loss=0.08649]

trial_003 train e005:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.39it/s, avg=0.10036, loss=0.10354]

trial_003 train e005:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:54,  1.42it/s, avg=0.10036, loss=0.10354]

trial_003 train e005:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:54,  1.42it/s, avg=0.10029, loss=0.09531]

trial_003 train e005:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:50<00:54,  1.42it/s, avg=0.10029, loss=0.09531]

trial_003 train e005:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:54,  1.42it/s, avg=0.10023, loss=0.09608]

trial_003 train e005:  49%|██████████████████████████████████████████████                                                | 73/149 [00:51<00:53,  1.42it/s, avg=0.10023, loss=0.09608]

trial_003 train e005:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:53,  1.42it/s, avg=0.10028, loss=0.10388]

trial_003 train e005:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:52,  1.43it/s, avg=0.10028, loss=0.10388]

trial_003 train e005:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:52,  1.43it/s, avg=0.10017, loss=0.09248]

trial_003 train e005:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:52,  1.41it/s, avg=0.10017, loss=0.09248]

trial_003 train e005:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:52,  1.41it/s, avg=0.10002, loss=0.08870]

trial_003 train e005:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:53<00:51,  1.42it/s, avg=0.10002, loss=0.08870]

trial_003 train e005:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:51,  1.42it/s, avg=0.10005, loss=0.10241]

trial_003 train e005:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:51,  1.41it/s, avg=0.10005, loss=0.10241]

trial_003 train e005:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:51,  1.41it/s, avg=0.10001, loss=0.09696]

trial_003 train e005:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:50,  1.40it/s, avg=0.10001, loss=0.09696]

trial_003 train e005:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:50,  1.40it/s, avg=0.10005, loss=0.10299]

trial_003 train e005:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:55<00:50,  1.39it/s, avg=0.10005, loss=0.10299]

trial_003 train e005:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.39it/s, avg=0.10013, loss=0.10654]

trial_003 train e005:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:56<00:50,  1.38it/s, avg=0.10013, loss=0.10654]

trial_003 train e005:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:50,  1.38it/s, avg=0.10004, loss=0.09253]

trial_003 train e005:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:50,  1.36it/s, avg=0.10004, loss=0.09253]

trial_003 train e005:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:50,  1.36it/s, avg=0.10038, loss=0.12813]

trial_003 train e005:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:47,  1.40it/s, avg=0.10038, loss=0.12813]

trial_003 train e005:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:47,  1.40it/s, avg=0.10025, loss=0.08967]

trial_003 train e005:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:58<00:48,  1.36it/s, avg=0.10025, loss=0.08967]

trial_003 train e005:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:48,  1.36it/s, avg=0.10022, loss=0.09767]

trial_003 train e005:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:59<00:47,  1.37it/s, avg=0.10022, loss=0.09767]

trial_003 train e005:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:47,  1.37it/s, avg=0.10013, loss=0.09284]

trial_003 train e005:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:46,  1.39it/s, avg=0.10013, loss=0.09284]

trial_003 train e005:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:46,  1.39it/s, avg=0.10002, loss=0.09040]

trial_003 train e005:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.40it/s, avg=0.10002, loss=0.09040]

trial_003 train e005:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.40it/s, avg=0.09999, loss=0.09713]

trial_003 train e005:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:01<00:44,  1.40it/s, avg=0.09999, loss=0.09713]

trial_003 train e005:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.40it/s, avg=0.10007, loss=0.10707]

trial_003 train e005:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:44,  1.38it/s, avg=0.10007, loss=0.10707]

trial_003 train e005:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:44,  1.38it/s, avg=0.10006, loss=0.09974]

trial_003 train e005:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:44,  1.36it/s, avg=0.10006, loss=0.09974]

trial_003 train e005:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:44,  1.36it/s, avg=0.10006, loss=0.09926]

trial_003 train e005:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:03<00:43,  1.36it/s, avg=0.10006, loss=0.09926]

trial_003 train e005:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:43,  1.36it/s, avg=0.09995, loss=0.09047]

trial_003 train e005:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:04<00:42,  1.37it/s, avg=0.09995, loss=0.09047]

trial_003 train e005:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.37it/s, avg=0.09984, loss=0.08936]

trial_003 train e005:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:41,  1.38it/s, avg=0.09984, loss=0.08936]

trial_003 train e005:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.38it/s, avg=0.09972, loss=0.08908]

trial_003 train e005:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:40,  1.38it/s, avg=0.09972, loss=0.08908]

trial_003 train e005:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:40,  1.38it/s, avg=0.09961, loss=0.08959]

trial_003 train e005:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:06<00:39,  1.40it/s, avg=0.09961, loss=0.08959]

trial_003 train e005:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:39,  1.40it/s, avg=0.09963, loss=0.10138]

trial_003 train e005:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:39,  1.38it/s, avg=0.09963, loss=0.10138]

trial_003 train e005:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.38it/s, avg=0.09953, loss=0.09009]

trial_003 train e005:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:38,  1.39it/s, avg=0.09953, loss=0.09009]

trial_003 train e005:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.39it/s, avg=0.09958, loss=0.10469]

trial_003 train e005:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.37it/s, avg=0.09958, loss=0.10469]

trial_003 train e005:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.37it/s, avg=0.09977, loss=0.11822]

trial_003 train e005:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:09<00:38,  1.34it/s, avg=0.09977, loss=0.11822]

trial_003 train e005:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:38,  1.34it/s, avg=0.09983, loss=0.10533]

trial_003 train e005:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:37,  1.35it/s, avg=0.09983, loss=0.10533]

trial_003 train e005:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:37,  1.35it/s, avg=0.09979, loss=0.09574]

trial_003 train e005:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:35,  1.38it/s, avg=0.09979, loss=0.09574]

trial_003 train e005:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:35,  1.38it/s, avg=0.09991, loss=0.11168]

trial_003 train e005:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:11<00:34,  1.38it/s, avg=0.09991, loss=0.11168]

trial_003 train e005:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.38it/s, avg=0.09980, loss=0.08911]

trial_003 train e005:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:34,  1.37it/s, avg=0.09980, loss=0.08911]

trial_003 train e005:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:34,  1.37it/s, avg=0.09990, loss=0.11011]

trial_003 train e005:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:33,  1.38it/s, avg=0.09990, loss=0.11011]

trial_003 train e005:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.38it/s, avg=0.09989, loss=0.09830]

trial_003 train e005:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.40it/s, avg=0.09989, loss=0.09830]

trial_003 train e005:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.40it/s, avg=0.10003, loss=0.11458]

trial_003 train e005:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:14<00:31,  1.38it/s, avg=0.10003, loss=0.11458]

trial_003 train e005:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.38it/s, avg=0.09991, loss=0.08723]

trial_003 train e005:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:31,  1.38it/s, avg=0.09991, loss=0.08723]

trial_003 train e005:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:31,  1.38it/s, avg=0.09999, loss=0.10943]

trial_003 train e005:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:30,  1.36it/s, avg=0.09999, loss=0.10943]

trial_003 train e005:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:30,  1.36it/s, avg=0.09988, loss=0.08738]

trial_003 train e005:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:30,  1.36it/s, avg=0.09988, loss=0.08738]

trial_003 train e005:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:30,  1.36it/s, avg=0.09963, loss=0.07293]

trial_003 train e005:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:17<00:29,  1.37it/s, avg=0.09963, loss=0.07293]

trial_003 train e005:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:29,  1.37it/s, avg=0.09966, loss=0.10236]

trial_003 train e005:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:28,  1.38it/s, avg=0.09966, loss=0.10236]

trial_003 train e005:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:28,  1.38it/s, avg=0.09971, loss=0.10584]

trial_003 train e005:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.39it/s, avg=0.09971, loss=0.10584]

trial_003 train e005:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.39it/s, avg=0.09982, loss=0.11193]

trial_003 train e005:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:19<00:26,  1.42it/s, avg=0.09982, loss=0.11193]

trial_003 train e005:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.42it/s, avg=0.09987, loss=0.10594]

trial_003 train e005:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:20<00:25,  1.41it/s, avg=0.09987, loss=0.10594]

trial_003 train e005:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.41it/s, avg=0.09991, loss=0.10450]

trial_003 train e005:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.41it/s, avg=0.09991, loss=0.10450]

trial_003 train e005:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.41it/s, avg=0.10000, loss=0.10989]

trial_003 train e005:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:21<00:23,  1.42it/s, avg=0.10000, loss=0.10989]

trial_003 train e005:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:23,  1.42it/s, avg=0.10005, loss=0.10525]

trial_003 train e005:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:22<00:22,  1.45it/s, avg=0.10005, loss=0.10525]

trial_003 train e005:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:22,  1.45it/s, avg=0.09991, loss=0.08435]

trial_003 train e005:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:22,  1.44it/s, avg=0.09991, loss=0.08435]

trial_003 train e005:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:22,  1.44it/s, avg=0.09988, loss=0.09585]

trial_003 train e005:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:21,  1.41it/s, avg=0.09988, loss=0.09585]

trial_003 train e005:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:21,  1.41it/s, avg=0.09984, loss=0.09580]

trial_003 train e005:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:24<00:20,  1.44it/s, avg=0.09984, loss=0.09580]

trial_003 train e005:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:20,  1.44it/s, avg=0.09997, loss=0.11544]

trial_003 train e005:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:20,  1.41it/s, avg=0.09997, loss=0.11544]

trial_003 train e005:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.41it/s, avg=0.09981, loss=0.08018]

trial_003 train e005:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:20,  1.38it/s, avg=0.09981, loss=0.08018]

trial_003 train e005:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:20,  1.38it/s, avg=0.09988, loss=0.10811]

trial_003 train e005:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:26<00:19,  1.37it/s, avg=0.09988, loss=0.10811]

trial_003 train e005:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.37it/s, avg=0.09980, loss=0.09057]

trial_003 train e005:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:27<00:18,  1.40it/s, avg=0.09980, loss=0.09057]

trial_003 train e005:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.40it/s, avg=0.09990, loss=0.11139]

trial_003 train e005:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.40it/s, avg=0.09990, loss=0.11139]

trial_003 train e005:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.40it/s, avg=0.09985, loss=0.09415]

trial_003 train e005:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:17,  1.38it/s, avg=0.09985, loss=0.09415]

trial_003 train e005:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:17,  1.38it/s, avg=0.09992, loss=0.10809]

trial_003 train e005:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:29<00:16,  1.39it/s, avg=0.09992, loss=0.10809]

trial_003 train e005:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.39it/s, avg=0.09983, loss=0.08908]

trial_003 train e005:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.38it/s, avg=0.09983, loss=0.08908]

trial_003 train e005:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.38it/s, avg=0.09969, loss=0.08233]

trial_003 train e005:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.36it/s, avg=0.09969, loss=0.08233]

trial_003 train e005:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.36it/s, avg=0.09966, loss=0.09571]

trial_003 train e005:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.36it/s, avg=0.09966, loss=0.09571]

trial_003 train e005:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.36it/s, avg=0.09973, loss=0.10808]

trial_003 train e005:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:32<00:14,  1.35it/s, avg=0.09973, loss=0.10808]

trial_003 train e005:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:14,  1.35it/s, avg=0.09968, loss=0.09290]

trial_003 train e005:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:13,  1.36it/s, avg=0.09968, loss=0.09290]

trial_003 train e005:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:13,  1.36it/s, avg=0.09959, loss=0.08885]

trial_003 train e005:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.37it/s, avg=0.09959, loss=0.08885]

trial_003 train e005:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.37it/s, avg=0.09957, loss=0.09685]

trial_003 train e005:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:34<00:11,  1.40it/s, avg=0.09957, loss=0.09685]

trial_003 train e005:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.40it/s, avg=0.09959, loss=0.10144]

trial_003 train e005:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.41it/s, avg=0.09959, loss=0.10144]

trial_003 train e005:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.41it/s, avg=0.09958, loss=0.09928]

trial_003 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:09,  1.41it/s, avg=0.09958, loss=0.09928]

trial_003 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:09,  1.41it/s, avg=0.09970, loss=0.11485]

trial_003 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.39it/s, avg=0.09970, loss=0.11485]

trial_003 train e005:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.39it/s, avg=0.09978, loss=0.11067]

trial_003 train e005:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:37<00:08,  1.38it/s, avg=0.09978, loss=0.11067]

trial_003 train e005:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.38it/s, avg=0.09985, loss=0.10963]

trial_003 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:07,  1.40it/s, avg=0.09985, loss=0.10963]

trial_003 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:07,  1.40it/s, avg=0.09987, loss=0.10292]

trial_003 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.39it/s, avg=0.09987, loss=0.10292]

trial_003 train e005:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.39it/s, avg=0.09984, loss=0.09547]

trial_003 train e005:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:39<00:06,  1.38it/s, avg=0.09984, loss=0.09547]

trial_003 train e005:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.38it/s, avg=0.09992, loss=0.11177]

trial_003 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:40<00:05,  1.40it/s, avg=0.09992, loss=0.11177]

trial_003 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.40it/s, avg=0.09995, loss=0.10304]

trial_003 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:04,  1.42it/s, avg=0.09995, loss=0.10304]

trial_003 train e005:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:04,  1.42it/s, avg=0.09984, loss=0.08418]

trial_003 train e005:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.39it/s, avg=0.09984, loss=0.08418]

trial_003 train e005:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.39it/s, avg=0.09977, loss=0.09008]

trial_003 train e005:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:42<00:03,  1.37it/s, avg=0.09977, loss=0.09008]

trial_003 train e005:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.37it/s, avg=0.09976, loss=0.09912]

trial_003 train e005:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.38it/s, avg=0.09976, loss=0.09912]

trial_003 train e005:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.38it/s, avg=0.09980, loss=0.10529]

trial_003 train e005:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.37it/s, avg=0.09980, loss=0.10529]

trial_003 train e005:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.37it/s, avg=0.09982, loss=0.10202]

trial_003 train e005:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.38it/s, avg=0.09982, loss=0.10202]

trial_003 train e005:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.38it/s, avg=0.09985, loss=0.10550]

trial_003 train e005:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.44it/s, avg=0.09985, loss=0.10550]

trial_003 train e005:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.44it/s, avg=0.09985, loss=0.09974]

trial_003 train e005: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:45<00:00,  1.72it/s, avg=0.09985, loss=0.09974]

trial_003 val e005:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e005:   2%|██▌                                                                                                                          | 1/50 [00:00<00:19,  2.51it/s]

trial_003 val e005:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.44it/s]

trial_003 val e005:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.43it/s]

trial_003 val e005:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.39it/s]

trial_003 val e005:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:19,  2.33it/s]

trial_003 val e005:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.34it/s]

trial_003 val e005:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:18,  2.36it/s]

trial_003 val e005:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.39it/s]

trial_003 val e005:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:17,  2.40it/s]

trial_003 val e005:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.41it/s]

trial_003 val e005:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.42it/s]

trial_003 val e005:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.43it/s]

trial_003 val e005:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.44it/s]

trial_003 val e005:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.44it/s]

trial_003 val e005:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.44it/s]

trial_003 val e005:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.41it/s]

trial_003 val e005:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:14,  2.34it/s]

trial_003 val e005:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.35it/s]

trial_003 val e005:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:13,  2.33it/s]

trial_003 val e005:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.32it/s]

trial_003 val e005:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.34it/s]

trial_003 val e005:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.37it/s]

trial_003 val e005:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.38it/s]

trial_003 val e005:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:10<00:10,  2.39it/s]

trial_003 val e005:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.39it/s]

trial_003 val e005:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.38it/s]

trial_003 val e005:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.40it/s]

trial_003 val e005:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.42it/s]

trial_003 val e005:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:12<00:08,  2.42it/s]

trial_003 val e005:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.37it/s]

trial_003 val e005:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.38it/s]

trial_003 val e005:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.39it/s]

trial_003 val e005:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.41it/s]

trial_003 val e005:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.43it/s]

trial_003 val e005:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.43it/s]

trial_003 val e005:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:15<00:05,  2.40it/s]

trial_003 val e005:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.38it/s]

trial_003 val e005:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.41it/s]

trial_003 val e005:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.43it/s]

trial_003 val e005:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.43it/s]

trial_003 val e005:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:17<00:03,  2.44it/s]

trial_003 val e005:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.45it/s]

trial_003 val e005:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.44it/s]

trial_003 val e005:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.41it/s]

trial_003 val e005:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.40it/s]

trial_003 val e005:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.41it/s]

trial_003 val e005:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.43it/s]

trial_003 val e005:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.44it/s]

trial_003 val e005:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.45it/s]

trial_003 val e005: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.47it/s]

[2026-05-28 21:15:29] [trial_003] epoch=005 | train_loss=0.099854 | val_MAE=0.099830 | val_S=0.900170 | best_S=0.900170 @epoch=5 | patience=0/5

[trial_003] epochs:   5%|██████                                                                                                                   | 5/100 [10:19<3:16:40, 124.22s/it]

trial_003 train e006:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e006:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09151, loss=0.09151]

trial_003 train e006:   1%|▋                                                                                              | 1/149 [00:00<01:50,  1.35it/s, avg=0.09151, loss=0.09151]

trial_003 train e006:   1%|▋                                                                                              | 1/149 [00:01<01:50,  1.35it/s, avg=0.09083, loss=0.09014]

trial_003 train e006:   1%|█▎                                                                                             | 2/149 [00:01<01:42,  1.43it/s, avg=0.09083, loss=0.09014]

trial_003 train e006:   1%|█▎                                                                                             | 2/149 [00:02<01:42,  1.43it/s, avg=0.09361, loss=0.09918]

trial_003 train e006:   2%|█▉                                                                                             | 3/149 [00:02<01:41,  1.44it/s, avg=0.09361, loss=0.09918]

trial_003 train e006:   2%|█▉                                                                                             | 3/149 [00:02<01:41,  1.44it/s, avg=0.09493, loss=0.09891]

trial_003 train e006:   3%|██▌                                                                                            | 4/149 [00:02<01:41,  1.42it/s, avg=0.09493, loss=0.09891]

trial_003 train e006:   3%|██▌                                                                                            | 4/149 [00:03<01:41,  1.42it/s, avg=0.09570, loss=0.09877]

trial_003 train e006:   3%|███▏                                                                                           | 5/149 [00:03<01:41,  1.42it/s, avg=0.09570, loss=0.09877]

trial_003 train e006:   3%|███▏                                                                                           | 5/149 [00:04<01:41,  1.42it/s, avg=0.09483, loss=0.09045]

trial_003 train e006:   4%|███▊                                                                                           | 6/149 [00:04<01:41,  1.41it/s, avg=0.09483, loss=0.09045]

trial_003 train e006:   4%|███▊                                                                                           | 6/149 [00:04<01:41,  1.41it/s, avg=0.09505, loss=0.09638]

trial_003 train e006:   5%|████▍                                                                                          | 7/149 [00:04<01:40,  1.41it/s, avg=0.09505, loss=0.09638]

trial_003 train e006:   5%|████▍                                                                                          | 7/149 [00:05<01:40,  1.41it/s, avg=0.09539, loss=0.09782]

trial_003 train e006:   5%|█████                                                                                          | 8/149 [00:05<01:39,  1.41it/s, avg=0.09539, loss=0.09782]

trial_003 train e006:   5%|█████                                                                                          | 8/149 [00:06<01:39,  1.41it/s, avg=0.09562, loss=0.09744]

trial_003 train e006:   6%|█████▋                                                                                         | 9/149 [00:06<01:39,  1.40it/s, avg=0.09562, loss=0.09744]

trial_003 train e006:   6%|█████▋                                                                                         | 9/149 [00:07<01:39,  1.40it/s, avg=0.09625, loss=0.10192]

trial_003 train e006:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.09625, loss=0.10192]

trial_003 train e006:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.09671, loss=0.10133]

trial_003 train e006:   7%|██████▉                                                                                       | 11/149 [00:07<01:40,  1.37it/s, avg=0.09671, loss=0.10133]

trial_003 train e006:   7%|██████▉                                                                                       | 11/149 [00:08<01:40,  1.37it/s, avg=0.09584, loss=0.08620]

trial_003 train e006:   8%|███████▌                                                                                      | 12/149 [00:08<01:40,  1.37it/s, avg=0.09584, loss=0.08620]

trial_003 train e006:   8%|███████▌                                                                                      | 12/149 [00:09<01:40,  1.37it/s, avg=0.09624, loss=0.10105]

trial_003 train e006:   9%|████████▏                                                                                     | 13/149 [00:09<01:38,  1.38it/s, avg=0.09624, loss=0.10105]

trial_003 train e006:   9%|████████▏                                                                                     | 13/149 [00:10<01:38,  1.38it/s, avg=0.09619, loss=0.09562]

trial_003 train e006:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.09619, loss=0.09562]

trial_003 train e006:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.09676, loss=0.10475]

trial_003 train e006:  10%|█████████▍                                                                                    | 15/149 [00:10<01:35,  1.40it/s, avg=0.09676, loss=0.10475]

trial_003 train e006:  10%|█████████▍                                                                                    | 15/149 [00:11<01:35,  1.40it/s, avg=0.09731, loss=0.10546]

trial_003 train e006:  11%|██████████                                                                                    | 16/149 [00:11<01:33,  1.43it/s, avg=0.09731, loss=0.10546]

trial_003 train e006:  11%|██████████                                                                                    | 16/149 [00:12<01:33,  1.43it/s, avg=0.09624, loss=0.07923]

trial_003 train e006:  11%|██████████▋                                                                                   | 17/149 [00:12<01:32,  1.42it/s, avg=0.09624, loss=0.07923]

trial_003 train e006:  11%|██████████▋                                                                                   | 17/149 [00:12<01:32,  1.42it/s, avg=0.09563, loss=0.08511]

trial_003 train e006:  12%|███████████▎                                                                                  | 18/149 [00:12<01:31,  1.43it/s, avg=0.09563, loss=0.08511]

trial_003 train e006:  12%|███████████▎                                                                                  | 18/149 [00:13<01:31,  1.43it/s, avg=0.09546, loss=0.09252]

trial_003 train e006:  13%|███████████▉                                                                                  | 19/149 [00:13<01:30,  1.43it/s, avg=0.09546, loss=0.09252]

trial_003 train e006:  13%|███████████▉                                                                                  | 19/149 [00:14<01:30,  1.43it/s, avg=0.09537, loss=0.09354]

trial_003 train e006:  13%|████████████▌                                                                                 | 20/149 [00:14<01:29,  1.44it/s, avg=0.09537, loss=0.09354]

trial_003 train e006:  13%|████████████▌                                                                                 | 20/149 [00:14<01:29,  1.44it/s, avg=0.09651, loss=0.11946]

trial_003 train e006:  14%|█████████████▏                                                                                | 21/149 [00:14<01:27,  1.46it/s, avg=0.09651, loss=0.11946]

trial_003 train e006:  14%|█████████████▏                                                                                | 21/149 [00:15<01:27,  1.46it/s, avg=0.09736, loss=0.11512]

trial_003 train e006:  15%|█████████████▉                                                                                | 22/149 [00:15<01:27,  1.45it/s, avg=0.09736, loss=0.11512]

trial_003 train e006:  15%|█████████████▉                                                                                | 22/149 [00:16<01:27,  1.45it/s, avg=0.09761, loss=0.10322]

trial_003 train e006:  15%|██████████████▌                                                                               | 23/149 [00:16<01:28,  1.42it/s, avg=0.09761, loss=0.10322]

trial_003 train e006:  15%|██████████████▌                                                                               | 23/149 [00:16<01:28,  1.42it/s, avg=0.09777, loss=0.10129]

trial_003 train e006:  16%|███████████████▏                                                                              | 24/149 [00:16<01:28,  1.42it/s, avg=0.09777, loss=0.10129]

trial_003 train e006:  16%|███████████████▏                                                                              | 24/149 [00:17<01:28,  1.42it/s, avg=0.09771, loss=0.09635]

trial_003 train e006:  17%|███████████████▊                                                                              | 25/149 [00:17<01:27,  1.41it/s, avg=0.09771, loss=0.09635]

trial_003 train e006:  17%|███████████████▊                                                                              | 25/149 [00:18<01:27,  1.41it/s, avg=0.09733, loss=0.08795]

trial_003 train e006:  17%|████████████████▍                                                                             | 26/149 [00:18<01:27,  1.40it/s, avg=0.09733, loss=0.08795]

trial_003 train e006:  17%|████████████████▍                                                                             | 26/149 [00:19<01:27,  1.40it/s, avg=0.09702, loss=0.08890]

trial_003 train e006:  18%|█████████████████                                                                             | 27/149 [00:19<01:26,  1.41it/s, avg=0.09702, loss=0.08890]

trial_003 train e006:  18%|█████████████████                                                                             | 27/149 [00:19<01:26,  1.41it/s, avg=0.09702, loss=0.09704]

trial_003 train e006:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:25,  1.42it/s, avg=0.09702, loss=0.09704]

trial_003 train e006:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:25,  1.42it/s, avg=0.09757, loss=0.11283]

trial_003 train e006:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:22,  1.46it/s, avg=0.09757, loss=0.11283]

trial_003 train e006:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:22,  1.46it/s, avg=0.09752, loss=0.09601]

trial_003 train e006:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:23,  1.43it/s, avg=0.09752, loss=0.09601]

trial_003 train e006:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:23,  1.43it/s, avg=0.09717, loss=0.08693]

trial_003 train e006:  21%|███████████████████▌                                                                          | 31/149 [00:21<01:23,  1.42it/s, avg=0.09717, loss=0.08693]

trial_003 train e006:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:23,  1.42it/s, avg=0.09690, loss=0.08850]

trial_003 train e006:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:22,  1.41it/s, avg=0.09690, loss=0.08850]

trial_003 train e006:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:22,  1.41it/s, avg=0.09742, loss=0.11390]

trial_003 train e006:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:22,  1.41it/s, avg=0.09742, loss=0.11390]

trial_003 train e006:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:22,  1.41it/s, avg=0.09768, loss=0.10623]

trial_003 train e006:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:23,  1.38it/s, avg=0.09768, loss=0.10623]

trial_003 train e006:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:23,  1.38it/s, avg=0.09741, loss=0.08817]

trial_003 train e006:  23%|██████████████████████                                                                        | 35/149 [00:24<01:23,  1.37it/s, avg=0.09741, loss=0.08817]

trial_003 train e006:  23%|██████████████████████                                                                        | 35/149 [00:25<01:23,  1.37it/s, avg=0.09791, loss=0.11550]

trial_003 train e006:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:21,  1.38it/s, avg=0.09791, loss=0.11550]

trial_003 train e006:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.38it/s, avg=0.09788, loss=0.09669]

trial_003 train e006:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:20,  1.39it/s, avg=0.09788, loss=0.09669]

trial_003 train e006:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:20,  1.39it/s, avg=0.09778, loss=0.09439]

trial_003 train e006:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.37it/s, avg=0.09778, loss=0.09439]

trial_003 train e006:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.37it/s, avg=0.09789, loss=0.10211]

trial_003 train e006:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:17,  1.43it/s, avg=0.09789, loss=0.10211]

trial_003 train e006:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:17,  1.43it/s, avg=0.09785, loss=0.09621]

trial_003 train e006:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:17,  1.40it/s, avg=0.09785, loss=0.09621]

trial_003 train e006:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:17,  1.40it/s, avg=0.09796, loss=0.10208]

trial_003 train e006:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:16,  1.40it/s, avg=0.09796, loss=0.10208]

trial_003 train e006:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:16,  1.40it/s, avg=0.09772, loss=0.08786]

trial_003 train e006:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:15,  1.41it/s, avg=0.09772, loss=0.08786]

trial_003 train e006:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:15,  1.41it/s, avg=0.09774, loss=0.09864]

trial_003 train e006:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:16,  1.39it/s, avg=0.09774, loss=0.09864]

trial_003 train e006:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:16,  1.39it/s, avg=0.09747, loss=0.08585]

trial_003 train e006:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:13,  1.43it/s, avg=0.09747, loss=0.08585]

trial_003 train e006:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:13,  1.43it/s, avg=0.09718, loss=0.08461]

trial_003 train e006:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:13,  1.41it/s, avg=0.09718, loss=0.08461]

trial_003 train e006:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.09730, loss=0.10258]

trial_003 train e006:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:12,  1.42it/s, avg=0.09730, loss=0.10258]

trial_003 train e006:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:12,  1.42it/s, avg=0.09759, loss=0.11110]

trial_003 train e006:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:11,  1.43it/s, avg=0.09759, loss=0.11110]

trial_003 train e006:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:11,  1.43it/s, avg=0.09768, loss=0.10163]

trial_003 train e006:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.41it/s, avg=0.09768, loss=0.10163]

trial_003 train e006:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.41it/s, avg=0.09750, loss=0.08902]

trial_003 train e006:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:12,  1.38it/s, avg=0.09750, loss=0.08902]

trial_003 train e006:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:12,  1.38it/s, avg=0.09753, loss=0.09922]

trial_003 train e006:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:11,  1.39it/s, avg=0.09753, loss=0.09922]

trial_003 train e006:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:11,  1.39it/s, avg=0.09766, loss=0.10395]

trial_003 train e006:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:10,  1.39it/s, avg=0.09766, loss=0.10395]

trial_003 train e006:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:10,  1.39it/s, avg=0.09747, loss=0.08795]

trial_003 train e006:  35%|████████████████████████████████▊                                                             | 52/149 [00:36<01:10,  1.38it/s, avg=0.09747, loss=0.08795]

trial_003 train e006:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:10,  1.38it/s, avg=0.09766, loss=0.10746]

trial_003 train e006:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:10,  1.36it/s, avg=0.09766, loss=0.10746]

trial_003 train e006:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:10,  1.36it/s, avg=0.09782, loss=0.10613]

trial_003 train e006:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:10,  1.36it/s, avg=0.09782, loss=0.10613]

trial_003 train e006:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:10,  1.36it/s, avg=0.09776, loss=0.09484]

trial_003 train e006:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.37it/s, avg=0.09776, loss=0.09484]

trial_003 train e006:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:08,  1.37it/s, avg=0.09763, loss=0.09032]

trial_003 train e006:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:05,  1.42it/s, avg=0.09763, loss=0.09032]

trial_003 train e006:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:05,  1.42it/s, avg=0.09758, loss=0.09470]

trial_003 train e006:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:05,  1.41it/s, avg=0.09758, loss=0.09470]

trial_003 train e006:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.41it/s, avg=0.09755, loss=0.09576]

trial_003 train e006:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:04,  1.40it/s, avg=0.09755, loss=0.09576]

trial_003 train e006:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:04,  1.40it/s, avg=0.09749, loss=0.09415]

trial_003 train e006:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:41<01:03,  1.41it/s, avg=0.09749, loss=0.09415]

trial_003 train e006:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:03,  1.41it/s, avg=0.09754, loss=0.10017]

trial_003 train e006:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:02,  1.42it/s, avg=0.09754, loss=0.10017]

trial_003 train e006:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:02,  1.42it/s, avg=0.09741, loss=0.09011]

trial_003 train e006:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:01,  1.43it/s, avg=0.09741, loss=0.09011]

trial_003 train e006:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:01,  1.43it/s, avg=0.09742, loss=0.09794]

trial_003 train e006:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:00,  1.43it/s, avg=0.09742, loss=0.09794]

trial_003 train e006:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:00,  1.43it/s, avg=0.09749, loss=0.10199]

trial_003 train e006:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<01:00,  1.43it/s, avg=0.09749, loss=0.10199]

trial_003 train e006:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:00,  1.43it/s, avg=0.09770, loss=0.11035]

trial_003 train e006:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<00:59,  1.42it/s, avg=0.09770, loss=0.11035]

trial_003 train e006:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<00:59,  1.42it/s, avg=0.09788, loss=0.10971]

trial_003 train e006:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.42it/s, avg=0.09788, loss=0.10971]

trial_003 train e006:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.42it/s, avg=0.09812, loss=0.11396]

trial_003 train e006:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<00:58,  1.42it/s, avg=0.09812, loss=0.11396]

trial_003 train e006:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.42it/s, avg=0.09806, loss=0.09383]

trial_003 train e006:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:57,  1.43it/s, avg=0.09806, loss=0.09383]

trial_003 train e006:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:57,  1.43it/s, avg=0.09818, loss=0.10588]

trial_003 train e006:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:56,  1.42it/s, avg=0.09818, loss=0.10588]

trial_003 train e006:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:56,  1.42it/s, avg=0.09819, loss=0.09926]

trial_003 train e006:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:48<00:56,  1.41it/s, avg=0.09819, loss=0.09926]

trial_003 train e006:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:56,  1.41it/s, avg=0.09814, loss=0.09439]

trial_003 train e006:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:49<00:56,  1.41it/s, avg=0.09814, loss=0.09439]

trial_003 train e006:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.41it/s, avg=0.09813, loss=0.09785]

trial_003 train e006:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:56,  1.39it/s, avg=0.09813, loss=0.09785]

trial_003 train e006:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:56,  1.39it/s, avg=0.09795, loss=0.08535]

trial_003 train e006:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:54,  1.40it/s, avg=0.09795, loss=0.08535]

trial_003 train e006:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:54,  1.40it/s, avg=0.09812, loss=0.11030]

trial_003 train e006:  49%|██████████████████████████████████████████████                                                | 73/149 [00:51<00:55,  1.38it/s, avg=0.09812, loss=0.11030]

trial_003 train e006:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:55,  1.38it/s, avg=0.09833, loss=0.11303]

trial_003 train e006:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:54,  1.39it/s, avg=0.09833, loss=0.11303]

trial_003 train e006:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:54,  1.39it/s, avg=0.09835, loss=0.10047]

trial_003 train e006:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:53,  1.39it/s, avg=0.09835, loss=0.10047]

trial_003 train e006:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:53,  1.39it/s, avg=0.09834, loss=0.09693]

trial_003 train e006:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:53<00:51,  1.43it/s, avg=0.09834, loss=0.09693]

trial_003 train e006:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:51,  1.43it/s, avg=0.09822, loss=0.08924]

trial_003 train e006:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:50,  1.42it/s, avg=0.09822, loss=0.08924]

trial_003 train e006:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:50,  1.42it/s, avg=0.09815, loss=0.09331]

trial_003 train e006:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:50,  1.40it/s, avg=0.09815, loss=0.09331]

trial_003 train e006:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:50,  1.40it/s, avg=0.09814, loss=0.09671]

trial_003 train e006:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:49,  1.41it/s, avg=0.09814, loss=0.09671]

trial_003 train e006:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:49,  1.41it/s, avg=0.09811, loss=0.09619]

trial_003 train e006:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:56<00:48,  1.43it/s, avg=0.09811, loss=0.09619]

trial_003 train e006:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:48,  1.43it/s, avg=0.09807, loss=0.09509]

trial_003 train e006:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:48,  1.42it/s, avg=0.09807, loss=0.09509]

trial_003 train e006:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:48,  1.42it/s, avg=0.09824, loss=0.11183]

trial_003 train e006:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:47,  1.40it/s, avg=0.09824, loss=0.11183]

trial_003 train e006:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:47,  1.40it/s, avg=0.09798, loss=0.07629]

trial_003 train e006:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:58<00:47,  1.39it/s, avg=0.09798, loss=0.07629]

trial_003 train e006:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:47,  1.39it/s, avg=0.09796, loss=0.09609]

trial_003 train e006:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:59<00:45,  1.42it/s, avg=0.09796, loss=0.09609]

trial_003 train e006:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:45,  1.42it/s, avg=0.09788, loss=0.09182]

trial_003 train e006:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:45,  1.41it/s, avg=0.09788, loss=0.09182]

trial_003 train e006:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:45,  1.41it/s, avg=0.09805, loss=0.11205]

trial_003 train e006:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:44,  1.40it/s, avg=0.09805, loss=0.11205]

trial_003 train e006:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:44,  1.40it/s, avg=0.09809, loss=0.10157]

trial_003 train e006:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:01<00:44,  1.40it/s, avg=0.09809, loss=0.10157]

trial_003 train e006:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.40it/s, avg=0.09830, loss=0.11688]

trial_003 train e006:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:44,  1.36it/s, avg=0.09830, loss=0.11688]

trial_003 train e006:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:44,  1.36it/s, avg=0.09856, loss=0.12115]

trial_003 train e006:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:43,  1.38it/s, avg=0.09856, loss=0.12115]

trial_003 train e006:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.38it/s, avg=0.09841, loss=0.08539]

trial_003 train e006:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.39it/s, avg=0.09841, loss=0.08539]

trial_003 train e006:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.39it/s, avg=0.09839, loss=0.09625]

trial_003 train e006:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:04<00:42,  1.38it/s, avg=0.09839, loss=0.09625]

trial_003 train e006:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.38it/s, avg=0.09833, loss=0.09290]

trial_003 train e006:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:41,  1.37it/s, avg=0.09833, loss=0.09290]

trial_003 train e006:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.37it/s, avg=0.09822, loss=0.08853]

trial_003 train e006:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:39,  1.40it/s, avg=0.09822, loss=0.08853]

trial_003 train e006:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:39,  1.40it/s, avg=0.09825, loss=0.10052]

trial_003 train e006:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:06<00:38,  1.42it/s, avg=0.09825, loss=0.10052]

trial_003 train e006:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:38,  1.42it/s, avg=0.09824, loss=0.09773]

trial_003 train e006:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:38,  1.42it/s, avg=0.09824, loss=0.09773]

trial_003 train e006:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:38,  1.42it/s, avg=0.09810, loss=0.08434]

trial_003 train e006:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:37,  1.40it/s, avg=0.09810, loss=0.08434]

trial_003 train e006:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:37,  1.40it/s, avg=0.09807, loss=0.09502]

trial_003 train e006:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.38it/s, avg=0.09807, loss=0.09502]

trial_003 train e006:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.38it/s, avg=0.09799, loss=0.09085]

trial_003 train e006:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:09<00:36,  1.39it/s, avg=0.09799, loss=0.09085]

trial_003 train e006:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.39it/s, avg=0.09801, loss=0.09951]

trial_003 train e006:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:34,  1.43it/s, avg=0.09801, loss=0.09951]

trial_003 train e006:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:34,  1.43it/s, avg=0.09815, loss=0.11262]

trial_003 train e006:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:34,  1.42it/s, avg=0.09815, loss=0.11262]

trial_003 train e006:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:34,  1.42it/s, avg=0.09815, loss=0.09791]

trial_003 train e006:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:11<00:34,  1.41it/s, avg=0.09815, loss=0.09791]

trial_003 train e006:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.41it/s, avg=0.09811, loss=0.09353]

trial_003 train e006:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:33,  1.42it/s, avg=0.09811, loss=0.09353]

trial_003 train e006:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:33,  1.42it/s, avg=0.09813, loss=0.10080]

trial_003 train e006:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:32,  1.40it/s, avg=0.09813, loss=0.10080]

trial_003 train e006:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:32,  1.40it/s, avg=0.09826, loss=0.11126]

trial_003 train e006:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.39it/s, avg=0.09826, loss=0.11126]

trial_003 train e006:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.39it/s, avg=0.09822, loss=0.09404]

trial_003 train e006:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:14<00:31,  1.40it/s, avg=0.09822, loss=0.09404]

trial_003 train e006:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.40it/s, avg=0.09816, loss=0.09234]

trial_003 train e006:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:30,  1.40it/s, avg=0.09816, loss=0.09234]

trial_003 train e006:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:30,  1.40it/s, avg=0.09800, loss=0.08117]

trial_003 train e006:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:30,  1.39it/s, avg=0.09800, loss=0.08117]

trial_003 train e006:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:30,  1.39it/s, avg=0.09807, loss=0.10541]

trial_003 train e006:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:16<00:29,  1.38it/s, avg=0.09807, loss=0.10541]

trial_003 train e006:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:29,  1.38it/s, avg=0.09808, loss=0.09845]

trial_003 train e006:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:17<00:28,  1.41it/s, avg=0.09808, loss=0.09845]

trial_003 train e006:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:28,  1.41it/s, avg=0.09818, loss=0.10945]

trial_003 train e006:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:27,  1.41it/s, avg=0.09818, loss=0.10945]

trial_003 train e006:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:27,  1.41it/s, avg=0.09807, loss=0.08622]

trial_003 train e006:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.39it/s, avg=0.09807, loss=0.08622]

trial_003 train e006:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.39it/s, avg=0.09809, loss=0.09976]

trial_003 train e006:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:19<00:26,  1.40it/s, avg=0.09809, loss=0.09976]

trial_003 train e006:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.40it/s, avg=0.09807, loss=0.09608]

trial_003 train e006:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:20<00:25,  1.40it/s, avg=0.09807, loss=0.09608]

trial_003 train e006:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.40it/s, avg=0.09796, loss=0.08590]

trial_003 train e006:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.40it/s, avg=0.09796, loss=0.08590]

trial_003 train e006:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.40it/s, avg=0.09804, loss=0.10674]

trial_003 train e006:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:21<00:24,  1.39it/s, avg=0.09804, loss=0.10674]

trial_003 train e006:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:24,  1.39it/s, avg=0.09805, loss=0.09952]

trial_003 train e006:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:22<00:23,  1.40it/s, avg=0.09805, loss=0.09952]

trial_003 train e006:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.40it/s, avg=0.09798, loss=0.08996]

trial_003 train e006:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:23,  1.39it/s, avg=0.09798, loss=0.08996]

trial_003 train e006:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:23,  1.39it/s, avg=0.09784, loss=0.08180]

trial_003 train e006:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:22,  1.40it/s, avg=0.09784, loss=0.08180]

trial_003 train e006:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:22,  1.40it/s, avg=0.09788, loss=0.10146]

trial_003 train e006:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:24<00:21,  1.42it/s, avg=0.09788, loss=0.10146]

trial_003 train e006:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.42it/s, avg=0.09789, loss=0.10001]

trial_003 train e006:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:20,  1.42it/s, avg=0.09789, loss=0.10001]

trial_003 train e006:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.42it/s, avg=0.09785, loss=0.09317]

trial_003 train e006:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:19,  1.42it/s, avg=0.09785, loss=0.09317]

trial_003 train e006:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:19,  1.42it/s, avg=0.09785, loss=0.09687]

trial_003 train e006:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:26<00:19,  1.40it/s, avg=0.09785, loss=0.09687]

trial_003 train e006:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.40it/s, avg=0.09784, loss=0.09717]

trial_003 train e006:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:27<00:18,  1.43it/s, avg=0.09784, loss=0.09717]

trial_003 train e006:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.43it/s, avg=0.09793, loss=0.10889]

trial_003 train e006:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.43it/s, avg=0.09793, loss=0.10889]

trial_003 train e006:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.43it/s, avg=0.09787, loss=0.09046]

trial_003 train e006:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:28<00:16,  1.45it/s, avg=0.09787, loss=0.09046]

trial_003 train e006:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:16,  1.45it/s, avg=0.09796, loss=0.10899]

trial_003 train e006:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:29<00:16,  1.39it/s, avg=0.09796, loss=0.10899]

trial_003 train e006:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.39it/s, avg=0.09791, loss=0.09249]

trial_003 train e006:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.38it/s, avg=0.09791, loss=0.09249]

trial_003 train e006:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.38it/s, avg=0.09793, loss=0.10000]

trial_003 train e006:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.37it/s, avg=0.09793, loss=0.10000]

trial_003 train e006:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.37it/s, avg=0.09794, loss=0.09955]

trial_003 train e006:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:31<00:14,  1.38it/s, avg=0.09794, loss=0.09955]

trial_003 train e006:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.38it/s, avg=0.09792, loss=0.09533]

trial_003 train e006:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:32<00:13,  1.39it/s, avg=0.09792, loss=0.09533]

trial_003 train e006:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.39it/s, avg=0.09787, loss=0.09155]

trial_003 train e006:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:13,  1.38it/s, avg=0.09787, loss=0.09155]

trial_003 train e006:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:13,  1.38it/s, avg=0.09784, loss=0.09351]

trial_003 train e006:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:33<00:12,  1.39it/s, avg=0.09784, loss=0.09351]

trial_003 train e006:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.39it/s, avg=0.09788, loss=0.10236]

trial_003 train e006:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:34<00:11,  1.37it/s, avg=0.09788, loss=0.10236]

trial_003 train e006:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.37it/s, avg=0.09792, loss=0.10333]

trial_003 train e006:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.37it/s, avg=0.09792, loss=0.10333]

trial_003 train e006:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.37it/s, avg=0.09781, loss=0.08388]

trial_003 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.35it/s, avg=0.09781, loss=0.08388]

trial_003 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.35it/s, avg=0.09778, loss=0.09385]

trial_003 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:36<00:09,  1.35it/s, avg=0.09778, loss=0.09385]

trial_003 train e006:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.35it/s, avg=0.09779, loss=0.09866]

trial_003 train e006:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:37<00:08,  1.35it/s, avg=0.09779, loss=0.09866]

trial_003 train e006:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.35it/s, avg=0.09792, loss=0.11535]

trial_003 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:08,  1.35it/s, avg=0.09792, loss=0.11535]

trial_003 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:08,  1.35it/s, avg=0.09793, loss=0.09935]

trial_003 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.36it/s, avg=0.09793, loss=0.09935]

trial_003 train e006:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.36it/s, avg=0.09786, loss=0.08862]

trial_003 train e006:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:39<00:06,  1.37it/s, avg=0.09786, loss=0.08862]

trial_003 train e006:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.37it/s, avg=0.09794, loss=0.10885]

trial_003 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:40<00:05,  1.37it/s, avg=0.09794, loss=0.10885]

trial_003 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.37it/s, avg=0.09792, loss=0.09494]

trial_003 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:05,  1.36it/s, avg=0.09792, loss=0.09494]

trial_003 train e006:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:05,  1.36it/s, avg=0.09800, loss=0.11009]

trial_003 train e006:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.36it/s, avg=0.09800, loss=0.11009]

trial_003 train e006:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.36it/s, avg=0.09799, loss=0.09658]

trial_003 train e006:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:42<00:03,  1.37it/s, avg=0.09799, loss=0.09658]

trial_003 train e006:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.37it/s, avg=0.09794, loss=0.09098]

trial_003 train e006:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.41it/s, avg=0.09794, loss=0.09098]

trial_003 train e006:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.41it/s, avg=0.09803, loss=0.10976]

trial_003 train e006:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.44it/s, avg=0.09803, loss=0.10976]

trial_003 train e006:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.44it/s, avg=0.09801, loss=0.09649]

trial_003 train e006:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:44<00:01,  1.41it/s, avg=0.09801, loss=0.09649]

trial_003 train e006:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.41it/s, avg=0.09800, loss=0.09614]

trial_003 train e006:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.38it/s, avg=0.09800, loss=0.09614]

trial_003 train e006:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.38it/s, avg=0.09802, loss=0.10633]

trial_003 train e006: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:45<00:00,  1.67it/s, avg=0.09802, loss=0.10633]

trial_003 val e006:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e006:   2%|██▌                                                                                                                          | 1/50 [00:00<00:19,  2.46it/s]

trial_003 val e006:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.45it/s]

trial_003 val e006:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.46it/s]

trial_003 val e006:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.46it/s]

trial_003 val e006:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.46it/s]

trial_003 val e006:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.46it/s]

trial_003 val e006:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.46it/s]

trial_003 val e006:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.46it/s]

trial_003 val e006:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.45it/s]

trial_003 val e006:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.39it/s]

trial_003 val e006:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.39it/s]

trial_003 val e006:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:16,  2.37it/s]

trial_003 val e006:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.36it/s]

trial_003 val e006:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:15,  2.38it/s]

trial_003 val e006:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.40it/s]

trial_003 val e006:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.42it/s]

trial_003 val e006:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.43it/s]

trial_003 val e006:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.43it/s]

trial_003 val e006:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.44it/s]

trial_003 val e006:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.45it/s]

trial_003 val e006:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.45it/s]

trial_003 val e006:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.46it/s]

trial_003 val e006:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.44it/s]

trial_003 val e006:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.41it/s]

trial_003 val e006:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.40it/s]

trial_003 val e006:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:10,  2.40it/s]

trial_003 val e006:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.42it/s]

trial_003 val e006:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.44it/s]

trial_003 val e006:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.46it/s]

trial_003 val e006:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.46it/s]

trial_003 val e006:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.47it/s]

trial_003 val e006:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.47it/s]

trial_003 val e006:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.48it/s]

trial_003 val e006:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.48it/s]

trial_003 val e006:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.47it/s]

trial_003 val e006:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.47it/s]

trial_003 val e006:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.44it/s]

trial_003 val e006:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.42it/s]

trial_003 val e006:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.40it/s]

trial_003 val e006:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.42it/s]

trial_003 val e006:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.44it/s]

trial_003 val e006:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.45it/s]

trial_003 val e006:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.46it/s]

trial_003 val e006:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.46it/s]

trial_003 val e006:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.47it/s]

trial_003 val e006:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.48it/s]

trial_003 val e006:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.47it/s]

trial_003 val e006:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.47it/s]

trial_003 val e006:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.45it/s]

trial_003 val e006: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.45it/s]

[2026-05-28 21:17:35] [trial_003] epoch=006 | train_loss=0.098025 | val_MAE=0.099889 | val_S=0.900111 | best_S=0.900170 @epoch=5 | patience=1/5

[trial_003] epochs:   6%|███████▎                                                                                                                 | 6/100 [12:25<3:15:52, 125.03s/it]

trial_003 train e007:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e007:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09925, loss=0.09925]

trial_003 train e007:   1%|▋                                                                                              | 1/149 [00:00<01:46,  1.38it/s, avg=0.09925, loss=0.09925]

trial_003 train e007:   1%|▋                                                                                              | 1/149 [00:01<01:46,  1.38it/s, avg=0.10152, loss=0.10380]

trial_003 train e007:   1%|█▎                                                                                             | 2/149 [00:01<01:42,  1.43it/s, avg=0.10152, loss=0.10380]

trial_003 train e007:   1%|█▎                                                                                             | 2/149 [00:02<01:42,  1.43it/s, avg=0.10263, loss=0.10485]

trial_003 train e007:   2%|█▉                                                                                             | 3/149 [00:02<01:42,  1.43it/s, avg=0.10263, loss=0.10485]

trial_003 train e007:   2%|█▉                                                                                             | 3/149 [00:02<01:42,  1.43it/s, avg=0.09985, loss=0.09151]

trial_003 train e007:   3%|██▌                                                                                            | 4/149 [00:02<01:41,  1.42it/s, avg=0.09985, loss=0.09151]

trial_003 train e007:   3%|██▌                                                                                            | 4/149 [00:03<01:41,  1.42it/s, avg=0.09932, loss=0.09717]

trial_003 train e007:   3%|███▏                                                                                           | 5/149 [00:03<01:43,  1.40it/s, avg=0.09932, loss=0.09717]

trial_003 train e007:   3%|███▏                                                                                           | 5/149 [00:04<01:43,  1.40it/s, avg=0.10150, loss=0.11244]

trial_003 train e007:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.39it/s, avg=0.10150, loss=0.11244]

trial_003 train e007:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.39it/s, avg=0.10101, loss=0.09806]

trial_003 train e007:   5%|████▍                                                                                          | 7/149 [00:04<01:41,  1.40it/s, avg=0.10101, loss=0.09806]

trial_003 train e007:   5%|████▍                                                                                          | 7/149 [00:05<01:41,  1.40it/s, avg=0.10222, loss=0.11071]

trial_003 train e007:   5%|█████                                                                                          | 8/149 [00:05<01:42,  1.38it/s, avg=0.10222, loss=0.11071]

trial_003 train e007:   5%|█████                                                                                          | 8/149 [00:06<01:42,  1.38it/s, avg=0.10110, loss=0.09213]

trial_003 train e007:   6%|█████▋                                                                                         | 9/149 [00:06<01:42,  1.37it/s, avg=0.10110, loss=0.09213]

trial_003 train e007:   6%|█████▋                                                                                         | 9/149 [00:07<01:42,  1.37it/s, avg=0.10120, loss=0.10204]

trial_003 train e007:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.10120, loss=0.10204]

trial_003 train e007:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.09959, loss=0.08356]

trial_003 train e007:   7%|██████▉                                                                                       | 11/149 [00:07<01:38,  1.41it/s, avg=0.09959, loss=0.08356]

trial_003 train e007:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.41it/s, avg=0.09884, loss=0.09055]

trial_003 train e007:   8%|███████▌                                                                                      | 12/149 [00:08<01:37,  1.41it/s, avg=0.09884, loss=0.09055]

trial_003 train e007:   8%|███████▌                                                                                      | 12/149 [00:09<01:37,  1.41it/s, avg=0.09892, loss=0.09985]

trial_003 train e007:   9%|████████▏                                                                                     | 13/149 [00:09<01:37,  1.39it/s, avg=0.09892, loss=0.09985]

trial_003 train e007:   9%|████████▏                                                                                     | 13/149 [00:10<01:37,  1.39it/s, avg=0.09887, loss=0.09822]

trial_003 train e007:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.40it/s, avg=0.09887, loss=0.09822]

trial_003 train e007:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.40it/s, avg=0.09771, loss=0.08149]

trial_003 train e007:  10%|█████████▍                                                                                    | 15/149 [00:10<01:37,  1.37it/s, avg=0.09771, loss=0.08149]

trial_003 train e007:  10%|█████████▍                                                                                    | 15/149 [00:11<01:37,  1.37it/s, avg=0.09752, loss=0.09476]

trial_003 train e007:  11%|██████████                                                                                    | 16/149 [00:11<01:36,  1.38it/s, avg=0.09752, loss=0.09476]

trial_003 train e007:  11%|██████████                                                                                    | 16/149 [00:12<01:36,  1.38it/s, avg=0.09733, loss=0.09421]

trial_003 train e007:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.09733, loss=0.09421]

trial_003 train e007:  11%|██████████▋                                                                                   | 17/149 [00:12<01:36,  1.37it/s, avg=0.09719, loss=0.09480]

trial_003 train e007:  12%|███████████▎                                                                                  | 18/149 [00:12<01:35,  1.38it/s, avg=0.09719, loss=0.09480]

trial_003 train e007:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.38it/s, avg=0.09742, loss=0.10158]

trial_003 train e007:  13%|███████████▉                                                                                  | 19/149 [00:13<01:34,  1.37it/s, avg=0.09742, loss=0.10158]

trial_003 train e007:  13%|███████████▉                                                                                  | 19/149 [00:14<01:34,  1.37it/s, avg=0.09776, loss=0.10431]

trial_003 train e007:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.38it/s, avg=0.09776, loss=0.10431]

trial_003 train e007:  13%|████████████▌                                                                                 | 20/149 [00:15<01:33,  1.38it/s, avg=0.09765, loss=0.09530]

trial_003 train e007:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.39it/s, avg=0.09765, loss=0.09530]

trial_003 train e007:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.39it/s, avg=0.09752, loss=0.09483]

trial_003 train e007:  15%|█████████████▉                                                                                | 22/149 [00:15<01:30,  1.40it/s, avg=0.09752, loss=0.09483]

trial_003 train e007:  15%|█████████████▉                                                                                | 22/149 [00:16<01:30,  1.40it/s, avg=0.09767, loss=0.10101]

trial_003 train e007:  15%|██████████████▌                                                                               | 23/149 [00:16<01:31,  1.37it/s, avg=0.09767, loss=0.10101]

trial_003 train e007:  15%|██████████████▌                                                                               | 23/149 [00:17<01:31,  1.37it/s, avg=0.09737, loss=0.09057]

trial_003 train e007:  16%|███████████████▏                                                                              | 24/149 [00:17<01:30,  1.38it/s, avg=0.09737, loss=0.09057]

trial_003 train e007:  16%|███████████████▏                                                                              | 24/149 [00:17<01:30,  1.38it/s, avg=0.09791, loss=0.11085]

trial_003 train e007:  17%|███████████████▊                                                                              | 25/149 [00:17<01:28,  1.40it/s, avg=0.09791, loss=0.11085]

trial_003 train e007:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.40it/s, avg=0.09811, loss=0.10306]

trial_003 train e007:  17%|████████████████▍                                                                             | 26/149 [00:18<01:25,  1.43it/s, avg=0.09811, loss=0.10306]

trial_003 train e007:  17%|████████████████▍                                                                             | 26/149 [00:19<01:25,  1.43it/s, avg=0.09772, loss=0.08752]

trial_003 train e007:  18%|█████████████████                                                                             | 27/149 [00:19<01:25,  1.43it/s, avg=0.09772, loss=0.08752]

trial_003 train e007:  18%|█████████████████                                                                             | 27/149 [00:20<01:25,  1.43it/s, avg=0.09773, loss=0.09812]

trial_003 train e007:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:25,  1.42it/s, avg=0.09773, loss=0.09812]

trial_003 train e007:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:25,  1.42it/s, avg=0.09811, loss=0.10878]

trial_003 train e007:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:23,  1.43it/s, avg=0.09811, loss=0.10878]

trial_003 train e007:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:23,  1.43it/s, avg=0.09829, loss=0.10339]

trial_003 train e007:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:24,  1.40it/s, avg=0.09829, loss=0.10339]

trial_003 train e007:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:24,  1.40it/s, avg=0.09859, loss=0.10758]

trial_003 train e007:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:25,  1.38it/s, avg=0.09859, loss=0.10758]

trial_003 train e007:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:25,  1.38it/s, avg=0.09840, loss=0.09261]

trial_003 train e007:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:24,  1.39it/s, avg=0.09840, loss=0.09261]

trial_003 train e007:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.39it/s, avg=0.09885, loss=0.11326]

trial_003 train e007:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:24,  1.37it/s, avg=0.09885, loss=0.11326]

trial_003 train e007:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:24,  1.37it/s, avg=0.09918, loss=0.11004]

trial_003 train e007:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:23,  1.37it/s, avg=0.09918, loss=0.11004]

trial_003 train e007:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:23,  1.37it/s, avg=0.09896, loss=0.09130]

trial_003 train e007:  23%|██████████████████████                                                                        | 35/149 [00:25<01:21,  1.39it/s, avg=0.09896, loss=0.09130]

trial_003 train e007:  23%|██████████████████████                                                                        | 35/149 [00:25<01:21,  1.39it/s, avg=0.09883, loss=0.09431]

trial_003 train e007:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:20,  1.41it/s, avg=0.09883, loss=0.09431]

trial_003 train e007:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.41it/s, avg=0.09852, loss=0.08751]

trial_003 train e007:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:18,  1.42it/s, avg=0.09852, loss=0.08751]

trial_003 train e007:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:18,  1.42it/s, avg=0.09818, loss=0.08571]

trial_003 train e007:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:19,  1.40it/s, avg=0.09818, loss=0.08571]

trial_003 train e007:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:19,  1.40it/s, avg=0.09818, loss=0.09809]

trial_003 train e007:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:19,  1.38it/s, avg=0.09818, loss=0.09809]

trial_003 train e007:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:19,  1.38it/s, avg=0.09795, loss=0.08889]

trial_003 train e007:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:19,  1.37it/s, avg=0.09795, loss=0.08889]

trial_003 train e007:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:19,  1.37it/s, avg=0.09794, loss=0.09746]

trial_003 train e007:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:18,  1.38it/s, avg=0.09794, loss=0.09746]

trial_003 train e007:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:18,  1.38it/s, avg=0.09795, loss=0.09844]

trial_003 train e007:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.09795, loss=0.09844]

trial_003 train e007:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.38it/s, avg=0.09794, loss=0.09772]

trial_003 train e007:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:15,  1.40it/s, avg=0.09794, loss=0.09772]

trial_003 train e007:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.40it/s, avg=0.09791, loss=0.09659]

trial_003 train e007:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:14,  1.42it/s, avg=0.09791, loss=0.09659]

trial_003 train e007:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.42it/s, avg=0.09783, loss=0.09394]

trial_003 train e007:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.09783, loss=0.09394]

trial_003 train e007:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.09816, loss=0.11331]

trial_003 train e007:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:12,  1.42it/s, avg=0.09816, loss=0.11331]

trial_003 train e007:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:12,  1.42it/s, avg=0.09796, loss=0.08866]

trial_003 train e007:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.41it/s, avg=0.09796, loss=0.08866]

trial_003 train e007:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:12,  1.41it/s, avg=0.09785, loss=0.09272]

trial_003 train e007:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.41it/s, avg=0.09785, loss=0.09272]

trial_003 train e007:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:11,  1.41it/s, avg=0.09736, loss=0.07404]

trial_003 train e007:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:10,  1.41it/s, avg=0.09736, loss=0.07404]

trial_003 train e007:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:10,  1.41it/s, avg=0.09708, loss=0.08291]

trial_003 train e007:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:08,  1.44it/s, avg=0.09708, loss=0.08291]

trial_003 train e007:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:08,  1.44it/s, avg=0.09715, loss=0.10092]

trial_003 train e007:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:08,  1.42it/s, avg=0.09715, loss=0.10092]

trial_003 train e007:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:08,  1.42it/s, avg=0.09696, loss=0.08745]

trial_003 train e007:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:08,  1.42it/s, avg=0.09696, loss=0.08745]

trial_003 train e007:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:08,  1.42it/s, avg=0.09685, loss=0.09075]

trial_003 train e007:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:06,  1.45it/s, avg=0.09685, loss=0.09075]

trial_003 train e007:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:06,  1.45it/s, avg=0.09688, loss=0.09858]

trial_003 train e007:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:07,  1.41it/s, avg=0.09688, loss=0.09858]

trial_003 train e007:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:07,  1.41it/s, avg=0.09670, loss=0.08716]

trial_003 train e007:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:07,  1.40it/s, avg=0.09670, loss=0.08716]

trial_003 train e007:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:07,  1.40it/s, avg=0.09654, loss=0.08758]

trial_003 train e007:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.41it/s, avg=0.09654, loss=0.08758]

trial_003 train e007:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.41it/s, avg=0.09652, loss=0.09536]

trial_003 train e007:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:05,  1.41it/s, avg=0.09652, loss=0.09536]

trial_003 train e007:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.41it/s, avg=0.09621, loss=0.07885]

trial_003 train e007:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.40it/s, avg=0.09621, loss=0.07885]

trial_003 train e007:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:05,  1.40it/s, avg=0.09627, loss=0.09955]

trial_003 train e007:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:03,  1.41it/s, avg=0.09627, loss=0.09955]

trial_003 train e007:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:03,  1.41it/s, avg=0.09614, loss=0.08867]

trial_003 train e007:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:03,  1.40it/s, avg=0.09614, loss=0.08867]

trial_003 train e007:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:03,  1.40it/s, avg=0.09615, loss=0.09620]

trial_003 train e007:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:02,  1.40it/s, avg=0.09615, loss=0.09620]

trial_003 train e007:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:02,  1.40it/s, avg=0.09620, loss=0.09985]

trial_003 train e007:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:02,  1.40it/s, avg=0.09620, loss=0.09985]

trial_003 train e007:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:02,  1.40it/s, avg=0.09621, loss=0.09652]

trial_003 train e007:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:01,  1.39it/s, avg=0.09621, loss=0.09652]

trial_003 train e007:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:01,  1.39it/s, avg=0.09619, loss=0.09468]

trial_003 train e007:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<01:01,  1.39it/s, avg=0.09619, loss=0.09468]

trial_003 train e007:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.39it/s, avg=0.09613, loss=0.09268]

trial_003 train e007:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<01:00,  1.39it/s, avg=0.09613, loss=0.09268]

trial_003 train e007:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.39it/s, avg=0.09640, loss=0.11400]

trial_003 train e007:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.42it/s, avg=0.09640, loss=0.11400]

trial_003 train e007:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.42it/s, avg=0.09608, loss=0.07462]

trial_003 train e007:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:57,  1.42it/s, avg=0.09608, loss=0.07462]

trial_003 train e007:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:57,  1.42it/s, avg=0.09595, loss=0.08717]

trial_003 train e007:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:58,  1.39it/s, avg=0.09595, loss=0.08717]

trial_003 train e007:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:58,  1.39it/s, avg=0.09581, loss=0.08624]

trial_003 train e007:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:56,  1.41it/s, avg=0.09581, loss=0.08624]

trial_003 train e007:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:56,  1.41it/s, avg=0.09580, loss=0.09528]

trial_003 train e007:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.39it/s, avg=0.09580, loss=0.09528]

trial_003 train e007:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.39it/s, avg=0.09570, loss=0.08914]

trial_003 train e007:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:55,  1.40it/s, avg=0.09570, loss=0.08914]

trial_003 train e007:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:55,  1.40it/s, avg=0.09555, loss=0.08463]

trial_003 train e007:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:55,  1.38it/s, avg=0.09555, loss=0.08463]

trial_003 train e007:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:55,  1.38it/s, avg=0.09553, loss=0.09429]

trial_003 train e007:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:54,  1.40it/s, avg=0.09553, loss=0.09429]

trial_003 train e007:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:54,  1.40it/s, avg=0.09558, loss=0.09879]

trial_003 train e007:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:53,  1.41it/s, avg=0.09558, loss=0.09879]

trial_003 train e007:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.41it/s, avg=0.09570, loss=0.10451]

trial_003 train e007:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:53,  1.38it/s, avg=0.09570, loss=0.10451]

trial_003 train e007:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.38it/s, avg=0.09566, loss=0.09292]

trial_003 train e007:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:53,  1.37it/s, avg=0.09566, loss=0.09292]

trial_003 train e007:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:53,  1.37it/s, avg=0.09570, loss=0.09892]

trial_003 train e007:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:52,  1.38it/s, avg=0.09570, loss=0.09892]

trial_003 train e007:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:52,  1.38it/s, avg=0.09585, loss=0.10706]

trial_003 train e007:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:51,  1.38it/s, avg=0.09585, loss=0.10706]

trial_003 train e007:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.38it/s, avg=0.09582, loss=0.09380]

trial_003 train e007:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.37it/s, avg=0.09582, loss=0.09380]

trial_003 train e007:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:50,  1.37it/s, avg=0.09583, loss=0.09670]

trial_003 train e007:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:50,  1.36it/s, avg=0.09583, loss=0.09670]

trial_003 train e007:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:50,  1.36it/s, avg=0.09598, loss=0.10797]

trial_003 train e007:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:49,  1.37it/s, avg=0.09598, loss=0.10797]

trial_003 train e007:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:49,  1.37it/s, avg=0.09619, loss=0.11273]

trial_003 train e007:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:48,  1.38it/s, avg=0.09619, loss=0.11273]

trial_003 train e007:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:48,  1.38it/s, avg=0.09614, loss=0.09250]

trial_003 train e007:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:47,  1.39it/s, avg=0.09614, loss=0.09250]

trial_003 train e007:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:47,  1.39it/s, avg=0.09596, loss=0.08101]

trial_003 train e007:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:47,  1.37it/s, avg=0.09596, loss=0.08101]

trial_003 train e007:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:47,  1.37it/s, avg=0.09597, loss=0.09643]

trial_003 train e007:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:45,  1.41it/s, avg=0.09597, loss=0.09643]

trial_003 train e007:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:45,  1.41it/s, avg=0.09590, loss=0.09037]

trial_003 train e007:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:44,  1.43it/s, avg=0.09590, loss=0.09037]

trial_003 train e007:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:44,  1.43it/s, avg=0.09589, loss=0.09517]

trial_003 train e007:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:42,  1.45it/s, avg=0.09589, loss=0.09517]

trial_003 train e007:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:42,  1.45it/s, avg=0.09587, loss=0.09339]

trial_003 train e007:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:42,  1.42it/s, avg=0.09587, loss=0.09339]

trial_003 train e007:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:42,  1.42it/s, avg=0.09600, loss=0.10772]

trial_003 train e007:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:42,  1.42it/s, avg=0.09600, loss=0.10772]

trial_003 train e007:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:42,  1.42it/s, avg=0.09595, loss=0.09177]

trial_003 train e007:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.38it/s, avg=0.09595, loss=0.09177]

trial_003 train e007:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:42,  1.38it/s, avg=0.09601, loss=0.10113]

trial_003 train e007:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.36it/s, avg=0.09601, loss=0.10113]

trial_003 train e007:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.36it/s, avg=0.09592, loss=0.08751]

trial_003 train e007:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:42,  1.35it/s, avg=0.09592, loss=0.08751]

trial_003 train e007:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:42,  1.35it/s, avg=0.09586, loss=0.09020]

trial_003 train e007:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:41,  1.35it/s, avg=0.09586, loss=0.09020]

trial_003 train e007:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:41,  1.35it/s, avg=0.09588, loss=0.09786]

trial_003 train e007:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:40,  1.36it/s, avg=0.09588, loss=0.09786]

trial_003 train e007:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:40,  1.36it/s, avg=0.09587, loss=0.09511]

trial_003 train e007:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.38it/s, avg=0.09587, loss=0.09511]

trial_003 train e007:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:39,  1.38it/s, avg=0.09589, loss=0.09777]

trial_003 train e007:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:38,  1.38it/s, avg=0.09589, loss=0.09777]

trial_003 train e007:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.38it/s, avg=0.09595, loss=0.10162]

trial_003 train e007:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.39it/s, avg=0.09595, loss=0.10162]

trial_003 train e007:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:37,  1.39it/s, avg=0.09596, loss=0.09724]

trial_003 train e007:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.38it/s, avg=0.09596, loss=0.09724]

trial_003 train e007:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.38it/s, avg=0.09598, loss=0.09764]

trial_003 train e007:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:34,  1.44it/s, avg=0.09598, loss=0.09764]

trial_003 train e007:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:34,  1.44it/s, avg=0.09593, loss=0.09125]

trial_003 train e007:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:33,  1.45it/s, avg=0.09593, loss=0.09125]

trial_003 train e007:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:33,  1.45it/s, avg=0.09574, loss=0.07687]

trial_003 train e007:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:33,  1.45it/s, avg=0.09574, loss=0.07687]

trial_003 train e007:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:33,  1.45it/s, avg=0.09586, loss=0.10742]

trial_003 train e007:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:32,  1.46it/s, avg=0.09586, loss=0.10742]

trial_003 train e007:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:32,  1.46it/s, avg=0.09605, loss=0.11574]

trial_003 train e007:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:32,  1.44it/s, avg=0.09605, loss=0.11574]

trial_003 train e007:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:32,  1.44it/s, avg=0.09624, loss=0.11560]

trial_003 train e007:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.40it/s, avg=0.09624, loss=0.11560]

trial_003 train e007:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.40it/s, avg=0.09637, loss=0.11066]

trial_003 train e007:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.38it/s, avg=0.09637, loss=0.11066]

trial_003 train e007:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.38it/s, avg=0.09638, loss=0.09677]

trial_003 train e007:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:30,  1.39it/s, avg=0.09638, loss=0.09677]

trial_003 train e007:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:30,  1.39it/s, avg=0.09639, loss=0.09765]

trial_003 train e007:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:30,  1.37it/s, avg=0.09639, loss=0.09765]

trial_003 train e007:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:30,  1.37it/s, avg=0.09634, loss=0.09128]

trial_003 train e007:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:30,  1.37it/s, avg=0.09634, loss=0.09128]

trial_003 train e007:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:30,  1.37it/s, avg=0.09642, loss=0.10497]

trial_003 train e007:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:29,  1.38it/s, avg=0.09642, loss=0.10497]

trial_003 train e007:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:29,  1.38it/s, avg=0.09642, loss=0.09569]

trial_003 train e007:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:28,  1.36it/s, avg=0.09642, loss=0.09569]

trial_003 train e007:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:28,  1.36it/s, avg=0.09636, loss=0.08988]

trial_003 train e007:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.37it/s, avg=0.09636, loss=0.08988]

trial_003 train e007:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.37it/s, avg=0.09637, loss=0.09752]

trial_003 train e007:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.38it/s, avg=0.09637, loss=0.09752]

trial_003 train e007:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.38it/s, avg=0.09637, loss=0.09624]

trial_003 train e007:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:20<00:25,  1.39it/s, avg=0.09637, loss=0.09624]

trial_003 train e007:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.39it/s, avg=0.09627, loss=0.08590]

trial_003 train e007:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.41it/s, avg=0.09627, loss=0.08590]

trial_003 train e007:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:24,  1.41it/s, avg=0.09632, loss=0.10109]

trial_003 train e007:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:24,  1.39it/s, avg=0.09632, loss=0.10109]

trial_003 train e007:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.39it/s, avg=0.09634, loss=0.09870]

trial_003 train e007:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.41it/s, avg=0.09634, loss=0.09870]

trial_003 train e007:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.41it/s, avg=0.09646, loss=0.11081]

trial_003 train e007:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:23,  1.39it/s, avg=0.09646, loss=0.11081]

trial_003 train e007:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:23,  1.39it/s, avg=0.09647, loss=0.09717]

trial_003 train e007:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:22,  1.38it/s, avg=0.09647, loss=0.09717]

trial_003 train e007:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.38it/s, avg=0.09659, loss=0.11181]

trial_003 train e007:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:20,  1.43it/s, avg=0.09659, loss=0.11181]

trial_003 train e007:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:20,  1.43it/s, avg=0.09651, loss=0.08594]

trial_003 train e007:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:20,  1.43it/s, avg=0.09651, loss=0.08594]

trial_003 train e007:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.43it/s, avg=0.09648, loss=0.09384]

trial_003 train e007:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:20,  1.39it/s, avg=0.09648, loss=0.09384]

trial_003 train e007:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:20,  1.39it/s, avg=0.09645, loss=0.09250]

trial_003 train e007:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.38it/s, avg=0.09645, loss=0.09250]

trial_003 train e007:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:19,  1.38it/s, avg=0.09635, loss=0.08450]

trial_003 train e007:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.40it/s, avg=0.09635, loss=0.08450]

trial_003 train e007:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.40it/s, avg=0.09652, loss=0.11636]

trial_003 train e007:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.44it/s, avg=0.09652, loss=0.11636]

trial_003 train e007:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.44it/s, avg=0.09656, loss=0.10187]

trial_003 train e007:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:16,  1.43it/s, avg=0.09656, loss=0.10187]

trial_003 train e007:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:16,  1.43it/s, avg=0.09657, loss=0.09842]

trial_003 train e007:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.42it/s, avg=0.09657, loss=0.09842]

trial_003 train e007:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.42it/s, avg=0.09656, loss=0.09551]

trial_003 train e007:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.43it/s, avg=0.09656, loss=0.09551]

trial_003 train e007:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.43it/s, avg=0.09654, loss=0.09294]

trial_003 train e007:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.39it/s, avg=0.09654, loss=0.09294]

trial_003 train e007:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.39it/s, avg=0.09648, loss=0.08897]

trial_003 train e007:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.39it/s, avg=0.09648, loss=0.08897]

trial_003 train e007:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.39it/s, avg=0.09661, loss=0.11394]

trial_003 train e007:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.39it/s, avg=0.09661, loss=0.11394]

trial_003 train e007:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.39it/s, avg=0.09654, loss=0.08660]

trial_003 train e007:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:12,  1.39it/s, avg=0.09654, loss=0.08660]

trial_003 train e007:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:12,  1.39it/s, avg=0.09657, loss=0.10150]

trial_003 train e007:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.39it/s, avg=0.09657, loss=0.10150]

trial_003 train e007:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.39it/s, avg=0.09663, loss=0.10413]

trial_003 train e007:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.39it/s, avg=0.09663, loss=0.10413]

trial_003 train e007:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.39it/s, avg=0.09666, loss=0.10010]

trial_003 train e007:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.38it/s, avg=0.09666, loss=0.10010]

trial_003 train e007:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.38it/s, avg=0.09655, loss=0.08199]

trial_003 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.37it/s, avg=0.09655, loss=0.08199]

trial_003 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.37it/s, avg=0.09650, loss=0.08999]

trial_003 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.38it/s, avg=0.09650, loss=0.08999]

trial_003 train e007:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.38it/s, avg=0.09655, loss=0.10397]

trial_003 train e007:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.39it/s, avg=0.09655, loss=0.10397]

trial_003 train e007:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.39it/s, avg=0.09658, loss=0.10022]

trial_003 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:07,  1.41it/s, avg=0.09658, loss=0.10022]

trial_003 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:07,  1.41it/s, avg=0.09653, loss=0.09026]

trial_003 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.43it/s, avg=0.09653, loss=0.09026]

trial_003 train e007:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.43it/s, avg=0.09654, loss=0.09779]

trial_003 train e007:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.40it/s, avg=0.09654, loss=0.09779]

trial_003 train e007:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.40it/s, avg=0.09657, loss=0.09956]

trial_003 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:40<00:05,  1.39it/s, avg=0.09657, loss=0.09956]

trial_003 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.39it/s, avg=0.09653, loss=0.09226]

trial_003 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:05,  1.39it/s, avg=0.09653, loss=0.09226]

trial_003 train e007:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:05,  1.39it/s, avg=0.09651, loss=0.09293]

trial_003 train e007:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.37it/s, avg=0.09651, loss=0.09293]

trial_003 train e007:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.37it/s, avg=0.09644, loss=0.08594]

trial_003 train e007:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.37it/s, avg=0.09644, loss=0.08594]

trial_003 train e007:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.37it/s, avg=0.09644, loss=0.09705]

trial_003 train e007:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.34it/s, avg=0.09644, loss=0.09705]

trial_003 train e007:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.34it/s, avg=0.09641, loss=0.09164]

trial_003 train e007:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.36it/s, avg=0.09641, loss=0.09164]

trial_003 train e007:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.36it/s, avg=0.09641, loss=0.09704]

trial_003 train e007:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.35it/s, avg=0.09641, loss=0.09704]

trial_003 train e007:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:46<00:01,  1.35it/s, avg=0.09645, loss=0.10234]

trial_003 train e007:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.38it/s, avg=0.09645, loss=0.10234]

trial_003 train e007:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.38it/s, avg=0.09649, loss=0.11031]

trial_003 train e007: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:46<00:00,  1.70it/s, avg=0.09649, loss=0.11031]

trial_003 val e007:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e007:   2%|██▌                                                                                                                          | 1/50 [00:00<00:18,  2.64it/s]

trial_003 val e007:   4%|█████                                                                                                                        | 2/50 [00:00<00:18,  2.55it/s]

trial_003 val e007:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:18,  2.52it/s]

trial_003 val e007:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.47it/s]

trial_003 val e007:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.45it/s]

trial_003 val e007:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.47it/s]

trial_003 val e007:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.47it/s]

trial_003 val e007:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:16,  2.47it/s]

trial_003 val e007:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.48it/s]

trial_003 val e007:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.48it/s]

trial_003 val e007:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.47it/s]

trial_003 val e007:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.47it/s]

trial_003 val e007:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:14,  2.48it/s]

trial_003 val e007:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.48it/s]

trial_003 val e007:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.48it/s]

trial_003 val e007:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.48it/s]

trial_003 val e007:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.49it/s]

trial_003 val e007:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:12,  2.47it/s]

trial_003 val e007:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.43it/s]

trial_003 val e007:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.42it/s]

trial_003 val e007:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.44it/s]

trial_003 val e007:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:08<00:11,  2.44it/s]

trial_003 val e007:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.45it/s]

trial_003 val e007:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.43it/s]

trial_003 val e007:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.45it/s]

trial_003 val e007:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.46it/s]

trial_003 val e007:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:10<00:09,  2.47it/s]

trial_003 val e007:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.46it/s]

trial_003 val e007:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.45it/s]

trial_003 val e007:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.46it/s]

trial_003 val e007:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.44it/s]

trial_003 val e007:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.43it/s]

trial_003 val e007:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.42it/s]

trial_003 val e007:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.44it/s]

trial_003 val e007:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.45it/s]

trial_003 val e007:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.44it/s]

trial_003 val e007:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.46it/s]

trial_003 val e007:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.46it/s]

trial_003 val e007:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:15<00:04,  2.44it/s]

trial_003 val e007:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.46it/s]

trial_003 val e007:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.47it/s]

trial_003 val e007:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.47it/s]

trial_003 val e007:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.46it/s]

trial_003 val e007:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:17<00:02,  2.44it/s]

trial_003 val e007:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.39it/s]

trial_003 val e007:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.39it/s]

trial_003 val e007:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.39it/s]

trial_003 val e007:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.40it/s]

trial_003 val e007:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:19<00:00,  2.43it/s]

trial_003 val e007: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.46it/s]

[2026-05-28 21:19:42] [trial_003] epoch=007 | train_loss=0.096489 | val_MAE=0.101262 | val_S=0.898738 | best_S=0.900170 @epoch=5 | patience=2/5

[trial_003] epochs:   7%|████████▍                                                                                                                | 7/100 [14:32<3:14:43, 125.63s/it]

trial_003 train e008:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e008:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.09785, loss=0.09785]

trial_003 train e008:   1%|▋                                                                                              | 1/149 [00:00<01:38,  1.51it/s, avg=0.09785, loss=0.09785]

trial_003 train e008:   1%|▋                                                                                              | 1/149 [00:01<01:38,  1.51it/s, avg=0.09801, loss=0.09818]

trial_003 train e008:   1%|█▎                                                                                             | 2/149 [00:01<01:41,  1.45it/s, avg=0.09801, loss=0.09818]

trial_003 train e008:   1%|█▎                                                                                             | 2/149 [00:02<01:41,  1.45it/s, avg=0.09579, loss=0.09134]

trial_003 train e008:   2%|█▉                                                                                             | 3/149 [00:02<01:43,  1.41it/s, avg=0.09579, loss=0.09134]

trial_003 train e008:   2%|█▉                                                                                             | 3/149 [00:02<01:43,  1.41it/s, avg=0.09355, loss=0.08685]

trial_003 train e008:   3%|██▌                                                                                            | 4/149 [00:02<01:41,  1.42it/s, avg=0.09355, loss=0.08685]

trial_003 train e008:   3%|██▌                                                                                            | 4/149 [00:03<01:41,  1.42it/s, avg=0.09479, loss=0.09971]

trial_003 train e008:   3%|███▏                                                                                           | 5/149 [00:03<01:43,  1.40it/s, avg=0.09479, loss=0.09971]

trial_003 train e008:   3%|███▏                                                                                           | 5/149 [00:04<01:43,  1.40it/s, avg=0.09373, loss=0.08844]

trial_003 train e008:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.39it/s, avg=0.09373, loss=0.08844]

trial_003 train e008:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.39it/s, avg=0.09479, loss=0.10118]

trial_003 train e008:   5%|████▍                                                                                          | 7/149 [00:04<01:42,  1.39it/s, avg=0.09479, loss=0.10118]

trial_003 train e008:   5%|████▍                                                                                          | 7/149 [00:05<01:42,  1.39it/s, avg=0.09404, loss=0.08873]

trial_003 train e008:   5%|█████                                                                                          | 8/149 [00:05<01:39,  1.41it/s, avg=0.09404, loss=0.08873]

trial_003 train e008:   5%|█████                                                                                          | 8/149 [00:06<01:39,  1.41it/s, avg=0.09560, loss=0.10811]

trial_003 train e008:   6%|█████▋                                                                                         | 9/149 [00:06<01:41,  1.38it/s, avg=0.09560, loss=0.10811]

trial_003 train e008:   6%|█████▋                                                                                         | 9/149 [00:07<01:41,  1.38it/s, avg=0.09529, loss=0.09250]

trial_003 train e008:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.09529, loss=0.09250]

trial_003 train e008:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.09484, loss=0.09038]

trial_003 train e008:   7%|██████▉                                                                                       | 11/149 [00:07<01:38,  1.40it/s, avg=0.09484, loss=0.09038]

trial_003 train e008:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.40it/s, avg=0.09491, loss=0.09559]

trial_003 train e008:   8%|███████▌                                                                                      | 12/149 [00:08<01:39,  1.38it/s, avg=0.09491, loss=0.09559]

trial_003 train e008:   8%|███████▌                                                                                      | 12/149 [00:09<01:39,  1.38it/s, avg=0.09522, loss=0.09901]

trial_003 train e008:   9%|████████▏                                                                                     | 13/149 [00:09<01:36,  1.41it/s, avg=0.09522, loss=0.09901]

trial_003 train e008:   9%|████████▏                                                                                     | 13/149 [00:09<01:36,  1.41it/s, avg=0.09606, loss=0.10692]

trial_003 train e008:   9%|████████▊                                                                                     | 14/149 [00:09<01:34,  1.43it/s, avg=0.09606, loss=0.10692]

trial_003 train e008:   9%|████████▊                                                                                     | 14/149 [00:10<01:34,  1.43it/s, avg=0.09632, loss=0.10005]

trial_003 train e008:  10%|█████████▍                                                                                    | 15/149 [00:10<01:35,  1.40it/s, avg=0.09632, loss=0.10005]

trial_003 train e008:  10%|█████████▍                                                                                    | 15/149 [00:11<01:35,  1.40it/s, avg=0.09655, loss=0.09998]

trial_003 train e008:  11%|██████████                                                                                    | 16/149 [00:11<01:35,  1.40it/s, avg=0.09655, loss=0.09998]

trial_003 train e008:  11%|██████████                                                                                    | 16/149 [00:12<01:35,  1.40it/s, avg=0.09740, loss=0.11096]

trial_003 train e008:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.38it/s, avg=0.09740, loss=0.11096]

trial_003 train e008:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.38it/s, avg=0.09781, loss=0.10488]

trial_003 train e008:  12%|███████████▎                                                                                  | 18/149 [00:12<01:33,  1.40it/s, avg=0.09781, loss=0.10488]

trial_003 train e008:  12%|███████████▎                                                                                  | 18/149 [00:13<01:33,  1.40it/s, avg=0.09828, loss=0.10667]

trial_003 train e008:  13%|███████████▉                                                                                  | 19/149 [00:13<01:31,  1.43it/s, avg=0.09828, loss=0.10667]

trial_003 train e008:  13%|███████████▉                                                                                  | 19/149 [00:14<01:31,  1.43it/s, avg=0.09850, loss=0.10265]

trial_003 train e008:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.39it/s, avg=0.09850, loss=0.10265]

trial_003 train e008:  13%|████████████▌                                                                                 | 20/149 [00:14<01:33,  1.39it/s, avg=0.09886, loss=0.10607]

trial_003 train e008:  14%|█████████████▏                                                                                | 21/149 [00:14<01:31,  1.39it/s, avg=0.09886, loss=0.10607]

trial_003 train e008:  14%|█████████████▏                                                                                | 21/149 [00:15<01:31,  1.39it/s, avg=0.09802, loss=0.08046]

trial_003 train e008:  15%|█████████████▉                                                                                | 22/149 [00:15<01:31,  1.39it/s, avg=0.09802, loss=0.08046]

trial_003 train e008:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.39it/s, avg=0.09805, loss=0.09856]

trial_003 train e008:  15%|██████████████▌                                                                               | 23/149 [00:16<01:29,  1.41it/s, avg=0.09805, loss=0.09856]

trial_003 train e008:  15%|██████████████▌                                                                               | 23/149 [00:17<01:29,  1.41it/s, avg=0.09777, loss=0.09131]

trial_003 train e008:  16%|███████████████▏                                                                              | 24/149 [00:17<01:28,  1.41it/s, avg=0.09777, loss=0.09131]

trial_003 train e008:  16%|███████████████▏                                                                              | 24/149 [00:17<01:28,  1.41it/s, avg=0.09730, loss=0.08614]

trial_003 train e008:  17%|███████████████▊                                                                              | 25/149 [00:17<01:28,  1.40it/s, avg=0.09730, loss=0.08614]

trial_003 train e008:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.40it/s, avg=0.09802, loss=0.11605]

trial_003 train e008:  17%|████████████████▍                                                                             | 26/149 [00:18<01:26,  1.41it/s, avg=0.09802, loss=0.11605]

trial_003 train e008:  17%|████████████████▍                                                                             | 26/149 [00:19<01:26,  1.41it/s, avg=0.09765, loss=0.08787]

trial_003 train e008:  18%|█████████████████                                                                             | 27/149 [00:19<01:24,  1.44it/s, avg=0.09765, loss=0.08787]

trial_003 train e008:  18%|█████████████████                                                                             | 27/149 [00:19<01:24,  1.44it/s, avg=0.09729, loss=0.08776]

trial_003 train e008:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:26,  1.40it/s, avg=0.09729, loss=0.08776]

trial_003 train e008:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:26,  1.40it/s, avg=0.09710, loss=0.09180]

trial_003 train e008:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:26,  1.38it/s, avg=0.09710, loss=0.09180]

trial_003 train e008:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.09679, loss=0.08772]

trial_003 train e008:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:26,  1.37it/s, avg=0.09679, loss=0.08772]

trial_003 train e008:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:26,  1.37it/s, avg=0.09661, loss=0.09105]

trial_003 train e008:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:24,  1.39it/s, avg=0.09661, loss=0.09105]

trial_003 train e008:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:24,  1.39it/s, avg=0.09691, loss=0.10620]

trial_003 train e008:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:22,  1.42it/s, avg=0.09691, loss=0.10620]

trial_003 train e008:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:22,  1.42it/s, avg=0.09712, loss=0.10405]

trial_003 train e008:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:21,  1.43it/s, avg=0.09712, loss=0.10405]

trial_003 train e008:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:21,  1.43it/s, avg=0.09662, loss=0.08014]

trial_003 train e008:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:20,  1.44it/s, avg=0.09662, loss=0.08014]

trial_003 train e008:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:20,  1.44it/s, avg=0.09622, loss=0.08258]

trial_003 train e008:  23%|██████████████████████                                                                        | 35/149 [00:24<01:21,  1.40it/s, avg=0.09622, loss=0.08258]

trial_003 train e008:  23%|██████████████████████                                                                        | 35/149 [00:25<01:21,  1.40it/s, avg=0.09587, loss=0.08348]

trial_003 train e008:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:20,  1.40it/s, avg=0.09587, loss=0.08348]

trial_003 train e008:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:20,  1.40it/s, avg=0.09565, loss=0.08779]

trial_003 train e008:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:20,  1.40it/s, avg=0.09565, loss=0.08779]

trial_003 train e008:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:20,  1.40it/s, avg=0.09547, loss=0.08885]

trial_003 train e008:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.39it/s, avg=0.09547, loss=0.08885]

trial_003 train e008:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:20,  1.39it/s, avg=0.09593, loss=0.11338]

trial_003 train e008:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:19,  1.39it/s, avg=0.09593, loss=0.11338]

trial_003 train e008:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:19,  1.39it/s, avg=0.09576, loss=0.08903]

trial_003 train e008:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:18,  1.39it/s, avg=0.09576, loss=0.08903]

trial_003 train e008:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:18,  1.39it/s, avg=0.09606, loss=0.10827]

trial_003 train e008:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:14,  1.45it/s, avg=0.09606, loss=0.10827]

trial_003 train e008:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:14,  1.45it/s, avg=0.09616, loss=0.10011]

trial_003 train e008:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:14,  1.43it/s, avg=0.09616, loss=0.10011]

trial_003 train e008:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:14,  1.43it/s, avg=0.09609, loss=0.09329]

trial_003 train e008:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:14,  1.42it/s, avg=0.09609, loss=0.09329]

trial_003 train e008:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:14,  1.42it/s, avg=0.09614, loss=0.09808]

trial_003 train e008:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:14,  1.41it/s, avg=0.09614, loss=0.09808]

trial_003 train e008:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:14,  1.41it/s, avg=0.09631, loss=0.10371]

trial_003 train e008:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.39it/s, avg=0.09631, loss=0.10371]

trial_003 train e008:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:14,  1.39it/s, avg=0.09606, loss=0.08486]

trial_003 train e008:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:13,  1.41it/s, avg=0.09606, loss=0.08486]

trial_003 train e008:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:13,  1.41it/s, avg=0.09590, loss=0.08855]

trial_003 train e008:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.40it/s, avg=0.09590, loss=0.08855]

trial_003 train e008:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:12,  1.40it/s, avg=0.09602, loss=0.10203]

trial_003 train e008:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.40it/s, avg=0.09602, loss=0.10203]

trial_003 train e008:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:12,  1.40it/s, avg=0.09605, loss=0.09749]

trial_003 train e008:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:11,  1.40it/s, avg=0.09605, loss=0.09749]

trial_003 train e008:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:11,  1.40it/s, avg=0.09608, loss=0.09749]

trial_003 train e008:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:11,  1.39it/s, avg=0.09608, loss=0.09749]

trial_003 train e008:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:11,  1.39it/s, avg=0.09606, loss=0.09468]

trial_003 train e008:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:10,  1.39it/s, avg=0.09606, loss=0.09468]

trial_003 train e008:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:10,  1.39it/s, avg=0.09594, loss=0.08991]

trial_003 train e008:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.39it/s, avg=0.09594, loss=0.08991]

trial_003 train e008:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:09,  1.39it/s, avg=0.09580, loss=0.08891]

trial_003 train e008:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:09,  1.38it/s, avg=0.09580, loss=0.08891]

trial_003 train e008:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:09,  1.38it/s, avg=0.09600, loss=0.10613]

trial_003 train e008:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:08,  1.39it/s, avg=0.09600, loss=0.10613]

trial_003 train e008:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:08,  1.39it/s, avg=0.09587, loss=0.08884]

trial_003 train e008:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:06,  1.41it/s, avg=0.09587, loss=0.08884]

trial_003 train e008:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:06,  1.41it/s, avg=0.09563, loss=0.08286]

trial_003 train e008:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:04,  1.44it/s, avg=0.09563, loss=0.08286]

trial_003 train e008:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:04,  1.44it/s, avg=0.09546, loss=0.08587]

trial_003 train e008:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:04,  1.42it/s, avg=0.09546, loss=0.08587]

trial_003 train e008:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:04,  1.42it/s, avg=0.09539, loss=0.09113]

trial_003 train e008:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.40it/s, avg=0.09539, loss=0.09113]

trial_003 train e008:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:05,  1.40it/s, avg=0.09516, loss=0.08210]

trial_003 train e008:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:05,  1.38it/s, avg=0.09516, loss=0.08210]

trial_003 train e008:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:05,  1.38it/s, avg=0.09527, loss=0.10183]

trial_003 train e008:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:03,  1.40it/s, avg=0.09527, loss=0.10183]

trial_003 train e008:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:03,  1.40it/s, avg=0.09502, loss=0.08010]

trial_003 train e008:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:00,  1.45it/s, avg=0.09502, loss=0.08010]

trial_003 train e008:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:00,  1.45it/s, avg=0.09483, loss=0.08287]

trial_003 train e008:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<00:59,  1.45it/s, avg=0.09483, loss=0.08287]

trial_003 train e008:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<00:59,  1.45it/s, avg=0.09496, loss=0.10299]

trial_003 train e008:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<00:59,  1.45it/s, avg=0.09496, loss=0.10299]

trial_003 train e008:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<00:59,  1.45it/s, avg=0.09503, loss=0.09932]

trial_003 train e008:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<00:59,  1.44it/s, avg=0.09503, loss=0.09932]

trial_003 train e008:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<00:59,  1.44it/s, avg=0.09519, loss=0.10569]

trial_003 train e008:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:58,  1.43it/s, avg=0.09519, loss=0.10569]

trial_003 train e008:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:58,  1.43it/s, avg=0.09527, loss=0.10049]

trial_003 train e008:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<00:58,  1.42it/s, avg=0.09527, loss=0.10049]

trial_003 train e008:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:58,  1.42it/s, avg=0.09528, loss=0.09575]

trial_003 train e008:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:58,  1.41it/s, avg=0.09528, loss=0.09575]

trial_003 train e008:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.41it/s, avg=0.09526, loss=0.09434]

trial_003 train e008:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:56,  1.43it/s, avg=0.09526, loss=0.09434]

trial_003 train e008:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<00:56,  1.43it/s, avg=0.09535, loss=0.10123]

trial_003 train e008:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:55,  1.43it/s, avg=0.09535, loss=0.10123]

trial_003 train e008:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:55,  1.43it/s, avg=0.09537, loss=0.09704]

trial_003 train e008:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:49<00:55,  1.43it/s, avg=0.09537, loss=0.09704]

trial_003 train e008:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:55,  1.43it/s, avg=0.09539, loss=0.09628]

trial_003 train e008:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:54,  1.42it/s, avg=0.09539, loss=0.09628]

trial_003 train e008:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:54,  1.42it/s, avg=0.09534, loss=0.09191]

trial_003 train e008:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:53,  1.45it/s, avg=0.09534, loss=0.09191]

trial_003 train e008:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:53,  1.45it/s, avg=0.09530, loss=0.09245]

trial_003 train e008:  49%|██████████████████████████████████████████████                                                | 73/149 [00:51<00:53,  1.42it/s, avg=0.09530, loss=0.09245]

trial_003 train e008:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:53,  1.42it/s, avg=0.09509, loss=0.08002]

trial_003 train e008:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:53,  1.41it/s, avg=0.09509, loss=0.08002]

trial_003 train e008:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.41it/s, avg=0.09493, loss=0.08274]

trial_003 train e008:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:53,  1.39it/s, avg=0.09493, loss=0.08274]

trial_003 train e008:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:53,  1.39it/s, avg=0.09491, loss=0.09380]

trial_003 train e008:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:53,  1.38it/s, avg=0.09491, loss=0.09380]

trial_003 train e008:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:53,  1.38it/s, avg=0.09483, loss=0.08844]

trial_003 train e008:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:52,  1.38it/s, avg=0.09483, loss=0.08844]

trial_003 train e008:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:52,  1.38it/s, avg=0.09473, loss=0.08692]

trial_003 train e008:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:51,  1.37it/s, avg=0.09473, loss=0.08692]

trial_003 train e008:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:51,  1.37it/s, avg=0.09492, loss=0.10952]

trial_003 train e008:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.37it/s, avg=0.09492, loss=0.10952]

trial_003 train e008:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.37it/s, avg=0.09488, loss=0.09201]

trial_003 train e008:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:56<00:50,  1.36it/s, avg=0.09488, loss=0.09201]

trial_003 train e008:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:50,  1.36it/s, avg=0.09499, loss=0.10422]

trial_003 train e008:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:51,  1.32it/s, avg=0.09499, loss=0.10422]

trial_003 train e008:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:51,  1.32it/s, avg=0.09485, loss=0.08320]

trial_003 train e008:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:50,  1.32it/s, avg=0.09485, loss=0.08320]

trial_003 train e008:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:50,  1.32it/s, avg=0.09487, loss=0.09659]

trial_003 train e008:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:49,  1.33it/s, avg=0.09487, loss=0.09659]

trial_003 train e008:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:49,  1.33it/s, avg=0.09504, loss=0.10938]

trial_003 train e008:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:59<00:47,  1.36it/s, avg=0.09504, loss=0.10938]

trial_003 train e008:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:47,  1.36it/s, avg=0.09515, loss=0.10418]

trial_003 train e008:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:46,  1.37it/s, avg=0.09515, loss=0.10418]

trial_003 train e008:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.37it/s, avg=0.09518, loss=0.09789]

trial_003 train e008:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.38it/s, avg=0.09518, loss=0.09789]

trial_003 train e008:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.38it/s, avg=0.09512, loss=0.08970]

trial_003 train e008:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.39it/s, avg=0.09512, loss=0.08970]

trial_003 train e008:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.39it/s, avg=0.09517, loss=0.09941]

trial_003 train e008:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:43,  1.42it/s, avg=0.09517, loss=0.09941]

trial_003 train e008:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.42it/s, avg=0.09533, loss=0.10972]

trial_003 train e008:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:42,  1.40it/s, avg=0.09533, loss=0.10972]

trial_003 train e008:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:42,  1.40it/s, avg=0.09530, loss=0.09233]

trial_003 train e008:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.38it/s, avg=0.09530, loss=0.09233]

trial_003 train e008:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.38it/s, avg=0.09532, loss=0.09699]

trial_003 train e008:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:04<00:41,  1.39it/s, avg=0.09532, loss=0.09699]

trial_003 train e008:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:41,  1.39it/s, avg=0.09519, loss=0.08377]

trial_003 train e008:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:41,  1.38it/s, avg=0.09519, loss=0.08377]

trial_003 train e008:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.38it/s, avg=0.09528, loss=0.10348]

trial_003 train e008:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:39,  1.41it/s, avg=0.09528, loss=0.10348]

trial_003 train e008:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:39,  1.41it/s, avg=0.09518, loss=0.08609]

trial_003 train e008:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:39,  1.38it/s, avg=0.09518, loss=0.08609]

trial_003 train e008:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:39,  1.38it/s, avg=0.09518, loss=0.09509]

trial_003 train e008:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:38,  1.40it/s, avg=0.09518, loss=0.09509]

trial_003 train e008:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:38,  1.40it/s, avg=0.09530, loss=0.10694]

trial_003 train e008:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:38,  1.38it/s, avg=0.09530, loss=0.10694]

trial_003 train e008:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:38,  1.38it/s, avg=0.09537, loss=0.10141]

trial_003 train e008:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.38it/s, avg=0.09537, loss=0.10141]

trial_003 train e008:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:37,  1.38it/s, avg=0.09541, loss=0.09920]

trial_003 train e008:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.39it/s, avg=0.09541, loss=0.09920]

trial_003 train e008:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.39it/s, avg=0.09545, loss=0.09999]

trial_003 train e008:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:36,  1.36it/s, avg=0.09545, loss=0.09999]

trial_003 train e008:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:36,  1.36it/s, avg=0.09538, loss=0.08764]

trial_003 train e008:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:36,  1.36it/s, avg=0.09538, loss=0.08764]

trial_003 train e008:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:36,  1.36it/s, avg=0.09545, loss=0.10246]

trial_003 train e008:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.37it/s, avg=0.09545, loss=0.10246]

trial_003 train e008:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.37it/s, avg=0.09542, loss=0.09285]

trial_003 train e008:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:33,  1.39it/s, avg=0.09542, loss=0.09285]

trial_003 train e008:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:33,  1.39it/s, avg=0.09542, loss=0.09542]

trial_003 train e008:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:33,  1.39it/s, avg=0.09542, loss=0.09542]

trial_003 train e008:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:33,  1.39it/s, avg=0.09544, loss=0.09756]

trial_003 train e008:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.37it/s, avg=0.09544, loss=0.09756]

trial_003 train e008:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.37it/s, avg=0.09535, loss=0.08641]

trial_003 train e008:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:32,  1.34it/s, avg=0.09535, loss=0.08641]

trial_003 train e008:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:32,  1.34it/s, avg=0.09539, loss=0.09948]

trial_003 train e008:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:32,  1.34it/s, avg=0.09539, loss=0.09948]

trial_003 train e008:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:32,  1.34it/s, avg=0.09536, loss=0.09210]

trial_003 train e008:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:31,  1.33it/s, avg=0.09536, loss=0.09210]

trial_003 train e008:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:31,  1.33it/s, avg=0.09542, loss=0.10107]

trial_003 train e008:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:30,  1.35it/s, avg=0.09542, loss=0.10107]

trial_003 train e008:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:30,  1.35it/s, avg=0.09540, loss=0.09401]

trial_003 train e008:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:29,  1.35it/s, avg=0.09540, loss=0.09401]

trial_003 train e008:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:29,  1.35it/s, avg=0.09541, loss=0.09589]

trial_003 train e008:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:28,  1.35it/s, avg=0.09541, loss=0.09589]

trial_003 train e008:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:28,  1.35it/s, avg=0.09543, loss=0.09816]

trial_003 train e008:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:27,  1.37it/s, avg=0.09543, loss=0.09816]

trial_003 train e008:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:27,  1.37it/s, avg=0.09552, loss=0.10553]

trial_003 train e008:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:27,  1.35it/s, avg=0.09552, loss=0.10553]

trial_003 train e008:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:21<00:27,  1.35it/s, avg=0.09558, loss=0.10196]

trial_003 train e008:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:26,  1.36it/s, avg=0.09558, loss=0.10196]

trial_003 train e008:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:26,  1.36it/s, avg=0.09560, loss=0.09837]

trial_003 train e008:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:25,  1.37it/s, avg=0.09560, loss=0.09837]

trial_003 train e008:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:25,  1.37it/s, avg=0.09569, loss=0.10581]

trial_003 train e008:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:24,  1.40it/s, avg=0.09569, loss=0.10581]

trial_003 train e008:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:23<00:24,  1.40it/s, avg=0.09573, loss=0.09987]

trial_003 train e008:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.43it/s, avg=0.09573, loss=0.09987]

trial_003 train e008:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:23,  1.43it/s, avg=0.09569, loss=0.09144]

trial_003 train e008:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:22,  1.41it/s, avg=0.09569, loss=0.09144]

trial_003 train e008:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:22,  1.41it/s, avg=0.09566, loss=0.09177]

trial_003 train e008:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:22,  1.41it/s, avg=0.09566, loss=0.09177]

trial_003 train e008:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:22,  1.41it/s, avg=0.09562, loss=0.09149]

trial_003 train e008:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.41it/s, avg=0.09562, loss=0.09149]

trial_003 train e008:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:26<00:21,  1.41it/s, avg=0.09564, loss=0.09785]

trial_003 train e008:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.40it/s, avg=0.09564, loss=0.09785]

trial_003 train e008:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:20,  1.40it/s, avg=0.09576, loss=0.11000]

trial_003 train e008:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:19,  1.46it/s, avg=0.09576, loss=0.11000]

trial_003 train e008:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:19,  1.46it/s, avg=0.09575, loss=0.09423]

trial_003 train e008:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:18,  1.45it/s, avg=0.09575, loss=0.09423]

trial_003 train e008:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:28<00:18,  1.45it/s, avg=0.09568, loss=0.08781]

trial_003 train e008:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.43it/s, avg=0.09568, loss=0.08781]

trial_003 train e008:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.43it/s, avg=0.09569, loss=0.09655]

trial_003 train e008:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.44it/s, avg=0.09569, loss=0.09655]

trial_003 train e008:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.44it/s, avg=0.09572, loss=0.09903]

trial_003 train e008:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:16,  1.46it/s, avg=0.09572, loss=0.09903]

trial_003 train e008:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:16,  1.46it/s, avg=0.09567, loss=0.08963]

trial_003 train e008:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.43it/s, avg=0.09567, loss=0.08963]

trial_003 train e008:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.43it/s, avg=0.09570, loss=0.10017]

trial_003 train e008:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.38it/s, avg=0.09570, loss=0.10017]

trial_003 train e008:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:15,  1.38it/s, avg=0.09573, loss=0.09913]

trial_003 train e008:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.38it/s, avg=0.09573, loss=0.09913]

trial_003 train e008:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.38it/s, avg=0.09569, loss=0.08991]

trial_003 train e008:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.39it/s, avg=0.09569, loss=0.08991]

trial_003 train e008:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:33<00:14,  1.39it/s, avg=0.09562, loss=0.08761]

trial_003 train e008:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.39it/s, avg=0.09562, loss=0.08761]

trial_003 train e008:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.39it/s, avg=0.09563, loss=0.09596]

trial_003 train e008:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:12,  1.39it/s, avg=0.09563, loss=0.09596]

trial_003 train e008:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:12,  1.39it/s, avg=0.09579, loss=0.11695]

trial_003 train e008:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.39it/s, avg=0.09579, loss=0.11695]

trial_003 train e008:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.39it/s, avg=0.09580, loss=0.09743]

trial_003 train e008:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.38it/s, avg=0.09580, loss=0.09743]

trial_003 train e008:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.38it/s, avg=0.09578, loss=0.09287]

trial_003 train e008:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.40it/s, avg=0.09578, loss=0.09287]

trial_003 train e008:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:10,  1.40it/s, avg=0.09576, loss=0.09362]

trial_003 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.40it/s, avg=0.09576, loss=0.09362]

trial_003 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.40it/s, avg=0.09577, loss=0.09686]

trial_003 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.40it/s, avg=0.09577, loss=0.09686]

trial_003 train e008:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.40it/s, avg=0.09571, loss=0.08689]

trial_003 train e008:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.39it/s, avg=0.09571, loss=0.08689]

trial_003 train e008:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.39it/s, avg=0.09566, loss=0.08896]

trial_003 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:07,  1.39it/s, avg=0.09566, loss=0.08896]

trial_003 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:07,  1.39it/s, avg=0.09569, loss=0.10014]

trial_003 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.37it/s, avg=0.09569, loss=0.10014]

trial_003 train e008:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.37it/s, avg=0.09575, loss=0.10437]

trial_003 train e008:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.38it/s, avg=0.09575, loss=0.10437]

trial_003 train e008:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:41<00:06,  1.38it/s, avg=0.09565, loss=0.08205]

trial_003 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.37it/s, avg=0.09565, loss=0.08205]

trial_003 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.37it/s, avg=0.09563, loss=0.09223]

trial_003 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:05,  1.39it/s, avg=0.09563, loss=0.09223]

trial_003 train e008:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:05,  1.39it/s, avg=0.09564, loss=0.09738]

trial_003 train e008:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.39it/s, avg=0.09564, loss=0.09738]

trial_003 train e008:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.39it/s, avg=0.09568, loss=0.10125]

trial_003 train e008:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.37it/s, avg=0.09568, loss=0.10125]

trial_003 train e008:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.37it/s, avg=0.09563, loss=0.08866]

trial_003 train e008:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.36it/s, avg=0.09563, loss=0.08866]

trial_003 train e008:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.36it/s, avg=0.09558, loss=0.08828]

trial_003 train e008:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.39it/s, avg=0.09558, loss=0.08828]

trial_003 train e008:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.39it/s, avg=0.09550, loss=0.08357]

trial_003 train e008:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.38it/s, avg=0.09550, loss=0.08357]

trial_003 train e008:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.38it/s, avg=0.09558, loss=0.10769]

trial_003 train e008:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.45it/s, avg=0.09558, loss=0.10769]

trial_003 train e008:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.45it/s, avg=0.09560, loss=0.10217]

trial_003 train e008: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:46<00:00,  1.73it/s, avg=0.09560, loss=0.10217]

trial_003 val e008:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e008:   2%|██▌                                                                                                                          | 1/50 [00:00<00:18,  2.61it/s]

trial_003 val e008:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.52it/s]

trial_003 val e008:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.47it/s]

trial_003 val e008:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.43it/s]

trial_003 val e008:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.42it/s]

trial_003 val e008:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.42it/s]

trial_003 val e008:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.43it/s]

trial_003 val e008:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.43it/s]

trial_003 val e008:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.45it/s]

trial_003 val e008:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.44it/s]

trial_003 val e008:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.45it/s]

trial_003 val e008:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.46it/s]

trial_003 val e008:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.44it/s]

trial_003 val e008:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.44it/s]

trial_003 val e008:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.44it/s]

trial_003 val e008:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:13,  2.47it/s]

trial_003 val e008:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:06<00:13,  2.45it/s]

trial_003 val e008:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.43it/s]

trial_003 val e008:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.43it/s]

trial_003 val e008:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.42it/s]

trial_003 val e008:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:12,  2.40it/s]

trial_003 val e008:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.41it/s]

trial_003 val e008:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.41it/s]

trial_003 val e008:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.41it/s]

trial_003 val e008:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.41it/s]

trial_003 val e008:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.40it/s]

trial_003 val e008:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.40it/s]

trial_003 val e008:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.42it/s]

trial_003 val e008:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.42it/s]

trial_003 val e008:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.42it/s]

trial_003 val e008:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.43it/s]

trial_003 val e008:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.44it/s]

trial_003 val e008:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:06,  2.45it/s]

trial_003 val e008:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:13<00:06,  2.44it/s]

trial_003 val e008:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.45it/s]

trial_003 val e008:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.43it/s]

trial_003 val e008:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.43it/s]

trial_003 val e008:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.44it/s]

trial_003 val e008:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.45it/s]

trial_003 val e008:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.44it/s]

trial_003 val e008:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.44it/s]

trial_003 val e008:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.45it/s]

trial_003 val e008:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.42it/s]

trial_003 val e008:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.40it/s]

trial_003 val e008:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.38it/s]

trial_003 val e008:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.40it/s]

trial_003 val e008:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.42it/s]

trial_003 val e008:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.42it/s]

trial_003 val e008:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.43it/s]

trial_003 val e008: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.46it/s]

[2026-05-28 21:21:49] [trial_003] epoch=008 | train_loss=0.095601 | val_MAE=0.100564 | val_S=0.899436 | best_S=0.900170 @epoch=5 | patience=3/5

[trial_003] epochs:   8%|█████████▋                                                                                                               | 8/100 [16:39<3:13:17, 126.07s/it]

trial_003 train e009:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e009:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08694, loss=0.08694]

trial_003 train e009:   1%|▋                                                                                              | 1/149 [00:00<01:38,  1.50it/s, avg=0.08694, loss=0.08694]

trial_003 train e009:   1%|▋                                                                                              | 1/149 [00:01<01:38,  1.50it/s, avg=0.09725, loss=0.10756]

trial_003 train e009:   1%|█▎                                                                                             | 2/149 [00:01<01:38,  1.49it/s, avg=0.09725, loss=0.10756]

trial_003 train e009:   1%|█▎                                                                                             | 2/149 [00:02<01:38,  1.49it/s, avg=0.10160, loss=0.11030]

trial_003 train e009:   2%|█▉                                                                                             | 3/149 [00:02<01:39,  1.47it/s, avg=0.10160, loss=0.11030]

trial_003 train e009:   2%|█▉                                                                                             | 3/149 [00:02<01:39,  1.47it/s, avg=0.09880, loss=0.09040]

trial_003 train e009:   3%|██▌                                                                                            | 4/149 [00:02<01:42,  1.42it/s, avg=0.09880, loss=0.09040]

trial_003 train e009:   3%|██▌                                                                                            | 4/149 [00:03<01:42,  1.42it/s, avg=0.09859, loss=0.09776]

trial_003 train e009:   3%|███▏                                                                                           | 5/149 [00:03<01:40,  1.43it/s, avg=0.09859, loss=0.09776]

trial_003 train e009:   3%|███▏                                                                                           | 5/149 [00:04<01:40,  1.43it/s, avg=0.09758, loss=0.09253]

trial_003 train e009:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.40it/s, avg=0.09758, loss=0.09253]

trial_003 train e009:   4%|███▊                                                                                           | 6/149 [00:04<01:42,  1.40it/s, avg=0.09844, loss=0.10357]

trial_003 train e009:   5%|████▍                                                                                          | 7/149 [00:04<01:40,  1.42it/s, avg=0.09844, loss=0.10357]

trial_003 train e009:   5%|████▍                                                                                          | 7/149 [00:05<01:40,  1.42it/s, avg=0.09857, loss=0.09953]

trial_003 train e009:   5%|█████                                                                                          | 8/149 [00:05<01:38,  1.43it/s, avg=0.09857, loss=0.09953]

trial_003 train e009:   5%|█████                                                                                          | 8/149 [00:06<01:38,  1.43it/s, avg=0.09872, loss=0.09991]

trial_003 train e009:   6%|█████▋                                                                                         | 9/149 [00:06<01:36,  1.45it/s, avg=0.09872, loss=0.09991]

trial_003 train e009:   6%|█████▋                                                                                         | 9/149 [00:06<01:36,  1.45it/s, avg=0.09968, loss=0.10828]

trial_003 train e009:   7%|██████▎                                                                                       | 10/149 [00:06<01:34,  1.47it/s, avg=0.09968, loss=0.10828]

trial_003 train e009:   7%|██████▎                                                                                       | 10/149 [00:07<01:34,  1.47it/s, avg=0.09914, loss=0.09377]

trial_003 train e009:   7%|██████▉                                                                                       | 11/149 [00:07<01:35,  1.44it/s, avg=0.09914, loss=0.09377]

trial_003 train e009:   7%|██████▉                                                                                       | 11/149 [00:08<01:35,  1.44it/s, avg=0.09792, loss=0.08454]

trial_003 train e009:   8%|███████▌                                                                                      | 12/149 [00:08<01:37,  1.41it/s, avg=0.09792, loss=0.08454]

trial_003 train e009:   8%|███████▌                                                                                      | 12/149 [00:09<01:37,  1.41it/s, avg=0.09765, loss=0.09440]

trial_003 train e009:   9%|████████▏                                                                                     | 13/149 [00:09<01:36,  1.41it/s, avg=0.09765, loss=0.09440]

trial_003 train e009:   9%|████████▏                                                                                     | 13/149 [00:09<01:36,  1.41it/s, avg=0.09760, loss=0.09692]

trial_003 train e009:   9%|████████▊                                                                                     | 14/149 [00:09<01:36,  1.39it/s, avg=0.09760, loss=0.09692]

trial_003 train e009:   9%|████████▊                                                                                     | 14/149 [00:10<01:36,  1.39it/s, avg=0.09771, loss=0.09926]

trial_003 train e009:  10%|█████████▍                                                                                    | 15/149 [00:10<01:34,  1.42it/s, avg=0.09771, loss=0.09926]

trial_003 train e009:  10%|█████████▍                                                                                    | 15/149 [00:11<01:34,  1.42it/s, avg=0.09684, loss=0.08384]

trial_003 train e009:  11%|██████████                                                                                    | 16/149 [00:11<01:33,  1.43it/s, avg=0.09684, loss=0.08384]

trial_003 train e009:  11%|██████████                                                                                    | 16/149 [00:11<01:33,  1.43it/s, avg=0.09612, loss=0.08460]

trial_003 train e009:  11%|██████████▋                                                                                   | 17/149 [00:11<01:32,  1.43it/s, avg=0.09612, loss=0.08460]

trial_003 train e009:  11%|██████████▋                                                                                   | 17/149 [00:12<01:32,  1.43it/s, avg=0.09558, loss=0.08633]

trial_003 train e009:  12%|███████████▎                                                                                  | 18/149 [00:12<01:32,  1.42it/s, avg=0.09558, loss=0.08633]

trial_003 train e009:  12%|███████████▎                                                                                  | 18/149 [00:13<01:32,  1.42it/s, avg=0.09556, loss=0.09525]

trial_003 train e009:  13%|███████████▉                                                                                  | 19/149 [00:13<01:32,  1.40it/s, avg=0.09556, loss=0.09525]

trial_003 train e009:  13%|███████████▉                                                                                  | 19/149 [00:14<01:32,  1.40it/s, avg=0.09534, loss=0.09111]

trial_003 train e009:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.41it/s, avg=0.09534, loss=0.09111]

trial_003 train e009:  13%|████████████▌                                                                                 | 20/149 [00:14<01:31,  1.41it/s, avg=0.09489, loss=0.08591]

trial_003 train e009:  14%|█████████████▏                                                                                | 21/149 [00:14<01:32,  1.39it/s, avg=0.09489, loss=0.08591]

trial_003 train e009:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.39it/s, avg=0.09445, loss=0.08523]

trial_003 train e009:  15%|█████████████▉                                                                                | 22/149 [00:15<01:30,  1.41it/s, avg=0.09445, loss=0.08523]

trial_003 train e009:  15%|█████████████▉                                                                                | 22/149 [00:16<01:30,  1.41it/s, avg=0.09375, loss=0.07825]

trial_003 train e009:  15%|██████████████▌                                                                               | 23/149 [00:16<01:30,  1.39it/s, avg=0.09375, loss=0.07825]

trial_003 train e009:  15%|██████████████▌                                                                               | 23/149 [00:16<01:30,  1.39it/s, avg=0.09398, loss=0.09937]

trial_003 train e009:  16%|███████████████▏                                                                              | 24/149 [00:16<01:31,  1.37it/s, avg=0.09398, loss=0.09937]

trial_003 train e009:  16%|███████████████▏                                                                              | 24/149 [00:17<01:31,  1.37it/s, avg=0.09426, loss=0.10091]

trial_003 train e009:  17%|███████████████▊                                                                              | 25/149 [00:17<01:28,  1.40it/s, avg=0.09426, loss=0.10091]

trial_003 train e009:  17%|███████████████▊                                                                              | 25/149 [00:18<01:28,  1.40it/s, avg=0.09465, loss=0.10454]

trial_003 train e009:  17%|████████████████▍                                                                             | 26/149 [00:18<01:27,  1.41it/s, avg=0.09465, loss=0.10454]

trial_003 train e009:  17%|████████████████▍                                                                             | 26/149 [00:19<01:27,  1.41it/s, avg=0.09472, loss=0.09646]

trial_003 train e009:  18%|█████████████████                                                                             | 27/149 [00:19<01:27,  1.39it/s, avg=0.09472, loss=0.09646]

trial_003 train e009:  18%|█████████████████                                                                             | 27/149 [00:19<01:27,  1.39it/s, avg=0.09475, loss=0.09541]

trial_003 train e009:  19%|█████████████████▋                                                                            | 28/149 [00:19<01:27,  1.39it/s, avg=0.09475, loss=0.09541]

trial_003 train e009:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:27,  1.39it/s, avg=0.09495, loss=0.10078]

trial_003 train e009:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:26,  1.38it/s, avg=0.09495, loss=0.10078]

trial_003 train e009:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.38it/s, avg=0.09513, loss=0.10023]

trial_003 train e009:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:24,  1.40it/s, avg=0.09513, loss=0.10023]

trial_003 train e009:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:24,  1.40it/s, avg=0.09477, loss=0.08406]

trial_003 train e009:  21%|███████████████████▌                                                                          | 31/149 [00:21<01:24,  1.40it/s, avg=0.09477, loss=0.08406]

trial_003 train e009:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:24,  1.40it/s, avg=0.09471, loss=0.09279]

trial_003 train e009:  21%|████████████████████▏                                                                         | 32/149 [00:22<01:22,  1.41it/s, avg=0.09471, loss=0.09279]

trial_003 train e009:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:22,  1.41it/s, avg=0.09475, loss=0.09591]

trial_003 train e009:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:20,  1.44it/s, avg=0.09475, loss=0.09591]

trial_003 train e009:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:20,  1.44it/s, avg=0.09486, loss=0.09847]

trial_003 train e009:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:21,  1.42it/s, avg=0.09486, loss=0.09847]

trial_003 train e009:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:21,  1.42it/s, avg=0.09489, loss=0.09598]

trial_003 train e009:  23%|██████████████████████                                                                        | 35/149 [00:24<01:21,  1.40it/s, avg=0.09489, loss=0.09598]

trial_003 train e009:  23%|██████████████████████                                                                        | 35/149 [00:25<01:21,  1.40it/s, avg=0.09533, loss=0.11064]

trial_003 train e009:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:21,  1.39it/s, avg=0.09533, loss=0.11064]

trial_003 train e009:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:21,  1.39it/s, avg=0.09543, loss=0.09926]

trial_003 train e009:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:20,  1.39it/s, avg=0.09543, loss=0.09926]

trial_003 train e009:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:20,  1.39it/s, avg=0.09599, loss=0.11677]

trial_003 train e009:  26%|███████████████████████▉                                                                      | 38/149 [00:26<01:18,  1.42it/s, avg=0.09599, loss=0.11677]

trial_003 train e009:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:18,  1.42it/s, avg=0.09576, loss=0.08696]

trial_003 train e009:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:18,  1.40it/s, avg=0.09576, loss=0.08696]

trial_003 train e009:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:18,  1.40it/s, avg=0.09594, loss=0.10279]

trial_003 train e009:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:16,  1.42it/s, avg=0.09594, loss=0.10279]

trial_003 train e009:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:16,  1.42it/s, avg=0.09590, loss=0.09441]

trial_003 train e009:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:17,  1.40it/s, avg=0.09590, loss=0.09441]

trial_003 train e009:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:17,  1.40it/s, avg=0.09634, loss=0.11415]

trial_003 train e009:  28%|██████████████████████████▍                                                                   | 42/149 [00:29<01:14,  1.44it/s, avg=0.09634, loss=0.11415]

trial_003 train e009:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:14,  1.44it/s, avg=0.09624, loss=0.09241]

trial_003 train e009:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:14,  1.42it/s, avg=0.09624, loss=0.09241]

trial_003 train e009:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:14,  1.42it/s, avg=0.09627, loss=0.09719]

trial_003 train e009:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:15,  1.39it/s, avg=0.09627, loss=0.09719]

trial_003 train e009:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:15,  1.39it/s, avg=0.09647, loss=0.10562]

trial_003 train e009:  30%|████████████████████████████▍                                                                 | 45/149 [00:31<01:12,  1.44it/s, avg=0.09647, loss=0.10562]

trial_003 train e009:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:12,  1.44it/s, avg=0.09654, loss=0.09976]

trial_003 train e009:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:12,  1.41it/s, avg=0.09654, loss=0.09976]

trial_003 train e009:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:12,  1.41it/s, avg=0.09634, loss=0.08686]

trial_003 train e009:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.41it/s, avg=0.09634, loss=0.08686]

trial_003 train e009:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:12,  1.41it/s, avg=0.09616, loss=0.08786]

trial_003 train e009:  32%|██████████████████████████████▎                                                               | 48/149 [00:33<01:10,  1.44it/s, avg=0.09616, loss=0.08786]

trial_003 train e009:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:10,  1.44it/s, avg=0.09620, loss=0.09805]

trial_003 train e009:  33%|██████████████████████████████▉                                                               | 49/149 [00:34<01:10,  1.41it/s, avg=0.09620, loss=0.09805]

trial_003 train e009:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:10,  1.41it/s, avg=0.09614, loss=0.09308]

trial_003 train e009:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:10,  1.41it/s, avg=0.09614, loss=0.09308]

trial_003 train e009:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:10,  1.41it/s, avg=0.09609, loss=0.09379]

trial_003 train e009:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:08,  1.44it/s, avg=0.09609, loss=0.09379]

trial_003 train e009:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:08,  1.44it/s, avg=0.09623, loss=0.10330]

trial_003 train e009:  35%|████████████████████████████████▊                                                             | 52/149 [00:36<01:08,  1.41it/s, avg=0.09623, loss=0.10330]

trial_003 train e009:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:08,  1.41it/s, avg=0.09610, loss=0.08948]

trial_003 train e009:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:09,  1.39it/s, avg=0.09610, loss=0.08948]

trial_003 train e009:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:09,  1.39it/s, avg=0.09628, loss=0.10562]

trial_003 train e009:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:08,  1.39it/s, avg=0.09628, loss=0.10562]

trial_003 train e009:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:08,  1.39it/s, avg=0.09632, loss=0.09858]

trial_003 train e009:  37%|██████████████████████████████████▋                                                           | 55/149 [00:38<01:07,  1.39it/s, avg=0.09632, loss=0.09858]

trial_003 train e009:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:07,  1.39it/s, avg=0.09641, loss=0.10145]

trial_003 train e009:  38%|███████████████████████████████████▎                                                          | 56/149 [00:39<01:06,  1.40it/s, avg=0.09641, loss=0.10145]

trial_003 train e009:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.40it/s, avg=0.09614, loss=0.08092]

trial_003 train e009:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:04,  1.42it/s, avg=0.09614, loss=0.08092]

trial_003 train e009:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:04,  1.42it/s, avg=0.09613, loss=0.09543]

trial_003 train e009:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.39it/s, avg=0.09613, loss=0.09543]

trial_003 train e009:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.39it/s, avg=0.09623, loss=0.10200]

trial_003 train e009:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:41<01:05,  1.38it/s, avg=0.09623, loss=0.10200]

trial_003 train e009:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:05,  1.38it/s, avg=0.09607, loss=0.08647]

trial_003 train e009:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:03,  1.40it/s, avg=0.09607, loss=0.08647]

trial_003 train e009:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:03,  1.40it/s, avg=0.09599, loss=0.09133]

trial_003 train e009:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:02,  1.40it/s, avg=0.09599, loss=0.09133]

trial_003 train e009:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:02,  1.40it/s, avg=0.09589, loss=0.09016]

trial_003 train e009:  42%|███████████████████████████████████████                                                       | 62/149 [00:43<01:01,  1.40it/s, avg=0.09589, loss=0.09016]

trial_003 train e009:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:01,  1.40it/s, avg=0.09588, loss=0.09532]

trial_003 train e009:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:44<01:00,  1.41it/s, avg=0.09588, loss=0.09532]

trial_003 train e009:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:00,  1.41it/s, avg=0.09579, loss=0.08994]

trial_003 train e009:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<01:00,  1.41it/s, avg=0.09579, loss=0.08994]

trial_003 train e009:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:00,  1.41it/s, avg=0.09559, loss=0.08298]

trial_003 train e009:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.41it/s, avg=0.09559, loss=0.08298]

trial_003 train e009:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<00:59,  1.41it/s, avg=0.09571, loss=0.10350]

trial_003 train e009:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:46<00:59,  1.39it/s, avg=0.09571, loss=0.10350]

trial_003 train e009:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<00:59,  1.39it/s, avg=0.09589, loss=0.10717]

trial_003 train e009:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:47<00:58,  1.40it/s, avg=0.09589, loss=0.10717]

trial_003 train e009:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<00:58,  1.40it/s, avg=0.09606, loss=0.10808]

trial_003 train e009:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:57,  1.41it/s, avg=0.09606, loss=0.10808]

trial_003 train e009:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<00:57,  1.41it/s, avg=0.09591, loss=0.08516]

trial_003 train e009:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:48<00:57,  1.39it/s, avg=0.09591, loss=0.08516]

trial_003 train e009:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:57,  1.39it/s, avg=0.09574, loss=0.08421]

trial_003 train e009:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:49<00:57,  1.38it/s, avg=0.09574, loss=0.08421]

trial_003 train e009:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:57,  1.38it/s, avg=0.09562, loss=0.08757]

trial_003 train e009:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:55,  1.41it/s, avg=0.09562, loss=0.08757]

trial_003 train e009:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:55,  1.41it/s, avg=0.09558, loss=0.09234]

trial_003 train e009:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:55,  1.39it/s, avg=0.09558, loss=0.09234]

trial_003 train e009:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:55,  1.39it/s, avg=0.09564, loss=0.09972]

trial_003 train e009:  49%|██████████████████████████████████████████████                                                | 73/149 [00:51<00:55,  1.38it/s, avg=0.09564, loss=0.09972]

trial_003 train e009:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:55,  1.38it/s, avg=0.09552, loss=0.08684]

trial_003 train e009:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:52<00:55,  1.36it/s, avg=0.09552, loss=0.08684]

trial_003 train e009:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:55,  1.36it/s, avg=0.09541, loss=0.08769]

trial_003 train e009:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:54,  1.36it/s, avg=0.09541, loss=0.08769]

trial_003 train e009:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:54,  1.36it/s, avg=0.09552, loss=0.10328]

trial_003 train e009:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:53,  1.37it/s, avg=0.09552, loss=0.10328]

trial_003 train e009:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:53,  1.37it/s, avg=0.09550, loss=0.09403]

trial_003 train e009:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:54<00:52,  1.37it/s, avg=0.09550, loss=0.09403]

trial_003 train e009:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:52,  1.37it/s, avg=0.09567, loss=0.10939]

trial_003 train e009:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:50,  1.39it/s, avg=0.09567, loss=0.10939]

trial_003 train e009:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:50,  1.39it/s, avg=0.09578, loss=0.10390]

trial_003 train e009:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.40it/s, avg=0.09578, loss=0.10390]

trial_003 train e009:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:50,  1.40it/s, avg=0.09572, loss=0.09140]

trial_003 train e009:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:56<00:48,  1.42it/s, avg=0.09572, loss=0.09140]

trial_003 train e009:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:48,  1.42it/s, avg=0.09559, loss=0.08489]

trial_003 train e009:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:57<00:48,  1.42it/s, avg=0.09559, loss=0.08489]

trial_003 train e009:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:48,  1.42it/s, avg=0.09575, loss=0.10841]

trial_003 train e009:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:47,  1.41it/s, avg=0.09575, loss=0.10841]

trial_003 train e009:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:47,  1.41it/s, avg=0.09583, loss=0.10231]

trial_003 train e009:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:47,  1.39it/s, avg=0.09583, loss=0.10231]

trial_003 train e009:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:47,  1.39it/s, avg=0.09565, loss=0.08101]

trial_003 train e009:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [00:59<00:46,  1.38it/s, avg=0.09565, loss=0.08101]

trial_003 train e009:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:46,  1.38it/s, avg=0.09562, loss=0.09277]

trial_003 train e009:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:46,  1.38it/s, avg=0.09562, loss=0.09277]

trial_003 train e009:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.38it/s, avg=0.09575, loss=0.10695]

trial_003 train e009:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.40it/s, avg=0.09575, loss=0.10695]

trial_003 train e009:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.40it/s, avg=0.09572, loss=0.09345]

trial_003 train e009:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:01<00:44,  1.40it/s, avg=0.09572, loss=0.09345]

trial_003 train e009:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.40it/s, avg=0.09602, loss=0.12207]

trial_003 train e009:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:02<00:42,  1.43it/s, avg=0.09602, loss=0.12207]

trial_003 train e009:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:42,  1.43it/s, avg=0.09608, loss=0.10096]

trial_003 train e009:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:43,  1.37it/s, avg=0.09608, loss=0.10096]

trial_003 train e009:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:43,  1.37it/s, avg=0.09608, loss=0.09608]

trial_003 train e009:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:43,  1.36it/s, avg=0.09608, loss=0.09608]

trial_003 train e009:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:43,  1.36it/s, avg=0.09597, loss=0.08666]

trial_003 train e009:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:04<00:42,  1.37it/s, avg=0.09597, loss=0.08666]

trial_003 train e009:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:42,  1.37it/s, avg=0.09589, loss=0.08800]

trial_003 train e009:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:41,  1.38it/s, avg=0.09589, loss=0.08800]

trial_003 train e009:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.38it/s, avg=0.09591, loss=0.09771]

trial_003 train e009:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:39,  1.40it/s, avg=0.09591, loss=0.09771]

trial_003 train e009:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:39,  1.40it/s, avg=0.09579, loss=0.08484]

trial_003 train e009:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:06<00:37,  1.46it/s, avg=0.09579, loss=0.08484]

trial_003 train e009:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:37,  1.46it/s, avg=0.09595, loss=0.11134]

trial_003 train e009:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:07<00:37,  1.46it/s, avg=0.09595, loss=0.11134]

trial_003 train e009:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:37,  1.46it/s, avg=0.09579, loss=0.08077]

trial_003 train e009:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:37,  1.43it/s, avg=0.09579, loss=0.08077]

trial_003 train e009:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:37,  1.43it/s, avg=0.09578, loss=0.09415]

trial_003 train e009:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:08<00:36,  1.42it/s, avg=0.09578, loss=0.09415]

trial_003 train e009:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:36,  1.42it/s, avg=0.09583, loss=0.10056]

trial_003 train e009:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:09<00:35,  1.42it/s, avg=0.09583, loss=0.10056]

trial_003 train e009:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:35,  1.42it/s, avg=0.09589, loss=0.10222]

trial_003 train e009:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:35,  1.42it/s, avg=0.09589, loss=0.10222]

trial_003 train e009:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:35,  1.42it/s, avg=0.09581, loss=0.08795]

trial_003 train e009:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:34,  1.41it/s, avg=0.09581, loss=0.08795]

trial_003 train e009:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:34,  1.41it/s, avg=0.09578, loss=0.09236]

trial_003 train e009:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:11<00:34,  1.39it/s, avg=0.09578, loss=0.09236]

trial_003 train e009:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.39it/s, avg=0.09571, loss=0.08919]

trial_003 train e009:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:12<00:33,  1.41it/s, avg=0.09571, loss=0.08919]

trial_003 train e009:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:33,  1.41it/s, avg=0.09569, loss=0.09381]

trial_003 train e009:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:32,  1.40it/s, avg=0.09569, loss=0.09381]

trial_003 train e009:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:32,  1.40it/s, avg=0.09569, loss=0.09564]

trial_003 train e009:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:13<00:31,  1.42it/s, avg=0.09569, loss=0.09564]

trial_003 train e009:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:31,  1.42it/s, avg=0.09559, loss=0.08504]

trial_003 train e009:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:14<00:31,  1.38it/s, avg=0.09559, loss=0.08504]

trial_003 train e009:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.38it/s, avg=0.09547, loss=0.08313]

trial_003 train e009:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:31,  1.38it/s, avg=0.09547, loss=0.08313]

trial_003 train e009:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:31,  1.38it/s, avg=0.09553, loss=0.10145]

trial_003 train e009:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:30,  1.39it/s, avg=0.09553, loss=0.10145]

trial_003 train e009:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:30,  1.39it/s, avg=0.09559, loss=0.10188]

trial_003 train e009:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:16<00:29,  1.41it/s, avg=0.09559, loss=0.10188]

trial_003 train e009:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:29,  1.41it/s, avg=0.09539, loss=0.07375]

trial_003 train e009:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:17<00:28,  1.42it/s, avg=0.09539, loss=0.07375]

trial_003 train e009:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:28,  1.42it/s, avg=0.09530, loss=0.08592]

trial_003 train e009:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:27,  1.43it/s, avg=0.09530, loss=0.08592]

trial_003 train e009:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:27,  1.43it/s, avg=0.09524, loss=0.08817]

trial_003 train e009:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:18<00:26,  1.43it/s, avg=0.09524, loss=0.08817]

trial_003 train e009:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:26,  1.43it/s, avg=0.09525, loss=0.09634]

trial_003 train e009:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:19<00:25,  1.45it/s, avg=0.09525, loss=0.09634]

trial_003 train e009:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:25,  1.45it/s, avg=0.09516, loss=0.08567]

trial_003 train e009:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:20<00:25,  1.43it/s, avg=0.09516, loss=0.08567]

trial_003 train e009:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.43it/s, avg=0.09510, loss=0.08813]

trial_003 train e009:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.41it/s, avg=0.09510, loss=0.08813]

trial_003 train e009:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.41it/s, avg=0.09513, loss=0.09839]

trial_003 train e009:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:21<00:23,  1.42it/s, avg=0.09513, loss=0.09839]

trial_003 train e009:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:23,  1.42it/s, avg=0.09524, loss=0.10746]

trial_003 train e009:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:22<00:22,  1.47it/s, avg=0.09524, loss=0.10746]

trial_003 train e009:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:22,  1.47it/s, avg=0.09524, loss=0.09587]

trial_003 train e009:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:22,  1.43it/s, avg=0.09524, loss=0.09587]

trial_003 train e009:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:22,  1.43it/s, avg=0.09529, loss=0.10124]

trial_003 train e009:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:23<00:21,  1.41it/s, avg=0.09529, loss=0.10124]

trial_003 train e009:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:21,  1.41it/s, avg=0.09531, loss=0.09707]

trial_003 train e009:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:24<00:21,  1.41it/s, avg=0.09531, loss=0.09707]

trial_003 train e009:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.41it/s, avg=0.09526, loss=0.08999]

trial_003 train e009:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:20,  1.41it/s, avg=0.09526, loss=0.08999]

trial_003 train e009:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:20,  1.41it/s, avg=0.09533, loss=0.10311]

trial_003 train e009:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:25<00:19,  1.42it/s, avg=0.09533, loss=0.10311]

trial_003 train e009:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:19,  1.42it/s, avg=0.09541, loss=0.10585]

trial_003 train e009:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:26<00:19,  1.40it/s, avg=0.09541, loss=0.10585]

trial_003 train e009:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.40it/s, avg=0.09541, loss=0.09440]

trial_003 train e009:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:27<00:18,  1.39it/s, avg=0.09541, loss=0.09440]

trial_003 train e009:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.39it/s, avg=0.09547, loss=0.10281]

trial_003 train e009:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.41it/s, avg=0.09547, loss=0.10281]

trial_003 train e009:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.41it/s, avg=0.09539, loss=0.08580]

trial_003 train e009:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:28<00:16,  1.43it/s, avg=0.09539, loss=0.08580]

trial_003 train e009:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:16,  1.43it/s, avg=0.09538, loss=0.09428]

trial_003 train e009:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:29<00:16,  1.43it/s, avg=0.09538, loss=0.09428]

trial_003 train e009:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.43it/s, avg=0.09534, loss=0.09015]

trial_003 train e009:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.42it/s, avg=0.09534, loss=0.09015]

trial_003 train e009:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:15,  1.42it/s, avg=0.09531, loss=0.09126]

trial_003 train e009:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:30<00:15,  1.39it/s, avg=0.09531, loss=0.09126]

trial_003 train e009:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.39it/s, avg=0.09523, loss=0.08592]

trial_003 train e009:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:31<00:14,  1.39it/s, avg=0.09523, loss=0.08592]

trial_003 train e009:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.39it/s, avg=0.09520, loss=0.09132]

trial_003 train e009:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:32<00:13,  1.41it/s, avg=0.09520, loss=0.09132]

trial_003 train e009:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.41it/s, avg=0.09510, loss=0.08149]

trial_003 train e009:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:12,  1.39it/s, avg=0.09510, loss=0.08149]

trial_003 train e009:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:12,  1.39it/s, avg=0.09516, loss=0.10296]

trial_003 train e009:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:33<00:12,  1.37it/s, avg=0.09516, loss=0.10296]

trial_003 train e009:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.37it/s, avg=0.09511, loss=0.08920]

trial_003 train e009:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:34<00:11,  1.37it/s, avg=0.09511, loss=0.08920]

trial_003 train e009:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.37it/s, avg=0.09512, loss=0.09650]

trial_003 train e009:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.39it/s, avg=0.09512, loss=0.09650]

trial_003 train e009:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:10,  1.39it/s, avg=0.09516, loss=0.09965]

trial_003 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:35<00:10,  1.40it/s, avg=0.09516, loss=0.09965]

trial_003 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.40it/s, avg=0.09512, loss=0.08992]

trial_003 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:36<00:09,  1.39it/s, avg=0.09512, loss=0.08992]

trial_003 train e009:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.39it/s, avg=0.09511, loss=0.09444]

trial_003 train e009:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:37<00:08,  1.39it/s, avg=0.09511, loss=0.09444]

trial_003 train e009:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.39it/s, avg=0.09499, loss=0.07854]

trial_003 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:08,  1.37it/s, avg=0.09499, loss=0.07854]

trial_003 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:08,  1.37it/s, avg=0.09502, loss=0.09853]

trial_003 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:38<00:07,  1.38it/s, avg=0.09502, loss=0.09853]

trial_003 train e009:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.38it/s, avg=0.09492, loss=0.08166]

trial_003 train e009:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:39<00:06,  1.40it/s, avg=0.09492, loss=0.08166]

trial_003 train e009:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.40it/s, avg=0.09493, loss=0.09590]

trial_003 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:40<00:05,  1.38it/s, avg=0.09493, loss=0.09590]

trial_003 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.38it/s, avg=0.09493, loss=0.09486]

trial_003 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:05,  1.39it/s, avg=0.09493, loss=0.09486]

trial_003 train e009:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:05,  1.39it/s, avg=0.09489, loss=0.08876]

trial_003 train e009:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:41<00:04,  1.40it/s, avg=0.09489, loss=0.08876]

trial_003 train e009:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.40it/s, avg=0.09479, loss=0.08161]

trial_003 train e009:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:42<00:03,  1.37it/s, avg=0.09479, loss=0.08161]

trial_003 train e009:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.37it/s, avg=0.09478, loss=0.09208]

trial_003 train e009:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.39it/s, avg=0.09478, loss=0.09208]

trial_003 train e009:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.39it/s, avg=0.09479, loss=0.09741]

trial_003 train e009:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:43<00:02,  1.39it/s, avg=0.09479, loss=0.09741]

trial_003 train e009:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.39it/s, avg=0.09478, loss=0.09260]

trial_003 train e009:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:44<00:01,  1.37it/s, avg=0.09478, loss=0.09260]

trial_003 train e009:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.37it/s, avg=0.09485, loss=0.10504]

trial_003 train e009:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.41it/s, avg=0.09485, loss=0.10504]

trial_003 train e009:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.41it/s, avg=0.09483, loss=0.08931]

trial_003 train e009: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:45<00:00,  1.71it/s, avg=0.09483, loss=0.08931]

trial_003 val e009:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e009:   2%|██▌                                                                                                                          | 1/50 [00:00<00:19,  2.54it/s]

trial_003 val e009:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.46it/s]

trial_003 val e009:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:19,  2.45it/s]

trial_003 val e009:   8%|██████████                                                                                                                   | 4/50 [00:01<00:19,  2.39it/s]

trial_003 val e009:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.38it/s]

trial_003 val e009:  12%|███████████████                                                                                                              | 6/50 [00:02<00:18,  2.37it/s]

trial_003 val e009:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:18,  2.38it/s]

trial_003 val e009:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.40it/s]

trial_003 val e009:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.42it/s]

trial_003 val e009:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.44it/s]

trial_003 val e009:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:15,  2.45it/s]

trial_003 val e009:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.44it/s]

trial_003 val e009:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.42it/s]

trial_003 val e009:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:14,  2.41it/s]

trial_003 val e009:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.41it/s]

trial_003 val e009:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.42it/s]

trial_003 val e009:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.40it/s]

trial_003 val e009:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.40it/s]

trial_003 val e009:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.41it/s]

trial_003 val e009:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.42it/s]

trial_003 val e009:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.42it/s]

trial_003 val e009:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.41it/s]

trial_003 val e009:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.41it/s]

trial_003 val e009:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.42it/s]

trial_003 val e009:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.43it/s]

trial_003 val e009:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.44it/s]

trial_003 val e009:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.43it/s]

trial_003 val e009:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:09,  2.43it/s]

trial_003 val e009:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.43it/s]

trial_003 val e009:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.42it/s]

trial_003 val e009:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.39it/s]

trial_003 val e009:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.38it/s]

trial_003 val e009:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.39it/s]

trial_003 val e009:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.40it/s]

trial_003 val e009:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.40it/s]

trial_003 val e009:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.40it/s]

trial_003 val e009:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.40it/s]

trial_003 val e009:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.41it/s]

trial_003 val e009:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.42it/s]

trial_003 val e009:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.43it/s]

trial_003 val e009:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.43it/s]

trial_003 val e009:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.41it/s]

trial_003 val e009:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.40it/s]

trial_003 val e009:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.40it/s]

trial_003 val e009:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.40it/s]

trial_003 val e009:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:19<00:01,  2.40it/s]

trial_003 val e009:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.42it/s]

trial_003 val e009:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.44it/s]

trial_003 val e009:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.45it/s]

trial_003 val e009: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.46it/s]

[2026-05-28 21:23:57] [trial_003] epoch=009 | train_loss=0.094834 | val_MAE=0.097601 | val_S=0.902399 | best_S=0.902399 @epoch=9 | patience=0/5

[trial_003] epochs:   9%|██████████▉                                                                                                              | 9/100 [18:47<3:11:54, 126.53s/it]

trial_003 train e010:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e010:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08910, loss=0.08910]

trial_003 train e010:   1%|▋                                                                                              | 1/149 [00:00<01:39,  1.49it/s, avg=0.08910, loss=0.08910]

trial_003 train e010:   1%|▋                                                                                              | 1/149 [00:01<01:39,  1.49it/s, avg=0.09086, loss=0.09262]

trial_003 train e010:   1%|█▎                                                                                             | 2/149 [00:01<01:43,  1.42it/s, avg=0.09086, loss=0.09262]

trial_003 train e010:   1%|█▎                                                                                             | 2/149 [00:02<01:43,  1.42it/s, avg=0.08870, loss=0.08438]

trial_003 train e010:   2%|█▉                                                                                             | 3/149 [00:02<01:43,  1.41it/s, avg=0.08870, loss=0.08438]

trial_003 train e010:   2%|█▉                                                                                             | 3/149 [00:02<01:43,  1.41it/s, avg=0.08736, loss=0.08335]

trial_003 train e010:   3%|██▌                                                                                            | 4/149 [00:02<01:41,  1.42it/s, avg=0.08736, loss=0.08335]

trial_003 train e010:   3%|██▌                                                                                            | 4/149 [00:03<01:41,  1.42it/s, avg=0.08885, loss=0.09479]

trial_003 train e010:   3%|███▏                                                                                           | 5/149 [00:03<01:40,  1.43it/s, avg=0.08885, loss=0.09479]

trial_003 train e010:   3%|███▏                                                                                           | 5/149 [00:04<01:40,  1.43it/s, avg=0.09058, loss=0.09922]

trial_003 train e010:   4%|███▊                                                                                           | 6/149 [00:04<01:39,  1.44it/s, avg=0.09058, loss=0.09922]

trial_003 train e010:   4%|███▊                                                                                           | 6/149 [00:04<01:39,  1.44it/s, avg=0.08986, loss=0.08552]

trial_003 train e010:   5%|████▍                                                                                          | 7/149 [00:04<01:39,  1.42it/s, avg=0.08986, loss=0.08552]

trial_003 train e010:   5%|████▍                                                                                          | 7/149 [00:05<01:39,  1.42it/s, avg=0.09115, loss=0.10024]

trial_003 train e010:   5%|█████                                                                                          | 8/149 [00:05<01:40,  1.40it/s, avg=0.09115, loss=0.10024]

trial_003 train e010:   5%|█████                                                                                          | 8/149 [00:06<01:40,  1.40it/s, avg=0.09122, loss=0.09177]

trial_003 train e010:   6%|█████▋                                                                                         | 9/149 [00:06<01:39,  1.41it/s, avg=0.09122, loss=0.09177]

trial_003 train e010:   6%|█████▋                                                                                         | 9/149 [00:07<01:39,  1.41it/s, avg=0.09150, loss=0.09397]

trial_003 train e010:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.09150, loss=0.09397]

trial_003 train e010:   7%|██████▎                                                                                       | 10/149 [00:07<01:40,  1.38it/s, avg=0.09131, loss=0.08943]

trial_003 train e010:   7%|██████▉                                                                                       | 11/149 [00:07<01:42,  1.35it/s, avg=0.09131, loss=0.08943]

trial_003 train e010:   7%|██████▉                                                                                       | 11/149 [00:08<01:42,  1.35it/s, avg=0.09188, loss=0.09821]

trial_003 train e010:   8%|███████▌                                                                                      | 12/149 [00:08<01:39,  1.38it/s, avg=0.09188, loss=0.09821]

trial_003 train e010:   8%|███████▌                                                                                      | 12/149 [00:09<01:39,  1.38it/s, avg=0.09088, loss=0.07888]

trial_003 train e010:   9%|████████▏                                                                                     | 13/149 [00:09<01:39,  1.37it/s, avg=0.09088, loss=0.07888]

trial_003 train e010:   9%|████████▏                                                                                     | 13/149 [00:10<01:39,  1.37it/s, avg=0.09100, loss=0.09252]

trial_003 train e010:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.09100, loss=0.09252]

trial_003 train e010:   9%|████████▊                                                                                     | 14/149 [00:10<01:38,  1.37it/s, avg=0.09068, loss=0.08615]

trial_003 train e010:  10%|█████████▍                                                                                    | 15/149 [00:10<01:37,  1.38it/s, avg=0.09068, loss=0.08615]

trial_003 train e010:  10%|█████████▍                                                                                    | 15/149 [00:11<01:37,  1.38it/s, avg=0.09079, loss=0.09247]

trial_003 train e010:  11%|██████████                                                                                    | 16/149 [00:11<01:35,  1.39it/s, avg=0.09079, loss=0.09247]

trial_003 train e010:  11%|██████████                                                                                    | 16/149 [00:12<01:35,  1.39it/s, avg=0.09096, loss=0.09372]

trial_003 train e010:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.38it/s, avg=0.09096, loss=0.09372]

trial_003 train e010:  11%|██████████▋                                                                                   | 17/149 [00:12<01:35,  1.38it/s, avg=0.09120, loss=0.09520]

trial_003 train e010:  12%|███████████▎                                                                                  | 18/149 [00:12<01:35,  1.38it/s, avg=0.09120, loss=0.09520]

trial_003 train e010:  12%|███████████▎                                                                                  | 18/149 [00:13<01:35,  1.38it/s, avg=0.09089, loss=0.08541]

trial_003 train e010:  13%|███████████▉                                                                                  | 19/149 [00:13<01:35,  1.36it/s, avg=0.09089, loss=0.08541]

trial_003 train e010:  13%|███████████▉                                                                                  | 19/149 [00:14<01:35,  1.36it/s, avg=0.09117, loss=0.09651]

trial_003 train e010:  13%|████████████▌                                                                                 | 20/149 [00:14<01:35,  1.36it/s, avg=0.09117, loss=0.09651]

trial_003 train e010:  13%|████████████▌                                                                                 | 20/149 [00:15<01:35,  1.36it/s, avg=0.09209, loss=0.11040]

trial_003 train e010:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.38it/s, avg=0.09209, loss=0.11040]

trial_003 train e010:  14%|█████████████▏                                                                                | 21/149 [00:15<01:32,  1.38it/s, avg=0.09184, loss=0.08669]

trial_003 train e010:  15%|█████████████▉                                                                                | 22/149 [00:15<01:31,  1.38it/s, avg=0.09184, loss=0.08669]

trial_003 train e010:  15%|█████████████▉                                                                                | 22/149 [00:16<01:31,  1.38it/s, avg=0.09157, loss=0.08550]

trial_003 train e010:  15%|██████████████▌                                                                               | 23/149 [00:16<01:30,  1.39it/s, avg=0.09157, loss=0.08550]

trial_003 train e010:  15%|██████████████▌                                                                               | 23/149 [00:17<01:30,  1.39it/s, avg=0.09159, loss=0.09210]

trial_003 train e010:  16%|███████████████▏                                                                              | 24/149 [00:17<01:29,  1.39it/s, avg=0.09159, loss=0.09210]

trial_003 train e010:  16%|███████████████▏                                                                              | 24/149 [00:17<01:29,  1.39it/s, avg=0.09176, loss=0.09585]

trial_003 train e010:  17%|███████████████▊                                                                              | 25/149 [00:17<01:26,  1.43it/s, avg=0.09176, loss=0.09585]

trial_003 train e010:  17%|███████████████▊                                                                              | 25/149 [00:18<01:26,  1.43it/s, avg=0.09229, loss=0.10544]

trial_003 train e010:  17%|████████████████▍                                                                             | 26/149 [00:18<01:27,  1.40it/s, avg=0.09229, loss=0.10544]

trial_003 train e010:  17%|████████████████▍                                                                             | 26/149 [00:19<01:27,  1.40it/s, avg=0.09243, loss=0.09613]

trial_003 train e010:  18%|█████████████████                                                                             | 27/149 [00:19<01:28,  1.38it/s, avg=0.09243, loss=0.09613]

trial_003 train e010:  18%|█████████████████                                                                             | 27/149 [00:20<01:28,  1.38it/s, avg=0.09241, loss=0.09178]

trial_003 train e010:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:27,  1.39it/s, avg=0.09241, loss=0.09178]

trial_003 train e010:  19%|█████████████████▋                                                                            | 28/149 [00:20<01:27,  1.39it/s, avg=0.09304, loss=0.11075]

trial_003 train e010:  19%|██████████████████▎                                                                           | 29/149 [00:20<01:26,  1.39it/s, avg=0.09304, loss=0.11075]

trial_003 train e010:  19%|██████████████████▎                                                                           | 29/149 [00:21<01:26,  1.39it/s, avg=0.09329, loss=0.10074]

trial_003 train e010:  20%|██████████████████▉                                                                           | 30/149 [00:21<01:27,  1.37it/s, avg=0.09329, loss=0.10074]

trial_003 train e010:  20%|██████████████████▉                                                                           | 30/149 [00:22<01:27,  1.37it/s, avg=0.09314, loss=0.08836]

trial_003 train e010:  21%|███████████████████▌                                                                          | 31/149 [00:22<01:24,  1.40it/s, avg=0.09314, loss=0.08836]

trial_003 train e010:  21%|███████████████████▌                                                                          | 31/149 [00:23<01:24,  1.40it/s, avg=0.09355, loss=0.10643]

trial_003 train e010:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.39it/s, avg=0.09355, loss=0.10643]

trial_003 train e010:  21%|████████████████████▏                                                                         | 32/149 [00:23<01:24,  1.39it/s, avg=0.09325, loss=0.08366]

trial_003 train e010:  22%|████████████████████▊                                                                         | 33/149 [00:23<01:23,  1.39it/s, avg=0.09325, loss=0.08366]

trial_003 train e010:  22%|████████████████████▊                                                                         | 33/149 [00:24<01:23,  1.39it/s, avg=0.09360, loss=0.10495]

trial_003 train e010:  23%|█████████████████████▍                                                                        | 34/149 [00:24<01:20,  1.43it/s, avg=0.09360, loss=0.10495]

trial_003 train e010:  23%|█████████████████████▍                                                                        | 34/149 [00:25<01:20,  1.43it/s, avg=0.09310, loss=0.07627]

trial_003 train e010:  23%|██████████████████████                                                                        | 35/149 [00:25<01:20,  1.41it/s, avg=0.09310, loss=0.07627]

trial_003 train e010:  23%|██████████████████████                                                                        | 35/149 [00:25<01:20,  1.41it/s, avg=0.09313, loss=0.09413]

trial_003 train e010:  24%|██████████████████████▋                                                                       | 36/149 [00:25<01:19,  1.42it/s, avg=0.09313, loss=0.09413]

trial_003 train e010:  24%|██████████████████████▋                                                                       | 36/149 [00:26<01:19,  1.42it/s, avg=0.09320, loss=0.09571]

trial_003 train e010:  25%|███████████████████████▎                                                                      | 37/149 [00:26<01:20,  1.39it/s, avg=0.09320, loss=0.09571]

trial_003 train e010:  25%|███████████████████████▎                                                                      | 37/149 [00:27<01:20,  1.39it/s, avg=0.09349, loss=0.10408]

trial_003 train e010:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:19,  1.39it/s, avg=0.09349, loss=0.10408]

trial_003 train e010:  26%|███████████████████████▉                                                                      | 38/149 [00:27<01:19,  1.39it/s, avg=0.09321, loss=0.08293]

trial_003 train e010:  26%|████████████████████████▌                                                                     | 39/149 [00:27<01:18,  1.40it/s, avg=0.09321, loss=0.08293]

trial_003 train e010:  26%|████████████████████████▌                                                                     | 39/149 [00:28<01:18,  1.40it/s, avg=0.09327, loss=0.09558]

trial_003 train e010:  27%|█████████████████████████▏                                                                    | 40/149 [00:28<01:17,  1.41it/s, avg=0.09327, loss=0.09558]

trial_003 train e010:  27%|█████████████████████████▏                                                                    | 40/149 [00:29<01:17,  1.41it/s, avg=0.09329, loss=0.09396]

trial_003 train e010:  28%|█████████████████████████▊                                                                    | 41/149 [00:29<01:16,  1.41it/s, avg=0.09329, loss=0.09396]

trial_003 train e010:  28%|█████████████████████████▊                                                                    | 41/149 [00:30<01:16,  1.41it/s, avg=0.09322, loss=0.09020]

trial_003 train e010:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.39it/s, avg=0.09322, loss=0.09020]

trial_003 train e010:  28%|██████████████████████████▍                                                                   | 42/149 [00:30<01:17,  1.39it/s, avg=0.09332, loss=0.09775]

trial_003 train e010:  29%|███████████████████████████▏                                                                  | 43/149 [00:30<01:15,  1.40it/s, avg=0.09332, loss=0.09775]

trial_003 train e010:  29%|███████████████████████████▏                                                                  | 43/149 [00:31<01:15,  1.40it/s, avg=0.09355, loss=0.10335]

trial_003 train e010:  30%|███████████████████████████▊                                                                  | 44/149 [00:31<01:12,  1.44it/s, avg=0.09355, loss=0.10335]

trial_003 train e010:  30%|███████████████████████████▊                                                                  | 44/149 [00:32<01:12,  1.44it/s, avg=0.09316, loss=0.07611]

trial_003 train e010:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.09316, loss=0.07611]

trial_003 train e010:  30%|████████████████████████████▍                                                                 | 45/149 [00:32<01:13,  1.41it/s, avg=0.09303, loss=0.08717]

trial_003 train e010:  31%|█████████████████████████████                                                                 | 46/149 [00:32<01:11,  1.44it/s, avg=0.09303, loss=0.08717]

trial_003 train e010:  31%|█████████████████████████████                                                                 | 46/149 [00:33<01:11,  1.44it/s, avg=0.09288, loss=0.08567]

trial_003 train e010:  32%|█████████████████████████████▋                                                                | 47/149 [00:33<01:11,  1.43it/s, avg=0.09288, loss=0.08567]

trial_003 train e010:  32%|█████████████████████████████▋                                                                | 47/149 [00:34<01:11,  1.43it/s, avg=0.09298, loss=0.09805]

trial_003 train e010:  32%|██████████████████████████████▎                                                               | 48/149 [00:34<01:11,  1.41it/s, avg=0.09298, loss=0.09805]

trial_003 train e010:  32%|██████████████████████████████▎                                                               | 48/149 [00:35<01:11,  1.41it/s, avg=0.09309, loss=0.09819]

trial_003 train e010:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:11,  1.39it/s, avg=0.09309, loss=0.09819]

trial_003 train e010:  33%|██████████████████████████████▉                                                               | 49/149 [00:35<01:11,  1.39it/s, avg=0.09329, loss=0.10316]

trial_003 train e010:  34%|███████████████████████████████▌                                                              | 50/149 [00:35<01:09,  1.42it/s, avg=0.09329, loss=0.10316]

trial_003 train e010:  34%|███████████████████████████████▌                                                              | 50/149 [00:36<01:09,  1.42it/s, avg=0.09330, loss=0.09381]

trial_003 train e010:  34%|████████████████████████████████▏                                                             | 51/149 [00:36<01:09,  1.41it/s, avg=0.09330, loss=0.09381]

trial_003 train e010:  34%|████████████████████████████████▏                                                             | 51/149 [00:37<01:09,  1.41it/s, avg=0.09311, loss=0.08330]

trial_003 train e010:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:08,  1.41it/s, avg=0.09311, loss=0.08330]

trial_003 train e010:  35%|████████████████████████████████▊                                                             | 52/149 [00:37<01:08,  1.41it/s, avg=0.09328, loss=0.10196]

trial_003 train e010:  36%|█████████████████████████████████▍                                                            | 53/149 [00:37<01:07,  1.42it/s, avg=0.09328, loss=0.10196]

trial_003 train e010:  36%|█████████████████████████████████▍                                                            | 53/149 [00:38<01:07,  1.42it/s, avg=0.09315, loss=0.08669]

trial_003 train e010:  36%|██████████████████████████████████                                                            | 54/149 [00:38<01:07,  1.40it/s, avg=0.09315, loss=0.08669]

trial_003 train e010:  36%|██████████████████████████████████                                                            | 54/149 [00:39<01:07,  1.40it/s, avg=0.09324, loss=0.09800]

trial_003 train e010:  37%|██████████████████████████████████▋                                                           | 55/149 [00:39<01:07,  1.39it/s, avg=0.09324, loss=0.09800]

trial_003 train e010:  37%|██████████████████████████████████▋                                                           | 55/149 [00:40<01:07,  1.39it/s, avg=0.09313, loss=0.08687]

trial_003 train e010:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.39it/s, avg=0.09313, loss=0.08687]

trial_003 train e010:  38%|███████████████████████████████████▎                                                          | 56/149 [00:40<01:06,  1.39it/s, avg=0.09308, loss=0.09015]

trial_003 train e010:  38%|███████████████████████████████████▉                                                          | 57/149 [00:40<01:05,  1.41it/s, avg=0.09308, loss=0.09015]

trial_003 train e010:  38%|███████████████████████████████████▉                                                          | 57/149 [00:41<01:05,  1.41it/s, avg=0.09287, loss=0.08109]

trial_003 train e010:  39%|████████████████████████████████████▌                                                         | 58/149 [00:41<01:05,  1.38it/s, avg=0.09287, loss=0.08109]

trial_003 train e010:  39%|████████████████████████████████████▌                                                         | 58/149 [00:42<01:05,  1.38it/s, avg=0.09280, loss=0.08882]

trial_003 train e010:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:04,  1.40it/s, avg=0.09280, loss=0.08882]

trial_003 train e010:  40%|█████████████████████████████████████▏                                                        | 59/149 [00:42<01:04,  1.40it/s, avg=0.09256, loss=0.07819]

trial_003 train e010:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:42<01:03,  1.39it/s, avg=0.09256, loss=0.07819]

trial_003 train e010:  40%|█████████████████████████████████████▊                                                        | 60/149 [00:43<01:03,  1.39it/s, avg=0.09257, loss=0.09339]

trial_003 train e010:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:43<01:03,  1.38it/s, avg=0.09257, loss=0.09339]

trial_003 train e010:  41%|██████████████████████████████████████▍                                                       | 61/149 [00:44<01:03,  1.38it/s, avg=0.09271, loss=0.10134]

trial_003 train e010:  42%|███████████████████████████████████████                                                       | 62/149 [00:44<01:02,  1.39it/s, avg=0.09271, loss=0.10134]

trial_003 train e010:  42%|███████████████████████████████████████                                                       | 62/149 [00:45<01:02,  1.39it/s, avg=0.09288, loss=0.10340]

trial_003 train e010:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:02,  1.37it/s, avg=0.09288, loss=0.10340]

trial_003 train e010:  42%|███████████████████████████████████████▋                                                      | 63/149 [00:45<01:02,  1.37it/s, avg=0.09297, loss=0.09836]

trial_003 train e010:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:45<01:01,  1.39it/s, avg=0.09297, loss=0.09836]

trial_003 train e010:  43%|████████████████████████████████████████▍                                                     | 64/149 [00:46<01:01,  1.39it/s, avg=0.09281, loss=0.08286]

trial_003 train e010:  44%|█████████████████████████████████████████                                                     | 65/149 [00:46<01:00,  1.39it/s, avg=0.09281, loss=0.08286]

trial_003 train e010:  44%|█████████████████████████████████████████                                                     | 65/149 [00:47<01:00,  1.39it/s, avg=0.09276, loss=0.08970]

trial_003 train e010:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:47<01:00,  1.38it/s, avg=0.09276, loss=0.08970]

trial_003 train e010:  44%|█████████████████████████████████████████▋                                                    | 66/149 [00:48<01:00,  1.38it/s, avg=0.09301, loss=0.10942]

trial_003 train e010:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<01:00,  1.36it/s, avg=0.09301, loss=0.10942]

trial_003 train e010:  45%|██████████████████████████████████████████▎                                                   | 67/149 [00:48<01:00,  1.36it/s, avg=0.09292, loss=0.08677]

trial_003 train e010:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:48<01:00,  1.35it/s, avg=0.09292, loss=0.08677]

trial_003 train e010:  46%|██████████████████████████████████████████▉                                                   | 68/149 [00:49<01:00,  1.35it/s, avg=0.09308, loss=0.10409]

trial_003 train e010:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:49<00:57,  1.39it/s, avg=0.09308, loss=0.10409]

trial_003 train e010:  46%|███████████████████████████████████████████▌                                                  | 69/149 [00:50<00:57,  1.39it/s, avg=0.09339, loss=0.11460]

trial_003 train e010:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.39it/s, avg=0.09339, loss=0.11460]

trial_003 train e010:  47%|████████████████████████████████████████████▏                                                 | 70/149 [00:50<00:56,  1.39it/s, avg=0.09327, loss=0.08508]

trial_003 train e010:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:50<00:56,  1.38it/s, avg=0.09327, loss=0.08508]

trial_003 train e010:  48%|████████████████████████████████████████████▊                                                 | 71/149 [00:51<00:56,  1.38it/s, avg=0.09324, loss=0.09068]

trial_003 train e010:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:51<00:55,  1.39it/s, avg=0.09324, loss=0.09068]

trial_003 train e010:  48%|█████████████████████████████████████████████▍                                                | 72/149 [00:52<00:55,  1.39it/s, avg=0.09320, loss=0.09013]

trial_003 train e010:  49%|██████████████████████████████████████████████                                                | 73/149 [00:52<00:54,  1.39it/s, avg=0.09320, loss=0.09013]

trial_003 train e010:  49%|██████████████████████████████████████████████                                                | 73/149 [00:53<00:54,  1.39it/s, avg=0.09314, loss=0.08946]

trial_003 train e010:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.39it/s, avg=0.09314, loss=0.08946]

trial_003 train e010:  50%|██████████████████████████████████████████████▋                                               | 74/149 [00:53<00:53,  1.39it/s, avg=0.09308, loss=0.08813]

trial_003 train e010:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:53<00:52,  1.40it/s, avg=0.09308, loss=0.08813]

trial_003 train e010:  50%|███████████████████████████████████████████████▎                                              | 75/149 [00:54<00:52,  1.40it/s, avg=0.09312, loss=0.09649]

trial_003 train e010:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:54<00:51,  1.42it/s, avg=0.09312, loss=0.09649]

trial_003 train e010:  51%|███████████████████████████████████████████████▉                                              | 76/149 [00:55<00:51,  1.42it/s, avg=0.09314, loss=0.09457]

trial_003 train e010:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:51,  1.40it/s, avg=0.09314, loss=0.09457]

trial_003 train e010:  52%|████████████████████████████████████████████████▌                                             | 77/149 [00:55<00:51,  1.40it/s, avg=0.09301, loss=0.08250]

trial_003 train e010:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:55<00:52,  1.37it/s, avg=0.09301, loss=0.08250]

trial_003 train e010:  52%|█████████████████████████████████████████████████▏                                            | 78/149 [00:56<00:52,  1.37it/s, avg=0.09307, loss=0.09805]

trial_003 train e010:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:56<00:49,  1.41it/s, avg=0.09307, loss=0.09805]

trial_003 train e010:  53%|█████████████████████████████████████████████████▊                                            | 79/149 [00:57<00:49,  1.41it/s, avg=0.09298, loss=0.08581]

trial_003 train e010:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:57<00:48,  1.42it/s, avg=0.09298, loss=0.08581]

trial_003 train e010:  54%|██████████████████████████████████████████████████▍                                           | 80/149 [00:58<00:48,  1.42it/s, avg=0.09290, loss=0.08697]

trial_003 train e010:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:47,  1.43it/s, avg=0.09290, loss=0.08697]

trial_003 train e010:  54%|███████████████████████████████████████████████████                                           | 81/149 [00:58<00:47,  1.43it/s, avg=0.09313, loss=0.11103]

trial_003 train e010:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:58<00:46,  1.45it/s, avg=0.09313, loss=0.11103]

trial_003 train e010:  55%|███████████████████████████████████████████████████▋                                          | 82/149 [00:59<00:46,  1.45it/s, avg=0.09302, loss=0.08414]

trial_003 train e010:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [00:59<00:46,  1.41it/s, avg=0.09302, loss=0.08414]

trial_003 train e010:  56%|████████████████████████████████████████████████████▎                                         | 83/149 [01:00<00:46,  1.41it/s, avg=0.09299, loss=0.09113]

trial_003 train e010:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:46,  1.38it/s, avg=0.09299, loss=0.09113]

trial_003 train e010:  56%|████████████████████████████████████████████████████▉                                         | 84/149 [01:00<00:46,  1.38it/s, avg=0.09298, loss=0.09216]

trial_003 train e010:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:00<00:46,  1.39it/s, avg=0.09298, loss=0.09216]

trial_003 train e010:  57%|█████████████████████████████████████████████████████▌                                        | 85/149 [01:01<00:46,  1.39it/s, avg=0.09298, loss=0.09278]

trial_003 train e010:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:01<00:45,  1.38it/s, avg=0.09298, loss=0.09278]

trial_003 train e010:  58%|██████████████████████████████████████████████████████▎                                       | 86/149 [01:02<00:45,  1.38it/s, avg=0.09308, loss=0.10118]

trial_003 train e010:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:02<00:44,  1.40it/s, avg=0.09308, loss=0.10118]

trial_003 train e010:  58%|██████████████████████████████████████████████████████▉                                       | 87/149 [01:03<00:44,  1.40it/s, avg=0.09305, loss=0.09084]

trial_003 train e010:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.40it/s, avg=0.09305, loss=0.09084]

trial_003 train e010:  59%|███████████████████████████████████████████████████████▌                                      | 88/149 [01:03<00:43,  1.40it/s, avg=0.09312, loss=0.09903]

trial_003 train e010:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:03<00:42,  1.40it/s, avg=0.09312, loss=0.09903]

trial_003 train e010:  60%|████████████████████████████████████████████████████████▏                                     | 89/149 [01:04<00:42,  1.40it/s, avg=0.09323, loss=0.10343]

trial_003 train e010:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:04<00:42,  1.38it/s, avg=0.09323, loss=0.10343]

trial_003 train e010:  60%|████████████████████████████████████████████████████████▊                                     | 90/149 [01:05<00:42,  1.38it/s, avg=0.09325, loss=0.09500]

trial_003 train e010:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:41,  1.39it/s, avg=0.09325, loss=0.09500]

trial_003 train e010:  61%|█████████████████████████████████████████████████████████▍                                    | 91/149 [01:05<00:41,  1.39it/s, avg=0.09333, loss=0.10061]

trial_003 train e010:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:05<00:41,  1.39it/s, avg=0.09333, loss=0.10061]

trial_003 train e010:  62%|██████████████████████████████████████████████████████████                                    | 92/149 [01:06<00:41,  1.39it/s, avg=0.09343, loss=0.10250]

trial_003 train e010:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:06<00:40,  1.37it/s, avg=0.09343, loss=0.10250]

trial_003 train e010:  62%|██████████████████████████████████████████████████████████▋                                   | 93/149 [01:07<00:40,  1.37it/s, avg=0.09334, loss=0.08534]

trial_003 train e010:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:07<00:39,  1.38it/s, avg=0.09334, loss=0.08534]

trial_003 train e010:  63%|███████████████████████████████████████████████████████████▎                                  | 94/149 [01:08<00:39,  1.38it/s, avg=0.09343, loss=0.10133]

trial_003 train e010:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:38,  1.41it/s, avg=0.09343, loss=0.10133]

trial_003 train e010:  64%|███████████████████████████████████████████████████████████▉                                  | 95/149 [01:08<00:38,  1.41it/s, avg=0.09345, loss=0.09545]

trial_003 train e010:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:08<00:37,  1.41it/s, avg=0.09345, loss=0.09545]

trial_003 train e010:  64%|████████████████████████████████████████████████████████████▌                                 | 96/149 [01:09<00:37,  1.41it/s, avg=0.09348, loss=0.09650]

trial_003 train e010:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:09<00:37,  1.40it/s, avg=0.09348, loss=0.09650]

trial_003 train e010:  65%|█████████████████████████████████████████████████████████████▏                                | 97/149 [01:10<00:37,  1.40it/s, avg=0.09345, loss=0.09026]

trial_003 train e010:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.39it/s, avg=0.09345, loss=0.09026]

trial_003 train e010:  66%|█████████████████████████████████████████████████████████████▊                                | 98/149 [01:10<00:36,  1.39it/s, avg=0.09335, loss=0.08334]

trial_003 train e010:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:10<00:35,  1.40it/s, avg=0.09335, loss=0.08334]

trial_003 train e010:  66%|██████████████████████████████████████████████████████████████▍                               | 99/149 [01:11<00:35,  1.40it/s, avg=0.09314, loss=0.07281]

trial_003 train e010:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:11<00:35,  1.38it/s, avg=0.09314, loss=0.07281]

trial_003 train e010:  67%|██████████████████████████████████████████████████████████████▍                              | 100/149 [01:12<00:35,  1.38it/s, avg=0.09312, loss=0.09062]

trial_003 train e010:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:12<00:34,  1.38it/s, avg=0.09312, loss=0.09062]

trial_003 train e010:  68%|███████████████████████████████████████████████████████████████                              | 101/149 [01:13<00:34,  1.38it/s, avg=0.09303, loss=0.08395]

trial_003 train e010:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:34,  1.38it/s, avg=0.09303, loss=0.08395]

trial_003 train e010:  68%|███████████████████████████████████████████████████████████████▋                             | 102/149 [01:13<00:34,  1.38it/s, avg=0.09303, loss=0.09293]

trial_003 train e010:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:13<00:32,  1.39it/s, avg=0.09303, loss=0.09293]

trial_003 train e010:  69%|████████████████████████████████████████████████████████████████▎                            | 103/149 [01:14<00:32,  1.39it/s, avg=0.09297, loss=0.08681]

trial_003 train e010:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:14<00:32,  1.38it/s, avg=0.09297, loss=0.08681]

trial_003 train e010:  70%|████████████████████████████████████████████████████████████████▉                            | 104/149 [01:15<00:32,  1.38it/s, avg=0.09300, loss=0.09647]

trial_003 train e010:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.40it/s, avg=0.09300, loss=0.09647]

trial_003 train e010:  70%|█████████████████████████████████████████████████████████████████▌                           | 105/149 [01:15<00:31,  1.40it/s, avg=0.09295, loss=0.08790]

trial_003 train e010:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:15<00:30,  1.43it/s, avg=0.09295, loss=0.08790]

trial_003 train e010:  71%|██████████████████████████████████████████████████████████████████▏                          | 106/149 [01:16<00:30,  1.43it/s, avg=0.09287, loss=0.08398]

trial_003 train e010:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:16<00:29,  1.40it/s, avg=0.09287, loss=0.08398]

trial_003 train e010:  72%|██████████████████████████████████████████████████████████████████▊                          | 107/149 [01:17<00:29,  1.40it/s, avg=0.09286, loss=0.09263]

trial_003 train e010:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:17<00:29,  1.41it/s, avg=0.09286, loss=0.09263]

trial_003 train e010:  72%|███████████████████████████████████████████████████████████████████▍                         | 108/149 [01:18<00:29,  1.41it/s, avg=0.09283, loss=0.08947]

trial_003 train e010:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:28,  1.41it/s, avg=0.09283, loss=0.08947]

trial_003 train e010:  73%|████████████████████████████████████████████████████████████████████                         | 109/149 [01:18<00:28,  1.41it/s, avg=0.09287, loss=0.09635]

trial_003 train e010:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:18<00:27,  1.42it/s, avg=0.09287, loss=0.09635]

trial_003 train e010:  74%|████████████████████████████████████████████████████████████████████▋                        | 110/149 [01:19<00:27,  1.42it/s, avg=0.09286, loss=0.09186]

trial_003 train e010:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:19<00:26,  1.42it/s, avg=0.09286, loss=0.09186]

trial_003 train e010:  74%|█████████████████████████████████████████████████████████████████████▎                       | 111/149 [01:20<00:26,  1.42it/s, avg=0.09286, loss=0.09322]

trial_003 train e010:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.41it/s, avg=0.09286, loss=0.09322]

trial_003 train e010:  75%|█████████████████████████████████████████████████████████████████████▉                       | 112/149 [01:20<00:26,  1.41it/s, avg=0.09280, loss=0.08615]

trial_003 train e010:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:20<00:25,  1.41it/s, avg=0.09280, loss=0.08615]

trial_003 train e010:  76%|██████████████████████████████████████████████████████████████████████▌                      | 113/149 [01:21<00:25,  1.41it/s, avg=0.09274, loss=0.08589]

trial_003 train e010:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:21<00:24,  1.41it/s, avg=0.09274, loss=0.08589]

trial_003 train e010:  77%|███████████████████████████████████████████████████████████████████████▏                     | 114/149 [01:22<00:24,  1.41it/s, avg=0.09273, loss=0.09118]

trial_003 train e010:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:23,  1.46it/s, avg=0.09273, loss=0.09118]

trial_003 train e010:  77%|███████████████████████████████████████████████████████████████████████▊                     | 115/149 [01:22<00:23,  1.46it/s, avg=0.09263, loss=0.08168]

trial_003 train e010:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:22<00:22,  1.44it/s, avg=0.09263, loss=0.08168]

trial_003 train e010:  78%|████████████████████████████████████████████████████████████████████████▍                    | 116/149 [01:23<00:22,  1.44it/s, avg=0.09271, loss=0.10219]

trial_003 train e010:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:23<00:22,  1.42it/s, avg=0.09271, loss=0.10219]

trial_003 train e010:  79%|█████████████████████████████████████████████████████████████████████████                    | 117/149 [01:24<00:22,  1.42it/s, avg=0.09266, loss=0.08651]

trial_003 train e010:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:24<00:21,  1.41it/s, avg=0.09266, loss=0.08651]

trial_003 train e010:  79%|█████████████████████████████████████████████████████████████████████████▋                   | 118/149 [01:25<00:21,  1.41it/s, avg=0.09258, loss=0.08304]

trial_003 train e010:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.41it/s, avg=0.09258, loss=0.08304]

trial_003 train e010:  80%|██████████████████████████████████████████████████████████████████████████▎                  | 119/149 [01:25<00:21,  1.41it/s, avg=0.09268, loss=0.10521]

trial_003 train e010:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:25<00:19,  1.45it/s, avg=0.09268, loss=0.10521]

trial_003 train e010:  81%|██████████████████████████████████████████████████████████████████████████▉                  | 120/149 [01:26<00:19,  1.45it/s, avg=0.09271, loss=0.09534]

trial_003 train e010:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:26<00:19,  1.45it/s, avg=0.09271, loss=0.09534]

trial_003 train e010:  81%|███████████████████████████████████████████████████████████████████████████▌                 | 121/149 [01:27<00:19,  1.45it/s, avg=0.09276, loss=0.09904]

trial_003 train e010:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.42it/s, avg=0.09276, loss=0.09904]

trial_003 train e010:  82%|████████████████████████████████████████████████████████████████████████████▏                | 122/149 [01:27<00:19,  1.42it/s, avg=0.09287, loss=0.10657]

trial_003 train e010:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:27<00:18,  1.42it/s, avg=0.09287, loss=0.10657]

trial_003 train e010:  83%|████████████████████████████████████████████████████████████████████████████▊                | 123/149 [01:28<00:18,  1.42it/s, avg=0.09279, loss=0.08244]

trial_003 train e010:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:28<00:17,  1.42it/s, avg=0.09279, loss=0.08244]

trial_003 train e010:  83%|█████████████████████████████████████████████████████████████████████████████▍               | 124/149 [01:29<00:17,  1.42it/s, avg=0.09267, loss=0.07884]

trial_003 train e010:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:29<00:17,  1.40it/s, avg=0.09267, loss=0.07884]

trial_003 train e010:  84%|██████████████████████████████████████████████████████████████████████████████               | 125/149 [01:30<00:17,  1.40it/s, avg=0.09266, loss=0.09042]

trial_003 train e010:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.38it/s, avg=0.09266, loss=0.09042]

trial_003 train e010:  85%|██████████████████████████████████████████████████████████████████████████████▋              | 126/149 [01:30<00:16,  1.38it/s, avg=0.09271, loss=0.09921]

trial_003 train e010:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:30<00:16,  1.37it/s, avg=0.09271, loss=0.09921]

trial_003 train e010:  85%|███████████████████████████████████████████████████████████████████████████████▎             | 127/149 [01:31<00:16,  1.37it/s, avg=0.09278, loss=0.10242]

trial_003 train e010:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:31<00:15,  1.40it/s, avg=0.09278, loss=0.10242]

trial_003 train e010:  86%|███████████████████████████████████████████████████████████████████████████████▉             | 128/149 [01:32<00:15,  1.40it/s, avg=0.09266, loss=0.07675]

trial_003 train e010:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.38it/s, avg=0.09266, loss=0.07675]

trial_003 train e010:  87%|████████████████████████████████████████████████████████████████████████████████▌            | 129/149 [01:32<00:14,  1.38it/s, avg=0.09266, loss=0.09255]

trial_003 train e010:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:32<00:13,  1.39it/s, avg=0.09266, loss=0.09255]

trial_003 train e010:  87%|█████████████████████████████████████████████████████████████████████████████████▏           | 130/149 [01:33<00:13,  1.39it/s, avg=0.09264, loss=0.09026]

trial_003 train e010:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:33<00:13,  1.37it/s, avg=0.09264, loss=0.09026]

trial_003 train e010:  88%|█████████████████████████████████████████████████████████████████████████████████▊           | 131/149 [01:34<00:13,  1.37it/s, avg=0.09269, loss=0.09914]

trial_003 train e010:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:34<00:12,  1.38it/s, avg=0.09269, loss=0.09914]

trial_003 train e010:  89%|██████████████████████████████████████████████████████████████████████████████████▍          | 132/149 [01:35<00:12,  1.38it/s, avg=0.09263, loss=0.08450]

trial_003 train e010:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.36it/s, avg=0.09263, loss=0.08450]

trial_003 train e010:  89%|███████████████████████████████████████████████████████████████████████████████████          | 133/149 [01:35<00:11,  1.36it/s, avg=0.09266, loss=0.09695]

trial_003 train e010:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:35<00:11,  1.36it/s, avg=0.09266, loss=0.09695]

trial_003 train e010:  90%|███████████████████████████████████████████████████████████████████████████████████▋         | 134/149 [01:36<00:11,  1.36it/s, avg=0.09264, loss=0.08949]

trial_003 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:36<00:10,  1.37it/s, avg=0.09264, loss=0.08949]

trial_003 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▎        | 135/149 [01:37<00:10,  1.37it/s, avg=0.09257, loss=0.08371]

trial_003 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:37<00:09,  1.39it/s, avg=0.09257, loss=0.08371]

trial_003 train e010:  91%|████████████████████████████████████████████████████████████████████████████████████▉        | 136/149 [01:38<00:09,  1.39it/s, avg=0.09257, loss=0.09219]

trial_003 train e010:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.39it/s, avg=0.09257, loss=0.09219]

trial_003 train e010:  92%|█████████████████████████████████████████████████████████████████████████████████████▌       | 137/149 [01:38<00:08,  1.39it/s, avg=0.09252, loss=0.08531]

trial_003 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:38<00:08,  1.36it/s, avg=0.09252, loss=0.08531]

trial_003 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▏      | 138/149 [01:39<00:08,  1.36it/s, avg=0.09249, loss=0.08833]

trial_003 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:39<00:07,  1.36it/s, avg=0.09249, loss=0.08833]

trial_003 train e010:  93%|██████████████████████████████████████████████████████████████████████████████████████▊      | 139/149 [01:40<00:07,  1.36it/s, avg=0.09254, loss=0.09979]

trial_003 train e010:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.36it/s, avg=0.09254, loss=0.09979]

trial_003 train e010:  94%|███████████████████████████████████████████████████████████████████████████████████████▍     | 140/149 [01:40<00:06,  1.36it/s, avg=0.09257, loss=0.09663]

trial_003 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:40<00:05,  1.40it/s, avg=0.09257, loss=0.09663]

trial_003 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████     | 141/149 [01:41<00:05,  1.40it/s, avg=0.09252, loss=0.08606]

trial_003 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:41<00:04,  1.41it/s, avg=0.09252, loss=0.08606]

trial_003 train e010:  95%|████████████████████████████████████████████████████████████████████████████████████████▋    | 142/149 [01:42<00:04,  1.41it/s, avg=0.09253, loss=0.09438]

trial_003 train e010:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:42<00:04,  1.42it/s, avg=0.09253, loss=0.09438]

trial_003 train e010:  96%|█████████████████████████████████████████████████████████████████████████████████████████▎   | 143/149 [01:43<00:04,  1.42it/s, avg=0.09255, loss=0.09416]

trial_003 train e010:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.40it/s, avg=0.09255, loss=0.09416]

trial_003 train e010:  97%|█████████████████████████████████████████████████████████████████████████████████████████▉   | 144/149 [01:43<00:03,  1.40it/s, avg=0.09259, loss=0.09862]

trial_003 train e010:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:43<00:02,  1.43it/s, avg=0.09259, loss=0.09862]

trial_003 train e010:  97%|██████████████████████████████████████████████████████████████████████████████████████████▌  | 145/149 [01:44<00:02,  1.43it/s, avg=0.09261, loss=0.09621]

trial_003 train e010:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:44<00:02,  1.39it/s, avg=0.09261, loss=0.09621]

trial_003 train e010:  98%|███████████████████████████████████████████████████████████████████████████████████████████▏ | 146/149 [01:45<00:02,  1.39it/s, avg=0.09264, loss=0.09684]

trial_003 train e010:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.39it/s, avg=0.09264, loss=0.09684]

trial_003 train e010:  99%|███████████████████████████████████████████████████████████████████████████████████████████▊ | 147/149 [01:45<00:01,  1.39it/s, avg=0.09263, loss=0.09135]

trial_003 train e010:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:45<00:00,  1.39it/s, avg=0.09263, loss=0.09135]

trial_003 train e010:  99%|████████████████████████████████████████████████████████████████████████████████████████████▍| 148/149 [01:46<00:00,  1.39it/s, avg=0.09268, loss=0.11032]

trial_003 train e010: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 149/149 [01:46<00:00,  1.68it/s, avg=0.09268, loss=0.11032]

trial_003 val e010:   0%|                                                                                                                                     | 0/50 [00:00<?, ?it/s]

trial_003 val e010:   2%|██▌                                                                                                                          | 1/50 [00:00<00:18,  2.59it/s]

trial_003 val e010:   4%|█████                                                                                                                        | 2/50 [00:00<00:19,  2.50it/s]

trial_003 val e010:   6%|███████▌                                                                                                                     | 3/50 [00:01<00:18,  2.49it/s]

trial_003 val e010:   8%|██████████                                                                                                                   | 4/50 [00:01<00:18,  2.48it/s]

trial_003 val e010:  10%|████████████▌                                                                                                                | 5/50 [00:02<00:18,  2.48it/s]

trial_003 val e010:  12%|███████████████                                                                                                              | 6/50 [00:02<00:17,  2.47it/s]

trial_003 val e010:  14%|█████████████████▌                                                                                                           | 7/50 [00:02<00:17,  2.47it/s]

trial_003 val e010:  16%|████████████████████                                                                                                         | 8/50 [00:03<00:17,  2.46it/s]

trial_003 val e010:  18%|██████████████████████▌                                                                                                      | 9/50 [00:03<00:16,  2.43it/s]

trial_003 val e010:  20%|████████████████████████▊                                                                                                   | 10/50 [00:04<00:16,  2.40it/s]

trial_003 val e010:  22%|███████████████████████████▎                                                                                                | 11/50 [00:04<00:16,  2.36it/s]

trial_003 val e010:  24%|█████████████████████████████▊                                                                                              | 12/50 [00:04<00:15,  2.38it/s]

trial_003 val e010:  26%|████████████████████████████████▏                                                                                           | 13/50 [00:05<00:15,  2.35it/s]

trial_003 val e010:  28%|██████████████████████████████████▋                                                                                         | 14/50 [00:05<00:15,  2.35it/s]

trial_003 val e010:  30%|█████████████████████████████████████▏                                                                                      | 15/50 [00:06<00:14,  2.38it/s]

trial_003 val e010:  32%|███████████████████████████████████████▋                                                                                    | 16/50 [00:06<00:14,  2.40it/s]

trial_003 val e010:  34%|██████████████████████████████████████████▏                                                                                 | 17/50 [00:07<00:13,  2.40it/s]

trial_003 val e010:  36%|████████████████████████████████████████████▋                                                                               | 18/50 [00:07<00:13,  2.37it/s]

trial_003 val e010:  38%|███████████████████████████████████████████████                                                                             | 19/50 [00:07<00:12,  2.39it/s]

trial_003 val e010:  40%|█████████████████████████████████████████████████▌                                                                          | 20/50 [00:08<00:12,  2.42it/s]

trial_003 val e010:  42%|████████████████████████████████████████████████████                                                                        | 21/50 [00:08<00:11,  2.43it/s]

trial_003 val e010:  44%|██████████████████████████████████████████████████████▌                                                                     | 22/50 [00:09<00:11,  2.44it/s]

trial_003 val e010:  46%|█████████████████████████████████████████████████████████                                                                   | 23/50 [00:09<00:11,  2.45it/s]

trial_003 val e010:  48%|███████████████████████████████████████████████████████████▌                                                                | 24/50 [00:09<00:10,  2.42it/s]

trial_003 val e010:  50%|██████████████████████████████████████████████████████████████                                                              | 25/50 [00:10<00:10,  2.42it/s]

trial_003 val e010:  52%|████████████████████████████████████████████████████████████████▍                                                           | 26/50 [00:10<00:09,  2.45it/s]

trial_003 val e010:  54%|██████████████████████████████████████████████████████████████████▉                                                         | 27/50 [00:11<00:09,  2.47it/s]

trial_003 val e010:  56%|█████████████████████████████████████████████████████████████████████▍                                                      | 28/50 [00:11<00:08,  2.47it/s]

trial_003 val e010:  58%|███████████████████████████████████████████████████████████████████████▉                                                    | 29/50 [00:11<00:08,  2.49it/s]

trial_003 val e010:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 30/50 [00:12<00:08,  2.48it/s]

trial_003 val e010:  62%|████████████████████████████████████████████████████████████████████████████▉                                               | 31/50 [00:12<00:07,  2.46it/s]

trial_003 val e010:  64%|███████████████████████████████████████████████████████████████████████████████▎                                            | 32/50 [00:13<00:07,  2.45it/s]

trial_003 val e010:  66%|█████████████████████████████████████████████████████████████████████████████████▊                                          | 33/50 [00:13<00:07,  2.39it/s]

trial_003 val e010:  68%|████████████████████████████████████████████████████████████████████████████████████▎                                       | 34/50 [00:14<00:06,  2.41it/s]

trial_003 val e010:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 35/50 [00:14<00:06,  2.41it/s]

trial_003 val e010:  72%|█████████████████████████████████████████████████████████████████████████████████████████▎                                  | 36/50 [00:14<00:05,  2.44it/s]

trial_003 val e010:  74%|███████████████████████████████████████████████████████████████████████████████████████████▊                                | 37/50 [00:15<00:05,  2.40it/s]

trial_003 val e010:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▏                             | 38/50 [00:15<00:04,  2.41it/s]

trial_003 val e010:  78%|████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 39/50 [00:16<00:04,  2.40it/s]

trial_003 val e010:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 40/50 [00:16<00:04,  2.40it/s]

trial_003 val e010:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                      | 41/50 [00:16<00:03,  2.41it/s]

trial_003 val e010:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 42/50 [00:17<00:03,  2.42it/s]

trial_003 val e010:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 43/50 [00:17<00:02,  2.43it/s]

trial_003 val e010:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 44/50 [00:18<00:02,  2.46it/s]

trial_003 val e010:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 45/50 [00:18<00:02,  2.47it/s]

trial_003 val e010:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 46/50 [00:18<00:01,  2.47it/s]

trial_003 val e010:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 47/50 [00:19<00:01,  2.46it/s]

trial_003 val e010:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 48/50 [00:19<00:00,  2.47it/s]

trial_003 val e010:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 49/50 [00:20<00:00,  2.47it/s]

trial_003 val e010: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.48it/s]

[2026-05-28 21:26:04] [trial_003] epoch=010 | train_loss=0.092680 | val_MAE=0.098865 | val_S=0.901135 | best_S=0.902399 @epoch=9 | patience=1/5

[trial_003] epochs:  10%|████████████                                                                                                            | 10/100 [20:54<3:10:00, 126.67s/it]

trial_003 train e011:   0%|                                                                                                                                  | 0/149 [00:00<?, ?it/s]

trial_003 train e011:   0%|                                                                                                       | 0/149 [00:00<?, ?it/s, avg=0.08218, loss=0.08218]

trial_003 train e011:   1%|▋                                                                                              | 1/149 [00:00<01:53,  1.31it/s, avg=0.08218, loss=0.08218]

trial_003 train e011:   1%|▋                                                                                              | 1/149 [00:01<01:53,  1.31it/s, avg=0.09076, loss=0.09934]

trial_003 train e011:   1%|█▎                                                                                             | 2/149 [00:01<01:48,  1.36it/s, avg=0.09076, loss=0.09934]

trial_003 train e011:   1%|█▎                                                                                             | 2/149 [00:02<01:48,  1.36it/s, avg=0.09241, loss=0.09570]

trial_003 train e011:   2%|█▉                                                                                             | 3/149 [00:02<01:44,  1.39it/s, avg=0.09241, loss=0.09570]

trial_003 train e011:   2%|█▉                                                                                             | 3/149 [00:02<01:44,  1.39it/s, avg=0.09460, loss=0.10116]

trial_003 train e011:   3%|██▌                                                                                            | 4/149 [00:02<01:43,  1.40it/s, avg=0.09460, loss=0.10116]

trial_003 train e011:   3%|██▌                                                                                            | 4/149 [00:03<01:43,  1.40it/s, avg=0.09320, loss=0.08760]

trial_003 train e011:   3%|███▏                                                                                           | 5/149 [00:03<01:44,  1.38it/s, avg=0.09320, loss=0.08760]

trial_003 train e011:   3%|███▏                                                                                           | 5/149 [00:04<01:44,  1.38it/s, avg=0.09532, loss=0.10595]

trial_003 train e011:   4%|███▊                                                                                           | 6/149 [00:04<01:40,  1.42it/s, avg=0.09532, loss=0.10595]

trial_003 train e011:   4%|███▊                                                                                           | 6/149 [00:05<01:40,  1.42it/s, avg=0.09517, loss=0.09424]

trial_003 train e011:   5%|████▍                                                                                          | 7/149 [00:05<01:41,  1.40it/s, avg=0.09517, loss=0.09424]

trial_003 train e011:   5%|████▍                                                                                          | 7/149 [00:05<01:41,  1.40it/s, avg=0.09660, loss=0.10661]

trial_003 train e011:   5%|█████                                                                                          | 8/149 [00:05<01:40,  1.40it/s, avg=0.09660, loss=0.10661]

trial_003 train e011:   5%|█████                                                                                          | 8/149 [00:06<01:40,  1.40it/s, avg=0.09531, loss=0.08499]

trial_003 train e011:   6%|█████▋                                                                                         | 9/149 [00:06<01:40,  1.40it/s, avg=0.09531, loss=0.08499]

trial_003 train e011:   6%|█████▋                                                                                         | 9/149 [00:07<01:40,  1.40it/s, avg=0.09474, loss=0.08962]

trial_003 train e011:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.09474, loss=0.08962]

trial_003 train e011:   7%|██████▎                                                                                       | 10/149 [00:07<01:39,  1.40it/s, avg=0.09422, loss=0.08903]

trial_003 train e011:   7%|██████▉                                                                                       | 11/149 [00:07<01:38,  1.40it/s, avg=0.09422, loss=0.08903]

trial_003 train e011:   7%|██████▉                                                                                       | 11/149 [00:08<01:38,  1.40it/s, avg=0.09342, loss=0.08464]

trial_003 train e011:   8%|███████▌                                                                                      | 12/149 [00:08<01:37,  1.40it/s, avg=0.09342, loss=0.08464]

In [ ]:
# =========================
# Save study results and plots
# =========================
section("Cell | Save Optuna study results")

trials_df = study.trials_dataframe(attrs=("number", "value", "state", "params", "user_attrs", "datetime_start", "datetime_complete", "duration"))
save_csv(trials_df, OUT_OPTUNA_STUDY / "optuna_trials_dataframe.csv")
save_csv(trials_df, OUT_TABLES / "optuna_trials_dataframe.csv")
# WavLM-compatible alias.
save_csv(trials_df, OUT_OPTUNA_STUDY / "study_trials.csv")
save_csv(trials_df, OUT_TABLES / "study_trials.csv")
display(trials_df.tail(10))

# Completed trials summary.
complete_rows = []
for t in study.trials:
    if t.state == TrialState.COMPLETE:
        row = {"number": t.number, "value": t.value}
        row.update(t.params)
        complete_rows.append(row)
complete_df = pd.DataFrame(complete_rows).sort_values("value", ascending=False).reset_index(drop=True)
save_csv(complete_df, OUT_OPTUNA_STUDY / "optuna_complete_trials.csv")
save_csv(complete_df.head(OPTUNA_TOPK), OUT_OPTUNA_STUDY / "optuna_top_trials.csv")
save_csv(complete_df.head(OPTUNA_TOPK), OUT_TABLES / "optuna_top_trials.csv")
# WavLM-compatible alias.
save_csv(complete_df.head(OPTUNA_TOPK), OUT_OPTUNA_STUDY / "top5_trials.csv")
save_csv(complete_df.head(OPTUNA_TOPK), OUT_TABLES / "top5_trials.csv")
display(complete_df.head(OPTUNA_TOPK))

# Optimization history plot.
if len(complete_df) > 0:
    hist_rows = []
    best_so_far = -np.inf
    for t in sorted([t for t in study.trials if t.state == TrialState.COMPLETE], key=lambda x: x.number):
        best_so_far = max(best_so_far, float(t.value))
        hist_rows.append({"trial": t.number, "value": float(t.value), "best_so_far": float(best_so_far)})
    hist_df = pd.DataFrame(hist_rows)
    save_csv(hist_df, OUT_OPTUNA_STUDY / "optuna_optimization_history.csv")
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(hist_df["trial"], hist_df["value"], marker="o", label="trial value")
    ax.plot(hist_df["trial"], hist_df["best_so_far"], marker="o", label="best so far")
    ax.set_xlabel("Trial")
    ax.set_ylabel("Validation S = 1 - MAE")
    ax.set_title("Optuna Optimization History")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_and_maybe_show(fig, OUT_OPTUNA_STUDY / "optuna_optimization_history.png", show=DISPLAY_SUMMARY_PLOTS)
    copy_if_exists(OUT_OPTUNA_STUDY / "optuna_optimization_history.png", OUT_FIGURES / "optuna_optimization_history.png")
# WavLM-compatible alias.
copy_if_exists(OUT_OPTUNA_STUDY / "optuna_optimization_history.png", OUT_OPTUNA_STUDY / "optimization_history.png")
copy_if_exists(OUT_OPTUNA_STUDY / "optuna_optimization_history.png", OUT_FIGURES / "optimization_history.png")

# Parameter importance plot.
try:
    importances = optuna.importance.get_param_importances(study)
    imp_df = pd.DataFrame([{"parameter": k, "importance": v} for k, v in importances.items()])
    save_csv(imp_df, OUT_OPTUNA_STUDY / "optuna_param_importance.csv")
    save_csv(imp_df, OUT_TABLES / "optuna_param_importance.csv")
    if len(imp_df) > 0:
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.bar(imp_df["parameter"], imp_df["importance"])
        ax.set_title("Optuna Parameter Importance")
        ax.set_ylabel("Importance")
        ax.tick_params(axis="x", rotation=30)
        save_and_maybe_show(fig, OUT_OPTUNA_STUDY / "optuna_param_importance.png", show=DISPLAY_SUMMARY_PLOTS)
        copy_if_exists(OUT_OPTUNA_STUDY / "optuna_param_importance.png", OUT_FIGURES / "optuna_param_importance.png")
        # WavLM-compatible alias.
        copy_if_exists(OUT_OPTUNA_STUDY / "optuna_param_importance.png", OUT_OPTUNA_STUDY / "parameter_importance.png")
        copy_if_exists(OUT_OPTUNA_STUDY / "optuna_param_importance.png", OUT_FIGURES / "parameter_importance.png")
except Exception as e:
    log_line(f"Parameter importance skipped: {repr(e)}", LIVE_LOG)

# Keep only top-k Optuna checkpoints to control disk usage, following the WavLM notebook behavior.
keep_trial_numbers = set(complete_df.head(OPTUNA_TOPK)["number"].astype(int).tolist())
keep_trial_names = {f"trial_{n+1:03d}" for n in keep_trial_numbers}
save_csv(pd.DataFrame({"kept_trial_dir": sorted(keep_trial_names)}), OUT_OPTUNA_STUDY / "kept_optuna_checkpoint_dirs.csv")

removed_dirs = []
for ckpt_dir in sorted(CKPT_OPTUNA_TRIALS.glob("trial_*")):
    if ckpt_dir.name not in keep_trial_names:
        shutil.rmtree(ckpt_dir, ignore_errors=True)
        removed_dirs.append(ckpt_dir.name)
save_csv(pd.DataFrame({"removed_trial_dir": removed_dirs}), OUT_OPTUNA_STUDY / "removed_optuna_checkpoint_dirs.csv")
log_line(f"Kept Optuna checkpoint dirs: {sorted(keep_trial_names)}", LIVE_LOG)
log_line(f"Removed Optuna checkpoint dirs outside top-{OPTUNA_TOPK}: {len(removed_dirs)}", LIVE_LOG)

BEST_HP = {
    "learning_rate": float(best_trial.params["learning_rate"]),
    "r": int(best_trial.params["r"]),
    "lora_alpha": int(best_trial.params["lora_alpha"]),
    "lora_dropout": float(best_trial.params["lora_dropout"]),
    "weight_decay": float(best_trial.params["weight_decay"]),
    "warmup_ratio": float(best_trial.params["warmup_ratio"]),
}
save_json(BEST_HP, OUT_OPTUNA_STUDY / "best_params.json")
save_json(BEST_HP, OUT_OPTUNA_STUDY / "optuna_best_params.json")
save_json(BEST_HP, OUT_OPTUNA_STUDY / "best_hp.json")
copy_if_exists(OUT_OPTUNA_STUDY / "best_hp.json", OUT_TABLES / "best_hp.json")
save_csv(pd.DataFrame([BEST_HP]), OUT_OPTUNA_STUDY / "best_params.csv")
save_csv(pd.DataFrame([BEST_HP]), OUT_TABLES / "best_params.csv")
log_line(f"BEST_HP: {BEST_HP}", LIVE_LOG)

In [ ]:
# =========================
# Final runs
# =========================
section("Cell | Final runs")

def validate_existing_final_run(run_name: str, run_out_dir: Path) -> Optional[Dict]:
    summary_path = run_out_dir / "run_summary.json"
    pred_test_path = run_out_dir / "predictions_test_strict.csv"
    history_path = run_out_dir / "history.csv"
    ckpt_path = CKPT_FINAL_RUNS / run_name / "best_model.pt"

    if not (
        summary_path.exists()
        and pred_test_path.exists()
        and history_path.exists()
        and ckpt_path.exists()
    ):
        return None

    try:
        with open(summary_path, "r", encoding="utf-8") as f:
            rs = json.load(f)

        # =========================
        # Basic artifact validation
        # =========================
        df_pred_check = pd.read_csv(pred_test_path)

        if len(df_pred_check) != len(df_test):
            log_line(
                f"[FINAL-RESUME] {run_name} existing prediction row mismatch; rerun needed.",
                LIVE_LOG,
            )
            return None

        if not df_pred_check["clip_id"].is_unique:
            log_line(
                f"[FINAL-RESUME] {run_name} existing prediction clip_id not unique; rerun needed.",
                LIVE_LOG,
            )
            return None
        
        # Validate exact test clip_id set to prevent stale resume
        expected_clip_ids = set(df_test[CLIP_ID_COL].astype(str).tolist())
        actual_clip_ids = set(df_pred_check["clip_id"].astype(str).tolist())

        if actual_clip_ids != expected_clip_ids:
            missing = sorted(expected_clip_ids - actual_clip_ids)[:10]
            extra = sorted(actual_clip_ids - expected_clip_ids)[:10]
            log_line(
                f"[FINAL-RESUME] {run_name} test clip_id set mismatch; "
                f"missing_first10={missing}; extra_first10={extra}; rerun needed.",
                LIVE_LOG,
            )
            return None
        
        required_summary_keys = ["best_epoch", "stop_epoch", "best_val_S"]
        if any(k not in rs for k in required_summary_keys):
            log_line(
                f"[FINAL-RESUME] {run_name} existing summary incomplete; rerun needed.",
                LIVE_LOG,
            )
            return None

        # =========================
        # Prevent stale resume
        # =========================

        # 1. Validate model name if available in run_summary.json
        if "model_name" in rs and rs.get("model_name") != MODEL_NAME:
            log_line(
                f"[FINAL-RESUME] {run_name} model mismatch "
                f"({rs.get('model_name')} != {MODEL_NAME}); rerun needed.",
                LIVE_LOG,
            )
            return None

        # 2. Validate seed from run_name against summary seed
        # Expected run_name example: run_01_seed_042
        if "seed" in rs:
            try:
                expected_seed = int(str(run_name).split("_seed_")[-1])
                actual_seed = int(rs.get("seed"))
                if actual_seed != expected_seed:
                    log_line(
                        f"[FINAL-RESUME] {run_name} seed mismatch "
                        f"({actual_seed} != {expected_seed}); rerun needed.",
                        LIVE_LOG,
                    )
                    return None
            except Exception:
                log_line(
                    f"[FINAL-RESUME] {run_name} seed validation failed; rerun needed.",
                    LIVE_LOG,
                )
                return None

        # 3. Validate best hyperparameters if available in run_summary.json
        if "hp" in rs:
            for k, v in BEST_HP.items():
                if k not in rs["hp"]:
                    log_line(
                        f"[FINAL-RESUME] {run_name} missing HP key '{k}'; rerun needed.",
                        LIVE_LOG,
                    )
                    return None

                old_v = rs["hp"].get(k)

                # Compare floats safely, otherwise compare as string
                try:
                    if isinstance(v, float) or isinstance(old_v, float):
                        if not np.isclose(float(old_v), float(v), rtol=1e-9, atol=1e-12):
                            log_line(
                                f"[FINAL-RESUME] {run_name} HP mismatch at {k} "
                                f"({old_v} != {v}); rerun needed.",
                                LIVE_LOG,
                            )
                            return None
                    else:
                        if str(old_v) != str(v):
                            log_line(
                                f"[FINAL-RESUME] {run_name} HP mismatch at {k} "
                                f"({old_v} != {v}); rerun needed.",
                                LIVE_LOG,
                            )
                            return None
                except Exception:
                    if str(old_v) != str(v):
                        log_line(
                            f"[FINAL-RESUME] {run_name} HP mismatch at {k} "
                            f"({old_v} != {v}); rerun needed.",
                            LIVE_LOG,
                        )
                        return None

        # 4. Validate required prediction columns
        required_pred_cols = ["clip_id"]
        for c in LABEL_COLS:
            required_pred_cols.extend([
                f"true_{c}",
                f"pred_{c}",
                f"abs_err_{c}",
            ])

        missing_pred_cols = [c for c in required_pred_cols if c not in df_pred_check.columns]
        if missing_pred_cols:
            log_line(
                f"[FINAL-RESUME] {run_name} missing prediction columns "
                f"{missing_pred_cols}; rerun needed.",
                LIVE_LOG,
            )
            return None
        pred_cols = [f"pred_{c}" for c in LABEL_COLS]
        true_cols = [f"true_{c}" for c in LABEL_COLS]

        if df_pred_check[pred_cols + true_cols].isna().any().any():
            log_line(f"[FINAL-RESUME] {run_name} has NaN in prediction/target columns; rerun needed.", LIVE_LOG)
            return None

        if not ((df_pred_check[pred_cols] >= 0).all().all() and (df_pred_check[pred_cols] <= 1).all().all()):
            log_line(f"[FINAL-RESUME] {run_name} prediction values outside [0,1]; rerun needed.", LIVE_LOG)
            return None
        
        log_line(
            f"[FINAL-RESUME] {run_name} existing artifacts valid; resume accepted.",
            LIVE_LOG,
        )
        return rs

    except Exception as e:
        log_line(
            f"[FINAL-RESUME] {run_name} validation error: {repr(e)}; rerun needed.",
            LIVE_LOG,
        )
        return None

final_run_rows = []
for idx, seed in enumerate(FINAL_SEEDS, start=1):
    run_name = f"run_{idx:02d}_seed_{seed:03d}"
    run_out_dir = OUT_FINAL_RUNS / run_name
    run_ckpt_dir = CKPT_FINAL_RUNS / run_name

    rs = validate_existing_final_run(run_name, run_out_dir)
    if rs is not None:
        log_line(f"[FINAL-RESUME] using existing completed run: {run_name}", LIVE_LOG)
    else:
        log_line(f"[FINAL] start {run_name}", LIVE_LOG)
        result = run_single_training(
            run_name=run_name,
            run_output_dir=run_out_dir,
            run_ckpt_dir=run_ckpt_dir,
            df_tr=df_train,
            df_va=df_val,
            df_te=df_test,
            seed=seed,
            hp=BEST_HP,
            is_optuna=False,
            trial=None,
            show_plots=DISPLAY_FINAL_RUN_PLOTS,
        )
        rs = result["run_summary"]
        del result
        gpu_flush()

    pred_test_path = run_out_dir / "predictions_test_strict.csv"
    assert pred_test_path.exists(), f"Missing test prediction CSV: {pred_test_path}"
    df_pred_check = pd.read_csv(pred_test_path)
    assert len(df_pred_check) == len(df_test), f"Prediction rows mismatch in {run_name}: {len(df_pred_check)} vs {len(df_test)}"
    assert df_pred_check["clip_id"].is_unique, f"clip_id is not unique in {pred_test_path}"

    final_run_rows.append({
        "run_id": run_name,
        "seed": int(seed),
        "best_epoch": int(rs["best_epoch"]),
        "stop_epoch": int(rs["stop_epoch"]),
        "best_val_S": float(rs["best_val_S"]),
        "test_MAE_mean": rs.get("test_mae_mean", np.nan),
        "test_RMSE_mean": rs.get("test_rmse_mean", np.nan),
        "test_R2_mean": rs.get("test_r2_mean", np.nan),
        "test_Acc_mean": rs.get("test_acc_mean", np.nan),
        "checkpoint_path": rs.get("checkpoint_path"),
    })

    log_line(f"[FINAL] recorded {run_name} | test_MAE={rs.get('test_mae_mean', np.nan):.6f} | test_R2={rs.get('test_r2_mean', np.nan):.6f}", LIVE_LOG)
    del df_pred_check
    gpu_flush()

final_runs_summary = pd.DataFrame(final_run_rows)
save_csv(final_runs_summary, OUT_FINAL_AGG / "final_runs_summary.csv")
save_csv(final_runs_summary, OUT_TABLES / "final_runs_summary.csv")
display(final_runs_summary)

In [ ]:
# =========================
# Aggregate statistics, selection, and ensemble
# =========================
section("Cell | Aggregate statistics, selection, and ensemble")

summary = pd.read_csv(OUT_FINAL_AGG / "final_runs_summary.csv")
metrics_cols = ["best_val_S", "test_MAE_mean", "test_RMSE_mean", "test_R2_mean", "test_Acc_mean"]
stat_rows = []
for col in metrics_cols:
    vals = summary[col].dropna().astype(float).values
    if len(vals) == 0:
        continue
    mean = float(np.mean(vals))
    std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
    sem = std / math.sqrt(len(vals)) if len(vals) > 1 else 0.0
    ci95 = 1.96 * sem if len(vals) > 1 else 0.0
    stat_rows.append({"metric": col, "n": len(vals), "mean": mean, "std": std, "min": float(np.min(vals)), "median": float(np.median(vals)), "max": float(np.max(vals)), "ci95_half_width": ci95})
final_stats_long = pd.DataFrame(stat_rows)
save_csv(final_stats_long, OUT_FINAL_AGG / "final_stats_summary_long.csv")
save_csv(final_stats_long, OUT_TABLES / "final_stats_summary_long.csv")
save_json({r["metric"]: r for r in stat_rows}, OUT_FINAL_AGG / "final_stats_summary_long.json")
display(final_stats_long)

# =========================
# Extra WavLM-compatible statistical artifacts
# =========================

def summarize_series(x: pd.Series, prefix: str) -> Dict:
    arr = x.dropna().values.astype(float)
    if len(arr) == 0:
        return {}

    mean = float(arr.mean())
    std = float(arr.std(ddof=1)) if len(arr) > 1 else 0.0
    ci95 = float(1.96 * std / math.sqrt(len(arr))) if len(arr) > 1 else 0.0

    return {
        f"{prefix}_n": int(len(arr)),
        f"{prefix}_mean": mean,
        f"{prefix}_std": std,
        f"{prefix}_min": float(np.min(arr)),
        f"{prefix}_max": float(np.max(arr)),
        f"{prefix}_p10": float(np.percentile(arr, 10)),
        f"{prefix}_p50": float(np.percentile(arr, 50)),
        f"{prefix}_p90": float(np.percentile(arr, 90)),
        f"{prefix}_ci95_low": mean - ci95,
        f"{prefix}_ci95_high": mean + ci95,
        f"{prefix}_ci95_half_width": ci95,
    }


stats = {}

for col in [
    "best_val_S",
    "test_MAE_mean",
    "test_RMSE_mean",
    "test_R2_mean",
    "test_Acc_mean",
    "best_epoch",
    "stop_epoch",
]:
    if col in summary.columns:
        stats.update(summarize_series(summary[col], col))

stats_wide_df = pd.DataFrame([stats])
save_csv(stats_wide_df, OUT_FINAL_AGG / "final_stats_summary_wide.csv")
save_csv(stats_wide_df, OUT_TABLES / "final_stats_summary_wide.csv")
save_json(make_json_safe(stats), OUT_FINAL_AGG / "final_stats_summary.json")

# WavLM-compatible alias
save_csv(stats_wide_df, OUT_FINAL_AGG / "final_stats_summary.csv")
save_csv(stats_wide_df, OUT_TABLES / "final_stats_summary.csv")

# 95% CI report per metric
ci_rows = []
for col in [
    "best_val_S",
    "test_MAE_mean",
    "test_RMSE_mean",
    "test_R2_mean",
    "test_Acc_mean",
]:
    if col in summary.columns and f"{col}_mean" in stats:
        ci_rows.append({
            "metric": col,
            "n": stats.get(f"{col}_n"),
            "mean": stats.get(f"{col}_mean"),
            "std": stats.get(f"{col}_std"),
            "ci95_low": stats.get(f"{col}_ci95_low"),
            "ci95_high": stats.get(f"{col}_ci95_high"),
            "ci95_half_width": stats.get(f"{col}_ci95_half_width"),
        })

ci_df = pd.DataFrame(ci_rows)
save_csv(ci_df, OUT_FINAL_AGG / "ci_95_report.csv")
save_csv(ci_df, OUT_TABLES / "ci_95_report.csv")


# Epoch behavior report
epoch_cols = [c for c in ["run_id", "seed", "best_epoch", "stop_epoch"] if c in summary.columns]
epoch_behavior_df = summary[epoch_cols].copy()
save_csv(epoch_behavior_df, OUT_FINAL_AGG / "epoch_behavior.csv")
save_csv(epoch_behavior_df, OUT_TABLES / "epoch_behavior.csv")


# Validation stability report
stability_cols = [
    c for c in [
        "run_id",
        "seed",
        "best_val_S",
        "test_MAE_mean",
        "test_RMSE_mean",
        "test_R2_mean",
        "test_Acc_mean",
    ]
    if c in summary.columns
]
validation_stability_df = summary[stability_cols].copy()
save_csv(validation_stability_df, OUT_FINAL_AGG / "validation_stability.csv")
save_csv(validation_stability_df, OUT_TABLES / "validation_stability.csv")


# Best epoch distribution
if "best_epoch" in summary.columns:
    best_epoch_dist = (
        summary["best_epoch"]
        .value_counts()
        .sort_index()
        .reset_index()
    )
    best_epoch_dist.columns = ["best_epoch", "count"]
    save_csv(best_epoch_dist, OUT_FINAL_AGG / "best_epoch_distribution.csv")
    save_csv(best_epoch_dist, OUT_TABLES / "best_epoch_distribution.csv")


# Stop epoch distribution
if "stop_epoch" in summary.columns:
    stop_epoch_dist = (
        summary["stop_epoch"]
        .value_counts()
        .sort_index()
        .reset_index()
    )
    stop_epoch_dist.columns = ["stop_epoch", "count"]
    save_csv(stop_epoch_dist, OUT_FINAL_AGG / "stop_epoch_distribution.csv")
    save_csv(stop_epoch_dist, OUT_TABLES / "stop_epoch_distribution.csv")


log_line("[FINAL] Extra WavLM-compatible statistical artifacts saved.", LIVE_LOG)



# Simple metric curves across final runs.
for metric in ["test_MAE_mean", "test_R2_mean", "test_Acc_mean"]:
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(range(1, len(summary)+1), summary[metric], marker="o")
    ax.set_xlabel("Run index")
    ax.set_ylabel(metric)
    ax.set_title(f"{metric} Across Final Runs")
    ax.grid(True, alpha=0.3)
    save_and_maybe_show(fig, OUT_FINAL_AGG / f"curve_{metric}_across_runs.png", show=DISPLAY_SUMMARY_PLOTS)
    copy_if_exists(OUT_FINAL_AGG / f"curve_{metric}_across_runs.png", OUT_FIGURES / f"curve_{metric}_across_runs.png")

# Select best-val run and median run.
best_val_row = summary.sort_values("best_val_S", ascending=False).iloc[0].to_dict()
# Match WavLM behavior: select representative median run using validation score, not test metric.
sorted_by_val = summary.sort_values("best_val_S", ascending=True).reset_index(drop=True)
median_row = sorted_by_val.iloc[len(sorted_by_val) // 2].to_dict()
selected_info = {"best_val": best_val_row, "median": median_row}
save_json(selected_info, OUT_FINAL_AGG / "selected_runs_summary.json")
save_csv(pd.DataFrame([best_val_row, median_row], index=["best_val", "median"]).reset_index(names="selection"), OUT_TABLES / "best_val_median_runs.csv")
display(pd.DataFrame([best_val_row, median_row], index=["best_val", "median"]))


def copy_selected_run(selection_name: str, row: Dict):
    src_run = OUT_FINAL_RUNS / str(row["run_id"])
    dst_run = OUT_FINAL_SELECTED / selection_name
    dst_run.mkdir(parents=True, exist_ok=True)
    for fname in [
        "history.csv", "loss_curve.png", "curve_train_loss.png", "curve_val_S.png",
        "curve_val_mae_mean.png", "curve_val_rmse_mean.png", "curve_val_r2_mean.png",
        "curve_mae_per_trait.png", "predictions_val_best.csv", "predictions_test_strict.csv",
        "test_metrics.json", "best_val_metrics.json", "test_per_trait_metrics.csv",
        "hist_test_strict_pred_vs_true.png", "scatter_test_strict_pred_vs_true.png",
        "scatter_test_strict_residuals.png"
    ]:
        copy_if_exists(src_run / fname, dst_run / fname)
    ckpt_src = CKPT_FINAL_RUNS / str(row["run_id"]) / "best_model.pt"
    ckpt_dst = CKPT_FINAL_SELECTED / selection_name / "best_model.pt"
    copy_if_exists(ckpt_src, ckpt_dst)

copy_selected_run("best_val", best_val_row)
copy_selected_run("median", median_row)

# Ensemble: average predictions from all final runs.
pred_paths = []
for run_id in summary["run_id"].tolist():
    p = OUT_FINAL_RUNS / str(run_id) / "predictions_test_strict.csv"
    assert p.exists(), f"Missing prediction: {p}"
    pred_paths.append(p)

base = pd.read_csv(pred_paths[0]).sort_values("clip_id").reset_index(drop=True)
ensemble_sources = [str(p) for p in pred_paths]
for col in LABEL_COLS:
    preds = []
    for p in pred_paths:
        d = pd.read_csv(p).sort_values("clip_id").reset_index(drop=True)
        assert (d["clip_id"].values == base["clip_id"].values).all(), f"clip_id order mismatch: {p}"
        preds.append(d[f"pred_{col}"].values)
    base[f"pred_{col}"] = np.mean(np.stack(preds, axis=0), axis=0)
    base[f"abs_err_{col}"] = np.abs(base[f"pred_{col}"] - base[f"true_{col}"])
base["run_id"] = "ensemble_mean_10runs"
base["seed"] = -1
base["mae_per_sample"] = base[[f"abs_err_{c}" for c in LABEL_COLS]].mean(axis=1)

y_true = base[[f"true_{c}" for c in LABEL_COLS]].values
y_pred = base[[f"pred_{c}" for c in LABEL_COLS]].values
ens_metrics = compute_metrics_from_arrays(y_true, y_pred)
ens_flat = metrics_to_flat_dict(ens_metrics)
ENS_OUT = OUT_FINAL_SELECTED / "ensemble"
ENS_OUT.mkdir(parents=True, exist_ok=True)
save_csv(base, ENS_OUT / "ensemble_predictions_test_strict.csv")
save_json(ens_flat, ENS_OUT / "ensemble_metrics.json")
save_json({"sources": ensemble_sources}, ENS_OUT / "ensemble_sources.json")
plot_pred_vs_true(base, ENS_OUT, tag="ensemble", show=DISPLAY_SUMMARY_PLOTS)
ens_trait = per_trait_metrics_df(y_true, y_pred, tag="ensemble")
save_csv(ens_trait, ENS_OUT / "ensemble_per_trait_metrics.csv")
save_csv(ens_trait, OUT_TABLES / "per_trait_metrics_ensemble.csv")
display(pd.DataFrame([ens_flat]))

# =========================================================
# Best-val, median, ensemble summary table
# =========================================================
bme_rows = []

bme_rows.append({
    "selection": "best_val",
    "run_id": best_val_row.get("run_id"),
    "seed": best_val_row.get("seed"),
    "best_val_S": best_val_row.get("best_val_S"),
    "test_MAE_mean": best_val_row.get("test_MAE_mean"),
    "test_RMSE_mean": best_val_row.get("test_RMSE_mean"),
    "test_R2_mean": best_val_row.get("test_R2_mean"),
    "test_Acc_mean": best_val_row.get("test_Acc_mean"),
})

bme_rows.append({
    "selection": "median",
    "run_id": median_row.get("run_id"),
    "seed": median_row.get("seed"),
    "best_val_S": median_row.get("best_val_S"),
    "test_MAE_mean": median_row.get("test_MAE_mean"),
    "test_RMSE_mean": median_row.get("test_RMSE_mean"),
    "test_R2_mean": median_row.get("test_R2_mean"),
    "test_Acc_mean": median_row.get("test_Acc_mean"),
})

bme_rows.append({
    "selection": "ensemble",
    "run_id": "ensemble_mean_10runs",
    "seed": -1,
    "best_val_S": np.nan,
    "test_MAE_mean": ens_flat.get("mae_mean"),
    "test_RMSE_mean": ens_flat.get("rmse_mean"),
    "test_R2_mean": ens_flat.get("r2_mean"),
    "test_Acc_mean": ens_flat.get("acc_mean"),
})

bme_df = pd.DataFrame(bme_rows)

save_csv(bme_df, OUT_FINAL_AGG / "best_val_median_ensemble.csv")
save_csv(bme_df, OUT_TABLES / "best_val_median_ensemble.csv")

display(bme_df)

# Copy summary figures to global figures.
copy_if_exists(ENS_OUT / "hist_ensemble_pred_vs_true.png", OUT_FIGURES / "hist_ensemble_pred_vs_true.png")
copy_if_exists(ENS_OUT / "scatter_ensemble_pred_vs_true.png", OUT_FIGURES / "scatter_ensemble_pred_vs_true.png")

In [ ]:
# =========================
# Loss diagnostics and overfit/underfit analysis
# =========================
section("Cell | Loss diagnostics and overfit/underfit analysis")

summary = pd.read_csv(OUT_FINAL_AGG / "final_runs_summary.csv")
gap_rows = []
all_histories = []
for _, row in summary.iterrows():
    run_id = str(row["run_id"])
    hpath = OUT_FINAL_RUNS / run_id / "history.csv"
    if not hpath.exists():
        continue
    h = pd.read_csv(hpath).sort_values("epoch").reset_index(drop=True)
    # history.csv dari training menyimpan val_mae_mean.
    # Untuk artefak post-hoc yang kompatibel dengan WavLM,
    # val_mae_mean dipakai sebagai alias val_loss.
    if "val_loss" not in h.columns:
        if "val_mae_mean" not in h.columns:
            raise KeyError(f"history.csv {hpath} tidak punya kolom val_mae_mean/val_loss")
        h["val_loss"] = h["val_mae_mean"]
    
    if "train_val_gap" not in h.columns:
        h["train_val_gap"] = h["val_loss"] - h["train_loss"]
    
    h["run_id"] = run_id
    all_histories.append(h)
    best_epoch = int(row["best_epoch"])
    best_h = h.loc[h["epoch"] == best_epoch].iloc[0] if (h["epoch"] == best_epoch).any() else h.sort_values("val_S", ascending=False).iloc[0]
    last_h = h.iloc[-1]
    gap_best = float(best_h["val_mae_mean"] - best_h["train_loss"])
    gap_last = float(last_h["val_mae_mean"] - last_h["train_loss"])
    if gap_best <= 0.01 and gap_last <= 0.015:
        diagnosis = "tidak menunjukkan overfitting berat"
    elif gap_best <= 0.02 or gap_last <= 0.03:
        diagnosis = "indikasi gap ringan; perlu dibaca bersama kurva"
    else:
        diagnosis = "indikasi overfitting yang perlu dicermati"
    if len(h) >= 2:
        train_improve = float(h["train_loss"].iloc[0] - h["train_loss"].iloc[-1])
        val_improve = float(h["val_mae_mean"].iloc[0] - h["val_mae_mean"].min())
    else:
        train_improve = np.nan
        val_improve = np.nan
    if np.isfinite(train_improve) and np.isfinite(val_improve) and train_improve < 0.001 and val_improve < 0.001:
        underfit_note = "kemungkinan underfitting/optimisasi belum efektif"
    else:
        underfit_note = "tidak ada indikasi underfitting yang jelas dari loss"
    gap_rows.append({
    "run_id": run_id,
    "seed": int(row["seed"]),
    "best_epoch": best_epoch,
    "stop_epoch": int(row["stop_epoch"]),
    "final_epoch": int(h["epoch"].max()),

    "min_train_loss": float(h["train_loss"].min()),
    "min_val_loss": float(h["val_loss"].min()),
    "epoch_min_val_loss": int(h.loc[h["val_loss"].idxmin(), "epoch"]),

    "train_loss_at_best_epoch": float(best_h["train_loss"]),
    "val_loss_at_best_epoch": float(best_h["val_loss"]),
    "gap_at_best_epoch": float(best_h["train_val_gap"]),

    "final_train_loss": float(last_h["train_loss"]),
    "final_val_loss": float(last_h["val_loss"]),
    "final_gap": float(last_h["train_val_gap"]),

    "mean_gap": float(h["train_val_gap"].mean()),
    "max_gap": float(h["train_val_gap"].max()),
    "min_gap": float(h["train_val_gap"].min()),

    "diagnosis": diagnosis,

    # legacy HuBERT columns, boleh tetap disimpan
    "overfit_diagnosis": diagnosis,
    "underfit_note": underfit_note,
})

gap_df = pd.DataFrame(gap_rows)
save_csv(gap_df, OUT_FINAL_AGG / "train_val_gap_diagnostics.csv")
save_csv(gap_df, OUT_TABLES / "train_val_gap_diagnostics.csv")
# WavLM posthoc-compatible alias.
save_csv(gap_df, OUT_FINAL_AGG / "loss_diagnostic_summary_per_run.csv")
save_csv(gap_df, OUT_TABLES / "loss_diagnostic_summary_per_run.csv")
save_csv(gap_df[["run_id", "overfit_diagnosis", "underfit_note"]], OUT_TABLES / "overfit_underfit_diagnosis.csv")
display(gap_df)

# Per-run posthoc-compatible history files
history_index_rows = []

for _, row in summary.iterrows():
    run_id = str(row["run_id"])
    run_dir = OUT_FINAL_RUNS / run_id
    hpath = run_dir / "history.csv"

    history_index_rows.append({
        "run_id": run_id,
        "seed": int(row["seed"]),
        "run_dir": str(run_dir),
        "history_path": str(hpath),
        "history_exists": hpath.exists(),
    })

    if hpath.exists():
        h = pd.read_csv(hpath).copy()
        h["val_loss"] = h["val_mae_mean"]
        h["train_val_gap"] = h["val_loss"] - h["train_loss"]
        save_csv(h, run_dir / "history_with_val_loss.csv")

save_csv(pd.DataFrame(history_index_rows), OUT_FINAL_AGG / "final_run_history_index.csv")
save_csv(pd.DataFrame(history_index_rows), OUT_TABLES / "final_run_history_index.csv")


if all_histories:
    hist_all = pd.concat(all_histories, ignore_index=True)
    hist_all["val_loss"] = hist_all["val_mae_mean"]
    hist_all["train_val_gap"] = hist_all["val_loss"] - hist_all["train_loss"]
    save_csv(hist_all, OUT_FINAL_AGG / "all_final_histories_long.csv")
    # WavLM posthoc-compatible alias.
    save_csv(hist_all, OUT_FINAL_AGG / "all_runs_history_with_val_loss.csv")
    agg = hist_all.groupby("epoch").agg(
    train_loss_mean=("train_loss", "mean"),
    train_loss_std=("train_loss", "std"),
    val_loss_mean=("val_loss", "mean"),
    val_loss_std=("val_loss", "std"),
    train_val_gap_mean=("train_val_gap", "mean"),
    train_val_gap_std=("train_val_gap", "std"),
    n=("run_id", "nunique"),
    ).reset_index()
    
    
    # WavLM posthoc-compatible aliases
    agg["n_runs"] = agg["n"]
    agg["gap_mean"] = agg["train_val_gap_mean"]
    agg["gap_std"] = agg["train_val_gap_std"]

    # Optional: reorder front columns for posthoc compatibility
    front_cols = [
        "epoch",
        "n_runs",
        "train_loss_mean",
        "train_loss_std",
        "val_loss_mean",
        "val_loss_std",
        "gap_mean",
        "gap_std",
    ]
    remaining_cols = [c for c in agg.columns if c not in front_cols]
    agg = agg[front_cols + remaining_cols]
        
    save_csv(agg, OUT_FINAL_AGG / "aggregate_loss_by_epoch.csv")
    # WavLM posthoc-compatible alias.
    save_csv(agg, OUT_FINAL_AGG / "aggregate_loss_curve_by_epoch.csv")
    save_csv(agg, OUT_TABLES / "aggregate_loss_curve_by_epoch.csv")
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(agg["epoch"], agg["train_loss_mean"], marker="o", label="train_loss mean")
    ax.plot(agg["epoch"], agg["val_loss_mean"], marker="o", label="validation_loss / val_MAE_mean")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("MAE / L1 loss")
    ax.set_title("Aggregate Train and Validation Loss Across Final Runs")
    ax.legend()
    ax.grid(True, alpha=0.3)
    save_and_maybe_show(fig, OUT_FINAL_AGG / "aggregate_loss_curve.png", show=DISPLAY_SUMMARY_PLOTS)
    copy_if_exists(OUT_FINAL_AGG / "aggregate_loss_curve.png", OUT_FIGURES / "aggregate_loss_curve.png")
    
    
    # WavLM posthoc-compatible overlay plot: all runs train vs validation loss
    fig, ax = plt.subplots(figsize=(10, 6))
    for run_id, sub in hist_all.groupby("run_id"):
        ax.plot(sub["epoch"], sub["train_loss"], alpha=0.35)
        ax.plot(sub["epoch"], sub["val_loss"], alpha=0.35, linestyle="--")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss / MAE")
    ax.set_title("All Runs Train vs Validation Loss Overlay")
    ax.grid(True, alpha=0.3)
    save_and_maybe_show(
        fig,
        OUT_FINAL_AGG / "all_runs_train_vs_val_loss_overlay.png",
        show=DISPLAY_SUMMARY_PLOTS,
    )
    copy_if_exists(
        OUT_FINAL_AGG / "all_runs_train_vs_val_loss_overlay.png",
        OUT_FIGURES / "all_runs_train_vs_val_loss_overlay.png",
    )

    # WavLM posthoc-compatible mean ± std plot
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(agg["epoch"], agg["train_loss_mean"], label="train_loss mean")
    ax.plot(agg["epoch"], agg["val_loss_mean"], label="val_loss mean")
    ax.fill_between(
        agg["epoch"],
        agg["train_loss_mean"] - agg["train_loss_std"].fillna(0),
        agg["train_loss_mean"] + agg["train_loss_std"].fillna(0),
        alpha=0.15,
    )
    ax.fill_between(
        agg["epoch"],
        agg["val_loss_mean"] - agg["val_loss_std"].fillna(0),
        agg["val_loss_mean"] + agg["val_loss_std"].fillna(0),
        alpha=0.15,
    )
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss / MAE")
    ax.set_title("Aggregate Train vs Validation Loss Mean ± Std")
    save_and_maybe_show(
        fig,
        OUT_FINAL_AGG / "aggregate_train_vs_val_loss_mean_std.png",
        show=DISPLAY_SUMMARY_PLOTS,
    )
    copy_if_exists(
        OUT_FINAL_AGG / "aggregate_train_vs_val_loss_mean_std.png",
        OUT_FIGURES / "aggregate_train_vs_val_loss_mean_std.png",
    )

    # WavLM posthoc-compatible train-validation gap plot
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(agg["epoch"], agg["train_val_gap_mean"], label="gap mean")
    ax.fill_between(
        agg["epoch"],
        agg["train_val_gap_mean"] - agg["train_val_gap_std"].fillna(0),
        agg["train_val_gap_mean"] + agg["train_val_gap_std"].fillna(0),
        alpha=0.15,
    )
    ax.axhline(0, linestyle="--")
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Validation loss - Train loss")
    ax.set_title("Aggregate Train-Validation Gap Mean ± Std")
    save_and_maybe_show(
        fig,
        OUT_FINAL_AGG / "aggregate_train_val_gap_mean_std.png",
        show=DISPLAY_SUMMARY_PLOTS,
    )
    copy_if_exists(
        OUT_FINAL_AGG / "aggregate_train_val_gap_mean_std.png",
        OUT_FIGURES / "aggregate_train_val_gap_mean_std.png",
    )


if not gap_df.empty:
    overfit_count = gap_df["overfit_diagnosis"].str.contains(
        "overfitting", case=False, na=False
    ).sum()

    underfit_count = gap_df["underfit_note"].str.contains(
        "underfitting", case=False, na=False
    ).sum()

    interpretation_text = f"""
Interpretasi Diagnostik Train Loss dan Validation Loss

Analisis ini membaca history.csv dari setiap final run HuBERT + LoRA pada strict split.
Train loss dihitung sebagai MAE/L1 loss, sedangkan validation loss direpresentasikan oleh val_mae_mean.
Jumlah run terbaca: {len(gap_df)}.
Jumlah run dengan indikasi overfitting yang perlu dicermati: {overfit_count}.
Jumlah run dengan indikasi underfitting/optimisasi belum efektif: {underfit_count}.

Interpretasi ini bersifat post-hoc dan tidak mengubah hasil eksperimen utama.
""".strip()

    save_text(
        interpretation_text,
        OUT_FINAL_AGG / "overfit_underfit_interpretation.txt",
    )
    copy_if_exists(
        OUT_FINAL_AGG / "overfit_underfit_interpretation.txt",
        OUT_APPENDIX / "appendix_overfit_underfit_interpretation.txt",
    )

In [ ]:
# =========================
# R² / regression-to-the-mean diagnostics and per-trait artifacts
# =========================
section("Cell | R2 and regression-to-the-mean diagnostics")

BEST_VAL_PRED = OUT_FINAL_SELECTED / "best_val" / "predictions_test_strict.csv"
MEDIAN_PRED = OUT_FINAL_SELECTED / "median" / "predictions_test_strict.csv"
ENS_PRED = OUT_FINAL_SELECTED / "ensemble" / "ensemble_predictions_test_strict.csv"
assert BEST_VAL_PRED.exists(), f"Missing: {BEST_VAL_PRED}"

def save_trait_outputs(pred_path: Path, tag: str):
    dfp = pd.read_csv(pred_path)
    y_true = dfp[[f"true_{c}" for c in LABEL_COLS]].values
    y_pred = dfp[[f"pred_{c}" for c in LABEL_COLS]].values
    trait_df = per_trait_metrics_df(y_true, y_pred, tag=tag)
    save_csv(trait_df, OUT_TABLES / f"per_trait_metrics_{tag}.csv")
    plot_bar_metrics(trait_df, "MAE", OUT_FIGURES / f"per_trait_mae_{tag}.png", f"Per-trait MAE ({tag})", show=DISPLAY_SUMMARY_PLOTS)
    plot_bar_metrics(trait_df, "R2", OUT_FIGURES / f"per_trait_r2_{tag}.png", f"Per-trait R² ({tag})", show=DISPLAY_SUMMARY_PLOTS)
    return dfp, trait_df

best_df, best_trait_df = save_trait_outputs(BEST_VAL_PRED, "best_val")
save_csv(best_trait_df, OUT_FINAL_AGG / "best_val_test_trait_summary.csv")
save_csv(best_trait_df, OUT_TABLES / "best_val_test_trait_summary.csv")
if "mae_per_sample" not in best_df.columns:
    best_df["mae_per_sample"] = best_df[[f"abs_err_{c}" for c in LABEL_COLS]].mean(axis=1)

df_worst = best_df.sort_values("mae_per_sample", ascending=False).head(20).reset_index(drop=True)
df_best = best_df.sort_values("mae_per_sample", ascending=True).head(20).reset_index(drop=True)

save_csv(df_worst, OUT_FINAL_AGG / "top20_worst_predictions.csv")
save_csv(df_best, OUT_FINAL_AGG / "top20_best_predictions.csv")
save_csv(df_worst, OUT_TABLES / "top20_worst_predictions.csv")
save_csv(df_best, OUT_TABLES / "top20_best_predictions.csv")

if MEDIAN_PRED.exists():
    median_df, median_trait_df = save_trait_outputs(MEDIAN_PRED, "median")
if ENS_PRED.exists():
    ens_df, ens_trait_df = save_trait_outputs(ENS_PRED, "ensemble")

# Regression-to-the-mean summary for best-val run.
analysis_rows = []
for col in LABEL_COLS:
    true_vals = best_df[f"true_{col}"].values
    pred_vals = best_df[f"pred_{col}"].values
    true_var = float(np.var(true_vals))
    pred_var = float(np.var(pred_vals))
    compression = float(pred_var / true_var) if true_var > 1e-12 else np.nan
    corr = float(np.corrcoef(true_vals, pred_vals)[0, 1]) if len(true_vals) > 1 else np.nan
    analysis_rows.append({
        "trait": col,
        "true_mean": float(np.mean(true_vals)),
        "true_std": float(np.std(true_vals)),
        "true_var": true_var,
        "true_min": float(np.min(true_vals)),
        "true_max": float(np.max(true_vals)),
        "pred_mean": float(np.mean(pred_vals)),
        "pred_std": float(np.std(pred_vals)),
        "pred_var": pred_var,
        "pred_min": float(np.min(pred_vals)),
        "pred_max": float(np.max(pred_vals)),
        "pred_var_over_true_var": compression,
        "corr_true_pred": corr,
        "mae": float(np.mean(np.abs(pred_vals - true_vals))),
        "rmse": float(np.sqrt(np.mean((pred_vals - true_vals) ** 2))),
        "r2": float(r2_score(true_vals, pred_vals)),
    })
analysis_df = pd.DataFrame(analysis_rows)
save_csv(analysis_df, OUT_FINAL_AGG / "r2_vs_mae_analysis.csv")
save_csv(analysis_df, OUT_FINAL_AGG / "regression_to_mean_summary.csv")
save_csv(analysis_df, OUT_TABLES / "regression_to_mean_summary.csv")
display(analysis_df)

# Std comparison plot.
fig, ax = plt.subplots(figsize=(9, 5))
x = np.arange(len(analysis_df))
width = 0.35
ax.bar(x - width/2, analysis_df["true_std"], width, label="true_std")
ax.bar(x + width/2, analysis_df["pred_std"], width, label="pred_std")
ax.set_xticks(x)
ax.set_xticklabels(analysis_df["trait"], rotation=30)
ax.set_ylabel("Standard deviation")
ax.set_title("True vs Predicted Standard Deviation (Best-Val Run)")
ax.legend()
save_and_maybe_show(fig, OUT_FIGURES / "true_std_vs_pred_std_best_val.png", show=DISPLAY_SUMMARY_PLOTS)

# Bin analysis.
bin_rows = []
for col in LABEL_COLS:
    temp = best_df[[f"true_{col}", f"pred_{col}"]].copy()
    temp.columns = ["true", "pred"]
    temp["bin"] = pd.qcut(temp["true"], q=5, duplicates="drop")
    grp = temp.groupby("bin", observed=False).agg(true_mean=("true", "mean"), pred_mean=("pred", "mean"), count=("true", "size")).reset_index()
    grp["trait"] = col
    grp["gap_pred_minus_true"] = grp["pred_mean"] - grp["true_mean"]
    bin_rows.append(grp)
bin_df = pd.concat(bin_rows, ignore_index=True)
save_csv(bin_df, OUT_FINAL_AGG / "best_val_test_bin_analysis.csv")
save_csv(bin_df, OUT_TABLES / "best_val_test_bin_analysis.csv")

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()
for i, col in enumerate(LABEL_COLS):
    ax = axes[i]
    sub = bin_df[bin_df["trait"] == col].reset_index(drop=True)
    ax.plot(range(len(sub)), sub["true_mean"], marker="o", label="true_mean")
    ax.plot(range(len(sub)), sub["pred_mean"], marker="o", label="pred_mean")
    ax.set_title(col)
    ax.set_xlabel("Target bin")
    ax.set_ylabel("Mean score")
    ax.legend()
axes[-1].axis("off")
save_and_maybe_show(fig, OUT_FIGURES / "best_val_test_bin_analysis.png", show=DISPLAY_SUMMARY_PLOTS)

# Residual boxplot.
residual_long = []
for col in LABEL_COLS:
    residual = best_df[f"pred_{col}"].values - best_df[f"true_{col}"].values
    for v in residual:
        residual_long.append({"trait": col, "residual": float(v)})
residual_df = pd.DataFrame(residual_long)
save_csv(residual_df, OUT_FINAL_AGG / "best_val_test_residuals_long.csv")
fig, ax = plt.subplots(figsize=(10, 5))
data = [residual_df[residual_df["trait"] == col]["residual"].values for col in LABEL_COLS]
ax.boxplot(data, tick_labels=LABEL_COLS)
ax.axhline(0, linestyle="--")
ax.set_title("Residual Distribution per Trait (Best-Val Test Strict)")
ax.set_ylabel("Pred - True")
save_and_maybe_show(fig, OUT_FIGURES / "best_val_test_residual_boxplot.png", show=DISPLAY_SUMMARY_PLOTS)

copy_if_exists(OUT_FIGURES / "true_std_vs_pred_std_best_val.png", OUT_FIGURES / "true_std_vs_pred_std.png")
copy_if_exists(OUT_FIGURES / "per_trait_mae_best_val.png", OUT_FIGURES / "per_trait_mae.png")
copy_if_exists(OUT_FIGURES / "per_trait_r2_best_val.png", OUT_FIGURES / "per_trait_r2.png")
copy_if_exists(OUT_FINAL_SELECTED / "best_val" / "hist_test_strict_pred_vs_true.png", OUT_FIGURES / "histogram_true_vs_pred_best_val.png")
copy_if_exists(OUT_FINAL_SELECTED / "best_val" / "scatter_test_strict_pred_vs_true.png", OUT_FIGURES / "scatter_true_vs_pred_best_val.png")

In [ ]:
# =========================
# WavLM-compatible posthoc diagnostics aliases
# =========================
section("Cell | Posthoc diagnostics aliases")

OUT_POSTHOC = OUTPUTS / "posthoc_diagnostics"
OUT_POSTHOC.mkdir(parents=True, exist_ok=True)

posthoc_alias_files = [
    # Loss diagnostics / overfit-underfit artifacts
    OUT_FINAL_AGG / "loss_diagnostic_summary_per_run.csv",
    OUT_FINAL_AGG / "train_val_gap_diagnostics.csv",
    OUT_FINAL_AGG / "all_final_histories_long.csv",
    OUT_FINAL_AGG / "all_runs_history_with_val_loss.csv",
    OUT_FINAL_AGG / "aggregate_loss_by_epoch.csv",
    OUT_FINAL_AGG / "aggregate_loss_curve_by_epoch.csv",
    OUT_FINAL_AGG / "aggregate_loss_curve.png",
    OUT_FINAL_AGG / "aggregate_train_vs_val_loss_mean_std.png",
    OUT_FINAL_AGG / "aggregate_train_val_gap_mean_std.png",
    OUT_FINAL_AGG / "all_runs_train_vs_val_loss_overlay.png",
    OUT_FINAL_AGG / "overfit_underfit_interpretation.txt",

    # R2 / regression-to-the-mean artifacts
    OUT_FINAL_AGG / "regression_to_mean_summary.csv",
    OUT_FINAL_AGG / "best_val_test_trait_summary.csv",
    OUT_FINAL_AGG / "best_val_test_bin_analysis.csv",
    OUT_FINAL_AGG / "best_val_test_residuals_long.csv",
    OUT_FINAL_AGG / "top20_worst_predictions.csv",
    OUT_FINAL_AGG / "top20_best_predictions.csv",

    # Figures
    OUT_FIGURES / "true_std_vs_pred_std_best_val.png",
    OUT_FIGURES / "true_std_vs_pred_std.png",
    OUT_FIGURES / "per_trait_mae_best_val.png",
    OUT_FIGURES / "per_trait_mae.png",
    OUT_FIGURES / "per_trait_r2_best_val.png",
    OUT_FIGURES / "per_trait_r2.png",
    OUT_FIGURES / "best_val_test_bin_analysis.png",
    OUT_FIGURES / "best_val_test_residual_boxplot.png",
    OUT_FIGURES / "histogram_true_vs_pred_best_val.png",
    OUT_FIGURES / "scatter_true_vs_pred_best_val.png",
]

copied_rows = []
for src in posthoc_alias_files:
    dst = OUT_POSTHOC / src.name
    copied = copy_if_exists(src, dst)
    copied_rows.append({
        "source": str(src.relative_to(ROOT)) if src.exists() else str(src),
        "alias_path": str(dst.relative_to(ROOT)),
        "source_exists": src.exists(),
        "copied": copied,
    })

posthoc_alias_df = pd.DataFrame(copied_rows)
save_csv(posthoc_alias_df, OUT_POSTHOC / "posthoc_alias_index.csv")
save_csv(posthoc_alias_df, OUT_TABLES / "posthoc_alias_index.csv")

display(posthoc_alias_df)
log_line(f"Posthoc alias folder prepared: {OUT_POSTHOC}", LIVE_LOG)

In [ ]:
# =========================
# Appendix-ready exports and artifact index
# =========================
section("Cell | Appendix-ready exports and artifact index")

# Copy selected prediction files.
copy_if_exists(OUT_FINAL_SELECTED / "best_val" / "predictions_test_strict.csv", OUT_APPENDIX / "appendix_best_val_predictions_test_strict.csv")
copy_if_exists(OUT_FINAL_SELECTED / "median" / "predictions_test_strict.csv", OUT_APPENDIX / "appendix_median_predictions_test_strict.csv")
copy_if_exists(OUT_FINAL_SELECTED / "ensemble" / "ensemble_predictions_test_strict.csv", OUT_APPENDIX / "appendix_ensemble_predictions_test_strict.csv")

# Copy core tables.
for src in [
    OUT_FINAL_AGG / "final_runs_summary.csv",
    OUT_FINAL_AGG / "final_stats_summary.csv",
    OUT_FINAL_AGG / "selected_runs_summary.json",
    OUT_FINAL_AGG / "train_val_gap_diagnostics.csv",
    OUT_FINAL_AGG / "r2_vs_mae_analysis.csv",
    OUT_OPTUNA_STUDY / "best_hp.csv",
    OUT_OPTUNA_STUDY / "optuna_top_trials.csv",
]:
    if src.exists():
        copy_if_exists(src, OUT_APPENDIX / f"appendix_{src.name}")

# Copy important figures.
important_figs = [
    OUT_OPTUNA_STUDY / "optuna_optimization_history.png",
    OUT_OPTUNA_STUDY / "optuna_param_importance.png",
    OUT_FINAL_AGG / "aggregate_loss_curve.png",
    OUT_FIGURES / "per_trait_mae_best_val.png",
    OUT_FIGURES / "per_trait_r2_best_val.png",
    OUT_FIGURES / "true_std_vs_pred_std_best_val.png",
    OUT_FIGURES / "best_val_test_bin_analysis.png",
    OUT_FIGURES / "best_val_test_residual_boxplot.png",
    OUT_FINAL_SELECTED / "best_val" / "hist_test_strict_pred_vs_true.png",
    OUT_FINAL_SELECTED / "best_val" / "scatter_test_strict_pred_vs_true.png",
    OUT_FINAL_SELECTED / "ensemble" / "hist_ensemble_pred_vs_true.png",
    OUT_FINAL_SELECTED / "ensemble" / "scatter_ensemble_pred_vs_true.png",
]
for src in important_figs:
    if src.exists():
        copy_if_exists(src, OUT_APPENDIX / src.name)

optuna_note = f"""
Optuna reproducibility note:
- N_TRIALS = {N_TRIALS}
- Remaining trials dihitung dari total len(study.trials), bukan jumlah COMPLETE.
- Sampler tidak dibuat eksplisit agar sesuai dengan notebook WavLM.
- Pruner = {PRUNER}
- Selection metric = validation S = 1 - MAE mean.
""".strip()

save_text(optuna_note, OUT_FINAL_AGG / "optuna_reproducibility_note.txt")
copy_if_exists(OUT_FINAL_AGG / "optuna_reproducibility_note.txt", OUT_APPENDIX / "appendix_optuna_reproducibility_note.txt")


strict_audit_csv = OUT_TABLES / "strict_split_leakage_audit.csv"
if strict_audit_csv.exists():
    audit_text = pd.read_csv(strict_audit_csv).to_string(index=False)
    save_text(audit_text, OUT_APPENDIX / "appendix_strict_split_leakage_audit.txt")


# Artifact index.
artifact_rows = []
for root_dir in [OUTPUTS, CHECKPOINTS, LOGS]:
    for p in root_dir.rglob("*"):
        if p.is_file():
            artifact_rows.append({
                "artifact": str(p.relative_to(ROOT)),
                "size_mb": round(p.stat().st_size / (1024**2), 4),
                "suffix": p.suffix,
            })
artifact_df = pd.DataFrame(artifact_rows).sort_values("artifact").reset_index(drop=True)
save_csv(artifact_df, OUT_APPENDIX / "artifact_index.csv")
display(artifact_df.tail(30))

log_line("Notebook completed successfully.", LIVE_LOG)
log_line(f"Appendix folder: {OUT_APPENDIX}", LIVE_LOG)